
##############################
# Country definition for ENG #
##############################

province =
{ id            = 5
  naval_base    = { size = 10 current_size = 10 }
  radar_station = { size = 3 current_size = 3 }
}                 # Scapa Flow
province =
{ id            = 6
  radar_station = { size = 1 current_size = 1 }
}                 # Inverness
province =
{ id            = 7
  naval_base    = { size = 5 current_size = 5 }
  radar_station = { size = 1 current_size = 1 }
}                 # Aberdeen
province =
{ id            = 8
  naval_base    = { size = 7 current_size = 7 }
  air_base      = { size = 8 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
}                 # Dunfermline
province =
{ id            = 9
  anti_air      = 3
  radar_station = { size = 3 current_size = 3 }
  ic            = 4
}                 # Glasgow
province =
{ id            = 10
  radar_station = { size = 4 current_size = 4 }
  ic            = 5
}                 # Edinburgh
province =
{ id            = 11
  naval_base    = { size = 6 current_size = 6 }
  air_base      = { size = 6 current_size = 6 }
  radar_station = { size = 4 current_size = 4 }
  ic            = 9
}                 # Sunderland
province =
{ id            = 12
  radar_station = { size = 2 current_size = 2 }
  ic            = 4
}                 # Blackpool
province =
{ id            = 13
  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 6 current_size = 6 }
  ic            = 9
}                 # Sheffield
province =
{ id            = 14
  anti_air      = 6
  naval_base    = { size = 10 current_size = 10 }
  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
  ic            = 10
}                 # Liverpool
province =
{ id            = 15
  radar_station = { size = 4 current_size = 4 }
}                 # Cardiff
province =
{ id            = 16
  anti_air      = 6
  radar_station = { size = 2 current_size = 2 }
  rocket_test   = { size = 2 current_size = 2 }
  ic            = 10
}                 # Birmingham
province =
{ id            = 17
  anti_air      = 6
  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 7 current_size = 7 }
}                 # Norwich
province =
{ id            = 19
  anti_air      = 9
  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 4 current_size = 4 }
  ic            = 10
}                 # London
province =
{ id            = 20

  coastalfort   = 9
  anti_air      = 6
  air_base      = { size = 5 current_size = 5 }
  radar_station = { size = 8 current_size = 8 }
}                 # Dover
province =
{ id            = 21
  anti_air      = 6
  naval_base    = { size = 5 current_size = 5 }
  air_base      = { size = 8 current_size = 8 }
  radar_station = { size = 8 current_size = 8 }
}                 # Portsmouth
province =
{ id            = 22
  radar_station = { size = 5 current_size = 5 }
}                 # Bristol
province =
{ id            = 23
  anti_air      = 6
  naval_base    = { size = 3 current_size = 3 }
  air_base      = { size = 8 current_size = 8 }
  radar_station = { size = 7 current_size = 7 }
}                 # Plymouth
province =
{ id            = 28
  naval_base    = { size = 3 current_size = 3 }
  air_base      = { size = 8 current_size = 8 }
  radar_station = { size = 1 current_size = 1 }
  oilpool       = 1000
  supplypool    = 2000
}                 # Belfast
province =
{ id            = 31

  coastalfort   = 3
  naval_base    = { size = 6 current_size = 6 }
  air_base      = { size = 6 current_size = 6 }
  radar_station = { size = 2 current_size = 2 }
  oilpool       = 1000
  supplypool    = 1000
}                 # Malta
province =
{ id            = 348
  landfort      = 10
  coastalfort   = 0
  anti_air      = 6
  naval_base    = { size = 4 current_size = 4 }
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 2 current_size = 2 }
  supplypool    = 1000
  oilpool       = 1000
}                 # Gibraltar
province =
{ id         = 404
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Haifa
province =
{ id         = 406
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Eilat
province =
{ id         = 444
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Cyprus
province =
{ id         = 538
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id            = 576
  naval_base    = { size = 4 current_size = 4 }
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 1 current_size = 1 }
}                 # Newfoundland
province =
{ id         = 668
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Long Island
province = { id = 866 oilpool = 100 supplypool = 200 } # Falkland Islands
province = { id = 900 anti_air = 6 } # Suez
province =
{ id         = 901
  anti_air   = 6
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
  oilpool    = 1000
  supplypool = 2000
}              # Port Said
province = { id = 903 anti_air = 6 } # Cairo
province =
{ id         = 906
  anti_air   = 6
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 5000
  oilpool    = 2000
}              # Alexandria
province =
{ id         = 919
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Tobruk
province =
{ id         = 923
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Barca
province =
{ id         = 933
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Zuara
province =
{ id         = 988
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
  oilpool    = 1000
  supplypool = 2000
}              # Freetown
province =
{ id         = 1033
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Massaua
province =
{ id         = 1056
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Mogadishu
province =
{ id       = 1287
  air_base = { size = 5 current_size = 5 }
}            # Imphal
province =
{ id       = 1296
  air_base = { size = 5 current_size = 5 }
}            # Mandalay
province =
{ id         = 1299
  anti_air   = 3
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 5 current_size = 5 }
}              # Rangoon
province = { id = 1315 coastalfort = 9 anti_air = 6 oilpool = 1000 supplypool = 1000 } # Hong Kong
province =
{ id          = 1353

  coastalfort = 9
  anti_air    = 6
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 5 current_size = 5 }
  oilpool     = 1000
  supplypool  = 2000
}               # Singapore
province =
{ id         = 1457
  anti_air   = 3
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
  ic         = 3
}              # Calcutta
province = { id = 1459 oilpool = 1500 supplypool = 2500 } # Ranchi
province = { id = 1464 ic = 2 } # Surat
province = { id = 1465 ic = 2 } # Rajkot
province =
{ id         = 1466
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
}              # Ahmadabad
province = { id = 1469 anti_air = 3 ic = 10 } # Delhi
province = { id = 1478 ic = 3 } # Bikaner
province = { id = 1479 ic = 3 } # Jodhpur
province = { id = 1494 ic = 2 } # Karachi
province = { id = 1505 ic = 2 supplypool = 2000 oilpool = 1000 } # Bombay
province = { id = 1513 ic = 2 } # Mangalore
province =
{ id            = 1516
  naval_base    = { size = 4 current_size = 4 }
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 2 current_size = 2 }
}                 # Trincomalee
province =
{ id          = 1517

  coastalfort = 9
  naval_base  = { size = 7 current_size = 7 }
  air_base    = { size = 7 current_size = 7 }
  oilpool     = 1000
  supplypool  = 2000
}               # Colombo
province =
{ id         = 1646
  naval_base = { size = 10 current_size = 10 }
}              # Miri
province = { id = 1797 anti_air = 3 } # Jerusalem
province =
{ id         = 1813
  naval_base = { size = 2 current_size = 2 }
}              # Aden
province =
{ id         = 1814
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # Mukalla
province =
{ id         = 1816
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # The Seychelles
province =
{ id         = 1817
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
  oilpool    = 100
  supplypool = 200
}              # Diego Garcia Island
province =
{ id         = 1822
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Kuweit City

#####################
# Country main data #
#####################

country =
{ tag                    = ENG
  capital                = 19
  belligerence           = 10
  manpower               = 485
  transports             = 1671
  escorts                = 250
  # Resource Reserves
  energy                 = 65000
  metal                  = 65000
  rare_materials         = 5000
  oil                    = 6000
  supplies               = 6000
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 10
    free_market       = 8
    professional_army = 7
    defense_lobby     = 7
    interventionism   = 6
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 14 }
  #SpyInfo                = { country = "GER" NumberOfSpies = 1}
  #SpyInfo                = { country = "VIC" NumberOfSpies = 6}
  #SpyInfo                = { country = "SOV" NumberOfSpies = 7}
  #SpyInfo                = { country = "SPA" NumberOfSpies = 5}
  #SpyInfo                = { country = "POL" NumberOfSpies = 7}
  #SpyInfo                = { country = "SWE" NumberOfSpies = 6}
  #SpyInfo                = { country = "NOR" NumberOfSpies = 1}
  #SpyInfo                = { country = "FIN" NumberOfSpies = 6}
  #SpyInfo                = { country = "YUG" NumberOfSpies = 7}
  #SpyInfo                = { country = "HUN" NumberOfSpies = 6}
  #SpyInfo                = { country = "BUL" NumberOfSpies = 6}
  #SpyInfo                = { country = "BEL" NumberOfSpies = 7}
  #SpyInfo                = { country = "DEN" NumberOfSpies = 5}
  #SpyInfo                = { country = "HOL" NumberOfSpies = 7}
  #SpyInfo                = { country = "USA" NumberOfSpies = 1}
  #SpyInfo                = { country = "ALB" NumberOfSpies = 5}
  #SpyInfo                = { country = "GRE" NumberOfSpies = 5}
  #SpyInfo                = { country = "ARG" NumberOfSpies = 5}
  #SpyInfo                = { country = "BRA" NumberOfSpies = 5}
  #SpyInfo                = { country = "JAP" NumberOfSpies = 5}
  #SpyInfo                = { country = "ROM" NumberOfSpies = 6}
  #SpyInfo                = { country = "LIT" NumberOfSpies = 6}
  #SpyInfo                = { country = "FRA" NumberOfSpies = 5}
  #SpyInfo                = { country = "POR" NumberOfSpies = 5}
  #SpyInfo                = { country = "ITA" NumberOfSpies = 6}
  #SpyInfo                = { country = "CHI" NumberOfSpies = 1}
  #SpyInfo                = { country = "MEX" NumberOfSpies = 5}
  #SpyInfo                = { country = "AST" NumberOfSpies = 6}
  #SpyInfo                = { country = "NZL" NumberOfSpies = 6}
  #SpyInfo                = { country = "CAN" NumberOfSpies = 6}
  #SpyInfo                = { country = "IRE" NumberOfSpies = 1}
  #SpyInfo                = { country = "IRQ" NumberOfSpies = 7}
  #SpyInfo                = { country = "BHU" NumberOfSpies = 5}
  #SpyInfo                = { country = "YEM" NumberOfSpies = 5}
  #SpyInfo                = { country = "ETH" NumberOfSpies = 5}
  # GREAT BRITAIN
  nationalprovinces      = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   1494
			     1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459 1457
			     1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288 1289
			     1290 1291 1898 1304 1295 1296 1302 1346 1299 1298 1297 1300 1292 1303 1454 575  576  444
			   }
  # GREAT BRITAIN
  ownedprovinces         = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444
			     1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
			     1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288
			     1289 1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1297 1300 1292 1454 1799 1797 1796 404  1802 1803 406  407
			     1813 1814 1820 1504 1798 900  901  902  903  904  905  906  907  908  909  910  911  912  913  914  915  4    1020 1019
			     1021 1022 1027 1023 1026 1024 1025 1800 1801 927  933  932  930  929  925  924  923  922  921  920  919  916  917  918
			     926  928  931  1017 1018 1016 1015 1033 1039 1038 1034 1055 1056 1058 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030
			     1040 1041 1349 1350 1351 1352 1353 1644 1646 1647 1315 758  891  871  873  806  807  808  809  897  538  652  653  664
			     665  666  668  805  896  866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1112
			     1111 1105 1124 1125 1104 1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085 1012 988  982  1877
			     1878 801  874  575  576  1822
			   }
  # GREAT BRITAIN
  controlledprovinces    = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444
			     1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
			     1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1284 1285 1286 1287 1288 1289 1291
			     1898 1454 1799 1797 1796 404  1802 1803 406  407  1813 1814 1504 1798 900  901  902  903  904  905  906  907  908  909
			     910  911  912  913  914  915  4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1800 1801 1065 1066 1069 1068 1067 1029
			     1028 1032 1031 1030 1040 1041 758  891  871  873  806  807  808  809  897  538  652  653  664  665  666  668  805  896
			     866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1112 1111 1105 1124 1125 1104
			     1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085 1012 988  982  525  526  524  523  522  521
			     520  519  518  517  516  515  534 927  933  932  930  929  925  924  923  922  921  920  919  916  917  918
			     926  928  931  1017 1018 1016 1015 1033 1039 1038 1034 1055 1056 1058 1877 1878 801  874  575  576  1822 1820
			   }
  # Commonwealth Tech '36
  # UK 1944 techs
  # ######################
  techapps               = { 1010  1020  1030  1040  1040  1050  1070  1080  1090  1100  1110  1120  1130  1140  1150  1160  1170  1180  1190  1200
			     1210  1220  1230  1240  1250  1260  1270  1280  1310  1320  1330  1340  1350  1360  14000 14010 14020 2010  2020  2030
			     2040  2050  2060  2070  2080  2090  2100  2110  2120  2150  2160  2170  2180  2190  2220  2230  2240  2260  2270  2290
			     2300  2310  2320  2330  2340  2350  2360  2370  2380  2400  2410  2420  2430  2450  2460  2470  2480  2490  2510  2520
			     2530  3010  3020  3030  3040  3070  3080  3090  3100  3110  3130  3140  3150  3190  3200  3210  3250  3260  3270  3280
			     3320  3330  3340  3350  3360  3370  3400  3410  3420  3430  4010  4020  4030  4040  4050  4060  4070  4080  4090  4100
			     4110  4120  4130  4140  4150  4160  4170  4180  4190  4200  4210  4220  4230  4240  4250  4260  4280  5010  5020  5030
			     5050  5060  5070  5080  5090  5100  5110  5120  5130  5140  5160  5180  5190  5200  5210  5220  5230  5310  5320  5330
			     5340  5350  5360  5370  5380  5390  5400  5410  5420  5430  5440  5450  5470  5480  5490  5500  5510  5550  5560  5570
			     6010  6030  6110  6120  6130  6140  6170  6200  7140  7150  8010  8020  8030  8040  8050  8070  8090  8100  8110
			     8120  8130  8140  8160  8190  8200  8250  8310  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110  9120
			     9130  9140  9150  9160  9170  9180  9190  9200  9210  9220  9230  9240  9250  9260  9270  9280  9290  9300  9310  9320
			     9330  9340  9350  9360  9370  9380  9390  9400  9410  9420  9430  9440  9450  9460  12100 12110 12120
			   }
  inventions             = { 8001 8010 }
  diplomacy =
  { relation = { tag = CHI value = 50 }
    relation = { tag = AFG value = -75 }
    relation = { tag = ARG value = 75 }
    relation = { tag = AST value = 200 access = yes }
    relation = { tag = BEL value = 200 }
    relation = { tag = BHU value = 200 access = yes }
    relation = { tag = BUL value = -200 }
    relation = { tag = CAN value = 200 access = yes }
    relation = { tag = FIN value = -200 }
    relation = { tag = FRA value = 200 }
    relation = { tag = GER value = -200 }
    relation = { tag = GUA value = 50 }
    relation = { tag = HUN value = -200 }
    relation = { tag = IRE value = 50 }
    relation = { tag = MEX value = 50 }
    relation = { tag = NEP value = 200 access = yes }
    relation = { tag = NZL value = 200 access = yes }
    relation = { tag = OMN value = 150 access = yes }
    relation = { tag = PER value = 100 }
    relation =
    { tag        = POR
      value      = 100
      guaranteed = { day = 22 month = may year = 1942 }
    }
    relation = { tag = ROM value = -200 }
    relation = { tag = SAF value = 200 access = yes }
    relation =
    { tag        = SAU
      value      = 100
      guaranteed = { day = 11 month = february year = 1942 }
    }
    relation =
    { tag        = SCH
      value      = 50
      guaranteed = { day = 19 month = april year = 1942 }
    }
    relation = { tag = SIA value = 70 }
    relation = { tag = SOV value = 200 }
    relation = { tag = SWE value = 80 }
    relation =
    { tag        = TUR
      value      = 75
      guaranteed = { day = 17 month = may year = 1941 }
    }
    relation = { tag = USA value = 200 }
    relation = { tag = VEN value = -10 }
    relation =
    { tag        = YEM
      value      = 150
      guaranteed = { day = 11 month = february year = 1942 }
      access     = yes
    }
    relation = { tag = HON value = 50 }
    relation = { tag = SPA value = -65 }
  }
  dormant_ministers      = { 1001 1031 1002 1004 1005 1081 1006 1007 1008 1127 1128 1009 1137 1010 1037 1045 1117 1129 1132 1149 1140 1082 1119 1132
			     1062 1163 1173 1174
			   }
  headofstate            = { type = 9 id = 1033 }
  headofgovernment       = { type = 9 id = 1038 }
  foreignminister        = { type = 9 id = 1003 }
  armamentminister       = { type = 9 id = 1063 }
  ministerofsecurity     = { type = 9 id = 1088 }
  ministerofintelligence = { type = 9 id = 1103 }
  chiefofstaff           = { type = 9 id = 1120 }
  chiefofarmy            = { type = 9 id = 1130 }
  chiefofnavy            = { type = 9 id = 1138 }
  chiefofair             = { type = 9 id = 1147 }
  landunit =
  { location = 20
    id       = { type = 10499 id = 1 }
    name     = "Aldershot Command"
    division =
    { experience = 30
      id         = { type = 10499 id = 2 }
      name       = "2nd Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 3 }
      name       = "6th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 4 }
      name       = "76th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 23
    id       = { type = 10499 id = 5 }
    name     = "Eastern Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 6 }
      name          = "12th 'Eastern' Motorized Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 7 }
      name       = "44th 'Home Counties' Motorized Div."
      type       = motorized
      model      = 2
      strength   = 100
      extra      = engineer
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 8 }
      name       = "54th 'East Anglia' Motorized Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 9 }
      name       = "77th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 19
    id       = { type = 10499 id = 10 }
    name     = "London District"
    division =
    { experience = 30
      id         = { type = 10499 id = 705 }
      name       = "Homeguard HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 11 }
      name          = "47th 'London' Motorized Infantry Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
  }
  landunit =
  { location = 8
    id       = { type = 10499 id = 12 }
    name     = "Scottish Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 13 }
      name          = "9th 'Scottish' Motorized Infantry Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = anti_tank
      brigade_model = 3
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 14 }
      name          = "15th 'Scottish' Motorized Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = anti_tank
      brigade_model = 3
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 15 }
      name          = "52nd 'Lowlands' Motorized Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { location = 21
    id       = { type = 10499 id = 16 }
    name     = "Southern Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 17 }
      name          = "48th 'South Midlands' Motorized Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 18 }
      name       = "61st Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 19 }
      name          = "43rd 'Wessex' Motorized Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 20 }
      name       = "45th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 21 }
      name       = "7th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 22 }
      name       = "10th Armoured Division"
      type       = armor
      model      = 3
      strength   = 100
    }
  }
  landunit =
  { location = 14
    id       = { type = 10499 id = 23 }
    name     = "Western Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 24 }
      name          = "55th 'West Lancashire' Motorized Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 25 }
      name          = "42nd 'East Lancashire' Motorized Div."
      type          = motorized
      model         = 2
      strength      = 100
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 26 }
      name       = "66th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 27 }
      name       = "38th 'Welsh' Motorized Div."
      type       = motorized
      model      = 2
      strength   = 100
      extra      = engineer
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 28 }
      name       = "53rd 'Welsh' Motorized Div."
      type       = motorized
      model      = 2
      strength   = 80
      extra      = engineer
    }
  }
  landunit =
  { location = 16
    id       = { type = 10499 id = 29 }
    name     = "Mobile Defense Corps"
    division =
    { experience    = 30
      id            = { type = 10499 id = 30 }
      name          = "8th Armoured Division"
      type          = armor
      model         = 3
      strength      = 100
      extra         = sp_artillery
      brigade_model = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 31 }
      name       = "9th Armoured Division"
      type       = armor
      model      = 3
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 32 }
      name       = "8th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 33 }
      name       = "10th Motorized Infantry Div."
      type       = motorized
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 1043
    id       = { type = 10499 id = 37 }
    name     = "East African Command"
    division =
    { experience = 30
      id         = { type = 10499 id = 38 }
      name       = "1st African Division"
      type       = infantry
      model      = 4
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 39 }
      name       = "2nd African Division"
      type       = infantry
      model      = 4
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 40 }
      name       = "11th (East African) Division"
      type       = infantry
      model      = 4
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 41 }
      name       = "12th African Division"
      type       = infantry
      model      = 4
      strength   = 100
    }
  }
  landunit =
  { location = 348
    id       = { type = 10499 id = 42 }
    name     = "Gibraltar Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 43 }
      name          = "Gibraltar Defence Force"
      type          = infantry
      model         = 4
      strength      = 100
      extra         = anti_air
      brigade_model = 2
      locked        = yes
    }
  }
  landunit =
  { location = 31
    id       = { type = 10499 id = 44 }
    name     = "Malta Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 45 }
      name          = "Malta Defence Force"
      type          = infantry
      model         = 4
      strength      = 100
      extra         = anti_air
      brigade_model = 2
      locked        = yes
    }
  }
  landunit =
  { location = 444
    id       = { type = 10499 id = 46 }
    name     = "Cyprus Command"
    division =
    { experience = 30
      id         = { type = 10499 id = 47 }
      name       = "Cyprus Defence Force"
      type       = garrison
      model      = 1
      strength   = 100
      locked     = yes
    }
  }
  # #############################
  # #UK Forces in India##########
  # #############################
  landunit =
  { location = 1288
    id       = { type = 10499 id = 706 }
    name     = "14th Army HQ"
    division =
    { experience = 30
      id         = { type = 10499 id = 707 }
      name       = "14th Army HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 1288
    id       = { type = 10499 id = 48 }
    name     = "IV Corps"
    division =
    { experience    = 30
      id            = { type = 10499 id = 49 }
      name          = "1st Indian Infantry"
      type          = infantry
      model         = 4
      strength      = 100
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 54 }
      name       = "6th Indian Infantry"
      type       = infantry
      model      = 4
      strength   = 100
      extra      = engineer
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 55 }
      name       = "7th Indian Infantry"
      type       = infantry
      model      = 4
      strength   = 100
      extra      = engineer
    }
  }
  landunit =
  { location = 1287
    id       = { type = 10499 id = 50 }
    name     = "XXIII Corps"
    division =
    { experience    = 30
      id            = { type = 10499 id = 51 }
      name          = "2nd Indian Infantry"
      type          = infantry
      model         = 4
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 52 }
      name       = "3rd Indian Infantry"
      type       = infantry
      model      = 4
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 53 }
      name       = "1st Burmese Infantry"
      type       = infantry
      model      = 4
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 287 }
      name       = "7th Gurka/5037 Comp"
      type       = bergsjaeger
      model      = 3
      extra      = engineer
      strength   = 100
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 286 }
      name          = "2nd Infantry Division"
      type          = infantry
      model         = 4
      extra         = artillery
      brigade_model = 5
      strength      = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 285 }
      name       = "50/254th Tank Brigade"
      type       = armor
      model      = 3
      strength   = 100
    }
  }
  landunit =
  { location = 1291
    id       = { type = 10499 id = 56 }
    name     = "NCAC"
    division =
    { experience = 30
      id         = { type = 10499 id = 57 }
      name       = "36th Infantry Division"
      type       = infantry
      model      = 4
      strength   = 100
      extra      = artillery
    }
  }
  # ####################################
  # #UK Colonial Forces in East Africa##
  # ####################################
  landunit =
  { name     = "1st Sudanese Colonials"
    location = 1028
    id       = { type = 10499 id = 58 }
    division =
    { experience = 30
      id         = { type = 10499 id = 59 }
      name       = "1st Sudanese Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "2nd Sudanese Colonials"
    location = 1023
    id       = { type = 10499 id = 60 }
    division =
    { experience = 30
      id         = { type = 10499 id = 61 }
      name       = "2nd Sudanese Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "3rd Sudanese Colonials"
    location = 1040
    id       = { type = 10499 id = 62 }
    division =
    { experience = 30
      id         = { type = 10499 id = 63 }
      name       = "3rd Sudanese Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "1st Ugandan Colonials"
    location = 1061
    id       = { type = 10499 id = 64 }
    division =
    { experience = 30
      id         = { type = 10499 id = 65 }
      name       = "1st Ugandan Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "2nd Ugandan Colonials"
    location = 1062
    id       = { type = 10499 id = 66 }
    division =
    { experience = 30
      id         = { type = 10499 id = 67 }
      name       = "2nd Ugandan Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "1st Kenyan Colonials"
    location = 1139
    id       = { type = 10499 id = 68 }
    division =
    { experience = 30
      id         = { type = 10499 id = 69 }
      name       = "1st Kenyan Colonialss"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "2nd Kenyan Colonials"
    location = 1140
    id       = { type = 10499 id = 70 }
    division =
    { experience = 30
      id         = { type = 10499 id = 71 }
      name       = "2nd Kenyan Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "1st Tanganyikan Colonials"
    location = 1036
    id       = { type = 10499 id = 72 }
    division =
    { experience = 30
      id         = { type = 10499 id = 73 }
      name       = "1st Tanganyikan Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  landunit =
  { name     = "2nd Tanganyikan Colonials"
    location = 1069
    id       = { type = 10499 id = 74 }
    division =
    { experience = 30
      id         = { type = 10499 id = 75 }
      name       = "2nd Tanganyikan Colonials"
      type       = militia
      model      = 1
      strength   = 100
    }
  }
  # ##MEDITERRANEAN TOE###
  landunit =
  { id       = { type = 10499 id = 110 }
    name     = "9th Army"
    location = 404
    division =
    { experience = 30
      id         = { type = 10499 id = 111 }
      name       = "31st Indian Armoured Division"
      strength   = 100
      type       = armor
      model      = 3
    }
  }
  # ##MIDDLE EASTERN TOE###
  landunit =
  { id       = { type = 10499 id = 112 }
    name     = "PAI Force"
    location = 1790
    division =
    { experience = 30
      id         = { type = 10499 id = 113 }
      name       = "6th Indian Motorized Div."
      strength   = 100
      type       = motorized
      model      = 2
    }
  }
  # ##UNITED KINGDOM TOE###
  landunit =
  { id       = { type = 10499 id = 114 }
    name     = "Home Forces"
    location = 10
    division =
    { experience = 30
      id         = { type = 10499 id = 115 }
      name       = "4th Polish Motorized Div."
      strength   = 100
      type       = motorized
      model      = 2
    }
  }
  # ##ITALY TOE###
  landunit =
  { location = 517
    id       = { type = 10499 id = 708 }
    name     = "8th Army HQ"
    division =
    { experience = 30
      id         = { type = 10499 id = 709 }
      name       = "8th Army HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { id       = { type = 10499 id = 76 }
    name     = "XIII. Corps"
    location = 517
    division =
    { experience    = 30
      id            = { type = 10499 id = 77 }
      name          = "1st Motorized Infantry Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 78 }
      name       = "6th Armoured Division"
      strength   = 100
      type       = armor
      model      = 3
      extra      = engineer
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 79 }
      name          = "8th Indian Motorized Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { id       = { type = 10499 id = 80 }
    name     = "X. Corps"
    location = 516
    division =
    { experience    = 30
      id            = { type = 10499 id = 81 }
      name          = "10th Indian Motorized Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { id       = { type = 10499 id = 82 }
    name     = "V. Corps"
    location = 517
    division =
    { experience    = 30
      id            = { type = 10499 id = 83 }
      name          = "1st Armoured Div. 'Royal Hussars'"
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 3
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 84 }
      name          = "4th Motorized Infantry Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 85 }
      name          = "4th Indian Motorized Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 86 }
      name          = "5th Motorized Infantry Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 87 }
      name          = "46th 'North Midlands' Motorized Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 88 }
      name       = "56th 'London' Motorized Div."
      strength   = 100
      type       = motorized
      model      = 2
    }
  }
  landunit =
  { id       = { type = 10499 id = 89 }
    name     = "1st Airborne Division"
    location = 519
    division =
    { experience = 30
      id         = { type = 10499 id = 90 }
      name       = "1st Airborne Division"
      strength   = 100
      type       = paratrooper
      model      = 3
    }
  }
  landunit =
  { id       = { type = 10499 id = 91 }
    name     = "2nd Polish Corps"
    location = 516
    division =
    { experience = 30
      id         = { type = 10499 id = 92 }
      name       = "3rd 'Carpathia' Division"
      strength   = 100
      type       = motorized
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 93 }
      name       = "5th 'Krestowa' Division"
      strength   = 100
      type       = motorized
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 94 }
      name       = "2nd 'Warsawa' Division"
      strength   = 100
      type       = motorized
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 95 }
      name       = "1st Polish Armoured Division"
      strength   = 100
      type       = armor
      model      = 3
    }
  }
  # ##NORMANDY TOE###
  landunit =
  { location = 39
    id       = { type = 10499 id = 710 }
    name     = "21st Army Group HQ"
    division =
    { experience = 30
      id         = { type = 10499 id = 711 }
      name       = "21st Army Group HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 39
    id       = { type = 10499 id = 712 }
    name     = "2nd Army HQ"
    division =
    { experience = 30
      id         = { type = 10499 id = 713 }
      name       = "2nd Army HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { id       = { type = 10499 id = 116 }
    name     = "I. Corps"
    location = 39
    division =
    { experience = 30
      id         = { type = 10499 id = 117 }
      name       = "3rd Motorized Infantry Div.H"
      strength   = 100
      type       = motorized
      model      = 2
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 118 }
      name          = "51st 'Highland' Motorized Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { id       = { type = 10499 id = 119 }
    name     = "6th Airborne Division"
    location = 39
    division =
    { experience = 30
      id         = { type = 10499 id = 120 }
      name       = "6th Airborne Division"
      strength   = 100
      type       = paratrooper
      model      = 3
    }
  }
  landunit =
  { id       = { type = 10499 id = 121 }
    name     = "III. Corps"
    location = 39
    division =
    { experience = 30
      id         = { type = 10499 id = 122 }
      name       = "50th 'Northumbrian' Motorized Div."
      strength   = 100
      type       = motorized
      model      = 2
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 123 }
      name          = "49th 'West Riding' Motorized Div."
      strength      = 100
      type          = motorized
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 124 }
      name          = "7th Armoured Division"
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 3
    }
  }
  # #########NA theatre########
  landunit =
  { location = 915
    id       = { type = 10499 id = 288 }
    name     = "8th Army"
    division =
    { experience = 30
      id         = { type = 10499 id = 289 }
      name       = "70th Infantry Division"
      type       = motorized
      model      = 2
      strength   = 100
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 290 }
      name       = "2nd Armoured Division"
      type       = armor
      model      = 3
      strength   = 100
    }
  }
  landunit =
  { location = 919
    id       = { type = 10499 id = 291 }
    name     = "Tobruk Garrison"
    division =
    { experience = 30
      id         = { type = 10499 id = 292 }
      name       = "11th (Indian) Division"
      type       = infantry
      model      = 4
      strength   = 100
    }
  }
  # ##########iraq###########
  landunit =
  { location = 1823
    id       = { type = 10499 id = 293 }
    name     = "PAI Force"
    division =
    { experience    = 30
      id            = { type = 10499 id = 294 }
      name          = "12th Indian Infantry"
      type          = infantry
      model         = 4
      extra         = anti_tank
      brigade_model = 3
    }
    # ########### anti_tank = indian 2nd armored bgd############
    division =
    { experience = 30
      id         = { type = 10499 id = 295 }
      name       = "13th Indian Infantry"
      type       = infantry
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 296 }
      name       = "14th Indian Infantry"
      type       = infantry
      model      = 4
    }
  }
  landunit =
  { location = 988
    id       = { type = 10499 id = 297 }
    name     = "West Africa GHQ"
    # ##########nigeria, west africa###########
    division =
    { experience = 30
      id         = { type = 10499 id = 298 }
      name       = "1st West African Division"
      type       = militia
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 299 }
      name       = "2nd West African Division"
      type       = militia
      model      = 1
    }
  }
  landunit =
  { location = 348
    id       = { type = 10499 id = 645 }
    name     = "Gibraltar Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 646 }
      name          = "Gibraltar Defence Force"
      type          = garrison
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
  }
  landunit =
  { location = 31
    id       = { type = 10499 id = 647 }
    name     = "Malta Command"
    division =
    { experience    = 30
      id            = { type = 10499 id = 648 }
      name          = "Malta Defence Force"
      type          = garrison
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
  }
  landunit =
  { location = 1517
    id       = { type = 10499 id = 649 }
    name     = "Ceylon Command"
    division =
    { experience = 30
      id         = { type = 10499 id = 654 }
      name       = "Ceylon Defence Force"
      type       = garrison
      model      = 1
      strength   = 100
    }
  }
  # ##########################
  # Revised OOB for UK - 1944 Scenario
  # By 2Coats
  # ##########################
  # ##################################################################################################
  # Active Fleets
  # ##################################################################################################
  # #################
  # Home Fleet#
  navalunit =
  { name     = "Home Fleet"
    id       = { type = 10499 id = 400 }
    location = 5 # Scapa Flow
    base     = 5 # Scapa Flow
    division =
    { experience    = 30
      id            = { type = 10499 id = 572 }
      name          = "HMS Argus"
      type          = escort_carrier
	model = 0
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 800 }
      name          = "HMS Furious"
      type          = carrier
      extra         = cag
      model         = 1
      brigade_model = 4
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 801 }
      name          = "HMS Formidable"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 402 }
      name       = "HMS Duke of York"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 403 }
      name       = "HMS Berwick"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 404 }
      name       = "HMS Kent"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 405 }
      name       = "HMS Jamaica"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 406 }
      name       = "HMS Sheffield"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 407 }
      name       = "HMS Devonshire"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 409 }
      name       = "1st Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 410 }
      name       = "2nd Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 411 }
      name       = "3rd Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 412 }
      name       = "4th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 413 }
      name       = "5th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
  }
  # #################
  # Reserve Fleet - Clyde#
  navalunit =
  { name     = "Reserve Fleet"
    id       = { type = 10499 id = 420 }
    location = 28 # Glasgow
    base     = 28
    division =
    { experience    = 30
      id            = { type = 10499 id = 811 }
      name          = "HMS Unicorn"
      type          = escort_carrier
      model         = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 812 }
      name       = "HMS Anson"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 813 }
      name       = "HMS Howe"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 814 }
      name       = "HMS King George V"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 422 }
      name       = "HMS Resolution"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 423 }
      name       = "HMS Revenge"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 424 }
      name       = "HMS Royal Sovereign"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 815 }
      name       = "HMS Effingham"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 816 }
      name       = "HMS Norfolk"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 425 }
      name       = "HMS Cardiff"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 426 }
      name       = "HMS Capetown"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 427 }
      name       = "HMS Dauntless"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 817 }
      name       = "HMS Carlisle"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 818 }
      name       = "HMS Diomede"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 428 }
      name       = "HMS Liverpool"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 822 }
      name       = "HMS Bermuda"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 823 }
      name       = "HMS Birmingham"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 824 }
      name       = "HMS Newfoundland"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 825 }
      name       = "HMS Uganda"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 819 }
      name       = "HMS Cleopatra"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 820 }
      name       = "HMS Euryalus"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 821 }
      name       = "HMS Leander"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 433 }
      name       = "HMS Bellona"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 430 }
      name       = "6th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 431 }
      name       = "7th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ######################
  # Mediterrean Fleet#
  navalunit =
  { name     = "Mediterranean Fleet"
    id       = { type = 10499 id = 440 }
    location = 906 # Alexandria
    base     = 906
    division =
    { experience = 30
      id         = { type = 10499 id = 441 }
      name       = "HMS Dido"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 442 }
      name       = "HMS Phoebe"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 453 }
      name       = "HMS Royalist"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 443 }
      name       = "8th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 444 }
      name       = "9th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 445 }
      name       = "10th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 448 }
      name       = "11th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 449 }
      name       = "12th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 450 }
      name       = "13th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 451 }
      name       = "14th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ###########################
  # Eastern Overlord - Normandy Taskforce#
  navalunit =
  { name     = "Force A"
    id       = { type = 10499 id = 460 }
    location = 21 # Southampton
    base     = 21
    division =
    { experience = 30
      id         = { type = 10499 id = 461 }
      name       = "HMS Warspite"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 462 }
      name       = "HMS Ramillies"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 463 }
      name       = "HMS Malaya"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 464 }
      name       = "HMS Rodney"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 465 }
      name       = "HMS Nelson"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 466 }
      name       = "HMS Danae"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 467 }
      name       = "HMS Hawkins"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 468 }
      name       = "HMS Frobisher"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 469 }
      name       = "HMS Arethusa"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 470 }
      name       = "HMS Emerald"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 471 }
      name       = "HMS Enterprise"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 472 }
      name       = "HMS Despatch"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 474 }
      name       = "HMS Dragon"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 475 }
      name       = "HMS Ajax"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 476 }
      name       = "HMS Orion"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 477 }
      name       = "HMS Glasgow"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 478 }
      name       = "HMS Belfast"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 480 }
      name       = "HMS Scylla"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 481 }
      name       = "HMS Sirius"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 482 }
      name       = "HMS Mauritius"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 483 }
      name       = "HMS Ceres"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 484 }
      name       = "HMS Argonaut"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 485 }
      name       = "HMS Black Prince"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 486 }
      name       = "HMS Diadem"
      type       = light_cruiser
      model      = 2
    }
  }
  # ###########################
  # Western Aprroaches#
  navalunit =
  { name     = "1st Escort Group"
    id       = { type = 10499 id = 490 }
    location = 14 # Manchester
    base     = 14
    division =
    { experience = 30
      id         = { type = 10499 id = 493 }
      name       = "15th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 494 }
      name       = "16th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
  }
  # ###########################
  # Portsmouth#
  navalunit =
  { name     = "1st Destroyer Squadron"
    id       = { type = 10499 id = 500 }
    location = 23 # Portsmouth
    base     = 23
    division =
    { experience = 30
      id         = { type = 10499 id = 501 }
      name       = "17th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 502 }
      name       = "18th Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
  }
  # ###########################
  # Plymouth#
  navalunit =
  { name     = "2nd Escort Group"
    id       = { type = 10499 id = 510 }
    location = 21 # Plymouth
    base     = 21
    division =
    { experience = 30
      id         = { type = 10499 id = 511 }
      name       = "HMS Colombo"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 512 }
      name       = "19th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 513 }
      name       = "20th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ###########################
  # Rosyth#
  navalunit =
  { name     = "Rosyth Escort Force"
    id       = { type = 10499 id = 520 }
    location = 7 # Edinburgh
    base     = 7
    division =
    { experience = 30
      id         = { type = 10499 id = 524 }
      name       = "21st Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ###########################
  # Sheerness, Kent#
  navalunit =
  { name     = "2nd Destroyer Squadron"
    id       = { type = 10499 id = 530 }
    location = 23 # Portsmouth
    base     = 23
    division =
    { experience = 30
      id         = { type = 10499 id = 531 }
      name       = "22nd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 532 }
      name       = "23rd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 533 }
      name       = "24th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ###########################
  # Harwich#
  navalunit =
  { name     = "3rd Destroyer Squadron"
    id       = { type = 10499 id = 540 }
    location = 23 # Portsmouth
    base     = 23
    division =
    { experience = 30
      id         = { type = 10499 id = 541 }
      name       = "25th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 542 }
      name       = "26th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ###########################
  # 11th Escort Group - RCN - Derry#
  navalunit =
  { name     = "3th Escort Group"
    id       = { type = 10499 id = 550 }
    location = 28 # Belfast
    base     = 28
    division =
    { experience = 30
      id         = { type = 10499 id = 551 }
      name       = "27th Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
  }
  # ##########################
  # East Indies Taskforce#
  navalunit =
  { name     = "East Indies Force"
    id       = { type = 10499 id = 560 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 10499 id = 561 }
      name       = "HMS Nigeria"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 568 }
      name       = "HMS Ceylon"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 562 }
      name       = "28th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 563 }
      name       = "29th Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 564 }
      name       = "30th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # #################
  # Eastern Fleet#
  navalunit =
  { name     = "Eastern Fleet"
    id       = { type = 10499 id = 570 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience    = 30
      id            = { type = 10499 id = 571 }
      name          = "HMS Victorious"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 808 }
      name          = "HMS Indomitable"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 573 }
      name       = "HMS Queen Elizabeth"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 574 }
      name       = "HMS Renown"
      type       = battlecruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 575 }
      name       = "HMS Caradoc"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 576 }
      name       = "HMS Achilles"
      type       = light_cruiser
      model      = 2
    }
  }
  # ###########################
  # Gibraltar Taskforce#
  navalunit =
  { name     = "Force H"
    id       = { type = 10499 id = 580 }
    location = 348 # Gibraltar
    base     = 348
    division =
    { experience = 30
      id         = { type = 10499 id = 581 }
      name       = "HMS Delhi"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 582 }
      name       = "HMS Caledon"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 583 }
      name       = "HMS Aurora"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 584 }
      name       = "31st Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ##########################
  # Indian Ocean Fleet#
  navalunit =
  { name     = "Indian Ocean Squadron"
    id       = { type = 10499 id = 590 }
    location = 2027 # North-east of Madagascar, en route to Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 10499 id = 591 }
      name       = "HMS Newcastle"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 592 }
      name       = "HMS Suffolk"
      type       = heavy_cruiser
      model      = 1
    }
  }
  # ##########################
  # Far East Fleet#
  navalunit =
  { name     = "Far East Fleet"
    id       = { type = 10499 id = 600 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience    = 30
      id            = { type = 10499 id = 809 }
      name          = "HMS Illustrious"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 810 }
      name          = "HMS Indefatigable"
      type          = carrier
      extra         = cag
      model         = 4
      brigade_model = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 601 }
      name       = "HMS Valiant"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 602 }
      name       = "HMS Sussex"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 603 }
      name       = "HMS London"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 604 }
      name       = "HMS Shropshire"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 605 }
      name       = "HMS Gambia"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 606 }
      name       = "HMS Cumberland"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 607 }
      name       = "HMS Kenya"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 608 }
      name       = "32nd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 611 }
      name       = "33rd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # #########################
  # 1st Submarine Squadron#
  navalunit =
  { name     = "1st Submarine Squadron"
    id       = { type = 10499 id = 620 }
    location = 11 # Valetta
    base     = 11
    division =
    { experience = 30
      id         = { type = 10499 id = 621 }
      name       = "1st Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 622 }
      name       = "2nd Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 3rd Submarine Squadron - Holy Loch#
  navalunit =
  { name     = "3rd Submarine Squadron"
    id       = { type = 10499 id = 630 }
    location = 28 # Glasgow
    base     = 28
    division =
    { experience = 30
      id         = { type = 10499 id = 631 }
      name       = "3rd Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 632 }
      name       = "4th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 633 }
      name       = "5th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 634 }
      name       = "6th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 635 }
      name       = "7th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 4th Submarine Squadron - Trincomalee#
  navalunit =
  { name     = "4th Submarine Squadron"
    id       = { type = 10499 id = 640 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 10499 id = 641 }
      name       = "8th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 642 }
      name       = "9th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 643 }
      name       = "10th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
  }
  # #########################
  # 5th Submarine Squadron#
  navalunit =
  { name     = "5th Submarine Squadron"
    id       = { type = 10499 id = 650 }
    location = 21 # Portsmouth
    base     = 21
    division =
    { experience = 30
      id         = { type = 10499 id = 651 }
      name       = "11th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 652 }
      name       = "12th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 653 }
      name       = "13th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 6th Submarine Squadron - Blyth#
  navalunit =
  { name     = "6th Submarine Squadron"
    id       = { type = 10499 id = 660 }
    location = 11 # Newcastle
    base     = 11
    division =
    { experience = 30
      id         = { type = 10499 id = 661 }
      name       = "14th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 7th Submarine Squadron - Rothesay#
  navalunit =
  { name     = "7th Submarine Squadron"
    id       = { type = 10499 id = 670 }
    location = 28 # Glasgow
    base     = 28
    division =
    { experience = 30
      id         = { type = 10499 id = 671 }
      name       = "15th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 672 }
      name       = "16th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 673 }
      name       = "17th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 674 }
      name       = "18th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
  }
  # #########################
  # 8th Submarine Squadron - Trincomalee#
  navalunit =
  { name     = "8th Submarine Squadron"
    id       = { type = 10499 id = 680 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 10499 id = 681 }
      name       = "19th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 682 }
      name       = "20th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
  }
  # #########################
  # 9th Submarine Squadron - Dundee#
  navalunit =
  { name     = "9th Submarine Squadron"
    id       = { type = 10499 id = 690 }
    location = 8 # Aberdeen
    base     = 8
    division =
    { experience = 30
      id         = { type = 10499 id = 691 }
      name       = "21th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 692 }
      name       = "22th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 10th Submarine Squadron - Maddalena#
  navalunit =
  { name     = "10th Submarine Squadron"
    id       = { type = 10499 id = 700 }
    location = 525 # Cagliari / Sardegna
    base     = 525
    division =
    { experience = 30
      id         = { type = 10499 id = 701 }
      name       = "23th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { name     = "1st Transport Squadron"
    id       = { type = 10499 id = 503 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { experience = 30
      id         = { type = 10499 id = 504 }
      name       = "Suffolk Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 505 }
      name       = "Trojan Star Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 506 }
      name       = "Queen Mary Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2500 }
      name       = "Nieuw Amsterdam Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2501 }
      name       = "Strathenden Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2502 }
      name       = "Fort Edmonton Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2503 }
      name       = "Lars Bay Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2504 }
      name       = "Fort Langley Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2505 }
      name       = "King Ethelred Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "2nd Transport Squadron"
    id       = { type = 10499 id = 1507 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { experience = 30
      id         = { type = 10499 id = 1508 }
      name       = "Dominion Monarch Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1509 }
      name       = "Empire Arquebus Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1510 }
      name       = "Hororata Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2506 }
      name       = "Henry the VIII Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2507 }
      name       = "The Bishops Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2508 }
      name       = "Empire of India Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2509 }
      name       = "Empire of Africa Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2510 }
      name       = "Royal Caledonian Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2511 }
      name       = "Royal Sovereign Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "3rd Transport Squadron"
    id       = { type = 10499 id = 1511 }
    location = 21
    base     = 21
    division =
    { experience = 30
      id         = { type = 10499 id = 1512 }
      name       = "Queen Elizabeth Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1513 }
      name       = "Empress of Canada Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1514 }
      name       = "Clan Macauley Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2512 }
      name       = "Samfleet Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2513 }
      name       = "Samfreedom Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2514 }
      name       = "Samfoyle Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2515 }
      name       = "Samconstant Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2516 }
      name       = "Samleyte Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2517 }
      name       = "Samfaithful Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "4th Transport Squadron"
    id       = { type = 10499 id = 1515 }
    location = 21 # Scapa Flow
    base     = 21
    division =
    { experience = 30
      id         = { type = 10499 id = 1516 }
      name       = "Empire Captain Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1517 }
      name       = "Andes Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1518 }
      name       = "Empire Charmain Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2518 }
      name       = "Samoresby Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2519 }
      name       = "1st Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2520 }
      name       = "2nd Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2521 }
      name       = "3rd Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2522 }
      name       = "4th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2523 }
      name       = "5th Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "5th Transport Squadron"
    id       = { type = 10499 id = 519 }
    location = 906 # Alexandria
    base     = 906
    division =
    { experience = 30
      id         = { type = 10499 id = 1520 }
      name       = "Essex Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1521 }
      name       = "Maloja Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1522 }
      name       = "Empire Chieftain Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2524 }
      name       = "6th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2525 }
      name       = "7th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2526 }
      name       = "8th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2527 }
      name       = "9th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2528 }
      name       = "10th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2529 }
      name       = "11th Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "6th Transport Squadron"
    id       = { type = 10499 id = 1523 }
    location = 906 # Alexandria
    base     = 906
    division =
    { experience = 30
      id         = { type = 10499 id = 1524 }
      name       = "Stirling Castle Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1525 }
      name       = "Empire Splendour Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1526 }
      name       = "Sam Torch Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2530 }
      name       = "12th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2531 }
      name       = "13th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2532 }
      name       = "14th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2533 }
      name       = "15th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2534 }
      name       = "16th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2535 }
      name       = "17th Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "7th Transport Squadron"
    id       = { type = 10499 id = 1527 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 10499 id = 1528 }
      name       = "Resolution Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1529 }
      name       = "Fort Dunvegan Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 1530 }
      name       = "Durham Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2536 }
      name       = "18th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2537 }
      name       = "19th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2538 }
      name       = "20th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2539 }
      name       = "21st Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2540 }
      name       = "22nd Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 2541 }
      name       = "23rd Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  # ############################
  # ROYAL AIR FORCE 1944 OOB####
  # ############################
  airunit =
  { location = 19
    base     = 19
    id       = { type = 10499 id = 300 }
    name     = "10 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 301 }
      name       = "No.126 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 302 }
      name       = "No.165 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 303 }
      name       = "No.406 Squadron RCAF"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 304 }
      name       = "No.464 Squadron RAAF"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 305 }
      name       = "No.610 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 10499 id = 307 }
    name     = "11 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 308 }
      name       = "No.1 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 309 }
      name       = "No.64 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 310 }
      name       = "No.313 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 311 }
      name       = "No.501 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 312 }
      name       = "No.219 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 313 }
      name       = "No.29 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 314 }
      name       = "No.303 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 10499 id = 316 }
    name     = "2nd TAF/1"
    division =
    { experience = 30
      id         = { type = 10499 id = 317 }
      name       = "No.3 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 318 }
      name       = "No.33 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 319 }
      name       = "No.137 Squadron"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 320 }
      name       = "No.184 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 321 }
      name       = "No.245 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 325 }
      name       = "No.132 Squadron "
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 326 }
      name       = "No.183 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 329 }
      name       = "No.332 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 10499 id = 333 }
    name     = "2nd TAF/2"
    division =
    { experience = 30
      id         = { type = 10499 id = 334 }
      name       = "No.65 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 335 }
      name       = "No.181 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 336 }
      name       = "No.401 Squadron RCAF"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 14
    base     = 14
    id       = { type = 10499 id = 340 }
    name     = "12 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 341 }
      name       = "No.168 Squadron"
      strength   = 75
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 330 }
      name       = "No.694 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 322 }
      name       = "No.264 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 342 }
      name       = "No.25 Squadron"
      strength   = 75
      type       = tactical_bomber
      model      = 2
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 10499 id = 345 }
    name     = "13th Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 346 }
      name       = "No.504 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 349 }
      name       = "No.118 Squadron"
      strength   = 100
      type       = interceptor
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 327 }
      name       = "No.308 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 328 }
      name       = "No.331 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 10499 id = 348 }
    name     = "14th Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 337 }
      name       = "No.412 Squadron RCAF"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 338 }
      name       = "No.441 Squadron RCAF"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 323 }
      name       = "No.416 Squadron RCAF"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 324 }
      name       = "No.80 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 8
    base     = 8
    id       = { type = 10499 id = 352 }
    name     = "38 Group"
    division =
    { experience = 30
      id         = { type = 10499 id = 353 }
      name       = "No.190 Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 354 }
      name       = "No.297 Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 355 }
      name       = "No.570 Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 11
    base     = 11
    id       = { type = 10499 id = 358 }
    name     = "No.603 Squadron"
    division =
    { experience = 30
      id         = { type = 10499 id = 359 }
      name       = "No.603 Squadron"
      strength   = 100
      type       = interceptor
      model      = 2
    }
  }
  airunit =
  { location = 348
    base     = 348
    id       = { type = 10499 id = 363 }
    name     = "No.43 Squadron"
    division =
    { experience = 30
      id         = { type = 10499 id = 364 }
      name       = "No.43 Squadron"
      strength   = 100
      type       = interceptor
      model      = 2
    }
  }
  # ## pac air OOB 1944 Author: valdemar
  airunit =
  { location = 1457
    base     = 1457
    id       = { type = 10499 id = 365 }
    name     = "1/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 366 }
      name       = "17/.67./81. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 367 }
      name       = "136./155. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 368 }
      name       = "607./615. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 374 }
      name       = "5./11./20. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 1703
    base     = 1703
    id       = { type = 10499 id = 370 }
    name     = "ANZAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 371 }
      name       = "452./455./54. Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 1457
    base     = 1457
    id       = { type = 10499 id = 373 }
    name     = "2/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 375 }
      name       = "28./30. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 376 }
      name       = "42./34./42. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 377 }
      name       = "60./79. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 378 }
      name       = "113./123./134. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 379 }
      name       = "135./146./152. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 380 }
      name       = "258./261./273. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 382 }
      name       = "82./84./110. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 381 }
      name       = "45. Squadron"
      strength   = 40
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 1287
    base     = 1287
    id       = { type = 10499 id = 384 }
    name     = "3/SEAC Air Forces"
    division =
    { experience    = 30
      id            = { type = 10499 id = 385 }
      name          = "200./203./215. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 386 }
      name          = "99./159. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 10499 id = 387 }
      name          = "292./355./356. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 1287
    base     = 1287
    id       = { type = 10499 id = 389 }
    name     = "4/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 390 }
      name       = "27./47./88. Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 391 }
      name       = "176./177./211. Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 1457
    base     = 1457
    id       = { type = 10499 id = 393 }
    name     = "5/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 10499 id = 394 }
      name       = "31./62./117. Squadron"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 10499 id = 395 }
      name       = "194./435./436. Squadron"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
  }
  # ########################################
  # ##form. can. inc
  airunit =
  { location = 23
    base     = 23
    id       = { type = 11128 id = 600 }
    name     = "1 Group "
    division =
    { experience    = 30
      id            = { type = 11128 id = 601 }
      name          = "No.12 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 602 }
      name          = "No.103 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 603 }
      name          = "No.300 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 604 }
      name          = "No.576 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 605 }
      name          = "No.625 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 14
    base     = 14
    id       = { type = 11128 id = 608 }
    name     = "3rd Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 609 }
      name          = "No.15 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 610 }
      name          = "No.115 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 611 }
      name          = "No.218 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 11128 id = 614 }
    name     = "4th Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 615 }
      name          = "No.10 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 616 }
      name          = "No.76 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 617 }
      name          = "No.78 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 618 }
      name          = "No.346 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 619 }
      name          = "No.640 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 13
    base     = 13
    id       = { type = 11128 id = 623 }
    name     = "5th Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 624 }
      name          = "No.9 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 625 }
      name          = "No.49 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 626 }
      name          = "No.61 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 627 }
      name          = "No.106 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 628 }
      name          = "No.467 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 629 }
      name          = "No.619 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 13
    base     = 13
    id       = { type = 11128 id = 632 }
    name     = "6th Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 633 }
      name          = "No.408 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 634 }
      name          = "No.424 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 635 }
      name          = "No.427 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 636 }
      name          = "No.429 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 637 }
      name          = "No.432 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 19
    base     = 19
    id       = { type = 11128 id = 640 }
    name     = "8th Group"
    division =
    { experience    = 30
      id            = { type = 11128 id = 641 }
      name          = "No.7 Squadron"
      strength      = 75
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 642 }
      name          = "No.156 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 30
      id            = { type = 11128 id = 643 }
      name          = "No.582 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience = 30
      id         = { type = 11128 id = 644 }
      name       = "No.692 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 2
    }
  }
  # ######################################################################################################################
  # New Warships Under Construction#
  # ######################################################################################################################
  division_development =
  { name  = "HMS Implacable"
    type  = carrier
    model = 4
    cost  = 6.8
    id    = { type = 10500 id = 13 }
    date  = { year = 1944 month = august day = 28 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "HMS Swiftsure"
    type  = light_cruiser
    model = 4
    cost  = 5.9
    id    = { type = 10500 id = 14 }
    date  = { year = 1944 month = june day = 22 }
  }
  division_development =
  { name  = "34th Destroyer Flotilla"
    type  = destroyer
    model = 1
    cost  = 1.9
    id    = { type = 10500 id = 15 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "35th Destroyer Flotilla"
    type  = destroyer
    model = 1
    cost  = 1.9
    id    = { type = 10500 id = 16 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "36th Destroyer Flotilla"
    type  = destroyer
    model = 3
    cost  = 2.8
    id    = { type = 10500 id = 17 }
    date  = { year = 1944 month = october day = 1 }
  }
  division_development =
  { name  = "24th Submarine Flotilla"
    type  = submarine
    model = 2
    cost  = 1.7
    id    = { type = 10500 id = 18 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "25th Submarine Flotilla"
    type  = submarine
    model = 2
    cost  = 1.7
    id    = { type = 10500 id = 19 }
    date  = { year = 1944 month = october day = 1 }
  }
}
