
##############################
# Country definition for GER #
##############################

province = {
	id = 38
	supplypool = 100
	}
province =
{ id         = 32
  ic         = 3
  anti_air   = 8
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Brest
province =
{ id         = 34
  ic         = 2
  anti_air   = 4
  naval_base = { size = 6 current_size = 6 }
}              # Lorient
province =
{ id         = 35
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
}              # Nantes
province =
{ id       = 42
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
}            # Dieppe
province =
{ id            = 43
  radar_station = { size = 1 current_size = 1 }
  naval_base    = { size = 3 current_size = 3 }
}                 # Dunkerque
province =
{ id            = 45
  radar_station = { size = 2 current_size = 1 }
}                 # Ghent
province =
{ id         = 46
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
}              # Rotterdam
province =
{ id            = 47
  radar_station = { size = 1 current_size = 1 }
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
}                 # Amsterdam
province = { id = 49 anti_air = 2 } # Eindhoven
province =
{ id            = 50
  anti_air      = 2
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 6 current_size = 3 }
}                 # Antwerp
province =
{ id            = 51
  anti_air      = 1
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 10 current_size = 6 }
}                 # Brussels
province =
{ id       = 56
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Paris
province = { id = 58 ic = 1 } # Le Mans
province =
{ id         = 59
  ic         = 1
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
}              # Cholet
province = { id = 62 ic = 2 } # Auxerre
province =
{ id            = 66
  landfort      = 3
  radar_station = { size = 2 current_size = 2 }
 } # Aachen
province =
{ id            = 67
  anti_air      = 6
  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 4 current_size = 4 }
}                 # Essen
province = { id = 70 anti_air = 2 } # Arlon
province =
{ id            = 72
  anti_air      = 3
  air_base      = { size = 10 current_size = 10 }
}				#Metz
province =
{ id            = 74
  anti_air      = 6
#  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
  landfort      = 3
}                 # Saarbrücken
province =
{ id            = 75
  radar_station = { size = 4 current_size = 4 }
  landfort      = 3
  anti_air      = 2
  air_base      = { size = 10 current_size = 10 }
}                 # Cologne
province =
{ id            = 76
  anti_air      = 6
  radar_station = { size = 4 current_size = 4 }
}                 # Dortmund
province =
{ id       = 78
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
}            # Leeuwarden
province =
{ id            = 80
  anti_air      = 9
  naval_base    = { size = 10 current_size = 10 }
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 2 current_size = 2 }
}                 # Wilhelmshafen
province =
{ id            = 81
  anti_air      = 2
  radar_station = { size = 2 current_size = 2 }
}                 # Münster
province = { id = 82
anti_air = 6
air_base = { size = 10 current_size = 10 }
} # Kassel
province =
{ id            = 86
  radar_station = { size = 3 current_size = 3 }
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
}                 # Hannover
province =
{ id            = 87

  coastalfort   = 12
  radar_station = { size = 2 current_size = 2 }
}                 # Bremen
province =
{ id            = 88
  anti_air      = 6
  radar_station = { size = 2 current_size = 2 }
}                 # Hamburg
province =
{ id         = 89
  anti_air      = 2
#  naval_base = { size = 10 current_size = 10 }
#  air_base   = { size = 10 current_size = 10 }
}              # Lübeck
province =
{ id            = 90
  anti_air      = 8
  naval_base = { size = 10 current_size = 10 }
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 2 current_size = 2 }
}                 # Kiel
province =
{ id            = 91
  radar_station = { size = 1 current_size = 1 }
}                 # Kolding
province =
{ id            = 92
  naval_base    = { size = 2 current_size = 2 }
  air_base      = { size = 2 current_size = 2 }
  radar_station = { size = 1 current_size = 1 }
}                 # Århus
province =
{ id         = 107
  anti_air      = 4
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
  oilpool    = 100
  supplypool = 500
}              # Oslo
province =
{ id         = 110
  radar_station = { size = 1 current_size = 1 }
  anti_air      = 4
  air_base      = { size = 6 current_size = 6 }
  naval_base    = { size = 5 current_size = 5 }
}              # Bergen
province =
{ id         = 118
  anti_air = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Trondheim
province =
{ id         = 125
  anti_air   = 6
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Narvik
province =
{ id         = 292
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 4 current_size = 4 }
}              # Aalborg
province =
{ id         = 294
  anti_air      = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Copenhagen
province =
{ id            = 296
  anti_air      = 2
  naval_base    = { size = 3 current_size = 3 }
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 1 current_size = 1 }
  rocket_test   = { size = 6 current_size = 6 }
}                 # Rostock
province =
{ id            = 298
  anti_air      = 6
  radar_station = { size = 2 current_size = 2 }
}                 # Magdeburg
province =
{ id            = 300
  ic       = 1
  anti_air = 7
  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}                 # Berlin
province =
{ id         = 302
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
}              # Stettin
province =
{ id                  = 303
  ic                  = 6
  naval_base          = { size = 5 current_size = 5 }
  anti_air            = 3
  air_base            = { size = 5 current_size = 5 }
  province_revoltrisk = 8
}                       # Danzig
province = { id = 305
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
 province_revoltrisk = 8
} # Torun
province = { id = 306 province_revoltrisk = 8 } # Bydgoszcz
province = { id = 307
  anti_air = 2
  province_revoltrisk = 8
} # Poznan
province =
{ id       = 308
  anti_air = 2
 # air_base = { size = 10 current_size = 10 }
}            # Küstrin
province =
{ id       = 309
  anti_air = 2
}            # Cottbus
 province =
{ id            = 310
  anti_air      = 3
  radar_station = { size = 2 current_size = 2 }
}                 # Leipzig
province =
{ id            = 311
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
}                 # Dresden
province = { id = 312 anti_air = 3 } # Nuremberg
province = { id = 313 anti_air = 6 } # Frankfurt-am-Main
province =
{ id            = 313
  anti_air      = 3
  air_base = { size = 6 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
#  landfort      = 3
}                 # Frankfurt am Main
province =
{ id            = 314
  anti_air      = 3
  air_base = { size = 6 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
  landfort      = 3
}                 # Stuttgart
province = { id = 315 landfort = 3 } # Freiburg
province = { id = 316 ic = 1 } # Mulhouse
province = { id       = 325
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Bordeaux
province =
{ id         = 368
  landfort   = 15
  anti_air = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 8 }
}              # Genoa
province =
{ id         = 369
  anti_air = 2
  naval_base = { size = 10 current_size = 7 }
  air_base   = { size = 4 current_size = 2 }
}				# La Spezia
province =
{ id         = 370
  anti_air = 2
}# Milan
province =
{ id       = 376
  ic       = 3
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # Munich
province =
{ id       = 377
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Innsbruck
province =
{ id         = 378
  anti_air = 3
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Venice
province =
{ id         = 379
  naval_base = { size = 5 current_size = 5 }
}              # Ferrara
province = { id = 380 province_revoltrisk = 10 } # Ljubljana
province =
{ id                  = 381
  anti_air = 1
  naval_base          = { size = 5 current_size = 5 }
  air_base            = { size = 5 current_size = 5 }
  province_revoltrisk = 10
}                       # Rijeka
province =
 { id       = 382
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}            # Zagreb
province = { id = 384 province_revoltrisk = 10 } # Split
province = { id = 385 province_revoltrisk = 10 } # Zenica
province = { id = 386
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  province_revoltrisk = 10
} # Sarajevo
province = { id = 387 province_revoltrisk = 10 } # Mostar
province =
{ id                  = 388
  naval_base          = { size = 4 current_size = 4 }
  air_base            = { size = 4 current_size = 4 }
  province_revoltrisk = 10
}                       # Dubrovnik
province = { id = 389 province_revoltrisk = 10 } # Podgorica
province =
{ id         = 390
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Tirana
province = { id = 392 province_revoltrisk = 8 } # Ioannina
province =
{ id                  = 393
  naval_base          = { size = 1 current_size = 1 }
  air_base            = { size = 1 current_size = 1 }
  province_revoltrisk = 8
}                       # Kefalonia
province = { id = 394 province_revoltrisk = 8 } # Patras
province =
{ id                  = 395
  naval_base          = { size = 2 current_size = 2 }
  air_base            = { size = 2 current_size = 2 }
  province_revoltrisk = 8
}                       # Corinthe
province =
{ id                  = 396
  supplypool = 200
  oilpool    = 200
  anti_air   = 2
  naval_base          = { size = 4 current_size = 4 }
  air_base            = { size = 4 current_size = 4 }
  province_revoltrisk = 8
}                       # Crete
province =
{ id         = 399
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Rhodes
province = { id = 400 province_revoltrisk = 8 } # The Cyclades
province =
{ id                  = 401
  naval_base          = { size = 10 current_size = 10 }
  supplypool = 200
  oilpool    = 200
  anti_air   = 4
  air_base            = { size = 10 current_size = 10 }
  province_revoltrisk = 8
}                       # Athens
province = { id = 402 province_revoltrisk = 8 } # Agrinio
province = { id = 403 province_revoltrisk = 8 } # Larisa
province = { id = 405 province_revoltrisk = 8 } # The Dardanelles
province = { id = 412
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  province_revoltrisk = 8
} # Edessa
province = { id = 415 province_revoltrisk = 10 } # Pristina
province = { id = 418 province_revoltrisk = 10 } # Nis
province = { id = 451 province_revoltrisk = 10 } # Novi Pazar
province = { id = 452 province_revoltrisk = 10 } # Uzice
province = { id = 453
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
  province_revoltrisk = 10 } # Belgrade
province = { id = 454
  anti_air = 2
  province_revoltrisk = 10 } # Osijek
province = { id = 459 province_revoltrisk = 10 } # Maribor
province = { id = 460 anti_air = 1 } # Graz
province =
{ id       = 462
  anti_air = 1
  air_base = { size = 3 current_size = 3 }
}            # Salzburg
province =
{ id       = 463
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # Vienna
province =
{ id       = 466
  air_base = { size = 3 current_size = 3 }
}            # Strakonice
province =
{ id       = 469
  anti_air = 5
  air_base = { size = 5 current_size = 5 }
}            # Prague
province = { id = 470 anti_air = 2 } # Pilsen
province =
{ id       = 473
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Breslau
province = { id = 475 anti_air = 4 } # Brno
province = { id = 479
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
 province_revoltrisk = 8
} # Cracow
province = { id = 480 province_revoltrisk = 8 } # Kielce
province = { id = 481 province_revoltrisk = 8 } # Czestochowa
province = { id = 482
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
 province_revoltrisk = 8 } # Oppeln
province = { id = 483
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
  province_revoltrisk = 8
} # Lodz
province = { id = 484 province_revoltrisk = 8 } # Radom
province = { id = 485
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  ic = 6
  province_revoltrisk = 8
} # Warsaw
province = { id = 486 province_revoltrisk = 8 } # Lomza
province = { id = 487
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  province_revoltrisk = 8
} # Lublin
province = { id = 488 province_revoltrisk = 8 } # Zamosc
province = { id = 489 province_revoltrisk = 8 } # Przemysl
province = { id = 494
  anti_air = 1
  province_revoltrisk = 10
} # Zrenjanin
province =
{ id         = 510
  anti_air   = 3
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 7 current_size = 7 }
}              # Königsberg
province =
{ id         = 513
  landfort      = 1		#Gothic linie
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Florence
province =
{ id       = 514
  landfort      = 1		#Gothic linie
}				#Rimini
province =
{ id       = 519
  air_base = { size = 10 current_size = 10 }
}            # Anzio
province =
{ id         = 521
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  supplypool = 5000
  oilpool    = 2000
}              # Naples
province =
{ id         = 523
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Taranto
province =
{ id         = 525
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
}              # Palermo
province =
{ id         = 526
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Catania
province = { id = 531 landfort = 15 } # Turin
province =
{ id         = 534
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Sardinia

#####################
# Country main data #
#####################

country =
{ tag                    = GER
  belligerence           = 100
  capital                = 300
  manpower               = 850
  transports             = 135
  escorts                = 35
  # Resource Reserves
  energy                 = 65000
  metal                  = 25000
  rare_materials         = 5000
  oil                    = 2000
  supplies               = 5000
  money                  = 200
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 1
    free_market       = 5
    freedom           = 2
    professional_army = 7
    defense_lobby     = 10
    interventionism   = 10
  }
  SpyInfo                = { country = "GER" NumberOfSpies = 14 }
  #SpyInfo                = { country = "ENG" NumberOfSpies = 6}
  #SpyInfo                = { country = "VIC" NumberOfSpies = 6 }
  #SpyInfo                = { country = "SOV" NumberOfSpies = 6}
  #SpyInfo                = { country = "SPA" NumberOfSpies = 6}
  #SpyInfo                = { country = "POL" NumberOfSpies = 12}
  #SpyInfo                = { country = "SWE" NumberOfSpies = 7}
  #SpyInfo                = { country = "FIN" NumberOfSpies = 6}
  #SpyInfo                = { country = "YUG" NumberOfSpies = 6}
  #SpyInfo                = { country = "HUN" NumberOfSpies = 7}
  #SpyInfo                = { country = "BUL" NumberOfSpies = 6}
  #SpyInfo                = { country = "BEL" NumberOfSpies = 5}
  #SpyInfo                = { country = "DEN" NumberOfSpies = 7 }
  #SpyInfo                = { country = "HOL" NumberOfSpies = 5}
  #SpyInfo                = { country = "ARG" NumberOfSpies = 7}
  #SpyInfo                = { country = "USA" NumberOfSpies = 12}
  #SpyInfo                = { country = "ALB" NumberOfSpies = 5}
  #SpyInfo                = { country = "GRE" NumberOfSpies = 5}
  #SpyInfo                = { country = "BRA" NumberOfSpies = 5}
  #SpyInfo                = { country = "JAP" NumberOfSpies = 7}
  #SpyInfo                = { country = "ROM" NumberOfSpies = 6}
  #SpyInfo                = { country = "LIT" NumberOfSpies = 6}
  #SpyInfo                = { country = "FRA" NumberOfSpies = 5}
  #SpyInfo                = { country = "POR" NumberOfSpies = 5}
  #SpyInfo                = { country = "ITA" NumberOfSpies = 12}
  #SpyInfo                = { country = "CHI" NumberOfSpies = 12}
  nationalprovinces      = { 67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  206 296 297 298 299 300 301 302 304 308 309 310 311 312 313
			     314 315 374 375 376 473 510 482 72  73  316 71  303 466 467 471 472 373 377 460 461 462 463 464 465 305 306 307
			   }
  ownedprovinces         = { 67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313 314
			     315 374 375 376 473 510 66  471 472 466 467 470 469 468 474 475 478 477 490 476 91  92  292 293 294 303 306 307 482 479
			     480 481 483 484 305 485 486 487 489 488 392 393 394 395 396 400 401 402 403 405 412 107 108 109 110 111 116 117 118 124
			     125 128 129 380 459 454 453 381 384 385 386 387 388 389 451 452 418 415 494 525 526 524 523 522 521 520 519 518 517 516
			     515 513 514 512 379 369 368 531 370 371 378 534 398 206 373 377 460 461 462 463 464 465 399 390 391 71  295
			   }
  controlledprovinces    = { 399 398 67   74   75   76   80   81   82   83   84   85   86   87   88   89   90   296  297  298  299  300  301  302  304  308
			     309  310  311  312  313  314  315  374  375  376  473  510  390  391  529  527  366  365  364  363  362  358  328  327
			     326  325  324  359  361  319  360  322  323  59   60   61   62   63   318  317  316  73   72   64   53   44   43   18
			     54   42   55   41   56   57   58   32   33   34   35   36   38   40   320  321  528  471  472  466  467  470  469  468
			     474  475  478  477  490  476  91   92   292  293  294  46   47   48   49   66   77   78   79   303  306  307  482  479
			     480  481  483  484  305  485  486  487  489  488  500  501  503  504  505  506  507  508  509  209  208  213  211  210
			     222  392  393  394  395  396  400  401  402  403  405  412  107  108  109  110  111  116  117  118  124  125  128  129
			     380  459  454  453  381  384  385  386  387  388  389  451  452  418  415  494  205  204  203  197  206  207  511  193
			     194  195  196  225  199  200  201  202  212  218  220  562  221  1874 214  198  513  514  512  379  369  368  531  370
			     371  378  45   50   51   52   65   68   69   70   373  377  460  461  462  463  464  465  71   577  295
			   }
  # Germany 1944 techs
  # ######################
  techapps               = { 1010  1020  1030  1040  1040  1050  1070  1080  1090  1100  1110  1120  1130  1140  1190  1200  1210  1220  1230  1240
			     1250  1260  1270  1280  1310  1320  1330  1340  1350  1360  14000 14010 14020 15030 15500 2010  2020  2030  2040  2050
			     2060  2070  2080  2090  2100  2110  2120  2150  2160  2170  2180  2190  2200  2220  2230  2240  2250  2260  2270  2280
			     2290  2300  2310  2320  2330  2340  2350  2360  2370  2380  2390  2400  2410  2420  2430  2450  2460  2470  2480  2490
			     2510  2520  2530  2540  3010  3020  3030  3040  3070  3080  3090  3100  3130  3140  3150  3160  3190  3200  3210  3220
			     3250  3260  3270  3280  3290  3320  3330  3340  3400  3410  3420  3430  3440  4010  4020  4030  4040  4050  4060  4070
			     4080  4090  4100  4110  4120  4130  4140  4150  4160  4170  4180  4190  4200  4210  4220  4230  4240  4250  4260  4270
			     4280  5010  5020  5030  5050  5060  5070  5080  5090  5100  5110  5120  5130  5140  5150  5160  5170  5180  5190  5200
			     5210  5220  5230  5310  5320  5330  5340  5350  5360  5370  5380  5410  5420  5430  5440  5450  5470  5480  5490  5500
			     5550  5560  5570  5580  5590  6210  6220  6230  6240  6250  6260  6270  6290  7010  7020  7100  7110  7140
			     8010  8020  8030  8040  8050  8080  8090  8150  8160  8170  8210  8280  8290  9010  9020
			     9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130  9190  9200  9210  9220  9230  9240  9250  9260  9270
			     9280  9290  9300  9310  9320  9330  9340  9350  9360  9370  9380  9390  9400  9410  9420  6280
			   }
  blueprints             = { 15000 15100 7150 }
  inventions             = { 8000 8001 8006 8007 8008 8009 8010 8011 8016 8017 }
  diplomacy =
  { relation = { tag = CHI value = -50 }
    relation = { tag = ARG value = 75 }
    relation = { tag = AST value = -200 }
    relation = { tag = BEL value = -200 }
    relation = { tag = BHU value = -200 }
    relation = { tag = BOL value = 15 }
    relation = { tag = BRA value = 50 }
    relation = { tag = BUL value = 200 }
    relation = { tag = CAN value = -200 }
    relation = { tag = CHL value = 50 }
    relation = { tag = COL value = -20 }
    relation = { tag = ENG value = -200 }
    relation = { tag = FIN value = 200 }
    relation = { tag = FRA value = -200 }
    relation =
    { tag        = HUN
      value      = 200
      guaranteed = { day = 20 month = november year = 1942 }
    }
    relation =
    { tag        = JAP
      value      = 200
    }
    relation = { tag = MAN value = 20 }
    relation = { tag = NEP value = -200 }
    relation = { tag = NZL value = -200 }
    relation = { tag = POR value = 75 }
    relation =
    { tag        = ROM
      value      = 200
      guaranteed = { day = 20 month = november year = 1942 }
    }
    relation = { tag = SAF value = -200 }
    relation = { tag = SCH value = 50 }
    relation = { tag = SOV value = -200 }
    relation = { tag = SPA value = 50 }
    relation = { tag = SWE value = 50 }
    relation = { tag = TUR value = 10 }
    relation = { tag = USA value = -200 }
    relation = { tag = OMN value = -200 }
    relation = { tag = YEM value = -200 }
  }
  dormant_ministers      = { 33  45  46  51  3   64  4   77  5   116 7   8   179 2   65  76  95  96  155 166 36  213 47  91  92  105 109 123 175 185
			     9   199 209 208 52  131 36  244
			   }
  headofstate            = { type = 9 id = 1 }
  headofgovernment       = { type = 9 id = 42 }
  foreignminister        = { type = 9 id = 55 }
  armamentminister       = { type = 9 id = 86 }
  ministerofsecurity     = { type = 9 id = 108 }
  ministerofintelligence = { type = 9 id = 138 }
  chiefofstaff           = { type = 9 id = 157 }
  chiefofarmy            = { type = 9 id = 177 }
  chiefofnavy            = { type = 9 id = 192 }
  chiefofair             = { type = 9 id = 10 }
  dormant_teams		 = { 21 }
  dormant_leaders        = { 398 607 473 334 116 215 287 316 447 584 41  194 212 219 233 268 271 272 292 321 354 565 567 50  53  88  129 131 138 140
			     144 164 695
			   }
  # #z3 operational but not put to use; Ju287 already flown
  landunit =
  { location = 193
    id       = { type = 10602 id = 1 }
    name     = "Narwa Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 702 }
      name       = "Narwa Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 2 }
      name          = "58. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = artillery
      brigade_model = 5
      model         = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 3 }
      name       = "122. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 4 }
      name       = "170. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 5 }
      name       = "225. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 6 }
      name       = "227. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 26 }
      name       = "285. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 27 }
      name       = "61. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 193
    id       = { type = 10602 id = 7 }
    name     = "3. SS Panzerkorps"
    division =
    { experience    = 60
      id            = { type = 10602 id = 8 }
      name          = "11. SS-Pz.Gr.Freiw.Div. 'Nordland'"
      strength      = 65
      type          = mechanized
      extra         = tank_destroyer
      model         = 2
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 9 }
      name       = "20. Estische SS-Freiw.-Div."
      strength   = 65
      type       = motorized
      model      = 2
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 200
    id       = { type = 10602 id = 10 }
    name     = "18. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 703 }
      name       = "18. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 11 }
      name          = "21. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 12 }
      name       = "30. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 13 }
      name       = "126. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 14 }
      name       = "212. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 15 }
      name       = "12. Luftwaffen-Feld-Division"
      strength   = 55
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 16 }
      name       = "32. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 17 }
      name       = "121. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 18 }
      name       = "21. Luftwaffen-Feld-Division"
      strength   = 55
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 19 }
      name       = "87. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 20 }
      name       = "205. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 21 }
      name       = "23. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 22 }
      name       = "81. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 23 }
      name       = "329. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 24 }
      name       = "215. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 25 }
      name       = "301. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 201
    id       = { type = 10602 id = 28 }
    name     = "16. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 704 }
      name       = "16. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 29 }
      name          = "93. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 30 }
      name       = "15. Lettische SS-Freiw.-Div."
      strength   = 65
      type       = motorized
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 31 }
      name       = "19. Lettische SS-Freiw.-Div."
      strength   = 65
      type       = motorized
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 32 }
      name       = "263. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 33 }
      name       = "290. Luftwaffen-Feld-Division"
      strength   = 60
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 34 }
      name       = "389. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 35 }
      name       = "24. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 36 }
      name       = "69. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 37 }
      name       = "281. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 1874
    id       = { type = 10602 id = 38 }
    name     = "3. Panzerarmee"
    division =
    { experience = 60
      id         = { type = 10602 id = 705 }
      name       = "3. Panzerarmee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 39 }
      name          = "83. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 40 }
      name       = "4. Luftwaffen-Feld-Division"
      strength   = 40
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 41 }
      name       = "6. Luftwaffen-Feld-Division"
      strength   = 40
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 42 }
      name       = "132. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 43 }
      name       = "218. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 44 }
      name       = "197. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 45 }
      name          = "296. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 46 }
      name       = "299. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 47 }
      name       = "201. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 48 }
      name       = "252. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 49 }
      name       = "206. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 50 }
      name       = "246. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 51 }
      name          = "98. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 218
    id       = { type = 10602 id = 52 }
    name     = "4. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 706 }
      name       = "4. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 53 }
      name       = "286. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 54 }
      name          = "57. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 55 }
      name          = "267. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 56 }
      name          = "78. Sturm-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 57 }
      name       = "260. Infanterie-Division"
      strength   = 60
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 58 }
      name       = "12. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 59 }
      name          = "31. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 60 }
      name       = "110. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 61 }
      name       = "337. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 62 }
      name       = "6. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 63 }
      name       = "45. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 64 }
      name       = "134. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 65 }
      name          = "295. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = artillery
      model         = 4
      brigade_model = 5
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 66 }
      name       = "383. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 67 }
      name       = "35. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 68 }
      name       = "36. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 69 }
      name       = "129. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 221
    id       = { type = 10602 id = 70 }
    name     = "XXVII. Korps"
    division =
    { experience = 60
      id         = { type = 10602 id = 71 }
      name       = "15. Panzergrenadier-Division"
      strength   = 65
      type       = mechanized
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 72 }
      name       = "28. Panzergrenadier-Division"
      strength   = 65
      type       = mechanized
      model      = 2
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 220
    id       = { type = 10602 id = 73 }
    name     = "9. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 707 }
      name       = "9. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 74 }
      name       = "102. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 75 }
      name          = "292. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 76 }
      name       = "5. Jäger-Division"
      strength   = 65
      type       = infantry
      extra      = engineer
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 77 }
      name          = "211. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = anti_air
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 78 }
      name       = "3. Kavallerie-Division"
      strength   = 60
      type       = cavalry
      model      = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 79 }
      name          = "707. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = artillery
      model         = 4
      brigade_model = 5
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 208
    id       = { type = 10602 id = 81 }
    name     = "Heeresgruppe Mitte"
    division =
    { experience = 60
      id         = { type = 10602 id = 701 }
      name       = "Heeresgruppe Mitte"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 82 }
      name          = "5. SS-Panzer-Div. 'Wiking'"
      strength      = 100
      type          = armor
      model         = 4
      extra         = sp_artillery
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 83 }
      name       = "20. Panzer-Division"
      strength   = 70
      type       = armor
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 84 }
      name          = "14. Galizische SS-Freiw.-Div."
      strength      = 80
      type          = motorized
      extra         = tank_destroyer
      model         = 2
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 85 }
      name          = "40. SS-Freiw.Pz.Gr.Div. 'Feldhernhalle'"
      strength      = 80
      type          = mechanized
      extra         = anti_air
      model         = 2
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 87 }
      name       = "52. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 88 }
      name       = "221. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 194
    id       = { type = 10602 id = 89 }
    name     = "Heeresgruppe Nord"
    division =
    { experience = 60
      id         = { type = 10602 id = 700 }
      name       = "Heeresgruppe Nord"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 90 }
      name          = "12. Panzer-Division"
      strength      = 70
      type          = armor
      model         = 4
      extra         = anti_air
      brigade_model = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 225
    id       = { type = 10602 id = 91 }
    name     = "2. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 708 }
      name       = "2. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 92 }
      name       = "340. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 93 }
      name          = "7. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 94 }
      name          = "361.Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 95 }
      name       = "203. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 96 }
      name       = "454. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 97 }
      name       = "213. Sicherungs-Division"
      strength   = 40
      type       = infantry
      model      = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 562
    id       = { type = 10602 id = 98 }
    name     = "4. Panzerarmee"
    division =
    { experience = 60
      id         = { type = 10602 id = 709 }
      name       = "4. Panzerarmee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 99 }
      name       = "88. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 100 }
      name          = "72. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 101 }
      name          = "26. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 102 }
      name       = "214. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 103 }
      name       = "291. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 104 }
      name       = "131. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 105 }
      name       = "253. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 106 }
      name       = "342. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 107 }
      name       = "75. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 108 }
      name       = "371. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 109 }
      name       = "1. SK Jäger Division"
      strength   = 65
      type       = infantry
      extra      = engineer
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 110 }
      name       = "100. Jäger-Division"
      strength   = 65
      type       = infantry
      extra      = engineer
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 500
    id       = { type = 10602 id = 111 }
    name     = "III. Panzerkorps"
    division =
    { experience = 60
      id         = { type = 10602 id = 112 }
      name       = "1. Panzer-Division"
      strength   = 50
      type       = armor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 113 }
      name       = "7. Panzer-Division"
      strength   = 50
      type       = armor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 114 }
      name       = "8. Panzer-Division"
      strength   = 50
      type       = armor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 115 }
      name       = "17. Panzer-Division"
      strength   = 50
      type       = armor
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 117 }
      name          = "20. Panzergrenadier-Division"
      strength      = 65
      type          = mechanized
      extra         = anti_air
      model         = 2
      brigade_model = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 501
    id       = { type = 10602 id = 118 }
    name     = "1. Panzerarmee"
    division =
    { experience = 60
      id         = { type = 10602 id = 710 }
      name       = "1. Panzerarmee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 119 }
      name          = "1. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 120 }
      name       = "168. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 121 }
      name       = "367. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 122 }
      name          = "349. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 123 }
      name          = "254. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 124 }
      name       = "96. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 125 }
      name       = "208. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 126 }
      name       = "357. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 127 }
      name       = "353. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 433
    id       = { type = 10602 id = 128 }
    name     = "XVII. Korps"
    division =
    { experience = 60
      id         = { type = 10602 id = 129 }
      name       = "3. Gebirgsjäger-Division"
      strength   = 65
      type       = bergsjaeger
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 130 }
      name       = "46. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 131 }
      name       = "8. Jäger-Division"
      strength   = 65
      type       = infantry
      extra      = engineer
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 132 }
      name       = "101. Jäger-Division"
      strength   = 65
      type       = infantry
      extra      = engineer
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 133 }
      name          = "14. Panzer-Division"
      strength      = 70
      type          = armor
      model         = 4
      extra         = heavy_armor
      brigade_model = 1
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 434
    id       = { type = 10602 id = 134 }
    name     = "6. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 711 }
      name       = "6. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 135 }
      name          = "10. Panzergrenadier-Division"
      strength      = 65
      type          = mechanized
      extra         = anti_air
      model         = 2
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 136 }
      name       = "15. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 137 }
      name       = "302. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 138 }
      name          = "257. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 139 }
      name          = "306. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = artillery
      model         = 4
      brigade_model = 5
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 140 }
      name       = "384. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 141 }
      name       = "106. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 142 }
      name       = "370. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 143 }
      name       = "258. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 144 }
      name       = "282. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 145 }
      name       = "335. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 146 }
      name       = "17. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 147 }
      name       = "294. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 435
    id       = { type = 10602 id = 148 }
    name     = "VII. Korps"
    division =
    { experience = 60
      id         = { type = 10602 id = 149 }
      name       = "320. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 150 }
      name       = "97. Jäger-Division"
      strength   = 65
      type       = infantry
      extra      = engineer
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 151 }
      name       = "4. Gebirgsjäger-Division"
      strength   = 65
      type       = bergsjaeger
      model      = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 506
    id       = { type = 10602 id = 152 }
    name     = "IV. Korps"
    division =
    { experience = 60
      id         = { type = 10602 id = 153 }
      name       = "23. Panzer-Division"
      strength   = 50
      type       = armor
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 154 }
      name          = "3. Panzer-Division"
      strength      = 50
      type          = armor
      model         = 4
      extra         = sp_artillery
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 155 }
      name       = "13. Panzer-Division"
      strength   = 50
      type       = armor
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 506
    id       = { type = 10602 id = 156 }
    name     = "17. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 724 }
      name       = "11. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 157 }
      name       = "1. slov. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 158 }
      name       = "50. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 159 }
      name          = "79. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 160 }
      name          = "376. Infanterie-Division"
      strength      = 65
      type          = infantry
      extra         = artillery
      model         = 4
      brigade_model = 5
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 500
    id       = { type = 10602 id = 161 }
    name     = "Armeegruppe Nordukraine"
    division =
    { experience    = 60
      id            = { type = 10602 id = 162 }
      name          = "Armeegruppe Nordukraine"
      type          = hq
      model         = 2
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 429
    id       = { type = 10602 id = 163 }
    name     = "Armeegruppe Südukraine"
    division =
    { experience    = 60
      id            = { type = 10602 id = 164 }
      name          = "Armeegruppe Südukraine"
      type          = hq
      model         = 2
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 432
    id       = { type = 10602 id = 165 }
    name     = "LXXII. Korps"
    division =
    { experience    = 60
      id            = { type = 10602 id = 166 }
      name          = "16. Panzer-Division"
      strength      = 50
      type          = armor
      model         = 4
      extra         = heavy_armor
      brigade_model = 1
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 167 }
      name       = "34. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 168 }
      name       = "73. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 169 }
      name       = "300. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 170 }
      name       = "356. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  # #############################
  # ## NORMANDY TOE INFANTRY ####
  # #############################
  landunit =
  { location = 40
    id       = { type = 10602 id = 712 }
    name     = "5. Panzerarmee"
    division =
    { experience = 60
      id         = { type = 10602 id = 713 }
      name       = "5. Panzerarmee"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 36
    id       = { type = 10602 id = 714 }
    name     = "7. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 715 }
      name       = "7. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 44
    id       = { type = 10602 id = 716 }
    name     = "15. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 717 }
      name       = "15. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 361
    id       = { type = 10602 id = 718 }
    name     = "1. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 719 }
      name       = "1. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 56
    id       = { type = 10602 id = 720 }
    name     = "Heeresgruppe B"
    division =
    { experience = 60
      id         = { type = 10602 id = 721 }
      name       = "Heeresgruppe B"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 66
    id       = { type = 10602 id = 722 }
    name     = "Heeresgruppe A"
    division =
    { experience = 60
      id         = { type = 10602 id = 723 }
      name       = "Heeresgruppe A"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { id       = { type = 10602 id = 202 }
    name     = "III. Fallschirmjäger Korps"
    location = 40
    division =
    { experience    = 60
      id            = { type = 10602 id = 203 }
      name          = "2. Fallschirmjäger Division"
      type          = paratrooper
      strength      = 40
      extra         = artillery
      brigade_model = 5
      organisation  = 20
      model         = 3
    }
  }
  landunit =
  { id       = { type = 10602 id = 204 }
    name     = "II. Fallschirmjäger Korps"
    location = 36
    division =
    { experience   = 60
      id           = { type = 10602 id = 205 }
      name         = "3. Fallschirmjäger Division"
      type         = paratrooper
      strength     = 100
      organisation = 20
      model        = 3
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 206 }
      name         = "5. Fallschirmjäger Division"
      type         = paratrooper
      strength     = 65
      organisation = 20
      model        = 3
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 207 }
      name         = "6. Fallschirmjäger Division"
      type         = paratrooper
      strength     = 40
      organisation = 20
      model        = 3
    }
    dig_in   = 20.000
  }
  landunit =
  { id       = { type = 10602 id = 208 }
    name     = "16. Luftwaffen-Feld-Division"
    location = 54 # On way to Normandy from Netherlands
    division =
    { experience   = 60
      id           = { type = 10602 id = 209 }
      name         = "16. Luftwaffen-Feld-Division"
      type         = infantry
      strength     = 62
      organisation = 20
      model        = 3
    }
  }
  landunit =
  { id       = { type = 10602 id = 210 }
    name     = "LXXXV. Armeekorps"
    location = 40 # Between St.Malo & Normandy
    division =
    { experience   = 60
      id           = { type = 10602 id = 212 }
      name         = "266. Infanterie-Division (mot)"
      type         = motorized
      strength     = 70
      organisation = 20
      model        = 2
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 213 }
      name         = "352. Infanterie-Division (mot)"
      type         = motorized
      strength     = 65
      organisation = 20
      model        = 2
    }
  }
  landunit =
  { id       = { type = 10602 id = 214 }
    name     = "85. Infanterie-Division"
    location = 43 # Just on way to Normandy
    division =
    { experience   = 60
      id           = { type = 10602 id = 215 }
      name         = "85. Infanterie-Division"
      type         = infantry
      strength     = 60
      organisation = 20
      model        = 4
    }
  }
  landunit =
  { id       = { type = 10602 id = 216 }
    name     = "LXXXVI. Armeekorps"
    location = 41 # Eastern side near Caen etc
    division =
    { experience   = 60
      id           = { type = 10602 id = 217 }
      name         = "91. Infanterie-Division"
      type         = infantry
      strength     = 10 # Heavily battered
      organisation = 20
      model        = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 218 }
    name     = "LXXXVII. Armeekorps"
    location = 41 # Near Orne River
    division =
    { experience    = 60
      id            = { type = 10602 id = 219 }
      name          = "346. Infanterie-Division (mot)"
      type          = motorized
      strength      = 50
      extra         = tank_destroyer
      brigade_model = 3
      organisation  = 20
      model         = 2
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 220 }
    name     = "LXXXIV. Armeekorps"
    location = 33 # Western side of Cotentin peninsula
    division =
    { experience   = 60
      id           = { type = 10602 id = 222 }
      name         = "265. Infanterie-Division (mot)"
      type         = motorized
      strength     = 80
      organisation = 20
      model        = 2
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 223 }
      name         = "275. Infanterie-Division"
      type         = infantry
      strength     = 65
      organisation = 20
      model        = 4
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 224 }
      name         = "277. Infanterie-Division"
      type         = infantry
      strength     = 90 # Just moved in from South
      organisation = 20
      model        = 4
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 274 }
      name         = "353. Infanterie-Division (mot)"
      type         = motorized
      strength     = 95
      organisation = 20
      model        = 2
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 275 }
      name         = "709. Infanterie-Division"
      type         = infantry
      strength     = 55
      organisation = 20
      model        = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 276 }
    name     = "15. Armee"
    location = 45
    division =
    { experience   = 60
      id           = { type = 10602 id = 277 }
      name         = "326. Infanterie-Division"
      type         = infantry
      strength     = 77
      model        = 4
      organisation = 20
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 278 }
      name         = "711. Infanterie-Division"
      type         = infantry
      strength     = 48
      model        = 4
      organisation = 20
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 279 }
      name         = "716. Infanterie-Division"
      type         = infantry
      strength     = 20
      model        = 4
      organisation = 20
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 280 }
    name     = "19. Armee"
    location = 363 # Southern France
    division =
    { experience    = 60
      id            = { type = 10602 id = 281 }
      name          = "272. Infanterie-Division (mot)"
      type          = infantry
      strength      = 80
      extra         = anti_air
      brigade_model = 3
      model         = 4
      organisation  = 20
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 282 }
      name         = "42. Jäger-Division"
      type         = infantry
      strength     = 90
      model        = 4
      organisation = 20
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 283 }
      name         = "34. Infanterie-Division"
      type         = infantry
      strength     = 90
      model        = 4
      organisation = 20
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 284 }
      name       = "248. Infanterie-Division"
      type       = infantry
      strength   = 90
      model      = 4
    }
  }
  landunit =
  { id       = { type = 10602 id = 285 }
    name     = "276. Infanterie-Division"
    location = 60 # On way from Bordeaux area on train
    division =
    { experience   = 60
      id           = { type = 10602 id = 286 }
      name         = "275. Infanterie-Division"
      type         = infantry
      strength     = 90
      model        = 4
      organisation = 20
    }
  }
  landunit =
  { id       = { type = 10602 id = 287 }
    name     = "331. Infanterie-Division (mot)"
    location = 46 # Did not move to Normandy yet
    division =
    { experience   = 60
      id           = { type = 10602 id = 288 }
      name         = "331. Infanterie-Division (mot)"
      type         = motorized
      strength     = 85
      model        = 2
      organisation = 20
    }
  }
  landunit =
  { id       = { type = 10602 id = 289 }
    name     = "I. Armee"
    location = 325 # Guarding Bay of Biscaye
    division =
    { experience   = 60
      id           = { type = 10602 id = 290 }
      name         = "266. Infanterie-Division"
      type         = infantry
      strength     = 55
      model        = 4
      organisation = 20
    }
  }
  # #############################
  # ### NORMANDY TOE armorS ####
  # #############################
  landunit =
  { id       = { type = 10602 id = 291 }
    name     = "XLVII. Panzerkorps"
    location = 40
    division =
    { experience    = 60
      id            = { type = 10602 id = 292 }
      name          = "130. Panzer-Lehr-Division"
      type          = armor
      model         = 4
      extra         = sp_artillery
      brigade_model = 3
      strength      = 95
      organisation  = 25
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 293 }
      name         = "2. Panzer-Division"
      type         = armor
      model        = 4
      strength     = 70
      organisation = 25
    }
  }
  landunit =
  { id       = { type = 10602 id = 294 }
    name     = "I. SS-Panzerkorps"
    location = 40
    division =
    { experience    = 60
      id            = { type = 10602 id = 295 }
      name          = "1. SS-Leibstandarte Adolf Hitler"
      type          = armor
      model         = 4
      extra         = heavy_armor
      brigade_model = 1
      strength      = 70
      organisation  = 25
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 296 }
      name          = "12. SS-Panzer-Div. 'Hitlerjugend'"
      type          = armor
      model         = 4
      extra         = heavy_armor
      brigade_model = 1
      strength      = 65
      organisation  = 25
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 297 }
      name         = "116. Panzer-Division"
      type         = armor
      model        = 3
      strength     = 35
      organisation = 25
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 298 }
    name     = "II. SS-Panzerkorps"
    location = 36
    division =
    { experience    = 60
      id            = { type = 10602 id = 299 }
      name          = "17. SS-Pz.Gr.Div. 'Götz Berlichingen'"
      type          = mechanized
      extra         = sp_artillery
      brigade_model = 3
      strength      = 65
      organisation  = 25
      model         = 2
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 300 }
      name          = "2. SS-Panzer-Div. 'Das Reich'"
      type          = armor
      model         = 4
      extra         = sp_artillery
      brigade_model = 3
      strength      = 65
      organisation  = 25
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 301 }
      name          = "9. SS-Panzer-Div. 'Hohenstaufen'"
      type          = armor
      model         = 4
      extra         = sp_artillery
      brigade_model = 3
      strength      = 40
      organisation  = 25
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 302 }
      name          = "10. SS-Panzer-Div. 'Frundsberg'"
      type          = armor
      model         = 2
      extra         = sp_artillery
      brigade_model = 3
      strength      = 65
      organisation  = 25
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 303 }
      name         = "21. Panzer-Division"
      type         = armor
      model        = 4
      strength     = 50
      organisation = 25
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 304 }
    name     = "Abs. Genoa"
    location = 368
    division =
    { experience = 60
      id         = { type = 10602 id = 305 }
      name       = "94. Infanterie-Division"
      type       = infantry
      strength   = 80
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 306 }
      name       = "157. Gebirgsjäger-Division"
      type       = bergsjaeger
      strength   = 75
      model      = 3
    }
  }
  landunit =
  { id       = { type = 10602 id = 307 }
    name     = "Abs. Venedig"
    location = 378
    division =
    { experience = 60
      id         = { type = 10602 id = 308 }
      name       = "90. Panzergrenadier-Division"
      type       = mechanized
      strength   = 80
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 309 }
      name       = "90. Reserve-Infanterie-Division"
      type       = infantry
      strength   = 40
      model      = 4
    }
  }
  landunit =
  { location = 483
    id       = { type = 10602 id = 171 }
    name     = "OKH Reserve"
    division =
    { experience    = 60
      id            = { type = 10602 id = 172 }
      name          = "18. SS-Pz.Gr.Div. 'Horst Wessel'"
      strength      = 65
      type          = mechanized
      extra         = tank_destroyer
      model         = 2
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 173 }
      name       = "6. Panzer-Division"
      strength   = 50
      type       = armor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 174 }
      name       = "11. Infanterie-Division"
      strength   = 65
      type       = infantry
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 175 }
      name          = "35. SS-Polizei-Grenadier-Div."
      strength      = 65
      type          = mechanized
      extra         = anti_air
      model         = 2
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 176 }
      name       = "8. SS-Kav.Div. 'Florian Geyer'"
      strength   = 65
      type       = cavalry
      model      = 3
    }
  }
  landunit =
  { id       = { type = 10602 id = 179 }
    name     = "LXXVI. Panzerkorps"
    location = 514
    division =
    { experience    = 60
      id            = { type = 10602 id = 180 }
      name          = "1. Fallschirmjäger Division"
      type          = paratrooper
      strength      = 65
      extra         = anti_air
      brigade_model = 3
      organisation  = 25
      model         = 3
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 181 }
      name         = "71. Infanterie-Division"
      type         = infantry
      strength     = 65
      organisation = 25
      model        = 4
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 182 }
      name         = "162. Infanterie-Division"
      type         = infantry
      strength     = 65
      organisation = 25
      model        = 4
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 183 }
      name         = "278. Infanterie-Division"
      type         = infantry
      strength     = 65
      organisation = 25
      model        = 4
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 184 }
      name         = "5. Gebirgsjäger-Division"
      type         = bergsjaeger
      strength     = 65
      organisation = 25
      model        = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 185 }
    name     = "LI. Gebirgskorps"
    location = 514
    division =
    { experience = 60
      id         = { type = 10602 id = 186 }
      name       = "114. Jäger-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 187 }
      name          = "44. Infanterie-Division"
      type          = infantry
      strength      = 65
      extra         = tank_destroyer
      model         = 4
      brigade_model = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 188 }
      name       = "308. Infanterie-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 189 }
      name       = "334. Infanterie-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 190 }
      name       = "715. Infanterie-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 191 }
    name     = "Armee Reserve"
    location = 369
    division =
    { experience = 60
      id         = { type = 10602 id = 192 }
      name       = "98. Infanterie-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 193 }
      name       = "29. Panzergrenadier-Division"
      type       = mechanized
      strength   = 65
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 194 }
      name       = "20. Luftwaffen-Sturm-Division"
      type       = infantry
      strength   = 40
      model      = 4
    }
  }
  landunit =
  { id       = { type = 10602 id = 195 }
    name     = "I. Fallschirmjägerkorps"
    location = 514
    division =
    { experience = 60
      id         = { type = 10602 id = 196 }
      name       = "356. Infanterie-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 197 }
      name          = "4. Fallschirmjäger Division"
      type          = paratrooper
      strength      = 70
      extra         = anti_air
      brigade_model = 3
      model         = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 198 }
      name       = "362. Infanterie-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { id       = { type = 10602 id = 310 }
    name     = "XIV. Panzerkorps"
    location = 513
    division =
    { experience = 60
      id         = { type = 10602 id = 311 }
      name       = "26. Panzer-Division"
      type       = armor
      strength   = 60
      extra         = anti_air
      brigade_model = 3
      model      = 4
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 312 }
      name          = "16. SS-Pz.Gr.Div. 'Reichsführer SS'"
      type          = mechanized
      strength      = 65
      extra         = tank_destroyer
      brigade_model = 3
      model         = 2
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 313 }
      name          = "Fallschirm Pz-Div. 'Hermann Göring'"
      type          = armor
      strength      = 70
      extra         = anti_air
      brigade_model = 3
      model         = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 314 }
      name       = "65. Infanterie-Division"
      type       = infantry
      strength   = 65
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 67
    id       = { type = 10602 id = 199 }
    name     = "OKW Reserve"
    division =
    { experience = 60
      id         = { type = 10602 id = 226 }
      name       = "4. Panzer-Division"
      strength   = 1
      type       = armor
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 227 }
      name       = "5. Panzer-Division"
      strength   = 1
      type       = armor
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 228 }
      name       = "22. Panzer-Division"
      strength   = 1
      type       = armor
      model      = 3
    }
  }
  # #ids 227, 228 in k#okw reserve!
  # ########aok norwegen########
  landunit =
  { location = 118
    id       = { type = 10602 id = 238 }
    name     = "XXXIII. Korps"
    division =
    { experience = 60
      id         = { type = 10602 id = 239 }
      name       = "196. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 240 }
      name       = "181. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 125
    id       = { type = 10602 id = 241 }
    name     = "Abs. Nordnorwegen"
    division =
    { experience = 60
      id         = { type = 10602 id = 242 }
      name       = "702. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 243 }
      name       = "199. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 107
    id       = { type = 10602 id = 244 }
    name     = "LXX. Korps"
    division =
    { experience = 60
      id         = { type = 10602 id = 245 }
      name       = "68. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 246 }
      name       = "214. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 247 }
      name       = "710. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  # #### abschnitt niederlande#########
  landunit =
  { location = 47
    id       = { type = 10602 id = 248 }
    name     = "Abs. Niederlande"
    division =
    { experience = 60
      id         = { type = 10602 id = 249 }
      name       = "82. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 250 }
      name       = "719.  Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  # ######abschnitt dänemark##########
  landunit =
  { location = 294
    id       = { type = 10602 id = 251 }
    name     = "Abs. Dänemark"
    division =
    { experience = 60
      id         = { type = 10602 id = 252 }
      name       = "217. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    dig_in   = 50.000
  }
  # ######abschnitt balkan##########
  landunit =
  { location = 418
    id       = { type = 10602 id = 253 }
    name     = "V. SS Gebirgskorps"
    division =
    { experience = 60
      id         = { type = 10602 id = 254 }
      name       = "118. Jäger-Division"
      strength   = 65
      type       = infantry
      model      = 4
      extra      = engineer
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 255 }
      name       = "7. SS-Freiw.-Geb.Div. 'Prinz Eugen'"
      strength   = 65
      type       = bergsjaeger
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 256 }
      name       = "22. SS-Kav.Div. 'Maria Theresia'"
      strength   = 65
      type       = cavalry
      model      = 3
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 390
    id       = { type = 10602 id = 257 }
    name     = "XV. Gebirgskorps"
    division =
    { experience = 60
      id         = { type = 10602 id = 258 }
      name       = "264. Infanterie-Division"
      strength   = 70
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 259 }
      name       = "Panzergrenadier-Div. 'Brandenburg'"
      strength   = 70
      type       = mechanized
      model      = 2
      extra      = engineer
    }
    dig_in   = 50.000
  }
  landunit =
  { location = 494
    id       = { type = 10602 id = 260 }
    name     = "2. Panzerarmee"
    division =
    { experience = 60
      id         = { type = 10602 id = 729 }
      name       = "2. Panzerarmee"
      type       = hq
      model      = 2
      strength   = 100
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 261 }
      name       = "13. Waffen-SS Geb.Div. 'Handschar'"
      strength   = 65
      type       = bergsjaeger
      model      = 3
    }
    dig_in   = 50.000
  }
  # ######12. armee##########
  landunit =
  { location = 401
    id       = { type = 10602 id = 730 }
    name     = "12. Armee"
    division =
    { experience = 60
      id         = { type = 10602 id = 731 }
      name       = "12. Armee"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 401
    id       = { type = 10602 id = 262 }
    name     = "XVIII. Geb.Korps"
    division =
    { experience    = 60
      id            = { type = 10602 id = 263 }
      name          = "717. Infanterie-Division"
      strength      = 100
      type          = infantry
      model         = 4
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 264 }
      name       = "714. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 265 }
      name       = "704. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
  }
  landunit =
  { location = 494
    id       = { type = 10602 id = 266 }
    name     = "LXV.Korps"
    division =
    { experience = 60
      id         = { type = 10602 id = 267 }
      name       = "718. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 268 }
      name       = "342. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 269 }
      name       = "113. Infanterie-Division"
      strength   = 100
      type       = infantry
      model      = 4
    }
  }
  landunit =
  { location = 429
    id       = { type = 10602 id = 270 }
    name     = "III. SS Panzerkorps"
    division =
    { experience    = 60
      id            = { type = 10602 id = 271 }
      name          = "3. SS-Panzer-Div. 'Totenkopf'"
      strength      = 100
      type          = armor
      model         = 4
      extra         = heavy_armor
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 272 }
      name          = "Pz.Gren.-Div. 'Großdeutschland'"
      strength      = 100
      type          = armor
      model         = 4
      extra         = heavy_armor
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 10602 id = 273 }
      name          = "24. Panzer-Division"
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 3
    }
  }
  # Hungarian forces..
  landunit =
  { id       = { type = 10633 id = 23 }
    name     = "6. Corps"
    location = 500
    control  = HUN
    division =
    { experience = 20
      id         = { type = 10633 id = 24 }
      name       = "20. gyalog hadosztály"
      type       = infantry
      model      = 2
      strength   = 55
    }
    division =
    { experience = 20
      id         = { type = 10633 id = 25 }
      name       = "27. gyalog hadosztály"
      type       = infantry
      model      = 2
      strength   = 55
    }
  }
  landunit =
  { id       = { type = 10633 id = 26 }
    name     = "1. Army"
    location = 500
    control  = HUN
    division =
    { experience = 20
      id         = { type = 10633 id = 27 }
      name       = "2. gyalog hadosztály"
      type       = armor
      strength   = 55
      model      = 3
    }
    division =
    { experience = 20
      id         = { type = 10633 id = 28 }
      name       = "19. gyalog hadosztály"
      type       = infantry
      model      = 2
      strength   = 55
    }
    division =
    { experience = 20
      id         = { type = 10633 id = 29 }
      name       = "16. gyalog hadosztály"
      type       = infantry
      model      = 2
      strength   = 55
    }
    division =
    { experience = 20
      id         = { type = 10633 id = 30 }
      name       = "24. gyalog hadosztály"
      type       = infantry
      model      = 2
      strength   = 55
    }
    division =
    { experience = 20
      id         = { type = 10633 id = 31 }
      name       = "26. gyalog hadosztály"
      type       = infantry
      model      = 2
      strength   = 55
    }
    division =
    { experience = 20
      id         = { type = 10633 id = 32 }
      name       = "18. gyalog hadosztály"
      type       = infantry
      model      = 2
      strength   = 55
    }
  }
  landunit =
  { location = 38
    id       = { type = 10602 id = 726 }
    name     = "Cherbourg Garnison"
    division =
    { experience   = 60
      id           = { type = 10602 id = 221 }
      name         = "243. Infanterie-Division (mot)"
      type         = motorized
      strength     = 50
      organisation = 20
      model        = 2
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 211 }
      name         = "77. Infanterie-Division"
      type         = infantry
      strength     = 30
      organisation = 20
      model        = 4
    }
    division =
    { experience   = 60
      id           = { type = 10602 id = 732 }
      name         = "709. Infanterie-Division"
      type         = infantry
      strength     = 30
      organisation = 20
      model        = 4
    }
  }
  # ###id used up to 450
  # #############################
  # ## GERMAN NAVAL OOB 1944 ####
  # #############################
  # ## DESTROYERS - ZERSTÖRER
  navalunit =
  { id       = { type = 10602 id = 500 }
    name     = "1. Zerstörergeschwader"
    location = 296 # Rostock
    base     = 296
    division =
    { experience = 60
      id         = { type = 10602 id = 501 }
      name       = "1. Zerstörergeschwader"
      type       = destroyer
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 502 }
    name     = "2. Zerstörergeschwader"
    location = 303 # Danzig
    base     = 303
    division =
    { experience = 60
      id         = { type = 10602 id = 503 }
      name       = "2. Zerstörergeschwader"
      type       = destroyer
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 504 }
    name     = "3. Zerstörergeschwader"
    location = 303 # Danzig
    base     = 303
    division =
    { experience = 60
      id         = { type = 10602 id = 505 }
      name       = "3. Zerstörergeschwader"
      type       = destroyer
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 506 }
    name     = "4. Zerstörergeschwader"
    location = 125 # Narvik
    base     = 125
    division =
    { experience = 60
      id         = { type = 10602 id = 507 }
      name       = "4. Zerstörergeschwader"
      type       = destroyer
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 10602 id = 508 }
    name     = "5. Zerstörergeschwader"
    location = 32 # Brest
    base     = 32
    division =
    { experience = 60
      id         = { type = 10602 id = 509 }
      name       = "5. Zerstörergeschwader"
      type       = destroyer
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 10602 id = 510 }
    name     = "6. Zerstörergeschwader"
    location = 303 # Danzig
    base     = 303
    division =
    { experience = 60
      id         = { type = 10602 id = 511 }
      name       = "6. Zerstörergeschwader"
      type       = destroyer
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 10602 id = 512 }
    name     = "7. Zerstörergeschwader"
    location = 32 # Nantes
    base     = 32
    division =
    { experience = 60
      id         = { type = 10602 id = 513 }
      name       = "7. Zerstörergeschwader"
      type       = destroyer
      model      = 2
    }
  }
  # ################################
  # ## CAPITAL SHIPS
  navalunit =
  { id       = { type = 10602 id = 514 }
    name     = "Baltische Flotte"
    location = 510 # Königsberg
    base     = 510
    division =
    { experience = 60
      id         = { type = 10602 id = 659 }
      name       = "KMS Gneisenau"
      type       = battlecruiser
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 525 }
      name       = "KMS Schlesien"
      type       = battlecruiser
      model      = 0
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 526 }
      name       = "KMS Schleswig-Holstein"
      type       = battlecruiser
      model      = 0
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 515 }
      name       = "KMS Lützow"
      type       = heavy_cruiser
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 516 }
      name       = "KMS Admiral Hipper"
      type       = heavy_cruiser
      model      = 3
    }              # undergoing refits
    division =
    { experience = 60
      id         = { type = 10602 id = 517 }
      name       = "KMS Prinz Eugen"
      type       = heavy_cruiser
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 518 }
      name       = "KMS Emden"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 519 }
      name       = "KMS Nürnberg"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 520 }
      name       = "KMS Leipzig"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 521 }
      name       = "KMS Köln"
      type       = light_cruiser
      model      = 2
    }              # undergoing refits
    division =
    { experience = 60
      id         = { type = 10602 id = 650 }
      name       = "1. Truppentransporterflottille"
      type       = transport
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 651 }
      name       = "2. Truppentransporterflottille"
      type       = transport
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 652 }
      name       = "3. Truppentransporterflottille"
      type       = transport
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 653 }
      name       = "4. Truppentransporterflottille"
      type       = transport
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 654 }
      name       = "5. Truppentransporterflottille"
      type       = transport
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 655 }
      name       = "6. Truppentransporterflottille"
      type       = transport
    }
  }
  navalunit =
  { id       = { type = 10602 id = 522 }
    name     = "Atlantische Flotte"
    location = 125 # Narvik
    base     = 125
    division =
    { experience = 60
      id         = { type = 10602 id = 523 }
      name       = "KMS Tirpitz"
      type       = battleship
      model      = 3
    }              # undergoing repair from airstrike
    division =
    { experience = 60
      id         = { type = 10602 id = 524 }
      name       = "KMS Admiral Scheer"
      type       = heavy_cruiser
      model      = 3
    }              # undergoing refits
  }
  # ID's used up to 526
  navalunit =
  { id       = { type = 10602 id = 527 }
    name     = "1. Unterseebootsflotte"
    location = 125 # Narvik
    base     = 125
    division =
    { experience = 60
      id         = { type = 10602 id = 528 }
      name       = "13. Unterseebootsflottille"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 529 }
      name       = "14. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 570 }
    name     = "2. Unterseebootsflotte"
    location = 110 # Bergen
    base     = 110
    division =
    { experience = 60
      id         = { type = 10602 id = 531 }
      name       = "11. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 533 }
      name       = "17. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 534 }
    name     = "2. Unterseebootsflotte"
    location = 90 # Kiel - on way to France
    base     = 90
    division =
    { experience = 60
      id         = { type = 10602 id = 535 }
      name       = "5. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 536 }
      name       = "31. Unterseebootsflottille"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 537 }
      name       = "32. Unterseebootsflottille"
      type       = submarine
      model      = 1
    }
  }
  navalunit =
  { id       = { type = 10602 id = 571 }
    name     = "12. Unterseebootsflotte"
    location = 80 # Wilhelmsfhavn
    base     = 80
    division =
    { experience = 60
      id         = { type = 10602 id = 538 }
      name       = "22. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 660 }
      name       = "40. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 661 }
      name       = "41. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 662 }
      name       = "42. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 663 }
      name       = "43. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 664 }
      name       = "44. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 665 }
      name       = "45. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 666 }
      name       = "46. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 667 }
      name       = "47. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 668 }
      name       = "48. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 669 }
      name       = "49. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 670 }
      name       = "50. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 671 }
      name       = "51. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 672 }
      name       = "52. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 673 }
      name       = "53. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 674 }
      name       = "54. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 675 }
      name       = "55. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 676 }
      name       = "56. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 677 }
      name       = "57. Unterseebootsflottille"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 678 }
      name       = "58. Unterseebootsflottille"
      type       = submarine
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 539 }
      name       = "27. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 540 }
      name       = "33. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 541 }
    name     = "3. Unterseebootsflotte"
    location = 32 # Brest
    base     = 32
    division =
    { experience = 60
      id         = { type = 10602 id = 542 }
      name       = "1. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 543 }
      name       = "9. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 572 }
    name     = "13. Unterseebootsflotte"
    location = 325 # Bordeaux
    base     = 325
    division =
    { experience = 60
      id         = { type = 10602 id = 544 }
      name       = "7. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 545 }
      name       = "6. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 546 }
      name       = "12. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 547 }
    name     = "4. Unterseebootsflotte"
    location = 34 # Lorient
    base     = 34
    division =
    { experience = 60
      id         = { type = 10602 id = 548 }
      name       = "2. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 549 }
      name       = "10. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 550 }
      name       = "21. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 551 }
      name       = "25. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 552 }
      name       = "26. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 553 }
    name     = "5. Unterseebootsflotte"
    location = 325 # La Rochelle
    base     = 325
    division =
    { experience = 60
      id         = { type = 10602 id = 554 }
      name       = "3. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 555 }
      name       = "24. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 556 }
    name     = "6. Unterseebootsflotte"
    location = 303 # Danzig
    base     = 303
    division =
    { experience = 60
      id         = { type = 10602 id = 557 }
      name       = "4. Unterseebootsflottille"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 558 }
      name       = "8. Unterseebootsflottille"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 559 }
      name       = "16. Unterseebootsflottille"
      type       = submarine
      model      = 1
    }
  }
  navalunit =
  { id       = { type = 10602 id = 573 }
    name     = "14. Unterseebootsflotte"
    location = 510 # Königsberg
    base     = 510
    division =
    { experience = 60
      id         = { type = 10602 id = 560 }
      name       = "19. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 561 }
      name       = "20. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 562 }
    name     = "7. Unterseebootsflotte"
    location = 436 # Constanta
    base     = 436
    division =
    { experience = 60
      id         = { type = 10602 id = 563 }
      name       = "30. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 564 }
    name     = "8. Unterseebootsflotte"
    location = 401 # Thessaloniki
    base     = 401
    division =
    { experience = 60
      id         = { type = 10602 id = 565 }
      name       = "23. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 566 }
    name     = "9. Unterseebootsflotte"
    location = 513 # La Spezia
    base     = 513
    division =
    { experience = 60
      id         = { type = 10602 id = 567 }
      name       = "29. Unterseebootsflottille"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 10602 id = 568 }
    name     = "10. Unterseebootsflotte"
    location = 142 # Helsinki
    base     = 142
    division =
    { experience = 60
      id         = { type = 10602 id = 569 }
      name       = "18. Unterseebootsflottille"
      type       = submarine
      model      = 1
    }
  }
  # ##########luftwaffe##############
  airunit =
  { location = 194
    base     = 194
    id       = { type = 10602 id = 400 }
    name     = "Heeresgruppe Nord"
    division =
    { experience = 60
      id         = { type = 10602 id = 401 }
      name       = "JG 54 'Grünherz'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 402 }
      name       = "JG 3 'Udet'"
      strength   = 80
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 403 }
      name       = "Sturzkampfgeschwader 3"
      strength   = 80
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 212
    base     = 212
    id       = { type = 10602 id = 404 }
    name     = "Heeresgruppe Mitte"
    division =
    { experience = 60
      id         = { type = 10602 id = 405 }
      name       = "JG 51 'Mölders'"
      strength   = 80
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 406 }
      name       = "Schlachtgeschwader 1"
      strength   = 80
      type       = multi_role
      model      = 3
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 407 }
      name       = "Schnellkampfgeschwader 10"
      strength   = 80
      type       = cas
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 408 }
      name       = "KG 1"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 409 }
      name       = "KG 53"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 410 }
      name       = "KG 27"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 450 }
      name       = "KG 55"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
  }
  airunit =
  { location = 501
    base     = 501
    id       = { type = 10602 id = 411 }
    name     = "XL. Fliegerkorps"
    division =
    { experience = 60
      id         = { type = 10602 id = 412 }
      name       = "Jagdgeschwader 11"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 413 }
      name       = "Jagdgeschwader 52"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 414 }
      name       = "JG 53 'Pik As'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 415 }
      name       = "Stukageschwader 2 'Immelmann'"
      strength   = 80
      type       = cas
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 416 }
      name       = "Sturzkampfgeschwader 9"
      strength   = 80
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 501
    base     = 501
    id       = { type = 10602 id = 449 }
    name     = "Heeresgruppe Süd"
    division =
    { experience = 60
      id         = { type = 10602 id = 417 }
      name       = "KG 1 'Hindenburg'"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 418 }
      name       = "KG 53 'Legion Condor'"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 419 }
      name       = "KG 27 'Boelcke'"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 420 }
      name       = "KG 55 'Greif'"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
  }
  airunit =
  { location = 56
    base     = 56
    id       = { type = 10602 id = 421 }
    name     = "Heeresgruppe West"
    division =
    { experience = 60
      id         = { type = 10602 id = 422 }
      name       = "Jagdgeschwader 27"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 423 }
      name       = "JG 2 'Richthofen'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 424 }
      name       = "JG 26 'Schlageter'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 425 }
      name       = "Sturzkampfgeschwader 4"
      strength   = 80
      type       = cas
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 426 }
      name       = "Kampfgeschwader 6"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 427 }
      name       = "KG 4 'General Wever'"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 428 }
      name       = "KG 27 'Boelcke'"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 429 }
      name       = "KG 55 'Greif'"
      strength   = 80
      type       = tactical_bomber
      model      = 2
    }
  }
  airunit =
  { location = 52
    base     = 52
    id       = { type = 10602 id = 430 }
    name     = "Jagdführer West"
    division =
    { experience = 60
      id         = { type = 10602 id = 431 }
      name       = "JG 3 'Udet'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 432 }
      name       = "JG 1 'Oesau'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 433 }
      name       = "JG 5 'Eismeer'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 434 }
      name       = "ZG 26"
      strength   = 80
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 368
    base     = 368
    id       = { type = 10602 id = 435 }
    name     = "Jagdführer Oberitalien"
    division =
    { experience = 60
      id         = { type = 10602 id = 436 }
      name       = "Jagdgeschwader 4"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 437 }
      name       = "JG 77 'Herz As'"
      strength   = 80
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 75
    base     = 75
    id       = { type = 10602 id = 438 }
    name     = "Jagdführer Oberrhein"
    division =
    { experience = 60
      id         = { type = 10602 id = 439 }
      name       = "Jagdgeschwader 76"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 440 }
      name       = "Jagdgeschwader 301 "
      strength   = 80
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 463
    base     = 463
    id       = { type = 10602 id = 442 }
    name     = "Jagdführer Österreich"
    division =
    { experience = 60
      id         = { type = 10602 id = 443 }
      name       = "Jagdgeschwader 302"
      strength   = 80
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 47
    base     = 47
    id       = { type = 10602 id = 444 }
    name     = "Jagdführer Niederlande"
    division =
    { experience = 60
      id         = { type = 10602 id = 445 }
      name       = "Jagdgeschwader 400"
      strength   = 80
      type       = interceptor
      model      = 5
    }              # #me163
  }
  airunit =
  { location = 67
    base     = 67
    id       = { type = 10602 id = 446 }
    name     = "Jagdführer Ruhr"
    division =
    { experience = 60
      id         = { type = 10602 id = 447 }
      name       = "Jagdgeschwader 11"
      strength   = 80
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 60
      id         = { type = 10602 id = 448 }
      name       = "Jagdgeschwader 26"
      strength   = 80
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { id       = { type = 10602 id = 604 }
    name     = "1. V1 Batterie"
    location = 46
    base     = 46
    division =
    { experience = 60
      id         = { type = 10602 id = 605 }
      name       = "1. V1 Batterie"
      type       = flying_bomb
    }
  }
  airunit =
  { id       = { type = 10602 id = 606 }
    name     = "2. V1 Batterie"
    location = 46
    base     = 46
    division =
    { experience = 60
      id         = { type = 10602 id = 607 }
      name       = "2. V1 Batterie"
      type       = flying_bomb
    }
  }
  airunit =
  { id       = { type = 10602 id = 608 }
    name     = "3. V1 Batterie"
    location = 44
    base     = 44
    division =
    { experience = 60
      id         = { type = 10602 id = 609 }
      name       = "3. V1 Batterie"
      type       = flying_bomb
    }
  }
  airunit =
  { id       = { type = 10602 id = 610 }
    name     = "4. V1 Batterie"
    location = 44
    base     = 44
    division =
    { experience = 60
      id         = { type = 10602 id = 611 }
      name       = "4. V1 Batterie"
      type       = flying_bomb
    }
  }
  # Under Construction#
  division_development =
  { name  = "34. Unterseebootsflottille"
    type  = submarine
    model = 2
    cost  = 1.6
    id    = { type = 10602 id = 800 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "35. Unterseebootsflottille"
    type  = submarine
    model = 2
    cost  = 1.6
    id    = { type = 10602 id = 801 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "36. Unterseebootsflottille"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10602 id = 802 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "37. Unterseebootsflottille"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10602 id = 803 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "38. Unterseebootsflottille"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10602 id = 804 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "39. Unterseebootsflottille"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10602 id = 805 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "40. Unterseebootsflottille"
    type  = submarine
    model = 4
    cost  = 3.2
    id    = { type = 10602 id = 806 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "41. Unterseebootsflottille"
    type  = submarine
    model = 4
    cost  = 3.2
    id    = { type = 10602 id = 807 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "42. Unterseebootsflottille"
    type  = submarine
    model = 4
    cost  = 3.2
    id    = { type = 10602 id = 808 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "43. Unterseebootsflottille"
    type  = submarine
    model = 4
    cost  = 3.2
    id    = { type = 10602 id = 809 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "44. Unterseebootsflottille"
    type  = submarine
    model = 4
    cost  = 3.2
    id    = { type = 10602 id = 810 }
    date  = { year = 1944 month = october day = 1 }
  }
  division_development =
  { name  = "45. Unterseebootsflottille"
    type  = submarine
    model = 4
    cost  = 3.2
    id    = { type = 10602 id = 811 }
    date  = { year = 1944 month = october day = 1 }
  }
  division_development =
  { id    = { type = 10602 id = 595 }
    name  = "5. V1 Batterie"
    type  = flying_bomb
    cost  = 0.7
    model = 0
    date  = { year = 1944 month = july day = 2 }
  }
  division_development =
  { id    = { type = 10602 id = 596 }
    name  = "6. V1 Batterie"
    type  = flying_bomb
    cost  = 0.7
    model = 0
    date  = { year = 1944 month = july day = 4 }
  }
  division_development =
  { id    = { type = 10602 id = 597 }
    name  = "7. V1 Batterie"
    type  = flying_bomb
    cost  = 0.7
    model = 0
    date  = { year = 1944 month = july day = 6 }
  }
  division_development =
  { id    = { type = 10602 id = 598 }
    name  = "8. V1 Batterie"
    type  = flying_bomb
    cost  = 0.7
    model = 0
    date  = { year = 1944 month = july day = 8 }
  }
  division_development =
  { id    = { type = 10602 id = 599 }
    name  = "9. V1 Batterie"
    type  = flying_bomb
    cost  = 0.7
    model = 0
    date  = { year = 1944 month = july day = 10 }
  }
  division_development =
  { id    = { type = 10602 id = 600 }
    name  = "10. V1 Batterie"
    type  = flying_bomb
    cost  = 0.7
    model = 0
    date  = { year = 1944 month = july day = 12 }
  }
  division_development =
  { id    = { type = 10602 id = 601 }
    name  = "1. V2 Batterie"
    type  = flying_rocket
    cost  = 0.8
    model = 0
    date  = { year = 1944 month = july day = 14 }
  }
  division_development =
  { id    = { type = 10602 id = 602 }
    name  = "2. V2 Batterie"
    type  = flying_rocket
    cost  = 0.8
    model = 0
    date  = { year = 1944 month = july day = 16 }
  }
  division_development =
  { id    = { type = 10602 id = 603 }
    name  = "3. V2 Batterie"
    type  = flying_rocket
    cost  = 0.8
    model = 0
    date  = { year = 1944 month = july day = 18 }
  }
}
