
###############################
# Country definition for USA #
##############################

province =
{ id         = 1
  anti_air   = 1
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 6 current_size = 6 }
}              # Reykjavik
province =
{ id            = 18
  naval_base    = { size = 5 current_size = 5 }
  air_base      = { size = 5 current_size = 5 }

  coastalfort   = 4
  radar_station = { size = 1 current_size = 1 }
}                 # Calais
province =
{ id         = 32
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
  anti_air   = 2
}              # Brest
province = { id = 33  coastalfort = 4 } # Rennes
province =
{ id         = 34
  naval_base = { size = 5 current_size = 5 }
}              # Lorient
province = { id = 35 anti_air = 2 } # Nantes
province =
{ id          = 38
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 5 current_size = 5 }
  anti_air    = 1

  coastalfort = 4
}               # Cherbourg
province = { id = 39 anti_air = 1  coastalfort = 4 supplypool = 4500 oilpool = 2000 } # Caen
province =
{ id          = 41
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 5 current_size = 5 }

  coastalfort = 4
}               # Le Havre
province = { id = 42  coastalfort = 4 } # Dieppe
province =
{ id            = 43
  naval_base    = { size = 3 current_size = 3 }

  coastalfort   = 4
  radar_station = { size = 1 current_size = 1 }
}                 # Dunkerque
province =
{ id       = 44
  air_base = { size = 10 current_size = 10 }
  anti_air = 1
}            # Lille
province =
{ id            = 45
  naval_base    = { size = 5 current_size = 5 }

  coastalfort   = 4
  radar_station = { size = 2 current_size = 2 }
}                 # Ghent
province =
{ id            = 46
  naval_base    = { size = 10 current_size = 10 }
  air_base      = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}                 # Rotterdam
province =
{ id            = 47
  naval_base    = { size = 10 current_size = 10 }
  air_base      = { size = 8 current_size = 8 }

  coastalfort   = 4
  radar_station = { size = 2 current_size = 2 }
}                 # Amsterdam
province =
{ id       = 50
  air_base = { size = 3 current_size = 3 }
}            # Antwerp
province =
{ id            = 51
  air_base      = { size = 6 current_size = 6 }
  radar_station = { size = 2 current_size = 2 }
}                 # Brussels
province =
{ id       = 52
  air_base = { size = 8 current_size = 8 }
}            # Mons
province =
{ id       = 56
  air_base = { size = 10 current_size = 10 }
  anti_air = 3
}            # Paris
province =
{ id            = 65
  radar_station = { size = 1 current_size = 1 }
}                 # Namur
province = { id = 72 anti_air = 1 } # Metz
province = { id = 73 anti_air = 2 } # Strasbourg
province =
{ id            = 78
  radar_station = { size = 1 current_size = 1 }
}                 # Leeuwarden
province =
{ id            = 79
  radar_station = { size = 1 current_size = 1 }
}                 # Groningen
province = { id = 317 anti_air = 1 } # Chaumont
province = { id = 320 anti_air = 1 } # Vichy
province = { id = 323  coastalfort = 4 } # La Rochelle
province =
{ id          = 325
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  anti_air    = 2

  coastalfort = 4
}               # Bordeaux
province = { id = 363  coastalfort = 4 } # Nîmes
province =
{ id          = 364
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  anti_air    = 3

  coastalfort = 4
}               # Marseille
province = { id = 366 landfort = 5 } # Nice
province =
{ id         = 367
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Corsica
province = { id = 527 landfort = 3 } # Grenoble
province = { id = 544 supplypool = 500 oilpool = 200 } # Andreanof Islands
province =
{ id         = 546
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Umnak Island
province =
{ id         = 549
  anti_air   = 1
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Anchorage
province = { id = 553 supplypool = 1000 oilpool = 2000 } # Juneau
province = { id = 595 ic = 2 } # Concord
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Plattsburgh
province =
{ id       = 595
  ic       = 2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id            = 600
  ic         = 3
  anti_air      = 3
  radar_station = { size = 1 current_size = 1 }
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}                 # Boston
province =
{ id         = 602
  ic         = 4
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}              # New York
province =
{ id         = 603
 ic = 6
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Newark
province =
{ id            = 606
  ic         = 2
  air_base      = { size = 10 current_size = 10 }
  anti_air      = 3
  radar_station = { size = 1 current_size = 1 }
}                 # Washington D.C.
province = { id = 607 ic = 5 } # Baltimore
province = { id = 608 ic = 3 anti_air = 2 } # Philadelphia
province = { id = 609 ic = 1 } # Harrisburg
province = { id = 613 ic = 3 } # Buffalo
province =
{ id       = 614
  ic       = 3
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Pittsburgh
province = { id = 615 ic = 2 } # Cleveland
province =
{ id       = 616
  ic       = 8
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Detroit
province = { id = 619 ic = 1 } # Indianapolis
province =
{ id       = 620
  ic       = 3
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Chicago
province =
{ id       = 621
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Milwaukee
province =
{ id            = 633
  naval_base    = { size = 10 current_size = 10 }
  air_base      = { size = 10 current_size = 10 }
  anti_air      = 3
  ic         = 4
  radar_station = { size = 1 current_size = 1 }
}                 # Norfolk
province =
{ id         = 634
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
}              # Wilmington
Province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 640
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province =
{ id              = 643
  nuclear_reactor = { size = 4 current_size = 4 }
}                   # Asheville
province =
{ id         = 644
  anti_air = 1
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
}              # Charleston
province =
{ id         = 648
  anti_air = 1
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Jacksonville
province =
{ id         = 651
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Miami
province =
{ id            = 662
  naval_base    = { size = 6 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
  supplypool    = 100
}                 # Midway Island
province =
{ id            = 663
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  radar_station = { size = 4 current_size = 4 }
  supplypool    = 1000
  oilpool       = 2000
}                 # Pearl Harbour
province =
{ id       = 670
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Atlanta
Province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Memphis
province =
{ id         = 676
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
}              # Mobile
province =
{ id         = 678
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Biloxi
province = { id = 680 ic = 4 } # New Orleans
province =
{ id       = 684
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Little Rock
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # St. Louis
province =
{ id       = 692
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Des Moines
province =
{ id       = 693
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
province =
{ id       = 698
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Bismarck
province =
{ id       = 707
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Denver
Province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Oklahoma City
province =
{ id       = 716
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Houston
province =
{ id          = 723
  rocket_test = { size = 1 current_size = 1 }
}               # Los Cruses
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 730
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Phoenix
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Salt Lake City
Province =
{ id         = 748
  anti_air   = 1
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 8 current_size = 8 }
}              # Corpus Christi
province =
{ id         = 761
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Diego
province =
{ id            = 762
  naval_base    = { size = 10 current_size = 10 }
  air_base      = { size = 10 current_size = 10 }
  anti_air      = 2
  radar_station = { size = 1 current_size = 1 }
}                 # Los Angeles
province =
{ id       = 763
  air_base = { size = 6 current_size = 6 }
}            # Fresno
province =
{ id            = 765
  naval_base    = { size = 10 current_size = 10 }
  air_base      = { size = 10 current_size = 10 }
  anti_air      = 2
  radar_station = { size = 1 current_size = 1 }
}                 # San Francisco
province =
{ id       = 764
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id         = 765
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Francisco
province =
{ id         = 766
  naval_base = { size = 6 current_size = 6 }
}              # Redding
province =
{ id         = 780
  ic         = 2
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Seattle
province =
{ id       = 783
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Portland
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Tulsa
province =
{ id            = 889
  anti_air      = 3
  coastalfort = 6
  radar_station = { size = 1 current_size = 1 }
  air_base    = { size = 4 current_size = 4 }
  Naval_base  = { size = 4 current_size = 4 }
  supplypool    = 100
}                 # Colon
province = { id = 895 supplypool = 50 } # Puerto Rico
province =
{ id         = 939
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
  anti_air   = 2
}              # Tunis
province =
{ id         = 946
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Bougie
province = { id = 949 anti_air = 2 supplypool = 2500 oilpool = 2000 } # Algiers
province =
{ id         = 950
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Mostaganem
province = { id = 958 anti_air = 1 } # Casablanca
province =
{ id         = 1408
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 500
  oilpool    = 200
}              # Attu Island
province =
{ id         = 1624
  air_base   = { size = 4 current_size = 4 }
  anti_air   = 2
  supplypool = 100
}              # Guam
province =
{ id         = 1668
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 7 current_size = 7 }
}              # Admiralty Islands
province =
{ id         = 1669
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 500
  oilpool    = 200
}              # New Ireland
province =
{ id         = 1670
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 7 current_size = 7 }
}              # Rabaul
province =
{ id         = 1672
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
  anti_air   = 1
}              # Lae
province =
{ id            = 1679
  naval_base    = { size = 6 current_size = 6 }
  air_base      = { size = 6 current_size = 6 }

  coastalfort   = 1
  oilpool       = 2000
  supplypool    = 2500
  anti_air      = 3
  radar_station = { size = 2 current_size = 2 }
}                 # Port Moresby
province =
{ id         = 1682
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 500
  oilpool    = 200
}              # Bougainville
province =
{ id         = 1685
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 2500
  oilpool    = 2000
}              # Guadalcanal
province = { id = 1688 supplypool = 2500 oilpool = 2000 } # Bank Islands
province =
{ id         = 1689
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Espirtu Santo
province =
{ id         = 1692
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 2500
  oilpool    = 2000
}              # Noumea
province =
{ id         = 1753
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
  supplypool = 500
  oilpool    = 200
}              # Vanua Levu
province = { id = 1756 supplypool = 50 } # Samoa
province = { id = 1762 supplypool = 1 oilpool = 200 } # Phoenix Island
province = { id = 1765 supplypool = 50 oilpool = 200 } # Palmyra
province = { id = 1766 supplypool = 1 oilpool = 200 } # Johnson Island
province = { id = 1786 anti_air = 2 supplypool = 100
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
} # Wake Island

#####################
# Country main data #
#####################

country =
{ tag                    = USA
  # Resource Reserves
  energy                 = 90000
  metal                  = 90000
  rare_materials         = 90000
  oil                    = 90000
  supplies               = 90000
  manpower               = 1280
  transports             = 1825
  escorts                = 500
  capital                = 606
  SpyInfo                = { country = "USA" NumberOfSpies = 14 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    freedom           = 10
    free_market       = 10
    professional_army = 1
    defense_lobby     = 9
    interventionism   = 6
  }
  # corsica
  nationalprovinces      = { 651 650 649 648 677 676 672 646 647 669 670 644 645 634 635 636 637 643 633 632 631 638 639 606 607 605 604 603 612 602
			     598 593 592 608 609 610 611 594 597 595 596 582 583 599 600 601 613 614 629 630 640 641 642 671 673 674 675 678 679 615
			     628 617 616 618 619 627 680 681 682 683 684 685 686 687 688 689 626 625 620 621 624 623 622 690 691 692 693 694 695 696
			     697 698 699 787 788 789 790 791 792 793 710 711 712 713 714 715 716 717 719 720 721 748 722 723 724 725 727 728 729 730
			     731 732 733 706 707 708 709 705 704 703 702 701 700 775 774 770 771 772 773 776 777 779 780 781 782 783 784 785 786 778
			     769 768 734 736 735 767 761 762 763 764 765 766 553 551 550 549 548 547 546 545 544 543 542 718 726 746 895 889
			   }
  ownedprovinces         = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1786 1624 1408 1    2
			     800  1666 1667 1672 1675 1676 1677 1678 1679 1680 1668 1669 1671 1681 1670 1622 1684 1685 1686 1763 1764 1765 1761 1767
			     1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1614 1682 1683 1690 1688 1691 1687 1692 1689 956  969  968  959  958
			     960  966  1014 970  1013 943  942  945  944  946  947  949  948  951  950  952  953  935  934  936  938  937  939  940
			     941  1758 529  527  366  365  367  364  363  362  358  328  327  326  325  324  359  361  319  360  322  323  59   60
			     61   62   63   318  317  316  73   72   64   53   44   43   18   54   42   55   41   56   57   58   32   33   34   35
			     36   37   38   39   40   320  321  528  46   47   48   49   77   78   79   45   50   51   52   65   68   69   70
			   }
  controlledprovinces    = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1408 1    2    800  1672
			     1675 1677 1678 1679 1680 1668 1669 1671 1681 1622 1683 1684 1685 1686 1763 1764 1765 1761 1767 1768 1769 1770 1757 1759
			     1760 1752 1753 1754 1755 37   39   1627 1620 1618 1615 1663 1664 1665 1600 1601 1602 1603 1605 1606 1607 1608 1611 1614
			     1667 1682 1690 1688 1691 1687 1692 1689 956  969  968  959  958  960  966  1014 970  1013 943  942  945  944  946  947
			     949  948  951  950  952  953  935  934  936  938  937  939  940  941  1758 1619 1617 1604 1661 367
			   }
  # usa-pacific
  # 658 659 660 661 662 663
  # USA 1944 techs
  # ######################
  techapps               = { 1010  1020  1030  1040  1040  1050  1070  1080  1090  1110  1120  1130  1150  1160  1170  1180  1190  1200  1210  12100
			     12110 1220  1230  1240  1250  1260  1270  1280  1310  1320  1330  1340  1350  1360  14000 14010 14020 14030
			     2010  2020  2030  2030  2040  2050  2060  2070  2080  2090  2100  2110  2150  2160  2170  2180  2190  2200  2220  2230
			     2240  2260  2270  2290  2300  2310  2320  2330  2340  2350  2360  2370  2380  2400  2410  2420  2430  2450  2460  2470
			     2480  2490  2510  2520  2530  3010  3020  3030  3040  3050  3070  3080  3090  3100  3110  3130  3140  3150  3160
			     3170  3190  3200  3210  3220  3230  3250  3260  3270  3280  3290  3320  3330  3340  3350  3360  3370  3400  3410  3420
			     3430  4010  4020  4030  4040  4050  4060  4070  4080  4090  4100  4110  4120  4130  4140  4150  4160  4170  4180  4190
			     4200  4210  4220  4230  4240  4250  4260  4280  5010  5020  5030  5050  5060  5070  5080  5090  5100  5110  5120  5130
			     5140  5150  5160  5180  5190  5200  5210  5220  5230  5310  5320  5330  5340  5350  5360  5370  5380  5390  5400  5410
			     5420  5430  5440  5450  5470  5480  5490  5500  5510  5520  5530  5540  5550  5560  5570  6010  6020  6040  6050  6060
			     6070  6080  6090  7140  7150  7160  8010  8020  8030  8040  8050  8060  8090  8100  8110  8130  8140  8160
			     8170  8180  8230  8240  8250  8270  8310  8320  8350  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110
			     9120  9130  9140  9150  9160  9170  9180  9190  9200  9210  9220  9230  9240  9250  9260  9270  9280  9290  9300  9310
			     9320  9330  9340  9350  9360  9370  9380  9390  9400  9410  9420  9430  9440  9450  9460
			   }
  inventions             = { 8000 8001 8010 8011 }
  diplomacy =
  { relation = { tag = LIB access = yes value = 200 }
    relation = { tag = CHI value = 130 }
    relation =
    { tag        = ARG
      value      = 75
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation = { tag = AST value = 150 }
    relation = { tag = BEL value = 75 }
    relation = { tag = BHU value = 100 }
    relation =
    { tag        = BOL
      value      = 85
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = BRA
      value      = 120
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = CAN
      value      = 200
      guaranteed = { day = 30 month = december year = 1942 }
    }
    # relation = { tag = CHI value = 100 }
    relation =
    { tag        = CHL
      value      = 100
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = COL
      value      = 75
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = COS
      value      = 100
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = CUB
      value      = 200
      guaranteed = { day = 30 month = december year = 1942 }
    }
    # relation = { tag = DEN value = 75 }
    relation =
    { tag        = DOM
      value      = 125
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = ECU
      value      = 75
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation = { tag = ENG value = 200 }
    relation = { tag = FIN value = -200 }
    relation = { tag = FRA value = 65 }
    relation = { tag = GER value = -200 }
    relation =
    { tag        = GUA
      value      = 125
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = HAI
      value      = 100
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = HON
      value      = 100
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation = { tag = IRE value = 75 }
    # relation = { tag = IRQ value = 120 }
    relation = { tag = JAP value = -200 }
    relation = { tag = MAN value = -200 }
    # relation = { tag = MEN value = 1 }
    relation =
    { tag        = MEX
      value      = 125
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation = { tag = NEP value = 100 }
    relation =
    { tag        = NIC
      value      = 100
      guaranteed = { day = 30 month = december year = 1942 }
    }
    # relation = { tag = NOR value = 75 }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation =
    { tag        = PAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = PAR
      value      = 75
      guaranteed = { day = 30 month = december year = 1942 }
    }
    # relation = { tag = PHI value = 200 }
    relation = { tag = POR value = 100 }
    relation =
    { tag        = PRU
      value      = 75
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation = { tag = SAF value = 125 }
    relation =
    { tag        = SAL
      value      = 100
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation = { tag = SOV value = 200 }
    relation = { tag = SWE value = 75 }
    relation =
    { tag        = URU
      value      = 100
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation =
    { tag        = VEN
      value      = 125
      guaranteed = { day = 30 month = december year = 1942 }
    }
    relation = { tag = YEM value = 100 }
  }
  dormant_ministers      = { 6006 6176 6009 6162 6158 6010 6107 6007 6008 6108 6173 6004 6041 6094 6114 }
  headofstate            = { type = 9 id = 6001 }
  headofgovernment       = { type = 9 id = 6044 }
  foreignminister        = { type = 9 id = 6003 }
  armamentminister       = { type = 9 id = 6077 }
  ministerofsecurity     = { type = 9 id = 6005 }
  ministerofintelligence = { type = 9 id = 6128 }
  chiefofstaff           = { type = 9 id = 6136 }
  chiefofarmy            = { type = 9 id = 6144 }
  chiefofnavy            = { type = 9 id = 6163 }
  chiefofair             = { type = 9 id = 6167 }
  # ### in division_development
  province_development =
  { id             = { type = 4712 id = 9935652452 }
    name           = ""
    progress       = 0.0000
    location       = 643
    cost           = 15.0000
    date           = { year = 1944 month = november day = 14 hour = 0 }
    manpower       = 0.0000
    total_progress = 0.0000
    size           = 1
    done           = 0
    days           = 180
    days_for_first = 180
    type           = nuclear_reactor
  }
  # ## USA OOB 1944 Author: mh ###
  # ###western theatre
  landunit =
  { location = 39
    id       = { type = 10178 id = 2250 }
    name     = "1st Army HQ"
    division =
    {
      experience = 35
      id         = { type = 10178 id = 2251 }
      name       = "1st Army HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 39
    id       = { type = 10178 id = 1 }
    name     = "1st Army"
    mission =
    { type       = attack
      target     = 38
      percentage = 35.000
      night      = yes
      day        = yes
      startdate  = { year = 1944 month = june day = 10 hour = 0 }
      task       = 1
      location   = 38
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 2 }
      name          = "1st 'Big Red One' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 3 }
      name          = "2nd 'Indianhead' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 4 }
      name          = "4th 'Iron Horse' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 5 }
      name          = "5th 'Red Devils' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 6 }
      name          = "8th 'Pathfinder' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 7 }
      name          = "28th 'Keystone' NG Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 8 }
      name          = "29th 'Blue and Gray' NG Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 9 }
      name          = "30th 'Old Hickory' NG Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 10 }
      name          = "79th Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 11 }
      name          = "6th Armored 'Super Sixth' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 12 }
      name          = "83rd 'Thunderbolts' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { location = 37
    id       = { type = 10178 id = 14 }
    name     = "5th Corps"
    mission =
    { type       = attack
      target     = 38
      percentage = 35.000
      night      = yes
      day        = yes
      startdate  = { year = 1944 month = june day = 10 hour = 0 }
      task       = 1
      location   = 38
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 15 }
      name       = "82nd Airborne 'All American' Division"
      strength   = 100
      type       = paratrooper
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 16 }
      name       = "101st US Air. 'Screaming Eagles Div."
      strength   = 100
      type       = paratrooper
      model      = 2
    }
  }
  landunit =
  { location = 37
    id       = { type = 10178 id = 18 }
    name     = "7th Corps"
    division =
    { experience    = 35
      id            = { type = 10178 id = 19 }
      name          = "2nd Armored 'Hell on Wheels' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 20 }
      name          = "3rd Armored 'Spearhead' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 21 }
      name          = "4th Armored 'Breakthrough' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 22 }
      name          = "5th Armored 'Victory' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { location = 37
    id       = { type = 10178 id = 2252 }
    name     = "3rd Army HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2253 }
      name       = "3rd Army HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 37
    id       = { type = 10178 id = 24 }
    name     = "3rd Army"
    division =
    { experience    = 35
      id            = { type = 10178 id = 25 }
      name          = "9th 'Old Reliables' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 26 }
      name          = "80th 'Blue Ridge Division'"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 27 }
      name          = "82nd Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 28 }
      name          = "90th 'Tough Ombres' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 29 }
      name          = "35th 'Santa Fe' NG Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { location = 518
    id       = { type = 10178 id = 2270 }
    name     = "15th Army Group HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2271 }
      name       = "15th Army Group HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 602
    id       = { type = 10178 id = 2254 }
    name     = "9th Army HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2255 }
      name       = "9th Army HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 602
    id       = { type = 10178 id = 36 }
    name     = "9th Army"
    division =
    { experience    = 35
      id            = { type = 10178 id = 37 }
      name          = "26th 'Yankee' NG Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 38 }
      name          = "44th Infantry NG Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 39 }
      name          = "84th 'Railsplitters' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 40 }
      name          = "94th 'Neuf Quatres' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 41 }
      name          = "95th 'Victory' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 42 }
      name          = "102nd 'Ozarks' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 43 }
      name          = "8th Armored 'Thundering Herd' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 44 }
      name          = "9th Armored 'Phantom' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 45 }
      name          = "10th Armored 'Tiger' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 46 }
      name          = "99th 'Checkerboard' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { location = 602
    id       = { type = 10178 id = 48 }
    name     = "17. Airborne Division"
    division =
    { experience = 35
      id         = { type = 10178 id = 49 }
      name       = "17th AB 'Thunder from Heaven' Div."
      strength   = 100
      type       = paratrooper
      model      = 2
    }
  }
  landunit =
  { location = 14
    id       = { type = 10178 id = 51 }
    name     = "78. Infantry Division"
    division =
    { experience    = 35
      id            = { type = 10178 id = 52 }
      name          = "78th Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { location = 21
    id       = { type = 10178 id = 54 }
    name     = "7. Armored Division"
    division =
    { experience    = 35
      id            = { type = 10178 id = 55 }
      name          = "7th Armored 'Lucky Seventh' Div."
      strength      = 100
      type          = armor
      model         = 3
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 10178 id = 56 }
    name     = "II. Corps"
    location = 515
    division =
    { experience    = 35
      id            = { type = 10178 id = 57 }
      name          = "34th 'Red Bull' NG Division"
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
      strength      = 100
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 58 }
      name          = "88th 'Blue Devils' Division"
      type          = mechanized
      model         = 2
      extra         = tank_destroyer
      brigade_model = 3
      strength      = 100
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 59 }
      name          = "91st 'Pine Tree' Division"
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10178 id = 60 }
    name     = "IV. Corps"
    location = 521
    division =
    { experience    = 35
      id            = { type = 10178 id = 61 }
      name          = "1st Armored 'Old Ironsides' Div."
      type          = armor
      extra         = sp_artillery
      brigade_model = 2
      strength      = 100
      model         = 3
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 62 }
      name          = "85th 'Custer Division'"
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
      strength      = 100
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 63 }
      name          = "45th Task Force"
      type          = motorized
      model         = 2
      extra         = anti_air
      brigade_model = 3
      strength      = 100
    }
  }
  landunit =
  { location = 1668
    id       = { type = 10178 id = 2256 }
    name     = "SWPAC HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2257 }
      name       = "SWPAC HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 1661
    id       = { type = 10178 id = 64 }
    name     = "3/SWPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 65 }
      name          = "41st 'Sunset' NG Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { location = 1668
    id       = { type = 10178 id = 67 }
    name     = "4/SWPAC"
    division =
    { experience = 35
      id         = { type = 10178 id = 68 }
      name       = "1st Cavalry 'The 1st Team' Div."
      strength   = 100
      type       = infantry
      model      = 3
      extra      = engineer
    }
  }
  landunit =
  { location = 1669
    id       = { type = 10178 id = 70 }
    name     = "5/SWPAC"
    division =
    { experience = 35
      id         = { type = 10178 id = 71 }
      name       = "11th US Airborne 'The Angels' Division"
      strength   = 100
      type       = paratrooper
      model      = 2
    }
  }
  landunit =
  { location = 1682
    id       = { type = 10178 id = 73 }
    name     = "6/SWPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 74 }
      name          = "43rd 'Winged Victory' NG Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { location = 1685
    id       = { type = 10178 id = 76 }
    name     = "7/SWPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 77 }
      name          = "25th 'Tropic Lightning' Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 78 }
      name       = "23rd 'Americal Division'"
      strength   = 100
      type       = infantry
      model      = 3
      extra      = engineer
    }
  }
  landunit =
  { location = 1608
    id       = { type = 10178 id = 2259 }
    name     = "CPAC HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2260 }
      name       = "CPAC HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 1608
    id       = { type = 10178 id = 80 }
    name     = "1/CPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 81 }
      name          = "7th 'Bayonet!' Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { location = 1608
    id       = { type = 10178 id = 84 }
    name     = "2/CPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 85 }
      name          = "3rd US Marine Division"
      strength      = 100
      type          = marine
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 86 }
      name       = "4th US Marine Division"
      strength   = 100
      type       = marine
      model      = 2
      extra      = engineer
    }
  }
  # landunit = { location = 1671 #should be Cape Gloucester id = { type = 10178 id = 88 } name = "8/SWPAC"
  # division = { experience = 35 id = { type = 10178 id = 89 } name = "7th US Marine Division" strength = 100 type = marine model = 2 extra = artillery brigade_model = 5 }
  # }
  landunit =
  { location = 1753
    id       = { type = 10178 id = 91 }
    name     = "9/SWPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 92 }
      name          = "37th 'Buckeye' NG Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { location = 663
    id       = { type = 10178 id = 94 }
    name     = "3/CPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 95 }
      name          = "5th 'Red Devils' Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 96 }
      name          = "31st 'Dixie' NG Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 97 }
      name          = "33rd 'Golden Cross' NG Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 98 }
      name          = "38th 'Cyclone' NG Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 99 }
      name          = "48th 'Lucky Devils' Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 101 }
      name       = "81st 'Wildcat' Division"
      strength   = 100
      type       = infantry
      model      = 3
      extra      = engineer
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 102 }
      name       = "93rd Infantry (Colored) Division"
      strength   = 100
      type       = infantry
      model      = 3
      extra      = engineer
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 103 }
      name       = "96th 'Deadeye' Division"
      strength   = 100
      type       = infantry
      model      = 3
      extra      = engineer
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 104 }
      name          = "98th 'Iroquois Division'"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = anti_air
      brigade_model = 3
    }
  }
  landunit =
  { location = 549
    id       = { type = 10178 id = 2262 }
    name     = "NPAC HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2263 }
      name       = "NPAC HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 662
    id       = { type = 10178 id = 106 }
    name     = "Midway Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 107 }
      name       = "Midway Garrison"
      strength   = 50
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 662
    id       = { type = 10178 id = 2280 }
    name     = "Asheville Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2281 }
      name       = "Asheville Garrison"
      strength   = 50
      type       = garrison
      model      = 2
    }
  }

  landunit =
  { location = 1766
    id       = { type = 10178 id = 109 }
    name     = "Johnston I. Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 110 }
      name       = "Johnston I. Garrison"
      strength   = 50
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 1765
    id       = { type = 10178 id = 112 }
    name     = "Palmyra Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 113 }
      name       = "Palmyra Garrison"
      strength   = 50
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 1762
    id       = { type = 10178 id = 115 }
    name     = "Baker I. Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 116 }
      name       = "Baker I. Garrison"
      strength   = 50
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 1408
    id       = { type = 10178 id = 118 }
    name     = "Attu I. Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 119 }
      name       = "Attu I. Garrison"
      strength   = 50
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 544
    id       = { type = 10178 id = 121 }
    name     = "Atka I. Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 122 }
      name       = "Atka I. Garrison"
      strength   = 50
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 1665
    id       = { type = 10178 id = 123 }
    name     = "1/SWPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 124 }
      name          = "1st US Marine 'The Old Breed' Div."
      strength      = 100
      type          = marine
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 125 }
      name          = "6th 'Sightseeing Sixth' Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 126 }
      name       = "24th 'Victory' Division"
      strength   = 100
      type       = infantry
      model      = 3
      extra      = engineer
    }
  }
  landunit =
  { location = 1667
    id       = { type = 10178 id = 127 }
    name     = "2/SWPAC"
    division =
    { experience    = 35
      id            = { type = 10178 id = 128 }
      name          = "32nd 'Red Arrow' NG Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { location = 1627
    id       = { type = 10178 id = 2264 }
    name     = "Marine Corps HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2265 }
      name       = "Marine Corps HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 1627
    id       = { type = 10178 id = 129 }
    name     = "V. Amphib. Corps"
    division =
    { experience    = 35
      id            = { type = 10178 id = 130 }
      name          = "77th Infantry Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 131 }
      name          = "2nd US Marine 'Follow Me' Division"
      strength      = 100
      type          = marine
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 132 }
      name       = "27th 'New York Division' NG"
      strength   = 100
      type       = infantry
      model      = 3
      extra      = engineer
    }
  }
  # ##added for balance
  landunit =
  { location = 762
    id       = { type = 10178 id = 133 }
    name     = "1st US Marine Corps"
    division =
    { experience = 35
      id         = { type = 10178 id = 134 }
      name       = "5th US Marine Division"
      strength   = 100
      type       = marine
      model      = 2
      extra      = engineer
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 135 }
      name          = "6th US Marine Division"
      strength      = 100
      type          = marine
      model         = 2
      extra         = artillery
      brigade_model = 5
    }
  }
  landunit =
  { location = 606
    id       = { type = 10178 id = 2266 }
    name     = "East Coast HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2267 }
      name       = "East Coast HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 606
    id       = { type = 10178 id = 137 }
    name     = "East Coast Reserves"
    division =
    { experience    = 35
      id            = { type = 10178 id = 138 }
      name          = "97th 'Trident' Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 139 }
      name          = "92nd 'Buffalo Soldiers' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 140 }
      name          = "89th 'Midwest Division'"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 141 }
      name          = "87th 'Golden Acorns' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 142 }
      name       = "86th 'Blackhawk' Division"
      strength   = 100
      type       = mechanized
      model      = 2
      extra      = engineer
    }
  }
  landunit =
  { location = 765
    id       = { type = 10178 id = 2268 }
    name     = "West Coast HQ"
    division =
    { experience = 35
      id         = { type = 10178 id = 2269 }
      name       = "West Coast HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 765
    id       = { type = 10178 id = 143 }
    name     = "West Coast Reserves"
    division =
    { experience    = 35
      id            = { type = 10178 id = 144 }
      name          = "36th 'Texas' NG Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 145 }
      name          = "39th 'Cougars' Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 146 }
      name          = "21st Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 147 }
      name          = "22nd Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 148 }
      name       = "76th 'Onaway Division'"
      strength   = 100
      type       = mechanized
      model      = 2
      extra      = engineer
    }
  }
  landunit =
  { location = 583
    id       = { type = 10178 id = 2149 }
    name     = "ME Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2150 }
      name       = "1st ME National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2200 }
      name       = "2nd ME National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2201 }
      name       = "3rd ME National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 601
    id       = { type = 10178 id = 2151 }
    name     = "CT Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2152 }
      name       = "1st CT National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2202 }
      name       = "2nd CT National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2203 }
      name       = "3rd CT National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 605
    id       = { type = 10178 id = 2180 }
    name     = "DE Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2153 }
      name       = "1st DE National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2204 }
      name       = "2nd DE National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2205 }
      name       = "3rd DE National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 633
    id       = { type = 10178 id = 2154 }
    name     = "VA Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2155 }
      name       = "1st VA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2206 }
      name       = "2nd VA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2207 }
      name       = "3rd VA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 644
    id       = { type = 10178 id = 2156 }
    name     = "SC Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2157 }
      name       = "1st SC National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2208 }
      name       = "2nd SC National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2209 }
      name       = "3rd SC National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 646
    id       = { type = 10178 id = 2158 }
    name     = "GA Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2159 }
      name       = "1st GA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2210 }
      name       = "2nd GA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2211 }
      name       = "3rd GA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 648
    id       = { type = 10178 id = 2179 }
    name     = "FL Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2181 }
      name       = "1st FL National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2212 }
      name       = "2nd FL National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2213 }
      name       = "3rd FL National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 680
    id       = { type = 10178 id = 2161 }
    name     = "LA Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2162 }
      name       = "1st LA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2214 }
      name       = "2nd LA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2215 }
      name       = "3rd LA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 716
    id       = { type = 10178 id = 2163 }
    name     = "TX Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2164 }
      name       = "1st TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2216 }
      name       = "2nd TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2217 }
      name       = "3rd TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 748
    id       = { type = 10178 id = 2165 }
    name     = "TX Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2166 }
      name       = "4th TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2218 }
      name       = "5th TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2219 }
      name       = "6th TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 762
    id       = { type = 10178 id = 2167 }
    name     = "CA Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2168 }
      name       = "1st CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2220 }
      name       = "2nd CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2221 }
      name       = "3rd CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 765
    id       = { type = 10178 id = 2169 }
    name     = "CA Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2170 }
      name       = "4th CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2222 }
      name       = "5th CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2223 }
      name       = "6th CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 783
    id       = { type = 10178 id = 2171 }
    name     = "OR Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2172 }
      name       = "1st OR National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2224 }
      name       = "2nd OR National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2225 }
      name       = "3rd OR National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 782
    id       = { type = 10178 id = 2173 }
    name     = "WA Garrison"
    division =
    { experience = 35
      id         = { type = 10178 id = 2174 }
      name       = "1st WA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2226 }
      name       = "2nd WA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2227 }
      name       = "3rd WA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 889
    id       = { type = 10178 id = 2175 }
    name     = "Channel Force"
    division =
    { experience    = 35
      id            = { type = 10178 id = 2176 }
      name          = "1/Channel Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 3
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 2177 }
      name          = "2/Channel Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = artillery
      brigade_model = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2178 }
      name       = "3/Channel Force"
      strength   = 100
      type       = garrison
      model      = 2
      extra      = engineer
    }
  }
  landunit =
  { location = 946
    id       = { type = 10178 id = 2228 }
    name     = "Algiers Garrison"
    division =
    { experience    = 35
      id            = { type = 10178 id = 2229 }
      name          = "Algiers Garrison Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 3
    }
  }
  landunit =
  { location = 949
    id       = { type = 10178 id = 2230 }
    name     = "Orléansville Garrison"
    division =
    { experience    = 35
      id            = { type = 10178 id = 2231 }
      name          = "Orléansville Garrison Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 3
    }
  }
  landunit =
  { location = 950
    id       = { type = 10178 id = 2232 }
    name     = "Oran Garrison"
    division =
    { experience    = 35
      id            = { type = 10178 id = 2233 }
      name          = "Oran Garrison Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 3
    }
  }
  landunit =
  { location = 960
    id       = { type = 10178 id = 2234 }
    name     = "Casablanca Garrison"
    division =
    { experience    = 35
      id            = { type = 10178 id = 2235 }
      name          = "Casablanca Garrison Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 3
    }
  }
  landunit =
  { location = 1
    id       = { type = 10178 id = 2236 }
    name     = "Reykavik Garrison"
    division =
    { experience    = 35
      id            = { type = 10178 id = 2237 }
      name          = "Reykavik Garrison Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 3
    }
  }
  landunit =
  { location = 2
    id       = { type = 10178 id = 2238 }
    name     = "Akrueyri Garrison"
    division =
    { experience    = 35
      id            = { type = 10178 id = 2239 }
      name          = "Akrueyri Garrison Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 3
    }
  }
#  landunit =
#  { id       = { type = 10178 id = 300 }
#    name     = "Panama Canal Force"
#    location = 889
#    division =
#    { id            = { type = 10178 id = 305 }
#      name          = "Panama Canal Garrison"
#      type          = garrison
#      locked        = yes
#      extra         = artillery
#      brigade_model = 2
#    }
#  }
  # ######id up to 286
  # ########################
  # ##US Naval OOB - 1944###
  # ########################
  # Task Group 58.1#
  navalunit =
  { id       = { type = 10178 id = 1000 }
    name     = "Task Group 58.1"
    location = 2174
    base     = 1608
    division =
    {
      id            = { type = 10178 id = 1001 }
      name          = "USS Hornet"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1002 }
      name          = "USS Yorktown"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1003 }
      name          = "USS Independence"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1004 }
      name       = "USS Baltimore"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1005 }
      name       = "USS Boston"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1006 }
      name       = "USS Canberra"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1007 }
      name       = "USS Oakland"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1008 }
      name       = "1st Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1009 }
      name       = "2nd Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1010 }
      name       = "3rd Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.2#
  navalunit =
  { id       = { type = 10178 id = 1011 }
    name     = "Task Group 58.2"
    location = 2174
    base     = 1668
    division =
    {
      id            = { type = 10178 id = 1012 }
      name          = "USS Bunker Hill"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1013 }
      name          = "USS Wasp"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1014 }
      name          = "USS Princeton"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 2504 }
      name          = "USS Belleau Wood"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1015 }
      name       = "USS Biloxi"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1016 }
      name       = "USS Mobile"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1017 }
      name       = "USS San Juan"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1018 }
      name       = "USS Santa Fe"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1019 }
      name       = "4th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1020 }
      name       = "5th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1021 }
      name       = "6th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.3#
  navalunit =
  { id       = { type = 10178 id = 1022 }
    name     = "Task Group 58.3"
    location = 2174
    base     = 1668
    division =
    {
      id            = { type = 10178 id = 1023 }
      name          = "USS Enterprise"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 2
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1024 }
      name          = "USS Lexington"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1025 }
      name          = "USS Cowpens"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 2502 }
      name          = "USS Monterey"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 2503 }
      name          = "USS Langley"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1026 }
      name       = "USS Indianapolis"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1027 }
      name       = "USS Birmingham"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1028 }
      name       = "USS Cleveland"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1029 }
      name       = "USS Montpelier"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1030 }
      name       = "USS Reno"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1031 }
      name       = "7th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1032 }
      name       = "8th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1033 }
      name       = "9th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.4#
  navalunit =
  { id       = { type = 10178 id = 1034 }
    name     = "Task Group 58.4"
    location = 2174
    base     = 1668
    division =
    {
      id            = { type = 10178 id = 1035 }
      name          = "USS Essex"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1036 }
      name          = "USS Cabot"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 2500 }
      name          = "USS Bataan"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 2501 }
      name          = "USS San Jacinto"
      type          = escort_carrier
      model         = 1
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1037 }
      name       = "USS Houston"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1038 }
      name       = "USS Miami"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1039 }
      name       = "USS San Diego"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1040 }
      name       = "USS Vincennes"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1041 }
      name       = "10th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1042 }
      name       = "11th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1043 }
      name       = "12th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.5#
  navalunit =
  { id       = { type = 10178 id = 1044 }
    name     = "Task Group 58.5"
    location = 2174
    base     = 1608
    division =
    { experience = 35
      id         = { type = 10178 id = 1045 }
      name       = "USS California"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1046 }
      name       = "USS Colorado"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1047 }
      name       = "USS Idaho"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1048 }
      name       = "USS Maryland"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1049 }
      name       = "USS New Mexico"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1050 }
      name       = "USS Pennsylvania"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1051 }
      name       = "USS Tennessee"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1052 }
      name       = "USS Honolulu"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1053 }
      name       = "16th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1054 }
      name       = "17th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1055 }
      name       = "18th Destroyer Division"
      type       = destroyer
      model      = 1
    }
  }
  # Task Group 58.6#
  navalunit =
  { id       = { type = 10178 id = 1056 }
    name     = "Task Group 58.6"
    location = 2174
    base     = 1668
    division =
    { experience = 35
      id         = { type = 10178 id = 1057 }
      name       = "USS Louisville"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1058 }
      name       = "USS St. Louis"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1059 }
      name       = "19th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1060 }
      name       = "20th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1061 }
      name       = "21st Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1062 }
      name       = "22nd Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1063 }
      name       = "23rd Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1064 }
      name       = "24th Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1065 }
      name       = "1st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1066 }
      name       = "2nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1067 }
      name       = "3rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1068 }
      name       = "4th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1069 }
      name       = "5th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1070 }
      name       = "6th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2300 }
      name       = "50th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2301 }
      name       = "51st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2302 }
      name       = "52nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2303 }
      name       = "53rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2304 }
      name       = "54th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2305 }
      name       = "55th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2306 }
      name       = "56th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2307 }
      name       = "57th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2308 }
      name       = "58th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2309 }
      name       = "59th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2310 }
      name       = "60th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2311 }
      name       = "61st Transport Division"
      type       = transport
    }
  }
  # Task Group 58.7#
  navalunit =
  { id       = { type = 10178 id = 1071 }
    name     = "Task Group 58.7"
    location = 2174
    base     = 1608
    division =
    { experience = 35
      id         = { type = 10178 id = 1072 }
      name       = "USS Alabama"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1073 }
      name       = "USS Indiana"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1074 }
      name       = "USS Iowa"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1075 }
      name       = "USS New Jersey"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1076 }
      name       = "USS North Carolina"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1077 }
      name       = "USS South Dakota"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1078 }
      name       = "USS Washington"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1079 }
      name       = "USS Minneapolis"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1080 }
      name       = "USS New Orleans"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1081 }
      name       = "USS San Francisco"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1082 }
      name       = "USS Wichita"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1083 }
      name       = "13th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1084 }
      name       = "14th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1085 }
      name       = "15th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Southwest Pacific Squadron#
  navalunit =
  { id       = { type = 10178 id = 1086 }
    name     = "Southwest Pacific Squadron"
    location = 1665
    base     = 1665
    division =
    { experience = 35
      id         = { type = 10178 id = 1087 }
      name       = "USS Boise"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1088 }
      name       = "USS Nashville"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1089 }
      name       = "USS Phoenix"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1090 }
      name       = "25th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1091 }
      name       = "26th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1092 }
      name       = "27th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1093 }
      name       = "28th Destroyer Division"
      type       = destroyer
      model      = 1
    }
  }
  # Southwest Pacific Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1094 }
    name     = "Southwest Pacific Transport Squadron"
    location = 1665
    base     = 1665
    division =
    { experience = 35
      id         = { type = 10178 id = 1095 }
      name       = "29th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1096 }
      name       = "30th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1097 }
      name       = "31st Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1098 }
      name       = "7th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1099 }
      name       = "8th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1100 }
      name       = "9th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1101 }
      name       = "10th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1102 }
      name       = "11th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1103 }
      name       = "12th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2312 }
      name       = "62nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2313 }
      name       = "63rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2314 }
      name       = "64th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2315 }
      name       = "65th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2316 }
      name       = "66th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2317 }
      name       = "67th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2318 }
      name       = "68th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2319 }
      name       = "69th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2320 }
      name       = "70th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2321 }
      name       = "71st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2322 }
      name       = "72nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2323 }
      name       = "73rd Transport Division"
      type       = transport
    }
  }
  # South Pacific Squadron#
  navalunit =
  { id       = { type = 10178 id = 1104 }
    name     = "South Pacific Squadron"
    location = 1685
    base     = 1685
    division =
    {
      id            = { type = 10178 id = 1105 }
      name          = "USS Saratoga"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 1
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1106 }
      name       = "32nd Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  # South Pacific Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1107 }
    name     = "South Pacific Transport Squadron"
    location = 1685
    base     = 1685
    division =
    { experience = 35
      id         = { type = 10178 id = 1108 }
      name       = "33rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1109 }
      name       = "13th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1110 }
      name       = "14th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2324 }
      name       = "74th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2325 }
      name       = "75th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2326 }
      name       = "76th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2327 }
      name       = "77th Transport Division"
      type       = transport
    }
  }
  # North Pacific Squadron#
  navalunit =
  { id       = { type = 10178 id = 1111 }
    name     = "North Pacific Squadron"
    location = 549
    base     = 549
    division =
    { experience = 35
      id         = { type = 10178 id = 1112 }
      name       = "USS Chester"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1113 }
      name       = "USS Pensacola"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1114 }
      name       = "USS Salt Lake City"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1115 }
      name       = "USS Concord"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1116 }
      name       = "USS Detroit"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1117 }
      name       = "USS Richmond"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1118 }
      name       = "USS Trenton"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1119 }
      name       = "34th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1120 }
      name       = "35th Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  # North Pacific Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1121 }
    name     = "North Pacific Transport Squadron"
    location = 549
    base     = 549
    division =
    { experience = 35
      id         = { type = 10178 id = 1122 }
      name       = "36th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1123 }
      name       = "15th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1124 }
      name       = "16th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2328 }
      name       = "78th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2329 }
      name       = "79th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2330 }
      name       = "80th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2331 }
      name       = "81st Transport Division"
      type       = transport
    }
  }
  # 3rd Fleet#
  navalunit =
  { id       = { type = 10178 id = 1125 }
    name     = "3rd Fleet"
    location = 663
    base     = 663
    division =
    {
      id            = { type = 10178 id = 1126 }
      name          = "USS Franklin"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1127 }
      name          = "USS Hancock"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1128 }
      name          = "USS Intrepid"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 10178 id = 1129 }
      name          = "USS Ticonderoga"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1130 }
      name       = "USS Massachusetts"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1131 }
      name       = "USS Denver"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1132 }
      name       = "37th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1133 }
      name       = "38th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1134 }
      name       = "39th Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  # 3rd Fleet Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1135 }
    name     = "3rd Fleet Transport Squadron"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 10178 id = 1136 }
      name       = "40th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1137 }
      name       = "17th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1138 }
      name       = "18th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1139 }
      name       = "19th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1140 }
      name       = "20th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2332 }
      name       = "82nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2333 }
      name       = "83rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2334 }
      name       = "84th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2335 }
      name       = "85th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2336 }
      name       = "86th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2337 }
      name       = "87th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2338 }
      name       = "88th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2339 }
      name       = "89th Transport Division"
      type       = transport
    }
  }
  # San Francisco Squadron#
  navalunit =
  { id       = { type = 10178 id = 1141 }
    name     = "San Francisco Squadron"
    location = 762
    base     = 762
    division =
    { experience    = 35
      id            = { type = 10178 id = 190 }
      name          = "USS Ranger"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 5
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 191 }
      name       = "USS Missouri"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 192 }
      name       = "USS Wisconsin"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 193 }
      name       = "USS Alaska"
      type       = battlecruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1142 }
      name       = "USS Mississippi"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1143 }
      name       = "USS West Virginia"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1144 }
      name       = "USS Portland"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1145 }
      name       = "USS Columbia"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 194 }
      name       = "USS Astoria"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 195 }
      name       = "USS Pasadena"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 196 }
      name       = "USS Vicksburg"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1146 }
      name       = "41st Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 197 }
      name       = "60th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 198 }
      name       = "61st Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 199 }
      name       = "62nd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 270 }
      name       = "63rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 271 }
      name       = "64th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 272 }
      name       = "65th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 273 }
      name       = "66th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 274 }
      name       = "67th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 275 }
      name       = "68th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 276 }
      name       = "69th Destroyer Division"
      type       = destroyer
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 277 }
      name       = "70th Destroyer Division"
      type       = destroyer
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 278 }
      name       = "71st Destroyer Division"
      type       = destroyer
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 279 }
      name       = "20th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 340 }
      name       = "21st Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 341 }
      name       = "22nd Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 342 }
      name       = "23rd Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 343 }
      name       = "24th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 344 }
      name       = "25th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 345 }
      name       = "26th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 346 }
      name       = "27th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 347 }
      name       = "28th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 348 }
      name       = "29th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 349 }
      name       = "30th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 1st West Coast Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1147 }
    name     = "1st West Coast Transport Squadron"
    location = 762
    base     = 762
    division =
    { experience = 35
      id         = { type = 10178 id = 1148 }
      name       = "21st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1149 }
      name       = "22nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2340 }
      name       = "90th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2341 }
      name       = "91st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2342 }
      name       = "92nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2343 }
      name       = "93rd Transport Division"
      type       = transport
    }
  }
  # Los Angeles Squadron#
  navalunit =
  { id       = { type = 10178 id = 1150 }
    name     = "Los Angeles Squadron"
    location = 766
    base     = 766
    division =
    { experience = 35
      id         = { type = 10178 id = 1151 }
      name       = "USS Nevada"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1152 }
      name       = "USS Marblehead"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1153 }
      name       = "USS Raleigh"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1154 }
      name       = "42nd Destroyer Division"
      type       = destroyer
      model      = 0
    }
  }
  # 2nd West Coast Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1155 }
    name     = "2nd West Coast Transport Squadron"
    location = 766
    base     = 766
    division =
    { experience = 35
      id         = { type = 10178 id = 1156 }
      name       = "23rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1157 }
      name       = "24th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2344 }
      name       = "94th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2345 }
      name       = "95th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2346 }
      name       = "96th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2347 }
      name       = "97th Transport Division"
      type       = transport
    }
  }
  # US Channel Squadron#
  navalunit =
  { id       = { type = 10178 id = 1158 }
    name     = "US Channel Squadron"
    location = 2412
    base     = 23
    division =
    { experience = 35
      id         = { type = 10178 id = 1159 }
      name       = "USS Arkansas"
      type       = battleship
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1160 }
      name       = "USS New York"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1161 }
      name       = "USS Texas"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1162 }
      name       = "USS Augusta"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1163 }
      name       = "USS Quincy"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1164 }
      name       = "USS Tuscaloosa"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1165 }
      name       = "USS Memphis"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1166 }
      name       = "43rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1167 }
      name       = "44th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1168 }
      name       = "45th Destroyer Division"
      type       = destroyer
      model      = 0
    }
  }
  # US Channel Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1169 }
    name     = "US Channel Transport Squadron"
    location = 2412
    base     = 23
    division =
    { experience = 35
      id         = { type = 10178 id = 1170 }
      name       = "46th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1171 }
      name       = "47th Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1172 }
      name       = "25th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1173 }
      name       = "26th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1174 }
      name       = "27th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1175 }
      name       = "28th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1176 }
      name       = "29th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1177 }
      name       = "30th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2348 }
      name       = "98th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2349 }
      name       = "99th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2350 }
      name       = "100th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2351 }
      name       = "101st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2352 }
      name       = "102nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2353 }
      name       = "103rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2354 }
      name       = "104th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2355 }
      name       = "105th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2356 }
      name       = "106th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2357 }
      name       = "107th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2358 }
      name       = "108th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2359 }
      name       = "109th Transport Division"
      type       = transport
    }
  }
  # US Mediterranean Squadron#
  navalunit =
  { id       = { type = 10178 id = 1178 }
    name     = "US Mediterranean Squadron"
    location = 950
    base     = 950
    division =
    { experience = 35
      id         = { type = 10178 id = 1179 }
      name       = "USS Brooklyn"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1180 }
      name       = "USS Cincinnati"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1182 }
      name       = "USS Omaha"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1183 }
      name       = "USS Philadelphia"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1184 }
      name       = "USS Savannah"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1185 }
      name       = "48th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1186 }
      name       = "49th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1187 }
      name       = "50th Destroyer Division"
      type       = destroyer
      model      = 0
    }
  }
  # US Mediterranean Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1188 }
    name     = "US Mediterranean Transport Squadron"
    location = 950
    base     = 950
    division =
    { experience = 35
      id         = { type = 10178 id = 1189 }
      name       = "51st Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1190 }
      name       = "52nd Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1191 }
      name       = "31st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1192 }
      name       = "32nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1193 }
      name       = "33rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1194 }
      name       = "34th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1195 }
      name       = "35th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1196 }
      name       = "36th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2360 }
      name       = "110th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2361 }
      name       = "111th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2362 }
      name       = "112th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2363 }
      name       = "113th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2364 }
      name       = "114th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2365 }
      name       = "115th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2366 }
      name       = "116th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2367 }
      name       = "117th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2368 }
      name       = "118th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2369 }
      name       = "119th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2370 }
      name       = "120th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2371 }
      name       = "121st Transport Division"
      type       = transport
    }
  }
  # 1st East Coast Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1197 }
    name     = "1st East Coast Transport Squadron"
    location = 602
    base     = 602
    division =
    { experience = 35
      id         = { type = 10178 id = 1198 }
      name       = "53rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1199 }
      name       = "37th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1200 }
      name       = "38th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2372 }
      name       = "122nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2373 }
      name       = "123rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2374 }
      name       = "124th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2375 }
      name       = "125th Transport Division"
      type       = transport
    }
  }
  # 2nd East Coast Transport Squadron#
  navalunit =
  { id       = { type = 10178 id = 1201 }
    name     = "2nd East Coast Transport Squadron"
    location = 603
    base     = 603
    division =
    { experience = 35
      id         = { type = 10178 id = 1202 }
      name       = "54th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1203 }
      name       = "39th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 1204 }
      name       = "40th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2376 }
      name       = "126th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2377 }
      name       = "127th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2378 }
      name       = "128th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 2379 }
      name       = "129th Transport Division"
      type       = transport
    }
  }
  # 1st Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1205 }
    name     = "1st Submarine Division"
    location = 2159
    base     = 1627
    division =
    { experience = 35
      id         = { type = 10178 id = 1206 }
      name       = "1st Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 2nd Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1207 }
    name     = "2nd Submarine Division"
    location = 2157
    base     = 1627
    division =
    { experience = 35
      id         = { type = 10178 id = 1208 }
      name       = "2nd Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 3rd Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1209 }
    name     = "3rd Submarine Division"
    location = 2154
    base     = 1627
    division =
    { experience = 35
      id         = { type = 10178 id = 1210 }
      name       = "3rd Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 4th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1211 }
    name     = "4th Submarine Division"
    location = 2157
    base     = 1627
    division =
    { experience = 35
      id         = { type = 10178 id = 1212 }
      name       = "4th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 5th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1213 }
    name     = "5th Submarine Division"
    location = 2264
    base     = 1665
    division =
    { experience = 35
      id         = { type = 10178 id = 1214 }
      name       = "5th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 6th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1215 }
    name     = "6th Submarine Division"
    location = 2262
    base     = 1665
    division =
    { experience = 35
      id         = { type = 10178 id = 1216 }
      name       = "6th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 7th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1217 }
    name     = "7th Submarine Division"
    location = 662
    base     = 662
    division =
    { experience = 35
      id         = { type = 10178 id = 1218 }
      name       = "7th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 8th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1219 }
    name     = "8th Submarine Division"
    location = 662
    base     = 662
    division =
    { experience = 35
      id         = { type = 10178 id = 1220 }
      name       = "8th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 9th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1221 }
    name     = "9th Submarine Division"
    location = 2152
    base     = 1704
    division =
    { experience = 35
      id         = { type = 10178 id = 1222 }
      name       = "9th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 10th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1223 }
    name     = "10th Submarine Division"
    location = 2160
    base     = 1704
    division =
    { experience = 35
      id         = { type = 10178 id = 1224 }
      name       = "10th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 11th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1225 }
    name     = "11th Submarine Division"
    location = 1704
    base     = 1704
    division =
    { experience = 35
      id         = { type = 10178 id = 1226 }
      name       = "11th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 12th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1227 }
    name     = "12th Submarine Division"
    location = 1704
    base     = 1704
    division =
    { experience = 35
      id         = { type = 10178 id = 1228 }
      name       = "12th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 13th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1229 }
    name     = "13th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 10178 id = 1230 }
      name       = "13th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 14th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1231 }
    name     = "14th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 10178 id = 1232 }
      name       = "14th Submarine Division"
      type       = submarine
      model      = 2
    }
  }
  # 15th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1233 }
    name     = "15th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 10178 id = 1234 }
      name       = "15th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 16th Submarine Division#
  navalunit =
  { id       = { type = 10178 id = 1235 }
    name     = "16th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 10178 id = 1236 }
      name       = "16th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 10178 id = 200 }
    name     = "8th Air Force/1st Division"
    division =
    { experience    = 35
      id            = { type = 10178 id = 201 }
      name          = "1st USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 202 }
      name          = "41st USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 203 }
      name          = "94th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 204 }
      name          = "40th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
   }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 10178 id = 350 }
    name     = "8th Air Force/2nd Division"
    division =
    { experience    = 35
      id            = { type = 10178 id = 205 }
      name          = "2nd USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 206 }
      name          = "14th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 207 }
      name          = "20th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 208 }
      name          = "93rd USAAF Strategic Bomb. Group"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 10178 id = 216 }
    name     = "8th Air Force Escorts"
    division =
    { experience = 35
      id         = { type = 10178 id = 217 }
      name       = "1st USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 218 }
      name       = "4th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 219 }
      name       = "56th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 220 }
      name       = "352nd USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 221 }
      name       = "355th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 222 }
      name       = "357th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 223 }
      name       = "356th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 224 }
      name       = "358th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 10178 id = 351 }
    name     = "8th Air Force/3 division"
    division =
    { experience    = 35
      id            = { type = 10178 id = 209 }
      name          = "4th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 210 }
      name          = "13th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 211 }
      name          = "45th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 212 }
      name          = "385th USAAF Strategic Bomb. Group"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 213 }
      name          = "487th USAAF Strategic Bomb. Group"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 214 }
      name          = "491st USAAF Strategic Bomb. Group"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 10178 id = 227 }
    name     = "9th Air Force"
    division =
    { experience = 35
      id         = { type = 10178 id = 228 }
      name       = "97th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 229 }
      name       = "98th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 230 }
      name       = "99th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 231 }
      name       = "70th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 232 }
      name       = "71st USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 233 }
      name       = "84th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 234 }
      name       = "100th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 235 }
      name       = "303rd USAAF interceptor Wing"
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 523
    base     = 523
    id       = { type = 10178 id = 240 }
    name     = "15th Air Force"
    division =
    { experience    = 35
      id            = { type = 10178 id = 241 }
      name          = "5th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 242 }
      name          = "47th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 243 }
      name          = "49th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 244 }
      name          = "55th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 245 }
      name          = "304th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 246 }
      name       = "305th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 247 }
      name       = "306th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 519
    base     = 519
    id       = { type = 10178 id = 250 }
    name     = "12th Air Force"
    division =
    { experience = 35
      id         = { type = 10178 id = 251 }
      name       = "17th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 252 }
      name       = "310th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 253 }
      name       = "57th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 254 }
      name       = "324th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 19
    base     = 19
    id       = { type = 10178 id = 255 }
    name     = "9th Air Force/Air Transports"
    division =
    { experience = 35
      id         = { type = 10178 id = 236 }
      name       = "50th USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 237 }
      name       = "52nd USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 238 }
      name       = "53rd USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
  }
  # ####id up to 255
  airunit =
  { location = 1679
    base     = 1679
    id       = { type = 10178 id = 158 }
    name     = "13th Air Force (Heavy)"
    division =
    { experience    = 35
      id            = { type = 10178 id = 159 }
      name          = "5th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 160 }
      name       = "42nd USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 161 }
      name       = "403rd USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
  }
  airunit =
  { location = 1668
    base     = 1668
    id       = { type = 10178 id = 164 }
    name     = "13th Air Force interceptors"
    division =
    { experience = 35
      id         = { type = 10178 id = 165 }
      name       = "347th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 603
    base     = 603
    id       = { type = 10178 id = 170 }
    name     = "USAAF CONUS Reserve"
    division =
    { experience    = 35
      id            = { type = 10178 id = 171 }
      name          = "1st Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 172 }
      name          = "2nd Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 173 }
      name          = "3rd Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 174 }
      name          = "4th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 175 }
      name          = "5th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 176 }
      name          = "6th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 177 }
      name          = "7th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 178 }
      name       = "1st Res FG"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 603
    base     = 603
    id       = { type = 10178 id = 352 }
    name     = "USAAF CONUS Reserve/Air Transports"
    division =
    { experience = 35
      id         = { type = 10178 id = 179 }
      name       = "1st Res Transp"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 180 }
      name       = "2nd Res Transp"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
   }
  airunit =
  { location = 1287
    base     = 1287
    id       = { type = 10178 id = 280 }
    name     = "10th Air Force"
    division =
    { experience    = 35
      id            = { type = 10178 id = 281 }
      name          = "7th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 282 }
      name       = "12th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 283 }
      name       = "33rd USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 284 }
      name       = "80th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 285 }
      name       = "311th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 286 }
      name       = "341st USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 1408
    base     = 1408
    id       = { type = 10178 id = 261 }
    name     = "11th Air Force"
    division =
    { experience    = 35
      id            = { type = 10178 id = 262 }
      name          = "9th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 263 }
      name       = "11th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 1665
    base     = 1665
    id       = { type = 10178 id = 287 }
    name     = "1/SWPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 288 }
      name       = "35th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 289 }
      name       = "38th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 290 }
      name       = "345th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 1679
    base     = 1679
    id       = { type = 10178 id = 292 }
    name     = "2/SWPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 293 }
      name       = "49th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 294 }
      name          = "43rd USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 10178 id = 295 }
      name          = "307th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 1668
    base     = 1668
    id       = { type = 10178 id = 297 }
    name     = "3/SWPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 298 }
      name       = "VMFN 115"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 299 }
      name       = "VMSB 142"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1669
    base     = 1669
    id       = { type = 10178 id = 301 }
    name     = "4/SWPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 302 }
      name       = "VMF 121/211"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 303 }
      name       = "VMF 313"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 304 }
      name       = "VMB 433/443"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 1682
    base     = 1682
    id       = { type = 10178 id = 306 }
    name     = "5/SWPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 307 }
      name       = "VMF 218/222"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 308 }
      name       = "VMSB 133/341"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 309 }
      name       = "VMSB 244/423"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1682
    base     = 1682
    id       = { type = 10178 id = 311 }
    name     = "6/SWPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 312 }
      name       = "VMF 215/223"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 313 }
      name       = "VMF 221/315"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 314 }
      name       = "VMB 241/413"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1608
    base     = 1608
    id       = { type = 10178 id = 316 }
    name     = "2/CPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 317 }
      name       = "VMF 111/224"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 318 }
      name       = "VMSB 311/331"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 319 }
      name       = "VMSB 231/245"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 663
    base     = 663
    id       = { type = 10178 id = 321 }
    name     = "1/CPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 322 }
      name       = "VMF 124/213"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 323 }
      name       = "VMSB "
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1627
    base     = 1627
    id       = { type = 10178 id = 325 }
    name     = "3/CPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 326 }
      name       = "VFN 532/534"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 327 }
      name       = "VMF 225/321"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 328 }
      name       = "VMF 216/217"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 329 }
      name       = "VMTB 131/242"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 1619
    base     = 1619
    id       = { type = 10178 id = 331 }
    name     = "4/CPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 332 }
      name       = "VMF 114/122"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 333 }
      name       = "VMB 134/541"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 1601
    base     = 1601
    id       = { type = 10178 id = 335 }
    name     = "7/SWPAF"
    division =
    { experience = 35
      id         = { type = 10178 id = 336 }
      name       = "VMF 113/422"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 10178 id = 337 }
      name       = "VMB 151/612"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  division_development =
  { name  = "USS Bennington"
    type  = carrier
    model = 4
    cost  = 6.4
    id    = { type = 10178 id = 1500 }
    date  = { year = 1944 month = august day = 6 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Boxer"
    type  = carrier
    model = 4
    cost  = 6.4
    id    = { type = 10178 id = 1501 }
    date  = { year = 1945 month = april day = 16 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Bon Homme Richard"
    type  = carrier
    model = 4
    cost  = 6.4
    id    = { type = 10178 id = 1502 }
    date  = { year = 1944 month = november day = 26 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Antietam"
    type  = carrier
    model = 4
    cost  = 6.4
    id    = { type = 10178 id = 1503 }
    date  = { year = 1945 month = january day = 28 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Shangri La"
    type  = carrier
    model = 4
    cost  = 6.4
    id    = { type = 10178 id = 1505 }
    date  = { year = 1944 month = september day = 15 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Lake Champlain"
    type  = carrier
    model = 4
    cost  = 6.4
    id    = { type = 10178 id = 1506 }
    date  = { year = 1945 month = june day = 3 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Midway"
    type  = carrier
    model = 5
    cost  = 8
    id    = { type = 10178 id = 1508 }
    date  = { year = 1945 month = september day = 10 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Coral Sea"
    type  = carrier
    model = 5
    cost  = 8
    id    = { type = 10178 id = 1509 }
    date  = { year = 1945 month = october day = 27 }
    extra = cag
    brigade_model = 5
  }
  division_development =
  { name  = "USS Flint"
    type  = light_cruiser
    model = 2
    cost  = 4
    id    = { type = 10178 id = 1510 }
    date  = { year = 1944 month = august day = 31 }
  }
  division_development =
  { name  = "USS Springfield"
    type  = light_cruiser
    model = 4
    cost  = 5.6
    id    = { type = 10178 id = 1511 }
    date  = { year = 1944 month = september day = 9 }
  }
  division_development =
  { name  = "USS Duluth"
    type  = light_cruiser
    model = 4
    cost  = 5.6
    id    = { type = 10178 id = 1512 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "USS Wilkes-Barre"
    type  = light_cruiser
    model = 4
    cost  = 5.6
    id    = { type = 10178 id = 1513 }
    date  = { year = 1944 month = july day = 1 }
  }
  division_development =
  { name  = "USS Pittsburgh"
    type  = heavy_cruiser
    model = 4
    cost  = 6.4
    id    = { type = 10178 id = 1514 }
    date  = { year = 1944 month = october day = 10 }
  }
  division_development =
  { name  = "USS Guam"
    type  = battlecruiser
    model = 4
    cost  = 8
    id    = { type = 10178 id = 1517 }
    date  = { year = 1944 month = september day = 17 }
  }
  division_development =
  { name  = "55th Destroyer Division"
    type  = destroyer
    model = 3
    cost  = 2.4
    id    = { type = 10178 id = 1518 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "56th Destroyer Division"
    type  = destroyer
    model = 3
    cost  = 2.4
    id    = { type = 10178 id = 1519 }
    date  = { year = 1944 month = august day = 15 }
  }
  division_development =
  { name  = "57th Destroyer Division"
    type  = destroyer
    model = 3
    cost  = 2.4
    id    = { type = 10178 id = 1520 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "17th Submarine Division"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10178 id = 1522 }
    date  = { year = 1944 month = august day = 1 }
  }
  division_development =
  { name  = "18th Submarine Division"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10178 id = 1523 }
    date  = { year = 1944 month = september day = 1 }
  }
  division_development =
  { name  = "19th Submarine Division"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10178 id = 1524 }
    date  = { year = 1944 month = october day = 1 }
  }
  division_development =
  { name          = "103rd 'Cactus' Division"
    id            = { type = 10178 id = 2190 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = august year = 1944 }
  }
  division_development =
  { name          = "104th 'Timberwolves' Division"
    id            = { type = 10178 id = 2191 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = august year = 1944 }
  }
  division_development =
  { name          = "106th 'Golden Lions' Division"
    id            = { type = 10178 id = 2192 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = august year = 1944 }
  }
  division_development =
  { name          = "108th 'Griffons' Division"
    id            = { type = 10178 id = 2193 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "110th 'Washington' Division"
    id            = { type = 10178 id = 2194 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "11th Armored 'Thunderbolt' Div."
    id            = { type = 10178 id = 2195 }
    type          = armor
    extra         = sp_artillery
    brigade_model = 2
    model         = 3
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "115th 'Jefferson' Division"
    id            = { type = 10178 id = 2240 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "116th 'Headhunters' Division"
    id            = { type = 10178 id = 2241 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "125th 'Robert E. Lee' Division"
    id            = { type = 10178 id = 2242 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "128th 'Brooklyn' Division"
    id            = { type = 10178 id = 2243 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "131th 'Lincoln' Division"
    id            = { type = 10178 id = 2244 }
    type          = mechanized
    model         = 2
    extra         = sp_artillery
    brigade_model = 2
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "12th Armored 'Hellcat' Div."
    id            = { type = 10178 id = 2245 }
    type          = armor
    extra         = sp_artillery
    brigade_model = 2
    model         = 3
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "13th Armored 'Blackcat' Div."
    id            = { type = 10178 id = 2246 }
    type          = armor
    extra         = sp_artillery
    brigade_model = 2
    model         = 3
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "14th Armored 'Liberator' Div."
    id            = { type = 10178 id = 2247 }
    type          = armor
    extra         = sp_artillery
    brigade_model = 2
    model         = 3
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "15th Armored Division"
    id            = { type = 10178 id = 2248 }
    type          = armor
    extra         = sp_artillery
    brigade_model = 2
    model         = 3
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
  division_development =
  { name          = "16th Armored Division"
    id            = { type = 10178 id = 2249 }
    type          = armor
    extra         = sp_artillery
    brigade_model = 2
    model         = 3
    cost          = 7
    date          = { day = 3 month = september year = 1944 }
  }
}
