
##############################
# Country definition for SOV #
##############################

province =
{ id         = 133
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
}              # Murmansk
province =
{ id         = 154
  anti_air   = 4
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Archangelsk
province =
{ id          = 163
  air_base    = { size = 4 current_size = 4 }
  landfort    = 5
  coastalfort = 0
  anti_air    = 3
}               # Stalingrad
province =
{ id          = 175
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  coastalfort = 0
  anti_air    = 4
}               # Moscow
province =
{ id       = 181
  air_base = { size = 3 current_size = 3 }
  anti_air = 1
}            # Kaluga
province =
{ id          = 187
  ic          = 7
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  coastalfort = 5
}               # Leningrad
province = { id = 191 anti_air = 1 } # Porkhov
province =
{ id       = 201
  air_base = { size = 6 current_size = 6 }
}            # Opochka
province =
{ id       = 217
  air_base = { size = 2 current_size = 2 }
  anti_air = 2
}            # Vitebsk
province = { id = 219 anti_air = 3 } # Smolensk
province =
{ id       = 220
  air_base = { size = 8 current_size = 8 }
}            # Mogilev
province =
{ id         = 233
  anti_air   = 5
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Odessa
province =
{ id       = 238
  ic       = 8
  air_base = { size = 8 current_size = 8 }
}            # Kiev
province = { id = 246 anti_air = 2 } # Zaporozhye
province =
{ id       = 248
  air_base = { size = 6 current_size = 6 }
}            # Kharkov
province =
{ id          = 253
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 6 current_size = 6 }
  landfort    = 3
  coastalfort = 5
}               # Sevastopol
province =
{ id       = 258
  air_base = { size = 4 current_size = 4 }
}            # Rostov
province = { id = 263 anti_air = 1 } # Svoboda
province =
{ id       = 264
  air_base = { size = 2 current_size = 2 }
}            # Pavlovsk
province =
{ id       = 273
  air_base = { size = 2 current_size = 2 }
}            # Gomel
province = { id = 277 anti_air = 2 } # Bryansk
province =
{ id       = 282
  air_base = { size = 5 current_size = 5 }
}            # Orel
province =
{ id       = 289
  air_base = { size = 2 current_size = 2 }
}            # Demyansk
province =
{ id       = 1163
  air_base = { size = 1 current_size = 1 }
}            # Yakutsk
province =
{ id         = 1175
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
}              # Ocha
province =
{ id       = 1368
  air_base = { size = 1 current_size = 1 }
}            # Komsomolsk-na-Amure
province =
{ id          = 1372
  anti_air    = 5
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 1
  coastalfort = 3
}               # Vladivostok
province =
{ id       = 1416
  air_base = { size = 3 current_size = 3 }
}            # Irkutsk
province = { id = 1422 ic = 8 } # Alma-Ata
province = { id = 1427 ic = 4 } # Tashkent
province = { id = 1429 ic = 6 } # Frunze
province = { id = 1485 ic = 4 } # Stalinabad
province = { id = 1490 ic = 4 } # Ashgabat
province =
{ id       = 1523
  air_base = { size = 2 current_size = 2 }
}            # Tynda
province =
{ id         = 1525
  anti_air   = 2
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # Okhotsk
province =
{ id       = 1538
  air_base = { size = 1 current_size = 1 }
}            # Severo-Yenisejsk
province =
{ id       = 1544
  air_base = { size = 2 current_size = 2 }
}            # Tomsk
province = { id = 1548 ic = 8 } # Novosibirsk
province =
{ id       = 1550
  air_base = { size = 2 current_size = 2 }
}            # Semipalatinsk
province =
{ id       = 1552
  ic       = 2
  air_base = { size = 1 current_size = 1 }
}            # Omsk
province = { id = 1567 ic = 3 } # Ufa
province = { id = 1570 ic = 3 } # Chkalov
province = { id = 1572 ic = 4 } # Sverdlovsk
province =
{ id       = 1574
  ic       = 3
  air_base = { size = 1 current_size = 1 }
}            # Chelyabinsk
province =
{ id       = 1827
  air_base = { size = 2 current_size = 2 }
}            # Naberezhnye Chelny
province =
{ id       = 1828
  air_base = { size = 4 current_size = 4 }
}            # Kuybyshev
province =
{ id       = 1832
  air_base = { size = 3 current_size = 3 }
}            # Saratov
province =
{ id       = 1838
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Astrakhan
province =
{ id       = 1839
  air_base = { size = 2 current_size = 2 }
}            # Novouzensk
province =
{ id         = 1848
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Batum
province = { id = 1850 ic = 8 } # Tblisi
province = { id = 1856 ic = 5 } # Yerevan

#####################
# Country main data #
#####################

country =
{ tag                    = SOV
  regular_id             = RUS
  intrinsic_gov_type     = leninist
  capital                = 175
  belligerence           = 5
  ground_def_eff         = 0.400
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 2000
  money                  = 100
  transports             = 10
  manpower               = 1600
  dissent                = 15
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 10
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 6
    interventionism   = 4
  }
  SpyInfo                = { country = "SOV" NumberOfSpies = 11 }
  #SpyInfo                = { country = "ENG" NumberOfSpies = 5 }
  #SpyInfo                = { country = "FRA" NumberOfSpies = 4 }
  #SpyInfo                = { country = "GER" NumberOfSpies = 4 }
  #SpyInfo                = { country = "SLO" NumberOfSpies = 4 }
  #SpyInfo                = { country = "SPA" NumberOfSpies = 4 }
  #SpyInfo                = { country = "POL" NumberOfSpies = 8 }
  #SpyInfo                = { country = "SWE" NumberOfSpies = 5 }
  #SpyInfo                = { country = "NOR" NumberOfSpies = 4 }
  #SpyInfo                = { country = "FIN" NumberOfSpies = 8 }
  #SpyInfo                = { country = "YUG" NumberOfSpies = 8 }
  #SpyInfo                = { country = "HUN" NumberOfSpies = 5 }
  #SpyInfo                = { country = "BUL" NumberOfSpies = 8 }
  #SpyInfo                = { country = "BEL" NumberOfSpies = 4 }
  #SpyInfo                = { country = "DEN" NumberOfSpies = 4 }
  #SpyInfo                = { country = "CXB" NumberOfSpies = 5 }
  #SpyInfo                = { country = "MON" NumberOfSpies = 8 }
  #SpyInfo                = { country = "CGX" NumberOfSpies = 4 }
  #SpyInfo                = { country = "USA" NumberOfSpies = 8 }
  #SpyInfo                = { country = "GUA" NumberOfSpies = 4 }
  #SpyInfo                = { country = "GRE" NumberOfSpies = 4 }
  #SpyInfo                = { country = "CYN" NumberOfSpies = 8 }
  #SpyInfo                = { country = "CSX" NumberOfSpies = 4 }
  #SpyInfo                = { country = "JAP" NumberOfSpies = 10 }
  #SpyInfo                = { country = "ROM" NumberOfSpies = 5 }
  #SpyInfo                = { country = "LIT" NumberOfSpies = 5 }
  #SpyInfo                = { country = "LUX" NumberOfSpies = 4 }
  #SpyInfo                = { country = "POR" NumberOfSpies = 4 }
  #SpyInfo                = { country = "ITA" NumberOfSpies = 8 }
  #SpyInfo                = { country = "CHI" NumberOfSpies = 5 }
  #SpyInfo                = { country = "SCH" NumberOfSpies = 4 }
  #SpyInfo                = { country = "TUR" NumberOfSpies = 8 }
  nationalprovinces      = { 1372 1373 1371 1370 1369 1367 1366 1527 1529 1528 1526 1523 1410 1525 1524 1409 1164 1165 1166 1167 1170 1171 1172 1405
			     1174 1175 1176 1522 1521 1384 1383 1520 1416 1415 1414 1413 1162 1412 1411 1163 1159 1160 1158 1417 1558 1557 1423 1556
			     1550 1549 1547 1546 1559 1561 1560 1562 1563 1532 1537 1538 1545 1544 1548 1543 1540 1539 1536 1535 1533 1534 1157 1531
			     1156 1155 1154 1565 1564 1571 1597 1598 1554 1555 1553 1552 1594 1596 1573 1593 1592 1591 1590 1589 1588 1587 1424 1586
			     1585 1584 1583 1581 1576 1575 1574 1572 1566 1567 1570 1577 1578 1580 1582 1579 1569 1568 1150 1151 1152 1153 1773 1772
			     1771 154  1840 1841 165  153  151  152  150  135  134  133  1838 1847 1857 1849 1850 1848 1845 1844 1846 1843 255  256
			     257  270  1842 1837 271  164  1833 1834 1836 1839 1827 1828 1835 1829 1832 1831 1830 252  253  254  1777 1778 1776 1775
			     1780 1781 1782 1783 1774 163  162  161  160  159  157  156  158  155  169  168  167  179  180  166  178  177  170  171
			     172  173  174  175  176  181  182  183  184  190  191  189  185  186  187  188  192  200  201  212  225  226  227  228
			     231  232  233  234  251  250  235  236  237  238  239  240  220  272  241  273  274  275  276  277  278  279  280  281
			     282  283  284  249  258  259  260  248  247  243  262  261  269  268  267  266  265  264  263  1490 1491 1485 1487 1488
			     1427 1428 1426 1425 1429 94   1874 215  216  217  218  219  221  242  244  245  246  285  286  287  288  289  1149 1161
			     1368 1422 1489 1856 1858 1907 1541 1542 1551 199  195  194  196  193  197  198  202  203  204  205  577  511  206  207
			     434  435  433  230  146  145  132
			   }
  ownedprovinces         = { 1372 1373 1371 1370 1369 1367 1366 1527 1529 1528 1526 1523 1410 1525 1524 1409 1164 1165 1166 1167 1170 1171 1172 1405
			     1175 1522 1521 1384 1383 1520 1416 1415 1414 1413 1162 1412 1411 1163 1159 1160 1158 1417 1558 1557 1423 1556 1550 1549
			     1547 1546 1559 1561 1560 1562 1563 1532 1537 1538 1545 1544 1548 1543 1540 1539 1536 1535 1533 1534 1157 1531 1156 1155
			     1154 1565 1564 1571 1597 1598 1554 1555 1553 1552 1594 1596 1573 1593 1592 1591 1590 1589 1588 1587 1424 1586 1585 1584
			     1583 1581 1576 1575 1574 1572 1566 1567 1570 1577 1578 1580 1582 1579 1569 1568 1150 1151 1152 1153 1773 1772 1771 154
			     1840 1841 165  153  151  152  150  135  134  133  1838 1847 1857 1849 1850 1848 1845 1844 1846 1843 255  256  257  270
			     1842 1837 271  164  1833 1834 1836 1839 1827 1828 1835 1829 1832 1831 1830 252  253  254  1777 1778 1776 1775 1780 1781
			     1782 1783 1774 163  162  161  160  159  157  156  158  155  169  168  167  179  180  166  178  177  170  171  172  173
			     174  175  176  181  182  183  184  190  191  189  185  186  187  188  192  200  201  212  225  226  227  228  231  232
			     233  234  251  250  235  236  237  238  239  240  220  272  241  273  274  275  276  277  278  279  280  281  282  283
			     284  249  258  259  260  248  247  243  262  261  269  268  267  266  265  264  263  1490 1491 1485 1487 1488 1427 1428
			     1426 1425 1429 94   1874 215  216  217  218  219  221  242  244  245  246  285  286  287  288  289  1149 1161 1368 1422
			     1489 1856 1858 1907 1541 1542 1551
			   }
  controlledprovinces    = { 1372 1373 1371 1370 1369 1367 1366 1527 1529 1528 1526 1523 1410 1525 1524 1409 1164 1165 1166 1167 1170 1171 1172 1405
			     1175 1522 1521 1384 1383 1520 1416 1415 1414 1413 1162 1412 1411 1163 1159 1160 1158 1417 1558 1557 1423 1556 1550 1549
			     1547 1546 1559 1561 1560 1562 1563 1532 1537 1538 1545 1544 1548 1543 1540 1539 1536 1535 1533 1534 1157 1531 1156 1155
			     1154 1565 1564 1571 1597 1598 1554 1555 1553 1552 1594 1596 1573 1593 1592 1591 1590 1589 1588 1587 1424 1586 1585 1584
			     1583 1581 1576 1575 1574 1572 1566 1567 1570 1577 1578 1580 1582 1579 1569 1568 1150 1151 1152 1153 1773 1772 1771 154
			     1840 1841 165  153  151  152  150  135  134  133  1838 1847 1857 1849 1850 1848 1845 1844 1846 1843 255  256  257  270
			     1842 1837 271  164  1833 1834 1836 1839 1827 1828 1835 1829 1832 1831 1830 252  253  254  1777 1778 1776 1775 1780 1781
			     1782 1783 1774 163  162  161  160  159  157  156  158  155  169  168  167  179  180  166  178  177  170  171  172  173
			     174  175  176  181  182  183  184  190  191  189  185  186  187  188  192  200  201  212  225  226  227  228  231  232
			     233  234  251  250  235  236  237  238  239  240  220  272  241  273  274  275  276  277  278  279  280  281  282  283
			     284  249  258  259  260  248  247  243  262  261  269  268  267  266  265  264  263  1490 1491 1485 1487 1488 1427 1428
			     1426 1425 1429 94   1874 215  216  217  218  219  221  242  244  245  246  285  286  287  288  289  1149 1161 1368 1422
			     1489 1856 1858 1907 1541 1542 1551
			   }
  # Rocket Test and Research Facility
  # Air Doctrines 1936
  # ################
  techapps               = { 5550 1310 4030 4060 1230 1210 1220 9010 9020 9030 9040 9090 4010 4020 4120 4130 4170 4250 4220 2010 2020 2030 2040 2150
			     2290 2300 2310 2320 2450 2050 2070 2100 2330 2400 2460 2510 5010 5020 5050 5080 5090 5100 5190 5200 5470 1010 1020 1110
			     1190 1030 1070 1200 6210 6300 6310 8010 8020 8030 8040 8050 8070 3010 3020 3030 3070 3080 3090 3130 3140 3190 3200 3250
			     3260 3270 3280 3400 3410 3420 3430
			   }
  diplomacy =
  { relation =
    { tag        = AFG
      value      = 1
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation = { tag = BRA value = -50 }
    relation =
    { tag        = BUL
      value      = 15
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation = { tag = SLO value = -100 }
    relation = { tag = ENG value = -25 }
    relation =
    { tag        = EST
      value      = -30
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation =
    { tag        = FIN
      value      = 1
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation = { tag = FRA value = 100 }
    relation = { tag = GER value = 20 }
    relation =
    { tag        = LAT
      value      = -30
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation =
    { tag        = LIT
      value      = -30
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation = { tag = MON value = 150 access = yes }
    relation = { tag = PER value = -20 }
    relation = { tag = POL value = -50 }
    relation =
    { tag        = ROM
      value      = 1
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation =
    { tag        = SIK
      value      = 125
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation = { tag = SPA value = -100 }
    relation =
    { tag        = TAN
      value      = 200
      guaranteed = { day = 30 month = december year = 1938 }
      access     = yes
    }
    relation =
    { tag        = TUR
      value      = 70
      guaranteed = { day = 30 month = december year = 1938 }
    }
    relation = { tag = URU value = -100 }
    relation = { tag = USA value = 35 }
  }
  headofstate            = { type = 9 id = 4001 }
  headofgovernment       = { type = 9 id = 4002 }
  foreignminister        = { type = 9 id = 4034 }
  armamentminister       = { type = 9 id = 4004 }
  ministerofsecurity     = { type = 9 id = 4041 }
  ministerofintelligence = { type = 9 id = 4046 }
  chiefofstaff           = { type = 9 id = 4051 }
  chiefofarmy            = { type = 9 id = 4008 }
  chiefofnavy            = { type = 9 id = 4062 }
  chiefofair             = { type = 9 id = 4064 }
  dormant_teams		 = { 3706 3716 }
  dormant_ministers      = { 4003 4005 4006 4007 4009 4010 }
  dormant_leaders        = { 9839  9841  9843  9849  9884  9894  9896  9900  9907  9910  9926  9930  9951  9955  9969  9974  9991  9993  10006 10016
			     10019 10028 10031 10042 10054 10066 10071 10114 10115 10137 10138 10202 10208 10215 10253 10271 10276 10283 10286 10297
			     10322 10342 10349 10369 10370 10371 10401 10417 10453 10463 10472 10477 10500 10514 10515 10516 10517 10518 10520 10521
			     10522
			   }
  landunit =
  { id       = { type = 30008 id = 1001 }
    name     = "STAVKA"
    location = 175
    division =
    { id       = { type = 30008 id = 1002 }
      name     = "STAVKA"
      strength = 100
      type     = hq
    }
  }
  landunit =
  { id       = { type = 30008 id = 1003 }
    name     = "Leningrad Front HQ"
    location = 187
    division =
    { id       = { type = 30008 id = 1004 }
      name     = "Leningrad Front HQ"
      strength = 100
      type     = hq
    }
  }
  landunit =
  { id       = { type = 30008 id = 1005 }
    name     = "West Front HQ"
    location = 219
    division =
    { id       = { type = 30008 id = 1006 }
      name     = "West Front HQ"
      strength = 100
      type     = hq
    }
  }
  landunit =
  { id       = { type = 30008 id = 1007 }
    name     = "Far East HQ"
    location = 1372
    division =
    { id       = { type = 30008 id = 1008 }
      name     = "Far East HQ"
      strength = 100
      type     = hq
    }
  }
  landunit =
  { id       = { type = 30008 id = 1 }
    name     = "1st Mechanized Corps"
    location = 187
    division =
    { id       = { type = 30008 id = 2 }
      name     = "3. Tankovaya & 163. Motostrelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
    division =
    { id       = { type = 30008 id = 3 }
      name     = "177. Strelkovaya Diviziya"
      strength = 60
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 233 }
      name     = "191. Strelkovaya Diviziya"
      strength = 60
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 234 }
      name     = "8. 'Minskaya' Strelk. Div."
      strength = 60
      type     = infantry
    }
  }
  # #####################
  # ######################
  landunit =
  { id       = { type = 30008 id = 4 }
    name     = "7ya Armiya"
    location = 152
    division =
    { id       = { type = 30008 id = 5 }
      name     = "54. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = anti_air
    }
    division =
    { id       = { type = 30008 id = 235 }
      name     = "71. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 6 }
      name     = "168. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 236 }
      name     = "237. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  # ############################
  # ############################
  landunit =
  { id       = { type = 30008 id = 7 }
    name     = "14ya Armiya"
    location = 191
    division =
    { id            = { type = 30008 id = 8 }
      name          = "122. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 237 }
      name     = "104. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 9 }
      name     = "14. 'Krivorozhskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 238 }
      name     = "52. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 10 }
      name     = "1. Tankovaya Diviziya"
      strength = 30
      type     = light_armor
      model    = 1
    }
  }
  # #########################
  # #########################
  landunit =
  { id       = { type = 30008 id = 11 }
    name     = "23ya Armiya"
    location = 216
    division =
    { id            = { type = 30008 id = 12 }
      name          = "142. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 239 }
      name     = "43. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 13 }
      name     = "70. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 240 }
      name     = "123. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 15 }
      name          = "198. Moto./115. Strelkovaya Diviziya"
      strength      = 80
      type          = motorized
      extra         = artillery
      brigade_model = 2
    }
  }
  # ###########################
  # #############################
  landunit =
  { id       = { type = 30008 id = 16 }
    name     = "8ya Armiya"
    location = 219
    division =
    { id       = { type = 30008 id = 17 }
      name     = "10. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 241 }
      name          = "48. Strelkovaya Diviziya"
      strength      = 80
      extra         = artillery
      brigade_model = 2
      type          = infantry
    }
    division =
    { id       = { type = 30008 id = 18 }
      name     = "90. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 242 }
      name     = "125. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 20 }
      name     = "202. Moto./11. Strelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = engineer
    }
  }
  # ##########################
  # ###########################
  landunit =
  { id       = { type = 30008 id = 21 }
    name     = "11ya Armiya"
    location = 220
    division =
    { id            = { type = 30008 id = 22 }
      name          = "5. 'Vitebskaya' Strelk. Div."
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 243 }
      name     = "179. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 23 }
      name          = "184. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 244 }
      name     = "33. 'Belorusskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 24 }
      name     = "2./5. Tankovaya Diviziya"
      strength = 80
      type     = light_armor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 25 }
      name     = "84. Mech/188. Strelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = engineer
    }
    division =
    { id       = { type = 30008 id = 26 }
      name     = "126. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 245 }
      name     = "128. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 246 }
      name     = "23. 'Har'kovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
  }
  # ######################
  # #######################
  landunit =
  { id       = { type = 30008 id = 27 }
    name     = "27ya Armiya"
    location = 272
    division =
    { id            = { type = 30008 id = 28 }
      name          = "180. Strelkovaya Diviziya"
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 247 }
      name     = "181. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 248 }
      name     = "182. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 29 }
      name     = "16. 'Ul'yanovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 249 }
      name     = "67. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 250 }
      name     = "183. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 30 }
      name     = "3. 'Tihookeanskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 251 }
      name     = "22. 'Krasnodarskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
  }
  # ##############################
  # ##############################
  landunit =
  { id       = { type = 30008 id = 31 }
    name     = "47ya Armiya Corps"
    location = 240
    division =
    { id       = { type = 30008 id = 32 }
      name     = "143. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 252 }
      name     = "121. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 253 }
      name     = "55. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  # ###########################
  # ###########################
  landunit =
  { id       = { type = 30008 id = 33 }
    name     = "17th Mechanized Corps"
    location = 175
    division =
    { id       = { type = 30008 id = 35 }
      name     = "209./210. Motorizovannaya Diviziya"
      strength = 60
      type     = motorized
      extra    = anti_tank
    }
  }
  # ###############################
  # ##############################
  landunit =
  { id       = { type = 30008 id = 49 }
    name     = "3ya Armiya"
    location = 238
    division =
    { id            = { type = 30008 id = 50 }
      name          = "27. 'Omskaya' Strelk. Div."
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 254 }
      name     = "24. 'Samaro-Ul'yanov.' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 255 }
      name     = "17. 'Gor'kovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 51 }
      name          = "50. 'Tamanskaya' Strelk. Div."
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 256 }
      name     = "56. 'Moskovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 257 }
      name     = "85. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 53 }
      name     = "75. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 258 }
      name     = "37. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  # #########################
  # #########################
  landunit =
  { id       = { type = 30008 id = 54 }
    name     = "4ya Armiya"
    location = 237
    division =
    { id            = { type = 30008 id = 55 }
      name          = "6. 'Orlovskaya' Strelk. Div."
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 259 }
      name     = "42. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 260 }
      name     = "49. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 57 }
      name     = "204./205. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  # ########################
  # #########################
  landunit =
  { id       = { type = 30008 id = 58 }
    name     = "10ya Armiya"
    location = 236
    division =
    { id       = { type = 30008 id = 59 }
      name     = "86. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 261 }
      name     = "13. 'Dagestanskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 262 }
      name          = "2. 'Belorusskaya' Strelk. Div."
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id            = { type = 30008 id = 60 }
      name          = "113. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 263 }
      name     = "8. 'Minskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 61 }
      name     = "6. 'Chongarskaya' Kav. Div."
      strength = 80
      type     = cavalry
    }
    division =
    { id       = { type = 30008 id = 62 }
      name     = "4./7. Tankovaya Diviziya"
      strength = 80
      type     = armor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 64 }
      name     = "29./208. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  # ##########################
  # ###########################
  landunit =
  { id       = { type = 30008 id = 65 }
    name     = "13ya Armiya"
    location = 234
    division =
    { id       = { type = 30008 id = 66 }
      name     = "161. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 264 }
      name     = "100. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 67 }
      name     = "64. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 265 }
      name     = "108. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  # ##########################
  # ##########################
  landunit =
  { id       = { type = 30008 id = 68 }
    name     = "31ya Armiya Corps"
    location = 253
    division =
    { id       = { type = 30008 id = 69 }
      name     = "193. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 266 }
      name     = "195. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 267 }
      name     = "200. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  # ##########################
  # ##########################
  landunit =
  { id       = { type = 30008 id = 70 }
    name     = "36ya Armiya Corps"
    location = 1848
    division =
    { id       = { type = 30008 id = 71 }
      name     = "140. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 268 }
      name     = "146. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 269 }
      name     = "228. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  # #########################
  # #########################
  landunit =
  { id       = { type = 30008 id = 72 }
    name     = "49ya Armiya Corps"
    location = 1850
    division =
    { id       = { type = 30008 id = 73 }
      name     = "199. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 270 }
      name     = "197. 'Kievskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 271 }
      name     = "190. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  # #################################
  # #################################
  landunit =
  { id       = { type = 30008 id = 74 }
    name     = "55ya Armiya Corps"
    location = 1857
    division =
    { id       = { type = 30008 id = 75 }
      name     = "189. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 272 }
      name     = "169. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 273 }
      name     = "130. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
  }
  # #############################
  # #############################
  landunit =
  { id       = { type = 30008 id = 79 }
    name     = "15. Mechanized Corps"
    location = 1490
    division =
    { id       = { type = 30008 id = 81 }
      name     = "131./212. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  # ###############################
  # ###############################
  landunit =
  { id       = { type = 30008 id = 85 }
    name     = "24. Mechanized Corps"
    location = 1520
    division =
    { id       = { type = 30008 id = 87 }
      name     = "213./216. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  # ###############################
  # ###############################
  landunit =
  { id       = { type = 30008 id = 88 }
    name     = "5ya Armiya"
    location = 1368
    division =
    { id            = { type = 30008 id = 89 }
      name          = "45. 'Volynskaya' Strelk. Div."
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 274 }
      name     = "87. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 90 }
      name          = "62. 'Turkestanskaya' Strelk. Div."
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 275 }
      name     = "124. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 92 }
      name     = "135. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 276 }
      name     = "97. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  # ###############################
  # ##############################
  landunit =
  { id       = { type = 30008 id = 93 }
    name     = "6ya Armiya"
    location = 1371
    division =
    { id            = { type = 30008 id = 94 }
      name          = "41. Strelkovaya Diviziya"
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 277 }
      name     = "80. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 278 }
      name     = "159. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 95 }
      name     = "139. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 279 }
      name     = "141. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 96 }
      name     = "3. 'Bessarabskaya' Kav. Div."
      strength = 80
      type     = cavalry
    }
    division =
    { id       = { type = 30008 id = 98 }
      name     = "215th/81. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  # ##############################
  # ##############################
  landunit =
  { id       = { type = 30008 id = 99 }
    name     = "12ya Armiya"
    location = 258
    division =
    { id            = { type = 30008 id = 100 }
      name          = "164. Strelkovaya Diviziya"
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 280 }
      name     = "58. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 101 }
      name     = "60. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 281 }
      name     = "69. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 103 }
      name     = "192. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 282 }
      name     = "44. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  # ################################
  # ################################
  landunit =
  { id       = { type = 30008 id = 104 }
    name     = "26ya Armiya"
    location = 133
    division =
    { id       = { type = 30008 id = 105 }
      name     = "99. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 283 }
      name     = "173. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 107 }
      name     = "240./7. Motorizovannaya Diviziya"
      strength = 60
      type     = motorized
      extra    = anti_tank
    }
  }
  # ###########################
  # ############################
  landunit =
  { id       = { type = 30008 id = 108 }
    name     = "7ya Armiya Corps"
    location = 260
    division =
    { id       = { type = 30008 id = 109 }
      name     = "116. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 284 }
      name     = "196. 'Dnepropetrov.' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 285 }
      name     = "206. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  # ############################
  # #############################
  landunit =
  { id       = { type = 30008 id = 110 }
    name     = "9ya Armiya Corps"
    location = 247
    division =
    { id       = { type = 30008 id = 111 }
      name     = "156. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 286 }
      name     = "106. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 287 }
      name     = "47. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 112 }
      name     = "32. Kavaleriyskaya Diviziya"
      strength = 30
      type     = cavalry
    }
  }
  # ##########################
  # ##########################
  landunit =
  { id       = { type = 30008 id = 113 }
    name     = "9ya Armiya"
    location = 243
    division =
    { id       = { type = 30008 id = 114 }
      name     = "176. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 288 }
      name          = "25. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 115 }
      name     = "74. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 289 }
      name     = "51. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = anti_air
    }
    division =
    { id       = { type = 30008 id = 116 }
      name     = "95. 'Moldavskaya' Strelk. Div."
      strength = 80
      type     = bergsjaeger
      extra    = engineer
    }
    division =
    { id       = { type = 30008 id = 117 }
      name     = "9. 'Krymskaya' Kav. Div."
      strength = 80
      type     = cavalry
    }
    division =
    { id       = { type = 30008 id = 120 }
      name     = "15./218. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  # #############################
  # ##############################
  landunit =
  { id       = { type = 30008 id = 121 }
    name     = "Transcaucasus Military District"
    location = 1907
    division =
    { id       = { type = 30008 id = 122 }
      name     = "4. 'Smolenskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 290 }
      name     = "31. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 291 }
      name     = "136. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 123 }
      name     = "138. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 292 }
      name     = "47. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 124 }
      name     = "17. 'Gor'kovskaya' Strelk. Div."
      strength = 100
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 125 }
      name     = "63./76./77. Strelkovaya Diviziya"
      strength = 100
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 126 }
      name     = "24. Kavaleriyskaya Diviziya"
      strength = 30
      type     = cavalry
    }
  }
  # ############################
  # ############################
  landunit =
  { id       = { type = 30008 id = 127 }
    name     = "28. Mechanized Corps"
    location = 277
    division =
    { id       = { type = 30008 id = 128 }
      name     = "6. Tankovaya/236. Motorizovannaya Diviziya"
      strength = 90
      type     = light_armor
      model    = 1
    }
  }
  # ###############################
  # ###############################
  landunit =
  { id       = { type = 30008 id = 130 }
    name     = "Arkhangelsk Military District"
    location = 153
    division =
    { id            = { type = 30008 id = 131 }
      name          = "88. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 293 }
      name     = "111. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  # ##################################
  # ##################################
  landunit =
  { id       = { type = 30008 id = 132 }
    name     = "Moscow Military District"
    location = 175
    division =
    { id       = { type = 30008 id = 133 }
      name     = "118. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = engineer
    }
    division =
    { id       = { type = 30008 id = 294 }
      name     = "235. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = engineer
    }
  }
  # #################################
  # #################################
  landunit =
  { id       = { type = 30008 id = 134 }
    name     = "North Caucasus Military District"
    location = 1845
    division =
    { id            = { type = 30008 id = 135 }
      name          = "175. Strelkovaya Diviziya"
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 295 }
      name     = "165. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 296 }
      name     = "157. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 136 }
      name     = "28. Strelkovaya Diviziya"
      strength = 30
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 138 }
      name     = "203./220. Motostrelkovaya Diviziya"
      strength = 60
      type     = motorized
      extra    = anti_tank
    }
  }
  # #############################
  # #############################
  landunit =
  { id       = { type = 30008 id = 139 }
    name     = "Orel Military District"
    location = 285
    division =
    { id            = { type = 30008 id = 140 }
      name          = "19. 'Voronezhskaya' Strelk. Div."
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 297 }
      name     = "89. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 298 }
      name     = "217. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 141 }
      name     = "120. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
      extra    = anti_air
    }
    division =
    { id       = { type = 30008 id = 299 }
      name     = "145. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 143 }
      name     = "222. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 300 }
      name     = "149. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
  }
  # ##############################
  # #############################
  landunit =
  { id       = { type = 30008 id = 144 }
    name     = "Central Asia Military District"
    location = 1556
    division =
    { id       = { type = 30008 id = 145 }
      name     = "68./83./194. Strelkovaya Diviziya"
      strength = 100
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 146 }
      name     = "21. 'Permskaya' Strelk. Div."
      strength = 100
      type     = bergsjaeger
    }
    division =
    { id       = { type = 30008 id = 148 }
      name     = "221. Moto./238. Strelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_air
    }
  }
  # ###########################
  # ############################
  landunit =
  { id       = { type = 30008 id = 149 }
    name     = "Transbaikal Military District"
    location = 1520
    division =
    { id       = { type = 30008 id = 150 }
      name     = "65. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 301 }
      name     = "114. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 151 }
      name     = "93. 'Vostochno-Sibir.' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 302 }
      name     = "94. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  # ##############################
  # ##############################
  landunit =
  { id       = { type = 30008 id = 152 }
    name     = "17ya Armiya"
    location = 1370
    division =
    { id       = { type = 30008 id = 154 }
      name     = "36./57./82nd Motorized Division"
      strength = 100
      type     = motorized
      extra    = anti_tank
    }
  }
  # ##############################
  # ##############################
  landunit =
  { id       = { type = 30008 id = 155 }
    name     = "1ya Armiya"
    location = 1523
    division =
    { id       = { type = 30008 id = 156 }
      name     = "39. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 303 }
      name     = "26. 'Zlatoustovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id            = { type = 30008 id = 304 }
      name          = "21. 'Permskaya' Strelk. Div."
      strength      = 100
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id            = { type = 30008 id = 157 }
      name          = "59. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 305 }
      name     = "22. 'Krasnodarskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 158 }
      name     = "1. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 306 }
      name     = "4. 'Smolenskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 307 }
      name     = "5. 'Vitebskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 160 }
      name     = "239. Motostrelkovaya Diviziya"
      strength = 30
      type     = motorized
      extra    = anti_tank
    }
  }
  # #########################
  # ##########################
  landunit =
  { id       = { type = 30008 id = 161 }
    name     = "Special Forces Far East"
    location = 1526
    division =
    { id       = { type = 30008 id = 162 }
      name     = "79. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = engineer
    }
    division =
    { id       = { type = 30008 id = 308 }
      name     = "78. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = engineer
    }
    division =
    { id       = { type = 30008 id = 163 }
      name     = "35. 'Sibirskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 309 }
      name     = "66. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 164 }
      name     = "101. Strelkovaya Diviziya"
      strength = 30
      type     = bergsjaeger
    }
  }
  # ###########################
  # ###########################
  landunit =
  { id       = { type = 30008 id = 165 }
    name     = "2ya Armiya"
    location = 1827
    division =
    { id            = { type = 30008 id = 166 }
      name          = "12. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id            = { type = 30008 id = 310 }
      name          = "3. 'Tihookeanskaya' Strelk. Div."
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
  }
  # #############################
  # #############################
  landunit =
  { id       = { type = 30008 id = 168 }
    name     = "25ya Armiya"
    location = 1570
    division =
    { id            = { type = 30008 id = 169 }
      name          = "92. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 30008 id = 311 }
      name     = "32. 'Saratovskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 30008 id = 170 }
      name     = "40. 'Bogucharskaya' Strelk. Div."
      strength = 80
      type     = infantry
      extra    = anti_air
    }
    division =
    { id       = { type = 30008 id = 312 }
      name     = "105. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  navalunit =
  { id       = { type = 10848 id = 5113 }
    name     = "Arctic Fleet"
    location = 133 # Murmansk
    base     = 133
    division =
    { id    = { type = 10849 id = 200 }
      name  = "1. Flotiliya Esmintsev"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10849 id = 201 }
      name  = "2. Flotiliya Esmintsev"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10849 id = 202 }
      name  = "1. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 203 }
      name  = "2. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 998 }
      name  = "30. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10849 id = 997 }
      name  = "31. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { id       = { type = 10848 id = 5114 }
    name     = "Red Banner Baltic Fleet"
    location = 187 # Leningrad
    base     = 187
    division =
    { id    = { type = 10849 id = 204 }
      name  = "Marat"
      type  = battleship
      model = 0
    }
    division =
    { id    = { type = 10849 id = 205 }
      name  = "Oktyabrskaya Revoluciya"
      type  = battleship
      model = 0
    }
    division =
    { id    = { type = 10849 id = 500 }
      name  = "Kirov"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10849 id = 206 }
      name  = "3. Flotiliya Esmintsev"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10849 id = 207 }
      name  = "4. Flotiliya Esmintsev"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10849 id = 208 }
      name  = "3. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 209 }
      name  = "4. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 210 }
      name  = "5. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 211 }
      name  = "6. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 212 }
      name  = "7. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 996 }
      name  = "32. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10849 id = 995 }
      name  = "33. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { id       = { type = 10848 id = 5115 }
    name     = "Black Sea Fleet"
    location = 253 # Sevastopol
    base     = 253
    division =
    { id    = { type = 10849 id = 234 }
      name  = "Parishskaya Kommuna"
      type  = battleship
      model = 0
    }
    division =
    { id    = { type = 10849 id = 214 }
      name  = "Profintern"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 10849 id = 215 }
      name  = "Pamiat Merkuriya"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 10849 id = 216 }
      name  = "Chervonaya Ukraina"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 10849 id = 217 }
      name  = "Krasni Kavkaz"
      type  = heavy_cruiser
      model = 0
    }
    division =
    { id    = { type = 10849 id = 218 }
      name  = "5. Flotiliya Esmintsev"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10849 id = 219 }
      name  = "6. Flotiliya Esmintsev"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10849 id = 220 }
      name  = "8. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 221 }
      name  = "9. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 222 }
      name  = "10. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 223 }
      name  = "11. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 994 }
      name  = "34. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10849 id = 993 }
      name  = "35. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { id       = { type = 10848 id = 5116 }
    name     = "Pacific Fleet"
    location = 1372 # Vladivostok
    base     = 1372
    division =
    { id    = { type = 10849 id = 600 }
      name  = "18. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 601 }
      name  = "19. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10849 id = 602 }
      name  = "20. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 603 }
      name  = "21. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 604 }
      name  = "22. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 605 }
      name  = "23. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 606 }
      name  = "24. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 607 }
      name  = "25. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 608 }
      name  = "26. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 609 }
      name  = "27. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 224 }
      name  = "7. Flotiliya Esmintsev"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10849 id = 225 }
      name  = "8. Flotiliya Esmintsev"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10849 id = 999 }
      name  = "9. Flotiliya Esmintsev"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10849 id = 226 }
      name  = "12. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 227 }
      name  = "13. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 228 }
      name  = "14. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 229 }
      name  = "15. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 230 }
      name  = "16. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10849 id = 231 }
      name  = "17. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id   = { type = 10849 id = 232 }
      name = "1. Transportnaya Flotiliya"
      type = transport
    }
  }
  # ##############################
  # ##############################
  airunit =
  { id       = { type = 30008 id = 171 }
    name     = "Leningrad Air Defense"
    location = 187
    base     = 187
    division =
    { id       = { type = 30008 id = 172 }
      name     = "3./54. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 174 }
      name     = "41. BAD"
      strength = 50
      type     = tactical_bomber
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 175 }
      name     = "55. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 176 }
      name     = "1./2. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 177 }
      name     = "5. IAD"
      strength = 50
      type     = interceptor
      model    = 1
    }
  }
  # ##########################
  # ##########################
  airunit =
  { id       = { type = 30008 id = 178 }
    name     = "Riga Air Command"
    location = 201
    base     = 201
    division =
    { id       = { type = 30008 id = 179 }
      name     = "21./57. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 180 }
      name     = "4./6. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 181 }
      name     = "8. IAD"
      strength = 50
      type     = interceptor
      model    = 1
    }
  }
  # #########################
  # ##########################
  airunit =
  { id       = { type = 30008 id = 182 }
    name     = "Western Air Command"
    location = 282
    base     = 282
    division =
    { id       = { type = 30008 id = 183 }
      name     = "11./184. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 184 }
      name     = "12./13. BAD"
      strength = 100
      type     = tactical_bomber
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 185 }
      name     = "9./10. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
  }
  # ##############################
  # ##############################
  airunit =
  { id       = { type = 30008 id = 186 }
    name     = "Kiev Air Command"
    location = 238
    base     = 238
    division =
    { id       = { type = 30008 id = 187 }
      name     = "36./44. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 188 }
      name     = "63./64. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 189 }
      name     = "19./62. BAD"
      strength = 100
      type     = tactical_bomber
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 190 }
      name     = "14./15. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 191 }
      name     = "17. IAD"
      strength = 50
      type     = interceptor
      model    = 1
    }
  }
  # ##############################
  # ##############################
  airunit =
  { id       = { type = 30008 id = 192 }
    name     = "Odessa Air Command"
    location = 233
    base     = 233
    division =
    { id       = { type = 30008 id = 193 }
      name     = "20./21. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 194 }
      name     = "45. IAD"
      strength = 50
      type     = interceptor
      model    = 1
    }
  }
  # ##############################
  # ###############################
  airunit =
  { id       = { type = 30008 id = 195 }
    name     = "Transcaucasus Air Command"
    location = 1848
    base     = 1848
    division =
    { id       = { type = 30008 id = 196 }
      name     = "25./27. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 197 }
      name     = "68./71. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 198 }
      name     = "26. BAD"
      strength = 50
      type     = tactical_bomber
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 199 }
      name     = "72. IAD"
      strength = 50
      type     = interceptor
      model    = 0
    }
  }
  # ################################
  # ################################
  airunit =
  { id       = { type = 30008 id = 200 }
    name     = "Kharkov Air Command"
    location = 248
    base     = 248
    division =
    { id       = { type = 30008 id = 201 }
      name     = "75./76. IAD"
      strength = 100
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 202 }
      name     = "49. BAD"
      strength = 50
      type     = tactical_bomber
      model    = 0
    }
  }
  # ################################
  # #################################
  airunit =
  { id       = { type = 30008 id = 203 }
    name     = "Moscow Air Command"
    location = 175
    base     = 175
    division =
    { id       = { type = 30008 id = 204 }
      name     = "6./78. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 205 }
      name     = "23./24. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 206 }
      name     = "46./47. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
  }
  # ##############################
  # ##############################
  airunit =
  { id       = { type = 30008 id = 207 }
    name     = "North Caucasus Air Command"
    location = 1848
    base     = 1848
    division =
    { id       = { type = 30008 id = 208 }
      name     = "73. IAD"
      strength = 50
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 209 }
      name     = "74. BAD"
      strength = 50
      type     = tactical_bomber
      model    = 0
    }
  }
  # #############################
  # ##############################
  airunit =
  { id       = { type = 30008 id = 210 }
    name     = "Orel Air Command"
    location = 282
    base     = 282
    division =
    { id       = { type = 30008 id = 211 }
      name     = "75. IAD"
      strength = 50
      type     = interceptor
      model    = 1
    }
    division =
    { id       = { type = 30008 id = 212 }
      name     = "76. BAD"
      strength = 50
      type     = tactical_bomber
      model    = 0
    }
  }
  # ###########################
  # ###########################
  airunit =
  { id       = { type = 30008 id = 213 }
    name     = "Transbaikal Air Command"
    location = 1523
    base     = 1523
    division =
    { id       = { type = 30008 id = 214 }
      name     = "37./38. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 215 }
      name     = "30. BAD"
      strength = 50
      type     = tactical_bomber
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 216 }
      name     = "28. IAD"
      strength = 50
      type     = interceptor
      model    = 0
    }
  }
  # ##########################
  # ############################
  airunit =
  { id       = { type = 30008 id = 217 }
    name     = "Far East Air Command"
    location = 1372
    base     = 1372
    division =
    { id       = { type = 30008 id = 218 }
      name     = "29./31. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 219 }
      name     = "32./34. IAD"
      strength = 70
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 220 }
      name     = "69./79. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 30008 id = 221 }
      name     = "70. IAD"
      strength = 50
      type     = interceptor
      model    = 3
    }
    division =
    { id       = { type = 30008 id = 222 }
      name     = "33./53. BAD"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
  }
  # ##########upgrading independent tank bgds to divs###############
  # ######SU had only 4 tank divs in 39 but lots of ind. tank bgds#########
  division_development =
  { id    = { type = 30008 id = 14 }
    name  = "21./24. Tankovaya Diviziya"
    type  = armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = january }
  }
  division_development =
  { id    = { type = 30008 id = 19 }
    name  = "23./28. Tankovaya Diviziya"
    type  = armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = january }
  }
  division_development =
  { id    = { type = 30008 id = 34 }
    name  = "27./36. Tankovaya Diviziya"
    type  = armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = february }
  }
  division_development =
  { id    = { type = 30008 id = 37 }
    name  = "10./26. Tankovaya Diviziya"
    type  = armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = february }
  }
  division_development =
  { id    = { type = 30008 id = 52 }
    name  = "29./33rd Tank Division"
    type  = armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = february }
  }
  division_development =
  { id    = { type = 30008 id = 56 }
    name  = "22./30. Tankovaya Diviziya"
    type  = armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = march }
  }
  division_development =
  { id    = { type = 30008 id = 63 }
    name  = "25./31. Tankovaya Diviziya"
    type  = light_armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = march }
  }
  division_development =
  { id    = { type = 30008 id = 77 }
    name  = "20./35. Tankovaya Diviziya"
    type  = light_armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = march }
  }
  division_development =
  { id    = { type = 30008 id = 97 }
    name  = "8./32. Tankovaya Diviziya"
    type  = light_armor
    model = 1
    cost  = 3
    date  = { year = 1939 month = december }
  }
  division_development =
  { id    = { type = 30008 id = 102 }
    name  = "15./39. Tankovaya Diviziya"
    type  = light_armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = february }
  }
  division_development =
  { id    = { type = 30008 id = 106 }
    name  = "12./34. Tankovaya Diviziya"
    type  = light_armor
    model = 1
    cost  = 3
    date  = { year = 1939 month = december }
  }
  division_development =
  { id    = { type = 30008 id = 118 }
    name  = "11./16. Tankovaya Diviziya"
    type  = light_armor
    model = 1
    cost  = 3
    date  = { year = 1940 month = january }
  }
  division_development =
  { id    = { type = 30008 id = 147 }
    name  = "9./19. Tankovaya Diviziya"
    type  = light_armor
    model = 1
    cost  = 3
    date  = { year = 1939 month = november }
  }
  division_development =
  { id    = { type = 30008 id = 320 }
    name  = "1. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 321 }
    name  = "2. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 322 }
    name  = "3. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 323 }
    name  = "4. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 324 }
    name  = "5. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 325 }
    name  = "6. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 326 }
    name  = "7. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 327 }
    name  = "8. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 328 }
    name  = "9. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 329 }
    name  = "10. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = september }
  }
  division_development =
  { id    = { type = 30008 id = 330 }
    name  = "11. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = october }
  }
  division_development =
  { id    = { type = 30008 id = 331 }
    name  = "12. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = october }
  }
  division_development =
  { id    = { type = 30008 id = 332 }
    name  = "13. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = october }
  }
  division_development =
  { id    = { type = 30008 id = 333 }
    name  = "14. NKVD Diviziya"
    type  = infantry
    model = 1
    cost  = 0
    date  = { year = 1941 month = october }
  }
  # ships under construction
  division_development =
  { name  = "Voroshilov"
    type  = heavy_cruiser
    model = 1
    cost  = 4.8
    id    = { type = 10849 id = 700 }
    date  = { year = 1940 month = june day = 15 }
  }
  division_development =
  { name  = "10. Flotiliya Esmintsev"
    type  = destroyer
    model = 1
    cost  = 1.9
    id    = { type = 10849 id = 701 }
    date  = { year = 1939 month = october day = 1 }
  }
  division_development =
  { name  = "36. Flotiliya Podlodok"
    type  = submarine
    model = 1
    cost  = 1.9
    id    = { type = 10849 id = 702 }
    date  = { year = 1939 month = october day = 1 }
  }
  division_development =
  { name  = "37. Flotiliya Podlodok"
    type  = submarine
    model = 2
    cost  = 1.9
    id    = { type = 10849 id = 703 }
    date  = { year = 1939 month = november day = 1 }
  }
}
