
##############################
# Country definition for USA #
##############################

province =
{ id         = 549
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
}              # Anchorage
province = { id = 553 supplypool = 500 } # Juneau
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Plattsburgh
province =
{ id       = 595
  ic       = 2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id         = 600
  ic         = 3
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Boston
province =
{ id         = 602
  ic         = 4
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # New York
province = { id = 603 ic = 6 } # Newark
province =
{ id         = 606
  ic         = 2
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Washington D.C.
province = { id = 608 ic = 3 anti_air = 2 } # Philadelphia
province = { id = 609 ic = 1 } # Harrisburg
province = { id = 613 ic = 3 } # Buffalo
province =
{ id       = 614
  ic       = 3
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Pittsburgh
province = { id = 615 ic = 2 } # Cleveland
province =
{ id       = 616
  ic       = 4
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Detroit
province = { id = 619 ic = 1 } # Indianapolis
province =
{ id       = 620
  ic       = 3
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Chicago
province =
{ id       = 621
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Milwaukee
province =
{ id         = 633
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Norfolk
Province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 640
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province =
{ id       = 644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charleston
Province =
{ id       = 648
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Jacksonville
province =
{ id         = 651
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Miami
province = { id = 662 supplypool = 100 } # Midway Island
province =
{ id         = 663
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
}              # Pearl Harbour
province =
{ id       = 670
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Atlanta
Province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Memphis
Province =
{ id       = 678
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Biloxi
province =
{ id       = 684
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Little Rock
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # St. Louis
province =
{ id       = 692
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Des Moines
province =
{ id       = 693
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
province =
{ id       = 698
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Bismarck
province =
{ id       = 707
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Denver
Province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Oklahoma City
province =
{ id       = 716
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Houston
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 730
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Phoenix
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Salt Lake City
Province =
{ id         = 748
  anti_air   = 1
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 8 current_size = 8 }
}              # Corpus Christi
province =
{ id         = 761
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Diego
province =
{ id         = 762
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # Los Angeles
province =
{ id       = 764
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id         = 765
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Francisco
province =
{ id         = 780
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Seattle
province =
{ id       = 783
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Portland
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Tulsa
province =
{ id         = 889
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Colon
province = { id = 895 supplypool = 50 } # Puerto Rico
province = { id = 1408 supplypool = 50 } # Attu Island
province =
{ id         = 1624
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Guam
province = { id = 1756 supplypool = 50 } # Samoa
province = { id = 1762 supplypool = 1 } # Phoenix Island
province = { id = 1765 supplypool = 50 } # Palmyra
province = { id = 1766 supplypool = 1 } # Johnson Island
province =
{ id         = 1786
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Wake Island

#####################
# Country main data #
#####################

country =
{ tag                    = USA
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 2000
  money                  = 100
  manpower               = 175
  transports             = 80
  escorts                = 80
  peacetime_ic_mod       = 0.25
  capital                = 606
  diplomacy =
  { relation =
    { tag        = ARG
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = AST value = 125 }
    relation = { tag = BEL value = 75 }
    relation = { tag = BHU value = 100 }
    relation =
    { tag        = BOL
      value      = 85
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = BRA
      value      = 120
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = CAN value = 175 }
    relation =
    { tag        = CHL
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = COL
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = COS
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = CUB
      value      = 200
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = DEN value = 75 }
    relation =
    { tag        = DOM
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = ECU
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = 90 }
    relation = { tag = FRA value = 65 }
    relation = { tag = GER value = -50 }
    relation =
    { tag        = GUA
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = HAI
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = HOL value = 70 }
    relation =
    { tag        = HON
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = IRE value = 75 }
    relation = { tag = IRQ value = 120 }
    relation = { tag = JAP value = 15 }
    relation = { tag = LIB value = 200 access = yes }
    relation = { tag = MAN value = 1 }
    relation = { tag = MEN value = 1 }
    relation =
    { tag        = MEX
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = NEP value = 100 }
    relation =
    { tag        = NIC
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = NOR value = 75 }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation =
    { tag        = PAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = PAR
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = PHI value = 200 access = yes }
    relation =
    { tag        = PRU
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = SAF value = 125 }
    relation =
    { tag        = SCH
      value      = 1
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation =
    { tag        = SAL
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = SOV value = 35 }
    relation = { tag = SWE value = 75 }
    relation =
    { tag        = URU
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = VEN
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = YEM value = 100 }
  }
  nationalprovinces      = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  1408 895  889
			   }
  ownedprovinces         = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1786 1624 1408 1764 1765
			   }
  controlledprovinces    = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1786 1624 1408 1764 1765
			   }
  # USA 1939 techs
  # ######################
  techapps               = { 12100 12110 4010  4020  4040  4050  4030  4120  4130  4140  4190  4220  4250  4260  2150  2010  2020  2030  2040  2290
			     2300  2310  2320  2330  2400  2450  2460  2510  1010  1020  1190  1200  1210  1220  1110  1150  1310  1340  5010  5020
			     5030  5050  5060  5070  5080  5090  5100  5110  5120  5130  5160  5190  5200  5210  5310  5320  5350  5360  5410  5470
			     5480  5490  9010  9020  9030  9140  6010  6020  6040  8010  8020  8030  8040  8050  8060  8090  8100  8110  8180  3010
			     3020  3030  3070  3080  3090  3100  3130  3140  3150  3190  3200  3210  3250  3260  3270  3280  3320  3330  3340  3350
			     3400  3410  3420  3430  14000 14010
			   }
  SpyInfo                = { country = "USA" NumberOfSpies = 13 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    freedom           = 10
    free_market       = 10
    professional_army = 1
    defense_lobby     = 1
    interventionism   = 2 # The Rape of Nanking has happened
  }
  headofstate            = { type = 9 id = 6001 }
  headofgovernment       = { type = 9 id = 6002 }
  foreignminister        = { type = 9 id = 6003 }
  armamentminister       = { type = 9 id = 6077 }
  ministerofsecurity     = { type = 9 id = 6005 }
  ministerofintelligence = { type = 9 id = 6006 }
  chiefofstaff           = { type = 9 id = 6136 }
  chiefofarmy            = { type = 9 id = 6144 }
  chiefofnavy            = { type = 9 id = 6159 }
  chiefofair             = { type = 9 id = 6167 }
  dormant_ministers      = { 6176 6009 6162 6158 6010 6004 6114 }
  # ############
  # ##USA OOB###
  # ############
  landunit =
  { location = 663
    name     = "Pacific HQ"
    id       = { type = 30014 id = 1101 }
    division =
    { id       = { type = 30014 id = 1102 }
      type     = hq
      model    = 0
      strength = 50
      name     = "Pacific HQ"
    }
  }
  landunit =
  { location = 765
    name     = "CONUS HQ"
    id       = { type = 30014 id = 1103 }
    division =
    { id       = { type = 30014 id = 1104 }
      type     = hq
      model    = 0
      strength = 50
      name     = "CONUS HQ"
    }
  }
  # landunit = {
  # location = 713
  # name = "1st Armored Corps"
  # id = { type = 30014 id = 1 }
  # division = {
  # id = { type = 30014 id = 2 }
  # type = armor
  # model = 2
  # strength = 50
  # extra = artillery
  # brigade_model = 3
  # name = "1st Armored 'Old Ironsides' Div." #The 1st Armoured was not activated till July 15, 1940.
  # }
  # division = {
  # id = { type = 30014 id = 3 }
  # type = armor
  # model = 1
  # strength = 50
  # extra = artillery
  # brigade_model = 3
  # name = "2nd Armored 'Hell on Wheels' Div." #The 2nd Armoured was not activated till July 15, 1940.
  # }
  # division = {
  # id = { type = 30014 id = 4 }
  # type = armor
  # model = 0
  # strength = 50
  # extra = artillery
  # brigade_model = 3
  # name = "3rd Armored 'Spearhead' Div." #The 3rd Armoured was not activated till 1941.
  # }
  # division = {
  # id = { type = 30014 id = 5 }
  # type = armor
  # model = 1
  # strength = 50
  # name = "4th Armored 'Breakthrough' Div." #The 4th Armoured was not activated till 15 Apr 1941.
  # }
  # division = {
  # id = { type = 30014 id = 6 }
  # type = armor
  # model = 0
  # strength = 50
  # name = "5th Armored 'Victory' Div." #The 5th Armoured was not activated till 1941.
  # }
  # }
  # ########################
  # ########################
  landunit =
  { id       = { type = 30014 id = 7 }
    name     = "1st Army Corps"
    location = 607
    # division = {
    # id = { type = 30014 id = 8 }
    # type = infantry
    # strength = 50
    # name = "8th 'Pathfinder' Division" #Activated: 1 July 1940
    # extra = artillery
    # brigade_model = 3
    # }
    # division = {
    # id = { type = 30014 id = 9 }
    # type = infantry
    # strength = 50
    # name = "9th 'Old Reliables' Division" #Activated: 1 August 1940
    # }
    division =
    { id       = { type = 30014 id = 10 }
      type     = infantry
      strength = 10
      name     = "30th 'Old Hickory' NG Division"
    }
  }
  # #########################
  # #########################
  landunit =
  { id       = { type = 30014 id = 11 }
    name     = "2nd Army Corps"
    location = 626
    division =
    { id            = { type = 30014 id = 12 }
      type          = infantry
      strength      = 10
      name          = "28th 'Keystone' NG Division"
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id       = { type = 30014 id = 13 }
      type     = infantry
      strength = 10
      name     = "29th 'Blue and Gray' NG Division"
    }
    division =
    { id       = { type = 30014 id = 14 }
      type     = infantry
      strength = 10
      name     = "44th Infantry NG Division"
    }
  }
  # ###########################
  # ###########################
  landunit =
  { id       = { type = 30014 id = 15 }
    name     = "6th Army Corps"
    location = 762
    division =
    { id            = { type = 30014 id = 16 }
      type          = infantry
      strength      = 50
      name          = "1st 'Big Red One' Division"
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id       = { type = 30014 id = 17 }
      type     = infantry
      strength = 10
      name     = "26th 'Yankee' NG Division"
    }
  }
  # ###########################
  # ###########################
  landunit =
  { id       = { type = 30014 id = 18 }
    name     = "7th Army Corps"
    location = 634
    division =
    { id       = { type = 30014 id = 19 }
      type     = infantry
      strength = 10
      name     = "27th 'New York Division' NG"
    }
    division =
    { id       = { type = 30014 id = 20 }
      type     = infantry
      strength = 10
      name     = "33rd 'Golden Cross' NG Division"
    }
    division =
    { id       = { type = 30014 id = 21 }
      type     = infantry
      strength = 10
      name     = "35th 'Santa Fe' NG Division"
    }
  }
  # division = {
  # id = { type = 30014 id = 22 }
  # type = cavalry
  # strength = 50
  # name = "2nd Cavalry (Colored) Division" #Activated: 1 April 1941
  # }
  # ########################
  # #########################
  landunit =
  { id       = { type = 30014 id = 25 }
    location = 716
    name     = "4th Army Corps"
    # division = {
    # id = { type = 30014 id = 26 }
    # type = motorized
    # strength = 50
    # name = "4th 'Iron Horse' Division" #Reactivated on June 1, 1040.
    # }
    division =
    { id            = { type = 30014 id = 27 }
      type          = infantry
      strength      = 10
      name          = "31st 'Dixie' NG Division"
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id            = { type = 30014 id = 28 }
      type          = infantry
      strength      = 10
      name          = "43rd 'Winged Victory' NG Division"
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id       = { type = 30014 id = 29 }
      type     = cavalry
      strength = 50
      name     = "1st Cavalry 'The 1st Team' Div."
    }
  }
  # #############################
  # #############################
  landunit =
  { id       = { type = 30014 id = 30 }
    location = 782
    name     = "5th Army Corps"
    division =
    { id       = { type = 30014 id = 31 }
      type     = infantry
      strength = 10
      name     = "32nd 'Red Arrow' NG Division"
    }
    division =
    { id       = { type = 30014 id = 32 }
      type     = infantry
      strength = 10
      name     = "34th 'Red Bull' NG Division"
    }
    division =
    { id       = { type = 30014 id = 33 }
      strength = 10
      name     = "37th 'Buckeye' NG Division"
      type     = infantry
    }
    division =
    { id            = { type = 30014 id = 34 }
      strength      = 10
      name          = "38th 'Cyclone' NG Division"
      type          = infantry
      extra         = artillery
      brigade_model = 3
    }
  }
  # ##############################
  # ##############################
  landunit =
  { id       = { type = 30014 id = 35 }
    location = 603
    name     = "8th Army Corps"
    division =
    { id            = { type = 30014 id = 36 }
      strength      = 50
      name          = "2nd 'Indianhead' Division"
      type          = infantry
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id       = { type = 30014 id = 37 }
      strength = 10
      name     = "36th 'Texas' NG Division"
      type     = infantry
    }
    division =
    { id       = { type = 30014 id = 38 }
      strength = 10
      name     = "45th 'Thunderbird' NG Division"
      type     = infantry
    }
  }
  # #################################
  # #################################
  landunit =
  { id       = { type = 30014 id = 39 }
    location = 627
    name     = "3rd Army Corps"
    # division = {
    # id = { type = 30014 id = 40 }
    # strength = 50
    # name = "7th 'Bayonet!' Division" # Activated: 1 July 1940
    # type = infantry
    # }
    division =
    { id            = { type = 30014 id = 41 }
      strength      = 10
      name          = "40th 'Sunshine' NG Division"
      type          = infantry
      extra         = artillery
      brigade_model = 3
    }
  }
  # ##################################
  # ##################################
  landunit =
  { id       = { type = 30014 id = 42 }
    location = 648
    name     = "9th Army Corps"
    division =
    { id       = { type = 30014 id = 43 }
      strength = 50
      name     = "3rd 'Rock of the Marne' Division"
      type     = infantry
    }
    division =
    { id            = { type = 30014 id = 44 }
      strength      = 10
      name          = "41st 'Sunset' NG Division"
      type          = infantry
      extra         = artillery
      brigade_model = 3
    }
  }
  # #################################
  # #################################
  landunit =
  { id       = { type = 30014 id = 45 }
    location = 658
    name     = "Hawaiian Army Corps"
    division =
    { id       = { type = 30014 id = 46 }
      strength = 50
      name     = "24th 'Victory' Division"
      type     = infantry
    }
  }
  # division = {
  # id = { type = 30014 id = 47 }
  # strength = 50
  # name = "25th 'Tropic Lightning' Division" # Activated: 10 October 1941 in Hawaii
  # type = infantry
  # }
  # #################################
  # ##################################
  landunit =
  { id       = { type = 30014 id = 48 }
    location = 1737
    name     = "Philippine Division"
    division =
    { id       = { type = 30014 id = 49 }
      strength = 50
      name     = "Philippine Division"
      type     = infantry
      locked   = yes
    }
  }
  landunit =
  { id       = { type = 12000 id = 220 }
    name     = "Panama Canal Force"
    location = 889
    division =
    { id            = { type = 12000 id = 221 }
      name          = "Panama Canal Garrison"
      type          = garrison
      model         = 0
      locked        = yes
      extra         = artillery
      brigade_model = 3
    }
  }
  # US PACIFIC FLEET-SAN DIEGO, CALIFORNIA
  # Battleship Division 1
  # Nevada, Arizona, Pennsylvania
  navalunit =
  { name     = "Battleship Division 1"
    id       = { type = 12000 id = 200 }
    location = 765
    base     = 765
    division =
    { id            = { type = 12400 id = 650 }
      name          = "USS Lexington"
      strength      = 100
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 3
    }
    division =
    { id    = { type = 12400 id = 2001 }
      name  = "USS Nevada"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2002 }
      name  = "USS Arizona"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2003 }
      name  = "USS Pennsylvania"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12400 id = 4000 }
      name  = "Edward Rutledge Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4001 }
      name  = "Young America Flotilla"
      type  = transport
      model = 0
    }
  }
  # Battleship Division 2
  # Oklahoma, Tennessee, California
  navalunit =
  { name     = "Battleship Division 2"
    id       = { type = 12000 id = 201 }
    location = 765
    base     = 765
    division =
    { id            = { type = 12400 id = 651 }
      name          = "USS Saratoga"
      strength      = 100
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 3
    }
    division =
    { id    = { type = 12400 id = 2004 }
      name  = "USS Oklahoma"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2005 }
      name  = "USS Tennessee"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2006 }
      name  = "USS California"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12400 id = 4002 }
      name  = "Abraham Lincoln Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4003 }
      name  = "Susan B. Anthony Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { id       = { type = 12400 id = 1000 }
    name     = "USS Enterprise"
    location = 761
    base     = 761
    division =
    { id            = { type = 12400 id = 1001 }
      name          = "USS Enterprise"
      strength      = 100
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 3
    }
  }
  # Battleship Division 4
  # Colorado, West Virginia, Maryland
  navalunit =
  { name     = "Battleship Division 4"
    id       = { type = 12000 id = 202 }
    location = 761
    base     = 761
    division =
    { id    = { type = 12400 id = 2007 }
      name  = "USS Colorado"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 12400 id = 2008 }
      name  = "USS West Virginia"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 12400 id = 2009 }
      name  = "USS Maryland"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 12400 id = 4004 }
      name  = "State Of Maryland Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4005 }
      name  = "Amherst Victory Flotilla"
      type  = transport
      model = 0
    }
  }
  # Pacific Light Cruiser Division 3
  # Richmond, Trenton, Concord
  navalunit =
  { name     = "Pacific Light Cruiser Division 3"
    id       = { type = 12000 id = 203 }
    location = 761
    base     = 761
    division =
    { id    = { type = 12400 id = 5000 }
      name  = "USS Raleigh"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 5001 }
      name  = "USS Detroit"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 5002 }
      name  = "USS Vincennes"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 12400 id = 5003 }
      name  = "USS Brooklyn"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 12400 id = 5004 }
      name  = "USS Philadelphia"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 12400 id = 5005 }
      name  = "USS Savannah"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 12400 id = 2011 }
      name  = "USS Richmond"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2012 }
      name  = "USS Trenton"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2013 }
      name  = "USS Concord"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 4006 }
      name  = "Josiah Bartlett Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4007 }
      name  = "Sea Marlin Flotilla"
      type  = transport
      model = 0
    }
  }
  # Pacific Light Cruiser Division 9
  # Phoenix, Boise, Honolulu, St. Louis
  navalunit =
  { name     = "Pacific Light Cruiser Division 9"
    id       = { type = 12000 id = 204 }
    location = 761
    base     = 761
    division =
    { id    = { type = 12400 id = 2021 }
      name  = "USS Phoenix"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 12400 id = 2022 }
      name  = "USS Boise"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 12400 id = 2033 }
      name  = "USS Honolulu"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 12400 id = 4008 }
      name  = "Booker T. Washington Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4009 }
      name  = "Storm King Flotilla"
      type  = transport
      model = 0
    }
  }
  # Pacific Light Cruiser Division 4
  # Pensacola, Salt Lake City, Chicago, Indianapolis
  navalunit =
  { name     = "Pacific Light Cruiser Division 4"
    id       = { type = 12000 id = 205 }
    location = 761
    base     = 761
    division =
    { id    = { type = 12400 id = 2061 }
      name  = "USS Pensacola"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2062 }
      name  = "USS Salt Lake City"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2063 }
      name  = "USS Chicago"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2064 }
      name  = "USS Indianapolis"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 4010 }
      name  = "Uruguay Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4011 }
      name  = "A. P. Hill Flotilla"
      type  = transport
      model = 0
    }
  }
  # Pacific Light Cruiser Division 5
  # Northampton, Chester, Louisville, Portland
  navalunit =
  { name     = "Pacific Light Cruiser Division 5"
    id       = { type = 12000 id = 206 }
    location = 761
    base     = 765
    division =
    { id    = { type = 12400 id = 2041 }
      name  = "USS Northampton"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2042 }
      name  = "USS Chester"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2043 }
      name  = "USS Louisville"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2044 }
      name  = "USS Portland"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12400 id = 4012 }
      name  = "Admiral Hugh Rodman Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4013 }
      name  = "U. S. Grant Flotilla"
      type  = transport
      model = 0
    }
  }
  # Pacific Light Cruiser Division 6
  # New Orleans, Astoria, Minneapolis, San Francisco
  navalunit =
  { name     = "Pacific Light Cruiser Division 6"
    id       = { type = 12000 id = 207 }
    location = 761
    base     = 761
    division =
    { id    = { type = 12400 id = 2051 }
      name  = "USS New Orleans"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 12400 id = 2052 }
      name  = "USS Astoria"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 12400 id = 2053 }
      name  = "USS Minneapolis"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 12400 id = 2054 }
      name  = "USS San Fransisco"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 12400 id = 4014 }
      name  = "Lincoln Victory Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4015 }
      name  = "Roanoke Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { name     = "Pacific Destroyers"
    id       = { type = 14800 id = 61 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 62 }
      name  = "1st Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 63 }
      name  = "2nd Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 64 }
      name  = "3rd Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 65 }
      name  = "4th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 66 }
      name  = "5th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 67 }
      name  = "6th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 68 }
      name  = "7th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 69 }
      name  = "8th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 70 }
      name  = "9th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 71 }
      name  = "10th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 72 }
      name  = "11th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 14800 id = 73 }
      name  = "12th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 14800 id = 101 }
      name  = "13th Destroyer Division"
      type  = destroyer
      model = 2
    }
  }
  # 24 Submarines = 5 submarine units
  navalunit =
  { name     = "Pacific Submarines"
    id       = { type = 12000 id = 2208 }
    location = 761
    base     = 761
    division =
    { id    = { type = 12400 id = 2331 }
      name  = "1st Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2332 }
      name  = "2nd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2333 }
      name  = "3rd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2334 }
      name  = "4th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12400 id = 2335 }
      name  = "5th Submarine Division"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { location = 663
    base     = 663
    id       = { type = 12000 id = 3004 }
    name     = "Asiatic Fleet"
    division =
    { id       = { type = 12000 id = 3005 }
      name     = "26th Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 12000 id = 3006 }
      name     = "27th Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 12000 id = 3007 }
      name     = "28th Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 12000 id = 3008 }
      name     = "6th Submarine Division"
      strength = 100
      type     = submarine
      model    = 0
    }
    division =
    { id       = { type = 12000 id = 3009 }
      name     = "7th Submarine Division"
      strength = 100
      type     = submarine
      model    = 0
    }
    division =
    { id    = { type = 12400 id = 4018 }
      name  = "1st Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4019 }
      name  = "2nd Transport Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { location = 663
    base     = 663
    id       = { type = 12000 id = 13004 }
    name     = "8th Submarine Division"
    division =
    { id       = { type = 12000 id = 3012 }
      name     = "8th Submarine Division"
      strength = 100
      type     = submarine
      model    = 1
    }
  }
  navalunit =
  { location = 780
    base     = 780
    id       = { type = 12000 id = 3014 }
    name     = "Seattle Fleet"
    division =
    { id       = { type = 12000 id = 3015 }
      name     = "USS Marblehead"
      strength = 100
      type     = light_cruiser
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3016 }
      name     = "29th Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
  }
  navalunit =
  { location = 780
    base     = 780
    id       = { type = 12000 id = 3018 }
    name     = "Columbia Fleet"
    division =
    { id       = { type = 12000 id = 3019 }
      name     = "USS Houston"
      strength = 100
      type     = heavy_cruiser
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3020 }
      name     = "9th Submarine Division"
      strength = 100
      type     = submarine
      model    = 1
    }
  }
  navalunit =
  { location = 748
    base     = 748
    id       = { type = 12000 id = 3022 }
    name     = "Carribean Fleet"
    division =
    { id       = { type = 12000 id = 3023 }
      name     = "21st Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 12000 id = 3024 }
      name     = "10th Submarine Division"
      strength = 100
      type     = submarine
      model    = 1
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 12000 id = 3026 }
    name     = "Battleship Division 3"
    division =
    { id       = { type = 12000 id = 3027 }
      name     = "USS New Mexico"
      strength = 100
      type     = battleship
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3028 }
      name     = "USS Mississippi"
      strength = 100
      type     = battleship
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3029 }
      name     = "USS Idaho"
      strength = 100
      type     = battleship
      model    = 1
    }
    division =
    { id    = { type = 12400 id = 4020 }
      name  = "Algonquin Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4021 }
      name  = "Mormacport Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 12000 id = 3031 }
    name     = "Battleship Division 5"
    division =
    { id       = { type = 12000 id = 3032 }
      name     = "USS Arkansas"
      strength = 100
      type     = battleship
      model    = 0
    }
    division =
    { id       = { type = 12000 id = 3033 }
      name     = "USS New York"
      strength = 100
      type     = battleship
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3034 }
      name     = "USS Texas"
      strength = 100
      type     = battleship
      model    = 1
    }
    division =
    { id    = { type = 12400 id = 4022 }
      name  = "Vassar Victory Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4023 }
      name  = "President Tyler Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 12000 id = 3039 }
    name     = "Atlantic Light Cruiser Division 2"
    division =
    { id       = { type = 12000 id = 3040 }
      name     = "USS Omaha"
      strength = 100
      type     = light_cruiser
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3041 }
      name     = "USS Milwaukee"
      strength = 100
      type     = light_cruiser
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3042 }
      name     = "USS Cincinnati"
      strength = 100
      type     = light_cruiser
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3043 }
      name     = "USS Memphis"
      strength = 100
      type     = light_cruiser
      model    = 1
    }
    division =
    { id    = { type = 12400 id = 5007 }
      name  = "USS Nashville"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 12400 id = 5008 }
      name  = "USS Wichita"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 12400 id = 4024 }
      name  = "Elbridge Gerry Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12400 id = 4025 }
      name  = "Cape Newenham Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 12000 id = 3045 }
    name     = "Atlantic Light Cruiser Division 7"
    division =
    { id       = { type = 12000 id = 3046 }
      name     = "USS Augusta"
      strength = 100
      type     = heavy_cruiser
      model    = 1
    }
    division =
    { id       = { type = 12000 id = 3047 }
      name     = "USS Tuscaloosa"
      strength = 100
      type     = heavy_cruiser
      model    = 2
    }
    division =
    { id       = { type = 12000 id = 3048 }
      name     = "USS Quincy"
      strength = 100
      type     = heavy_cruiser
      model    = 2
    }
    division =
    { id    = { type = 12400 id = 4026 }
      name  = "Sea Ray Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 30010 id = 183 }
    name     = "Ranger Taskforce"
    division =
    { id            = { type = 30010 id = 184 }
      name          = "USS Ranger"
      strength      = 100
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 3
    }
    division =
    { id       = { type = 30010 id = 185 }
      name     = "30th Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 30010 id = 186 }
      name     = "31st Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 30010 id = 187 }
      name     = "32nd Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 30010 id = 189 }
    name     = "Yorktown Taskforce"
    division =
    { id            = { type = 30010 id = 190 }
      name          = "USS Yorktown"
      strength      = 100
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 3
    }
    division =
    { id       = { type = 30010 id = 191 }
      name     = "33rd Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 30010 id = 192 }
      name     = "34th Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 30010 id = 193 }
      name     = "35th Destroyer Division"
      strength = 100
      type     = destroyer
      model    = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 30010 id = 195 }
    name     = "Atl Submarine Division"
    division =
    { id       = { type = 30010 id = 196 }
      name     = "11th Submarine Division"
      strength = 100
      type     = submarine
      model    = 1
    }
    division =
    { id       = { type = 30010 id = 600 }
      name     = "12th Submarine Division"
      strength = 100
      type     = submarine
      model    = 1
    }
    division =
    { id       = { type = 30010 id = 601 }
      name     = "13th Submarine Division"
      strength = 100
      type     = submarine
      model    = 1
    }
    division =
    { id       = { type = 30010 id = 602 }
      name     = "14th Submarine Division"
      strength = 100
      type     = submarine
      model    = 1
    }
    division =
    { id       = { type = 30010 id = 603 }
      name     = "15th Submarine Division"
      strength = 100
      type     = submarine
      model    = 3
    }
    division =
    { id       = { type = 30010 id = 604 }
      name     = "16th Submarine Division"
      strength = 100
      type     = submarine
      model    = 3
    }
    division =
    { id       = { type = 30010 id = 605 }
      name     = "17th Submarine Division"
      strength = 100
      type     = submarine
      model    = 3
    }
    division =
    { id       = { type = 30010 id = 606 }
      name     = "18th Submarine Division"
      strength = 100
      type     = submarine
      model    = 3
    }
    division =
    { id       = { type = 30010 id = 607 }
      name     = "19th Submarine Division"
      strength = 100
      type     = submarine
      model    = 3
    }
  }
  # ############################
  # ############################
  airunit =
  { id       = { type = 30014 id = 137 }
    name     = "1st Air Force"
    location = 633
    base     = 633
    division =
    { id       = { type = 30014 id = 138 }
      name     = "1st USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
    division =
    { id       = { type = 30014 id = 139 }
      name     = "6th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 2
    }
  }
  # ############################
  # ############################
  airunit =
  { id       = { type = 30014 id = 140 }
    name     = "2nd Air Force"
    location = 761
    base     = 761
    division =
    { id       = { type = 30014 id = 141 }
      name     = "2nd USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
    division =
    { id       = { type = 30014 id = 142 }
      name     = "7th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 2
    }
    division =
    { id       = { type = 30014 id = 610 }
      name     = "1st USAAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 0
    }
  }
  # #############################
  # #############################
  airunit =
  { id       = { type = 30014 id = 143 }
    name     = "3rd Air Force"
    location = 602
    base     = 602
    division =
    { id       = { type = 30014 id = 144 }
      name     = "3rd USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
    division =
    { id       = { type = 30014 id = 145 }
      name     = "9th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 2
    }
  }
  # #############################
  # ##############################
  airunit =
  { id       = { type = 30014 id = 146 }
    name     = "4th Air Force"
    location = 780
    base     = 780
    division =
    { id       = { type = 30014 id = 147 }
      name     = "4th USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
    division =
    { id       = { type = 30014 id = 148 }
      name     = "10th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 2
    }
  }
  # #############################
  # #############################
  airunit =
  { id       = { type = 30014 id = 149 }
    name     = "Hawaiian Air Force"
    location = 663
    base     = 663
    division =
    { id       = { type = 30014 id = 150 }
      name     = "18th USAF Tactical Bomb. Wing"
      strength = 30
      type     = tactical_bomber
      model    = 1
    }
    division =
    { id       = { type = 30014 id = 151 }
      name     = "11th USAF interceptor Wing"
      strength = 30
      type     = interceptor
      model    = 2
    }
  }
  # ##############################
  # ##############################
  airunit =
  { id       = { type = 30014 id = 152 }
    name     = "Far East Air Force"
    location = 1737
    base     = 1737
    division =
    { id       = { type = 30014 id = 153 }
      name     = "5th USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
    division =
    { id       = { type = 30014 id = 154 }
      name     = "62d USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 2
    }
  }
  # Under Construction#
  division_development =
  { name  = "USS Wasp"
    type  = carrier
    model = 2
    cost  = 4.5
    id    = { type = 12000 id = 502 }
    date  = { year = 1940 month = april day = 25 }
    extra = cag
    brigade_model = 2
  }
  division_development =
  { name  = "USS St. Louis"
    type  = light_cruiser
    model = 3
    cost  = 4.5
    id    = { type = 12000 id = 503 }
    date  = { year = 1939 month = december day = 1 }
  }
  division_development =
  { name  = "USS Helena"
    type  = light_cruiser
    model = 3
    cost  = 4.5
    id    = { type = 12000 id = 504 }
    date  = { year = 1939 month = december day = 14 }
  }
  division_development =
  { name  = "36th Destroyer Division"
    type  = destroyer
    model = 2
    cost  = 1.5
    id    = { type = 12000 id = 505 }
    date  = { year = 1939 month = october day = 1 }
  }
  division_development =
  { name  = "37st Destroyer Division"
    type  = destroyer
    model = 2
    cost  = 1.5
    id    = { type = 12000 id = 506 }
    date  = { year = 1939 month = december day = 1 }
  }
  division_development =
  { name  = "20th Submarine Division"
    type  = submarine
    model = 3
    cost  = 2.3
    id    = { type = 12000 id = 507 }
    date  = { year = 1939 month = november day = 1 }
  }
  division_development =
  { name  = "21st Submarine Division"
    type  = submarine
    model = 3
    cost  = 2.3
    id    = { type = 12000 id = 508 }
    date  = { year = 1939 month = december day = 1 }
  }
  division_development =
  { id   = { type = 30014 id = 23 }
    type = infantry
    name = "5th 'Red Devils' Division"
    cost = 2
    date = { year = 1939 month = october day = 2 }
  }
  division_development =
  { id   = { type = 30014 id = 24 }
    type = infantry
    name = "6th 'Sightseeing Sixth' Division"
    cost = 2
    date = { year = 1939 month = october day = 12 }
  }
}
