province = {
	id = 1188
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1599
	air_base = {
		size = 3
		current_size = 3
		}

	naval_base = {
		size = 2
		current_size = 2
		}

	supplypool = 500
	oilpool = 200
	}

province = {
	id = 1190
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


province = {
	id = 1613
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 6
		current_size = 6
		}

	energy	=	18
	metal	=	10
	rare_materials =	6
	oil	=	6

	ic = 6
	coastalfort = 1
	supplypool = 500
	oilpool = 200
	}


province = {
	id = 1627
	air_base = {
		size = 3
		current_size = 3
		}

	naval_base = {
		size = 2
		current_size = 2
		}

	supplypool = 500
	oilpool = 200
	}


province = {
	id = 1621
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 6
		current_size = 6
		}

	       coastalfort = 1
	supplypool = 500
	oilpool = 50
	}




province = {
	id = 1683
	air_base = {
		size = 2
		current_size = 2
		}

	naval_base = {
		size = 1
		current_size = 1
		}
	supplypool = 500
	oilpool = 50
	}

province = {
	id = 1188
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


province = {
	id = 1190
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

#1187 Osaka
province = {
	id = 1187
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1188
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1185
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


#Taiwan
province = {
	id = 1322
	anti_air = 2
	air_base = {
		size = 8
		current_size = 8
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	supplypool = 500
	oilpool = 150
	}

#Hainan
province = {
	id = 1321
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	supplypool = 200
	oilpool = 50
	}


#Okinawa
province = {
	id = 1193
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 6
		current_size = 6
		}
	supplypool = 100
	oilpool = 10
	}
#Saigon
province = {
	id = 1337
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	supplypool = 1500
	oilpool = 500
	}

province = {
	id = 1340
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}
	}

province = {
	id = 1328
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 4
		current_size = 4
		}
	supplypool = 100
	oilpool = 10
	}




country = {
	tag = JAP

	policy = {
	date = { year = 0 month = january day = 0 }
	democratic = 1
	political_left = 4
	freedom = 3
	free_market = 3
	professional_army = 3
	defense_lobby = 8
	interventionism = 8
		 }

		headofstate = { type = 9 id = 5001 }
		headofgovernment = { type = 9 id = 5042 }
		foreignminister = { type = 9 id = 5065 }
		armamentminister = { type = 9 id = 5091 }
		ministerofsecurity = { type = 9 id = 5122 }
		ministerofintelligence = { type = 9 id = 5144 }
		chiefofstaff = { type = 9 id = 5156 }
		chiefofarmy = { type = 9 id = 5166 }
		chiefofnavy = { type = 9 id = 5200 }
		chiefofair = { type = 9 id = 5193 }

	capital = 1187

	manpower = 45


	oil	=	2000
	supplies = 4500

	extra_tc = 100
	free =		{
		oil	=	35
		supplies =	80
		transports = 1
		ic = 25
	}


	ownedprovinces =      { 1612 1187	1188	1189	1190	1191	1192	1193	1306	1314	1321	1322	1323	1324	1326	1328	1329	1332	1333	1334	1335	1336	1337	1338	1339	1340	1341	1599	1613	1615	1616	1617	1618	1619	1620	1621	1625	1627
}
	controlledprovinces = { 1612 1187	1188	1189	1190	1191	1192	1193	1306	1314	1321	1322	1323	1324	1326	1328	1329	1332	1333	1334	1335	1336	1337	1338	1339	1340	1341	1599	1613	1615	1616	1617	1618	1619	1620	1621	1625	1627
 }
	nationalprovinces =   { 1612 1187	1188	1189	1190	1191	1192	1193	1322	1323	1324	1599	1613	1615	1616	1617	1618	1619	1620	1621	1625	1627
 }


techapps = {
# JAP 1941 techs
#######################

1050 1040

4010 4020 4030 4050

4040 # Basic MR

4170 # Basic CAS

4120 4130 4140 4150 # Improved medium bomber (Betty)

4190 4200 # Improved naval bomber (Betty again)

4250 # Basic transport

2150 # Basic Armoured Car

2010 2020 2030 2040 # Basic light tank

2030 2050 2070 # Basic Medium

2290 2300 2310 2320 2330 # Basic artillery

2400 # Early AT

2450 2460 2470 # Basic Static AA

2510 2520 # Imp. AA

1010 1020 1030 # Basic infantry

1190 1200 1210 1220 # Semi-moto cavalry

1110 1120 1130 1070 # Imp. Mountain/Early para

1230 # Basic motorized

1150 1160 # Basic Marine

1310 1340 # Supply/repair - basics only

5010 # Agriculture (basic)

5050 5060 5070 # Advanced Machine Tools

5080 5090 5100 # Construction (up to the forts)

5110 5120 5130 5140 # Assembly lines (planes, ships)

5190 5200 # Imp. oil conversion

5310 5320 5350 # Basic encryption

5470 5480 5490 # Nuclear Tier 2

9010 9020 9030 9040 9050 9060 9070 9080 9090 9100 9110 9120 9130 9190 9200 9210 9220 9350 # Doctrines (air)

6010 6030 6110 6120 6160 # doctrine (land)

8010 8020 8030 8040 8050 8060 8090 8100 8110 8180 8230

3010 3020 3030 #(Asashio)
3070 3080 3090 3100 #(Mogami)
3130 3140 3150 #(Nachi)
3190 3200 3210 #(Amagi)
3250 3260 3270 3280 3310 #(Yamato is in the que)
3320 3330 3340 3350 3360 #(Taiho-for the CAG tech)
3400 3410 3420 3430 #(J-boats)
#hospital
14000 14010

}

	transports = 500
	escorts = 6


	landunit = {
		id = { type = 10300 id = 1 }
		name = "Dai 144 Rentai"
		location = 1613

			division = {
			id = { type = 10300 id = 2 }
			name = "Dai 144 Rentai"
			strength = 45
			max_strength = 45
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 3
			experience = 85
			}
		       }

	landunit = {
		id = { type = 10300 id = 3 }
		name = "Dai 16 'Kyoto' Hoheishidan"
		location = 1193

		division = {
		id = { type = 10300 id = 4 }
		name = "Dai 16 'Kyoto' Hoheishidan"
		strength = 100
		type = infantry
		model = 2
		experience = 85
		}
	       }

	landunit = {
		id = { type = 10300 id = 5 }
		name = "Dai 146 Rentai"
		location = 1621

			division = {
			id = { type = 10300 id = 6 }
			name = "Dai 146 Rentai"
			strength = 45
			max_strength = 45
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 3
			experience = 85
			}
		       }


	landunit = {
		id = { type = 10300 id = 7 }
		name = "Dai 25 Gun" # 25th army
		location = 1339

		division = {
		id = { type = 10300 id = 8 }
		name = "1 Konoe Shidan" # /Imperial Guard
		strength = 100
		type = infantry
		model = 2
		extra = artillery
		experience = 85
		}

		division = {
		id = { type = 10300 id = 9 }
		name = "2 Konoe Shidan"
		strength = 100
		type = cavalry
		model = 2
		extra = armored_car
		experience = 85
		}

		division = {
		id = { type = 10300 id = 10 }
		name = "33 Hoheishidan"
		strength = 100
		type = infantry
		model = 2
		extra = engineer
		experience = 70
		}
 }



	landunit = {
		id = { type = 10300 id = 11 }
		name = "Dai 21 Hoheishidan"
		location = 1326

		division = {
		id = { type = 10300 id = 12 }
		name = "Dai 21 Hoheishidan"
		strength = 100
		type = infantry
		model = 2
		experience = 70
		}
	       }



	landunit = {
		id = { type = 10300 id = 13 }
		name = "Dai 25 gun"
		location = 1321

		division = {
		id = { type = 10300 id = 14 }
		name = "Dai 22 Hoheishidan"
		strength = 100
		type = infantry
		model = 2
		experience = 70
		}

		division = {
		id = { type = 10300 id = 15 }
		name = "Dai 18 Hoheishidan"
		strength = 100
		type = infantry
		model = 2
		experience = 85
		}
	       }


	landunit = {
		id = { type = 10300 id = 16 }
		name = "Dai 38 Hoheishidan"
		location = 1314

		division = {
		id = { type = 10300 id = 17 }
		name = "Dai 38 Hoheishidan"
		strength = 100
		type = infantry
		model = 2
		experience = 85
		}
	       }


	navalunit = {
	id = { type = 10300 id = 18 }
	name = "IJN Ryujo"
	location = 1621
	base = 1621
		division = { id = { type = 10300 id = 19 }
		name = "IJN Ryujo"
		type = carrier
		model = 2
		extra = cag
		brigade_model = 4
		experience = 85}
		division = { experience = 85 id = { type = 10300 id = 20 } name = "Dai 31 Kuchiku Sentai" type = destroyer model = 1 }
		}



	navalunit = {
	id = { type = 10300 id = 21 }
	name = "Rengô Kantai 1 Sentai" # Combined Fleet 1. Squadron
	location = 1187
	base = 1187

		division = { experience = 85 id = { type = 10300 id = 22 }
		name = "IJN Nagato"
		type = battleship
		model = 2

		}

		division = { experience = 85 id = { type = 10300 id = 23 }
		name = "IJN Mutsu"
		type = battleship
		model = 2
		#seaattack = 15
		}


		}



	navalunit = {
	id = { type = 10300 id = 1002 }
	name = "Rengô Kantai 9 Sentai" # Combined Fleet 9. Squadron
	location = 1187
	base = 1187

		division = { experience = 85 id = { type = 10300 id = 52 }
		name = "IJN Kitakami"
		type = light_cruiser
		model = 1
		#seaattack = 14 # 32tt
		#maxspeed = 36
		}

		division = { experience = 85 id = { type = 10300 id = 53 }
		name = "IJN Oi"
		type = light_cruiser
		model = 1
		#seaattack = 16 # 40tt (!!)
		#maxspeed = 36
		}
		}

	navalunit = {
	id = { type = 10300 id = 1003 }
	name = "Dai 1 Kantai 2 Sentai" #1. Fleet 2. Squadron
	location = 1187
	base = 1187

		division = { experience = 85 id = { type = 10300 id = 24 }
		name = "IJN Fuso"
		type = battleship
		model = 0
		}

		division = { experience = 85 id = { type = 10300 id = 25 }
		name = "IJN Yamashiro"
		type = battleship
		model = 0
		}

		division = { experience = 85 id = { type = 10300 id = 26 }
		name = "IJN Ise"
		type = battleship
		model = 1
		}

		division = { experience = 85 id = { type = 10300 id = 27 }
		name = "IJN Hyuga"
		type = battleship
		model = 1
		}
		}



	navalunit = {
	id = { type = 10300 id = 1004 }
	name = "Dai 1 Kantai 3 Sentai"
	location = 1337
	base = 1337

		division = { experience = 85 id = { type = 10300 id = 28 }
		name = "IJN Kongo"
		type = battlecruiser
		model = 0
		}

		division = { experience = 85 id = { type = 10300 id = 29 }
		name = "IJN Haruna"
		type = battlecruiser
		model = 0
		}


		}

	navalunit = {
	id = { type = 10300 id = 1005 }
	name = "Nankai Kantai"
	location = 1613
	base = 1613

		division = { experience = 85 id = { type = 10300 id = 30 }
		name = "IJN Furutaka"
		type = heavy_cruiser
		model = 1
		#seaattack = 8 #6x8" = lower than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 31 }
		name = "IJN Kako"
		type = heavy_cruiser
		model = 1
		#seaattack = 8 #6x8" = lower than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 32 }
		name = "IJN Aoba"
		type = heavy_cruiser
		model = 1
		#seaattack = 8 #6x8" = lower than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 33 }
		name = "IJN Kinugasa"
		type = heavy_cruiser
		model = 1
		#seaattack = 8 #6x8" = lower than normal for class
		}
		}


	navalunit = {
	id = { type = 10300 id = 1006 }
	name = "Dai 1 Kantai 3 kidô butai" # 1. fleet 3rd Carrier force
	location = 1187
	base = 1187


		division = { experience = 85 id = { type = 10300 id = 1007 }
		name = "IJN Hosho"
		type = escort_carrier
		model = 0 # 21 ac/21knots/20000
		}

		division = { experience = 85 id = { type = 10300 id = 1008 }
		name = "IJN Zuiho"
		type = escort_carrier
		model = 1 # 21 ac/21knots/20000
		}
		division = { experience = 85 id = { type = 10300 id = 580 }
		name = "IJN Shoho"
		type = escort_carrier
		model = 1 # 21 ac/21knots/20000
		}
	}

	navalunit = {
	id = { type = 10300 id = 1009 }
	name = "Dai 1 Kantai 1&3 DD Sentais"
	location = 1193
	base = 1193

		division = { experience = 85 id = { type = 10300 id = 64 }
		name = "IJN Sendai"
		type = light_cruiser
		model = 2
		#maxspeed = 35
		}

		division = { experience = 85 id = { type = 10300 id = 149 } name = "Dai 40 Kuchiku Sentai" type = destroyer model = 2 }
		division = { experience = 85 id = { type = 10300 id = 150 } name = "Dai 41 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 34 } name = "Dai 13 Yuso Sentai" type = transport }
		}


	navalunit = {
	id = { type = 10300 id = 1010 }
	name = "Dai 2 Kantai 4 Sentai"
	location = 1337
	base = 1337


		division = { experience = 85 id = { type = 10300 id = 38 }
		name = "IJN Takao"
		type = heavy_cruiser
		model = 3
		#seaattack = 14 #10x8"+16tt = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 35 }
		name = "IJN Atago"
		type = heavy_cruiser
		model = 3
		#seaattack = 14 #10x8"+16tt = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 36 }
		name = "IJN Maya"
		type = heavy_cruiser
		model = 3
		#seaattack = 14 #10x8"+16tt = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 37 }
		name = "IJN Chokai"
		type = heavy_cruiser
		model = 3
		#seaattack = 10 #10x8"+16tt = higher than normal for class
		}
		}



	navalunit = {
	id = { type = 10300 id = 1011 }
	name = "Dai 2 Kantai 5 Sentai"
	location = 1621
	base = 1621

		division = { experience = 85 id = { type = 10300 id = 39 }
		name = "IJN Myoko"
		type = heavy_cruiser
		model = 2
		#seaattack = 10 #10x8" = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 40 }
		name = "IJN Nachi"
		type = heavy_cruiser
		model = 2
		#seaattack = 10 #10x8" = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 41 }
		name = "IJN Haguro"
		type = heavy_cruiser
		model = 2
		#seaattack = 10 #10x8" = higher than normal for class
		}
		}


	navalunit = {
	id = { type = 10300 id = 1041 }
	name = "Dai 2 Kantai 7 Sentai"
	location = 1327
	base = 1327

		division = { experience = 85 id = { type = 10300 id = 42 }
		name = "IJN Mogami"
		type = heavy_cruiser
		model = 3
		#seaattack = 14 #10x8"+16tt = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 43 }
		name = "IJN Mikuma"
		type = heavy_cruiser
		model = 3
		#seaattack = 14 #10x8"+16tt = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 44 }
		name = "IJN Suzuya"
		type = heavy_cruiser
		model = 3
		#seaattack = 14 #10x8"+16tt = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 45 }
		name = "IJN Kumano"
		type = heavy_cruiser
		model = 3
		#seaattack = 14 #10x8"+16tt = higher than normal for class
		}
		}

	navalunit = {
	id = { type = 10300 id = 1055 }
	name = "Dai 2 Kantai 2&4 DD Sentai"
	location = 1322
	base = 1322

		division = { experience = 85 id = { type = 10300 id = 65 }
		name = "IJN Jintsu"
		type = light_cruiser
		model = 2
		maxspeed = 35
		}

		division = { experience = 85 id = { type = 10300 id = 89 } name = "Dai 1 Kuchiku Sentai" type = destroyer model = 0 }
		division = { experience = 85 id = { type = 10300 id = 90 } name = "Dai 2 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 91 } name = "Dai 3 Kuchiku Sentai" type = destroyer model = 0 }
		division = { experience = 85 id = { type = 10300 id = 92 } name = "Dai 4 Kuchiku Sentai" type = destroyer model = 0 }
		division = { experience = 85 id = { type = 10300 id = 93 } name = "Dai 5 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 94 } name = "Dai 6 Kuchiku Sentai" type = destroyer model = 0 }


		division = { experience = 85 id = { type = 10300 id = 63 }
		name = "IJN Naka"
		type = light_cruiser
		model = 2
		maxspeed = 35
		}
		division = { experience = 85 id = { type = 10300 id = 365 } name = "Dai 11 Yuso Sentai" type = transport }
		division = { experience = 85 id = { type = 10300 id = 366 } name = "Dai 12 Yuso Sentai" type = transport }
		}

	navalunit = {
	id = { type = 10300 id = 1013 }
	name = "Dai 3 Kantai 16 Sentai"
	location = 1322
	base = 1322

		division = { experience = 85 id = { type = 10300 id = 46 }
		name = "IJN Ashigara"
		type = heavy_cruiser
		model = 2
		#seaattack = 10 #10x8" = higher than normal for class
		}

		division = { experience = 85 id = { type = 10300 id = 50 }
		name = "IJN Kuma"
		type = light_cruiser
		model = 1
		#maxspeed = 36
		}

		division = { experience = 85 id = { type = 10300 id = 56 }
		name = "IJN Nagara"
		type = light_cruiser
		model = 1
		#maxspeed = 36
		}
		}



	navalunit = {
	id = { type = 10300 id = 1015 }
	name = "Dai 4 Kantai 18 Sentai"
	location = 1327
	base = 1327


		division = { experience = 85 id = { type = 10300 id = 47 }
		name = "IJN Tenryu"
		type = light_cruiser
		model = 1
		}

		division = { experience = 85 id = { type = 10300 id = 48 }
		name = "IJN Tatsuta"
		type = light_cruiser
		model = 1
		}

		division = { experience = 85 id = { type = 10300 id = 68 }
		name = "IJN Kashima"
		type = light_cruiser
		model = 1
		maxspeed = 18
		#seaattack = 8 # lower than normal
		}

		division = { experience = 85 id = { type = 10300 id = 98 } name = "Dai 9 Kuchiku Sentai" type = destroyer  model = 0 }
		division = { experience = 85 id = { type = 10300 id = 99 } name = "Dai 10 Kuchiku Sentai" type = destroyer model = 0 }
		division = { experience = 85 id = { type = 10300 id = 581 } name = "Dai 3 Yuso Sentai" type = transport }

		}


	navalunit = {
	id = { type = 10300 id = 1016 }
	name = "Dai 5 Kantai 21 Sentai"
	location = 1337
	base = 1337


		division = { experience = 85 id = { type = 10300 id = 51 }
		name = "IJN Tama"
		type = light_cruiser
		model = 1
		#maxspeed = 36
		}

		division = { experience = 85 id = { type = 10300 id = 54 }
		name = "IJN Kiso"
		type = light_cruiser
		model = 1
		#maxspeed = 36
		}
		}

	navalunit = {
	id = { type = 10300 id = 1022 }
	name = "Nanpô Kantai" # Southern Fleet
	location = 1337
	base = 1337

		division = { experience = 85 id = { type = 10300 id = 143 } name = "Dai 35 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 144 } name = "Dai 36 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 145 } name = "Dai 37 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 146 } name = "Dai 38 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 147 } name = "Dai 39 Kuchiku Sentai" type = destroyer model = 1 }
		division = { experience = 85 id = { type = 10300 id = 361 } name = "Dai 7 Yuso Sentai" type = transport }
		division = { experience = 85 id = { type = 10300 id = 362 } name = "Dai 8 Yuso Sentai" type = transport }
		division = { experience = 85 id = { type = 10300 id = 363 } name = "Dai 9 Yuso Sentai" type = transport }
		division = { experience = 85 id = { type = 10300 id = 157 } name = "Dai 47 Kuchiku Sentai" type = destroyer model = 2 }
		division = { experience = 85 id = { type = 10300 id = 158 } name = "Dai 48 Kuchiku Sentai" type = destroyer model = 2 }
		}


	navalunit = {
	id = { type = 10300 id = 1065 }
	name = "Shien Kantai" # Reserve fleet
	location = 1187
	base = 1187
		division = { experience = 85 id = { type = 10300 id = 159 } name = "Dai 49 Kuchikukantai" type = destroyer model = 2 }
		division = { experience = 85 id = { type = 10300 id = 160 } name = "Dai 50 Kuchikukantai" type = destroyer model = 2 }
		division = { experience = 85 id = { type = 10300 id = 161 } name = "Dai 51 Kuchikukantai" type = destroyer model = 2 }

		division = { experience = 85 id = { type = 10300 id = 285 } name = "Dai 9 Sensui Sentai" type = submarine model = 1 }
		division = { experience = 85 id = { type = 10300 id = 286 } name = "Dai 13 Sensui Sentai" type = submarine model = 1 }
		division = { experience = 85 id = { type = 10300 id = 288 } name = "Dai 26 Sensui Sentai" type = submarine model = 1 }
		division = { experience = 85 id = { type = 10300 id = 289 } name = "Dai 27 Sensui Sentai" type = submarine model = 2 }
		division = { experience = 85 id = { type = 10300 id = 290 } name = "Dai 33 Sensui Sentai" type = submarine model = 1 }
		division = { experience = 85 id = { type = 10300 id = 300 } name = "Dai 11 Sensui Sentai" type = submarine model = 1 }
		division = { experience = 85 id = { type = 10300 id = 301 } name = "Dai 12 Sensui Sentai" type = submarine model = 2 }
		}

	navalunit = {
	id = { type = 10300 id = 1066 }
	name = "Dai 8 Kantai 3 Sentai"
	location = 1321
	base = 1321
		division = { experience = 85 id = { type = 10300 id = 364 } name = "Dai 10 Yuso Sentai" type = transport }
		division = { experience = 85 id = { type = 10300 id = 156 } name = "Dai 46 Kuchiku Sentai" type = destroyer model = 2 }
	       }

	navalunit = {
	id = { type = 10300 id = 1067 }
	name = "Dai 2 Sendan"
	location = 1627
	base = 1627
		division = { experience = 85 id = { type = 10300 id = 1068 } name = "Dai 2 Yuso Sentai" type = transport }
	       }

	navalunit = {
	id = { type = 10300 id = 1069 }
	name = "Dai 3 Sendan"
	location = 1621
	base = 1621
		division = { experience = 85 id = { type = 10300 id = 1070 } name = "Dai 6 Yuso Sentai" type = transport }
		division = { experience = 85 id = { type = 10300 id = 1071 } name = "Dai 14 Yuso Sentai" type = transport }
	       }
	navalunit = {
	id = { type = 10300 id = 1072 }
	name = "Dai 5 Sendan"
	location = 1613
	base = 1613
		division = { experience = 85 id = { type = 10300 id = 1073 } name = "Dai 5 Yuso Sentai" type = transport }
	       }

	landunit = {
	id = { type = 10300 id = 505 }
	name = "Dai 15 gun"
	location = 1337

		division = { experience = 85
		id = { type = 10300 id = 506 }
		name = "Dai 55 Hoheishidan"
		strength = 100
		type = infantry
		extra = anti_air
		model = 1
		}
	}


	landunit = {
	id = { type = 10300 id = 541 }
	name = "Dai 14 gun"
	location = 1322

		division = { experience = 85
		id = { type = 10300 id = 543 }
		name = "Dai 48 Hoheishidan"
		strength = 100
		type = infantry
		model = 2
		extra = artillery brigade_model = 4
		}
		}

	landunit = {
	id = { type = 10300 id = 544 }
	name = "Dai 65 Dokuritsu Ryodan"
	location = 1322

		division = { experience = 85
		id = { type = 10300 id = 545 }
		name = "Dai 65 Dokuritsu Ryodan"
		strength = 55
		max_strength = 55
		type = infantry
		model = 2
		}
		}


	landunit = {
	id = { type = 10300 id = 546 }
	name = "Tanaka Rentai"
	location = 1322

		division = { experience = 85
		id = { type = 10300 id = 547 }
		name = "Tanaka Rentai"
		strength = 35
		max_strength = 35
		type = infantry
		model = 2
		}
		}

	landunit = {
	id = { type = 10300 id = 548 }
	name = "Kanno Rentai"
	location = 1322

		division = { experience = 85
		id = { type = 10300 id = 549 }
		name = "Kanno Rentai"
		strength = 35
		max_strength = 35
		type = infantry
		model = 2
		}
		}
	landunit = {
	id = { type = 10300 id = 550 }
	name = "K Ryodan"
	location = 1187

		division = { experience = 85
		id = { type = 10300 id = 551 }
		name = "K Ryodan"
		strength = 55
		max_strength = 55
		type = cavalry
		model = 1
		}
		}


	landunit = {
	id = { type = 10300 id = 552 }
	name = "Nankai shitai" # South Seas Detachement
	location = 1627

		division = { experience = 85
		id = { type = 10300 id = 553 }
		name = "Nankai shitai"
		strength = 55
		max_strength = 55
		type = infantry
		model = 2
		}
		}

	landunit = {
	id = { type = 10300 id = 554 }
	name = "Kimura Shitai" # Kimura Detachment
	location = 1621

		division = { experience = 85
		id = { type = 10300 id = 555 }
		name = "Dai 33 Rentai"
		strength = 35
		max_strength = 35
		type = infantry
		model = 2
		}
		}

	landunit = {
	id = { type = 10300 id = 556 }
	name = "Sakaguchi Rentai"
	location = 1621

		division = { experience = 85
		id = { type = 10300 id = 557 }
		name = "Sakaguchi Rentai"
		strength = 35
		max_strength = 35
		type = infantry
		model = 2
		}
		}


	landunit = {
	id = { type = 10300 id = 572 }
	name = "Dai 1 Teishinshudan"
	location = 1337

		division = { experience = 85
		id = { type = 10300 id = 573 }
		name = "Dai 1 Teishinshudan"
		strength = 45
		max_strength = 45
		type = paratrooper
		model = 1
		}
		}

	landunit = {
	id = { type = 10300 id = 574 }
	name = "Sasebo Rikusentai"
	location = 1190

		division = { experience = 85
		id = { type = 10300 id = 575 }
		name = "Sasebo Rikusentai"
		type = marine
		model = 1
		strength = 55
		max_strength = 55
		}
		}

	landunit = {
	id = { type = 10300 id = 576 }
	name = "Maizaru Rikusentai"
	location = 1322

		division = { experience = 85
		id = { type = 10300 id = 577 }
		name = "Maizaru Rikusentai"
		strength = 55
		max_strength = 55
		type = marine
		model = 1
		}
		}

	landunit = {
	id = { type = 10300 id = 578 }
	name = "Yokohama Rikusentai"
	location = 1337

		division = { experience = 85
		id = { type = 10300 id = 579 }
		name = "Yokohama Rikusentai"
		type = marine
		strength = 55
		max_strength = 55
		model = 1
		}
		}


	landunit = {
	id = { type = 10300 id = 598 }
	name = "Dai 29 gun"
	location = 1187

		division = { experience = 85
		id = { type = 10300 id = 599 }
		name = "Dai 37 Hoheishidan"
		strength = 100
		type = infantry
		model = 1
		}
	}



		landunit = {
		id = { type = 10300 id = 611 }
		name = "Naha keibitai"
		location = 1193

			division = { experience = 85
			id = { type = 10300 id = 612 }
			name = "Naha keibitai"
			strength = 100
			type = garrison
			}
			}



		landunit = {
		id = { type = 10300 id = 621 }
		name = "Palau keibitai"
		location = 1621

			division = { experience = 85
			id = { type = 10300 id = 622 }
			name = "Palau keibitai"
			strength = 100
			type = garrison
			}
			}


		landunit = {
		id = { type = 10300 id = 629 }
		name = "Uruppu keibitai"
		location = 1627

			division = { experience = 85
			id = { type = 10300 id = 630 }
			name = "Uruppu keibitai"
			strength = 100
			type = garrison
			}
			}

		landunit = {
		id = { type = 10300 id = 631 }
		name = "Shumushushima keibitai"
		location = 1599

			division = { experience = 85
			id = { type = 10300 id = 632 }
			name = "Shumushushima keibitai"
			strength = 100
			type = garrison
			}
			}


		landunit = {
		id = { type = 10300 id = 637 }
		name = "Caroline keibitai"
		location = 1615

			division = { experience = 85
			id = { type = 10300 id = 638 }
			name = "Caroline keibitai"
			strength = 100
			type = garrison
			}
			}

		landunit = {
		id = { type = 10300 id = 639 }
		name = "Truk keibitai"
		location = 1613

			division = { experience = 85
			id = { type = 10300 id = 640 }
			name = "Truk keibitai"
			strength = 100
			type = garrison
			}
			}

		landunit = {
		id = { type = 10300 id = 641 }
		name = "Palikir keibitai"
		location = 1619

			division = { experience = 85
			id = { type = 10300 id = 642 }
			name = "Palikir keibitai"
			strength = 100
			type = garrison
			}
			}


airunit = {
		id = { type = 10300 id = 312 }
		name = "Genzan Kaigun Kokutai" # Genzan Naval Air Group
		location = 1337 #Saigon
		base = 1337 #Saigon
		division = { experience = 90 id = { type = 10300 id = 313 } name = "Genzan Kaigunkogeki Hikôdan" strength = 100 type = naval_bomber model = 1 experience = 20 }
		}

	airunit = {
		id = { type = 10300 id = 314 }
		name = "Kanoya Kaigun Kokutai"
		location = 1337 #Saigon
		base = 1337 #Saigon
		division = { experience = 90 id = { type = 10300 id = 315 } name = "Kanoya Sento Hikô Sentai" strength = 100 type = multi_role model = 1 experience = 20 }
		}

	airunit = {
		id = { type = 10300 id = 316 }
		name = "Dai 1 Kaigun Kokutai"
		location = 1322 #Kaohsiung
		base = 1322 #Kaohsiung
		division = { experience = 90 id = { type = 10300 id = 317 } name = "Dai 1 Kaigunkogeki Hikôdan" strength = 100 type = naval_bomber model = 0 experience = 20 }
		}

	airunit = {
		id = { type = 10300 id = 318 }
		name = "Tainan Kaigun Kokutai"
		location = 1322 #Kaohsiung
		base = 1322 #Kaohsiung
		division = { experience = 90 id = { type = 10300 id = 319 } name = "Tainan Sento Hikô Sentai" strength = 100 type = multi_role model = 1 experience = 20 }
		}

	airunit = {
		id = { type = 10300 id = 320 }
		name = "Takao Kaigun Kokutai"
		location = 1322 #Kaohsiung
		base = 1322 #Kaohsiung
		division = { experience = 90 id = { type = 10300 id = 321 } name = "Takao Kaigunkogeki Hikôdan" strength = 100 type = naval_bomber model = 1 experience = 20 }
		}

	airunit = {
		id = { type = 10300 id = 322 }
		name = "Dai 3 Gun Hikôdan" # 3rd Army Air Force Brigade
		location = 1337 #Saigon
		base = 1337 #Saigon
		division = { experience = 90 id = { type = 10300 id = 323 } name = "Dai 3 RikuGun Hikôdan" strength = 100 type = tactical_bomber model = 1 }
		}

	airunit = {
		id = { type = 10300 id = 324 }
		name = "Dai 7 Gun Hikôdan"
		location = 1340 #Phnom Penh
		base = 1340 #Phnom Penh
		division = { experience = 90 id = { type = 10300 id = 325 } name = "Dai 7 RikuGun Hikôdan" strength = 100 type = tactical_bomber model = 0 }
		}

	airunit = {
		id = { type = 10300 id = 326 }
		name = "Dai 10 Gun Hikôdan"
		location = 1340 #Phnom Penh
		base = 1340 #Phnom Penh
		division = { experience = 90 id = { type = 10300 id = 327 } name = "Dai 10 Kyokutsi Hikôdan" strength = 100 type = interceptor model = 1 }
		}

	airunit = {
		id = { type = 10300 id = 328 }
		name = "Dai 12 Gun Hikôdan"
		location = 1337 #Saigon
		base = 1337 #Saigon
		division = { experience = 90 id = { type = 10300 id = 329 } name = "Dai 12 Kyokutsi Hikôdan" strength = 100 type = interceptor model = 1 }
		}

	airunit = {
		id = { type = 10300 id = 330 }
		name = "Dai 4 Gun Hikôdan"
		location = 1322 #Kaohsiung
		base = 1322 #Kaohsiung
		division = { experience = 90 id = { type = 10300 id = 331 } name = "Dai 4 RikiGun Hikôdan" strength = 100 type = tactical_bomber model = 1 }
		}

	airunit = {
		id = { type = 10300 id = 332 }
		name = "Oita Kaigun Kokutai"
		location = 1190 #Fukuoka
		base = 1190 #Fukuoka
		division = { experience = 90 id = { type = 10300 id = 333 } name = "Oita Sento Hikôdan" strength = 100 type = multi_role model = 0 }
		}

	airunit = {
		id = { type = 10300 id = 334 }
		name = "Usa Kaigun Kokutai"
		location = 1190 #Fukuoka
		base = 1190 #Fukuoka
		division = { experience = 90 id = { type = 10300 id = 335 } name = "Usa Kaigunkogeki Hikôdan" strength = 100 type = naval_bomber model = 0 }
		}


		airunit = {
		id = { type = 10300 id = 336 }
		name = "Dai 12 Yuso Hikodan"
		location = 1337
		base = 1337


			division = { experience = 85
			id = { type = 10300 id = 337 }
			name = "12 Yuso Hikodan"
			strength = 100
			type = transport_plane
			}
			}



navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 582 } name = "IJN Kirishima" type = battlecruiser model = 0 } ##PH
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 583 } name = "IJN Hiei" type = battlecruiser model = 0 } ##PH
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 584 } name = "IJN Tone" type = heavy_cruiser model = 3 airattack = 14 } ##PH
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 585 } name = "IJN Chikuma"  type = heavy_cruiser model = 3 airattack = 14 } ##PH
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 401 } name = "IJN Kaga" type = carrier model = 1  extra = cag brigade_model = 2 }
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 402 } name = "IJN Akagi" type = carrier model = 1  extra = cag brigade_model = 2 }
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 403 } name = "IJN Soryu" type = carrier model = 2 extra = cag brigade_model = 2 }
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 404 } name = "IJN Hiryu" type = carrier model = 2 extra = cag brigade_model = 2 }
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 405 } name = "IJN Shokaku" type = carrier model = 3  extra = cag brigade_model = 2 }
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 406 } name = "IJN Zuikaku" type = carrier model = 3  extra = cag brigade_model = 2 }
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 133 } name = "Dai 32 Kuchiku Sentai" type = destroyer model = 1 }
navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 134 } name = "Dai 33 Kuchiku Sentai" type = destroyer model = 1 }


navaldivision = { experience = 85 dormant = yes id = { type = 10300 id = 1001 } name = "IJN Yamato" type = battleship model = 6 }

landdivision = { experience = 85 dormant = yes id = { type = 10300 id = 601 } name = "Dai 58 Hoheishidan" strength = 100 type = infantry model = 2 }
landdivision = { experience = 85 dormant = yes id = { type = 10300 id = 600 } name = "Dai 59 Hoheishidan" strength = 100 type = infantry model = 2 }


landdivision = { experience = 85 dormant = yes
		id = { type = 10300 id = 602 }
		name = "Dai 35 dokuritsu Ryodan"
		strength = 55
		max_strength = 55
		type = infantry
		model = 2
		}


landdivision = { experience = 85 dormant = yes
		id = { type = 10300 id = 603 }
		name = "Dai 17 dokuritsu Ryodan"
		strength = 55
		max_strength = 55
		type = infantry
		model = 2
		}

}



