
##############################
# Country definition for ENG #
##############################

province =
{ id            = 5
  radar_station = { size = 1 current_size = 1 }
  anti_air      = 4
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Scapa Flow
province =
{ id            = 6
  radar_station = { size = 1 current_size = 1 }
}                 # Inverness
province =
{ id            = 7
  naval_base    = { size = 5 current_size = 5 }
  radar_station = { size = 1 current_size = 1 }
}                 # Aberdeen
province =
{ id            = 8
  naval_base    = { size = 7 current_size = 7 }
  air_base      = { size = 8 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
}                 # Dunfermline
province =
{ id            = 12
  ic            = 6
  radar_station = { size = 2 current_size = 2 }
}                 # Blackpool
province =
{ id            = 13
  ic            = 14
  radar_station = { size = 2 current_size = 2 }
  anti_air      = 2
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Sheffield
province =
{ id            = 14
  ic            = 16
  anti_air      = 8
  radar_station = { size = 2 current_size = 2 }
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Liverpool
province =
{ id            = 15
  radar_station = { size = 1 current_size = 1 }
}                 # Cardiff
province =
{ id            = 17
  anti_air      = 8
  radar_station = { size = 3 current_size = 3 }
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Norwich
province =
{ id       = 19
  air_base = { size = 5 current_size = 5 }
}            # London
province =
{ id            = 20
  coastalfort   = 9
  anti_air      = 9
  radar_station = { size = 4 current_size = 4 }
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Dover
province =
{ id            = 21
  anti_air      = 10
  radar_station = { size = 4 current_size = 4 }
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Portsmouth
province =
{ id            = 22
  radar_station = { size = 1 current_size = 1 }
}                 # Bristol
province =
{ id            = 23
  anti_air      = 10
  radar_station = { size = 3 current_size = 3 }
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Plymouth
province =
{ id         = 28
  naval_base = { size = 5 current_size = 5 }
  air_base   = 2
}              # Belfast
province =
{ id    = 66
  infra = { size = 1 current_size = 0.75 }
}         # Aachen
province =
{ id       = 67
  air_base = { size = 10 current_size = 8 }
  infra    = { size = 1 current_size = 0.75 }
  ic       = { size = 3 current_size = 0 }
}            # Essen
province =
{ id    = 76
  infra = { size = 1 current_size = 0.7 }
  ic    = { size = 4 current_size = 0 }
}         # Dortmund
province =
{ id         = 80
  air_base   = { size = 10 current_size = 8 }
  infra      = { size = 1 current_size = 0.7 }
  supplypool = 5000
  oilpool    = 500
  ic         = { size = 2 current_size = 0 }
}              # Wilhelmshafen
province =
{ id    = 81
  infra = { size = 1 current_size = 0.75 }
  ic    = { size = 4 current_size = 0 }
}         # Münster
province =
{ id    = 86
  infra = { size = 1 current_size = 0.75 }
  ic    = { size = 3 current_size = 0 }
}         # Hannover
province =
{ id    = 88
  infra = { size = 1 current_size = 0.7 }
  ic    = { size = 2 current_size = 0 }
}         # Hamburg
province =
{ id         = 89
  naval_base = { size = 10 current_size = 8 }
  air_base   = { size = 10 current_size = 8 }
  infra      = { size = 1 current_size = 0.7 }
}              # Lübeck
province =
{ id    = 90
  infra = { size = 1 current_size = 0.8 }
  ic    = { size = 2 current_size = 0 }
}         # Kiel
province =
{ id            = 348
  supplypool    = 500
  oilpool       = 200
  landfort      = 10
  anti_air      = 10
  radar_station = { size = 2 current_size = 2 }
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Gibraltar
province =
{ id         = 399
  oilpool    = 100
  supplypool = 500
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Rhodes
province =
{ id         = 404
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Haifa
province =
{ id         = 406
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Eilat
province =
{ id         = 444
  naval_base = { size = 4 current_size = 4 }
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
}              # Cyprus
province =
{ id    = 460
  infra = { size = 1 current_size = 0.75 }
  ic    = { size = 2 current_size = 0 }
}         # Graz
province =
{ id         = 461
  supplypool = 1000
  oilpool    = 100
  ic         = { size = 1 current_size = 0 }
  infra      = { size = 0.8 current_size = 0.6 }
}              # Klagenfurt
province =
{ id         = 538
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id            = 576
  naval_base    = { size = 4 current_size = 4 }
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 1 current_size = 1 }
}                 # Newfoundland
province =
{ id       = 652
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Andros
province =
{ id         = 668
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Long Island
province =
{ id         = 866
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
  oilpool    = 100
  supplypool = 200
}              # Falkland Islands
province =
{ id       = 873
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Georgetown
province = { id = 900 anti_air = 6 } # Suez
province =
{ id         = 901
  anti_air   = 6
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Port Said
province = { id = 903 anti_air = 6 } # Cairo
province =
{ id         = 906
  supplypool = 5000
  oilpool    = 2000
  anti_air   = 9
  air_base   = { size = 7 current_size = 7 }
  naval_base = { size = 10 current_size = 10 }
}              # Alexandria
province =
{ id         = 919
  anti_air   = 4
  landfort   = 6
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Tobruk
province =
{ id         = 923
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
}              # Barca
province =
{ id         = 924
  anti_air   = 2
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 4 current_size = 4 }
}              # Bengazi
province =
{ id         = 932
  anti_air   = 2
  oilpool    = 100
  supplypool = 500
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Tripoli
province =
{ id         = 933
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Zuara
province =
{ id         = 988
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 1000
  supplypool = 2000
}              # Freetown
province =
{ id       = 1002
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Accra
province =
{ id       = 1008
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Lagos
province =
{ id         = 1033
  anti_air   = 2
  oilpool    = 100
  supplypool = 500
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Massaua
province =
{ id         = 1038
  anti_air   = 4
  supplypool = 1000
  oilpool    = 1000
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # Assab
province =
{ id         = 1056
  oilpool    = 100
  supplypool = 500
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Mogadishu
province =
{ id       = 1061
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mombasa
province =
{ id       = 1066
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Khartoum
province =
{ id       = 1287
  air_base = { size = 5 current_size = 5 }
}            # Imphal
province =
{ id       = 1296
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mandalay
province =
{ id         = 1299
  anti_air   = 5
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Rangoon
province =
{ id          = 1315
  landfort    = 9
  anti_air    = 8
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  oilpool     = 100
  supplypool  = 500
}               # Hong Kong
province =
{ id          = 1353

  coastalfort = 9
  anti_air    = 10
  air_base    = { size = 8 current_size = 8 }
  naval_base  = { size = 10 current_size = 10 }
  oilpool     = 1000
  supplypool  = 5000
}               # Singapore
province =
{ id         = 1457
  ic         = 3
  anti_air   = 5
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # Calcutta
province = { id = 1459 oilpool = 100 supplypool = 500 } # Ranchi
province = { id = 1464 ic = 2 } # Surat
province = { id = 1465 ic = 4 } # Rajkot
province =
{ id         = 1466
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
}              # Ahmadabad
province =
{ id       = 1467
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Indore
province =
{ id       = 1469
  ic       = 19
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}            # Delhi
province = { id = 1478 ic = 5 } # Bikaner
province = { id = 1479 ic = 6 } # Jodhpur
province =
{ id         = 1494
  ic         = 2
  anti_air   = 1
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 8 current_size = 8 }
}              # Karachi
province =
{ id         = 1505
  ic         = 4
  supplypool = 5000
  oilpool    = 2000
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Bombay
province = { id = 1513 ic = 4 } # Mangalore
province =
{ id       = 1514
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cochin
province =
{ id            = 1516
  radar_station = { size = 2 current_size = 2 }
  anti_air      = 1
  air_base      = { size = 2 current_size = 2 }
  naval_base    = { size = 2 current_size = 2 }
}                 # Trincomalee
province =
{ id          = 1517
  coastalfort = 9
  anti_air    = 2
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  oilpool     = 1000
  supplypool  = 2000
}               # Colombo
province =
{ id       = 1644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Kuching
province =
{ id         = 1685
  supplypool = 2500
  oilpool    = 2000
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Guadalcanal
province =
{ id         = 1753
  supplypool = 500
  oilpool    = 200
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
}              # Vanua Levu

#####################
# Country main data #
#####################

country =
{ tag                    = ENG
  capital                = 19
  manpower               = 485
  # Resource Reserves
  energy                 = 5000
  metal                  = 5000
  rare_materials         = 2500
  oil                    = 500
  supplies               = 10000
  money                  = 500
  # #######################
  # ##CONVOYS##############
  # #######################
  transports             = 1600
  escorts                = 150
  dissent                = 4
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 8
    freedom           = 10
    free_market       = 8
    professional_army = 5
    defense_lobby     = 5
    interventionism   = 6
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 15 }
  # GREAT BRITAIN
  nationalprovinces      = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   1494
			     1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1877 1878 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460
			     1459 1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287
			     1288 1289 1290 1291 1898 1295 1296 1301 1302 1346 1299 1298 1297 1300 1292 1454
			   }
  # GREAT BRITAIN
  ownedprovinces         = { 10   1000 1001 1002 1007 1008 1009 1010 1011 1012 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
			     1029 1030 1031 1032 1033 1034 1035 1036 1038 1039 1040 1041 1055 1056 1058 1059 1060 1061 1062 1064 1065 1066 1067 1068
			     1069 1085 1099 11   1104 1105 1111 1112 1124 1125 1126 1128 1129 1132 1136 1139 1140 1141 1145 1147 1148 12   1284 1285
			     1286 1287 1288 1289 1290 1291 1292 1295 1296 1297 1298 1299 13   1300 1301 1302 1315 1346 1348 1349 1350 1351 1352 1353
			     14   1454 1456 1457 1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1474 1475 1476 1477 1478
			     1479 1480 1481 1482 1483 1494 15   1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 16
			     1611 1614 1622 1644 1647 1683 1684 1685 1686 17   1752 1753 1754 1755 1757 1758 1759 1760 1761 1763 1767 1768 1769 1770
			     1796 1797 1798 1799 1800 1801 1802 1803 1813 1814 1815 1816 1817 1822 1877 1878 1898 19   20   21   22   23   28   29
			     3    31   348  399  4    404  406  407  444  460  461  5    538  575  576  6    652  653  66   664  665  666  668  67
			     7    758  76   8    80   805  806  807  808  809  81   85   86   866  871  873  88   89   891  896  897  9    90   900
			     901  902  903  904  905  906  907  908  909  910  911  912  913  914  915  916  917  918  919  920  921  922  923  924
			     925  926  927  928  929  930  931  932  933  982  988  999
			   }
  # GREAT BRITAIN
  controlledprovinces    = { 10   1000 1001 1002 1007 1008 1009 1010 1011 1012 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
			     1029 1030 1031 1032 1033 1034 1035 1036 1038 1039 1040 1041 1055 1056 1058 1059 1060 1061 1062 1064 1065 1066 1067 1068
			     1069 1085 1099 11   1104 1105 1111 1112 1124 1125 1126 1128 1129 1132 1136 1139 1140 1141 1145 1147 1148 12   1284 1285
			     1286 1287 1288 1289 1290 1291 1292 1295 1296 1297 1298 1299 13   1300 1301 1302 1315 1346 1348 1349 1350 1351 1352 1353
			     14   1454 1456 1457 1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1474 1475 1476 1477 1478
			     1479 1480 1481 1482 1483 1494 15   1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 16
			     1611 1614 1622 1644 1647 1683 1684 1685 1686 17   1752 1753 1754 1755 1757 1758 1759 1760 1761 1763 1767 1768 1769 1770
			     1796 1797 1798 1799 1800 1801 1802 1803 1813 1814 1815 1816 1817 1822 1877 1878 1898 19   20   21   22   23   28   29
			     3    31   348  399  4    404  406  407  444  460  461  5    538  575  576  6    652  653  66   664  665  666  668  67
			     7    758  76   8    80   805  806  807  808  809  81   85   86   866  871  873  88   89   891  896  897  9    90   900
			     901  902  903  904  905  906  907  908  909  910  911  912  913  914  915  916  917  918  919  920  921  922  923  924
			     925  926  927  928  929  930  931  932  933  982  988  999
			   }
  # Commonwealth Tech '36
  # UK 1939 techs
  # ######################
  techapps               = { 1010  1020  1030  1040  1050  1070  1080  1090  1100  1110  1120  1130  1140  1150  1160  1170  1180  1190  1200  1210  12100 12110 12120
			     12130 1220  1230  1240  1250  1260  1270  1280  1310  1320  1330  1340  1350  1360  14000 14010 14020 14030 15000 15010 15500
			     2010  2020  2030  2040  2050  2060  2070  2080  2090  2100  2110  2120  2150  2160  2170  2180  2190  2220  2230  2240
			     2260  2270  2290  2300  2310  2320  2330  2340  2350  2360  2370  2380  2400  2410  2420  2430  2450  2460  2470  2480
			     2490  2510  2520  2530  3010  3020  3030  3040  3050  3070  3080  3090  3100  3110  3130  3140  3150  3160  3190  3200
			     3210  3220  3250  3260  3270  3280  3290  3320  3330  3340  3350  3360  3370  3400  3410  3420  3430  4010  4020  4030
			     4040  4050  4060  4070  4080  4090  4100  4110  4120  4130  4140  4150  4160  4170  4180  4190  4200  4210  4220  4230
			     4240  4250  4260  4270  4280  5010  5020  5030  5040  5050  5060  5070  5080  5090  5100  5110  5120  5130  5140  5150
			     5160  5180  5190  5200  5210  5220  5230  5310  5320  5330  5340  5350  5360  5370  5380  5390  5400  5410  5420  5430
			     5440  5450  5460  5470  5480  5490  5500  5510  5550  5560  5570  6010  6030  6110  6120  6130  6140  6170  6200  7010
			     7140  7150  8010  8020  8030  8040  8050  8070  8090  8100  8110  8120  8130  8140  8160  8190  8200  8240  8250  8310
			     8330  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130  9140  9150  9160  9170  9180  9190
			     9200  9210  9220  9230  9240  9250  9260  9270  9280  9290  9300  9320  9340  9350  9360  9370  9380  9390
			     9400  9420  9410  9430  9440  9450  9460
			   }
  inventions = { 8000 8001 8010 }
  diplomacy =
  { relation = { tag = AFG value = -75 }
    relation = { tag = ARG value = 75 }
    relation = { tag = AST value = 200 access = yes }
    relation = { tag = BEL value = 150 access = yes }
    relation = { tag = BHU value = 200 access = yes }
    relation = { tag = BUL value = 20 }
    relation = { tag = CAN value = 200 access = yes }
    relation =
    { tag        = DEN
      value      = 100
      guaranteed = { day = 19 month = april year = 1939 }
    }
    relation = { tag = FRA value = 150 access = yes }
    relation =
    { tag        = GRE
      value      = 50
      guaranteed = { day = 13 month = april year = 1939 }
    }
    relation =
    { tag        = HOL
      value      = 125
      guaranteed = { day = 19 month = april year = 1939 }
      access     = yes
    }
    relation = { tag = HUN value = -50 }
    relation = { tag = IRE value = 50 }
    relation = { tag = IRQ value = 100 access = yes }
    relation = { tag = ITA value = 100 access = yes }
    relation = { tag = MEX value = 50 }
    relation = { tag = NEP value = 200 access = yes }
    relation = { tag = NOR value = 90 }
    relation = { tag = NZL value = 200 access = yes }
    relation = { tag = OMN value = 150 access = yes }
    relation =
    { tag        = POL
      guaranteed = { day = 30 month = march year = 1939 }
    }
    relation =
    { tag        = POR
      value      = 100
      guaranteed = { day = 22 month = may year = 1939 }
    }
    relation =
    { tag        = ROM
      value      = 50
      guaranteed = { day = 13 month = april year = 1939 }
    }
    relation = { tag = SAF value = 200 access = yes }
    relation =
    { tag        = SAU
      value      = 100
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation =
    { tag        = SCH
      value      = 50
      guaranteed = { day = 19 month = april year = 1939 }
    }
    relation = { tag = SIA value = 70 }
    relation = { tag = SWE value = 80 }
    relation =
    { tag        = TUR
      value      = 75
      guaranteed = { day = 17 month = may year = 1938 }
    }
    relation = { tag = USA value = 150 }
    relation = { tag = VEN value = -10 }
    relation =
    { tag        = YEM
      value      = 150
      access     = yes
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = ICL value = 150 access = yes }
    relation = { tag = BRU access = yes value = 200 }
    relation = { tag = PER value = 100 access = yes }
  }
  headofstate            = { type = 9 id = 1033 }
  headofgovernment       = { type = 9 id = 1040 }
  foreignminister        = { type = 9 id = 1047 }
  armamentminister       = { type = 9 id = 1067 }
  ministerofsecurity     = { type = 9 id = 1089 }
  ministerofintelligence = { type = 9 id = 1106 }
  chiefofstaff           = { type = 9 id = 1123 }
  chiefofarmy            = { type = 9 id = 1133 }
  chiefofnavy            = { type = 9 id = 1139 }
  chiefofair             = { type = 9 id = 1148 }
  dormant_ministers      = { 1001 1002 1004 1006 1007 1008 1009 1010 1031 1042 1049 1052 1053 1054 1068 1073 1081 1082 1090 1107 1119 1124 1127 1128 1131 1134 1140 1143
			     1160 1162
			   }
  landunit =
  { id       = { type = 30251 id = 1 }
    name     = "I Corps"
    location = 88
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 1 }
      name          = "3rd Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 2 }
      name          = "49th (West Riding) Infantry Division"
      experience    = 80
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 3 }
      name          = "53rd (Welsh) Infantry Division"
      extra         = artillery
      brigade_model = 5
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 4 }
      name          = "52nd (Lowland) Infantry Division"
      extra         = anti_air
      brigade_model = 2
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 5 }
      name          = "Guards Infantry Division"
      extra         = light_armor_brigade
      brigade_model = 0
      experience    = 80
    }
    division =
    { type         = infantry
      model        = 5
      id           = { type = 30254 id = 6 }
      name         = "308th Infantry Brigade"
      experience   = 80
      strength     = 35
      max_strength = 35
    }
  }
  landunit =
  { id       = { type = 30251 id = 2 }
    name     = "VIII Corps"
    location = 85
    division =
    { type          = armor
      model         = 3
      id            = { type = 30254 id = 7 }
      name          = "7th Armoured Division"
      extra         = heavy_armor
      brigade_model = 0
      experience    = 90
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30254 id = 8 }
      name          = "11th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 90
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 9 }
      name          = "55th (West Lancashire) Infantry Division"
      experience    = 90
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type         = paratrooper
      model        = 0
      id           = { type = 30254 id = 10 }
      name         = "1st Parachute Brigade"
      strength     = 50
      max_strength = 50
      experience   = 90
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 11 }
      name          = "15th (Scottish) Infantry Division"
      experience    = 90
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30251 id = 3 }
    name     = "XXX Corps"
    location = 89
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 12 }
      name          = "43rd (Wessex) Infantry Division"
      experience    = 85
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 13 }
      name          = "5th Infantry Division"
      experience    = 85
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 14 }
      name          = "51st (Highland) Infantry Division"
      experience    = 85
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30254 id = 15 }
      name          = "Guards Armoured Division"
      extra         = heavy_armor
      brigade_model = 1
      experience    = 85
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 16 }
      name          = "305th Infantry Brigade"
      strength      = 35
      max_strength  = 35
      experience    = 85
      extra         = anti_air
      brigade_model = 2
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 17 }
      name          = "301st Infantry Division"
      strength      = 35
      max_strength  = 35
      experience    = 85
      extra         = tank_destroyer
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30251 id = 4 }
    name     = "Army of the Rhine HQ"
    location = 85
    division =
    { type          = hq
      model         = 2
      id            = { type = 30254 id = 18 }
      name          = "HQ Army of the Rhine"
      extra         = anti_air
      brigade_model = 1
      experience    = 90
    }
  }
  landunit =
  { id       = { type = 30251 id = 5 }
    name     = "8th Army HQ"
    location = 460
    division =
    { type       = hq
      model      = 2
      id         = { type = 30254 id = 19 }
      name       = "8th Army HQ"
      experience = 75
    }
  }
  landunit =
  { id       = { type = 30251 id = 6 }
    name     = "V Corps"
    location = 460
    division =
    { type          = armor
      model         = 3
      id            = { type = 30254 id = 20 }
      name          = "6th Armoured Division"
      experience    = 75
      extra         = heavy_armor
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 21 }
      name          = "56th (London) Infantry Division"
      extra         = light_armor_brigade
      brigade_model = 0
      experience    = 75
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 22 }
      name          = "78th Infantry Division"
      experience    = 75
      extra         = light_armor_brigade
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30251 id = 7 }
    name     = "II polish Corps"
    location = 86
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30254 id = 23 }
      name          = "1st polish Infantry Division"
      experience    = 75
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type         = armor
      model        = 3
      id           = { type = 30254 id = 24 }
      name         = "9th Armoured Brigade"
      strength     = 35
      max_strength = 35
      experience   = 75
    }
  }
  landunit =
  { id       = { type = 30251 id = 8 }
    name     = "X Corps"
    location = 461
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30254 id = 25 }
      name          = "10th Indian Infantry Division"
      experience    = 70
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30254 id = 26 }
      name          = "4th Indian Infantry Division"
      experience    = 70
      extra         = anti_tank
      brigade_model = 3
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30254 id = 27 }
      name          = "1st Infantry Division"
      experience    = 70
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type         = armor
      model        = 4
      id           = { type = 30254 id = 28 }
      name         = "7th Armoured Brigade"
      strength     = 40
      max_strength = 40
      experience   = 70
    }
  }
  landunit =
  { id       = { type = 30251 id = 9 }
    name     = "14th Army HQ"
    location = 1353
    division =
    { type          = hq
      model         = 1
      id            = { type = 30254 id = 29 }
      name          = "14th Army HQ"
      extra         = engineer
      brigade_model = 0
      experience    = 50
    }
  }
  landunit =
  { id       = { type = 30251 id = 10 }
    name     = "XV Corps"
    location = 1797
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 30 }
      name       = "82nd West African Infantry Division"
      experience = 50
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 31 }
      name       = "81st West African Infantry Division"
      experience = 50
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 32 }
      name       = "26th Indian Infantry Division"
      experience = 50
    }
    division =
    { type          = infantry
      model         = 5
      id            = { type = 30254 id = 33 }
      name          = "36th Infantry Division"
      experience    = 55
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30251 id = 11 }
    name     = "IV Corps"
    location = 906
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 34 }
      name       = "5th Indian Infantry Division"
      experience = 55
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 35 }
      name       = "17th Indian Infantry Division"
      experience = 55
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 36 }
      name       = "20th Indian Infantry Division"
      experience = 55
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30254 id = 37 }
      name          = "14th Indian Infantry Division"
      experience    = 50
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30251 id = 12 }
    name     = "XXXIII Corps"
    location = 1497
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 38 }
      name       = "19th Indian Infantry Division"
      experience = 45
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 39 }
      name       = "7th Indian Infantry Division"
      experience = 45
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30254 id = 40 }
      name       = "23rd Indian Infantry Division"
      experience = 45
    }
    division =
    { type          = infantry
      model         = 5
      id            = { type = 30254 id = 41 }
      name          = "2nd Infantry Division"
      experience    = 45
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { location = 348
    id       = { type = 30251 id = 13 }
    name     = "Gibraltar Command"
    division =
    { experience    = 30
      id            = { type = 30254 id = 42 }
      name          = "Gibraltar Defence Force"
      type          = infantry
      model         = 4
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
  }
  landunit =
  { location = 31
    id       = { type = 30251 id = 14 }
    name     = "Malta Command"
    division =
    { experience    = 30
      id            = { type = 30254 id = 43 }
      name          = "Malta Defence Force"
      type          = infantry
      model         = 4
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
  }
  landunit =
  { location = 444
    id       = { type = 30251 id = 15 }
    name     = "Cyprus Command"
    division =
    { experience = 30
      id         = { type = 30254 id = 44 }
      name       = "Cyprus Defence Force"
      type       = garrison
      model      = 1
      strength   = 100
    }
  }
  # ##################################################################################################
  # Active Fleets
  # ##################################################################################################
  # #################
  # Home Fleet#
  navalunit =
  { name     = "Home Fleet"
    id       = { type = 30252 id = 1 }
    location = 5 # Scapa Flow
    base     = 5 # Scapa Flow
    division =
    { experience    = 30
      id            = { type = 30255 id = 1 }
      name          = "HMS Argus"
      type          = escort_carrier
      model         = 0
    }
    division =
    { experience    = 30
      id            = { type = 30255 id = 2 }
      name          = "HMS Furious"
      type          = carrier
      extra         = cag
      model         = 1
      brigade_model = 4
    }
    division =
    { experience    = 30
      id            = { type = 30255 id = 3 }
      name          = "HMS Formidable"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience = 0
      id         = { type = 30255 id = 300 }
      name       = "Colossus"
      type       = escort_carrier
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30255 id = 301 }
      name       = "Vengeance"
      type       = escort_carrier
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30255 id = 302 }
      name       = "Venerable"
      type       = escort_carrier
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30255 id = 303 }
      name       = "Glory"
      type       = escort_carrier
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30255 id = 304 }
      name       = "Ocean"
      type       = escort_carrier
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 4 }
      name       = "HMS Duke of York"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 5 }
      name       = "HMS Berwick"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 6 }
      name       = "HMS Kent"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 7 }
      name       = "HMS Jamaica"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 8 }
      name       = "HMS Sheffield"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 9 }
      name       = "HMS Devonshire"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 10 }
      name       = "1st Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 11 }
      name       = "2nd Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 12 }
      name       = "3rd Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 13 }
      name       = "4th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 14 }
      name       = "5th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
  }
  # #################
  # Reserve Fleet - Clyde#
  navalunit =
  { name     = "Reserve Fleet"
    id       = { type = 30252 id = 2 }
    location = 28 # Glasgow
    base     = 28
    division =
    { experience    = 30
      id            = { type = 30255 id = 15 }
      name          = "HMS Unicorn"
      type          = carrier
      extra         = cag
      model         = 1
      brigade_model = 4
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 16 }
      name       = "HMS Anson"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 17 }
      name       = "HMS Howe"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 18 }
      name       = "HMS King George V"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 19 }
      name       = "HMS Resolution"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 20 }
      name       = "HMS Revenge"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 21 }
      name       = "HMS Royal Sovereign"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 22 }
      name       = "HMS Effingham"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 23 }
      name       = "HMS Norfolk"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 24 }
      name       = "HMS Cardiff"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 25 }
      name       = "HMS Capetown"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 26 }
      name       = "HMS Dauntless"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 27 }
      name       = "HMS Carlisle"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 28 }
      name       = "HMS Diomede"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 29 }
      name       = "HMS Liverpool"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 30 }
      name       = "HMS Bermuda"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 31 }
      name       = "HMS Birmingham"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 32 }
      name       = "HMS Newfoundland"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 33 }
      name       = "HMS Uganda"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 34 }
      name       = "HMS Cleopatra"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 35 }
      name       = "HMS Euryalus"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 36 }
      name       = "HMS Leander"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 37 }
      name       = "HMS Bellona"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 38 }
      name       = "6th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 39 }
      name       = "7th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ######################
  # Mediterrean Fleet#
  navalunit =
  { name     = "Mediterranean Fleet"
    id       = { type = 30252 id = 3 }
    location = 444 # Alexandria
    base     = 444
    division =
    { experience = 30
      id         = { type = 30255 id = 40 }
      name       = "HMS Dido"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 41 }
      name       = "HMS Phoebe"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 42 }
      name       = "HMS Royalist"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 43 }
      name       = "8th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 44 }
      name       = "9th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 45 }
      name       = "10th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 46 }
      name       = "11th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 47 }
      name       = "12th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 48 }
      name       = "13th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 49 }
      name       = "14th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ###########################
  navalunit =
  { name     = "Force A"
    id       = { type = 30252 id = 4 }
    location = 21 # Southampton
    base     = 21
    division =
    { experience = 30
      id         = { type = 30255 id = 50 }
      name       = "HMS Warspite"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 51 }
      name       = "HMS Ramillies"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 52 }
      name       = "HMS Malaya"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 53 }
      name       = "HMS Rodney"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 54 }
      name       = "HMS Nelson"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 55 }
      name       = "HMS Danae"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 56 }
      name       = "HMS Hawkins"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 57 }
      name       = "HMS Frobisher"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 58 }
      name       = "HMS Arethusa"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 59 }
      name       = "HMS Emerald"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 60 }
      name       = "HMS Enterprise"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 61 }
      name       = "HMS Despatch"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 62 }
      name       = "HMS Dragon"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 63 }
      name       = "HMS Ajax"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 64 }
      name       = "HMS Orion"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 65 }
      name       = "HMS Glasgow"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 66 }
      name       = "HMS Belfast"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 67 }
      name       = "HMS Scylla"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 68 }
      name       = "HMS Sirius"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 69 }
      name       = "HMS Mauritius"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 70 }
      name       = "HMS Ceres"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 71 }
      name       = "HMS Argonaut"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 72 }
      name       = "HMS Black Prince"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 73 }
      name       = "HMS Diadem"
      type       = light_cruiser
      model      = 2
    }
  }
  navalunit =
  { name     = "Force B"
    id       = { type = 30252 id = 5 }
    location = 906 # Southampton
    base     = 906
    division =
    { experience    = 30
      id            = { type = 30255 id = 74 }
      name          = "HMS Implacable"
      type          = carrier
      extra         = cag
      model         = 4
      brigade_model = 5
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 75 }
      name       = "HMS Swiftsure"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 76 }
      name       = "34th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 77 }
      name       = "35th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 78 }
      name       = "36th Destroyer Flotilla"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 79 }
      name       = "21st Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 80 }
      name       = "HMS Colombo"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 81 }
      name       = "19th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 82 }
      name       = "20th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 83 }
      name       = "15th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 84 }
      name       = "16th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 85 }
      name       = "17th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 86 }
      name       = "18th Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 87 }
      name       = "22nd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 88 }
      name       = "23rd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 89 }
      name       = "24th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 90 }
      name       = "25th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 91 }
      name       = "26th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 92 }
      name       = "27th Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
  }
  # ##########################
  # East Indies Taskforce#
  navalunit =
  { name     = "East Indies Force"
    id       = { type = 30252 id = 6 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 30255 id = 93 }
      name       = "HMS Nigeria"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 94 }
      name       = "HMS Ceylon"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 95 }
      name       = "28th Destroyer Flotilla"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 96 }
      name       = "29th Destroyer Flotilla"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 97 }
      name       = "30th Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # #################
  # Eastern Fleet#
  navalunit =
  { name     = "Eastern Fleet"
    id       = { type = 30252 id = 7 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience    = 30
      id            = { type = 30255 id = 98 }
      name          = "HMS Victorious"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience    = 30
      id            = { type = 30255 id = 99 }
      name          = "HMS Indomitable"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 100 }
      name       = "HMS Queen Elizabeth"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 101 }
      name       = "HMS Renown"
      type       = battlecruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 102 }
      name       = "HMS Caradoc"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 103 }
      name       = "HMS Achilles"
      type       = light_cruiser
      model      = 2
    }
  }
  # ###########################
  # Gibraltar Taskforce#
  navalunit =
  { name     = "Force H"
    id       = { type = 30252 id = 8 }
    location = 348 # Gibraltar
    base     = 348
    division =
    { experience = 30
      id         = { type = 30255 id = 104 }
      name       = "HMS Delhi"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 105 }
      name       = "HMS Caledon"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 106 }
      name       = "HMS Aurora"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 107 }
      name       = "31st Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # ##########################
  # Indian Ocean Fleet#
  navalunit =
  { name     = "Indian Ocean Squadron"
    id       = { type = 30252 id = 9 }
    location = 2027 # North-east of Madagascar, en route to Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 30255 id = 108 }
      name       = "HMS Newcastle"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 109 }
      name       = "HMS Suffolk"
      type       = heavy_cruiser
      model      = 1
    }
  }
  # ##########################
  # Far East Fleet#
  navalunit =
  { name     = "Far East Fleet"
    id       = { type = 30252 id = 10 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience    = 30
      id            = { type = 30255 id = 110 }
      name          = "HMS Illustrious"
      type          = carrier
      extra         = cag
      model         = 3
      brigade_model = 4
    }
    division =
    { experience    = 30
      id            = { type = 30255 id = 111 }
      name          = "HMS Indefatigable"
      type          = carrier
      extra         = cag
      model         = 4
      brigade_model = 4
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 112 }
      name       = "HMS Valiant"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 113 }
      name       = "HMS Sussex"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 114 }
      name       = "HMS London"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 115 }
      name       = "HMS Shropshire"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 116 }
      name       = "HMS Gambia"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 117 }
      name       = "HMS Cumberland"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 118 }
      name       = "HMS Kenya"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 119 }
      name       = "32nd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 120 }
      name       = "33rd Destroyer Flotilla"
      type       = destroyer
      model      = 1
    }
  }
  # #########################
  # 1st Submarine Squadron#
  navalunit =
  { name     = "1st Submarine Squadron"
    id       = { type = 30252 id = 11 }
    location = 23 # Valetta
    base     = 23
    division =
    { experience = 30
      id         = { type = 30255 id = 121 }
      name       = "1st Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 122 }
      name       = "2nd Submarine Flotilla"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 123 }
      name       = "24st Submarine Flotilla"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 124 }
      name       = "25th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 3rd Submarine Squadron - Holy Loch#
  navalunit =
  { name     = "3rd Submarine Squadron"
    id       = { type = 30252 id = 12 }
    location = 28 # Glasgow
    base     = 28
    division =
    { experience = 30
      id         = { type = 30255 id = 125 }
      name       = "3rd Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 126 }
      name       = "4th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 127 }
      name       = "5th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 128 }
      name       = "6th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 129 }
      name       = "7th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 4th Submarine Squadron - Trincomalee#
  navalunit =
  { name     = "4th Submarine Squadron"
    id       = { type = 30252 id = 13 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 30255 id = 130 }
      name       = "8th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 131 }
      name       = "9th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 132 }
      name       = "10th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
  }
  # #########################
  # 5th Submarine Squadron#
  navalunit =
  { name     = "5th Submarine Squadron"
    id       = { type = 30252 id = 14 }
    location = 21 # Portsmouth
    base     = 21
    division =
    { experience = 30
      id         = { type = 30255 id = 133 }
      name       = "11th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 134 }
      name       = "12th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 135 }
      name       = "13th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 6th Submarine Squadron - Blyth#
  navalunit =
  { name     = "6th Submarine Squadron"
    id       = { type = 30252 id = 15 }
    location = 23 # Newcastle
    base     = 23
    division =
    { experience = 30
      id         = { type = 30255 id = 136 }
      name       = "14th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 7th Submarine Squadron - Rothesay#
  navalunit =
  { name     = "7th Submarine Squadron"
    id       = { type = 30252 id = 16 }
    location = 28 # Glasgow
    base     = 28
    division =
    { experience = 30
      id         = { type = 30255 id = 137 }
      name       = "15th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 138 }
      name       = "16th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 139 }
      name       = "17th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 140 }
      name       = "18th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
  }
  # #########################
  # 8th Submarine Squadron - Trincomalee#
  navalunit =
  { name     = "8th Submarine Squadron"
    id       = { type = 30252 id = 17 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { experience = 30
      id         = { type = 30255 id = 141 }
      name       = "19th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 142 }
      name       = "20th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
  }
  # #########################
  # 9th Submarine Squadron - Dundee#
  navalunit =
  { name     = "9th Submarine Squadron"
    id       = { type = 30252 id = 18 }
    location = 8 # Aberdeen
    base     = 8
    division =
    { experience = 30
      id         = { type = 30255 id = 143 }
      name       = "21th Submarine Flotilla"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 144 }
      name       = "22th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  # #########################
  # 10th Submarine Squadron - Maddalena#
  navalunit =
  { name     = "10th Submarine Squadron"
    id       = { type = 30252 id = 19 }
    location = 525 # Cagliari / Sardegna
    base     = 525
    division =
    { experience = 30
      id         = { type = 30255 id = 145 }
      name       = "23th Submarine Flotilla"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { name     = "1st Transport Squadron"
    id       = { type = 30252 id = 20 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { experience = 30
      id         = { type = 30255 id = 146 }
      name       = "Suffolk Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 147 }
      name       = "Trojan Star Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 148 }
      name       = "Queen Mary Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 149 }
      name       = "Nieuw Amsterdam Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 150 }
      name       = "Strathenden Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 151 }
      name       = "Fort Edmonton Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 152 }
      name       = "Lars Bay Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 153 }
      name       = "Fort Langley Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 154 }
      name       = "King Ethelred Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "2nd Transport Squadron"
    id       = { type = 30252 id = 21 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { experience = 30
      id         = { type = 30255 id = 155 }
      name       = "Dominion Monarch Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 156 }
      name       = "Empire Arquebus Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 157 }
      name       = "Hororata Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 158 }
      name       = "Henry the VIII Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 159 }
      name       = "The Bishops Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 160 }
      name       = "Empire of India Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 161 }
      name       = "Empire of Africa Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 162 }
      name       = "Royal Caledonian Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 163 }
      name       = "Royal Sovereign Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "3rd Transport Squadron"
    id       = { type = 30252 id = 22 }
    location = 21
    base     = 21
    division =
    { experience = 30
      id         = { type = 30255 id = 164 }
      name       = "Queen Elizabeth Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 165 }
      name       = "Empress of Canada Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 166 }
      name       = "Clan Macauley Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 167 }
      name       = "Samfleet Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 168 }
      name       = "Samfreedom Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 169 }
      name       = "Samfoyle Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 170 }
      name       = "Samconstant Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 171 }
      name       = "Samleyte Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 172 }
      name       = "Samfaithful Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "4th Transport Squadron"
    id       = { type = 30252 id = 23 }
    location = 444 # Scapa Flow
    base     = 444
    division =
    { experience = 30
      id         = { type = 30255 id = 173 }
      name       = "Empire Captain Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 174 }
      name       = "Andes Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 175 }
      name       = "Empire Charmain Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 176 }
      name       = "Samoresby Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 177 }
      name       = "1st Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 178 }
      name       = "2nd Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 179 }
      name       = "3rd Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 180 }
      name       = "4th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 181 }
      name       = "5th Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "5th Transport Squadron"
    id       = { type = 30252 id = 24 }
    location = 444 # Alexandria
    base     = 444
    division =
    { experience = 30
      id         = { type = 30255 id = 182 }
      name       = "Essex Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 183 }
      name       = "Maloja Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 184 }
      name       = "Empire Chieftain Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 185 }
      name       = "6th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 186 }
      name       = "7th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 187 }
      name       = "8th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 188 }
      name       = "9th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 189 }
      name       = "10th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 190 }
      name       = "11th Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "6th Transport Squadron"
    id       = { type = 30252 id = 25 }
    location = 1353 # Alexandria
    base     = 1353
    division =
    { experience = 30
      id         = { type = 30255 id = 191 }
      name       = "Stirling Castle Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 192 }
      name       = "Empire Splendour Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 193 }
      name       = "Sam Torch Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 194 }
      name       = "12th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 195 }
      name       = "13th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 196 }
      name       = "14th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 197 }
      name       = "15th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 198 }
      name       = "16th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 199 }
      name       = "17th Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  navalunit =
  { name     = "7th Transport Squadron"
    id       = { type = 30252 id = 26 }
    location = 1299 # Colombo
    base     = 1299
    division =
    { experience = 30
      id         = { type = 30255 id = 200 }
      name       = "Resolution Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 201 }
      name       = "Fort Dunvegan Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 202 }
      name       = "Durham Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 203 }
      name       = "18th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 204 }
      name       = "19th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 205 }
      name       = "20th Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 206 }
      name       = "21st Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 207 }
      name       = "22nd Transport Flotilla"
      type       = transport
      model      = 0
    }
    division =
    { experience = 30
      id         = { type = 30255 id = 208 }
      name       = "23rd Transport Flotilla"
      type       = transport
      model      = 0
    }
  }
  # ############################
  # ROYAL AIR FORCE 1944 OOB####
  # ############################
  airunit =
  { location = 370
    base     = 370
    id       = { type = 30253 id = 1 }
    name     = "10th Group"
    division =
    { experience = 40
      id         = { type = 30256 id = 1 }
      name       = "No.126 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 40
      id         = { type = 30256 id = 2 }
      name       = "No.165 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 3 }
      name       = "No.406 Squadron RCAF "
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 4 }
      name       = "No.464 Squadron RAAF "
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
  }
  airunit =
  { location = 80
    base     = 80
    id       = { type = 30253 id = 2 }
    name     = "11th Group"
    division =
    { experience = 40
      id         = { type = 30256 id = 5 }
      name       = "No.1 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 6 }
      name       = "No.501 Squadron "
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 45
      id         = { type = 30256 id = 7 }
      name       = "No.219 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
    division =
    { experience = 54
      id         = { type = 30256 id = 8 }
      name       = "No.29 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
  }
  airunit =
  { location = 46
    base     = 46
    id       = { type = 30253 id = 3 }
    name     = "2nd TAF/1"
    division =
    { experience = 50
      id         = { type = 30256 id = 9 }
      name       = "No.3 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 10 }
      name       = "No.33 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 40
      id         = { type = 30256 id = 11 }
      name       = "No.245 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 12 }
      name       = "No.694 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 30253 id = 4 }
    name     = "2nd TAF/2"
    division =
    { experience = 42
      id         = { type = 30256 id = 13 }
      name       = "No.65 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 42
      id         = { type = 30256 id = 14 }
      name       = "No.181 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 40
      id         = { type = 30256 id = 15 }
      name       = "No.401 Squadron RCAF "
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 16 }
      name       = "No.610 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 51
    base     = 51
    id       = { type = 30253 id = 5 }
    name     = "12th Group"
    division =
    { experience = 45
      id         = { type = 30256 id = 17 }
      name       = "No.168 Squadron"
      strength   = 75
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 18 }
      name       = "No.25 Squadron"
      strength   = 75
      type       = tactical_bomber
      model      = 4
    }
    division =
    { experience = 45
      id         = { type = 30256 id = 19 }
      name       = "No.264 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
    division =
    { experience = 55
      id         = { type = 30256 id = 20 }
      name       = "No.303 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 30253 id = 6 }
    name     = "13th Group"
    division =
    { experience = 30
      id         = { type = 30256 id = 21 }
      name       = "No.504 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 22 }
      name       = "No.412 Squadron RCAF "
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 10
      id         = { type = 30256 id = 23 }
      name       = "No.308 Squadron "
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 30253 id = 7 }
    name     = "14th Group"
    division =
    { experience = 30
      id         = { type = 30256 id = 24 }
      name       = "No.118 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 25 }
      name       = "No.441 Squadron RCAF "
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 10
      id         = { type = 30256 id = 26 }
      name       = "No.331 Squadron "
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 8
    base     = 8
    id       = { type = 30253 id = 8 }
    name     = "38th Group"
    division =
    { experience = 30
      id         = { type = 30256 id = 27 }
      name       = "No.190 Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 28 }
      name       = "No.297 Squadron "
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 29 }
      name       = "No.570 Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 67
    base     = 67
    id       = { type = 30253 id = 9 }
    name     = "No.603 Squadron"
    division =
    { experience = 50
      id         = { type = 30256 id = 30 }
      name       = "No.603 Squadron "
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 348
    base     = 348
    id       = { type = 30253 id = 10 }
    name     = "No.43 Squadron"
    division =
    { experience = 50
      id         = { type = 30256 id = 31 }
      name       = "No.43 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  # ## pac air OOB 1944 Author: valdemar
  airunit =
  { location = 1457
    base     = 1457
    id       = { type = 30253 id = 11 }
    name     = "1/SEAC Air Forces"
    division =
    { experience = 50
      id         = { type = 30256 id = 32 }
      name       = "17/.67./81. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 33 }
      name       = "136./155. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 34 }
      name       = "607./615. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 45
      id         = { type = 30256 id = 35 }
      name       = "28./30. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 404
    base     = 404
    id       = { type = 30253 id = 12 }
    name     = "2/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 30256 id = 36 }
      name       = "5./11./20. Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 40
      id         = { type = 30256 id = 37 }
      name       = "42./34./42. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 65
      id         = { type = 30256 id = 38 }
      name       = "60./79. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 39 }
      name       = "No.183 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 1287
    base     = 1287
    id       = { type = 30253 id = 13 }
    name     = "3/SEAC Air Forces"
    division =
    { experience    = 50
      id            = { type = 30256 id = 40 }
      name          = "200./203./215. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 70
      id            = { type = 30256 id = 41 }
      name          = "99./159. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 42 }
      name          = "292./355./356. Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 50
      id            = { type = 30256 id = 43 }
      name          = "No.429 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 1287
    base     = 1287
    id       = { type = 30253 id = 14 }
    name     = "4/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 30256 id = 44 }
      name       = "27./47./88. Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 45 }
      name       = "176./177./211. Squadron"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 906
    base     = 906
    id       = { type = 30253 id = 15 }
    name     = "5/SEAC Air Forces"
    division =
    { experience = 30
      id         = { type = 30256 id = 46 }
      name       = "31./62./117. Squadron"
      strength   = 100
      type       = transport_plane
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 47 }
      name       = "194./435./436. Squadron"
      strength   = 100
      type       = transport_plane
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 48 }
      name       = "45. Squadron"
      strength   = 40
      type       = tactical_bomber
      model      = 4
    }
    division =
    { experience = 40
      id         = { type = 30256 id = 49 }
      name       = "No.692 Squadron"
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
  }
  # ########################################
  # ##form. can. inc
  airunit =
  { location = 23
    base     = 23
    id       = { type = 30253 id = 16 }
    name     = "1st Group "
    division =
    { experience    = 60
      id            = { type = 30256 id = 50 }
      name          = "No.12 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 51 }
      name          = "No.103 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 52 }
      name          = "No.300 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 53 }
      name          = "No.576 Squadron "
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 14
    base     = 14
    id       = { type = 30253 id = 17 }
    name     = "3rd Group"
    division =
    { experience    = 30
      id            = { type = 30256 id = 54 }
      name          = "No.15 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 55 }
      name          = "No.115 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 56 }
      name          = "No.218 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 40
      id            = { type = 30256 id = 57 }
      name          = "No.106 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 30253 id = 18 }
    name     = "4th Group"
    division =
    { experience    = 60
      id            = { type = 30256 id = 58 }
      name          = "No.10 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 59 }
      name          = "No.76 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 60 }
      name          = "No.78 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 61 }
      name          = "No.640 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 13
    base     = 13
    id       = { type = 30253 id = 19 }
    name     = "5th Group"
    division =
    { experience    = 30
      id            = { type = 30256 id = 62 }
      name          = "No.9 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 63 }
      name          = "No.49 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 30
      id            = { type = 30256 id = 64 }
      name          = "No.467 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 50
      id            = { type = 30256 id = 65 }
      name          = "No.619 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 19
    base     = 19
    id       = { type = 30253 id = 20 }
    name     = "6th Group"
    division =
    { experience    = 30
      id            = { type = 30256 id = 66 }
      name          = "No.408 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 40
      id            = { type = 30256 id = 67 }
      name          = "No.424 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 50
      id            = { type = 30256 id = 68 }
      name          = "No.427 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 40
      id            = { type = 30256 id = 69 }
      name          = "No.432 Squadron RCAF"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 19
    base     = 19
    id       = { type = 30253 id = 21 }
    name     = "8th Group"
    division =
    { experience    = 60
      id            = { type = 30256 id = 70 }
      name          = "No.7 Squadron"
      strength      = 75
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 71 }
      name          = "No.156 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 72 }
      name          = "No.582 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 73 }
      name          = "No.346 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 30253 id = 22 }
    name     = "16th Group"
    location = 20
    base     = 20
    division =
    { experience = 50
      id         = { type = 30256 id = 74 }
      name       = "No.313 Squadron "
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 75 }
      name       = "No.64 Squadron"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 50
      id         = { type = 30256 id = 76 }
      name       = "No.332 Squadron "
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 77 }
      name       = "No.132 Squadron "
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { id       = { type = 30253 id = 23 }
    name     = "18th Group"
    location = 47
    base     = 47
    division =
    { experience = 40
      id         = { type = 30256 id = 78 }
      name       = "No.184 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 30
      id         = { type = 30256 id = 79 }
      name       = "No.80 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 40
      id         = { type = 30256 id = 80 }
      name       = "No.137 Squadron"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 45
      id         = { type = 30256 id = 81 }
      name       = "No.416 Squadron RCAF"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { id       = { type = 30253 id = 523 }
    name     = "Meteor Mk III "
    location = 19
    base     = 19
    division =
    { experience = 40
      id         = { type = 30256 id = 578 }
      name       = "Meteor Mk III  Squadron"
      strength   = 50
      type       = interceptor
      model      = 7
    }
  }
  airunit =
  { id       = { type = 30253 id = 24 }
    name     = "9th Group"
    location = 67
    base     = 67
    division =
    { experience = 55
      id         = { type = 30256 id = 82 }
      name       = "82./84./110. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 55
      id         = { type = 30256 id = 83 }
      name       = "258./261./273. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 45
      id         = { type = 30256 id = 84 }
      name       = "135./146./152. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 60
      id         = { type = 30256 id = 85 }
      name       = "113./123./134. Squadron"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { id       = { type = 30253 id = 25 }
    name     = "7th Group"
    location = 28
    base     = 28
    division =
    { experience    = 50
      id            = { type = 30256 id = 86 }
      name          = "No.61 Squadron"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 60
      id            = { type = 30256 id = 87 }
      name          = "No.625 Squadron "
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 1
    }
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = november year = 1945 }
    cost          = 6
    days          = 100
    id            = { type = 30254 id = 45 }
    name          = "303rd Infantry Division"
    extra         = artillery
    brigade_model = 6
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = november year = 1945 }
    cost          = 6
    days          = 100
    id            = { type = 30254 id = 46 }
    name          = "305th Infantry Division"
    extra         = artillery
    brigade_model = 6
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = november year = 1945 }
    cost          = 7
    days          = 100
    id            = { type = 30254 id = 47 }
    name          = "307th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = december year = 1945 }
    cost          = 7
    days          = 100
    id            = { type = 30254 id = 48 }
    name          = "401st Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = december year = 1945 }
    cost          = 5
    days          = 100
    id            = { type = 30254 id = 49 }
    name          = "402nd Infantry Division"
    extra         = anti_tank
    brigade_model = 3
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = december year = 1946 }
    cost          = 5
    days          = 100
    id            = { type = 30254 id = 50 }
    name          = "501st Infantry Division"
    extra         = anti_tank
    brigade_model = 3
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = january year = 1946 }
    cost          = 7
    days          = 100
    id            = { type = 30254 id = 51 }
    name          = "412th Infantry Division"
    extra         = tank_destroyer
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = january year = 1946 }
    cost          = 7
    days          = 100
    id            = { type = 30254 id = 52 }
    name          = "333rd Infantry Division"
    extra         = tank_destroyer
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = january year = 1946 }
    cost          = 5
    days          = 100
    id            = { type = 30254 id = 53 }
    name          = "313th Infantry Division"
    extra         = light_armor_brigade
    brigade_model = 0
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = february year = 1946 }
    cost          = 5
    days          = 100
    id            = { type = 30254 id = 54 }
    name          = "311th  nfantry Division"
    extra         = light_armor_brigade
    brigade_model = 0
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = february year = 1946 }
    cost          = 7
    days          = 100
    id            = { type = 30254 id = 55 }
    name          = "405th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = armor
    model         = 3
    date          = { day = 0 month = november year = 1945 }
    cost          = 10
    days          = 185
    id            = { type = 30254 id = 56 }
    name          = "17th Armored Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = armor
    model         = 3
    date          = { day = 0 month = december year = 1945 }
    cost          = 10
    days          = 185
    id            = { type = 30254 id = 57 }
    name          = "19th Armored Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = armor
    model         = 3
    date          = { day = 0 month = january year = 1946 }
    cost          = 10
    days          = 185
    id            = { type = 30254 id = 58 }
    name          = "21st Armored Division"
    extra         = heavy_armor
    brigade_model = 1
  }
  division_development =
  { type          = armor
    model         = 3
    date          = { day = 0 month = february year = 1946 }
    cost          = 10
    days          = 185
    id            = { type = 30254 id = 59 }
    name          = "31st Armored Division"
    extra         = heavy_armor
    brigade_model = 1
  }
  division_development =
  { type  = escort_carrier
    model = 3
    date  = { day = 9 month = february year = 1946 }
    cost  = 5
    days  = 185
    id    = { type = 30255 id = 400 }
    name  = "HMS Theseus"
  }
  division_development =
  { type  = escort_carrier
    model = 3
    date  = { day = 14 month = march year = 1946 }
    cost  = 5
    days  = 220
    id    = { type = 30255 id = 600 }
    name  = "HMS Warrior"
  }

  division_development =
  { type  = escort_carrier
    model = 3
    date  = { day = 9 month = may year = 1946 }
    cost  = 5
    days  = 255
    id    = { type = 30255 id = 601 }
    name  = "HMS Triumph"
  }
}
