
##############################
# Country definition for SOV #
##############################

province =
{ id         = 132
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
  infra      = { size = 0.4 current_size = 0.35 }
}              # Petsamo
province =
{ id         = 133
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 2
}              # Murmansk
province =
{ id       = 145
  landfort = 6
  anti_air = 7
  infra    = { size = 0.8 current_size = 0.6 }
}            # Viipuri
province = { id = 146 anti_air = 4 } # Sortavala
province =
{ id         = 154
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 3 current_size = 3 }
  anti_air   = 2
}              # Archangelsk
province = { id = 163 ic = 15 landfort = 5 anti_air = 3 air_base = 3 } # Stalingrad
province = { id = 175 ic = 15 landfort = 5 anti_air = 4 air_base = 5 } # Moscow
province = { id = 181 anti_air = 1 } # Kaluga
province = { id = 184 ic = 3 } # Tikhvin
province = { id = 185 ic = 3 } # Volkhov
province =
{ id          = 187
  ic          = 15
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  coastalfort = 5
  anti_air    = 4
}               # Leningrad
province =
{ id       = 191
  air_base = { size = 6 current_size = 6 }
  anti_air = 1
}            # Porkhov
province =
{ id         = 194
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
}              # Tallinn
province =
{ id         = 197
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
}              # Riga
province =
{ id       = 208
  anti_air = 1
  air_base = { size = 5 current_size = 5 }
}            # Wilno
province = { id = 211 anti_air = 3 } # Lida
province =
{ id       = 212
  air_base = { size = 10 current_size = 10 }
}            # Minsk
province = { id = 217 anti_air = 2 } # Vitebsk
province =
{ id       = 219
  air_base = { size = 10 current_size = 10 }
  anti_air = 3
}            # Smolensk
province =
{ id       = 233
  air_base = { size = 6 current_size = 6 }
  anti_air = 3
}            # Odessa
province =
{ id       = 238
  air_base = { size = 10 current_size = 10 }
  anti_air = 3
}            # Kiev
province = { id = 246 anti_air = 2 } # Zaporozhye
province = { id = 248 anti_air = 1 } # Kharkov
province =
{ id          = 253
  naval_base  = { size = 3 current_size = 3 }
  air_base    = { size = 3 current_size = 3 }
  landfort    = 3
  coastalfort = 5
  anti_air    = 3
}               # Sevastopol
province = { id = 258 anti_air = 2 } # Rostov
province = { id = 263 anti_air = 1 } # Svoboda
province =
{ id       = 273
  air_base = { size = 3 current_size = 3 }
}            # Gomel
province = { id = 277 anti_air = 2 } # Bryansk
province =
{ id       = 296
  infra    = { size = 1 current_size = 0.6 }
  air_base = { size = 4 current_size = 2 }
  ic       = { size = 1 current_size = 0 }
}            # Rostock
province =
{ id       = 298
  anti_air = 2
  infra    = { size = 1 current_size = 0.6 }
  ic       = { size = 2 current_size = 0 }
}            # Magdeburg
province =
{ id       = 300
  infra    = { size = 1 current_size = 0.4 }
  air_base = { size = 2 current_size = 1 }
  ic       = { size = 15 current_size = 0 }
}            # Berlin
province =
{ id    = 310
  infra = { size = 1 current_size = 0.65 }
  ic    = { size = 2 current_size = 0 }
}         # Leipzig
province =
{ id    = 311
  infra = { size = 1 current_size = 0.55 }
  ic    = { size = 8 current_size = 0 }
}         # Dresden
province =
{ id       = 435
  anti_air = 3
  infra    = { size = 0.8 current_size = 0.7 }
}            # Ismail
province =
{ id       = 463
  infra    = { size = 1 current_size = 0.65 }
  air_base = { size = 2 current_size = 1 }
  ic       = { size = 10 current_size = 0 }
}            # Vienna
province =
{ id    = 465
  infra = { size = 1 current_size = 0.55 }
  ic    = { size = 2 current_size = 0 }
}         # Linz
province =
{ id       = 501
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
  infra    = { size = 0.8 current_size = 0.75 }
  ic       = { size = 4 current_size = 2 }
}            # Lvov
province =
{ id       = 504
  landfort = 2
  infra    = { size = 0.6 current_size = 0.55 }
}            # Brest Litovsk
province =
{ id         = 510
  naval_base = { size = 7 current_size = 7 }
  anti_air   = 1
  air_base   = 4
  infra      = { size = 1 current_size = 0.65 }
  ic         = { size = 6 current_size = 0 }
}              # Königsberg
province = { id = 1150 anti_air = 2 ic = 12 } # Osa
province =
{ id         = 1175
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
  supplypool = 200
}              # Ocha
province =
{ id         = 1176
  air_base   = { size = 2 current_size = 1 }
  infra      = { size = 0.6 current_size = 0.55 }
  naval_base = { size = 10 current_size = 1 }
}              # Toyohara
province =
{ id         = 1177
  supplypool = 100
  oilpool    = 2000
  ic         = 0
  infra      = { size = 1 current_size = 0.8 }
  anti_air = 2
}              # Etorofu
province =
{ id       = 1201
  infra    = { size = 0.8 current_size = 0.6 }
  air_base = { size = 2 current_size = 1 }
  ic       = { size = 2 current_size = 0 }
}            # Pyongyang
province =
{ id         = 1202
  naval_base = { size = 4 current_size = 1 }
  infra      = { size = 0.6 current_size = 0.5 }
  air_base   = { size = 2 current_size = 1 }
}              # Dalian
province =
{ id    = 1371
  infra = { size = 0.4 current_size = 0.35 }
}         # Tetyukhe
province =
{ id          = 1372
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 5 current_size = 5 }
  landfort    = 1
  coastalfort = 3
  anti_air    = 3
}               # Vladivostok
province =
{ id    = 1379
  infra = { size = 0.6 current_size = 0.5 }
  ic    = { size = 6 current_size = 0 }
}         # Harbin
province =
{ id                 = 1389
  energy             = 0
  max_energy         = 0
  metal              = 0
  max_metal          = 0
  rare_materials     = 0
  max_rare_materials = 0
  ic                 = { size = 4 current_size = 0 }
}                      # Mukden
province =
{ id            = 1393
  anti_air      = 4
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 4 current_size = 4 }
  infra         = { size = 0.8 current_size = 0.75 }
}                 # Sinuiju
province = { id = 1570 anti_air = 2 } # Chkalov
province = { id = 1577 anti_air = 2 ic = 12 } # Orsk
province =
{ id    = 1587
  infra = { size = 0.6 current_size = 0.4 }
}         # Baikonur
province =
{ id          = 1834
  rocket_test = { size = 2 current_size = 2 }
}               # Krasnya Sloboda

#####################
# Country main data #
#####################

country =
{ tag                    = SOV
  belligerence           = 50
  regular_id             = RUS
  intrinsic_gov_type     = leninist
  capital                = 175
  # Resource Reserves
  energy                 = 50000
  metal                  = 50000
  rare_materials         = 5000
  oil                    = 15000
  supplies               = 15000
  manpower               = 1000
  dissent                = 0
  # ###########################
  # ## SOVIET NAVY OOB 1944 ###
  # ###########################
  transports             = 150
  escorts                = 50

  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 10
    freedom           = 1
    free_market       = 1
    professional_army = 4
    defense_lobby     = 10
    interventionism   = 10
  }
  SpyInfo                = { country = "SOV" NumberOfSpies = 15 }
  nationalprovinces      = { 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1170 1171 1172 1175 132
			     133  134  135  1366 1367 1368 1369 1370 1371 1372 1373 1383 1384 1405 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418
			     1422 1423 1424 1425 1426 1427 1428 1429 1430 1431 145  146  1485 1487 1488 1489 1490 1491 150  151  152  1520 1521 1522
			     1523 1524 1525 1526 1527 1528 1529 153  1531 1532 1533 1534 1535 1536 1537 1538 1539 154  1540 1541 1542 1543 1544 1545
			     1546 1547 1548 1549 155  1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 156  1560 1561 1562 1563 1564 1565 1566 1567
			     1568 1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 1589
			     159  1590 1591 1592 1593 1594 1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170  171  172  173  174
			     175  176  177  1771 1772 1773 1774 1775 1776 1777 1778 178  1780 1781 1782 1783 179  180  181  182  1827 1828 1829 183
			     1830 1831 1832 1833 1834 1835 1836 1837 1838 1839 184  1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 185  1850 1856
			     1857 1858 186  187  1874 188  189  190  1907 191  192  193  194  195  196  197  198  199  200  201  202  203  204  205
			     206  207  208  209  210  211  212  213  214  215  216  217  218  219  220  221  222  225  226  227  228  229  230
			     231  232  233  234  235  236  237  238  239  240  241  242  243  244  245  246  247  248  249  250  251  252  253  254
			     255  256  257  258  259  260  261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278
			     279  280  281  282  283  284  285  286  287  288  289  433  434  435  499  500  501  502  503  504  506  507  510  511
			     562  577  94
			   }
  ownedprovinces         = { 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1170 1171 1172 1174 1175
			     1176 1177 1200 1201 1202 132  133  134  135  1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378 1379 1380
			     1381 1382 1383 1384 1386 1387 1388 1389 1390 1391 1392 1393 1394 1395 1396 1405 1409 1410 1411 1412 1413 1414 1415 1416
			     1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 145  146  1485 1487 1488 1489 1490 1491 150  151  152  1520 1521 1522
			     1523 1524 1525 1526 1527 1528 1529 153  1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 154  1540 1541 1542 1543 1544
			     1545 1546 1547 1548 1549 155  1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 156  1560 1561 1562 1563 1564 1565 1566
			     1567 1568 1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588
			     1589 159  1590 1591 1592 1593 1594 1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170  171  172  173
			     174  175  176  177  1771 1772 1773 1774 1775 1776 1777 1778 178  1780 1781 1782 1783 179  180  181  182  1827 1828 1829
			     183  1830 1831 1832 1833 1834 1835 1836 1837 1838 1839 184  1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 185  1850
			     1856 1857 1858 186  187  1874 188  189  190  1907 191  192  193  194  195  196  197  198  199  200  201  202  203  204
			     205  206  207  208  209  210  211  212  213  214  215  216  217  218  219  220  221  222  225  226  227  228  229  230
			     231  232  233  234  235  236  237  238  239  240  241  242  243  244  245  246  247  248  249  250  251  252  253  254
			     255  256  257  258  259  260  261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278
			     279  280  281  282  283  284  285  286  287  288  289  295  296  297  298  299  300  301  309  310  311  433  434  435
			     463  464  465  499  500  501  502  503  504  506  507  510  511  562  577  94
			   }
  controlledprovinces    = { 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1170 1171 1172 1174 1175
			     1176 1177 1200 1201 1202 132  133  134  135  1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378 1379 1380
			     1381 1382 1383 1384 1386 1387 1388 1389 1390 1391 1392 1393 1394 1395 1396 1405 1409 1410 1411 1412 1413 1414 1415 1416
			     1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 145  146  1485 1487 1488 1489 1490 1491 150  1500 1501 1503 151  152
			     1520 1521 1522 1523 1524 1525 1526 1527 1528 1529 153  1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 154  1540 1541
			     1542 1543 1544 1545 1546 1547 1548 1549 155  1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 156  1560 1561 1562 1563
			     1564 1565 1566 1567 1568 1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585
			     1586 1587 1588 1589 159  1590 1591 1592 1593 1594 1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170
			     171  172  173  174  175  176  177  1771 1772 1773 1774 1775 1776 1777 1778 178  1780 1781 1782 1783 1787 1788 179  180
			     181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1835 1836 1837 1838 1839 184  1840 1841 1842 1843 1844 1845 1846
			     1847 1848 1849 185  1850 1856 1857 1858 1859 186  187  1874 188  189  190  1907 191  192  193  194  195  196  197  198
			     199  200  201  202  203  204  205  206  207  208  209  210  211  212  213  214  215  216  217  218  219  220  221  222
			     225  226  227  228  229  230  231  232  233  234  235  236  237  238  239  240  241  242  243  244  245  246  247  248
			     249  250  251  252  253  254  255  256  257  258  259  260  261  262  263  264  265  266  267  268  269  270  271  272
			     273  274  275  276  277  278  279  280  281  282  283  284  285  286  287  288  289  295  296  297  298  299  300  301
			     309  310  311  433  434  435  463  464  465  499  500  501  502  503  504  506  507  510  511  562  577  94
			   }
  # Air Doctrines 1936
  # ################
  techapps               = { 1010  1020  1030  1040  1050  1070  1080  1090  1110  1120  1130  1150  1160  1190  1200  1210  1220  1230  1240  1250
			     1260  1270  1280  1310  1320  1330  1340  1350  14000 14010 14020 2010  2020  2030  2040  2050  2060  2070  2080  2090
			     2100  2110  2120  2120  2130  2140  2150  2160  2170  2180  2190  2200  2220  2230  2240  2250  2260  2270  2280  2290
			     2300  2310  2320  2330  2340  2350  2370  2380  2390  2400  2410  2420  2430  2450  2460  2470  2480  2510  2520  3010
			     3020  3030  3040  3070  3080  3090  3130  3140  3150  3190  3200  3210  3250  3260  3270  3280  3320  3330  3400  3410
			     3420  3430  4010  4020  4030  4040  4050  4060  4070  4080  4090  4100  4120  4130  4140  4150  4160  4170  4180  4190
			     4200  4220  4230  4250  4260  4280  5010  5020  5050  5060  5070  5080  5090  5100  5110  5120  5130  5140  5160  5180
			     5190  5200  5210  5220  5230  5310  5320  5330  5350  5360  5410  5470  5480  5490  5500  5510  5550  5560  6210  6300
			     6310  6320  6330  6340  6350  6360  6370  8010  8020  8030  8040  8050  8080  8090  8150  8160  8170  8210  9010  9020
			     9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130  9140  9150  9160  9170  9180  9190  9200  9210  9220
			     9230  9240  9260  9270  9280  9290  9310  9320  9330  9350  9360  9430
			   }
  blueprints             = { 2490 3440 5150 5420 5430 5520 5530 5570 8280 8290 }
  diplomacy =
  { relation = { tag = BRA value = -50 }
    relation = { tag = BUL access = yes }
    relation = { tag = FIN access = yes value = 50 }
    relation =
    { tag        = MON
      value      = 150
      guaranteed = { day = 8 month = april year = 1943 }
      access     = yes
    }
    relation = { tag = PER value = -20 }
    relation = { tag = ROM access = yes }
    relation =
    { tag        = SIK
      guaranteed = { day = 30 month = december year = 1942 }
      access     = yes
    }
    relation = { tag = TUR value = 70 }
    relation = { tag = URU value = -100 }
    relation = { tag = ALB access = yes }
    relation = { tag = CZE access = yes }
    relation = { tag = POL access = yes }
    relation = { tag = YUG access = yes }
    relation = { tag = HUN access = yes }
    relation = { tag = SPA value = 150 }
  }
  dormant_ministers      = { 4031 4032 4039 4045 4066 4011 4012 4013 4014 4015 4016 4017 4018 4019 4020 4003 4005 4006 4007 4009 4010 4039 4040 4045
			     4046 4061 4064 4066 4004 4008 4051
			   }
  headofstate            = { type = 9 id = 4001 }
  headofgovernment       = { type = 9 id = 4002 }
  foreignminister        = { type = 9 id = 4034 }
  armamentminister       = { type = 9 id = 4038 }
  ministerofsecurity     = { type = 9 id = 4041 }
  ministerofintelligence = { type = 9 id = 4049 }
  chiefofstaff           = { type = 9 id = 4056 }
  chiefofarmy            = { type = 9 id = 4059 }
  chiefofnavy            = { type = 9 id = 4062 }
  chiefofair             = { type = 9 id = 4068 }
  dormant_teams		 = { 3706 3716 }
  dormant_leaders        = { 9839  9841  9843  9849  9884  9894  9896  9900  9907  9910  9926  9930  9951  9955  9969  9974  9991  9993  10006 10016
			     10019 10028 10031 10042 10054 10066 10071 10114 10115 10137 10138 10202 10208 10215 10253 10271 10276 10283 10286 10297
			     10322 10342 10349 10369 10370 10371 10401 10417 10453 10463 10472 10477 10500 10514 10515 10516 10517 10518 10520 10521
			     10522 10363
			   }
  # ### in division_development
  province_development =
  { id             = { type = 4712 id = 9934652452 }
    name           = ""
    progress       = 0.0000
    location       = 1552
    cost           = 15.0000
    date           = { year = 1946 month = march day = 14 hour = 0 }
    manpower       = 0.0000
    total_progress = 0.0000
    size           = 2
    done           = 0
    days           = 351
    days_for_first = 180
    type           = nuclear_reactor
  }
  landunit =
  { id       = { type = 30151 id = 1 }
    name     = "Trans-Baikal Front HQ"
    location = 1372
    division =
    { type          = hq
      model         = 1
      id            = { type = 30154 id = 1 }
      name          = "Trans-Baikal Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 20
    }
  }
  landunit =
  { id       = { type = 30151 id = 2 }
    name     = "1st Far Eastern Front HQ"
    location = 1201
    division =
    { type          = hq
      model         = 1
      id            = { type = 30154 id = 2 }
      name          = "1st Far Eastern Front HQ"
      experience    = 25
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 3 }
    name     = "2nd Far Eastern Front HQ"
    location = 1200
    division =
    { type          = hq
      model         = 1
      id            = { type = 30154 id = 3 }
      name          = "2nd Far Eastern Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 15
    }
  }
  landunit =
  { id       = { type = 30151 id = 4 }
    name     = "6th Guards Army"
    location = 1200
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 4 }
      name          = "20th Guards Tank"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 80
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 5 }
      name          = "7th Guards Mechanized"
      extra         = sp_rct_artillery
      brigade_model = 1
      experience    = 60
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 6 }
      name       = "61st Infantry"
      experience = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 7 }
      name          = "12th Guards Mechanized "
      extra         = anti_air
      brigade_model = 1
      experience    = 70
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 8 }
      name          = "143rd Infantry"
      extra         = artillery
      brigade_model = 5
      experience    = 44
    }
  }
  landunit =
  { id       = { type = 30151 id = 5 }
    name     = "17th Army"
    location = 1372
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 9 }
      name          = "209th Infantry"
      experience    = 33
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 10 }
      name          = "278th Infantry"
      experience    = 44
      extra         = rocket_artillery
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 11 }
      name          = "284th Infantry"
      experience    = 33
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 6 }
    name     = "36th Army"
    location = 1379
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 12 }
      name          = "102nd Infantry"
      experience    = 44
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 13 }
      name          = "94th Infantry"
      experience    = 33
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 14 }
      name          = "210th Infantry"
      experience    = 44
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 15 }
      name       = "292nd Infantry"
      experience = 33
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 16 }
      name       = "293rd Infantry"
      experience = 44
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 17 }
      name          = "275th Infantry"
      experience    = 33
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 18 }
      name       = "298th Infantry"
      experience = 33
    }
  }
  landunit =
  { id       = { type = 30151 id = 7 }
    name     = "39th Army"
    location = 1200
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 19 }
      name          = "17th Guards Infantry"
      experience    = 60
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 20 }
      name          = "19th Guards Infantry"
      experience    = 60
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 21 }
      name          = "91st Guards Infantry"
      experience    = 70
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 22 }
      name          = "124th Infantry"
      experience    = 33
      extra         = anti_tank
      brigade_model = 3
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 23 }
      name       = "221st Infantry"
      experience = 33
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 24 }
      name       = "358th Infantry"
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 25 }
      name       = "192nd Infantry"
      experience = 33
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 26 }
      name       = "262nd Infantry"
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 27 }
      name       = "228th Infantry"
      experience = 44
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 28 }
      name          = "3rd Guards Motorized Infantry"
      extra         = sp_artillery
      brigade_model = 1
      experience    = 60
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 29 }
      name          = "4th Guards  Motorized Infantry"
      extra         = sp_artillery
      brigade_model = 1
      experience    = 70
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 30 }
      name          = "21st Tank"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 34
    }
  }
  landunit =
  { id       = { type = 30151 id = 8 }
    name     = "53rd Army"
    location = 1202
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 31 }
      name          = "109 Guards Infantry"
      experience    = 77
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 32 }
      name          = "110th Guards Infantry"
      experience    = 73
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 33 }
      name       = "6th Infantry"
      experience = 33
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 34 }
      name          = "242nd Infantry"
      experience    = 44
      extra         = anti_tank
      brigade_model = 2
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 35 }
      name       = "56th Infantry"
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 36 }
      name       = "203rd Infantry"
      experience = 44
    }
    division =
    { type       = paratrooper
      model      = 2
      id         = { type = 30154 id = 37 }
      name       = "1st Guards Airborne"
      experience = 75
    }
  }
  landunit =
  { id       = { type = 30151 id = 9 }
    name     = "Cav-Mech Army"
    location = 1392
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 38 }
      name          = "3rd Guard Mechanized"
      extra         = heavy_armor
      brigade_model = 1
      experience    = 80
    }
    division =
    { type          = cavalry
      model         = 3
      id            = { type = 30154 id = 39 }
      name          = "59th Cavalry "
      experience    = 50
      extra         = light_armor_brigade
      brigade_model = 0
    }
    division =
    { type       = cavalry
      model      = 3
      id         = { type = 30154 id = 40 }
      name       = "5th Mongolian Cavalry"
      experience = 30
    }
    division =
    { type       = cavalry
      model      = 3
      id         = { type = 30154 id = 41 }
      name       = "6th Mongolian Cavalry"
      experience = 30
    }
    division =
    { type       = cavalry
      model      = 3
      id         = { type = 30154 id = 42 }
      name       = "7th Mongolian Cavalry"
      experience = 30
    }
    division =
    { type       = cavalry
      model      = 3
      id         = { type = 30154 id = 43 }
      name       = "8th Mongolian Cavalry"
      experience = 30
    }
  }
  landunit =
  { id       = { type = 30151 id = 10 }
    name     = "1st Red Banner Army"
    location = 1201
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 44 }
      name          = "22nd Infantry"
      experience    = 44
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 45 }
      name          = "39th Infantry"
      experience    = 44
      extra         = tank_destroyer
      brigade_model = 3
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 46 }
      name          = "58th Infantry"
      experience    = 33
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 47 }
      name          = "365th Infantry"
      experience    = 44
      extra         = light_armor_brigade
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 48 }
      name          = "231st Infantry"
      experience    = 44
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 49 }
      name       = "300th Infantry"
      experience = 33
    }
  }
  landunit =
  { id       = { type = 30151 id = 11 }
    name     = "5th Army"
    location = 1201
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 50 }
      name          = "187th Infantry"
      experience    = 33
      extra         = light_armor_brigade
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 51 }
      name          = "366th Infantry"
      experience    = 33
      extra         = sp_artillery
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 52 }
      name          = "157th Infantry"
      experience    = 44
      extra         = tank_destroyer
      brigade_model = 3
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 53 }
      name          = "159th Infantry"
      experience    = 44
      extra         = light_armor_brigade
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 54 }
      name          = "184th Infantry"
      experience    = 33
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 55 }
      name          = "197th Infantry"
      experience    = 44
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 56 }
      name          = "144th Infantry"
      experience    = 3
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 57 }
      name          = "190th Infantry"
      experience    = 44
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 58 }
      name          = "371st Infantry"
      experience    = 33
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 59 }
      name          = "63rd Infantry"
      experience    = 44
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 60 }
      name          = "215th Infantry"
      experience    = 44
      extra         = sp_rct_artillery
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 61 }
      name          = "277th Infantry"
      experience    = 33
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 12 }
    name     = "25th Army"
    location = 302
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 62 }
      name          = "145th Infantry"
      experience    = 40
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 63 }
      name          = "384th Infantry"
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 64 }
      name       = "393rd Infantry"
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 65 }
      name       = "386th Infantry"
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 13 }
    name     = "35th Army"
    location = 1393
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 66 }
      name       = "66th Infantry"
      experience = 44
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 67 }
      name          = "264th Infantry"
      experience    = 33
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 68 }
      name       = "363rd Infantry"
      experience = 44
    }
  }
  landunit =
  { id       = { type = 30151 id = 14 }
    name     = "2nd Red Banner Army"
    location = 1200
    division =
    { type       = motorized
      model      = 2
      id         = { type = 30154 id = 69 }
      name       = "3rd Motorized Infantry"
      experience = 40
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 70 }
      name          = "12th Motorized Infantry"
      experience    = 40
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 71 }
      name          = "396th Infantry"
      experience    = 44
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = bergsjaeger
      model      = 3
      id         = { type = 30154 id = 72 }
      name       = "369th Mountain Infantry"
      experience = 40
    }
  }
  landunit =
  { id       = { type = 30151 id = 15 }
    name     = "15th Army"
    location = 463
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 73 }
      name       = "34th Infantry"
      experience = 45
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 74 }
      name          = "388th Infantry"
      experience    = 45
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 75 }
      name          = "255th Infantry"
      experience    = 45
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 76 }
      name       = "361st Infantry"
      experience = 45
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 77 }
      name       = "35th Infantry"
      experience = 45
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 78 }
      name       = "390th Infantry"
      experience = 45
    }
  }
  landunit =
  { id       = { type = 30151 id = 16 }
    name     = "16th army"
    location = 304
    division =
    { type       = motorized
      model      = 1
      id         = { type = 30154 id = 79 }
      name       = "101st Motorized Infantry"
      experience = 50
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 80 }
      name          = "78th Infantry"
      experience    = 50
      extra         = tank_destroyer
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 17 }
    name     = "Karelian Front HQ"
    location = 132
    division =
    { type          = hq
      model         = 1
      id            = { type = 30154 id = 81 }
      name          = "Karelian Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 20
    }
  }
  landunit =
  { id       = { type = 30151 id = 18 }
    name     = "14th Army"
    location = 132
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 82 }
      name       = "122nd Infantry"
      strength   = 80
      experience = 33
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 83 }
      name          = "140th Infantry"
      strength      = 80
      experience    = 44
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 84 }
      name       = "123rd Infantry"
      strength   = 80
      experience = 33
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 85 }
      name          = "130th Infantry"
      strength      = 80
      experience    = 44
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 86 }
      name          = "142nd Infantry"
      strength      = 80
      experience    = 33
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 87 }
      name       = "132nd Infantry"
      strength   = 80
      experience = 44
    }
  }
  landunit =
  { id       = { type = 30151 id = 19 }
    name     = "19th Army"
    location = 297
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 88 }
      name       = "108th Infantry"
      strength   = 80
      experience = 30
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 89 }
      name       = "131st Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 90 }
      name          = "114th Infantry"
      strength      = 80
      experience    = 50
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 91 }
      name          = "137th Infantry"
      strength      = 80
      experience    = 44
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 92 }
      name          = "148th Infantry"
      strength      = 80
      experience    = 50
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 93 }
      name       = "149th Infantry"
      strength   = 80
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 20 }
    name     = "1st Belorussian Front HQ"
    location = 300
    division =
    { type          = hq
      model         = 2
      id            = { type = 30154 id = 94 }
      name          = "1st Belorussian Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 70
    }
  }
  landunit =
  { id       = { type = 30151 id = 21 }
    name     = "2nd Belorussian Front HQ"
    location = 297
    division =
    { type          = hq
      model         = 2
      id            = { type = 30154 id = 95 }
      name          = "2nd Belorussian Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 22 }
    name     = "3rd Belorussian Front HQ"
    location = 296
    division =
    { type          = hq
      model         = 2
      id            = { type = 30154 id = 96 }
      name          = "3rd Belorussian Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 30
    }
  }
  landunit =
  { id       = { type = 30151 id = 23 }
    name     = "1st Ukrainean Front HQ"
    location = 470
    division =
    { type          = hq
      model         = 2
      id            = { type = 30154 id = 97 }
      name          = "1st Ukrainean Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 70
    }
  }
  landunit =
  { id       = { type = 30151 id = 24 }
    name     = "2nd Ukrainean Front HQ"
    location = 463
    division =
    { type          = hq
      model         = 2
      id            = { type = 30154 id = 98 }
      name          = "2nd Ukrainean Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 25 }
    name     = "3rd Ukrainean Front HQ"
    location = 458
    division =
    { type          = hq
      model         = 2
      id            = { type = 30154 id = 99 }
      name          = "3rd Ukrainean Front HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 30
    }
  }
  landunit =
  { id       = { type = 30151 id = 26 }
    name     = "Steppe Front HQ"
    location = 485
    division =
    { type          = hq
      model         = 1
      id            = { type = 30154 id = 100 }
      name          = "Steppe Front HQ"
      experience    = 20
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 27 }
    name     = "STAVKA HQ"
    location = 1907
    division =
    { type          = hq
      model         = 2
      id            = { type = 30154 id = 101 }
      name          = "STAVKA HQ"
      extra         = anti_air
      brigade_model = 1
      experience    = 100
    }
  }
  landunit =
  { id       = { type = 30151 id = 28 }
    name     = "28th Army"
    location = 296
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 102 }
      name          = "32nd Guards Infantry"
      strength      = 80
      experience    = 66
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 103 }
      name          = "64th Infantry"
      strength      = 80
      experience    = 44
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 104 }
      name          = "127th Infantry"
      strength      = 80
      experience    = 44
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 105 }
      name          = "46th Infantry"
      strength      = 80
      experience    = 44
      extra         = anti_tank
      brigade_model = 2
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 106 }
      name       = "20th Infantry"
      strength   = 80
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 107 }
      name       = "72nd Infantry"
      strength   = 80
      experience = 44
    }
  }
  landunit =
  { id       = { type = 30151 id = 29 }
    name     = "31st Army"
    location = 301
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 108 }
      name       = "352nd Infantry"
      strength   = 75
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 109 }
      name       = "91st Infantry"
      strength   = 75
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 110 }
      name       = "113rd Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 111 }
      name       = "230th Infantry"
      strength   = 75
      experience = 30
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 112 }
      name          = "25th Guards Infantry"
      strength      = 75
      experience    = 60
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 113 }
      name          = "9th Motorized Infantry"
      strength      = 75
      experience    = 50
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 114 }
      name          = "5th Guards Motorized Infantry"
      strength      = 75
      experience    = 80
      extra         = sp_artillery
      brigade_model = 1
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 115 }
      name          = "9th Tank"
      strength      = 75
      experience    = 35
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 30 }
    name     = "2nd Guards Army"
    location = 296
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 116 }
      name       = "87th Infantry"
      strength   = 60
      experience = 47
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 117 }
      name       = "54th Infantry"
      strength   = 60
      experience = 47
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 118 }
      name       = "126th Infantry"
      strength   = 60
      experience = 48
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 119 }
      name       = "214th Infantry"
      strength   = 60
      experience = 48
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 120 }
      name          = "55th Motorized Infantry"
      strength      = 60
      experience    = 50
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 121 }
      name          = "21st Motorized Infantry "
      strength      = 60
      experience    = 30
      extra         = sp_artillery
      brigade_model = 1
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 122 }
      name          = "16th Tank"
      strength      = 60
      experience    = 50
      extra         = sp_rct_artillery
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 31 }
    name     = "2nd Shock Army"
    location = 300
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 123 }
      name          = "18th Guards Tank"
      extra         = sp_artillery
      brigade_model = 0
      strength      = 90
      experience    = 70
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 124 }
      name          = "22nd Tank"
      extra         = tank_destroyer
      brigade_model = 3
      strength      = 90
      experience    = 50
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 125 }
      name          = "10th Motorized Infantry"
      extra         = sp_rct_artillery
      brigade_model = 2
      strength      = 90
      experience    = 40
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 126 }
      name          = "57th Infantry"
      extra         = anti_air
      brigade_model = 1
      strength      = 90
      experience    = 33
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 127 }
      name       = "58th Infantry"
      strength   = 90
      experience = 33
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 128 }
      name       = "55th Infantry"
      strength   = 90
      experience = 33
    }
  }
  landunit =
  { id       = { type = 30151 id = 32 }
    name     = "61st Army"
    location = 299
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 129 }
      name       = "80th Infantry"
      strength   = 70
      experience = 50
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 130 }
      name          = "9th Guards Infantry"
      strength      = 70
      experience    = 66
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 131 }
      name       = "89th Infantry"
      strength   = 70
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 132 }
      name       = "98th Infantry"
      strength   = 70
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 133 }
      name       = "205th Infantry"
      strength   = 70
      experience = 50
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 134 }
      name          = "18th Guards Infantry"
      strength      = 70
      experience    = 66
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 135 }
      name       = "116th Infantry"
      strength   = 70
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 33 }
    name     = "5th Shock Army"
    location = 310
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 136 }
      name       = "235th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 137 }
      name          = "266th Infantry"
      strength      = 80
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 138 }
      name       = "416th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 139 }
      name       = "295th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 140 }
      name       = "301st Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 141 }
      name       = "248th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 142 }
      name          = "60th Guards Motorized Infantry"
      strength      = 80
      experience    = 80
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 143 }
      name          = "94th Guards Motorized Infantry"
      strength      = 80
      experience    = 70
      extra         = tank_destroyer
      brigade_model = 3
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 144 }
      name          = "89th Guards Motorized Infantry"
      strength      = 80
      experience    = 80
      extra         = sp_rct_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 34 }
    name     = "8th Guards Army"
    location = 471
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 145 }
      name          = "7th Guards Tank"
      extra         = sp_artillery
      brigade_model = 2
      strength      = 80
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 146 }
      name          = "27th Guards Motorized Infantry"
      extra         = tank_destroyer
      brigade_model = 2
      strength      = 80
      experience    = 70
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 147 }
      name          = "74th Guards Motorized Infantry"
      extra         = sp_rct_artillery
      brigade_model = 2
      strength      = 80
      experience    = 87
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 148 }
      name          = "82nd Guards Motorized Infantry"
      extra         = anti_air
      brigade_model = 1
      strength      = 80
      experience    = 78
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 149 }
      name       = "37th Guards Infantry"
      strength   = 80
      experience = 77
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 150 }
      name       = "88th Guards Infantry"
      strength   = 80
      experience = 66
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 151 }
      name       = "39th Guards Infantry"
      strength   = 80
      experience = 77
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 152 }
      name       = "79th Guards Infantry"
      strength   = 80
      experience = 80
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 153 }
      name       = "57th Guards Infantry"
      strength   = 80
      experience = 77
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 154 }
      name       = "47th Guards Infantry"
      strength   = 80
      experience = 66
    }
  }
  landunit =
  { id       = { type = 30151 id = 35 }
    name     = "3rd Army"
    location = 297
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 155 }
      name       = "136th Infantry"
      strength   = 60
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 156 }
      name       = "40th Infantry"
      strength   = 60
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 157 }
      name       = "41st Infantry"
      strength   = 60
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 158 }
      name       = "70th Infantry"
      strength   = 60
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 159 }
      name       = "81st Infantry"
      strength   = 60
      experience = 40
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 160 }
      name          = "27th Guards Infantry"
      strength      = 60
      experience    = 66
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 161 }
      name          = "32nd Motorized Infantry"
      strength      = 60
      experience    = 50
      extra         = sp_rct_artillery
      brigade_model = 1
    }
    division =
    { type          = mechanized
      model         = 1
      id            = { type = 30154 id = 162 }
      name          = "12th Guards Mechanized "
      strength      = 60
      experience    = 60
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 163 }
      name          = "4th Guards Tank"
      strength      = 60
      experience    = 70
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 36 }
    name     = "2nd Guards Tank Army"
    location = 309
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 164 }
      name          = "9th Guards Tank"
      extra         = heavy_armor
      brigade_model = 2
      strength      = 90
      experience    = 80
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 165 }
      name          = "12th Guards Tank"
      extra         = sp_rct_artillery
      brigade_model = 1
      strength      = 90
      experience    = 80
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 166 }
      name          = "9th Mechanized"
      strength      = 90
      experience    = 40
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 37 }
    name     = "47th Army"
    location = 469
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 167 }
      name       = "85th Infantry"
      strength   = 80
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 168 }
      name       = "125th Infantry"
      strength   = 80
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 169 }
      name       = "129th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 170 }
      name          = "42nd Infantry"
      strength      = 80
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 171 }
      name          = "337th Infantry"
      strength      = 80
      experience    = 30
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 172 }
      name       = "180th Infantry"
      strength   = 80
      experience = 30
    }
  }
  landunit =
  { id       = { type = 30151 id = 38 }
    name     = "3rd Shock Army"
    location = 311
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 173 }
      name       = "146th Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 174 }
      name       = "265th Infantry"
      strength   = 75
      experience = 59
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 175 }
      name       = "364th Infantry"
      strength   = 75
      experience = 59
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 176 }
      name          = "150th Infantry"
      strength      = 75
      experience    = 59
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 177 }
      name       = "207th Infantry"
      strength   = 75
      experience = 39
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 178 }
      name       = "171st Infantry"
      strength   = 75
      experience = 49
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 179 }
      name          = "23rd Guards Motorized Infantry"
      strength      = 75
      experience    = 80
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 180 }
      name       = "32nd Infantry"
      strength   = 75
      experience = 59
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 181 }
      name          = "52nd Guards Motorized Infantry"
      strength      = 75
      experience    = 70
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 182 }
      name          = "8th Tank"
      strength      = 75
      experience    = 50
      extra         = sp_rct_artillery
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 39 }
    name     = "1st Guards Tank Army"
    location = 298
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 183 }
      name          = "11th Guards Tank"
      extra         = heavy_armor
      brigade_model = 2
      experience    = 70
      strength      = 85
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 184 }
      name          = "12th Tank"
      extra         = sp_rct_artillery
      brigade_model = 1
      experience    = 50
      strength      = 85
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 185 }
      name          = "8th Guards Mechanized"
      extra         = tank_destroyer
      brigade_model = 3
      experience    = 60
      strength      = 85
    }
  }
  landunit =
  { id       = { type = 30151 id = 40 }
    name     = "33rd Army"
    location = 309
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 186 }
      name       = "95th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 187 }
      name       = "16th Infantry"
      strength   = 80
      experience = 30
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 188 }
      name       = "250th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 189 }
      name          = "62nd Infantry"
      strength      = 80
      experience    = 40
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 190 }
      name          = "20th Tank"
      strength      = 80
      experience    = 45
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 191 }
      name          = "2nd Guards Mechanized"
      strength      = 80
      experience    = 70
      extra         = light_armor_brigade
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30151 id = 41 }
    name     = "3rd Guards Army"
    location = 1788
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 192 }
      name       = "5th Guards Infantry"
      strength   = 85
      experience = 73
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 193 }
      name          = "2nd Motorized Infantry"
      strength      = 85
      experience    = 40
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 194 }
      name          = "16th Guards Tank"
      strength      = 85
      experience    = 80
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 42 }
    name     = "21st Army"
    location = 471
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 195 }
      name       = "204th Infantry"
      strength   = 80
      experience = 34
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 196 }
      name       = "109th Infantry"
      strength   = 80
      experience = 43
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 197 }
      name          = "110th Infantry"
      strength      = 80
      experience    = 34
      extra         = sp_rct_artillery
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 198 }
      name          = "97th Infantry"
      strength      = 80
      experience    = 43
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 199 }
      name       = "297th Infantry"
      strength   = 80
      experience = 34
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 200 }
      name          = "286th Infantry"
      strength      = 80
      experience    = 43
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 201 }
      name       = "168th Infantry"
      strength   = 80
      experience = 43
    }
  }
  landunit =
  { id       = { type = 30151 id = 43 }
    name     = "60th Army"
    location = 1859
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 202 }
      name       = "106th Infantry"
      strength   = 90
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 203 }
      name          = "15th Infantry "
      strength      = 90
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 204 }
      name          = "28th Infantry"
      strength      = 90
      experience    = 40
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = bergsjaeger
      model      = 2
      id         = { type = 30154 id = 205 }
      name       = "9th Mountain Infantry"
      strength   = 90
      experience = 40
    }
    division =
    { type       = bergsjaeger
      model      = 2
      id         = { type = 30154 id = 206 }
      name       = "3rd Mountain Infantry"
      strength   = 90
      experience = 40
    }
    division =
    { type       = bergsjaeger
      model      = 2
      id         = { type = 30154 id = 207 }
      name       = "13th Mountain Infantry"
      strength   = 90
      experience = 40
    }
  }
  landunit =
  { id       = { type = 30151 id = 44 }
    name     = "1st Guards Army"
    location = 465
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 208 }
      name       = "194th Infantry"
      strength   = 75
      experience = 44
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 209 }
      name          = "17th Infantry"
      strength      = 75
      experience    = 44
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 210 }
      name       = "107th Infantry"
      strength   = 75
      experience = 44
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 211 }
      name       = "237th Infantry"
      strength   = 75
      experience = 44
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 212 }
      name       = "351st Infantry"
      strength   = 75
      experience = 44
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 213 }
      name          = "11th Mechanized"
      strength      = 75
      experience    = 50
      extra         = light_armor_brigade
      brigade_model = 0
    }
    division =
    { type       = paratrooper
      model      = 2
      id         = { type = 30154 id = 214 }
      name       = "2nd Guards Airborne"
      strength   = 75
      experience = 70
    }
  }
  landunit =
  { id       = { type = 30151 id = 45 }
    name     = "3rd Guards Tank Army"
    location = 470
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 215 }
      name          = "6th Guards Tank"
      extra         = heavy_armor
      brigade_model = 1
      experience    = 80
      strength      = 80
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 216 }
      name          = "8th Guards Tank"
      extra         = tank_destroyer
      brigade_model = 3
      experience    = 70
      strength      = 80
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 217 }
      name          = "14th Mechanized"
      extra         = tank_destroyer
      brigade_model = 3
      experience    = 30
      strength      = 80
    }
  }
  landunit =
  { id       = { type = 30151 id = 46 }
    name     = "13th Army"
    location = 463
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 218 }
      name       = "27th Infantry"
      strength   = 85
      experience = 45
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 219 }
      name       = "104th Infantry"
      strength   = 85
      experience = 45
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 220 }
      name       = "133rd Infantry"
      strength   = 85
      experience = 45
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 221 }
      name       = "112nd Infantry"
      strength   = 85
      experience = 45
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 222 }
      name          = "24th Infantry"
      strength      = 85
      experience    = 45
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 223 }
      name          = "101st Infantry"
      strength      = 85
      experience    = 45
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = paratrooper
      model      = 2
      id         = { type = 30154 id = 224 }
      name       = "9th Guards Airborne "
      strength   = 85
      experience = 75
    }
  }
  landunit =
  { id       = { type = 30151 id = 47 }
    name     = "18th Army"
    location = 453
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 225 }
      name          = "14th Tank"
      strength      = 80
      experience    = 45
      extra         = tank_destroyer
      brigade_model = 3
    }
    division =
    { type          = mechanized
      model         = 0
      id            = { type = 30154 id = 226 }
      name          = "16th Mechanized"
      strength      = 75
      experience    = 40
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 227 }
      name       = "21st Infantry"
      strength   = 90
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 48 }
    name     = "5th Guards Army"
    location = 466
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 228 }
      name          = "121st Infantry"
      strength      = 65
      experience    = 30
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 229 }
      name       = "287th Guards Infantry"
      strength   = 65
      experience = 80
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 230 }
      name          = "140th Guards Infantry"
      strength      = 65
      experience    = 80
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 231 }
      name          = "14th Guards Infantry"
      strength      = 65
      experience    = 80
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 232 }
      name          = "20th Motorized Infantry"
      strength      = 65
      experience    = 50
      extra         = sp_rct_artillery
      brigade_model = 2
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 233 }
      name       = "299th Infantry"
      strength   = 65
      experience = 50
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 234 }
      name       = "252nd Infantry"
      strength   = 65
      experience = 44
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 235 }
      name          = "10th Guards Tank"
      strength      = 65
      experience    = 80
      extra         = tank_destroyer
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 30151 id = 49 }
    name     = "4th Guards Tank Army"
    location = 307
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 236 }
      name          = "2nd Guards Tank"
      extra         = heavy_armor
      brigade_model = 2
      strength      = 90
      experience    = 70
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 237 }
      name          = "5th Guards Mechanized"
      extra         = tank_destroyer
      brigade_model = 3
      strength      = 90
      experience    = 70
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 238 }
      name          = "6th Guards Mechanized"
      extra         = sp_rct_artillery
      brigade_model = 1
      strength      = 90
      experience    = 80
    }
  }
  landunit =
  { id       = { type = 30151 id = 50 }
    name     = "52nd Army"
    location = 310
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 239 }
      name          = "17th Tank"
      strength      = 75
      experience    = 45
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = mechanized
      model         = 1
      id            = { type = 30154 id = 240 }
      name          = "10th Guards Mechanized"
      strength      = 75
      experience    = 60
      extra         = sp_rct_artillery
      brigade_model = 2
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 241 }
      name       = "213rd Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 242 }
      name       = "48th Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 243 }
      name       = "73rd Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 244 }
      name       = "178th Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 245 }
      name       = "31st Infantry"
      strength   = 75
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 51 }
    name     = "40th Army"
    location = 463
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 246 }
      name          = "51st Infantry"
      strength      = 75
      experience    = 45
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 247 }
      name          = "30th Guards Infantry"
      strength      = 75
      experience    = 77
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 248 }
      name       = "43rd Infantry"
      strength   = 75
      experience = 45
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 249 }
      name       = "67th Infantry"
      strength   = 75
      experience = 45
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 250 }
      name          = "7th Tank"
      strength      = 75
      experience    = 44
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 52 }
    name     = "12th Guards Army"
    location = 485
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 251 }
      name          = "23th Guards Infantry"
      strength      = 65
      experience    = 77
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 252 }
      name          = "52nd Infantry"
      strength      = 65
      experience    = 50
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 253 }
      name          = "134th Infantry"
      strength      = 65
      experience    = 50
      extra         = anti_air
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 254 }
      name       = "84th Infantry"
      strength   = 65
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 53 }
    name     = "6th Tank Army"
    location = 465
    division =
    { type          = mechanized
      model         = 1
      id            = { type = 30154 id = 255 }
      name          = "15th Mechanized "
      strength      = 70
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = mechanized
      model         = 1
      id            = { type = 30154 id = 256 }
      name          = "17th Mechanized"
      strength      = 70
      experience    = 40
      extra         = sp_artillery
      brigade_model = 0
    }
    division =
    { type          = mechanized
      model         = 1
      id            = { type = 30154 id = 257 }
      name          = "18th Mechanized"
      strength      = 70
      experience    = 40
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 258 }
      name       = "22nd Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 259 }
      name       = "12th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 260 }
      name       = "39th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 261 }
      name          = "14th Guards Tank"
      strength      = 80
      experience    = 70
      extra         = heavy_armor
      brigade_model = 2
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 262 }
      name          = "19th Guards Tank"
      strength      = 80
      experience    = 80
      extra         = tank_destroyer
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 30151 id = 54 }
    name     = "27th Army"
    location = 381
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 263 }
      name          = "33rd Infantry "
      experience    = 33
      strength      = 70
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 264 }
      name          = "35th Guards Infantry"
      experience    = 77
      strength      = 70
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 265 }
      name          = "15th Guards Infantry"
      experience    = 77
      strength      = 70
      extra         = tank_destroyer
      brigade_model = 2
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 266 }
      name       = "193rd Infantry"
      experience = 33
      strength   = 70
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 267 }
      name       = "135th Infantry"
      experience = 44
      strength   = 70
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 268 }
      name       = "38th Infantry"
      experience = 44
      strength   = 70
    }
  }
  landunit =
  { id       = { type = 30151 id = 55 }
    name     = "18th Army"
    location = 311
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 269 }
      name       = "271st Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 270 }
      name       = "9th Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 271 }
      name       = "71st Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 272 }
      name          = "138th Infantry"
      strength      = 85
      experience    = 40
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 273 }
      name          = "24th Guards Infantry"
      strength      = 85
      experience    = 70
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 274 }
      name       = "267th Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 275 }
      name       = "317th Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 276 }
      name          = "8th Guards Infantry"
      strength      = 85
      experience    = 70
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30151 id = 56 }
    name     = "7th Guards Army"
    location = 464
    division =
    { type       = paratrooper
      model      = 2
      id         = { type = 30154 id = 277 }
      name       = "6th Airborne"
      strength   = 90
      experience = 40
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 278 }
      name          = "53rd Guards Motorized Infantry"
      strength      = 90
      experience    = 80
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 279 }
      name          = "409th Guards Motorized Infantry"
      strength      = 90
      experience    = 70
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 280 }
      name       = "36th Infantry"
      strength   = 90
      experience = 35
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 281 }
      name       = "141st Infantry"
      strength   = 90
      experience = 35
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 282 }
      name       = "243rd Infantry"
      strength   = 90
      experience = 35
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 283 }
      name          = "303rd Infantry"
      strength      = 90
      experience    = 35
      extra         = anti_air
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 284 }
      name       = "25th Infantry"
      strength   = 90
      experience = 35
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 285 }
      name       = "151st Infantry"
      strength   = 90
      experience = 35
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 286 }
      name       = "153rd Infantry"
      strength   = 90
      experience = 35
    }
  }
  landunit =
  { id       = { type = 30151 id = 57 }
    name     = "56th Army"
    location = 142
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 287 }
      name       = "23rd Infantry"
      strength   = 80
      experience = 44
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 288 }
      name          = "10th Guards Infantry"
      strength      = 80
      experience    = 72
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 289 }
      name          = "99th Infantry"
      strength      = 80
      experience    = 33
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 290 }
      name       = "175th Infantry"
      strength   = 80
      experience = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 291 }
      name          = "1st Guards Mechanized"
      strength      = 80
      experience    = 70
      extra         = tank_destroyer
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 30151 id = 58 }
    name     = "46th Army"
    location = 458
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 292 }
      name       = "49th Infantry"
      strength   = 65
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 293 }
      name       = "316th Infantry"
      strength   = 65
      experience = 50
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 294 }
      name          = "96th Infantry"
      strength      = 65
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 295 }
      name          = "320th Infantry"
      strength      = 65
      experience    = 40
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 296 }
      name       = "86th Infantry"
      strength   = 65
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 297 }
      name          = "59th Infantry"
      strength      = 65
      experience    = 30
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 298 }
      name          = "185st Infantry"
      strength      = 65
      experience    = 30
      extra         = anti_tank
      brigade_model = 3
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 299 }
      name          = "206th Infantry"
      strength      = 65
      experience    = 30
      extra         = sp_rct_artillery
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 300 }
      name       = "105th Infantry"
      strength   = 65
      experience = 40
    }
  }
  landunit =
  { id       = { type = 30151 id = 59 }
    name     = "4th Guards Army"
    location = 465
    division =
    { type       = paratrooper
      model      = 1
      id         = { type = 30154 id = 301 }
      name       = "5th Guards Airborne"
      strength   = 80
      experience = 75
    }
    division =
    { type       = paratrooper
      model      = 1
      id         = { type = 30154 id = 302 }
      name       = "7th Guards Airborne"
      strength   = 80
      experience = 75
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 303 }
      name          = "62nd Guards Infantry"
      strength      = 80
      experience    = 77
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 304 }
      name          = "69th Guards Infantry"
      strength      = 80
      experience    = 77
      extra         = artillery
      brigade_model = 5
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 305 }
      name          = "4th Guards Infantry"
      strength      = 80
      experience    = 77
      extra         = sp_rct_artillery
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 306 }
      name          = "34th Guards Infantry"
      strength      = 80
      experience    = 77
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 307 }
      name          = "80th Guards Infantry"
      strength      = 80
      experience    = 77
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 308 }
      name          = "152nd Infantry"
      strength      = 80
      experience    = 44
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 309 }
      name       = "93rd Infantry"
      strength   = 80
      experience = 44
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 310 }
      name       = "223rd Infantry"
      strength   = 80
      experience = 44
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 311 }
      name          = "40 Guards Motorized Infantry"
      strength      = 75
      experience    = 80
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 60 }
    name     = "6th Guards Tank Army"
    location = 459
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 312 }
      name          = "5th Guards Tank"
      extra         = heavy_armor
      brigade_model = 2
      strength      = 90
      experience    = 70
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 313 }
      name          = "9th Guards Motorized Infantry"
      strength      = 90
      experience    = 80
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 314 }
      name          = "7th Guards Motorized Infantry"
      strength      = 90
      experience    = 70
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 61 }
    name     = "9th Guards Army"
    location = 459
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 315 }
      name       = "13th Guards Infantry"
      strength   = 75
      experience = 77
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 316 }
      name       = "6th Guards Infantry"
      strength   = 75
      experience = 77
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 317 }
      name          = "6th Motorized Infantry"
      strength      = 75
      experience    = 30
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 318 }
      name          = "5th Motorized Infantry"
      strength      = 75
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 319 }
      name          = "15th Guards Tank"
      strength      = 75
      experience    = 70
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 320 }
      name          = "22nd Tank"
      strength      = 75
      experience    = 34
      extra         = sp_artillery
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 321 }
      name       = "3rd Infantry"
      strength   = 75
      experience = 30
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 322 }
      name       = "52nd Infantry"
      strength   = 75
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 62 }
    name     = "26th Army"
    location = 1503
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 323 }
      name       = "13th Infantry"
      strength   = 90
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 324 }
      name       = "19th Infantry"
      strength   = 90
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 325 }
      name          = "53rd Infantry"
      strength      = 90
      extra         = engineer
      brigade_model = 0
      experience    = 30
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 326 }
      name       = "69th Infantry"
      strength   = 90
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 327 }
      name       = "61st Infantry"
      strength   = 90
      experience = 50
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 328 }
      name       = "2nd Guards Infantry"
      strength   = 90
      experience = 78
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 329 }
      name          = "17th Guards Tank"
      strength      = 90
      extra         = heavy_armor
      brigade_model = 2
      experience    = 80
    }
  }
  landunit =
  { id       = { type = 30151 id = 63 }
    name     = "57th Army"
    location = 457
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 330 }
      name       = "236th Infantry"
      strength   = 55
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 331 }
      name       = "75th Infantry"
      strength   = 55
      experience = 30
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 332 }
      name          = "119th Infantry"
      strength      = 55
      experience    = 40
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 333 }
      name       = "68th Infantry"
      strength   = 55
      experience = 30
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 334 }
      name          = "50th Infantry"
      strength      = 55
      experience    = 30
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 335 }
      name          = "23rd Tank"
      strength      = 55
      experience    = 43
      extra         = sp_rct_artillery
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 64 }
    name     = "37th Army"
    location = 415
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 336 }
      name       = "333rd Infantry"
      strength   = 70
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 337 }
      name       = "180th Infantry"
      strength   = 70
      experience = 33
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 338 }
      name       = "195th Infantry"
      strength   = 70
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 339 }
      name       = "244th Infantry"
      strength   = 70
      experience = 33
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 340 }
      name       = "20th Guards Infantry"
      strength   = 70
      experience = 77
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 341 }
      name       = "28th Guards Infantry"
      strength   = 70
      experience = 77
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 342 }
      name       = "61st Guards Infantry"
      strength   = 70
      experience = 77
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 343 }
      name          = "7th Motorized Infantry"
      strength      = 70
      experience    = 40
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 344 }
      name       = "296nd Infantry"
      strength   = 70
      experience = 44
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 345 }
      name          = "4th Motorized Infantry"
      strength      = 70
      experience    = 30
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 346 }
      name          = "11th Tank"
      strength      = 70
      experience    = 45
      extra         = sp_artillery
      brigade_model = 0
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 347 }
      name          = "4th Tank"
      strength      = 70
      experience    = 45
      extra         = light_armor_brigade
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30151 id = 65 }
    name     = "11th Guards Army"
    location = 187
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 348 }
      name          = "1st Guards Tank"
      strength      = 90
      experience    = 80
      extra         = armored_car
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 349 }
      name          = "8th Guards Motorized Infantry"
      strength      = 90
      experience    = 70
      extra         = sp_rct_artillery
      brigade_model = 2
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 350 }
      name          = "11th Guards Infantry"
      strength      = 90
      experience    = 74
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 351 }
      name          = "36th Guards Infantry"
      strength      = 90
      experience    = 76
      extra         = anti_tank
      brigade_model = 3
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 352 }
      name       = "16th Guards Infantry"
      strength   = 90
      experience = 66
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 353 }
      name       = "65th Infantry"
      strength   = 90
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 354 }
      name       = "79th Infantry"
      strength   = 90
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 355 }
      name       = "7th Infantry"
      strength   = 90
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 66 }
    name     = "59th Army"
    location = 472
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 356 }
      name       = "100th Infantry"
      strength   = 55
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 357 }
      name       = "90th Infantry"
      strength   = 55
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 358 }
      name       = "78th Infantry"
      strength   = 55
      experience = 33
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 359 }
      name          = "18th Infantry"
      strength      = 55
      experience    = 33
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 360 }
      name       = "2nd Infantry"
      strength   = 55
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 361 }
      name       = "30th Infantry"
      strength   = 55
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 362 }
      name       = "47th Infantry"
      strength   = 55
      experience = 3
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 363 }
      name          = "3rd Tank"
      strength      = 55
      experience    = 33
      extra         = sp_artillery
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 67 }
    name     = "42nd Army"
    location = 197
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 364 }
      name       = "88th Infantry"
      strength   = 65
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 365 }
      name       = "128th Infantry"
      strength   = 65
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 366 }
      name       = "245th Infantry"
      strength   = 65
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 367 }
      name       = "376th Infantry"
      strength   = 65
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 368 }
      name       = "118th Infantry"
      strength   = 65
      experience = 40
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 369 }
      name          = "46th Guards Infantry"
      strength      = 65
      experience    = 63
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 370 }
      name          = "45th Guards Infantry"
      strength      = 65
      experience    = 63
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 371 }
      name          = "19th Tank"
      strength      = 65
      experience    = 34
      extra         = sp_artillery
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 30151 id = 68 }
    name     = "22nd Army"
    location = 416
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 372 }
      name       = "319th Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 373 }
      name       = "163rd Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 374 }
      name       = "28th Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 375 }
      name          = "21st Guards Infantry"
      strength      = 85
      experience    = 77
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 376 }
      name          = "6th Tank"
      strength      = 85
      experience    = 44
      extra         = sp_artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 30151 id = 69 }
    name     = "1st Shock Army"
    location = 380
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 377 }
      name       = "321st Infantry "
      strength   = 75
      experience = 49
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 378 }
      name          = "208th Infantry"
      strength      = 75
      experience    = 50
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 379 }
      name       = "147th Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 380 }
      name          = "33th Guards Infantry "
      strength      = 75
      experience    = 70
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 381 }
      name          = "26th Guards Infantry"
      strength      = 75
      experience    = 60
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 382 }
      name       = "11th Infantry "
      strength   = 75
      experience = 40
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 383 }
      name       = "285th Infantry "
      strength   = 75
      experience = 40
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 384 }
      name       = "282nd Infantry "
      strength   = 75
      experience = 40
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 385 }
      name       = "182nd Infantry "
      strength   = 75
      experience = 40
    }
  }
  landunit =
  { id       = { type = 30151 id = 70 }
    name     = "8th Army"
    location = 253
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 386 }
      name       = "4th Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 387 }
      name       = "26th Infantry"
      strength   = 75
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 388 }
      name       = "29th Infantry"
      strength   = 75
      experience = 40
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 389 }
      name          = "1st Tank"
      strength      = 75
      experience    = 35
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 390 }
      name          = "37th Infantry"
      strength      = 75
      experience    = 44
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 391 }
      name          = "66th Guards Infantry"
      strength      = 75
      experience    = 62
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30151 id = 71 }
    name     = "67th Army"
    location = 1500
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 392 }
      name          = "13th Tank"
      extra         = sp_artillery
      brigade_model = 1
      strength      = 70
      experience    = 35
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 393 }
      name          = "14th Motorized Infantry"
      extra         = tank_destroyer
      brigade_model = 2
      strength      = 70
      experience    = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 394 }
      name       = "198th Infantry"
      strength   = 70
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 395 }
      name       = "103rd Infantry"
      strength   = 70
      experience = 33
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 396 }
      name          = "8th Infantry"
      strength      = 70
      experience    = 44
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 397 }
      name       = "76th Infantry"
      strength   = 70
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 398 }
      name       = "111th Infantry"
      strength   = 70
      experience = 33
    }
  }
  landunit =
  { id       = { type = 30151 id = 72 }
    name     = "51st Army"
    location = 1787
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 399 }
      name          = "15th Tank"
      strength      = 80
      experience    = 45
      extra         = tank_destroyer
      brigade_model = 3
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 400 }
      name          = "3rd Guards Infantry"
      strength      = 80
      experience    = 74
      extra         = artillery
      brigade_model = 6
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 401 }
      name       = "83rd Infantry"
      strength   = 80
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 402 }
      name       = "1st Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 403 }
      name          = "5th Infantry"
      strength      = 80
      experience    = 30
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 404 }
      name       = "10th Infantry"
      strength   = 80
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 405 }
      name       = "45th Infantry"
      strength   = 80
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 406 }
      name       = "77th Infantry"
      strength   = 80
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 73 }
    name     = "54th Army"
    location = 390
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 407 }
      name          = "225th Infantry"
      strength      = 65
      experience    = 30
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 408 }
      name       = "196th Infantry"
      strength   = 65
      experience = 30
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 409 }
      name          = "44th Infantry"
      strength      = 65
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 410 }
      name       = "229th Infantry"
      strength   = 65
      experience = 40
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 411 }
      name       = "374th Infantry"
      strength   = 65
      experience = 50
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 412 }
      name       = "288th Infantry"
      strength   = 65
      experience = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 74 }
    name     = "4th Shock Army"
    location = 303
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 413 }
      name       = "14th Infantry"
      strength   = 60
      experience = 40
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 414 }
      name       = "120th Infantry "
      strength   = 60
      experience = 40
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 415 }
      name          = "360th Infantry "
      strength      = 60
      experience    = 40
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 416 }
      name       = "332nd Infantry "
      strength   = 60
      experience = 40
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 417 }
      name          = "24th Tank"
      strength      = 60
      experience    = 50
      extra         = light_armor_brigade
      brigade_model = 0
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 418 }
      name          = "5th Tank"
      strength      = 60
      experience    = 50
      extra         = sp_rct_artillery
      brigade_model = 2
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 419 }
      name          = "18th Tank"
      strength      = 60
      experience    = 45
      extra         = sp_artillery
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 420 }
      name       = "115th Infantry"
      strength   = 60
      experience = 45
    }
  }
  landunit =
  { id       = { type = 30151 id = 75 }
    name     = "43rd Army"
    location = 380
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30154 id = 421 }
      name          = "13th Guards Motorized Infantry"
      strength      = 75
      experience    = 70
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 422 }
      name       = "60th Infantry"
      strength   = 75
      experience = 33
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 423 }
      name       = "92nd Infantry"
      strength   = 75
      experience = 44
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 424 }
      name          = "74th Infantry"
      strength      = 75
      experience    = 33
      extra         = tank_destroyer
      brigade_model = 3
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 425 }
      name       = "160th Infantry"
      strength   = 75
      experience = 44
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 426 }
      name       = "117th Infantry"
      strength   = 75
      experience = 44
    }
    division =
    { type          = infantry
      model         = 3
      id            = { type = 30154 id = 427 }
      name          = "174th Infantry"
      strength      = 75
      experience    = 33
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30151 id = 76 }
    name     = "10th Guards Army"
    location = 1848
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 428 }
      name       = "1st Guards Infantry"
      strength   = 85
      experience = 73
    }
    division =
    { type          = infantry
      model         = 4
      id            = { type = 30154 id = 429 }
      name          = "12th Guards Infantry"
      strength      = 85
      experience    = 72
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { type       = infantry
      model      = 4
      id         = { type = 30154 id = 430 }
      name       = "7th Guards Infantry"
      strength   = 85
      experience = 79
    }
    division =
    { type       = infantry
      model      = 3
      id         = { type = 30154 id = 431 }
      name       = "82nd Infantry"
      strength   = 85
      experience = 40
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30154 id = 432 }
      name          = "2nd Tank"
      strength      = 80
      experience    = 34
      extra         = sp_artillery
      brigade_model = 1
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 433 }
      name          = "13th Guards Tank"
      experience    = 80
      strength      = 90
      extra         = sp_rct_artillery
      brigade_model = 2
    }
    division =
    { type       = motorized
      model      = 1
      id         = { type = 30154 id = 434 }
      name       = "1st Motorized Infantry"
      strength   = 90
      experience = 40
    }
    division =
    { type          = motorized
      model         = 1
      id            = { type = 30154 id = 435 }
      name          = "8th Motorized Infantry"
      strength      = 90
      extra         = artillery
      brigade_model = 6
      experience    = 40
    }
  }
  landunit =
  { id       = { type = 30151 id = 77 }
    name     = "5th Guards Tank Army"
    location = 482
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 436 }
      name          = "3rd Guards Tank"
      extra         = heavy_armor
      brigade_model = 2
      strength      = 85
      experience    = 70
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30154 id = 437 }
      name          = "10th Tank"
      extra         = sp_rct_artillery
      brigade_model = 1
      strength      = 85
      experience    = 50
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 438 }
      name          = "4th Guards Mechanized"
      extra         = tank_destroyer
      brigade_model = 2
      strength      = 85
      experience    = 60
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 30154 id = 439 }
      name          = "13th Mechanized"
      extra         = engineer
      brigade_model = 0
      strength      = 85
      experience    = 50
    }
  }
  landunit =
  { id       = { type = 30151 id = 78 }
    name     = "1st Kuril Garrison"
    location = 1174
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 440 }
      name  = "1st Kuril Garrison"
    }
  }
  landunit =
  { id       = { type = 30151 id = 79 }
    name     = "2nd Kuril Garrison"
    location = 1177
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 441 }
      name  = "2nd Kuril Garrison"
    }
  }
  landunit =
  { id       = { type = 30151 id = 80 }
    name     = "1st Sachalin Garrison"
    location = 1175
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 442 }
      name  = "1st Sachalin Garrison"
    }
  }
  landunit =
  { id       = { type = 30151 id = 81 }
    name     = "2nd Sachalin Garrison"
    location = 1176
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 443 }
      name  = "2nd Sachalin Garrison"
    }
  }
  landunit =
  { id       = { type = 30151 id = 82 }
    name     = "1st Manchuria Security"
    location = 1380
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 444 }
      name  = "1st Manchuria Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 83 }
    name     = "2nd Manchuria Security "
    location = 1375
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 445 }
      name  = "2nd Manchuria Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 84 }
    name     = "3rd Manchuria Security"
    location = 1388
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 446 }
      name  = "3rd Manchuria Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 85 }
    name     = "4th Manchuria Security"
    location = 1395
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 447 }
      name  = "4th Manchuria Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 86 }
    name     = "5th Manchuria Security"
    location = 1390
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 448 }
      name  = "5th Manchuria Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 87 }
    name     = "1st Far East Coast Guards"
    location = 1367
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 466 }
      name  = "1st Far East Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 88 }
    name     = "2nd Far East Coast Guards"
    location = 1371
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 467 }
      name  = "2nd Far East Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 89 }
    name     = "3rd Far East Coast Guards"
    location = 1370
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 468 }
      name  = "3rd Far East Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 90 }
    name     = "1st Border Guards"
    location = 1520
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 460 }
      name  = "1st Border Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 91 }
    name     = "2nd Border Guards"
    location = 1422
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 461 }
      name  = "2nd Border Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 92 }
    name     = "3rd Border Guards"
    location = 1485
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 462 }
      name  = "3rd Border Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 93 }
    name     = "4th Border Guards"
    location = 1487
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 463 }
      name  = "4th Border Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 94 }
    name     = "5th Border Guards"
    location = 1856
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 464 }
      name  = "5th Border Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 95 }
    name     = "6th Border Guards"
    location = 1850
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 465 }
      name  = "6th Border Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 96 }
    name     = "1st Security "
    location = 298
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 456 }
      name  = "1st Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 97 }
    name     = "2nd Security "
    location = 311
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 457 }
      name  = "2nd Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 98 }
    name     = "3rd Security "
    location = 463
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 458 }
      name  = "3rd Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 99 }
    name     = "4th Security "
    location = 300
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 459 }
      name  = "4th Security Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 100 }
    name     = "1st Coast Guards"
    location = 133
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 449 }
      name  = "1st Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 101 }
    name     = "2nd Coast Guards"
    location = 197
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 450 }
      name  = "2nd Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 102 }
    name     = "3rd Coast Guards"
    location = 253
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 451 }
      name  = "3rd Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 103 }
    name     = "4th Coast Guards"
    location = 205
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 452 }
      name  = "4th Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 104 }
    name     = "5th Coast Guards"
    location = 510
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 453 }
      name  = "5th Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 105 }
    name     = "6th Coast Guards"
    location = 154
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 454 }
      name  = "6th Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 106 }
    name     = "7th Coast Guards"
    location = 194
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 455 }
      name  = "7th Coast Guard Division"
    }
  }
  landunit =
  { id       = { type = 30151 id = 107 }
    name     = "4th Far East Coast Guards"
    location = 1527
    division =
    { type  = garrison
      model = 2
      id    = { type = 30154 id = 469 }
      name  = "4th Far East Coast Guard Division"
    }
  }
  navalunit =
  { id       = { type = 30152 id = 1 }
    name     = "Cernoje Flote"
    location = 253
    base     = 253
    division =
    { experience = 25
      id         = { type = 30155 id = 1 }
      name       = "Parishskaya Kommuna"
      type       = battleship
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 2 }
      name       = "Voroshilov"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 3 }
      name       = "Molotov"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 4 }
      name       = "Kaganovich"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 5 }
      name       = "Krasnyi Kavkaz"
      type       = heavy_cruiser
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 6 }
      name       = "Profintern"
      type       = light_cruiser
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 7 }
      name       = "1. Flotiliya Esmintsev"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 8 }
      name       = "2. Flotiliya Esmintsev"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 9 }
      name       = "3. Flotiliya Esmintsev"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 10 }
      name       = "4. Flotiliya Esmintsev"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 11 }
      name       = "17. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 12 }
      name       = "18. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 13 }
      name       = "19. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 14 }
      name       = "1. Transportnaya Flotiliya"
      type       = transport
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 15 }
      name       = "2. Transportnaya Flotiliya"
      type       = transport
    }
  }
  navalunit =
  { id       = { type = 30152 id = 2 }
    name     = "Arskoje Flote"
    location = 133
    base     = 133
    division =
    { experience = 25
      id         = { type = 30155 id = 16 }
      name       = "Murmansk"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 17 }
      name       = "13. Flotiliya Esmintsev"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 18 }
      name       = "20. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 19 }
      name       = "21. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 30152 id = 3 }
    name     = "Beringovo Flote"
    location = 1372
    base     = 1372 # Vladivostok
    division =
    { experience = 25
      id         = { type = 30155 id = 20 }
      name       = "16. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 21 }
      name       = "23. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 22 }
      name       = "25. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 30152 id = 4 }
    name     = "CCCP Baltijskoje Flote"
    location = 187
    base     = 187 # Leningrad
    division =
    { experience = 25
      id         = { type = 30155 id = 23 }
      name       = "Oktyabrskaya Revolutsia"
      type       = battleship
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 24 }
      name       = "Kirov"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 25 }
      name       = "Maxim Gor'kiy"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 26 }
      name       = "Kalinin"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 27 }
      name       = "9. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 28 }
      name       = "28. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 29 }
      name       = "27. Flotiliya Esmintsev"
      type       = destroyer
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 30152 id = 5 }
    name     = "2. Flote Podlodok"
    location = 187
    base     = 187 # Leningrad
    division =
    { experience = 25
      id         = { type = 30155 id = 30 }
      name       = "9. Flotiliya Podlodok"
      type       = submarine
      model      = 1
    }
  }
  navalunit =
  { id       = { type = 30152 id = 6 }
    name     = "3. Flote Podlodok"
    location = 187
    base     = 187 # Leningrad
    division =
    { experience = 25
      id         = { type = 30155 id = 31 }
      name       = "12. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 32 }
      name       = "13. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 33 }
      name       = "14. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 34 }
      name       = "15. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 35 }
      name       = "16. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 30152 id = 7 }
    name     = "4. Flote Podlodok"
    location = 253
    base     = 253 # Sevastopol
    division =
    { experience = 25
      id         = { type = 30155 id = 36 }
      name       = "17. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 37 }
      name       = "18. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 38 }
      name       = "19. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 39 }
      name       = "20. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 40 }
      name       = "21. Flotiliya Podlodok"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 41 }
      name       = "22. Flotiliya Podlodok"
      type       = submarine
      model      = 1
    }
  }
  navalunit =
  { id       = { type = 30152 id = 8 }
    name     = "5. Flote Podlodok"
    location = 253
    base     = 253 # Sevastopol
    division =
    { experience = 25
      id         = { type = 30155 id = 42 }
      name       = "23. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 43 }
      name       = "24. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 44 }
      name       = "25. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 45 }
      name       = "26. Flotiliya Podlodok"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 46 }
      name       = "27. Flotiliya Podlodok"
      type       = submarine
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 47 }
      name       = "28. Flotiliya Podlodok"
      type       = submarine
      model      = 1
    }
  }
  navalunit =
  { id       = { type = 30152 id = 9 }
    name     = "6. Flote Podlodok"
    location = 1372
    base     = 1372 # Vladivostok
    division =
    { experience = 25
      id         = { type = 30155 id = 48 }
      name       = "29. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 49 }
      name       = "30. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 50 }
      name       = "31. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 51 }
      name       = "32. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 52 }
      name       = "33. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 53 }
      name       = "34. Flotiliya Podlodok"
      type       = submarine
      model      = 2
    }
  }
  navalunit =
  { id       = { type = 30152 id = 10 }
    name     = "1. Flote Podlodok"
    location = 133
    base     = 133 # ##murmansk
    division =
    { experience = 25
      id         = { type = 30155 id = 54 }
      name       = "1. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 55 }
      name       = "2. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 56 }
      name       = "3. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 57 }
      name       = "4. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 58 }
      name       = "5. Flotiliya Podlodok"
      type       = submarine
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30155 id = 59 }
      name       = "6. Flotiliya Podlodok"
      type       = submarine
      model      = 1
    }
  }
  navalunit =
  { id       = { type = 30152 id = 11 }
    name     = "7. Flote Podlodok"
    location = 187
    base     = 187 # Leningrad
    division =
    { experience = 0
      id         = { type = 30155 id = 60 }
      name       = "35. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 61 }
      name       = "36. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 62 }
      name       = "37. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 63 }
      name       = "38. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 64 }
      name       = "39. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 65 }
      name       = "40. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 30152 id = 12 }
    name     = "8. Flote Podlodok"
    location = 253
    base     = 253 # Sevastopol
    division =
    { experience = 0
      id         = { type = 30155 id = 66 }
      name       = "41. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 67 }
      name       = "42. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 68 }
      name       = "43. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 69 }
      name       = "44. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 70 }
      name       = "45. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 71 }
      name       = "46. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 30152 id = 13 }
    name     = "9. Flote Podlodok"
    location = 133
    base     = 133 # ##murmansk
    division =
    { experience = 0
      id         = { type = 30155 id = 72 }
      name       = "47. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 73 }
      name       = "48. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 74 }
      name       = "49. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 75 }
      name       = "50. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 76 }
      name       = "51. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 77 }
      name       = "52. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 30152 id = 14 }
    name     = "10. Flote Podlodok"
    location = 1372
    base     = 1372 # Vladivostok
    division =
    { experience = 0
      id         = { type = 30155 id = 78 }
      name       = "53. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 79 }
      name       = "54. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 80 }
      name       = "55. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 81 }
      name       = "56. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 82 }
      name       = "57. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 0
      id         = { type = 30155 id = 83 }
      name       = "58. Flotiliya Podlodok"
      type       = submarine
      model      = 3
    }
  }
  airunit =
  { location = 253
    base     = 253
    id       = { type = 30153 id = 1 }
    name     = "4th Bomber Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 1 }
      name       = "202. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 2 }
      name       = "219. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 463
    base     = 463
    id       = { type = 30153 id = 2 }
    name     = "5th Assault Avialtion Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 3 }
      name       = "4th Gds Assault Division"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 4 }
      name       = "264. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 5 }
      name       = "2nd Gds Assault Division"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 300
    base     = 300
    id       = { type = 30153 id = 3 }
    name     = "8th Assault Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 6 }
      name       = "224. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 7 }
      name       = "226. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 8 }
      name       = "299. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 501
    base     = 501
    id       = { type = 30153 id = 4 }
    name     = "5th interceptor Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 9 }
      name       = "5th Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 10 }
      name       = "256. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 296
    base     = 296
    id       = { type = 30153 id = 5 }
    name     = "10th interceptor Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 11 }
      name       = "10th Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 12 }
      name       = "235. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 510
    base     = 510
    id       = { type = 30153 id = 6 }
    name     = "2nd Air Army Night Bomber Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 13 }
      name       = "208th Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 14 }
      name       = "326th Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
  }
  airunit =
  { location = 132
    base     = 132
    id       = { type = 30153 id = 7 }
    name     = "2nd Gds Bomber Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 15 }
      name       = "1st Gds Bomber Division"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 16 }
      name       = "8th Gds Bomber Division"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 305
    base     = 305
    id       = { type = 30153 id = 8 }
    name     = "1st Gds Assault Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 17 }
      name       = "8. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 18 }
      name       = "9th Gds Bomber Division"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 19 }
      name       = "12th Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 20 }
      name       = "312 Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
  }
  airunit =
  { location = 303
    base     = 303
    id       = { type = 30153 id = 9 }
    name     = "2nd Assault Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 21 }
      name       = "7th Gds Assault Division"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 22 }
      name       = "231. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 307
    base     = 307
    id       = { type = 30153 id = 10 }
    name     = "4th interceptor Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 23 }
      name       = "294. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 24 }
      name       = "302. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 163
    base     = 163
    id       = { type = 30153 id = 11 }
    name     = "7th interceptor Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 25 }
      name       = "9th Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 26 }
      name       = "205. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 27 }
      name       = "304. IAD"
      strength   = 100
      type       = interceptor
      model      = 2
    }
  }
  airunit =
  { location = 466
    base     = 466
    id       = { type = 30153 id = 12 }
    name     = "1st Gds Mixed Air Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 28 }
      name       = "5th Gds Assault Division"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 29 }
      name       = "6th Gds Assault Division"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 30 }
      name       = "11th Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 466
    base     = 466
    id       = { type = 30153 id = 13 }
    name     = "9 Mixed Air Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 31 }
      name       = "305. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 32 }
      name       = "306. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 33 }
      name       = "295. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 381
    base     = 381
    id       = { type = 30153 id = 14 }
    name     = "17th Air Army Reserves"
    division =
    { experience = 25
      id         = { type = 30156 id = 34 }
      name       = "236. IAD"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 35 }
      name       = "238. IAD"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 36 }
      name       = "262nd Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 37 }
      name       = "218. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 457
    base     = 457
    id       = { type = 30153 id = 15 }
    name     = "11th Mixed Air Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 38 }
      name       = "4, 148 & 293 interceptor Regiments"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 39 }
      name       = "658 & 724 Assault Regiments"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 40 }
      name       = "284th Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 41 }
      name       = "313rd Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
  }
  airunit =
  { location = 479
    base     = 479
    id       = { type = 30153 id = 16 }
    name     = "14th Air Army"
    division =
    { experience = 25
      id         = { type = 30156 id = 42 }
      name       = "281. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 43 }
      name       = "269. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 44 }
      name       = "225. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 300
    base     = 300
    id       = { type = 30153 id = 17 }
    name     = "13 Air Army"
    division =
    { experience = 25
      id         = { type = 30156 id = 45 }
      name       = "276. DBAD"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 46 }
      name       = "277. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 47 }
      name       = "275. IAD"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 48 }
      name       = "246. IAD"
      strength   = 100
      type       = multi_role
      model      = 1
    }
  }
  airunit =
  { location = 1202
    base     = 1202
    id       = { type = 30153 id = 18 }
    name     = "12th Air Army"
    division =
    { experience = 25
      id         = { type = 30156 id = 49 }
      name       = "30. DBAD"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 50 }
      name       = "247. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 51 }
      name       = "248. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 52 }
      name       = "246. IAD"
      strength   = 100
      type       = multi_role
      model      = 1
    }
  }
  airunit =
  { location = 485
    base     = 485
    id       = { type = 30153 id = 19 }
    name     = "11th interceptor Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 53 }
      name       = "5th Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 54 }
      name       = "190. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 476
    base     = 476
    id       = { type = 30153 id = 20 }
    name     = "1st Guards Bomber Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 55 }
      name       = "4th Gds Bomber Division"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 56 }
      name       = "5th Gds Bomber Division"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 187
    base     = 187
    id       = { type = 30153 id = 21 }
    name     = "1st Naval Bomber Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 57 }
      name       = "1st Naval Bomber Division"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 58 }
      name       = "2nd Naval Bomber Division"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 59 }
      name       = "3rd Naval Bomber Division"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 463
    base     = 463
    id       = { type = 30153 id = 22 }
    name     = "3rd Assault Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 60 }
      name       = "307. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 61 }
      name       = "308. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 463
    base     = 463
    id       = { type = 30153 id = 23 }
    name     = "3rd Gds Bomber Division"
    division =
    { experience = 25
      id         = { type = 30156 id = 62 }
      name       = "113. DBAD"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 63 }
      name       = "311. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 64 }
      name       = "303. IAD"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 65 }
      name       = "213th Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
  }
  airunit =
  { location = 469
    base     = 469
    id       = { type = 30153 id = 24 }
    name     = "1st Guards interceptor Aviation Corps "
    division =
    { experience = 25
      id         = { type = 30156 id = 66 }
      name       = "3rd Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 67 }
      name       = "4th Gds interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 469
    base     = 469
    id       = { type = 30153 id = 25 }
    name     = "2nd interceptor Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 68 }
      name       = "240. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 69 }
      name       = "303. IAD"
      strength   = 100
      type       = interceptor
      model      = 1
    }
  }
  # division = { experience = 25
  # id = { type = 10849 id = 1142 }
  # name = "7th Gds interceptor Division"
  # strength = 100
  # type = multi_role
  # model = 1
  # }
  # division = { experience = 25
  # id = { type = 10849 id = 1143 }
  # name = "322. IAD"
  # strength = 100
  # type = multi_role
  # model = 1
  # }
  airunit =
  { location = 163
    base     = 163
    id       = { type = 30153 id = 26 }
    name     = "3rd interceptor Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 70 }
      name       = "265. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 71 }
      name       = "278. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 72 }
      name       = "240. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 296
    base     = 296
    id       = { type = 30153 id = 27 }
    name     = "1st Air Army Reserves"
    division =
    { experience = 25
      id         = { type = 30156 id = 73 }
      name       = "6th Gds Bomber Division"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 74 }
      name       = "1st Gds Assault Division"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 75 }
      name       = "334. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 76 }
      name       = "311. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 1201
    base     = 1201
    id       = { type = 30153 id = 28 }
    name     = "9th Air Army"
    division =
    { experience = 25
      id         = { type = 30156 id = 77 }
      name       = "229. IAD"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 78 }
      name       = "325th Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 79 }
      name       = "233. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 80 }
      name       = "309. IAD"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 485
    base     = 485
    id       = { type = 30153 id = 29 }
    name     = "6th Air Army"
    division =
    { experience = 25
      id         = { type = 30156 id = 81 }
      name       = "3rd Guards Assault Division"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 82 }
      name       = "336. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 83 }
      name       = "242nd Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 84 }
      name       = "230. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  airunit =
  { location = 469
    base     = 469
    id       = { type = 30153 id = 30 }
    name     = "3rd Bomber Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 85 }
      name       = "241. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 86 }
      name       = "301. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 417
    base     = 417
    id       = { type = 30153 id = 31 }
    name     = "6th Mixed Aviation Corps"
    division =
    { experience = 25
      id         = { type = 30156 id = 87 }
      name       = "132. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 88 }
      name       = "221. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 89 }
      name       = "283. IAD"
      strength   = 100
      type       = interceptor
      model      = 2
    }
  }
  # division = { experience = 25
  # id = { type = 10849 id = 1184 }
  # name = "282. IAD"
  # strength = 100
  # type = multi_role
  # model = 1
  # }
  airunit =
  { location = 390
    base     = 390
    id       = { type = 30153 id = 32 }
    name     = "6th interceptor Aviation Corps"
    # division = { experience = 25
    # id = { type = 10849 id = 1188 }
    # name = "273. IAD"
    # strength = 100
    # type = multi_role
    # model = 1
    # }
    division =
    { experience = 25
      id         = { type = 30156 id = 90 }
      name       = "279. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
  }
  airunit =
  { location = 453
    base     = 453
    id       = { type = 30153 id = 33 }
    name     = "16th Air Army Mixed units"
    division =
    { experience = 25
      id         = { type = 30156 id = 91 }
      name       = "1st Guards interceptor Division"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 92 }
      name       = "234. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 93 }
      name       = "286. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 94 }
      name       = "271st Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
  }
  airunit =
  { location = 1372
    base     = 1372
    id       = { type = 30153 id = 34 }
    name     = "10th Air Army"
    division =
    { experience = 25
      id         = { type = 30156 id = 95 }
      name       = "115. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 96 }
      name       = "107. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 97 }
      name       = "100. IAD"
      strength   = 100
      type       = interceptor
      model      = 3
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 98 }
      name       = "95. BAD"
      strength   = 100
      type       = tactical_bomber
      model      = 1
    }
  }
  airunit =
  { location = 296
    base     = 296
    id       = { type = 30153 id = 35 }
    name     = "3rd Air Army Reserves"
    division =
    { experience = 25
      id         = { type = 30156 id = 99 }
      name       = "211. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 100 }
      name       = "335. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
    # division = { experience = 25
    # id = { type = 10849 id = 1214 }
    # name = "259. IAD"
    # strength = 100
    # type = multi_role
    # model = 1
    # }
    division =
    { experience = 25
      id         = { type = 30156 id = 101 }
      name       = "314th Night Bomber Division"
      strength   = 100
      type       = strategic_bomber
      model      = 0
    }
    division =
    { experience = 25
      id         = { type = 30156 id = 102 }
      name       = "316. ShAD"
      strength   = 100
      type       = cas
      model      = 1
    }
  }
  division_development =
  { name           = "Baku"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 84 }
    date           = { year = 1945 month = november day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Gorki"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 85 }
    date           = { year = 1945 month = november day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Riga"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 86 }
    date           = { year = 1945 month = november day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Tallin"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 87 }
    date           = { year = 1945 month = december day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Vilna"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 88 }
    date           = { year = 1945 month = december day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Smolensk"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 89 }
    date           = { year = 1945 month = december day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Archangelsk"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 90 }
    date           = { year = 1946 month = january day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Vladivostok"
    type           = light_cruiser
    model          = 2
    cost           = 2.5
    id             = { type = 30155 id = 91 }
    date           = { year = 1946 month = january day = 0 }
    days           = 220
    # # days_of_first  = 220
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Novosibirsk"
    type           = heavy_cruiser
    model          = 2
    cost           = 3
    id             = { type = 30155 id = 92 }
    date           = { year = 1945 month = november day = 0 }
    days           = 310
    # # days_of_first  = 310
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Irkutsk"
    type           = heavy_cruiser
    model          = 2
    cost           = 3
    id             = { type = 30155 id = 93 }
    date           = { year = 1945 month = december day = 0 }
    days           = 310
    # # days_of_first  = 310
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Kursk"
    type           = heavy_cruiser
    model          = 2
    cost           = 3
    id             = { type = 30155 id = 94 }
    date           = { year = 1946 month = january day = 0 }
    days           = 310
    # # days_of_first  = 310
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Sverdlovsk"
    type           = heavy_cruiser
    model          = 2
    cost           = 3
    id             = { type = 30155 id = 95 }
    date           = { year = 1946 month = january day = 0 }
    days           = 310
    # # days_of_first  = 310
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Kiev"
    type           = battlecruiser
    model          = 2
    cost           = 4
    id             = { type = 30155 id = 96 }
    date           = { year = 1945 month = november day = 0 }
    days           = 615
    # # days_of_first  = 615
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Minsk"
    type           = battlecruiser
    model          = 2
    cost           = 4
    id             = { type = 30155 id = 97 }
    date           = { year = 1945 month = december day = 0 }
    days           = 615
    # # days_of_first  = 615
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Leningrad"
    type           = battlecruiser
    model          = 2
    cost           = 4
    id             = { type = 30155 id = 98 }
    date           = { year = 1946 month = january day = 0 }
    days           = 615
    # # days_of_first  = 615
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Moscow"
    type           = battleship
    model          = 2
    cost           = 4.5
    id             = { type = 30155 id = 99 }
    date           = { year = 1945 month = november day = 0 }
    days           = 730
    # # days_of_first  = 730
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Stalingrad"
    type           = battleship
    model          = 2
    cost           = 4.5
    id             = { type = 30155 id = 100 }
    date           = { year = 1946 month = january day = 0 }
    days           = 730
    # # days_of_first  = 730
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "Josif W. Stalin"
    type           = carrier
    model          = 1
    cost           = 5.7
    id             = { type = 30155 id = 101 }
    date           = { year = 1946 month = january day = 1 }
    days           = 650
    # # days_of_first  = 730
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
    extra          = cag
    brigade_model  = 1
  }
  # # days_of_first  = 650
  # # series         = 1
  division_development =
  { name           = "30. Flotiliya Esmintsev"
    type           = destroyer
    model          = 2
    cost           = 1
    id             = { type = 30155 id = 102 }
    date           = { year = 1945 month = november day = 0 }
    days           = 140
    # # days_of_first  = 140
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "31. Flotiliya Esmintsev"
    type           = destroyer
    model          = 2
    cost           = 1
    id             = { type = 30155 id = 103 }
    date           = { year = 1945 month = november day = 0 }
    days           = 140
    # # days_of_first  = 140
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "32. Flotiliya Esmintsev"
    type           = destroyer
    model          = 2
    cost           = 1
    id             = { type = 30155 id = 104 }
    date           = { year = 1945 month = december day = 0 }
    days           = 140
    # # days_of_first  = 140
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "33. Flotiliya Esmintsev"
    type           = destroyer
    model          = 2
    cost           = 1
    id             = { type = 30155 id = 105 }
    date           = { year = 1945 month = december day = 0 }
    days           = 140
    # # days_of_first  = 140
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "34. Flotiliya Esmintsev"
    type           = destroyer
    model          = 2
    cost           = 1
    id             = { type = 30155 id = 106 }
    date           = { year = 1946 month = january day = 0 }
    days           = 140
    # # days_of_first  = 140
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "35. Flotiliya Esmintsev"
    type           = destroyer
    model          = 2
    cost           = 1
    id             = { type = 30155 id = 107 }
    date           = { year = 1946 month = january day = 0 }
    days           = 140
    # # days_of_first  = 140
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "50. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 108 }
    date           = { year = 1945 month = november day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "51. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 109 }
    date           = { year = 1945 month = november day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "52. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 110 }
    date           = { year = 1945 month = november day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "53. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 111 }
    date           = { year = 1945 month = november day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "54. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 112 }
    date           = { year = 1945 month = november day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "55. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 113 }
    date           = { year = 1945 month = november day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "56. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 114 }
    date           = { year = 1945 month = december day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "57. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 115 }
    date           = { year = 1945 month = december day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "58. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 116 }
    date           = { year = 1945 month = december day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "59. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 117 }
    date           = { year = 1945 month = december day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "60. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 118 }
    date           = { year = 1945 month = december day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "61. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 119 }
    date           = { year = 1945 month = december day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "62. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 120 }
    date           = { year = 1946 month = january day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "63. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 121 }
    date           = { year = 1946 month = january day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "64. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 122 }
    date           = { year = 1946 month = january day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "65. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 123 }
    date           = { year = 1946 month = january day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "66. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 124 }
    date           = { year = 1946 month = january day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { name           = "67. Flotiliya Podlodok"
    type           = submarine
    model          = 3
    cost           = 1.5
    id             = { type = 30155 id = 125 }
    date           = { year = 1946 month = january day = 0 }
    days           = 160
    # # days_of_first  = 160
    total_progress = 0
    # # series        = 1
    done           = 0
    progress       = 0
  }
  division_development =
  { type           = naval_bomber
    model          = 1
    date           = { day = 24 month = october year = 1945 }
    cost           = 5
    days           = 180
    # days_of_first  = 180
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30156 id = 103 }
    name           = "4th Naval Bomber Division"
  }
  division_development =
  { type           = naval_bomber
    model          = 1
    date           = { day = 24 month = october year = 1945 }
    cost           = 5
    days           = 180
    # days_of_first  = 180
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30156 id = 104 }
    name           = "5th Naval Bomber Division"
  }
  division_development =
  { type           = naval_bomber
    model          = 1
    date           = { day = 14 month = november year = 1945 }
    cost           = 5
    days           = 180
    # days_of_first  = 180
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30156 id = 105 }
    name           = "6th Naval Bomber Division"
  }
  division_development =
  { type           = naval_bomber
    model          = 1
    date           = { day = 14 month = november year = 1945 }
    cost           = 5
    days           = 180
    # days_of_first  = 180
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30156 id = 106 }
    name           = "7th Naval Bomber Division"
  }
  division_development =
  { type           = naval_bomber
    model          = 1
    date           = { day = 4 month = december year = 1945 }
    cost           = 5
    days           = 180
    # days_of_first  = 180
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30156 id = 107 }
    name           = "8th Naval Bomber Division"
  }
  division_development =
  { type           = naval_bomber
    model          = 1
    date           = { day = 4 month = december year = 1945 }
    cost           = 5
    days           = 180
    # days_of_first  = 180
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30156 id = 108 }
    name           = "9th Naval Bomber Division"
  }
  division_development =
  { type           = naval_bomber
    model          = 1
    date           = { day = 0 month = january year = 1946 }
    cost           = 5
    days           = 180
    # days_of_first  = 180
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30156 id = 109 }
    name           = "10th Naval Bomber Division"
  }
}
