
##############################
# Country definition for USA #
##############################

province =
{ id       = 82
  infra    = { size = 1 current_size = 0.8 }
  air_base = 2
  ic       = { size = 2 current_size = 0 }
}            # Kassel
province =
{ id    = 84
  infra = { size = 1 current_size = 0.75 }
}         # Erfurt
province =
{ id         = 87
  naval_base = { size = 10 current_size = 5 }

  infra      = { size = 1 current_size = 0.7 }
  supplypool = 1000
  oilpool    = 100
  ic         = { size = 1 current_size = 0 }
}              # Bremen
province =
{ id    = 312
  infra = { size = 1 current_size = 0.7 }
  ic    = { size = 4 current_size = 0 }
}         # Nuremberg
province =
{ id         = 313
  infra      = { size = 1 current_size = 0.8 }
  air_base   = 2
  supplypool = 5000
  oilpool    = 500
  ic         = { size = 5 current_size = 0 }
}              # Frankfurt-am-Main
province =
{ id                 = 376
  infra              = { size = 1 current_size = 0.7 }
  metal              = 0
  max_metal          = 0
  rare_materials     = 0
  max_rare_materials = 0
  energy             = 0
  max_energy         = 0
  ic                 = { size = 4 current_size = 0 }
}                      # Munich
province =
{ id       = 462
  air_base = { size = 3 current_size = 3 }
  infra    = { size = 1 current_size = 0.8 }
  ic       = { size = 1 current_size = 0 }
}            # Salzburg
province = { id = 542 supplypool = 1 } # Kiska Island
province = { id = 543 supplypool = 1 } # Amchitka Island
province = { id = 544 supplypool = 1 oilpool = 200 } # Andreanof Islands
province = { id = 545 supplypool = 1 } # Yunaska Island
province =
{ id         = 546
  supplypool = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Umnak Island
province = { id = 547 supplypool = 1 } # Unalaska Island
province = { id = 548 supplypool = 1 } # Unimak Island
province =
{ id         = 549
  supplypool = 1
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
}              # Anchorage
province = { id = 550 supplypool = 1 } # Seward Peninsula
province = { id = 551 supplypool = 1 } # Fairbanks
province = { id = 553 supplypool = 1 oilpool = 2000 } # Juneau
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Plattsburgh
province =
{ id       = 595
  ic       = 2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id            = 600
  anti_air      = 5
  radar_station = { size = 1 current_size = 1 }
  ic            = 3
  air_base      = { size = 10 current_size = 10 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # Boston
province =
{ id            = 602
  anti_air      = 7
  radar_station = { size = 1 current_size = 1 }
  ic            = 4
  air_base      = { size = 10 current_size = 10 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # New York
province =
{ id         = 603
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  ic         = 6
}              # Newark
province =
{ id            = 606
  anti_air      = 7
  radar_station = { size = 1 current_size = 1 }
  ic            = 2
  air_base      = { size = 10 current_size = 10 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # Washington D.C.
province = { id = 608 anti_air = 4 ic = 3 } # Philadelphia
province = { id = 609 ic = 1 } # Harrisburg
province = { id = 613 ic = 3 } # Buffalo
province =
{ id       = 614
  ic       = 3
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Pittsburgh
province = { id = 615 ic = 2 } # Cleveland
province =
{ id       = 616
  ic       = 4
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Detroit
province = { id = 619 ic = 1 } # Indianapolis
province =
{ id       = 620
  anti_air = 5
  ic       = 3
  air_base = { size = 10 current_size = 10 }
}            # Chicago
province =
{ id       = 621
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Milwaukee
province =
{ id            = 633
  anti_air      = 7
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 10 current_size = 10 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # Norfolk
province =
{ id         = 634
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 8 current_size = 8 }
}              # Wilmington
Province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 640
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province = { id = 643 infra = 0.2 nuclear_reactor = 8 } # Asheville
province =
{ id         = 644
  naval_base = { size = 8 current_size = 8 }
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
}              # Charleston
province =
{ id         = 648
  naval_base = { size = 3 current_size = 3 }
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
}              # Jacksonville
province =
{ id         = 651
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Miami
province = { id = 658 supplypool = 1 } # Hawaii
province = { id = 659 supplypool = 1 } # Maui
province = { id = 660 supplypool = 1 } # Kauai
province = { id = 661 supplypool = 1 } # Niihau
province =
{ id            = 662
  supplypool    = 1
  naval_base    = { size = 6 current_size = 6 }
  radar_station = { size = 1 current_size = 1 }
}                 # Midway Island
province =
{ id            = 663
  supplypool    = 1
  oilpool       = 2000
  anti_air      = 5
  radar_station = { size = 4 current_size = 4 }
  air_base      = { size = 10 current_size = 10 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # Pearl Harbour
province =
{ id       = 670
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Atlanta
Province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Memphis
province =
{ id         = 676
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
}              # Mobile
province =
{ id         = 678
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
}              # Biloxi
province =
{ id       = 684
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Little Rock
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # St. Louis
province =
{ id       = 692
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Des Moines
province =
{ id       = 693
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
province =
{ id       = 698
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Bismarck
province =
{ id       = 707
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Denver
Province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Oklahoma City
province =
{ id       = 716
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Houston
province =
{ id            = 723
  rocket_test   = 2
  infra         = 0.2
  radar_station = { size = 1 current_size = 1 }
}                 # Las Cruces
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Salt Lake City
Province =
{ id         = 748
  anti_air   = 1
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 8 current_size = 8 }
}              # Corpus Christi
province =
{ id         = 761
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Diego
province =
{ id            = 762
  anti_air      = 5
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 8 current_size = 8 }
}                 # Los Angeles
province =
{ id       = 763
  air_base = { size = 6 current_size = 6 }
}            # Fresno
province =
{ id       = 764
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id            = 765
  anti_air      = 5
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 10 current_size = 10 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # San Francisco
province =
{ id         = 766
  naval_base = { size = 6 current_size = 6 }
}              # Redding
province =
{ id         = 780
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Seattle
province =
{ id       = 783
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Portland
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Tulsa
province =
{ id            = 889
  anti_air      = 5
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 4 current_size = 4 }
}                 # Colon
province = { id = 895 supplypool = 1 } # Puerto Rico
province =
{ id         = 1178
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
}              # Asahikawa
province =
{ id         = 1179
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
  infra      = { size = 1 current_size = 0.8 }
  ic         = { size = 2 current_size = 0 }
}              # Sapporo
province =
{ id         = 1180
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 5 current_size = 5 }
  ic         = { size = 2 current_size = 0 }
  max_energy = 5
}              # Sendai
province =
{ id       = 1181
  anti_air = 2
  oil      = 0
  max_oil  = 0
  ic       = { size = 2 current_size = 0 }
}            # Akita
province =
{ id = 1182
  ic = { size = 3 current_size = 0 }
}      # Fukushima
province =
{ id = 1183
  ic = { size = 4 current_size = 0 }
}      # Niigata
province =
{ id         = 1184
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  infra      = { size = 1 current_size = 0.7 }
  oilpool    = 500
  supplypool = 5000
  ic         = { size = 13 current_size = 0 }
}              # Tokyo
province =
{ id         = 1185
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  infra      = { size = 0.8 current_size = 0.75 }
  ic         = { size = 4 current_size = 0 }
}              # Nagoya
province =
{ id    = 1186
  infra = { size = 0.8 current_size = 0.7 }
  ic    = { size = 3 current_size = 0 }
}         # Kanazawa
province =
{ id         = 1187
  naval_base = { size = 10 current_size = 8 }
  air_base   = { size = 10 current_size = 8 }
  infra      = { size = 1 current_size = 0.7 }
  ic         = { size = 8 current_size = 0 }
}              # Osaka
province =
{ id         = 1188
  naval_base = { size = 4 current_size = 2 }
  air_base   = { size = 4 current_size = 2 }
  infra      = { size = 1 current_size = 0.5 }
  ic         = { size = 4 current_size = 0 }
}              # Hiroshima
province =
{ id         = 1189
  naval_base = { size = 3 current_size = 2 }
  air_base   = { size = 3 current_size = 2 }
  infra      = { size = 1 current_size = 0.8 }
  ic         = { size = 2 current_size = 0 }
}              # Shikoku
province =
{ id         = 1190
  naval_base = { size = 3 current_size = 2 }
  air_base   = { size = 3 current_size = 2 }
  infra      = { size = 1 current_size = 0.9 }
  ic         = { size = 4 current_size = 0 }
}              # Fukuoka
province =
{ id    = 1191
  infra = { size = 1 current_size = 0.6 }
  ic    = { size = 3 current_size = 0 }
}         # Kagoshima
province =
{ id         = 1192
  naval_base = { size = 2 current_size = 1 }
  air_base   = { size = 2 current_size = 1 }
}              # Amami
province =
{ id         = 1193
  naval_base = { size = 2 current_size = 1 }
  air_base   = { size = 2 current_size = 1 }
  infra      = { size = 1 current_size = 0.75 }
}              # Okinawa
province =
{ id         = 1195
  naval_base = { size = 2 current_size = 1 }
  air_base   = { size = 2 current_size = 1 }
  infra      = { size = 0.8 current_size = 0.7 }
  ic         = { size = 2 current_size = 0 }
}              # Gwangju
province =
{ id         = 1196
  infra      = { size = 0.8 current_size = 0.7 }
  oilpool    = 500
  supplypool = 5000
  ic         = { size = 2 current_size = 0 }
}              # Busan
province =
{ id         = 1199
  naval_base = { size = 6 current_size = 4 }
  air_base   = { size = 6 current_size = 4 }
  infra      = { size = 0.8 current_size = 0.7 }
  ic         = { size = 4 current_size = 0 }
}              # Seoul
province =
{ id         = 1408
  supplypool = 500
  oilpool    = 200
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 4 current_size = 4 }
}              # Attu Island
province =
{ id         = 1599
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
  infra      = { size = 0.6 current_size = 0.5 }
}              # Iwo Jima
province =
{ id         = 1601
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
  anti_air   = 2
  infra      = { size = 0.6 current_size = 0.5 }
}              # Eniwetok
province = { id = 1605 anti_air = 3 } # Majuro
province =
{ id         = 1608
  supplypool = 2500
  oilpool    = 2000
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
  anti_air   = 3
}              # Kwajalein
province =
{ id         = 1613
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  anti_air   = 2
}              # Truk
province =
{ id         = 1619
  supplypool = 500
  oilpool    = 200
  air_base   = { size = 3 current_size = 3 }
  anti_air   = 3
}              # Yap
province =
{ id         = 1621
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
}              # Palau
province =
{ id         = 1624
  supplypool = 1
  anti_air   = 5
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  infra      = { size = 0.6 current_size = 0.5 }
}              # Guam
province =
{ id         = 1627
  supplypool = 2500
  oilpool    = 2000
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 6 current_size = 6 }
  anti_air   = 3
}              # Saipan
province = { id = 1756 supplypool = 1 } # Samoa
province = { id = 1762 supplypool = 1 oilpool = 200 } # Phoenix Island
province = { id = 1764 supplypool = 1 } # Jarvis Island
province = { id = 1765 supplypool = 1 oilpool = 200 } # Palmyra
province = { id = 1766 supplypool = 1 oilpool = 200 } # Johnson Island

#####################
# Country main data #
#####################

country =
{ tag                    = USA
  # Resource Reserves
  energy                 = 5000
  metal                  = 5000
  rare_materials         = 2500
  oil                    = 500
  supplies               = 10000
  money                  = 1000
  manpower               = 1000
  transports             = 2000
  escorts                = 800
  nuke                   = 0
  capital                = 606
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    freedom           = 10
    free_market       = 10
    professional_army = 1
    defense_lobby     = 1
    interventionism   = 5
  }
  SpyInfo                = { country = "USA" NumberOfSpies = 15 }
  nationalprovinces      = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  1408 895  889
			   }
  ownedprovinces         = { 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199 1408 1599
			     1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1612 1613 1615 1616 1617 1618 1619 1620 1621 1624 1625 1626 1627
			     1756 1762 1764 1765 1766 1784 1785 1786 312  313  375  376  462  542  543  544  545  546  547  548  549  550  551  553
			     582  583  592  593  594  595  596  597  598  599  600  601  602  603  604  605  606  607  608  609  610  611  612  613
			     614  615  616  617  618  619  620  621  622  623  624  625  626  627  628  629  630  631  632  633  634  635  636  637
			     638  639  640  641  642  643  644  645  646  647  648  649  650  651  658  659  660  661  662  663  669  670  671  672
			     673  674  675  676  677  678  679  680  681  682  683  684  685  686  687  688  689  690  691  692  693  694  695  696
			     697  698  699  700  701  702  703  704  705  706  707  708  709  710  711  712  713  714  715  716  717  718  719  720
			     721  722  723  724  725  726  727  728  729  730  731  732  733  734  735  736  746  748  761  762  763  764  765  766
			     767  768  769  770  771  772  773  774  775  776  777  778  779  780  781  782  783  784  785  786  787  788  789  790
			     791  792  793  82   83   84   87   889  895
			   }
  controlledprovinces    = { 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199 1408 1599
			     1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1612 1613 1615 1616 1617 1618 1619 1620 1621 1624 1625 1626 1627
			     1756 1762 1764 1765 1766 1784 1785 1786 312  313  375  376  462  542  543  544  545  546  547  548  549  550  551  553
			     582  583  592  593  594  595  596  597  598  599  600  601  602  603  604  605  606  607  608  609  610  611  612  613
			     614  615  616  617  618  619  620  621  622  623  624  625  626  627  628  629  630  631  632  633  634  635  636  637
			     638  639  640  641  642  643  644  645  646  647  648  649  650  651  658  659  660  661  662  663  669  670  671  672
			     673  674  675  676  677  678  679  680  681  682  683  684  685  686  687  688  689  690  691  692  693  694  695  696
			     697  698  699  700  701  702  703  704  705  706  707  708  709  710  711  712  713  714  715  716  717  718  719  720
			     721  722  723  724  725  726  727  728  729  730  731  732  733  734  735  736  746  748  761  762  763  764  765  766
			     767  768  769  770  771  772  773  774  775  776  777  778  779  780  781  782  783  784  785  786  787  788  789  790
			     791  792  793  82   83   84   87   889  895
			   }
  # USA 1939 techs
  # ######################
  techapps               = { 1010  1020  1030  1040  1050  1070  1080  1090  1100  1110  1120  1130  1140  1150  1160  1170  1180  1190  1200  1210
			     12100 12110 12120 1220  1230  1240  1250  1260  1270  1280  1310  1320  1330  1340  1350  1360  14000 14010 14020
			     14030 15030 15500 2010  2020  2030  2040  2050  2070  2080  2090  2100  2110  2150  2160  2170  2180
			     2190  2200  2220  2230  2240  2260  2290  2300  2310  2320  2330  2340  2350  2370  2380  2400  2410  2420  2430  2450
			     2460  2470  2480  2510  2520  2530  3010  3020  3030  3040  3050  3070  3080  3090  3100  3110  3130  3140  3150  3160
			     3170  3190  3200  3210  3220  3230  3250  3260  3270  3280  3290  3320  3330  3340  3350  3360  3370  3400  3410  3420
			     3430  4010  4020  4030  4040  4050  4060  4070  4080  4090  4100  4110  4120  4130  4140  4150  4160  4170  4180  4190
			     4200  4210  4220  4230  4240  4250  4260  4270  4280  5010  5020  5030  5050  5060  5070  5080  5090  5100  5110  5120
			     5130  5140  5150  5160  5170  5180  5190  5200  5210  5310  5320  5330  5340  5350  5360  5370  5380  5390  5400  5410
			     5420  5430  5440  5450  5470  5480  5490  5500  5510  5520  5530  5540  5550  5560  5570  6010  6020  6040  6050  6060
			     6070  6080  6090  7140  7150  7160  7170  7180  7190  8010  8020  8030  8040  8050  8060  8090  8100  8110  8130  8140
			     8160  8180  8230  8240  8250  8310  8320  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130
			     9140  9150  9160  9170  9180  9190  9200  9210  9220  9230  9240  9250  9260  9270  9280  9290  9300  9310  9320  9330
			     9350  9360  9370  9380  9390  9400  9430  9440  9450  9460  2060  2270  2360  2490  2540  5220  5230  8170
			     8270  8350  9340  9410
			   }
  inventions = { 8000 8001 8010 8011 }
  diplomacy =
  { relation =
    { tag        = ARG
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = AST access = yes }
    relation = { tag = BEL value = 75 }
    relation =
    { tag        = BOL
      value      = 85
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = BRA
      value      = 120
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = CHL
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = COL
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = COS
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = CUB
      value      = 200
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = DEN value = 75 }
    relation =
    { tag        = DOM
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = ECU
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = ENG value = 150 access = yes }
    relation = { tag = FRA access = yes }
    relation =
    { tag        = GUA
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = HAI
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = HOL value = 70 access = yes }
    relation =
    { tag        = HON
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = IRE value = 75 }
    relation = { tag = IRQ value = 120 }
    relation = { tag = LIB value = 200 access = yes }
    relation =
    { tag        = MEX
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = NEP value = 100 }
    relation =
    { tag        = NIC
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = NOR value = 75 }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation =
    { tag        = PAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = PAR
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = PHI value = 200 access = yes }
    relation =
    { tag        = PRU
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = SAF value = 125 }
    relation =
    { tag        = SCH
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation =
    { tag        = SAL
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = SWE value = 75 }
    relation =
    { tag        = URU
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = VEN
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = YEM value = 100 }
    relation = { tag = ITA access = yes }
    relation = { tag = ICL value = 200 access = yes }
    relation = { tag = TUR access = yes }
  }
  nukedate               = { year = 1945 month = june day = 1 hour = 0 }
  headofstate            = { type = 9 id = 6034 }
  headofgovernment       = { type = 9 id = 6046 }
  foreignminister        = { type = 9 id = 6063 }
  armamentminister       = { type = 9 id = 6091 }
  ministerofsecurity     = { type = 9 id = 6005 }
  ministerofintelligence = { type = 9 id = 6126 }
  chiefofstaff           = { type = 9 id = 6136 }
  chiefofarmy            = { type = 9 id = 6144 }
  chiefofnavy            = { type = 9 id = 6163 }
  chiefofair             = { type = 9 id = 6167 }
  dormant_ministers      = { 6036 6003 6153 6067 6033 6088 6060 6007 6008 6096 6176 6009 6162 6158 6010 6004 6114 6001 }
  landunit =
  { id       = { type = 30301 id = 1 }
    name     = "II Corps"
    location = 86
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 1 }
      name          = "88th Infantry Division"
      experience    = 64
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 2 }
      name          = "34th Infantry Division"
      experience    = 68
      extra         = tank_destroyer
      brigade_model = 2
    }
    division =
    { type       = motorized
      model      = 2
      id         = { type = 30304 id = 3 }
      name       = "91st Infantry Division"
      experience = 67
    }
  }
  landunit =
  { id       = { type = 30301 id = 2 }
    name     = "9th Army HQ"
    location = 82
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 4 }
      name          = "9th Army HQ"
      extra         = anti_air
      brigade_model = 0
      experience    = 70
    }
  }
  landunit =
  { id       = { type = 30301 id = 3 }
    name     = "1st Army HQ"
    location = 87
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 5 }
      name          = "1st Army HQ"
      extra         = anti_air
      brigade_model = 0
      experience    = 46
    }
  }
  landunit =
  { id       = { type = 30301 id = 4 }
    name     = "3rd Army HQ"
    location = 313
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 6 }
      name          = "3rd Army HQ"
      extra         = police
      brigade_model = 0
      experience    = 49
    }
  }
  landunit =
  { id       = { type = 30301 id = 5 }
    name     = "7th Army HQ"
    location = 81
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 7 }
      name          = "7th Army HQ"
      extra         = police
      brigade_model = 0
      experience    = 60
    }
  }
  landunit =
  { id       = { type = 30301 id = 6 }
    name     = "XVI Corps"
    location = 82
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 8 }
      name          = "29th Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 75
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 9 }
      name          = "75th Infantry Division"
      extra         = artillery
      brigade_model = 6
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 10 }
      name          = "79th Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 85
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 11 }
      name          = "95th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 10
    }
  }
  landunit =
  { id       = { type = 30301 id = 7 }
    name     = "XIII Corps"
    location = 313
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 12 }
      name          = "39th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 84
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 13 }
      name          = "76th Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 55
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 14 }
      name          = "84th Infantry Division"
      extra         = anti_tank
      brigade_model = 3
      experience    = 55
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 15 }
      name          = "35th Infantry Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 55
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 16 }
      name          = "83rd Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 65
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 17 }
      name          = "102nd Infantry Division"
      extra         = anti_air
      brigade_model = 2
      experience    = 75
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 18 }
      name          = "5th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 3
      experience    = 54
    }
  }
  landunit =
  { id       = { type = 30301 id = 8 }
    name     = "XIX Corps"
    location = 87
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 19 }
      name          = "2nd Armoured Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 75
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 20 }
      name          = "8th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 3
      experience    = 82
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 21 }
      name          = "3rd Armoured Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 86
    }
  }
  landunit =
  { id       = { type = 30301 id = 9 }
    name     = "VII Corps"
    location = 462
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 22 }
      name          = "9th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 90
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 23 }
      name          = "104th Infantry Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 85
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 24 }
      name          = "69th Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 50
    }
  }
  landunit =
  { id       = { type = 30301 id = 10 }
    name     = "III Corps"
    location = 83
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 25 }
      name          = "4th Infantry Division"
      extra         = anti_air
      brigade_model = 2
      experience    = 85
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 26 }
      name          = "99th Infantry Division"
      extra         = artillery
      brigade_model = 6
      experience    = 80
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30304 id = 27 }
      name          = "14th Armoured Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 95
    }
  }
  landunit =
  { id       = { type = 30301 id = 11 }
    name     = "V Corps"
    location = 312
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 28 }
      name          = "97th Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 54
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 29 }
      name          = "78th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 73
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30304 id = 30 }
      name          = "16th Armoured Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 84
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 31 }
      name          = "9th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 3
      experience    = 80
    }
  }
  landunit =
  { id       = { type = 30301 id = 12 }
    name     = "VIII Corps"
    location = 375
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 32 }
      name          = "70th Infantry Division"
      extra         = anti_tank
      brigade_model = 3
      experience    = 90
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 33 }
      name          = "87th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 34 }
      name          = "89th Infantry Division"
      extra         = anti_tank
      brigade_model = 3
      experience    = 80
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 35 }
      name          = "6th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 80
    }
  }
  landunit =
  { id       = { type = 30301 id = 13 }
    name     = "XII Corps"
    location = 81
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 36 }
      name          = "5th Infantry Division"
      experience    = 80
      extra         = engineer
      brigade_model = 0
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 37 }
      name          = "26th Infantry Division"
      experience    = 80
      extra         = rocket_artillery
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 38 }
      name          = "90th Infantry Division"
      experience    = 75
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30304 id = 39 }
      name          = "4th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 80
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 40 }
      name          = "11th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 76
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 41 }
      name          = "1st Infantry Division"
      extra         = artillery
      brigade_model = 6
      experience    = 80
    }
  }
  landunit =
  { id       = { type = 30301 id = 14 }
    name     = "XX Corps"
    location = 376
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 42 }
      name          = "65th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 68
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 43 }
      name          = "71st Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 69
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 44 }
      name          = "2nd Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 90
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 45 }
      name          = "80th Infantry Division"
      extra         = anti_tank
      brigade_model = 3
      experience    = 85
    }
    division =
    { type          = armor
      model         = 3
      id            = { type = 30304 id = 46 }
      name          = "13th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 75
    }
  }
  landunit =
  { id       = { type = 30301 id = 15 }
    name     = "XXI Corps"
    location = 82
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 47 }
      name          = "36th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 48 }
      name          = "63rd Infantry Division"
      extra         = rocket_artillery
      brigade_model = 1
      experience    = 70
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 49 }
      name          = "12th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 76
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 30304 id = 50 }
      name          = "101st Infantry Division"
      experience    = 80
      extra         = anti_tank
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 30301 id = 16 }
    name     = "XV Corps"
    location = 79
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 51 }
      name          = "3rd Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 52 }
      name          = "42nd Infantry Division"
      extra         = anti_air
      brigade_model = 2
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 53 }
      name          = "45th Infantry Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 75
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 54 }
      name          = "86th Infantry Division"
      extra         = rocket_artillery
      brigade_model = 1
      experience    = 85
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 55 }
      name          = "20th Armoured Division"
      extra         = tank_destroyer
      brigade_model = 2
      experience    = 59
    }
  }
  landunit =
  { id       = { type = 30301 id = 17 }
    name     = "VI Corps"
    location = 84
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 56 }
      name          = "44th Infantry Divisions"
      experience    = 80
      extra         = rocket_artillery
      brigade_model = 1
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 57 }
      name          = "100th Infantry Division"
      experience    = 85
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 58 }
      name          = "103rd Infantry Division"
      experience    = 86
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 30301 id = 18 }
    name     = "XVII Airborne Corps"
    location = 531
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 59 }
      name          = "8th Infantry Division"
      experience    = 60
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 30304 id = 60 }
      name          = "13th Airborne Division"
      experience    = 80
      extra         = anti_tank
      brigade_model = 3
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 30304 id = 61 }
      name          = "7th Armoured Division"
      experience    = 75
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 30304 id = 62 }
      name          = "82nd Airborne Division"
      experience    = 80
      extra         = artillery
      brigade_model = 6
    }
  }
  landunit =
  { id       = { type = 30301 id = 19 }
    name     = "15th Army HQ"
    location = 371
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 63 }
      name          = "15th Army HQ"
      extra         = anti_air
      brigade_model = 2
      experience    = 70
    }
  }
  landunit =
  { id       = { type = 30301 id = 20 }
    name     = "XXII Corps"
    location = 371
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 64 }
      name          = "94th Infantry Division"
      extra         = tank_destroyer
      brigade_model = 3
      experience    = 75
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 30304 id = 65 }
      name          = "17th Airborne Division"
      extra         = anti_tank
      brigade_model = 3
      experience    = 76
    }
    division =
    { type          = bergsjaeger
      model         = 3
      id            = { type = 30304 id = 176 }
      name          = "10th Mountain Division"
      extra         = artillery
      brigade_model = 6
      experience    = 76
    }
  }
  landunit =
  { id       = { type = 30301 id = 21 }
    name     = "XXIII Corps"
    location = 378
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 66 }
      name          = "28th Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 72
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 67 }
      name          = "66th Infantry Division"
      extra         = sp_artillery
      brigade_model = 2
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 68 }
      name          = "106th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
  }
  landunit =
  { id       = { type = 30301 id = 22 }
    name     = "6th Army HQ"
    location = 1198
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 69 }
      name          = "6th Army HQ"
      extra         = anti_air
      brigade_model = 0
      experience    = 59
    }
  }
  landunit =
  { id       = { type = 30301 id = 23 }
    name     = "8th Army HQ"
    location = 1196
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 70 }
      name          = "8th Army HQ"
      extra         = police
      brigade_model = 0
      experience    = 75
    }
  }
  landunit =
  { id       = { type = 30301 id = 24 }
    name     = "10th Army HQ"
    location = 1184
    division =
    { type          = hq
      model         = 2
      id            = { type = 30304 id = 71 }
      name          = "10th Army HQ"
      extra         = anti_air
      brigade_model = 0
      experience    = 75
    }
  }
  landunit =
  { id       = { type = 30301 id = 25 }
    name     = "V amphibious Corps"
    location = 1198
    division =
    { type          = marine
      model         = 3
      id            = { type = 30304 id = 72 }
      name          = "2nd Marine Division"
      extra         = engineer
      brigade_model = 0
      experience    = 59
    }
    division =
    { type          = marine
      model         = 3
      id            = { type = 30304 id = 73 }
      name          = "5th Marine Division"
      extra         = engineer
      brigade_model = 0
      experience    = 59
    }
    division =
    { type          = marine
      model         = 3
      id            = { type = 30304 id = 74 }
      name          = "3rd Marine Division"
      extra         = engineer
      brigade_model = 0
      experience    = 59
    }
  }
  landunit =
  { id       = { type = 30301 id = 26 }
    name     = "III amphibious Corps"
    location = 1197
    division =
    { type          = marine
      model         = 3
      id            = { type = 30304 id = 75 }
      name          = "4th Marine Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
    division =
    { type          = marine
      model         = 3
      id            = { type = 30304 id = 76 }
      name          = "6th Marine Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
    division =
    { type          = marine
      model         = 3
      id            = { type = 30304 id = 77 }
      name          = "1st Marine Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
  }
  landunit =
  { id       = { type = 30301 id = 27 }
    name     = "XXIV Corps"
    location = 1187
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 78 }
      name          = "96th Infantry Division"
      extra         = artillery
      brigade_model = 6
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 79 }
      name          = "7th Infantry Division"
      extra         = anti_air
      brigade_model = 2
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 80 }
      name          = "27th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 80
    }
  }
  landunit =
  { id       = { type = 30301 id = 28 }
    name     = "X Corps"
    location = 1184
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 81 }
      name          = "24th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 82 }
      name          = "31st Infantry Division"
      extra         = artillery
      brigade_model = 5
      experience    = 75
    }
  }
  landunit =
  { id       = { type = 30301 id = 29 }
    name     = "I Corps"
    location = 1195
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 83 }
      name          = "25th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 85
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 84 }
      name          = "41st Infantry Division"
      extra         = artillery
      brigade_model = 6
      experience    = 85
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 85 }
      name          = "33rd Infantry Division"
      extra         = anti_air
      brigade_model = 2
      experience    = 85
    }
  }
  landunit =
  { id       = { type = 30301 id = 30 }
    name     = "XI Corps"
    location = 1199
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 86 }
      name          = "6th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 65
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 87 }
      name          = "43rd Infantry Division"
      extra         = artillery
      brigade_model = 6
      experience    = 65
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 88 }
      name          = "Americal Infantry Division"
      extra         = anti_air
      brigade_model = 2
      experience    = 65
    }
  }
  landunit =
  { id       = { type = 30301 id = 31 }
    name     = "IX Corps"
    location = 1196
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 89 }
      name          = "77th Infantry Division"
      extra         = artillery
      brigade_model = 5
      experience    = 80
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 90 }
      name          = "98th Infantry Division"
      extra         = artillery
      brigade_model = 5
      experience    = 80
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 30304 id = 91 }
      name          = "11th Airbourne Division"
      experience    = 80
      extra         = artillery
      brigade_model = 6
    }
  }
  landunit =
  { id       = { type = 30301 id = 32 }
    name     = "XIV Corps"
    location = 1196
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 92 }
      name          = "40th Infantry Division"
      extra         = engineer
      brigade_model = 0
      experience    = 75
    }
    division =
    { type          = motorized
      model         = 2
      id            = { type = 30304 id = 93 }
      name          = "37th Infantry Division"
      extra         = artillery
      brigade_model = 5
      experience    = 75
    }
  }
  landunit =
  { id       = { type = 30301 id = 33 }
    name     = "Panama Canal Force"
    location = 889
    division =
    { id            = { type = 30304 id = 94 }
      name          = "Panama Canal Garrison"
      type          = garrison
      locked        = yes
      extra         = artillery
      brigade_model = 5
      model         = 2
    }
  }
  landunit =
  { location = 606
    id       = { type = 30301 id = 34 }
    name     = "East Coast HQ"
    division =
    { experience = 35
      id         = { type = 30304 id = 95 }
      name       = "East Coast HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 606
    id       = { type = 30301 id = 35 }
    name     = "East Coast Reserves"
    division =
    { experience    = 35
      id            = { type = 30304 id = 96 }
      name          = "97th Infantry Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30304 id = 97 }
      name          = "92nd Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30304 id = 98 }
      name          = "89th Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30304 id = 99 }
      name          = "87th Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 100 }
      name       = "86th Infantry Division"
      strength   = 100
      type       = mechanized
      model      = 2
      extra      = engineer
    }
  }
  landunit =
  { location = 765
    id       = { type = 30301 id = 36 }
    name     = "West Coast HQ"
    division =
    { experience = 35
      id         = { type = 30304 id = 101 }
      name       = "West Coast HQ"
      type       = hq
      model      = 2
      strength   = 100
    }
  }
  landunit =
  { location = 765
    id       = { type = 30301 id = 37 }
    name     = "West Coast Reserves"
    division =
    { experience    = 35
      id            = { type = 30304 id = 102 }
      name          = "36th Infantry Division"
      strength      = 100
      type          = mechanized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30304 id = 103 }
      name          = "39th Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30304 id = 104 }
      name          = "21st Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30304 id = 105 }
      name          = "22nd Infantry Division"
      strength      = 100
      type          = motorized
      model         = 2
      extra         = sp_artillery
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 106 }
      name       = "76th Infantry Division"
      strength   = 100
      type       = mechanized
      model      = 2
      extra      = engineer
    }
  }
  landunit =
  { location = 583
    id       = { type = 30301 id = 38 }
    name     = "ME Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 107 }
      name       = "1st ME National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 108 }
      name       = "2nd ME National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 109 }
      name       = "3rd ME National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 601
    id       = { type = 30301 id = 39 }
    name     = "CT Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 110 }
      name       = "1st CT National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 111 }
      name       = "2nd CT National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 112 }
      name       = "3rd CT National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 605
    id       = { type = 30301 id = 40 }
    name     = "DE Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 113 }
      name       = "1st DE National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 114 }
      name       = "2nd DE National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 115 }
      name       = "3rd DE National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 633
    id       = { type = 30301 id = 41 }
    name     = "VA Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 116 }
      name       = "1st VA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 117 }
      name       = "2nd VA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 118 }
      name       = "3rd VA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 644
    id       = { type = 30301 id = 42 }
    name     = "SC Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 119 }
      name       = "1st SC National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 120 }
      name       = "2nd SC National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 121 }
      name       = "3rd SC National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 646
    id       = { type = 30301 id = 43 }
    name     = "GA Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 122 }
      name       = "1st GA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 123 }
      name       = "2nd GA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 124 }
      name       = "3rd GA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 648
    id       = { type = 30301 id = 44 }
    name     = "FL Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 125 }
      name       = "1st FL National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 126 }
      name       = "2nd FL National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 127 }
      name       = "3rd FL National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 680
    id       = { type = 30301 id = 45 }
    name     = "LA Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 128 }
      name       = "1st LA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 129 }
      name       = "2nd LA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 130 }
      name       = "3rd LA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 716
    id       = { type = 30301 id = 46 }
    name     = "TX Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 131 }
      name       = "1st TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 132 }
      name       = "2nd TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 133 }
      name       = "3rd TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 748
    id       = { type = 30301 id = 47 }
    name     = "TX Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 134 }
      name       = "4th TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 135 }
      name       = "5th TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 136 }
      name       = "6th TX National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 762
    id       = { type = 30301 id = 48 }
    name     = "CA Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 137 }
      name       = "1st CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 138 }
      name       = "2nd CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 139 }
      name       = "3rd CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 765
    id       = { type = 30301 id = 49 }
    name     = "CA Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 140 }
      name       = "4th CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 141 }
      name       = "5th CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 142 }
      name       = "6th CA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 783
    id       = { type = 30301 id = 50 }
    name     = "OR Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 143 }
      name       = "1st OR National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 144 }
      name       = "2nd OR National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 145 }
      name       = "3rd OR National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 782
    id       = { type = 30301 id = 51 }
    name     = "WA Garrison"
    division =
    { experience = 35
      id         = { type = 30304 id = 146 }
      name       = "1st WA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 147 }
      name       = "2nd WA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 148 }
      name       = "3rd WA National Guard Division"
      strength   = 100
      type       = garrison
      model      = 2
    }
  }
  landunit =
  { location = 889
    id       = { type = 30301 id = 52 }
    name     = "Channel Force"
    division =
    { experience    = 35
      id            = { type = 30304 id = 149 }
      name          = "1/Channel Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = anti_air
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30304 id = 150 }
      name          = "2/Channel Force"
      strength      = 100
      type          = garrison
      model         = 2
      extra         = artillery
      brigade_model = 4
    }
    division =
    { experience = 35
      id         = { type = 30304 id = 151 }
      name       = "3/Channel Force"
      strength   = 100
      type       = garrison
      model      = 2
      extra      = engineer
    }
  }
  # ######id up to 286
  # ########################
  # ##US Naval OOB - 1944###
  # ########################
  # Task Group 58.1#
  navalunit =
  { id       = { type = 30302 id = 1 }
    name     = "Task Group 58.1"
    location = 1185
    base     = 1185
    division =
    {
      id            = { type = 30305 id = 1 }
      name          = "USS Hornet"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 2 }
      name          = "USS Yorktown"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id         = { type = 30305 id = 3 }
      name       = "USS Independence"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    {
      id         = { type = 30305 id = 400 }
      name       = "USS Belleau Wood"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 4 }
      name       = "USS Baltimore"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 5 }
      name       = "USS Boston"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 6 }
      name       = "USS Canberra"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 7 }
      name       = "USS Oakland"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 8 }
      name       = "1st Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 9 }
      name       = "2nd Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 10 }
      name       = "3rd Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.2#
  navalunit =
  { id       = { type = 30302 id = 2 }
    name     = "Task Group 58.2"
    location = 1408
    base     = 1408
    division =
    {
      id            = { type = 30305 id = 11 }
      name          = "USS Bunker Hill"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 12 }
      name          = "USS Wasp"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id         = { type = 30305 id = 13 }
      name       = "USS Cowpens"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    {
      id         = { type = 30305 id = 401 }
      name       = "USS Monterey"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 14 }
      name       = "USS Biloxi"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 15 }
      name       = "USS Mobile"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 16 }
      name       = "USS San Juan"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 17 }
      name       = "USS Santa Fe"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 18 }
      name       = "4th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 19 }
      name       = "5th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 20 }
      name       = "6th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.3#
  navalunit =
  { id       = { type = 30302 id = 3 }
    name     = "Task Group 58.3"
    location = 1193
    base     = 1193
    division =
    {
      id            = { type = 30305 id = 21 }
      name          = "USS Enterprise"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 2
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 22 }
      name          = "USS Lexington"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id         = { type = 30305 id = 23 }
      name       = "USS Langley"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    {
      id         = { type = 30305 id = 402 }
      name       = "USS Cabot"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 24 }
      name       = "USS Indianapolis"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 25 }
      name       = "USS Birmingham"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 26 }
      name       = "USS Cleveland"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 27 }
      name       = "USS Montpelier"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 28 }
      name       = "USS Reno"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 29 }
      name       = "7th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 30 }
      name       = "8th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 31 }
      name       = "9th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.4#
  navalunit =
  { id       = { type = 30302 id = 4 }
    name     = "Task Group 58.4"
    location = 1599
    base     = 1599
    division =
    {
      id            = { type = 30305 id = 32 }
      name          = "USS Essex"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id         = { type = 30305 id = 33 }
      name       = "USS Bataan"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    {
      id         = { type = 30305 id = 403 }
      name       = "USS San Jacinto"
      type       = escort_carrier
      model      = 1
      experience = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 34 }
      name       = "USS Houston"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 35 }
      name       = "USS Miami"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 36 }
      name       = "USS San Diego"
      type       = light_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 37 }
      name       = "USS Vincennes"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 38 }
      name       = "10th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 39 }
      name       = "11th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 40 }
      name       = "12th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Task Group 58.5#
  navalunit =
  { id       = { type = 30302 id = 5 }
    name     = "Task Group 58.5"
    location = 1187
    base     = 1187
    division =
    { experience = 35
      id         = { type = 30305 id = 41 }
      name       = "USS California"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 42 }
      name       = "USS Colorado"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 43 }
      name       = "USS Idaho"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 44 }
      name       = "USS Maryland"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 45 }
      name       = "USS New Mexico"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 46 }
      name       = "USS Pennsylvania"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 47 }
      name       = "USS Tennessee"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 48 }
      name       = "USS Honolulu"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 49 }
      name       = "16th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 50 }
      name       = "17th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 51 }
      name       = "18th Destroyer Division"
      type       = destroyer
      model      = 1
    }
  }
  # Task Group 58.6#
  navalunit =
  { id       = { type = 30302 id = 6 }
    name     = "Task Group 58.6"
    location = 1624
    base     = 1624
    division =
    { experience = 35
      id         = { type = 30305 id = 52 }
      name       = "USS Louisville"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 53 }
      name       = "USS St. Louis"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 54 }
      name       = "19th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 55 }
      name       = "20th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 56 }
      name       = "21st Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 57 }
      name       = "22nd Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 58 }
      name       = "23rd Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 59 }
      name       = "24th Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 60 }
      name       = "1st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 61 }
      name       = "2nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 62 }
      name       = "3rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 63 }
      name       = "4th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 64 }
      name       = "5th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 65 }
      name       = "6th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 66 }
      name       = "50th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 67 }
      name       = "51st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 68 }
      name       = "52nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 69 }
      name       = "53rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 70 }
      name       = "54th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 71 }
      name       = "55th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 72 }
      name       = "56th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 73 }
      name       = "57th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 74 }
      name       = "58th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 75 }
      name       = "59th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 76 }
      name       = "60th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 77 }
      name       = "61st Transport Division"
      type       = transport
    }
  }
  # Task Group 58.7#
  navalunit =
  { id       = { type = 30302 id = 7 }
    name     = "Task Group 58.7"
    location = 1184
    base     = 1184
    division =
    { experience = 35
      id         = { type = 30305 id = 78 }
      name       = "USS Alabama"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 79 }
      name       = "USS Indiana"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 80 }
      name       = "USS Iowa"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 81 }
      name       = "USS New Jersey"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 82 }
      name       = "USS North Carolina"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 83 }
      name       = "USS South Dakota"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 84 }
      name       = "USS Washington"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 85 }
      name       = "USS Minneapolis"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 86 }
      name       = "USS New Orleans"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 87 }
      name       = "USS San Francisco"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 88 }
      name       = "USS Wichita"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 89 }
      name       = "13th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 90 }
      name       = "14th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 91 }
      name       = "15th Destroyer Division"
      type       = destroyer
      model      = 2
    }
  }
  # Southwest Pacific Squadron#
  navalunit =
  { id       = { type = 30302 id = 8 }
    name     = "Southwest Pacific Squadron"
    location = 1665
    base     = 1665
    division =
    { experience = 35
      id         = { type = 30305 id = 92 }
      name       = "USS Boise"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 93 }
      name       = "USS Nashville"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 94 }
      name       = "USS Phoenix"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 95 }
      name       = "25th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 96 }
      name       = "26th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 97 }
      name       = "27th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 98 }
      name       = "28th Destroyer Division"
      type       = destroyer
      model      = 1
    }
  }
  # Southwest Pacific Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 9 }
    name     = "Southwest Pacific Transport Squadron"
    location = 1665
    base     = 1665
    division =
    { experience = 35
      id         = { type = 30305 id = 99 }
      name       = "29th Destroyer Division"
      type       = destroyer
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 100 }
      name       = "30th Destroyer Division"
      type       = destroyer
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 101 }
      name       = "31st Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 102 }
      name       = "7th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 103 }
      name       = "8th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 104 }
      name       = "9th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 105 }
      name       = "10th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 106 }
      name       = "11th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 107 }
      name       = "12th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 108 }
      name       = "62nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 109 }
      name       = "63rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 110 }
      name       = "64th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 111 }
      name       = "65th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 112 }
      name       = "66th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 113 }
      name       = "67th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 114 }
      name       = "68th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 115 }
      name       = "69th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 116 }
      name       = "70th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 117 }
      name       = "71st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 118 }
      name       = "72nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 119 }
      name       = "73rd Transport Division"
      type       = transport
    }
  }
  # South Pacific Squadron#
  navalunit =
  { id       = { type = 30302 id = 10 }
    name     = "South Pacific Squadron"
    location = 1685
    base     = 1685
    division =
    {
      id            = { type = 30305 id = 120 }
      name          = "USS Saratoga"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 1
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 121 }
      name       = "32nd Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  # South Pacific Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 11 }
    name     = "South Pacific Transport Squadron"
    location = 1685
    base     = 1685
    division =
    { experience = 35
      id         = { type = 30305 id = 122 }
      name       = "33rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 123 }
      name       = "13th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 124 }
      name       = "14th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 125 }
      name       = "74th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 126 }
      name       = "75th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 127 }
      name       = "76th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 128 }
      name       = "77th Transport Division"
      type       = transport
    }
  }
  # North Pacific Squadron#
  navalunit =
  { id       = { type = 30302 id = 12 }
    name     = "North Pacific Squadron"
    location = 549
    base     = 549
    division =
    { experience = 35
      id         = { type = 30305 id = 129 }
      name       = "USS Chester"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 130 }
      name       = "USS Pensacola"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 131 }
      name       = "USS Salt Lake City"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 132 }
      name       = "USS Concord"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 133 }
      name       = "USS Detroit"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 134 }
      name       = "USS Richmond"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 135 }
      name       = "USS Trenton"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 136 }
      name       = "34th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 137 }
      name       = "35th Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  # North Pacific Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 13 }
    name     = "North Pacific Transport Squadron"
    location = 1184
    base     = 1184
    division =
    { experience = 35
      id         = { type = 30305 id = 138 }
      name       = "36th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 139 }
      name       = "15th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 140 }
      name       = "16th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 141 }
      name       = "78th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 142 }
      name       = "79th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 143 }
      name       = "80th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 144 }
      name       = "81st Transport Division"
      type       = transport
    }
  }
  # 3rd Fleet#
  navalunit =
  { id       = { type = 30302 id = 14 }
    name     = "3rd Fleet"
    location = 663
    base     = 663
    division =
    {
      id            = { type = 30305 id = 145 }
      name          = "USS Franklin"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 146 }
      name          = "USS Hancock"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 147 }
      name          = "USS Intrepid"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 148 }
      name          = "USS Ticonderoga"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 149 }
      name       = "USS Massachusetts"
      type       = battleship
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 150 }
      name       = "USS Denver"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 151 }
      name       = "37th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 152 }
      name       = "38th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 153 }
      name       = "39th Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  # 3rd Fleet Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 15 }
    name     = "3rd Fleet Transport Squadron"
    location = 1187
    base     = 1187
    division =
    { experience = 35
      id         = { type = 30305 id = 154 }
      name       = "40th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 155 }
      name       = "17th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 156 }
      name       = "18th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 157 }
      name       = "19th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 158 }
      name       = "20th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 159 }
      name       = "82nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 160 }
      name       = "83rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 161 }
      name       = "84th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 162 }
      name       = "85th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 163 }
      name       = "86th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 164 }
      name       = "87th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 165 }
      name       = "88th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 166 }
      name       = "89th Transport Division"
      type       = transport
    }
  }
  # San Francisco Squadron#
  navalunit =
  { id       = { type = 30302 id = 16 }
    name     = "San Francisco Squadron"
    location = 762
    base     = 762
    division =
    { experience    = 35
      id            = { type = 30305 id = 167 }
      name          = "USS Ranger"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 5
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 168 }
      name       = "USS Missouri"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 169 }
      name       = "USS Wisconsin"
      type       = battleship
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 170 }
      name       = "USS Alaska"
      type       = battlecruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 171 }
      name       = "USS Mississippi"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 172 }
      name       = "USS West Virginia"
      type       = battleship
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 173 }
      name       = "USS Portland"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 174 }
      name       = "USS Columbia"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 175 }
      name       = "USS Astoria"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 176 }
      name       = "USS Pasadena"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 177 }
      name       = "USS Vicksburg"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 178 }
      name       = "41st Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 179 }
      name       = "60th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 180 }
      name       = "61st Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 181 }
      name       = "62nd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 182 }
      name       = "63rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 183 }
      name       = "64th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 184 }
      name       = "65th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 185 }
      name       = "66th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 186 }
      name       = "67th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 187 }
      name       = "68th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 188 }
      name       = "69th Destroyer Division"
      type       = destroyer
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 189 }
      name       = "70th Destroyer Division"
      type       = destroyer
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 190 }
      name       = "71st Destroyer Division"
      type       = destroyer
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 191 }
      name       = "20th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 192 }
      name       = "21st Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 193 }
      name       = "22nd Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 194 }
      name       = "23rd Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 195 }
      name       = "24th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 196 }
      name       = "25th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 197 }
      name       = "26th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 198 }
      name       = "27th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 199 }
      name       = "28th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 200 }
      name       = "29th Submarine Division"
      type       = submarine
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 201 }
      name       = "30th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 1st West Coast Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 17 }
    name     = "1st West Coast Transport Squadron"
    location = 762
    base     = 762
    division =
    { experience = 35
      id         = { type = 30305 id = 202 }
      name       = "21st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 203 }
      name       = "22nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 204 }
      name       = "90th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 205 }
      name       = "91st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 206 }
      name       = "92nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 207 }
      name       = "93rd Transport Division"
      type       = transport
    }
  }
  # Los Angeles Squadron#
  navalunit =
  { id       = { type = 30302 id = 18 }
    name     = "Los Angeles Squadron"
    location = 766
    base     = 766
    division =
    { experience = 35
      id         = { type = 30305 id = 208 }
      name       = "USS Nevada"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 209 }
      name       = "USS Marblehead"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 210 }
      name       = "USS Raleigh"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 211 }
      name       = "42nd Destroyer Division"
      type       = destroyer
      model      = 0
    }
  }
  # 2nd West Coast Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 19 }
    name     = "2nd West Coast Transport Squadron"
    location = 766
    base     = 766
    division =
    { experience = 35
      id         = { type = 30305 id = 212 }
      name       = "23rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 213 }
      name       = "24th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 214 }
      name       = "94th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 215 }
      name       = "95th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 216 }
      name       = "96th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 217 }
      name       = "97th Transport Division"
      type       = transport
    }
  }
  # US Channel Squadron#
  navalunit =
  { id       = { type = 30302 id = 20 }
    name     = "US Channel Squadron"
    location = 87
    base     = 87
    division =
    { experience = 35
      id         = { type = 30305 id = 218 }
      name       = "USS Arkansas"
      type       = battleship
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 219 }
      name       = "USS New York"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 220 }
      name       = "USS Texas"
      type       = battleship
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 221 }
      name       = "USS Augusta"
      type       = heavy_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 222 }
      name       = "USS Quincy"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 223 }
      name       = "USS Tuscaloosa"
      type       = heavy_cruiser
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 224 }
      name       = "USS Memphis"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 225 }
      name       = "43rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 226 }
      name       = "44th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 227 }
      name       = "45th Destroyer Division"
      type       = destroyer
      model      = 0
    }
  }
  # US Channel Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 21 }
    name     = "US Channel Transport Squadron"
    location = 87
    base     = 87
    division =
    { experience = 35
      id         = { type = 30305 id = 228 }
      name       = "46th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 229 }
      name       = "47th Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 230 }
      name       = "25th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 231 }
      name       = "26th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 232 }
      name       = "27th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 233 }
      name       = "28th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 234 }
      name       = "29th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 235 }
      name       = "30th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 236 }
      name       = "98th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 237 }
      name       = "99th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 238 }
      name       = "100th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 239 }
      name       = "101st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 240 }
      name       = "102nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 241 }
      name       = "103rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 242 }
      name       = "104th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 243 }
      name       = "105th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 244 }
      name       = "106th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 245 }
      name       = "107th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 246 }
      name       = "108th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 247 }
      name       = "109th Transport Division"
      type       = transport
    }
  }
  # US Mediterranean Squadron#
  navalunit =
  { id       = { type = 30302 id = 22 }
    name     = "US Mediterranean Squadron"
    location = 950
    base     = 950
    division =
    { experience = 35
      id         = { type = 30305 id = 248 }
      name       = "USS Brooklyn"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 249 }
      name       = "USS Cincinnati"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 250 }
      name       = "USS Omaha"
      type       = light_cruiser
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 251 }
      name       = "USS Philadelphia"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 252 }
      name       = "USS Savannah"
      type       = light_cruiser
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 253 }
      name       = "48th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 254 }
      name       = "49th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 255 }
      name       = "50th Destroyer Division"
      type       = destroyer
      model      = 0
    }
  }
  # US Mediterranean Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 23 }
    name     = "US Mediterranean Transport Squadron"
    location = 950
    base     = 950
    division =
    { experience = 35
      id         = { type = 30305 id = 256 }
      name       = "51st Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 257 }
      name       = "52nd Destroyer Division"
      type       = destroyer
      model      = 0
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 258 }
      name       = "31st Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 259 }
      name       = "32nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 260 }
      name       = "33rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 261 }
      name       = "34th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 262 }
      name       = "35th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 263 }
      name       = "36th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 264 }
      name       = "110th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 265 }
      name       = "111th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 266 }
      name       = "112th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 267 }
      name       = "113th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 268 }
      name       = "114th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 269 }
      name       = "115th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 270 }
      name       = "116th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 271 }
      name       = "117th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 272 }
      name       = "118th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 273 }
      name       = "119th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 274 }
      name       = "120th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 275 }
      name       = "121st Transport Division"
      type       = transport
    }
  }
  # 1st East Coast Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 24 }
    name     = "1st East Coast Transport Squadron"
    location = 602
    base     = 602
    division =
    { experience = 35
      id         = { type = 30305 id = 276 }
      name       = "53rd Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 277 }
      name       = "37th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 278 }
      name       = "38th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 279 }
      name       = "122nd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 280 }
      name       = "123rd Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 281 }
      name       = "124th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 282 }
      name       = "125th Transport Division"
      type       = transport
    }
  }
  # 2nd East Coast Transport Squadron#
  navalunit =
  { id       = { type = 30302 id = 25 }
    name     = "2nd East Coast Transport Squadron"
    location = 603
    base     = 603
    division =
    { experience = 35
      id         = { type = 30305 id = 283 }
      name       = "54th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 284 }
      name       = "39th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 285 }
      name       = "40th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 286 }
      name       = "126th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 287 }
      name       = "127th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 288 }
      name       = "128th Transport Division"
      type       = transport
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 289 }
      name       = "129th Transport Division"
      type       = transport
    }
  }
  # 1st Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 26 }
    name     = "1st Submarine Division"
    location = 2159
    base     = 1627
    division =
    { experience = 35
      id         = { type = 30305 id = 290 }
      name       = "1st Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 2nd Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 27 }
    name     = "2nd Submarine Division"
    location = 2157
    base     = 1627
    division =
    { experience = 35
      id         = { type = 30305 id = 291 }
      name       = "2nd Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 3rd Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 28 }
    name     = "3rd Submarine Division"
    location = 2154
    base     = 1627
    division =
    { experience = 35
      id         = { type = 30305 id = 292 }
      name       = "3rd Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 4th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 29 }
    name     = "4th Submarine Division"
    location = 2157
    base     = 1627
    division =
    { experience = 35
      id         = { type = 30305 id = 293 }
      name       = "4th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 5th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 30 }
    name     = "5th Submarine Division"
    location = 2264
    base     = 1665
    division =
    { experience = 35
      id         = { type = 30305 id = 294 }
      name       = "5th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 6th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 31 }
    name     = "6th Submarine Division"
    location = 2262
    base     = 1665
    division =
    { experience = 35
      id         = { type = 30305 id = 295 }
      name       = "6th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 7th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 32 }
    name     = "7th Submarine Division"
    location = 662
    base     = 662
    division =
    { experience = 35
      id         = { type = 30305 id = 296 }
      name       = "7th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 8th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 33 }
    name     = "8th Submarine Division"
    location = 662
    base     = 662
    division =
    { experience = 35
      id         = { type = 30305 id = 297 }
      name       = "8th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 9th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 34 }
    name     = "9th Submarine Division"
    location = 2152
    base     = 1704
    division =
    { experience = 35
      id         = { type = 30305 id = 298 }
      name       = "9th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 10th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 35 }
    name     = "10th Submarine Division"
    location = 2160
    base     = 1704
    division =
    { experience = 35
      id         = { type = 30305 id = 299 }
      name       = "10th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 11th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 36 }
    name     = "11th Submarine Division"
    location = 1704
    base     = 1704
    division =
    { experience = 35
      id         = { type = 30305 id = 300 }
      name       = "11th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 12th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 37 }
    name     = "12th Submarine Division"
    location = 1704
    base     = 1704
    division =
    { experience = 35
      id         = { type = 30305 id = 301 }
      name       = "12th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 13th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 38 }
    name     = "13th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 30305 id = 302 }
      name       = "13th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 14th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 39 }
    name     = "14th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 30305 id = 303 }
      name       = "14th Submarine Division"
      type       = submarine
      model      = 2
    }
  }
  # 15th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 40 }
    name     = "15th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 30305 id = 304 }
      name       = "15th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 16th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 41 }
    name     = "16th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 30305 id = 305 }
      name       = "16th Submarine Division"
      type       = submarine
      model      = 1
    }
  }
  # 17th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 42 }
    name     = "17th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 30305 id = 306 }
      name       = "17th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 18th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 43 }
    name     = "18th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 30305 id = 307 }
      name       = "18th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  # 19th Submarine Division#
  navalunit =
  { id       = { type = 30302 id = 44 }
    name     = "19th Submarine Division"
    location = 663
    base     = 663
    division =
    { experience = 35
      id         = { type = 30305 id = 308 }
      name       = "19th Submarine Division"
      type       = submarine
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 30302 id = 45 }
    name     = "Task Group 60.1"
    location = 1184
    base     = 1184
    division =
    {
      id            = { type = 30305 id = 309 }
      name          = "USS Bennington"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 310 }
      name          = "USS Boxer"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 311 }
      name          = "USS Antietam"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 312 }
      name          = "USS Bon Homme Richard"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 0
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 313 }
      name       = "USS Duluth"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 314 }
      name       = "USS Wilkes-Barre"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 315 }
      name       = "USS Pittsburgh"
      type       = heavy_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 316 }
      name       = "55th Destroyer Division"
      type       = destroyer
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 317 }
      name       = "56th Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  navalunit =
  { id       = { type = 30302 id = 46 }
    name     = "Task Group 60.2"
    location = 1193
    base     = 1193
    division =
    {
      id            = { type = 30305 id = 318 }
      name          = "USS Shangri La"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 319 }
      name          = "USS Lake Champlain"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 320 }
      name          = "USS Midway"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 4
      experience    = 20
    }
    division =
    {
      id            = { type = 30305 id = 321 }
      name          = "USS Coral Sea"
      type          = carrier
      extra         = cag
      brigade_model = 5
      model         = 0
      experience    = 20
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 322 }
      name       = "USS Flint"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 323 }
      name       = "USS Springfield"
      type       = light_cruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 324 }
      name       = "USS Guam"
      type       = battlecruiser
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30305 id = 325 }
      name       = "57th Destroyer Division"
      type       = destroyer
      model      = 3
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 30303 id = 1 }
    name     = "8th Air Force Bombers/1"
    division =
    { experience    = 35
      id            = { type = 30306 id = 1 }
      name          = "25th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 2 }
      name          = "91st USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 3 }
      name          = "94th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 11 }
      name          = "457th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 82
    base     = 82
    id       = { type = 30303 id = 2 }
    name     = "8th Air Force Fighters/1"
    division =
    { experience = 35
      id         = { type = 30306 id = 15 }
      name       = "1st USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 16 }
      name       = "4th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 17 }
      name       = "56th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 18 }
      name       = "352nd USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 44
    base     = 44
    id       = { type = 30303 id = 3 }
    name     = "9th Air Force"
    division =
    { experience = 35
      id         = { type = 30306 id = 23 }
      name       = "97th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 24 }
      name       = "98th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 25 }
      name       = "99th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 30 }
      name       = "303rd USAAF interceptor Wing"
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 523
    base     = 523
    id       = { type = 30303 id = 4 }
    name     = "15th Air Force"
    division =
    { experience    = 35
      id            = { type = 30306 id = 31 }
      name          = "5th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 32 }
      name          = "47th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 33 }
      name          = "49th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 34 }
      name          = "55th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 462
    base     = 462
    id       = { type = 30303 id = 5 }
    name     = "12th Air Force"
    division =
    { experience = 35
      id         = { type = 30306 id = 38 }
      name       = "17th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 39 }
      name       = "310th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 40 }
      name       = "57th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 41 }
      name       = "324th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 19
    base     = 19
    id       = { type = 30303 id = 6 }
    name     = "9th Air Force/Air Transports"
    division =
    { experience = 35
      id         = { type = 30306 id = 42 }
      name       = "50th USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 43 }
      name       = "52nd USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 44 }
      name       = "53rd USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 47 }
      name       = "403rd USAAF Troop Carrier Wing"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
  }
  # ####id up to 255
  airunit =
  { location = 1185
    base     = 1185
    id       = { type = 30303 id = 7 }
    name     = "13th Air Force (Heavy)"
    division =
    { experience    = 35
      id            = { type = 30306 id = 45 }
      name          = "5th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 46 }
      name       = "42nd USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 2
    }
  }
  airunit =
  { location = 1599
    base     = 1599
    id       = { type = 30303 id = 8 }
    name     = "13th Air Force interceptors"
    division =
    { experience = 35
      id         = { type = 30306 id = 48 }
      name       = "347th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { location = 94
    base     = 440
    id       = { type = 30303 id = 9 }
    name     = "USAAF CONUS Reserve 1"
    mission =
    { type       = nuke
      target     = 175
      percentage = 0.0000
      night      = yes
      day        = yes
      startdate  = { year = 1945 month = october day = 1 hour = 0 }
      enddate    = { year = 1945 month = november day = 1 hour = 0 }
      task       = 1
      location   = 94
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 49 }
      name          = "1st Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      nuke          = yes
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 50 }
      name          = "2nd Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 55 }
      name          = "7th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
  }
  # Commented as for now
  # division =
  # { experience = 35
  # id         = { type = 30306 id = 56 }
  # name       = "1st Res FG"
  # strength   = 100
  # type       = multi_role
  # model      = 2
  # }
  airunit =
  { location = 1193
    base     = 1193
    id       = { type = 30303 id = 10 }
    name     = "10th Air Force"
    division =
    { experience    = 35
      id            = { type = 30306 id = 59 }
      name          = "7th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 60 }
      name       = "12th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 64 }
      name       = "341st USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 4
    }
  }
  airunit =
  { location = 1179
    base     = 1179
    id       = { type = 30303 id = 11 }
    name     = "11th Air Force"
    division =
    { experience    = 35
      id            = { type = 30306 id = 65 }
      name          = "9th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 66 }
      name       = "11th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 35 }
      name          = "304th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { location = 1195
    base     = 1195
    id       = { type = 30303 id = 12 }
    name     = "1/SWPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 67 }
      name       = "35th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 68 }
      name       = "38th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 69 }
      name       = "345th USAAF Tactical Bomb. Wing"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 1185
    base     = 1185
    id       = { type = 30303 id = 13 }
    name     = "2/SWPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 70 }
      name       = "49th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 71 }
      name          = "43rd USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 72 }
      name          = "307th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { location = 1624
    base     = 1624
    id       = { type = 30303 id = 14 }
    name     = "3/SWPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 73 }
      name       = "VMFN 115"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 74 }
      name       = "VMSB 142"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1195
    base     = 1195
    id       = { type = 30303 id = 15 }
    name     = "4/SWPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 75 }
      name       = "VMF 121/211"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 76 }
      name       = "VMF 313"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 77 }
      name       = "VMB 433/443"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { location = 1190
    base     = 1190
    id       = { type = 30303 id = 16 }
    name     = "5/SWPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 78 }
      name       = "VMF 218/222"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 79 }
      name       = "VMSB 133/341"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 80 }
      name       = "VMSB 244/423"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1195
    base     = 1195
    id       = { type = 30303 id = 17 }
    name     = "6/SWPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 81 }
      name       = "VMF 215/223"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 82 }
      name       = "VMF 221/315"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 83 }
      name       = "VMB 241/413"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1184
    base     = 1184
    id       = { type = 30303 id = 18 }
    name     = "2/CPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 84 }
      name       = "VMF 111/224"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 85 }
      name       = "VMSB 311/331"
      strength   = 100
      type       = cas
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 86 }
      name       = "VMSB 231/245"
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 663
    base     = 663
    id       = { type = 30303 id = 19 }
    name     = "1/CPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 87 }
      name       = "VMF 124/213"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 88 }
      name       = "VMSB "
      strength   = 100
      type       = cas
      model      = 2
    }
  }
  airunit =
  { location = 1627
    base     = 1627
    id       = { type = 30303 id = 20 }
    name     = "3/CPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 89 }
      name       = "VFN 532/534"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 90 }
      name       = "VMF 225/321"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 91 }
      name       = "VMF 216/217"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 92 }
      name       = "VMTB 131/242"
      strength   = 100
      type       = naval_bomber
      model      = 2
    }
  }
  airunit =
  { location = 1187
    base     = 1187
    id       = { type = 30303 id = 21 }
    name     = "4/CPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 93 }
      name       = "VMF 114/122"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 94 }
      name       = "VMB 134/541"
      strength   = 100
      type       = interceptor
      model      = 4
    }
  }
  airunit =
  { location = 1184
    base     = 1184
    id       = { type = 30303 id = 22 }
    name     = "7/SWPAF"
    division =
    { experience = 35
      id         = { type = 30306 id = 95 }
      name       = "VMF 113/422"
      strength   = 100
      type       = interceptor
      model      = 4
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 96 }
      name       = "VMB 151/612"
      strength   = 100
      type       = tactical_bomber
      model      = 3
    }
  }
  airunit =
  { id       = { type = 30303 id = 23 }
    name     = "USAAF CONUS Reserve 2"
    location = 1839
    base     = 448
    mission =
    { type       = nuke
      target     = 1828
      percentage = 0.0000
      night      = yes
      day        = yes
      startdate  = { year = 1945 month = october day = 1 hour = 0 }
      enddate    = { year = 1945 month = november day = 1 hour = 0 }
      task       = 1
      location   = 1839
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 53 }
      name          = "5th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      nuke          = yes
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 52 }
      name          = "4th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 51 }
      name          = "3rd Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 54 }
      name          = "6th Res BG"
      strength      = 100
      type          = strategic_bomber
      model         = 2
      extra         = escort
      brigade_model = 2
    }
  }
  airunit =
  { id       = { type = 30303 id = 24 }
    name     = "9th Air Force Fighters"
    location = 44
    base     = 44
    division =
    { experience = 35
      id         = { type = 30306 id = 26 }
      name       = "70th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 27 }
      name       = "71st USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 28 }
      name       = "84th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 29 }
      name       = "100th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { id       = { type = 30303 id = 25 }
    name     = "15th Air Force Fighters"
    location = 531
    base     = 531
    division =
    { experience = 35
      id         = { type = 30306 id = 36 }
      name       = "305th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 37 }
      name       = "306th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { id       = { type = 30303 id = 26 }
    name     = "Reserve Transports"
    location = 606
    base     = 606
    division =
    { experience = 35
      id         = { type = 30306 id = 57 }
      name       = "1st Res Transp"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 58 }
      name       = "2nd Res Transp"
      strength   = 100
      type       = transport_plane
      model      = 1
    }
  }
  airunit =
  { id       = { type = 30303 id = 27 }
    name     = "10th Air Force Fighters"
    location = 47
    base     = 47
    division =
    { experience = 35
      id         = { type = 30306 id = 61 }
      name       = "33rd USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 62 }
      name       = "80th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 63 }
      name       = "311th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { id       = { type = 30303 id = 28 }
    name     = "8th Air Force Fighters/2"
    location = 313
    base     = 313
    division =
    { experience = 35
      id         = { type = 30306 id = 19 }
      name       = "355th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 20 }
      name       = "357th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 21 }
      name       = "356th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
    division =
    { experience = 35
      id         = { type = 30306 id = 22 }
      name       = "358th USAAF interceptor Wing"
      strength   = 100
      type       = multi_role
      model      = 2
    }
  }
  airunit =
  { id       = { type = 30303 id = 29 }
    name     = "8th Air Force Bombers/2"
    location = 20
    base     = 20
    division =
    { experience    = 35
      id            = { type = 30306 id = 13 }
      name          = "487th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 10 }
      name          = "445th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 5 }
      name          = "322nd USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 4 }
      name          = "303rd USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 30303 id = 30 }
    name     = "8th Air Force Bombers/3"
    location = 21
    base     = 21
    division =
    { experience    = 35
      id            = { type = 30306 id = 8 }
      name          = "388th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 7 }
      name          = "385th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 12 }
      name          = "467th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 30303 id = 31 }
    name     = "8th Air Force Bombers/4"
    location = 19
    base     = 19
    division =
    { experience    = 35
      id            = { type = 30306 id = 9 }
      name          = "392nd USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 6 }
      name          = "379th USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
    division =
    { experience    = 35
      id            = { type = 30306 id = 14 }
      name          = "491st USAAF Strategic Bomb. Wing"
      strength      = 100
      type          = strategic_bomber
      model         = 1
      extra         = escort
      brigade_model = 1
    }
  }
  airunit =
  { id       = { type = 30303 id = 32 }
    name     = "P-80 Squadron"
    location = 606
    base     = 606
    division =
    { type         = multi_role
      model        = 4
      id           = { type = 30306 id = 97 }
      name         = "P-80 Squadron"
      strength     = 4
      max_strength = 45
    }
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = october year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 171 }
    name          = "107th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = october year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 152 }
    name          = "109th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = october year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 153 }
    name          = "110th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = october year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 154 }
    name          = "108th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 155 }
    name          = "111th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 156 }
    name          = "112th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 157 }
    name          = "113th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 158 }
    name          = "114th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 159 }
    name          = "115th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 160 }
    name          = "116th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 161 }
    name          = "117th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = november year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 162 }
    name          = "118th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 163 }
    name          = "119th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 164 }
    name          = "120th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 165 }
    name          = "121st Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 0 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 166 }
    name          = "122nd Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 167 }
    name          = "123rd Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 168 }
    name          = "124th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 169 }
    name          = "125th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = motorized
    model         = 2
    date          = { day = 14 month = december year = 1945 }
    cost          = 10
    days          = 100
    id            = { type = 30304 id = 170 }
    name          = "126th Infantry Division"
    extra         = sp_artillery
    brigade_model = 2
  }
  division_development =
  { type          = armor
    model         = 4
    date          = { day = 0 month = january year = 1946 }
    cost          = 15
    days          = 185
    id            = { type = 30304 id = 172 }
    name          = "21st Armoured Division"
    extra         = heavy_armor
    brigade_model = 1
  }
  division_development =
  { type          = armor
    model         = 4
    date          = { day = 0 month = january year = 1946 }
    cost          = 15
    days          = 185
    id            = { type = 30304 id = 173 }
    name          = "22nd Armoured Division"
    extra         = heavy_armor
    brigade_model = 1
  }
  division_development =
  { type          = armor
    model         = 4
    date          = { day = 0 month = january year = 1946 }
    cost          = 15
    days          = 185
    id            = { type = 30304 id = 174 }
    name          = "23rd Armoured Division"
    extra         = heavy_armor
    brigade_model = 1
  }
  division_development =
  { type          = armor
    model         = 4
    date          = { day = 0 month = january year = 1946 }
    cost          = 15
    days          = 185
    id            = { type = 30304 id = 175 }
    name          = "24th Armoured Division"
    extra         = heavy_armor
    brigade_model = 1
  }
  division_development =
  { type           = carrier
    model          = 5
    date           = { day = 10 month = april year = 1946 }
    cost           = 11.1
    days           = 810
    # days_of_first  = 810
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 326 }
    name           = "Leyte"
    extra          = cag
    brigade_model  = 5
  }
  division_development =
  { type           = carrier
    model          = 5
    date           = { day = 1 month = may year = 1946 }
    cost           = 11.1
    days           = 810
    # days_of_first  = 810
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 327 }
    name           = "Kearsarge"
    extra          = cag
    brigade_model  = 5
  }
  division_development =
  { type           = carrier
    model          = 5
    date           = { day = 17 month = november year = 1945 }
    cost           = 11.1
    days           = 810
    # days_of_first  = 810
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 328 }
    name           = "Princeton"
    extra          = cag
    brigade_model  = 5
  }
  division_development =
  { type           = heavy_cruiser
    model          = 4
    date           = { day = 9 month = january year = 1946 }
    cost           = 8
    days           = 365
    # days_of_first  = 365
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 330 }
    name           = "Chicago"
  }
  division_development =
  { type           = heavy_cruiser
    model          = 4
    date           = { day = 14 month = june year = 1946 }
    cost           = 8
    days           = 365
    # days_of_first  = 365
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 329 }
    name           = "Albany"
  }
  division_development =
  { type           = light_cruiser
    model          = 4
    date           = { day = 14 month = february year = 1946 }
    cost           = 7
    days           = 230
    # days_of_first  = 230
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 331 }
    name           = "Juneau"
  }
  division_development =
  { type           = light_cruiser
    model          = 4
    date           = { day = 14 month = may year = 1946 }
    cost           = 7
    days           = 230
    # days_of_first  = 230
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 332 }
    name           = "Spokane"
  }
  division_development =
  { type           = escort_carrier
    model          = 2
    date           = { day = 1 month = july year = 1946 }
    cost           = 7
    days           = 360
    # days_of_first  = 230
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 405 }
    name           = "USS Saipan"
  }
  division_development =
  { type           = escort_carrier
    model          = 2
    date           = { day = 1 month = february year = 1947 }
    cost           = 5
    days           = 600
    # days_of_first  = 230
    total_progress = 0
    # series         = 1
    done           = 0
    progress       = 0
    id             = { type = 30305 id = 406 }
    name           = "USS Wright"
  }
}
