province = {
	id = 1737 #Manila
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	oilpool = 5000
	supplypool = 5000
	}

province = {
	id = 1739 #Clark Field
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1193 #Okinawa
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	oilpool = 10000
	supplypool = 10000
	}

province = {
	id = 1599 #Iwo Jima
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	oilpool = 1000
	supplypool = 5000
	}

province = {
	id = 1624 #Guam
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1626 #Tinian
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1627 #Saipan
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1618 #Ulithi
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}


country = {
	tag = ALS

	capital = 1618

	manpower = 1280

	transports = 600
	escorts = 200

	extra_tc = 300

	oil = 25000
	supplies = 50000

	free = {
		supplies = 400
		oil = 200
		ic = 100
		}

	policy = {
		date = { year = 0 month = january day = 0 }
		democratic = 10
		political_left = 7
		freedom = 10
		free_market = 10
		professional_army = 1
		defense_lobby = 5
		interventionism = 1
		}

	headofstate = { type = 9 id = 6034 }
	headofgovernment = { type = 9 id = 6047 }
	foreignminister = { type = 9 id = 6063 }
	armamentminister = { type = 9 id = 6082 }
	ministerofsecurity = { type = 9 id = 6005 }
	ministerofintelligence = { type = 9 id = 6128 }
	chiefofstaff = { type = 9 id = 6136 }
	chiefofarmy = { type = 9 id = 6144 }
	chiefofnavy = { type = 9 id = 6163 }
	chiefofair = { type = 9 id = 6167 }

steal_leader = 60386 #A. Burke
steal_leader = 60465 #A. E. Smith
steal_leader = 60381 #Barbey
steal_leader = 60384 #Bogan
steal_leader = 60398 #Denfield
steal_leader = 60399 #Durgin
steal_leader = 60402 #Fetchteler
steal_leader = 60404 #Fletcher
steal_leader = 1348 #Fraser (UK)
steal_leader = 60503 #G. B. Davis
steal_leader = 60514 #Gardner
steal_leader = 60413 #Hall
steal_leader = 60420 #H. Hill
steal_leader = 60414 #Halsey
steal_leader = 60416 #Harrill
steal_leader = 60392 #J. Clark
steal_leader = 60426 #Kinkaid
steal_leader = 60430 #Lee
steal_leader = 60436 #McCain
steal_leader = 60439 #McCormick
steal_leader = 60443 #Mitscher
steal_leader = 60452 #Oldendorf
steal_leader = 60458 #Reeves
steal_leader = 60463 #Sherman
steal_leader = 60467 #Sprague
steal_leader = 60469 #Spruance
steal_leader = 60471 #Stump
steal_leader = 60475 #Turner
steal_leader = 1399 #Vian (UK)
steal_leader = 60577 #T. Allen
steal_leader = 60490 #Brett
steal_leader = 60491 #Brooks
steal_leader = 60068 #Bruce
steal_leader = 60069 #Brush
steal_leader = 60080 #Butler
steal_leader = 60109 #Corlett
steal_leader = 60505 #Doolittle
steal_leader = 60144 #Eichelberger
steal_leader = 60509 #Fitch
steal_leader = 60217 #Geiger
steal_leader = 60182 #Griswold
steal_leader = 60333 #H. M. Smith
steal_leader = 60196 #Harmon
steal_leader = 60216 #Hodge
steal_leader = 60217 #Hodges
steal_leader = 60334 #J. C. Smith
steal_leader = 60525 #Johnson
steal_leader = 1179 #Keightley (UK)
steal_leader = 60526 #Kennedy
steal_leader = 60527 #Kenney
steal_leader = 60233 #Krueger
steal_leader = 60532 #LeMay
steal_leader = 60250 #MacArthur
steal_leader = 60545 #Partridge
steal_leader = 60291 #Patch
steal_leader = 60318 #Rupertus
steal_leader = 60323 #Schmidt
steal_leader = 60557 #Spaatz
steal_leader = 60558 #Timberlake
steal_leader = 60560 #Twining
steal_leader = 60357 #Vandegrift
steal_leader = 60364 #Watson
steal_leader = 60368 #Wheeler
steal_leader = 60567 #White
steal_leader = 60568 #Whitehead
steal_leader = 60570 #Woods


	ownedprovinces = {
	1737 1738 1739 1740 1741 1742 1743
	1624
	1618
	}
	controlledprovinces = {
	1737 1738 1739 1740 1741 1742 1743
	1193 1599
	1624 1626 1627
	1618
	}
	nationalprovinces = {
	1737 1738 1739 1740 1741 1742 1743
	1624
	1618
	}

	techapps = { 1010 1020 1030 1040 1050 1070 1080 1090 1100 1110 1120 1130 1140 1150 1160 1170 1180 1190 1200 1210
			     12100 12110 12120 12130 1220 1230 1240 1250 1260 1270 1280 1310 1320 1330 1340 1350 1360 14000 14010 14020
			     14030 15000 15030 15040 15060 15500 2010 2020 2030 2040 2050 2070 2080 2090 2100 2110 2150 2160 2170 2180
			     2190 2200 2220 2230 2240 2260 2290 2300 2310 2320 2330 2340 2350 2370 2380 2400 2410 2420 2430 2450
			     2460 2470 2480 2510 2520 2530 3010 3020 3030 3040 3050 3070 3080 3090 3100 3110 3130 3140 3150 3160
			     3170 3190 3200 3210 3220 3230 3250 3260 3270 3280 3290 3320 3330 3340 3350 3360 3370 3400 3410 3420
			     3430 4010 4020 4030 4040 4050 4060 4070 4080 4090 4100 4110 4120 4130 4140 4150 4160 4170 4180 4190
			     4200 4210 4220 4230 4240 4250 4260 4270 4280 5010 5020 5030 5050 5060 5070 5080 5090 5100 5110 5120
			     5130 5140 5150 5160 5170 5180 5190 5200 5210 5310 5320 5330 5340 5350 5360 5370 5380 5390 5400 5410
			     5420 5430 5440 5450 5470 5480 5490 5500 5510 5520 5530 5540 5550 5560 5570 6010 6020 6040 6050 6060
			     6070 6080 6090 7140 7150 7160 8010 8020 8030 8040 8050 8060 8090 8100 8110 8130 8140
			     8160 8180 8230 8240 8250 8310 8320 9010 9020 9030 9040 9050 9060 9070 9080 9090 9100 9110 9120 9130
			     9140 9150 9160 9170 9180 9190 9200 9210 9220 9230 9240 9250 9260 9270 9280 9290 9300 9310 9320 9330
			     9350 9360 9370 9380 9390 9400 9430 9440 9450 9460
			   }
	landunit = {
		id = { type = 10000 id = 1 }
		name = "V Marine Amphibious Corps"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2 } name = "2nd Marine Division" strength = 100 type = marine model = 3 }
		division = { id = { type = 10000 id = 3 } name = "3rd Marine Division" strength = 100 type = marine model = 3 }
		division = { id = { type = 10000 id = 4 } name = "5th Marine Division" strength = 100 type = marine model = 3 }
		}

	landunit = {
		id = { type = 10000 id = 5 }
		name = "XI Corps"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 6 } name = "Americal Division" strength = 100 type = infantry model = 5 }
		division = { id = { type = 10000 id = 7 } name = "1st Cavalry Division" strength = 100 type = cavalry model = 4 }
		division = { id = { type = 10000 id = 8 } name = "43rd Infantry Division" strength = 100 type = infantry model = 5 }
		}

	landunit = {
		id = { type = 10000 id = 9 }
		name = "I Corps"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 10 } name = "25th Infantry Division" strength = 100 type = infantry model = 5 }
		division = { id = { type = 10000 id = 11 } name = "33rd Infantry Division" strength = 100 type = infantry model = 5 }
		division = { id = { type = 10000 id = 12 } name = "41st Infantry Division" strength = 100 type = infantry model = 5 }
		}

	landunit = {
		id = { type = 10000 id = 13 }
		name = "IX Corps"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 14 } name = "81st Infantry Division" strength = 100 type = infantry model = 5 }
		division = { id = { type = 10000 id = 15 } name = "98th Infantry Division" strength = 100 type = infantry model = 5 }
		}

	landunit = {
		id = { type = 10000 id = 16 }
		name = "40th Infantry Division"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 17 } name = "40th Infantry Division" strength = 100 type = infantry model = 5 }
		}

	landunit = {
		id = { type = 10000 id = 18 }
		name = "11th Airborne Division"
		location = 1737 #Manila
		division = { id = { type = 10000 id = 19 } name = "11th Airborne Division" strength = 100 type = paratrooper model = 3 }
		}

	landunit = {
		id = { type = 10000 id = 20 }
		name = "77th Infantry Division"
		location = 1737 #Manila
		division = { id = { type = 10000 id = 21 } name = "77th Infantry Division" strength = 100 type = infantry model = 5 }
		}

	landunit = {
		id = { type = 10000 id = 22 }
		name = "93rd Infantry Division"
		location = 1741 #Aparri
		division = { id = { type = 10000 id = 23 } name = "93rd Infantry Division" strength = 100 type = infantry model = 5 }
		}

	landunit = {
		id = { type = 10000 id = 24 }
		name = "III Marine Amphibious Corps"
		location = 1618 #Ulithi
		division = { id = { type = 10000 id = 25 } name = "1st Marine Division" strength = 100 type = marine model = 3 }
		division = { id = { type = 10000 id = 26 } name = "4th Marine Division" strength = 100 type = marine model = 3 }
		division = { id = { type = 10000 id = 27 } name = "6th Marine Division" strength = 100 type = marine model = 3 }
		}

	landunit = {
		id = { type = 10000 id = 28 }
		name = "XXIV Corps"
		location = 1627 #Saipan
		division = { id = { type = 10000 id = 29 } name = "7th Infantry Division" strength = 100 type = infantry model = 5 }
		division = { id = { type = 10000 id = 30 } name = "27th Infantry Division" strength = 100 type = infantry model = 5 }
		division = { id = { type = 10000 id = 31 } name = "96th Infantry Division" strength = 100 type = infantry model = 5 }
		}

	landunit = {
		id = { type = 10000 id = 32 }
		name = "Okinawa Garrison"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 33 } name = "Okinawa Garrison" strength = 100 type = garrison model = 2 locked = yes}
		}

	landunit = {
		id = { type = 10000 id = 34 }
		name = "Iwo Jima Garrison"
		location = 1599 #Iwo Jima
		division = { id = { type = 10000 id = 35 } name = "Iwo Jima Garrison" strength = 100 type = garrison model = 2 locked = yes }
		}

	landunit = {
		id = { type = 10000 id = 36 }
		name = "Guam Garrison"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 37 } name = "Guam Garrison" strength = 100 type = garrison model = 2 locked = yes }
		}

	landunit = {
		id = { type = 10000 id = 38 }
		name = "Tinian Garrison"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 39 } name = "Tinian Garrison" strength = 100 type = garrison model = 2 locked = yes }
		}

	landunit = {
		id = { type = 10000 id = 40 }
		name = "Saipan Garrison"
		location = 1627 #Saipan
		division = { id = { type = 10000 id = 41 } name = "Saipan Garrison" strength = 100 type = garrison model = 2 locked = yes }
		}

	landunit = {
		id = { type = 10000 id = 42 }
		name = "Ulithi Garrison"
		location = 1618 #Ulithi
		division = { id = { type = 10000 id = 43 } name = "Ulithi Garrison" strength = 100 type = garrison model = 2 locked = yes }
		}

	landunit = {
		id = { type = 10000 id = 44 }
		name = "Manila Garrison"
		location = 1737 #Manila
		division = { id = { type = 10000 id = 45 } name = "Manila Garrison" strength = 100 type = garrison model = 2 locked = yes }
		}

	landunit = {
		id = { type = 10000 id = 46 }
		name = "Clark Field Garrison"
		location = 1739 #Clark Field
		division = { id = { type = 10000 id = 47 } name = "Clark Field Garrison" strength = 100 type = garrison model = 2 locked = yes }
		}

	landunit = {
		id = { type = 10000 id = 48 }
		name = "6th Army"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 49 } name = "6th Army" strength = 100 type = hq model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1000 }
		name = "Task Force 38.1"
		location = 2193 #East of Kyushu
		base = 1193 #Okinawa
		division = { id = { type = 10000 id = 1001 } name = "USS Essex" type = carrier model = 4 extra = cag brigade_model = 7 }
		division = { id = { type = 10000 id = 1002 } name = "USS Yorktown" type = carrier model = 4 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1003 } name = "USS Intrepid" type = carrier model = 4 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1004 } name = "1st Light Carrier Division" type = carrier model = 3 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1005 } name = "USS Wisconsin" type = battleship model = 4 }
		division = { id = { type = 10000 id = 1006 } name = "USS Boston" type = heavy_cruiser model = 3 }
		division = { id = { type = 10000 id = 1007 } name = "USS Atlanta" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1008 } name = "USS Dayton" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1009 } name = "USS San Juan" type = light_cruiser model = 2 } #AA CL
		division = { id = { type = 10000 id = 1010 } name = "1st Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1011 } name = "2nd Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1012 } name = "3rd Destroyer Division" type = destroyer model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1013 }
		name = "Task Force 38.2"
		location = 2193 #East of Kyushu
		base = 1193 #Okinawa
		division = { id = { type = 10000 id = 1014 } name = "USS Hornet" type = carrier model = 4 extra = cag brigade_model = 7 }
		division = { id = { type = 10000 id = 1015 } name = "USS Ticonderoga" type = carrier model = 4 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1016 } name = "USS Randolph" type = carrier model = 4 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1017 } name = "USS Missouri" type = battleship model = 4 }
		division = { id = { type = 10000 id = 1018 } name = "USS Baltimore" type = heavy_cruiser model = 3 }
		division = { id = { type = 10000 id = 1019 } name = "USS Wilkes-Barre" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1020 } name = "USS Amsterdam" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1021 } name = "USS Oakland" type = light_cruiser model = 2 } #AA CL
		division = { id = { type = 10000 id = 1022 } name = "4th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1023 } name = "5th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1024 } name = "6th Destroyer Division" type = destroyer model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1025 }
		name = "Task Force 38.3"
		location = 2187 #West of Kyushu
		base = 1193 #Okinawa
		division = { id = { type = 10000 id = 1026 } name = "USS Lexington" type = carrier model = 4 extra = cag brigade_model = 7 }
		division = { id = { type = 10000 id = 1027 } name = "USS Bunker Hill" type = carrier model = 4 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1028 } name = "USS Wasp" type = carrier model = 4 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1029 } name = "USS New Jersey" type = battleship model = 4 }
		division = { id = { type = 10000 id = 1030 } name = "USS Chicago" type = heavy_cruiser model = 3 }
		division = { id = { type = 10000 id = 1031 } name = "USS Oklahoma City" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1032 } name = "USS Astoria" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1033 } name = "USS Tucson" type = light_cruiser model = 2 } #AA CL
		division = { id = { type = 10000 id = 1034 } name = "7th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1035 } name = "8th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1036 } name = "9th Destroyer Division" type = destroyer model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1037 }
		name = "Task Force 38.4"
		location = 2187 #West of Kyushu
		base = 1193 #Okinawa
		division = { id = { type = 10000 id = 1038 } name = "USS Hancock" type = carrier model = 4 extra = cag brigade_model = 7 }
		division = { id = { type = 10000 id = 1039 } name = "USS Bennington" type = carrier model = 4 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1040 } name = "USS Enterprise" type = carrier model = 2 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1041 } name = "USS Iowa" type = battleship model = 4 }
		division = { id = { type = 10000 id = 1042 } name = "USS Fall River" type = heavy_cruiser model = 3 }
		division = { id = { type = 10000 id = 1043 } name = "USS Miami" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1044 } name = "USS Duluth" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1045 } name = "USS Flint" type = light_cruiser model = 2 } #AA CL
		division = { id = { type = 10000 id = 1046 } name = "10th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1047 } name = "11th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1048 } name = "12th Destroyer Division" type = destroyer model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1049 }
		name = "Task Force 38.5"
		location = 2589 #Off Tokyo
		base = 1193 #Okinawa
		division = { id = { type = 10000 id = 1050 } name = "USS Shangri La" type = carrier model = 4 extra = cag brigade_model = 7 }
		division = { id = { type = 10000 id = 1051 } name = "USS Saratoga" type = carrier model = 1 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1052 } name = "2nd Light Carrier Division" type = carrier model = 3 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1053 } name = "3rd Light Carrier Division" type = carrier model = 3 extra = cag brigade_model = 6 }
		division = { id = { type = 10000 id = 1054 } name = "USS Alabama" type = battleship model = 4 }
		division = { id = { type = 10000 id = 1055 } name = "USS Bremerton" type = heavy_cruiser model = 3 }
		division = { id = { type = 10000 id = 1056 } name = "USS Vicksburg" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1057 } name = "USS Providence" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1058 } name = "USS Reno" type = light_cruiser model = 2 } #AA CL
		division = { id = { type = 10000 id = 1059 } name = "13th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1060 } name = "14th Destroyer Division" type = destroyer model = 3 }
		division = { id = { type = 10000 id = 1061 } name = "15th Destroyer Division" type = destroyer model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1062 }
		name = "Task Force 38.6"
		location = 2193 #East of Kyushu
		base = 1193 #Okinawa
		division = { id = { type = 10000 id = 1063 } name = "USS Massachusetts" type = battleship model = 3 }
		division = { id = { type = 10000 id = 1064 } name = "USS Indiana" type = battleship model = 3 }
		division = { id = { type = 10000 id = 1065 } name = "USS South Dakota" type = battleship model = 3 }
		division = { id = { type = 10000 id = 1066 } name = "USS Washington" type = battleship model = 3 }
		division = { id = { type = 10000 id = 1067 } name = "USS Alaska" type = battlecruiser model = 3 }
		division = { id = { type = 10000 id = 1068 } name = "USS Guam" type = battlecruiser model = 3 }
		division = { id = { type = 10000 id = 1069 } name = "USS Helena" type = heavy_cruiser model = 3 }
		division = { id = { type = 10000 id = 1070 } name = "USS Columbus" type = heavy_cruiser model = 3 }
		division = { id = { type = 10000 id = 1071 } name = "USS Houston" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1072 } name = "USS Biloxi" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1073 } name = "16th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1074 } name = "17th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1075 } name = "18th Destroyer Division" type = destroyer model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1076 }
		name = "Task Force 58.1"
		location = 2185 #Off Okinawa
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1077 } name = "1st Escort Carrier Division" type = carrier model = 2 extra = cag brigade_model = 4 }
		division = { id = { type = 10000 id = 1078 } name = "2nd Escort Carrier Division" type = carrier model = 2 extra = cag brigade_model = 4 }
		division = { id = { type = 10000 id = 1079 } name = "3rd Escort Carrier Division" type = carrier model = 2 extra = cag brigade_model = 4 }
		division = { id = { type = 10000 id = 1080 } name = "USS Topeka" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1081 } name = "USS Springfield" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1082 } name = "USS Pasadena" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1083 } name = "USS Vincennes" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1084 } name = "USS Mobile" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1085 } name = "USS Birmingham" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1086 } name = "USS San Diego" type = light_cruiser model = 3 } #AA CL
		division = { id = { type = 10000 id = 1087 } name = "19th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1088 } name = "20th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1089 } name = "21st Destroyer Division" type = destroyer model = 1 }
		}

	navalunit = {
		id = { type = 10000 id = 1090 }
		name = "Task Force 58.2"
		location = 2187 #West of Kyushu
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1091 } name = "USS North Carolina" type = battleship model = 3 }
		division = { id = { type = 10000 id = 1092 } name = "USS West Virginia" type = battleship model = 2 }
		division = { id = { type = 10000 id = 1093 } name = "USS California" type = battleship model = 1 }
		division = { id = { type = 10000 id = 1094 } name = "USS Tennessee" type = battleship model = 1 }
		division = { id = { type = 10000 id = 1095 } name = "USS Idaho" type = battleship model = 1 }
		division = { id = { type = 10000 id = 1096 } name = "USS Mississippi" type = battleship model = 1 }
		division = { id = { type = 10000 id = 1097 } name = "USS St. Paul" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1098 } name = "USS Pittsburgh" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1099 } name = "USS Wichita" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1100 } name = "USS San Francisco" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1101 } name = "USS Tuscaloosa" type = heavy_cruiser model = 1 }
		division = { id = { type = 10000 id = 1102 } name = "USS Denver" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1103 } name = "USS Montpelier" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1104 } name = "USS Santa Fe" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1105 } name = "USS St. Louis" type = light_cruiser model = 2 }
		division = { id = { type = 10000 id = 1106 } name = "22nd Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1107 } name = "23rd Destroyer Division" type = destroyer model = 1 }
		}

	navalunit = {
		id = { type = 10000 id = 1108 }
		name = "Task Force 58.3"
		location = 2187 #West of Kyushu
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1109 } name = "USS Maryland" type = battleship model = 2 }
		division = { id = { type = 10000 id = 1110 } name = "USS Colorado" type = battleship model = 2 }
		division = { id = { type = 10000 id = 1111 } name = "USS New Mexico" type = battleship model = 1 }
		division = { id = { type = 10000 id = 1112 } name = "USS Pennsylvania" type = battleship model = 1 }
		division = { id = { type = 10000 id = 1113 } name = "USS Nevada" type = battleship model = 1 }
		division = { id = { type = 10000 id = 1114 } name = "USS Quincy" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1115 } name = "USS Canberra" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1116 } name = "USS Minneapolis" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1117 } name = "USS New Orleans" type = heavy_cruiser model = 2 }
		division = { id = { type = 10000 id = 1118 } name = "USS Portland" type = heavy_cruiser model = 1 }
		division = { id = { type = 10000 id = 1119 } name = "USS Columbia" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1120 } name = "USS Cleveland" type = light_cruiser model = 3 }
		division = { id = { type = 10000 id = 1121 } name = "USS Honolulu" type = light_cruiser model = 2 }
		division = { id = { type = 10000 id = 1122 } name = "USS Boise" type = light_cruiser model = 2 }
		division = { id = { type = 10000 id = 1123 } name = "24th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1124 } name = "25th Destroyer Division" type = destroyer model = 1 }
		}

	navalunit = {
		id = { type = 10000 id = 1125 }
		name = "Task Force 58.4"
		location = 2185 #Off Okinawa
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1126 } name = "4th Escort Carrier Division" type = carrier model = 2 extra = cag brigade_model = 4 }
		division = { id = { type = 10000 id = 1127 } name = "26th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1128 } name = "27th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1129 } name = "28th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1130 } name = "29th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1131 } name = "30th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1132 } name = "31st Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1133 } name = "32nd Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1134 } name = "33rd Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1135 } name = "1st Transport Flotilla" type = transport }
		division = { id = { type = 10000 id = 1136 } name = "2nd Transport Flotilla" type = transport }
		division = { id = { type = 10000 id = 1137 } name = "3rd Transport Flotilla" type = transport }
		}

	navalunit = {
		id = { type = 10000 id = 1138 }
		name = "Task Force 58.5"
		location = 2185 #Off Okinawa
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1139 } name = "5th Escort Carrier Division" type = carrier model = 2 extra = cag brigade_model = 4 }
		division = { id = { type = 10000 id = 1140 } name = "34th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1141 } name = "35th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1142 } name = "36th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1143 } name = "37th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1144 } name = "38th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1145 } name = "39th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1146 } name = "40th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1147 } name = "41st Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1148 } name = "4th Transport Flotilla" type = transport }
		division = { id = { type = 10000 id = 1149 } name = "5th Transport Flotilla" type = transport }
		division = { id = { type = 10000 id = 1150 } name = "6th Transport Flotilla" type = transport }
		}

	navalunit = {
		id = { type = 10000 id = 1151 }
		name = "Task Force 58.6"
		location = 2185 #Off Okinawa
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1152 } name = "6th Escort Carrier Division" type = carrier model = 2 extra = cag brigade_model = 4 }
		division = { id = { type = 10000 id = 1153 } name = "42nd Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1154 } name = "43rd Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1155 } name = "44th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1156 } name = "45th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1157 } name = "46th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1158 } name = "47th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1159 } name = "48th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1160 } name = "49th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1161 } name = "7th Transport Flotilla" type = transport }
		division = { id = { type = 10000 id = 1162 } name = "8th Transport Flotilla" type = transport }
		division = { id = { type = 10000 id = 1163 } name = "9th Transport Flotilla" type = transport }
		}

	navalunit = {
		id = { type = 10000 id = 1164 }
		name = "Task Force 58.7"
		location = 1193 #Okinawa
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1165 } name = "50th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1166 } name = "51st Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1167 } name = "52nd Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1168 } name = "53rd Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1169 } name = "54th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1170 } name = "55th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1171 } name = "10th Transport Flotilla" type = transport }
		division = { id = { type = 10000 id = 1172 } name = "11th Transport Flotilla" type = transport }
		}

	navalunit = {
		id = { type = 10000 id = 1173 }
		name = "Task Force 58.8"
		location = 2262 #South of Formosa
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1174 } name = "7th Escort Carrier Division" type = carrier model = 2 extra = cag brigade_model = 4 }
		division = { id = { type = 10000 id = 1175 } name = "56th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1176 } name = "57th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1177 } name = "58th Destroyer Division" type = destroyer model = 2 }
		division = { id = { type = 10000 id = 1178 } name = "59th Destroyer Division" type = destroyer model = 2 }
		}

	navalunit = {
		id = { type = 10000 id = 1179 }
		name = "1st Submarine Division"
		location = 2193 #Inland Sea
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1180 } name = "1st Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1181 }
		name = "2nd Submarine Division"
		location = 2193 #Inland Sea
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1182 } name = "2nd Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1183 }
		name = "3rd Submarine Division"
		location = 2193 #Inland Sea
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1184 } name = "3rd Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1185 }
		name = "4th Submarine Division"
		location = 2192 #Tsushima Strait
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1186 } name = "4th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1187 }
		name = "5th Submarine Division"
		location = 2192 #Tsushima Strait
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1188 } name = "5th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1189 }
		name = "6th Submarine Division"
		location = 2589 #Tokyo Bay
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1190 } name = "6th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1191 }
		name = "7th Submarine Division"
		location = 2589 #Tokyo Bay
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1192 } name = "7th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1193 }
		name = "8th Submarine Division"
		location = 2213 #Tsugaru Strait
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1194 } name = "8th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1195 }
		name = "9th Submarine Division"
		location = 2187 #North Ryukyu
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1196 } name = "9th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1197 }
		name = "10th Submarine Division"
		location = 2185 #South Ryukyu
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1198 } name = "10th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1199 }
		name = "11th Submarine Division"
		location = 1737 #Manila
		base = 1737 #Manila
		division = { id = { type = 10000 id = 1200 } name = "11th Submarine Division" type = submarine model = 3 }
		}

	navalunit = {
		id = { type = 10000 id = 1201 }
		name = "12th Submarine Division"
		location = 1618 #Ulithi
		base = 1618 #Ulithi
		division = { id = { type = 10000 id = 1202 } name = "12th Submarine Division" type = submarine model = 3 }
		}


	airunit = {
		id = { type = 10000 id = 2000 }
		name = "5th Bombardment (Heavy) Group"
		location = 1739 #Clark Field
		division = { id = { type = 10000 id = 2001 } name = "5th Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2002 }
		name = "307th Bombardment (Heavy) Group"
		location = 1739 #Clark Field
		division = { id = { type = 10000 id = 2003 } name = "307th Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2004 }
		name = "374th Troop Carrier Group"
		location = 1739 #Clark Field
		division = { id = { type = 10000 id = 2005 } name = "374th Troop Carrier Group" strength = 100 type = transport_plane model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2006 }
		name = "433rd Troop Carrier Group"
		location = 1739 #Clark Field
		division = { id = { type = 10000 id = 2007 } name = "433rd Troop Carrier Group" strength = 100 type = transport_plane model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2008 }
		name = "16th Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2009 } name = "16th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2010 }
		name = "19th Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2011 } name = "19th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2012 }
		name = "29th Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2013 } name = "29th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2014 }
		name = "39th Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2015 } name = "39th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2016 }
		name = "330th Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2017 } name = "330th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2018 }
		name = "331st Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2019 } name = "331st Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2020 }
		name = "382nd Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2021 } name = "382nd Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2022 }
		name = "501st Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2023 } name = "501st Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2024 }
		name = "502nd Bombardment (Very Heavy) Group"
		location = 1624 #Guam
		division = { id = { type = 10000 id = 2025 } name = "502nd Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2026 }
		name = "21st Fighter Group"
		location = 1599 #Iwo Jima
		division = { id = { type = 10000 id = 2027 } name = "21st Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2028 }
		name = "414th Fighter Group"
		location = 1599 #Iwo Jima
		division = { id = { type = 10000 id = 2029 } name = "414th Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2030 }
		name = "506th Fighter Group"
		location = 1599 #Iwo Jima
		division = { id = { type = 10000 id = 2031 } name = "506th Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2032 }
		name = "2nd Combat Cargo Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2033 } name = "2nd Combat Cargo Group" strength = 100 type = transport_plane model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2034 }
		name = "3rd Bombardment (Light) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2035 } name = "3rd Bombardment (Light) Group" strength = 100 type = tactical_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2036 }
		name = "8th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2037 } name = "8th Fighter Group" strength = 100 type = multi_role model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2038 }
		name = "11th Bombardment (Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2039 } name = "11th Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2040 }
		name = "22nd Bombardment (Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2041 } name = "22nd Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2042 }
		name = "35th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2043 } name = "35th Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2044 }
		name = "38th Bombardment (Medium) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2045 } name = "38th Bombardment (Medium) Group" strength = 100 type = tactical_bomber model = 3 }
		}

	airunit = {
		id = { type = 10000 id = 2046 }
		name = "41st Bombardment (Medium) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2047 } name = "41st Bombardment (Medium) Group" strength = 100 type = tactical_bomber model = 3 }
		}

	airunit = {
		id = { type = 10000 id = 2048 }
		name = "43rd Bombardment (Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2049 } name = "43rd Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2050 }
		name = "49th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2051 } name = "49th Fighter Group" strength = 100 type = multi_role model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2052 }
		name = "58th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2053 } name = "58th Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2054 }
		name = "90th Bombardment (Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2055 } name = "90th Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2056 }
		name = "312th Bombardment (Light) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2057 } name = "312th Bombardment (Light) Group" strength = 100 type = tactical_bomber model = 4 }
		}

	airunit = {
		id = { type = 10000 id = 2058 }
		name = "317th Troop Carrier Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2059 } name = "317th Troop Carrier Group" strength = 100 type = transport_plane model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2060 }
		name = "318th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2061 } name = "318th Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2062 }
		name = "319th Bombardment (Medium) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2063 } name = "319th Bombardment (Medium) Group" strength = 100 type = cas model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2064 }
		name = "333rd Bombardment (Very Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2065 } name = "333rd Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2066 }
		name = "345th Bombardment (Medium) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2067 } name = "345th Bombardment (Medium) Group" strength = 100 type = tactical_bomber model = 3 }
		}

	airunit = {
		id = { type = 10000 id = 2068 }
		name = "346th Bombardment (Very Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2069 } name = "346th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2070 }
		name = "348th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2071 } name = "348th Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2072 }
		name = "375th Troop Carrier Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2073 } name = "375th Troop Carrier Group" strength = 100 type = transport_plane model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2074 }
		name = "380th Bombardment (Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2075 } name = "380th Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2076 }
		name = "413rd Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2077 } name = "413rd Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2078 }
		name = "417th Bombardment (Light) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2079 } name = "417th Bombardment (Light) Group" strength = 100 type = tactical_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2080 }
		name = "475th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2081 } name = "475th Fighter Group" strength = 100 type = multi_role model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2082 }
		name = "494th Bombardment (Heavy) Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2083 } name = "494th Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2084 }
		name = "507th Fighter Group"
		location = 1193 #Okinawa
		division = { id = { type = 10000 id = 2085 } name = "507th Fighter Group" strength = 100 type = multi_role model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2086 }
		name = "30th Bombardment (Heavy) Group"
		location = 1627 #Saipan
		division = { id = { type = 10000 id = 2087 } name = "30th Bombardment (Heavy) Group" strength = 100 type = strategic_bomber model = 1 }
		}

	airunit = {
		id = { type = 10000 id = 2088 }
		name = "497th Bombardment (Very Heavy) Group"
		location = 1627 #Saipan
		division = { id = { type = 10000 id = 2089 } name = "497th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2090 }
		name = "498th Bombardment (Very Heavy) Group"
		location = 1627 #Saipan
		division = { id = { type = 10000 id = 2091 } name = "498th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2092 }
		name = "499th Bombardment (Very Heavy) Group"
		location = 1627 #Saipan
		division = { id = { type = 10000 id = 2093 } name = "499th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2094 }
		name = "500th Bombardment (Very Heavy) Group"
		location = 1627 #Saipan
		division = { id = { type = 10000 id = 2095 } name = "500th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2096 }
		name = "6th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2097 } name = "6th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2098 }
		name = "9th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2099 } name = "9th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2100 }
		name = "40th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2101 } name = "40th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2102 }
		name = "383rd Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2103 } name = "383rd Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2104 }
		name = "444th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2105 } name = "444th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2106 }
		name = "462nd Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2107 } name = "462nd Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2108 }
		name = "468th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2109 } name = "468th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2110 }
		name = "504th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2111 } name = "504th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2112 }
		name = "505th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2113 } name = "505th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}

	airunit = {
		id = { type = 10000 id = 2114 }
		name = "509th Bombardment (Very Heavy) Group"
		location = 1626 #Tinian
		division = { id = { type = 10000 id = 2115 } name = "509th Bombardment (Very Heavy) Group" strength = 100 type = strategic_bomber model = 2 }
		}


#Operation Coronet Reinforcements

landdivision = { dormant = yes id = { type = 10000 id = 500 } name = "24th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 501 } name = "31st Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 502 } name = "37th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 503 } name = "13rd Armoured Division" strength = 100 type = armor model = 4 }
landdivision = { dormant = yes id = { type = 10000 id = 504 } name = "20th Armoured Division" strength = 100 type = armor model = 4 }
landdivision = { dormant = yes id = { type = 10000 id = 505 } name = "6th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 506 } name = "32nd Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 507 } name = "38th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 508 } name = "97th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 509 } name = "3rd British Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 510 } name = "6th Canadian Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 511 } name = "10th Australian Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 528 } name = "1st Army" strength = 100 type = hq model = 2 }
landdivision = { dormant = yes id = { type = 10000 id = 529 } name = "8th Army" strength = 100 type = hq model = 2 }

#Redeployments from Europe

landdivision = { dormant = yes id = { type = 10000 id = 512 } name = "5th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 513 } name = "44th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 514 } name = "86th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 515 } name = "4th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 516 } name = "8th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 517 } name = "87th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 518 } name = "2nd Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 519 } name = "28th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 520 } name = "35th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 521 } name = "91st Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 522 } name = "95th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 523 } name = "104th Infantry Division" strength = 100 type = infantry model = 5 }
landdivision = { dormant = yes id = { type = 10000 id = 526 } name = "82nd Airborne Division" strength = 100 type = paratrooper model = 3 }
landdivision = { dormant = yes id = { type = 10000 id = 527 } name = "101st Airborne Division" strength = 100 type = paratrooper model = 3 }
landdivision = { dormant = yes id = { type = 10000 id = 530 } name = "4th Army" strength = 100 type = hq model = 2 }

#British Reinforcements

landdivision = { dormant = yes id = { type = 10000 id = 524 } name = "1st British Division" strength = 100 type = infantry model = 4 }
landdivision = { dormant = yes id = { type = 10000 id = 525 } name = "2nd British Division" strength = 100 type = infantry model = 4 }

	}
