
##############################
# Country definition for UTL #
##############################

province = { id = 667 infra = 0.2 metal = 5 max_metal = 5 oil = 23 anti_air = 2 } # Buenos Aires
province = { id = 816 infra = 0.2 rare_materials = 10 energy = 30 oil = 16 } # Trujillo
province = { id = 820 infra = 0.6 energy = 20 rare_materials = 5 } # Solimões
province = { id = 821 infra = 0.6 energy = 20 rare_materials = 5 } # Pucallpa
province = { id = 822 infra = 0.6 energy = 20 rare_materials = 5 } # Rio Branco
province = { id = 823 infra = 0.6 energy = 26 rare_materials = 4 } # Tefé
province = { id = 824 infra = 0.4 energy = 20 air_base = 4 anti_air = 1 } # Manaus
province = { id = 825 infra = 0.6 ic = 5 } # Pôrto Velho
province = { id = 826 infra = 0.4 energy = 20 } # Santarém
province = { id = 827 infra = 0.6 ic = 5 air_base = 3 anti_air = 1 } # Riberalta
province = { id = 828 infra = 0.6 ic = 5 } # Cobija
province = { id = 829 infra = 0.2 energy = 10 rare_materials = 5 } # Cuzco
province = { id = 830 infra = 0.2 metal = 7 max_metal = 7 naval_base = 2 air_base = 5 anti_air = 2 } # Lima
province = { id = 831 infra = 0.2 } # Arequipa
province = { id = 832 infra = 0.2 metal = 10 max_metal = 10 } # La Paz
province = { id = 833 infra = 0.6 ic = 5 } # Perseverancia
province = { id = 834 infra = 0.4 ic = 5 } # Cuiabá
province = { id = 835 infra = 0.4 ic = 5 rare_materials = 5 energy = 20 } # Mato Grosso
province = { id = 836 infra = 0.4 ic = 5 energy = 30 rare_materials = 5 oil = 10 } # Santa Cruz
province = { id = 837 infra = 0.4 energy = 30 oil = 10 } # Asunción
province = { id = 838 infra = 0.4 metal = 5 max_metal = 5 } # Sucre
province = { id = 839 infra = 0.2 metal = 25 max_metal = 25 } # Antofagasta
province = { id = 840 infra = 0.2 metal = 5 max_metal = 5 anti_air = 1 } # Santiago
province = { id = 841 infra = 0.2 } # Juan Fernández Archipelago
province = { id = 842 infra = 0.2 } # Isla San Félix
province = { id = 843 infra = 0.4 } # San Miguel de Tucumán
province = { id = 844 infra = 0.4 ic = 5 oil = 15 air_base = 3 anti_air = 1 } # Corrientes
province = { id = 845 infra = 0.4 oil = 10 } # Córdoba
province = { id = 846 infra = 0.2 oil = 10 } # Ciudad del Este
province = { id = 847 infra = 0.2 anti_air = 1 } # Curitiba
province =
{ id             = 848
  infra          = 0.2
  anti_air       = 2
  air_base       = { size = 4 current_size = 4 }
  naval_base     = { size = 8 current_size = 8 }
  rare_materials = 5
  energy         = 10
}                  # Pôrto Alegre
province = { id = 849 infra = 0.2 metal = 2 max_metal = 2 oil = 10 anti_air = 1 } # Montevideo
province = { id = 850 infra = 0.2 oil = 10 } # Concordia
province = { id = 851 infra = 0.2 } # Rosario
province = { id = 852 infra = 0.2 naval_base = 2 anti_air = 1 } # Mar del Plata
province = { id = 853 infra = 0.2 ic = 5 } # Bahia Blanca
province = { id = 854 infra = 0.2 ic = 5 } # Viedma
province = { id = 855 infra = 0.6 } # Neuquén
province = { id = 856 infra = 0.2 } # Puerto Montt
province = { id = 857 infra = 0.2 } # Puerto Madryn
province = { id = 858 infra = 0.4 ic = 5 } # Comodoro Rivadavia
province = { id = 859 infra = 0.6 ic = 5 } # San Carlos de Bariloche
province = { id = 860 infra = 0.4 ic = 5 naval_base = 3 anti_air = 1 } # Puerto Aisén
province = { id = 861 infra = 0.4 ic = 5 } # Wellington
province = { id = 862 infra = 0.6 ic = 5 } # Sarmiento
province = { id = 863 infra = 0.4 ic = 6 anti_air = 1 } # Santa Cruz
province = { id = 864 infra = 0.4 ic = 6 } # Punta Arenas
province = { id = 865 infra = 0.4 ic = 6 } # Tierra del Fuego
province = { id = 866 infra = 0.4 ic = 5 naval_base = 2 air_base = 2 anti_air = 1 } # Falkland Islands
province = { id = 871 infra = 0.2 } # Cuyuni
province = { id = 872 infra = 0.4 } # Boa Vista
province = { id = 873 infra = 0.2 } # Georgetown
province = { id = 874 infra = 0.2 } # Paramaribo
province = { id = 875 infra = 0.2 } # Cayenne
province = { id = 876 infra = 0.2 } # Macapá
province = { id = 877 infra = 0.2 naval_base = 5 anti_air = 1 } # Marajó
province = { id = 878 infra = 0.4 } # Marabá
province = { id = 879 infra = 0.2 } # Belém
province = { id = 880 infra = 0.2 } # Fortaleza
province = { id = 881 infra = 0.2 anti_air = 2 } # Recife
province = { id = 882 infra = 0.2 } # Salvador
province = { id = 883 infra = 0.4 anti_air = 2 } # Goiás
province = { id = 884 infra = 0.2 } # Vitória
province =
{ id         = 885
  infra      = 0.2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 2
}              # Rio de Janeiro
province =
{ id             = 886
  infra          = 0.2
  anti_air       = 1
  air_base       = { size = 4 current_size = 4 }
  naval_base     = { size = 6 current_size = 6 }
  metal          = 3
  max_metal      = 3
  rare_materials = 7
  energy         = 16
}                  # São Paulo
province = { id = 887 infra = 0.2 } # Campinas

#####################
# Country main data #
#####################

country =
{ tag                    = UTL
  belligerence           = 50
  ai 			 = "globalwar/BRA.ai"
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  manpower               = 1000
  capital                = 885
  transports             = 100
  escorts                = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 10
    free_market       = 6
    freedom           = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  nationalprovinces      = { 848 847 835 834 825 823 822 820 872 824 826 878 876 877 879 883 887 886 885 884 882 880 881 849 837 846 831 829 830 821
			     874 875 836 833 838 832 828 827 864 861 860 856 840 839 841 842 667 853 852 843 844 845 851 854 855 857 858 859 862
			     863 865 850 866 871 873 816 818 819 868 869 870
			   }
  ownedprovinces         = { 848 847 835 834 825 823 822 820 872 824 826 878 876 877 879 883 887 886 885 884 882 880 881 849 837 846 831 829 830 821
			     816 874 875 836 833 838 832 828 827 864 861 860 856 840 839 841 842 667 853 852 843 844 845 851 854 855 857 858 859 862
			     863 865 850 866 871 873
			   }
  controlledprovinces    = { 848 847 835 834 825 823 822 820 872 824 826 878 876 877 879 883 887 886 885 884 882 880 881 849 837 846 831 829 830 821
			     816 874 875 836 833 838 832 828 827 864 861 860 856 840 839 841 842 667 853 852 843 844 845 851 854 855 857 858 859 862
			     863 865 850 866 871 873
			   }
  # Semi-Major Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5010 5080 8010 8020 8030 8040 8050 9010 }




  diplomacy =
  {
	relation = { tag = UIR value = 200 }

 }




  landunit =
  { id       = { type = 30013 id = 1 }
    name     = "1. Corps"
    location = 885
    division =
    { id       = { type = 30013 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 3 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 4 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30013 id = 5 }
    name     = "2. Corps"
    location = 885
    division =
    { id       = { type = 30013 id = 6 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 7 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 8 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30013 id = 9 }
    name     = "3. Corps"
    location = 885
    division =
    { id       = { type = 30013 id = 10 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 11 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 12 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30013 id = 13 }
    name     = "4. Corps"
    location = 885
    division =
    { id       = { type = 30013 id = 14 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 15 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30013 id = 16 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30013 id = 17 }
    name     = "Armored Corps"
    location = 885
    division =
    { type  = armor
      model = 0
      id    = { type = 30013 id = 18 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30013 id = 19 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30013 id = 20 }
      name  = "3rd Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30013 id = 193 }
    name     = "Main Fleet"
    location = 885
    base     = 885
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30013 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30013 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30013 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30013 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30013 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30013 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30013 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30013 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30013 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30013 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30013 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30013 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30013 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30013 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30013 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30013 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30013 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30013 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30013 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30013 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30013 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30013 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30013 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30013 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30013 id = 173 }
    name     = "Bomber Group 1"
    location = 885
    base     = 885
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30013 id = 178 }
    name     = "Bomber Group 2"
    location = 885
    base     = 885
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30013 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30013 id = 183 }
    name     = "Fighter Group 1"
    location = 885
    base     = 885
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30013 id = 188 }
    name     = "Fighter Group 2"
    location = 885
    base     = 885
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30013 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
