
##############################
# Country definition for CHI #
##############################

province = { id = 1204 infra = 0.3 } # Tianjin
province = { id = 1205 infra = 0.2 } # Beiping
province = { id = 1206 infra = 0.4 } # Kalgan
province = { id = 1207 infra = 0.5 } # Jining
province = { id = 1208 infra = 0.6 } # Hohhot
province = { id = 1209 infra = 0.4 } # Datong
province = { id = 1210 infra = 0.4 } # Baoding
province = { id = 1211 infra = 0.4 } # Shijiazhuang
province = { id = 1212 infra = 0.4 } # Handan
province = { id = 1213 infra = 0.4 } # Yucheng
province = { id = 1214 infra = 0.4 } # Yantai
province =
{ id         = 1215
  infra      = 0.4
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 3
}              # Qingdao
province = { id = 1216 infra = 0.4 anti_air = 1 } # Jinan
province = { id = 1217 infra = 0.4 } # Lianyungang
province = { id = 1218 infra = 0.4 } # Xuzhou
province = { id = 1219 infra = 0.4 } # Nantong
province = { id = 1220 infra = 0.5 } # Yangzhou
province = { id = 1221 infra = 0.4 } # Hefei
province = { id = 1222 infra = 0.4 } # Fuyang
province = { id = 1223 infra = 0.4 } # Kaifeng
province = { id = 1224 infra = 0.5 energy = 10 } # Anyang
province = { id = 1225 infra = 0.4 anti_air = 1 } # Taiyuan
province = { id = 1226 infra = 0.4 } # Changzhi
province = { id = 1227 infra = 0.5 energy = 30 metal = 10 rare_materials = 10 oil = 20 } # Luoyang
province = { id = 1228 infra = 0.5 } # Zhengzhou
province = { id = 1229 infra = 0.6 ic = 4 air_base = 9 anti_air = 3 } # Nanyang
province = { id = 1230 infra = 0.5 energy = 10 } # Xinyang
province = { id = 1231 infra = 0.5 energy = 10 } # Xiangfan
province = { id = 1232 infra = 0.5 } # Hankou
province = { id = 1233 infra = 0.4 energy = 21 } # Anqing
province = { id = 1234 infra = 0.4 } # Wuhu
province = { id = 1235 infra = 0.3 ic = 1 anti_air = 2 } # Nanjing
province = { id = 1236 infra = 0.3 } # Suzhou
province =
{ id         = 1237
  infra      = 0.2
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 2
}              # Shanghai
province =
{ id       = 1238
  infra    = 0.4
  air_base = { size = 10 current_size = 10 }
  anti_air = 2
}            # Hangzhou
province = { id = 1239 infra = 0.4 } # Ningbo
province = { id = 1240 infra = 0.4 } # Wenzhou
province = { id = 1241 infra = 0.5 } # Quzhou
province = { id = 1242 infra = 0.5 } # Shangrao
province = { id = 1243 infra = 0.5 } # Nanping
province =
{ id       = 1244
  infra    = 0.4
  air_base = { size = 1 current_size = 1 }
  anti_air = 1
}            # Fuzhou
province = { id = 1245 infra = 0.4 } # Quanzhou
province = { id = 1246 infra = 0.6 } # Longyan
province = { id = 1247 infra = 0.4 } # Xiamen
province = { id = 1248 infra = 0.4 } # Shantou
province = { id = 1249 infra = 0.4 } # Chao'an
province = { id = 1250 infra = 0.4 } # Ganzhou
province =
{ id       = 1251
  infra    = 0.3
  air_base = { size = 10 current_size = 10 }
  anti_air = 2
}            # Nanchang
province = { id = 1252 infra = 0.5 } # Jiujiang
province = { id = 1253 infra = 0.5 } # Wuchang
province = { id = 1254 infra = 0.5 } # Pingxiang
province = { id = 1255 infra = 0.5 } # Changsha
province = { id = 1256 infra = 0.5 } # Zhuzhou
province = { id = 1257 infra = 0.5 } # Hengyang
province = { id = 1258 infra = 0.4 } # Guilin
province = { id = 1259 infra = 0.5 } # Shaoyang
province = { id = 1260 infra = 0.5 ic = 4 } # Changde
province = { id = 1261 infra = 0.5 ic = 4 } # Huaihua
province = { id = 1262 infra = 0.5 } # Zunyi
province = { id = 1263 infra = 0.5 ic = 4 } # Fuling
province = { id = 1264 infra = 0.5 } # Enshi
province = { id = 1265 infra = 0.5 } # Wanxian
province = { id = 1266 infra = 0.5 } # Yichang
province = { id = 1267 infra = 0.5 energy = 20 metal = 10 rare_materials = 5 oil = 20 } # Ankang
province = { id = 1268 infra = 0.5 } # Nancheng
province = { id = 1269 infra = 0.5 ic = 4 energy = 20 metal = 10 rare_materials = 5 oil = 15 anti_air = 1 } # Xi'an
province = { id = 1270 infra = 0.4 ic = 4 } # Xianyang
province = { id = 1271 infra = 0.4 } # Yan'an
province = { id = 1272 infra = 0.7 air_base = 7 anti_air = 1 } # Yuling
province = { id = 1273 infra = 0.7 ic = 4 } # Yinchuan
province = { id = 1274 infra = 0.7 ic = 4 } # Guyuan
province = { id = 1275 infra = 0.6 } # Pingliang
province = { id = 1276 infra = 0.7 } # Lanzhou
province = { id = 1277 infra = 0.6 } # Tianshui
province = { id = 1278 infra = 0.5 } # Baoji
province = { id = 1279 infra = 0.5 } # Nanchong
province = { id = 1280 infra = 0.3 } # Chongqing
province = { id = 1281 infra = 0.7 ic = 4 } # Ya'an
province = { id = 1282 infra = 0.7 ic = 4 } # Kangding
province = { id = 1283 infra = 0.6 } # Qamdo
province = { id = 1293 infra = 0.6 } # Xiaguan
province = { id = 1294 infra = 0.6 } # Baoshan
province = { id = 1305 infra = 0.7 } # Jinghong
province = { id = 1307 infra = 0.4 air_base = 1 anti_air = 3 } # Kunming
province = { id = 1308 infra = 0.5 } # Qujing
province = { id = 1309 infra = 0.5 } # Bose
province = { id = 1310 infra = 0.5 ic = 4 } # Liuzhou
province = { id = 1311 infra = 0.5 } # Wuzhou
province = { id = 1312 infra = 0.5 } # Shaoguan
province = { id = 1313 infra = 0.4 anti_air = 1 } # Guangzhou
province = { id = 1314 infra = 0.3 } # Bao'an
province = { id = 1317 infra = 0.4 } # Jiangmen
province = { id = 1318 infra = 0.4 } # Maoming
province = { id = 1319 infra = 0.4 } # Nanning
province = { id = 1320 infra = 0.4 } # Zhanjiang
province = { id = 1321 infra = 0.4 air_base = 3 naval_base = 4 anti_air = 2 } # Hainan
province = { id = 1325 infra = 0.4 } # Qinzhou
province = { id = 1327 infra = 0.5 } # Wenshan
province =
{ id       = 1360
  infra    = 0.4
  air_base = { size = 3 current_size = 3 }
  anti_air = 2
}            # Chengdu
province = { id = 1361 infra = 0.4 } # Zigong
province = { id = 1362 infra = 0.5 } # Zhaotung
province = { id = 1363 infra = 0.4 } # Anshun
province = { id = 1364 infra = 0.5 } # Guiyang
province = { id = 1365 infra = 0.5 ic = 4 air_base = 2 anti_air = 1 } # Kaili
province = { id = 1385 infra = 0.4 } # Bayan Tumen
province = { id = 1399 infra = 0.4 } # Saynshand
province = { id = 1404 infra = 0.6 anti_air = 1 } # Ulan Bator
province = { id = 1419 infra = 0.6 } # Muren
province = { id = 1420 infra = 0.6 } # Khobdo
province = { id = 1421 infra = 0.4 energy = 20 metal = 10 rare_materials = 5 oil = 20 } # Altay
province = { id = 1430 infra = 0.4 } # Kashgar
province = { id = 1431 infra = 0.4 } # Aksu
province = { id = 1432 infra = 0.4 } # Gulja
province = { id = 1433 infra = 0.4 air_base = 4 anti_air = 2 } # Urumqi
province = { id = 1434 infra = 0.6 } # Yusun Bulag
province = { id = 1435 infra = 0.4 ic = 4 } # Qumul
province = { id = 1436 infra = 0.6 energy = 20 metal = 10 rare_materials = 20 oil = 20 } # Bayan Hongor
province = { id = 1437 infra = 0.6 energy = 20 metal = 10 rare_materials = 5 oil = 10 air_base = 1 anti_air = 1 } # Arvayheer
province = { id = 1438 infra = 0.6 energy = 20 metal = 6 rare_materials = 3 oil = 10 } # Dalan Dzadagad
province = { id = 1439 infra = 0.7 ic = 4 } # Bayan Nur
province = { id = 1440 infra = 0.6 } # Jinchang
province = { id = 1441 infra = 0.4 } # Dunhuang
province = { id = 1442 infra = 0.4 ic = 4 anti_air = 1 } # Golmud
province = { id = 1443 infra = 0.6 ic = 4 energy = 20 metal = 10 rare_materials = 5 oil = 10 air_base = 6 anti_air = 1 } # Xining
province = { id = 1444 infra = 0.6 ic = 4 } # Yushu
province = { id = 1445 infra = 0.6 ic = 4 } # Korla
province = { id = 1446 infra = 0.8 ic = 4 } # Taklimakan Desert
province = { id = 1447 infra = 0.4 } # Hotan
province = { id = 1448 infra = 0.8 } # Gar
province = { id = 1450 infra = 0.6 ic = 4 } # Nagqu
province = { id = 1451 infra = 0.8 } # Kagar
province = { id = 1452 infra = 0.4 } # Xigaze
province = { id = 1453 infra = 0.4 } # Lhasa

#####################
# Country main data #
#####################

country =
{ tag                    = UCH
  ai 			 = "globalwar/CHI.ai"
  capital                = 1235 # Nanjing
  belligerence           = 50
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 1000
  oil                    = 1000
  supplies               = 1000
  money                  = 10
  manpower               = 1000
  transports             = 100
  escorts                = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 7
    free_market       = 6
    freedom           = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  diplomacy =
  {
  }

  nationalprovinces      = { 1276 1277 1267 1268 1269 1278 1222 1223 1224 1227 1228 1229 1230 1214 1215 1218 1221 1233 1234 1217 1219 1220 1235 1236
			     1237 1263 1265 1279 1280 1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259
			     1260 1261 1242 1250 1251 1252 1254 1243 1244 1245 1246 1247 1316 1258 1310 1311 1309 1319 1325 1312 1313 1249 1248 1314
			     1317 1318 1320 1321 1270 1271 1275 1204 1205 1206 1210 1211 1212 1213 1216 1207 1208 1272 1209 1225 1226 1442 1441 1273
			     1440 1443 1274 1444 1439 1293 1294 1305 1307 1308 1327 1362 1281 1282 1421 1432 1433 1435 1445 1446 1447 1430 1431 1420
			     1419 1434 1436 1437 1438 1399 1404 1385 1283 1448 1450 1451 1452 1453 1315 1203 1397 1398 1386 1387 1382 1383 1384 1520
			     1557 1423 1422 1429 1484 1483 1475 1474 1473 1455 1454 1284 1878 1877 1291 1898 1292 1295 1304 1306 1326
			   }
  ownedprovinces         = { 1276 1277 1267 1268 1269 1278 1222 1223 1224 1227 1228 1229 1230 1214 1215 1218 1221 1233 1234 1217 1219 1220 1235 1236
			     1237 1263 1265 1279 1280 1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259
			     1260 1261 1242 1250 1251 1252 1254 1243 1244 1245 1246 1247 1316 1258 1310 1311 1309 1319 1325 1312 1313 1249 1248 1314
			     1317 1318 1320 1321 1270 1271 1275 1204 1205 1206 1210 1211 1212 1213 1216 1207 1208 1272 1209 1225 1226 1442 1441 1273
			     1440 1443 1274 1444 1439 1293 1294 1305 1307 1308 1327 1362 1281 1282 1421 1432 1433 1435 1445 1446 1447 1430 1431 1420
			     1419 1434 1436 1437 1438 1399 1404 1385 1283 1448 1450 1451 1452 1453 1315
			   }

  controlledprovinces    = { 1276 1277 1267 1268 1269 1278 1222 1223 1224 1227 1228 1229 1230 1214 1215 1218 1221 1233 1234 1217 1219 1220 1235 1236
			     1237 1263 1265 1279 1280 1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259
			     1260 1261 1242 1250 1251 1252 1254 1243 1244 1245 1246 1247 1316 1258 1310 1311 1309 1319 1325 1312 1313 1249 1248 1314
			     1317 1318 1320 1321 1270 1271 1275 1204 1205 1206 1210 1211 1212 1213 1216 1207 1208 1272 1209 1225 1226 1442 1441 1273
			     1440 1443 1274 1444 1439 1293 1294 1305 1307 1308 1327 1362 1281 1282 1421 1432 1433 1435 1445 1446 1447 1430 1431 1420
			     1419 1434 1436 1437 1438 1399 1404 1385 1283 1448 1450 1451 1452 1453 1315
			   }


  # ######################

 techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5080 8010 8020 8030 8040 8050 9010 }

  landunit =
  { id       = { type = 30016 id = 1 }
    name     = "1. Corps"
    location = 1235
    division =
    { id       = { type = 30016 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 3 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 4 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30016 id = 5 }
    name     = "2. Corps"
    location = 1235
    division =
    { id       = { type = 30016 id = 6 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 7 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 8 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30016 id = 9 }
    name     = "3. Corps"
    location = 1235
    division =
    { id       = { type = 30016 id = 10 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 11 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 12 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30016 id = 13 }
    name     = "4. Corps"
    location = 1235
    division =
    { id       = { type = 30016 id = 14 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 15 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30016 id = 16 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30016 id = 17 }
    name     = "Armored Corps"
    location = 1235
    division =
    { type  = armor
      model = 0
      id    = { type = 30016 id = 18 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30016 id = 19 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30016 id = 20 }
      name  = "3rd Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30016 id = 193 }
    name     = "Main Fleet"
    location = 1237
    base     = 1237
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30016 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30016 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30016 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30016 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30016 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30016 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30016 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30016 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30016 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30016 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30016 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30016 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30016 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30016 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30016 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30016 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30016 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30016 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30016 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30016 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30016 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30016 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30016 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30016 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30016 id = 173 }
    name     = "Bomber Group 1"
    location = 1238
    base     = 1238
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30016 id = 178 }
    name     = "Bomber Group 2"
    location = 1238
    base     = 1238
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30016 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30016 id = 183 }
    name     = "Fighter Group 1"
    location = 1238
    base     = 1238
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30016 id = 188 }
    name     = "Fighter Group 2"
    location = 1238
    base     = 1238
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30016 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
