
##############################
# Country definition for UCS #
##############################

province = { id = 539 infra = 0.2 } # Managua
province = { id = 540 infra = 0.2 } # San José
province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province = { id = 642 metal = 0 max_metal = 0 } # Nashville
province = { id = 643 infra = 0.2 } # Asheville
province =
{ id        = 644
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 0
  max_metal = 0
}             # Charleston
province = { id = 645 metal = 0 max_metal = 0 } # Columbia
Province =
{ id                 = 648
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  rare_materials     = 0
  max_rare_materials = 0
  energy             = 11
}                      # Jacksonville
province = { id = 649 rare_materials = 0 max_rare_materials = 0 } # Tampa
province =
{ id                 = 651
  anti_air           = 1
  air_base           = { size = 10 current_size = 10 }
  Naval_base         = { size = 10 current_size = 10 }
  rare_materials     = 0
  max_rare_materials = 0
}                      # Miami
province =
{ id       = 652
  infra    = 0.2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic       = 1
}            # Andros
province = { id = 653 infra = 0.2 } # New Providence
province = { id = 654 infra = 0.2 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Havana
province = { id = 655 infra = 0.2 metal = 0 max_metal = 0 } # Santa Clara
province = { id = 656 infra = 0.2 ic = 12 } # Camagüey
province = { id = 657 infra = 0.2 } # Guantánamo
province = { id = 664 infra = 0.2 ic = 2 } # Grand Bahama
province = { id = 665 infra = 0.2 ic = 2 } # The Abacos
province = { id = 666 infra = 0.2 } # Eleuthera
province = { id = 668 infra = 0.2 } # Long Island
province = { id = 669 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Augusta
province =
{ id                 = 670
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  metal              = 0
  max_metal          = 0
  rare_materials     = 0
  max_rare_materials = 0
}                      # Atlanta
province = { id = 671 infra = 0.2 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Chattanooga
province = { id = 672 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Birmingham
province =
{ id                 = 673
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  metal              = 0
  max_metal          = 0
  rare_materials     = 0
  max_rare_materials = 0
}                      # Memphis
province = { id = 675 metal = 0 max_metal = 0 oil = 0 max_oil = 0 } # Jackson
province = { id = 676 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Mobile
province = { id = 677 rare_materials = 0 max_rare_materials = 0 } # Tallahassee
province =
{ id        = 678
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 0
  max_metal = 0
}             # Biloxi
province = { id = 679 metal = 0 max_metal = 0 } # Baton Rouge
province = { id = 680 metal = 0 max_metal = 0 } # New Orleans
province = { id = 682 oil = 0 max_oil = 0 } # Monroe
province =
{ id        = 684
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 4
  max_metal = 4
}             # Little Rock
Province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  oil      = 0
  max_oil  = 0
}            # Oklahoma City
province = { id = 715 rare_materials = 0 max_rare_materials = 0 oil = 0 max_oil = 0 } # Dallas
province =
{ id                 = 716
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  rare_materials     = 49
  max_rare_materials = 49
  oil                = 0
  max_oil            = 0
}                      # Houston
province = { id = 718 infra = 0.2 } # El Paso
province = { id = 721 oil = 0 max_oil = 0 } # Lubbock
province = { id = 722 infra = 0.2 oil = 0 max_oil = 0 } # Roswell
province = { id = 723 infra = 0.2 } # Las Cruces
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province = { id = 726 infra = 0.2 oil = 0 max_oil = 0 } # Los Alamos
province = { id = 727 infra = 0.2 } # Silver City
province = { id = 737 infra = 0.2 } # Mexicali
province = { id = 738 infra = 0.2 } # La Paz
province = { id = 739 infra = 0.2 } # Hermosillo
province = { id = 740 infra = 0.2 } # Nogales
province = { id = 741 infra = 0.2 } # Ciudad Juárez
province = { id = 742 infra = 0.2 air_base = 5 anti_air = 3 } # Chihuahua
province = { id = 743 infra = 0.2 naval_base = 3 anti_air = 2 } # Culiacán
province = { id = 744 infra = 0.2 } # Durango
province = { id = 745 infra = 0.2 } # Monclova
province = { id = 747 infra = 0.2 anti_air = 1 } # Monterrey
Province =
{ id         = 748
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 8 current_size = 8 }
  anti_air   = 3
}              # Corpus Christi
province = { id = 749 infra = 0.2 oil = 0 max_oil = 0 } # Tampico
province = { id = 750 infra = 0.2 energy = 19 } # León
province = { id = 751 infra = 0.2 anti_air = 1 } # Guadalajara
province = { id = 752 infra = 0.2 anti_air = 2 energy = 24 } # Mexico City
province = { id = 753 infra = 0.2 } # Puebla
province =
{ id         = 754
  infra      = 0.2
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # Acapulco
province = { id = 755 infra = 0.2 oil = 0 max_oil = 0 } # Villahermosa
province = { id = 756 infra = 0.2 } # Mérida
province =
{ id         = 757
  infra      = 0.2
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Guatemala
province = { id = 758 infra = 0.2 } # Belize City
province = { id = 759 infra = 0.2 } # San Salvador
province = { id = 760 infra = 0.2 } # Tegucigalpa
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  oil      = 3
  max_oil  = 3
}            # Tulsa
province = { id = 801 infra = 0.2 } # Curacao
province = { id = 802 infra = 0.2 naval_base = 3 air_base = 3 anti_air = 1 } # Barquisimeto
province = { id = 803 infra = 0.2 } # Barranquilla
province = { id = 804 infra = 0.2 } # Maracaibo
province = { id = 805 infra = 0.2 ic = 2 } # St. Lucia
province = { id = 806 infra = 0.2 ic = 2 } # St. George's
province = { id = 807 infra = 0.2 ic = 2 naval_base = 2 air_base = 2 anti_air = 1 } # Barbados
province = { id = 808 infra = 0.2 ic = 2 } # Tobago
province = { id = 809 infra = 0.2 ic = 2 oil = 0 max_oil = 0 } # Trinidad
province = { id = 810 infra = 0.2 } # Cumaná
province = { id = 811 infra = 0.2 } # Caracas
province = { id = 812 infra = 0.4 } # Cúcuta
province = { id = 813 infra = 0.2 air_base = 8 anti_air = 3 } # Bogotá
province = { id = 814 infra = 0.2 } # Guayaquil
province = { id = 815 infra = 0.2 } # Quito
province = { id = 817 infra = 0.4 } # Tigre
province = { id = 818 infra = 0.6 } # Iquitos
province = { id = 819 infra = 0.6 } # Mitú
province = { id = 867 infra = 0.4 } # Angostura Falls
province = { id = 868 infra = 0.6 } # Inirida
province = { id = 869 infra = 0.4 } # Ciudad Bolivar
province = { id = 870 infra = 0.2 } # Ciudad Guayana
province = { id = 888 infra = 0.2 } # Panamá
province =
{ id         = 889
  infra      = 0.2
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
}              # Colon
province = { id = 890 infra = 0.2 } # Medellín
province = { id = 891 infra = 0.2 ic = 2 } # Jamaica
province = { id = 892 infra = 0.2 naval_base = 4 air_base = 4 anti_air = 3 } # Port-au-Prince
province = { id = 893 infra = 0.2 } # Santiago
province = { id = 894 infra = 0.2 } # Santo Domingo
province = { id = 895 infra = 0.2 } # Puerto Rico
province = { id = 896 infra = 0.2 ic = 2 } # Virgin Islands
province = { id = 897 infra = 0.2 ic = 2 } # Antigua
province = { id = 898 infra = 0.2 ic = 2 } # Guadelope
province = { id = 899 infra = 0.2 ic = 2 } # Martinique

#####################
# Country main data #
#####################

country =
{ tag                    = UCS
  ai 			 = "globalwar/MEX.ai"
  belligerence           = 50
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  capital                = 752
  manpower               = 1000
  transports             = 100
  escorts                = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 1
    freedom           = 6
    free_market       = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  nationalprovinces      = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 814 815 817 818 718 746 717 721 720 719 715 716
			     748 722 723 724 725 726 727 712 713 714 793 680 681 682 683 684 685 686 670 671 672 673 674 675 676 677 678 679 669 634
			     635 636 637 642 643 644 645 646 647 648 649 650 651 895 889 652 653 664 665 666 668 758 805 806 807 808 809 891 896 897
			     801 804 802 810 811 869 870 654 655 656 657 757 539 540 759 760 803 812 813 890 867 819 868 888 892 893 894 898 899 633
			     632 638 639 640 641 687 688 792 711 710 709 708 728 729 736 761 816 821 820 872 871
			   }
  ownedprovinces         = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 814 815 817 818 718 746 717 721 720 719 715 716
			     748 722 723 724 725 726 727 712 713 714 793 680 681 682 683 684 685 686 670 671 672 673 674 675 676 677 678 679 669 634
			     635 636 637 642 643 644 645 646 647 648 649 650 651 895 889 652 653 664 665 666 668 758 805 806 807 808 809 891 896 897
			     801 804 802 810 811 869 870 654 655 656 657 757 539 540 759 760 803 812 813 890 867 819 868 888 892 893 894 898 899
			   }
  controlledprovinces    = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 814 815 817 818 718 746 717 721 720 719 715 716
			     748 722 723 724 725 726 727 712 713 714 793 680 681 682 683 684 685 686 670 671 672 673 674 675 676 677 678 679 669 634
			     635 636 637 642 643 644 645 646 647 648 649 650 651 895 889 652 653 664 665 666 668 758 805 806 807 808 809 891 896 897
			     801 804 802 810 811 869 870 654 655 656 657 757 539 540 759 760 803 812 813 890 867 819 868 888 892 893 894 898 899
			   }

  # ######################
 techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5080 8010 8020 8030 8040 8050 9010 }


  landunit =
  { id       = { type = 30002 id = 1 }
    name     = "1. Corps"
    location = 752
    division =
    { id       = { type = 30002 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 3 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 4 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 5 }
    name     = "2. Corps"
    location = 752
    division =
    { id       = { type = 30002 id = 6 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 7 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 8 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 9 }
    name     = "3. Corps"
    location = 752
    division =
    { id       = { type = 30002 id = 10 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 11 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 12 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 13 }
    name     = "4. Corps"
    location = 752
    division =
    { id       = { type = 30002 id = 14 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 15 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30002 id = 16 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 17 }
    name     = "Armored Corps"
    location = 752
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 18 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 19 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 20 }
      name  = "3rd Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30002 id = 193 }
    name     = "Main Fleet"
    location = 754
    base     = 754
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30002 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30002 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30002 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30002 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30002 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30002 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30002 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30002 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30002 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30002 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30002 id = 173 }
    name     = "Bomber Group 1"
    location = 754
    base     = 754
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30002 id = 178 }
    name     = "Bomber Group 2"
    location = 754
    base     = 754
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30002 id = 183 }
    name     = "Fighter Group 1"
    location = 754
    base     = 754
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30002 id = 188 }
    name     = "Fighter Group 2"
    location = 754
    base     = 754
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
