
###############################
# Victory points distribution #
###############################

province = { id = 7 points = 1 } # Aberdeen
province = { id = 8 points = 1 } # Dunfermline
province = { id = 9 points = 1 } # Glasgow
province = { id = 10 points = 1 } # Edinburgh
province = { id = 11 points = 1 } # Sunderland
province = { id = 12 points = 1 } # Blackpool
province = { id = 14 points = 4 } # Liverpool
province = { id = 16 points = 4 } # Birmingham
province = { id = 19 points = 5 } # London
province = { id = 28 points = 1 } # Belfast
province = { id = 30 points = 2 } # Dublin
province = { id = 39 points = 2 } # Caen
province = { id = 41 points = 1 } # Le Havre
province = { id = 43 points = 2 } # Dunkerque
province = { id = 44 points = 2 } # Lille
province = { id = 45 points = 1 } # Ghent
province = { id = 46 points = 1 } # Rotterdam
province = { id = 47 points = 2 } # Amsterdam
province = { id = 48 points = 1 } # Utrecht
province = { id = 49 points = 1 } # Eindhoven
province = { id = 50 points = 1 } # Antwerp
province = { id = 51 points = 2 } # Brussels
province = { id = 52 points = 1 } # Mons
province = { id = 56 points = 2 } # Paris
province = { id = 65 points = 1 } # Namur
province = { id = 67 points = 1 } # Essen
province = { id = 68 points = 1 } # Liège
province = { id = 70 points = 1 } # Arlon
province = { id = 71 points = 1 } # Luxembourg
province = { id = 73 points = 2 } # Strasbourg
province = { id = 74 points = 1 } # Saarbrücken
province = { id = 75 points = 2 } # Cologne
province = { id = 76 points = 1 } # Dortmund
province = { id = 77 points = 1 } # Arnhem
province = { id = 78 points = 1 } # Leeuwarden
province = { id = 79 points = 1 } # Groningen
province = { id = 80 points = 1 } # Wilhelmshafen
province = { id = 81 points = 1 } # Münster
province = { id = 82 points = 1 } # Kassel
province = { id = 83 points = 1 } # Schweinfurt
province = { id = 86 points = 1 } # Hannover
province = { id = 87 points = 1 } # Bremen
province = { id = 88 points = 1 } # Hamburg
province = { id = 90 points = 1 } # Kiel
province = { id = 92 points = 1 } # Århus
province = { id = 96 points = 2 } # Gotland
province = { id = 100 points = 2 } # Norrköping
province = { id = 101 points = 3 } # Stockholm
province = { id = 102 points = 2 } # Uppsala
province = { id = 103 points = 2 } # Åland
province = { id = 104 points = 2 } # Västerås
province = { id = 105 points = 2 } # Karlstad
province = { id = 107 points = 2 } # Oslo
province = { id = 111 points = 2 } # Hamar
province = { id = 112 points = 2 } # Ludvika
province = { id = 113 points = 2 } # Falun
province = { id = 116 points = 2 } # Röros
province = { id = 119 points = 2 } # Östersund
province = { id = 120 points = 2 } # Sundsvall
province = { id = 121 points = 2 } # Vilhelmina
province = { id = 123 points = 1 } # Gällivare
province = { id = 126 points = 1 } # Kiruna
province = { id = 130 points = 1 } # Rovaniemi
province = { id = 132 points = 1 } # Petsamo
province = { id = 136 points = 1 } # Kajaani
province = { id = 139 points = 1 } # Seinäjoki
province = { id = 140 points = 1 } # Pori
province = { id = 141 points = 2 } # Turku
province = { id = 142 points = 2 } # Helsinki
province = { id = 154 points = 2 } # Archangelsk
province = { id = 163 points = 1 } # Stalingrad
province = { id = 165 points = 1 } # Konosha
province = { id = 168 points = 1 } # Gorkij
province = { id = 171 points = 2 } # Volodga
province = { id = 175 points = 3 } # Moscow
province = { id = 187 points = 2 } # Leningrad
province = { id = 194 points = 2 } # Tallinn
province = { id = 197 points = 2 } # Riga
province = { id = 207 points = 2 } # Kaunas
province = { id = 208 points = 1 } # Wilno
province = { id = 210 points = 1 } # Baranowicze
province = { id = 212 points = 1 } # Minsk
province = { id = 220 points = 1 } # Mogilev
province = { id = 227 points = 1 } # Zhitomir
province = { id = 228 points = 2 } # Vinnitsa
province = { id = 229 points = 1 } # Stanislawow
province = { id = 230 points = 2 } # Beltsy
province = { id = 231 points = 2 } # Mogilev Podolski
province = { id = 232 points = 2 } # Balta
province = { id = 233 points = 1 } # Odessa
province = { id = 234 points = 1 } # Kherson
province = { id = 235 points = 2 } # Dnepropetrovsk
province = { id = 236 points = 1 } # Krivoy Rog
province = { id = 237 points = 2 } # Cherkassy
province = { id = 238 points = 2 } # Kiev
province = { id = 239 points = 2 } # Priluki
province = { id = 241 points = 1 } # Chernigov
province = { id = 243 points = 1 } # Kursk
province = { id = 244 points = 2 } # Sumy
province = { id = 245 points = 2 } # Poltava
province = { id = 246 points = 2 } # Zaporozhye
province = { id = 247 points = 1 } # Belgorod
province = { id = 248 points = 1 } # Kharkov
province = { id = 249 points = 1 } # Stalino
province = { id = 256 points = 1 } # Krasnodar
province = { id = 258 points = 1 } # Rostov
province = { id = 266 points = 2 } # Kashary
province = { id = 268 points = 2 } # Morozovsk
province = { id = 269 points = 2 } # Konstatinovsk
province = { id = 283 points = 1 } # Voronezh
province = { id = 292 points = 1 } # Aalborg
province = { id = 293 points = 1 } # Odense
province = { id = 294 points = 2 } # Copenhagen
province = { id = 296 points = 1 } # Rostock
province = { id = 298 points = 1 } # Magdeburg
province = { id = 300 points = 5 } # Berlin
province = { id = 302 points = 1 } # Stettin
province = { id = 303 points = 1 } # Danzig
province = { id = 305 points = 1 } # Torun
province = { id = 307 points = 1 } # Poznan
province = { id = 310 points = 1 } # Leipzig
province = { id = 311 points = 2 } # Dresden
province = { id = 312 points = 2 } # Nuremberg
province = { id = 313 points = 2 } # Frankfurt-am-Main
province = { id = 314 points = 2 } # Stuttgart
province = { id = 320 points = 2 } # Vichy
province = { id = 325 points = 2 } # Bordeaux
province = { id = 331 points = 2 } # Bilbao
province = { id = 333 points = 1 } # Burgos
province = { id = 334 points = 1 } # La Coruña
province = { id = 335 points = 1 } # Oporto
province = { id = 336 points = 2 } # Lissabon
province = { id = 339 points = 1 } # Valladolid
province = { id = 341 points = 2 } # Madrid
province = { id = 342 points = 1 } # Guadalajara
province = { id = 346 points = 1 } # Huelva
province = { id = 347 points = 2 } # Seville
province = { id = 348 points = 2 } # Gibraltar
province = { id = 349 points = 1 } # Málaga
province = { id = 350 points = 1 } # Almería
province = { id = 352 points = 1 } # Murcia
province = { id = 354 points = 2 } # València
province = { id = 356 points = 1 } # Tarragona
province = { id = 357 points = 2 } # Barcelona
province = { id = 359 points = 2 } # Toulouse
province = { id = 364 points = 2 } # Marseille
province = { id = 368 points = 1 } # Genoa
province = { id = 370 points = 2 } # Milan
province = { id = 376 points = 2 } # Munich
province = { id = 378 points = 2 } # Venice
province = { id = 380 points = 1 } # Ljubljana
province = { id = 381 points = 2 } # Rijeka
province = { id = 382 points = 2 } # Zagreb
province = { id = 383 points = 2 } # Banja Luka
province = { id = 384 points = 2 } # Split
province = { id = 385 points = 2 } # Zenica
province = { id = 386 points = 1 } # Sarajevo
province = { id = 390 points = 1 } # Tirana
province = { id = 395 points = 1 } # Corinthe
province = { id = 401 points = 2 } # Athens
province = { id = 403 points = 1 } # Larisa
province = { id = 407 points = 1 } # Ar-Ruwayshid
province = { id = 408 points = 1 } # Bursa
province = { id = 409 points = 3 } # Istanbul
province = { id = 411 points = 1 } # Salonika
province = { id = 412 points = 1 } # Edessa
province = { id = 415 points = 1 } # Pristina
province = { id = 417 points = 2 } # Sofia
province = { id = 420 points = 1 } # Pleven
province = { id = 421 points = 1 } # Plovdiv
province = { id = 422 points = 1 } # Varna
province = { id = 423 points = 1 } # Constanta
province = { id = 424 points = 3 } # Bucharest
province = { id = 428 points = 1 } # Cluj-Napoca
province = { id = 431 points = 1 } # Ploesti
province = { id = 433 points = 1 } # Iasi
province = { id = 434 points = 1 } # Chisinev
province = { id = 439 points = 1 } # Izmit
province = { id = 442 points = 1 } # Konya
province = { id = 445 points = 1 } # Gaziantep
province = { id = 446 points = 1 } # Kayseri
province = { id = 448 points = 2 } # Ankara
province = { id = 453 points = 2 } # Belgrade
province = { id = 457 points = 2 } # Budapest
province = { id = 460 points = 1 } # Graz
province = { id = 463 points = 2 } # Vienna
province = { id = 467 points = 1 } # Tábor
province = { id = 468 points = 1 } # Kutna Hora
province = { id = 469 points = 1 } # Prague
province = { id = 470 points = 1 } # Pilsen
province = { id = 471 points = 1 } # Ústí
province = { id = 475 points = 1 } # Brno
province = { id = 476 points = 1 } # Bratislava
province = { id = 479 points = 1 } # Cracow
province = { id = 481 points = 1 } # Czestochowa
province = { id = 482 points = 2 } # Oppeln
province = { id = 483 points = 2 } # Lodz
province = { id = 485 points = 2 } # Warsaw
province = { id = 490 points = 1 } # Kosice
province = { id = 497 points = 1 } # Debrecen
province = { id = 501 points = 1 } # Lvov
province = { id = 502 points = 1 } # Tarnopol
province = { id = 510 points = 1 } # Königsberg
province = { id = 512 points = 2 } # Bologna
province = { id = 513 points = 1 } # Florence
province = { id = 515 points = 3 } # Rome
province = { id = 517 points = 1 } # Pescara
province = { id = 518 points = 2 } # Cassino
province = { id = 521 points = 1 } # Naples
province = { id = 522 points = 2 } # Potenza
province = { id = 525 points = 1 } # Palermo
province = { id = 528 points = 2 } # Lyon
province = { id = 530 points = 1 } # Geneva
province = { id = 531 points = 2 } # Turin
province = { id = 532 points = 2 } # Bern
province = { id = 533 points = 1 } # Zürich
province = { id = 539 points = 2 } # Managua
province = { id = 540 points = 1 } # San José
province = { id = 583 points = 1 } # Portland
province = { id = 584 points = 1 } # Sherbrooke
province = { id = 586 points = 1 } # Québec City
province = { id = 588 points = 1 } # Ottawa
province = { id = 589 points = 1 } # Toronto
province = { id = 590 points = 1 } # Windsor
province = { id = 591 points = 1 } # Kingston
province = { id = 598 points = 1 } # Albany
province = { id = 599 points = 1 } # Worcester
province = { id = 600 points = 2 } # Boston
province = { id = 601 points = 1 } # Hartford
province = { id = 602 points = 2 } # New York
province = { id = 603 points = 2 } # Newark
province = { id = 604 points = 2 } # Atlantic City
province = { id = 606 points = 1 } # Washington D.C.
province = { id = 607 points = 1 } # Baltimore
province = { id = 608 points = 2 } # Philadelphia
province = { id = 609 points = 1 } # Harrisburg
province = { id = 612 points = 1 } # Syracuse
province = { id = 614 points = 1 } # Pittsburgh
province = { id = 615 points = 3 } # Cleveland
province = { id = 616 points = 2 } # Detroit
province = { id = 618 points = 1 } # Grand Rapids
province = { id = 619 points = 1 } # Indianapolis
province = { id = 620 points = 2 } # Chicago
province = { id = 621 points = 2 } # Milwaukee
province = { id = 625 points = 1 } # Peoria
province = { id = 628 points = 1 } # Columbus
province = { id = 629 points = 1 } # Charleston
province = { id = 635 points = 1 } # Fayetteville
province = { id = 636 points = 1 } # Raleigh
province = { id = 637 points = 1 } # Charlotte
province = { id = 640 points = 1 } # Louisville
province = { id = 642 points = 1 } # Nashville
province = { id = 644 points = 1 } # Charleston
province = { id = 645 points = 1 } # Columbia
province = { id = 654 points = 2 } # Havana
province = { id = 656 points = 2 } # Camagüey
province = { id = 662 points = 1 } # Midway Island
province = { id = 664 points = 1 } # Grand Bahama
province = { id = 665 points = 1 } # The Abacos
province = { id = 667 points = 3 } # Buenos Aires
province = { id = 669 points = 1 } # Augusta
province = { id = 670 points = 1 } # Atlanta
province = { id = 671 points = 1 } # Chattanooga
province = { id = 672 points = 1 } # Birmingham
province = { id = 673 points = 1 } # Memphis
province = { id = 675 points = 1 } # Jackson
province = { id = 676 points = 1 } # Mobile
province = { id = 678 points = 1 } # Biloxi
province = { id = 679 points = 1 } # Baton Rouge
province = { id = 680 points = 1 } # New Orleans
province = { id = 684 points = 1 } # Little Rock
province = { id = 686 points = 1 } # Fort Smith
province = { id = 689 points = 1 } # St. Louis
province = { id = 690 points = 1 } # Kansas City
province = { id = 692 points = 1 } # Des Moines
province = { id = 693 points = 2 } # Minneapolis
province = { id = 715 points = 1 } # Dallas
province = { id = 716 points = 1 } # Houston
province = { id = 752 points = 3 } # Mexico City
province = { id = 753 points = 1 } # Puebla
province = { id = 757 points = 2 } # Guatemala
province = { id = 759 points = 2 } # San Salvador
province = { id = 760 points = 2 } # Tegucigalpa
province = { id = 762 points = 1 } # Los Angeles
province = { id = 765 points = 1 } # San Francisco
province = { id = 780 points = 1 } # Seattle
province = { id = 783 points = 1 } # Portland
province = { id = 789 points = 1 } # Omaha
province = { id = 793 points = 1 } # Tulsa
province = { id = 803 points = 1 } # Barranquilla
province = { id = 811 points = 2 } # Caracas
province = { id = 813 points = 2 } # Bogotá
province = { id = 815 points = 2 } # Quito
province = { id = 816 points = 1 } # Trujillo
province = { id = 825 points = 1 } # Pôrto Velho
province = { id = 827 points = 1 } # Riberalta
province = { id = 828 points = 1 } # Cobija
province = { id = 830 points = 2 } # Lima
province = { id = 831 points = 1 } # Arequipa
province = { id = 832 points = 2 } # La Paz
province = { id = 833 points = 1 } # Perseverancia
province = { id = 834 points = 1 } # Cuiabá
province = { id = 835 points = 1 } # Mato Grosso
province = { id = 836 points = 1 } # Santa Cruz
province = { id = 837 points = 1 } # Asunción
province = { id = 839 points = 1 } # Antofagasta
province = { id = 840 points = 2 } # Santiago
province = { id = 843 points = 1 } # San Miguel de Tucumán
province = { id = 844 points = 2 } # Corrientes
province = { id = 845 points = 2 } # Córdoba
province = { id = 849 points = 2 } # Montevideo
province = { id = 852 points = 2 } # Mar del Plata
province = { id = 853 points = 1 } # Bahia Blanca
province = { id = 854 points = 1 } # Viedma
province = { id = 863 points = 1 } # Santa Cruz
province = { id = 864 points = 2 } # Punta Arenas
province = { id = 865 points = 1 } # Tierra del Fuego
province = { id = 866 points = 1 } # Falkland Islands
province = { id = 875 points = 2 } # Cayenne
province = { id = 879 points = 1 } # Belém
province = { id = 881 points = 2 } # Recife
province = { id = 882 points = 2 } # Salvador
province = { id = 883 points = 1 } # Goiás
province = { id = 884 points = 2 } # Vitória
province = { id = 885 points = 2 } # Rio de Janeiro
province = { id = 886 points = 2 } # São Paulo
province = { id = 888 points = 1 } # Panamá
province = { id = 892 points = 1 } # Port-au-Prince
province = { id = 894 points = 1 } # Santo Domingo
province = { id = 901 points = 1 } # Port Said
province = { id = 903 points = 2 } # Cairo
province = { id = 906 points = 2 } # Alexandria
province = { id = 924 points = 1 } # Bengazi
province = { id = 930 points = 1 } # Homs
province = { id = 932 points = 1 } # Tripoli
province = { id = 933 points = 1 } # Zuara
province = { id = 935 points = 1 } # Gabès
province = { id = 949 points = 2 } # Algiers
province = { id = 957 points = 0 } # Ceuta
province = { id = 958 points = 2 } # Casablanca
province = { id = 981 points = 1 } # Dakar
province = { id = 992 points = 1 } # Monrovia
province = { id = 997 points = 2 } # Ouagadougou
province = { id = 1042 points = 1 } # Gonder
province = { id = 1043 points = 1 } # Desê
province = { id = 1046 points = 2 } # Addis Ababa
province = { id = 1064 points = 2 } # Entebbe
province = { id = 1066 points = 2 } # Khartoum
province = { id = 1078 points = 2 } # Bangui
province = { id = 1089 points = 2 } # Douala
province = { id = 1090 points = 2 } # São Tomé
province = { id = 1095 points = 2 } # Banana
province = { id = 1096 points = 2 } # Loanda
province = { id = 1103 points = 2 } # Vila Pereira d'Eça
province = { id = 1105 points = 2 } # Maun
province = { id = 1112 points = 2 } # Gaberones
province = { id = 1116 points = 2 } # Cape Town
province = { id = 1117 points = 2 } # Port Elisabeth
province = { id = 1118 points = 2 } # East London
province = { id = 1119 points = 2 } # Durban
province = { id = 1120 points = 2 } # Johannesburg
province = { id = 1121 points = 3 } # Pretoria
province = { id = 1125 points = 2 } # Harare
province = { id = 1126 points = 2 } # Lusaka
province = { id = 1127 points = 2 } # Élisabethville
province = { id = 1129 points = 1 } # Ndola
province = { id = 1133 points = 1 } # Quelimane
province = { id = 1134 points = 2 } # Fianarantsoa
province = { id = 1135 points = 1 } # Reunion
province = { id = 1136 points = 1 } # Mauritius
province = { id = 1140 points = 2 } # Dar es Salaam
province = { id = 1145 points = 1 } # Kano
province = { id = 1146 points = 1 } # Cap Verde Islands
province = { id = 1149 points = 1 } # Vorkuta
province = { id = 1150 points = 1 } # Osa
province = { id = 1151 points = 1 } # Molotov
province = { id = 1152 points = 1 } # Storozhevsk
province = { id = 1154 points = 1 } # Salekhard
province = { id = 1155 points = 1 } # Tazov
province = { id = 1156 points = 2 } # Dudinka
province = { id = 1158 points = 1 } # Saskylakh
province = { id = 1172 points = 1 } # Petropavlovsk-Kamchatskij
province = { id = 1179 points = 1 } # Sapporo
province = { id = 1180 points = 1 } # Sendai
province = { id = 1181 points = 1 } # Akita
province = { id = 1182 points = 2 } # Fukushima
province = { id = 1183 points = 1 } # Niigata
province = { id = 1184 points = 3 } # Tokyo
province = { id = 1185 points = 2 } # Nagoya
province = { id = 1186 points = 1 } # Kanazawa
province = { id = 1187 points = 2 } # Osaka
province = { id = 1188 points = 1 } # Hiroshima
province = { id = 1189 points = 1 } # Shikoku
province = { id = 1190 points = 1 } # Fukuoka
province = { id = 1191 points = 1 } # Kagoshima
province = { id = 1195 points = 1 } # Gwangju
province = { id = 1196 points = 1 } # Busan
province = { id = 1197 points = 1 } # Daegu
province = { id = 1199 points = 1 } # Seoul
province = { id = 1200 points = 1 } # Wonsan
province = { id = 1201 points = 1 } # Pyongyang
province = { id = 1204 points = 1 } # Tianjin
province = { id = 1205 points = 1 } # Beiping
province = { id = 1207 points = 1 } # Jining
province = { id = 1210 points = 1 } # Baoding
province = { id = 1214 points = 1 } # Yantai
province = { id = 1216 points = 1 } # Jinan
province = { id = 1221 points = 1 } # Hefei
province = { id = 1225 points = 1 } # Taiyuan
province = { id = 1227 points = 1 } # Luoyang
province = { id = 1229 points = 1 } # Nanyang
province = { id = 1232 points = 1 } # Hankou
province = { id = 1234 points = 1 } # Wuhu
province = { id = 1235 points = 2 } # Nanjing
province = { id = 1237 points = 1 } # Shanghai
province = { id = 1238 points = 1 } # Hangzhou
province = { id = 1250 points = 1 } # Ganzhou
province = { id = 1253 points = 1 } # Wuchang
province = { id = 1257 points = 1 } # Hengyang
province = { id = 1258 points = 1 } # Guilin
province = { id = 1261 points = 1 } # Huaihua
province = { id = 1268 points = 1 } # Nancheng
province = { id = 1270 points = 1 } # Xianyang
province = { id = 1271 points = 1 } # Yan'an
province = { id = 1272 points = 1 } # Yuling
province = { id = 1277 points = 1 } # Tianshui
province = { id = 1280 points = 2 } # Chongqing
province = { id = 1281 points = 1 } # Ya'an
province = { id = 1282 points = 1 } # Kangding
province = { id = 1284 points = 1 } # Dimapur
province = { id = 1285 points = 1 } # Dhaka
province = { id = 1286 points = 1 } # Comilla
province = { id = 1288 points = 1 } # Chittagong
province = { id = 1290 points = 1 } # Kalewa
province = { id = 1293 points = 1 } # Xiaguan
province = { id = 1294 points = 1 } # Baoshan
province = { id = 1296 points = 2 } # Mandalay
province = { id = 1299 points = 2 } # Rangoon
province = { id = 1301 points = 2 } # Toungoo
province = { id = 1303 points = 2 } # Chiang Rai
province = { id = 1307 points = 2 } # Kunming
province = { id = 1309 points = 1 } # Bose
province = { id = 1310 points = 1 } # Liuzhou
province = { id = 1313 points = 2 } # Guangzhou
province = { id = 1316 points = 1 } # Macao
province = { id = 1321 points = 1 } # Hainan
province = { id = 1322 points = 1 } # Kaohsiung
province = { id = 1323 points = 1 } # Taipei
province = { id = 1328 points = 1 } # Hanoi
province = { id = 1329 points = 1 } # Vientiane
province = { id = 1330 points = 2 } # Phitsanulok
province = { id = 1331 points = 2 } # Khon Kaen
province = { id = 1333 points = 1 } # Da Nang
province = { id = 1336 points = 2 } # Pakse
province = { id = 1337 points = 1 } # Saigon
province = { id = 1340 points = 2 } # Phnom Penh
province = { id = 1341 points = 2 } # Ubon Ratchthani
province = { id = 1342 points = 1 } # Nakhon Ratchthani
province = { id = 1343 points = 3 } # Bangkok
province = { id = 1344 points = 2 } # Nakhon Sawan
province = { id = 1349 points = 1 } # Alor Star
province = { id = 1350 points = 1 } # Kota Bahru
province = { id = 1351 points = 1 } # Kuantan
province = { id = 1352 points = 1 } # Kuala Lumpur
province = { id = 1353 points = 2 } # Singapore
province = { id = 1355 points = 1 } # Medan
province = { id = 1358 points = 2 } # Palembang
province = { id = 1359 points = 2 } # Oosthaven
province = { id = 1360 points = 1 } # Chengdu
province = { id = 1363 points = 1 } # Anshun
province = { id = 1364 points = 1 } # Guiyang
province = { id = 1379 points = 2 } # Harbin
province = { id = 1389 points = 1 } # Mukden
province = { id = 1390 points = 2 } # Xinjing
province = { id = 1395 points = 1 } # Yingkou
province = { id = 1396 points = 1 } # Jinxi
province = { id = 1404 points = 1 } # Ulan Bator
province = { id = 1410 points = 1 } # Aldan
province = { id = 1420 points = 1 } # Khobdo
province = { id = 1422 points = 2 } # Alma-Ata
province = { id = 1424 points = 2 } # Zhambyl
province = { id = 1425 points = 1 } # Chimkent
province = { id = 1427 points = 2 } # Tashkent
province = { id = 1428 points = 2 } # Osh
province = { id = 1429 points = 2 } # Frunze
province = { id = 1433 points = 1 } # Urumqi
province = { id = 1442 points = 1 } # Golmud
province = { id = 1443 points = 1 } # Xining
province = { id = 1453 points = 2 } # Lhasa
province = { id = 1455 points = 2 } # Punakha
province = { id = 1457 points = 1 } # Calcutta
province = { id = 1458 points = 1 } # Cuttack
province = { id = 1459 points = 1 } # Ranchi
province = { id = 1460 points = 2 } # Jabalpur
province = { id = 1462 points = 2 } # Nagpur
province = { id = 1463 points = 2 } # Satpura Mountains
province = { id = 1466 points = 1 } # Ahmadabad
province = { id = 1467 points = 1 } # Indore
province = { id = 1468 points = 2 } # Jaipur
province = { id = 1469 points = 3 } # Delhi
province = { id = 1471 points = 2 } # Lucknow
province = { id = 1472 points = 1 } # Darbhanga
province = { id = 1473 points = 2 } # Kathmandu
province = { id = 1474 points = 1 } # Srinagar
province = { id = 1475 points = 2 } # Lahore
province = { id = 1476 points = 1 } # Ludhiana
province = { id = 1477 points = 1 } # Meerut
province = { id = 1479 points = 2 } # Jodhpur
province = { id = 1480 points = 1 } # Hyderabad
province = { id = 1481 points = 2 } # Sukkur
province = { id = 1482 points = 2 } # Multan
province = { id = 1485 points = 2 } # Stalinabad
province = { id = 1486 points = 2 } # Kabul
province = { id = 1487 points = 1 } # Samarkand
province = { id = 1489 points = 2 } # Bukhara
province = { id = 1490 points = 2 } # Ashgabat
province = { id = 1496 points = 1 } # Birjand
province = { id = 1500 points = 1 } # Mashhad
province = { id = 1501 points = 2 } # Dasht-i-Kavir
province = { id = 1502 points = 3 } # Teheran
province = { id = 1503 points = 2 } # Babol
province = { id = 1505 points = 1 } # Bombay
province = { id = 1507 points = 2 } # Hyderabad
province = { id = 1509 points = 1 } # Madras
province = { id = 1510 points = 2 } # Salem
province = { id = 1511 points = 2 } # Bangalore
province = { id = 1512 points = 1 } # Kolhapur
province = { id = 1514 points = 1 } # Cochin
province = { id = 1517 points = 2 } # Colombo
province = { id = 1531 points = 1 } # Norilsk
province = { id = 1532 points = 1 } # Tura
province = { id = 1533 points = 1 } # Igarka
province = { id = 1534 points = 1 } # Poloi
province = { id = 1535 points = 1 } # Angutikha
province = { id = 1536 points = 1 } # Turukhansk
province = { id = 1546 points = 1 } # Kemerovo
province = { id = 1547 points = 1 } # Barnaul
province = { id = 1548 points = 2 } # Novosibirsk
province = { id = 1554 points = 1 } # Karaganda
province = { id = 1566 points = 1 } # Berezniki
province = { id = 1567 points = 1 } # Ufa
province = { id = 1571 points = 1 } # Serov
province = { id = 1572 points = 2 } # Sverdlovsk
province = { id = 1574 points = 1 } # Chelyabinsk
province = { id = 1581 points = 2 } # Turgai
province = { id = 1582 points = 2 } # Aralsk
province = { id = 1585 points = 2 } # Nukus
province = { id = 1586 points = 2 } # Kazalinsk
province = { id = 1587 points = 2 } # Baikonur
province = { id = 1593 points = 2 } # Tyumen
province = { id = 1599 points = 1 } # Iwo Jima
province = { id = 1601 points = 1 } # Eniwetok
province = { id = 1605 points = 1 } # Majuro
province = { id = 1608 points = 1 } # Kwajalein
province = { id = 1610 points = 1 } # Ponape
province = { id = 1611 points = 1 } # Nauru
province = { id = 1613 points = 1 } # Truk
province = { id = 1614 points = 1 } # Vella Lavella
province = { id = 1615 points = 1 } # Ulul
province = { id = 1618 points = 1 } # Ulithi
province = { id = 1619 points = 1 } # Yap
province = { id = 1621 points = 1 } # Palau
province = { id = 1622 points = 1 } # Kolombangara
province = { id = 1624 points = 1 } # Guam
province = { id = 1626 points = 1 } # Tinian
province = { id = 1627 points = 1 } # Saipan
province = { id = 1628 points = 2 } # Batavia
province = { id = 1629 points = 1 } # Tjilatjap
province = { id = 1630 points = 1 } # Semarang
province = { id = 1632 points = 1 } # Soerabaja
province = { id = 1635 points = 2 } # Bali
province = { id = 1639 points = 1 } # Flores
province = { id = 1654 points = 1 } # Helmahera
province = { id = 1655 points = 1 } # Buru
province = { id = 1656 points = 1 } # Ceram
province = { id = 1657 points = 1 } # West Timor
province = { id = 1658 points = 1 } # East Timor
province = { id = 1659 points = 1 } # Sorong
province = { id = 1660 points = 1 } # Babo
province = { id = 1661 points = 1 } # Biak Island
province = { id = 1662 points = 1 } # Kokonau
province = { id = 1663 points = 1 } # Arare
province = { id = 1664 points = 1 } # Sarmi
province = { id = 1665 points = 2 } # Hollandia
province = { id = 1670 points = 1 } # Rabaul
province = { id = 1672 points = 1 } # Lae
province = { id = 1674 points = 1 } # Merauke
province = { id = 1675 points = 1 } # Kerema
province = { id = 1679 points = 2 } # Port Moresby
province = { id = 1682 points = 1 } # Bougainville
province = { id = 1685 points = 2 } # Guadalcanal
province = { id = 1689 points = 1 } # Espirtu Santo
province = { id = 1692 points = 1 } # Noumea
province = { id = 1696 points = 1 } # Townsville
province = { id = 1697 points = 1 } # Hughenden
province = { id = 1700 points = 1 } # Mount Isa
province = { id = 1703 points = 2 } # Darwin
province = { id = 1705 points = 1 } # Barrow Creek
province = { id = 1712 points = 1 } # Perth
province = { id = 1714 points = 1 } # Laverton
province = { id = 1722 points = 2 } # Brisbane
province = { id = 1724 points = 1 } # Newcastle
province = { id = 1727 points = 3 } # Sydney
province = { id = 1728 points = 2 } # Canberra
province = { id = 1730 points = 2 } # Melbourne
province = { id = 1733 points = 1 } # Adelaide
province = { id = 1737 points = 1 } # Manila
province = { id = 1752 points = 1 } # Fiji
province = { id = 1756 points = 1 } # Samoa
province = { id = 1769 points = 1 } # Tarawa
province = { id = 1771 points = 2 } # Mezen
province = { id = 1772 points = 1 } # Ukhta
province = { id = 1773 points = 2 } # Syktyvkar
province = { id = 1774 points = 1 } # Kotelnich
province = { id = 1780 points = 1 } # Kazan
province = { id = 1783 points = 2 } # Kirov
province = { id = 1786 points = 1 } # Wake Island
province = { id = 1787 points = 2 } # Rasht
province = { id = 1788 points = 2 } # Hamadan
province = { id = 1792 points = 1 } # Damascus
province = { id = 1796 points = 1 } # Amman
province = { id = 1797 points = 1 } # Jerusalem
province = { id = 1802 points = 1 } # Akaba
province = { id = 1803 points = 1 } # Bayir
province = { id = 1807 points = 2 } # Riyadh
province = { id = 1812 points = 2 } # Sanaa
province = { id = 1819 points = 1 } # Mascate
province = { id = 1826 points = 2 } # Esfahan
province = { id = 1828 points = 1 } # Kuybyshev
province = { id = 1832 points = 1 } # Saratov
province = { id = 1840 points = 1 } # Kotlas
province = { id = 1841 points = 1 } # Velikij Ustyug
province = { id = 1850 points = 1 } # Tblisi
province = { id = 1854 points = 1 } # Batman
province = { id = 1856 points = 1 } # Yerevan
province = { id = 1857 points = 1 } # Makhachkala
province = { id = 1858 points = 2 } # Kirovabad
province = { id = 1861 points = 1 } # Dair az Zawr
province = { id = 1863 points = 1 } # Hims
province = { id = 1866 points = 2 } # Baghdad
province = { id = 1907 points = 1 } # Baku
