
##############################
# Country definition for ENG #
##############################

province =
{ id            = 5
  anti_air      = 4
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 10 current_size = 10 }
  radar_station = { size = 2 current_size = 2 }
}                 # Scapa Flow
province =
{ id            = 6
  radar_station = { size = 1 current_size = 1 }
}                 # Inverness
province =
{ id            = 7
  radar_station = { size = 1 current_size = 1 }
}                 # Aberdeen
province =
{ id            = 8
  radar_station = { size = 1 current_size = 1 }
}                 # Dunfermline
province =
{ id            = 9
  ic            = 4
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
  radar_station = { size = 2 current_size = 2 }
}                 # Glasgow
province =
{ id            = 10
  ic            = 3
  radar_station = { size = 2 current_size = 2 }
}                 # Edinburgh
province =
{ id            = 11
  ic            = 5
  radar_station = { size = 2 current_size = 2 }
}                 # Sunderland
province =
{ id            = 12
  ic            = 2
  radar_station = { size = 1 current_size = 1 }
}                 # Blackpool
province =
{ id            = 13
  ic            = 6
  anti_air      = 2
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
  radar_station = { size = 4 current_size = 4 }
}                 # Sheffield
province =
{ id            = 14
  ic            = 7
  anti_air      = 4
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 10 current_size = 10 }
  radar_station = { size = 1 current_size = 1 }
}                 # Liverpool
province =
{ id            = 15
  radar_station = { size = 2 current_size = 2 }
}                 # Cardiff
province =
{ id            = 16
  ic            = 8
  anti_air      = 2
  radar_station = { size = 1 current_size = 1 }
}                 # Birmingham
province =
{ id            = 17
  anti_air      = 4
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 6 current_size = 6 }
  radar_station = { size = 5 current_size = 5 }
}                 # Norwich
province =
{ id            = 19
  ic            = 8
  anti_air      = 3
  radar_station = { size = 2 current_size = 2 }
}                 # London
province =
{ id            = 20
  anti_air      = 3
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
  coastalfort   = 4
  radar_station = { size = 6 current_size = 6 }
}                 # Dover
province =
{ id            = 21
  anti_air      = 6
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
  radar_station = { size = 6 current_size = 6 }
}                 # Portsmouth
province =
{ id            = 22
  radar_station = { size = 3 current_size = 3 }
}                 # Bristol
province =
{ id            = 23
  anti_air      = 4
  air_base      = { size = 10 current_size = 10 }
  naval_base    = { size = 10 current_size = 10 }
  radar_station = { size = 5 current_size = 5 }
}                 # Plymouth
province = { id = 28 oilpool = 500 supplypool = 1000 } # Belfast
province =
{ id          = 31
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 5 current_size = 5 }
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 1000
}               # Malta
province =
{ id          = 348
  anti_air    = 4
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 7
  oilpool     = 1000
  supplypool  = 1000
}               # Gibraltar
province =
{ id       = 444
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cyprus
province =
{ id         = 538
  anti_air   = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id         = 576
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Newfoundland
province =
{ id       = 652
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Andros
province =
{ id         = 866
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
  oilpool    = 100
  supplypool = 200
}              # Falkland Islands
province =
{ id       = 873
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Georgetown
province = { id = 900 anti_air = 2 } # Suez
province = { id = 901 anti_air = 2 oilpool = 1500 supplypool = 2500 } # Port Said
province = { id = 903 anti_air = 2 } # Cairo
province =
{ id         = 906
  anti_air   = 3
  air_base   = { size = 7 current_size = 7 }
  naval_base = { size = 10 current_size = 10 }
}              # Alexandria
province = { id = 919 landfort = 6 coastalfort = 5 oilpool = 50 supplypool = 200 } # Tobruk
province =
{ id         = 988
  anti_air   = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 500
  supplypool = 1000
}              # Freetown
province =
{ id       = 1002
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Accra
province =
{ id       = 1008
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Lagos
province =
{ id       = 1061
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mombasa
province =
{ id       = 1066
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Khartoum
province =
{ id       = 1296
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mandalay
province =
{ id         = 1299
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Rangoon
province =
{ id          = 1315
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 2
  oilpool     = 1000
  supplypool  = 1000
}               # Hong Kong
province =
{ id          = 1353
  anti_air    = 4
  air_base    = { size = 8 current_size = 8 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 5
  oilpool     = 1000
  supplypool  = 2000
}               # Singapore
province =
{ id       = 1457
  ic       = 3
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Calcutta
province = { id = 1464 ic = 1 } # Surat
province = { id = 1465 ic = 2 } # Rajkot
province =
{ id       = 1467
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Indore
province =
{ id       = 1469
  ic       = 10
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Delhi
province = { id = 1478 ic = 3 } # Bikaner
province = { id = 1479 ic = 3 } # Jodhpur
province =
{ id         = 1494
  ic         = 1
  anti_air   = 1
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 8 current_size = 8 }
}              # Karachi
province =
{ id         = 1505
  ic         = 2
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 1000
  supplypool = 2000
}              # Bombay
province = { id = 1513 ic = 2 } # Mangalore
province =
{ id       = 1514
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cochin
province =
{ id         = 1516
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # Trincomalee
province =
{ id          = 1517
  anti_air    = 2
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }

  coastalfort = 4
  oilpool     = 1000
  supplypool  = 2000
}               # Colombo
province =
{ id       = 1644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Kuching
province =
{ id       = 1797
  anti_air = 3
  air_base = { size = 3 current_size = 3 }
}            # Jerusalem
province =
{ id         = 1813
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
}              # Aden
province =
{ id         = 1817
  anti_air   = 4
  air_base   = { size = 4 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 100
  supplypool = 200
}              # Diego Garcia Island
province =
{ id         = 1823
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # Basrah
province =
{ id       = 1866
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Baghdad

#####################
# Country main data #
#####################

country =
{ tag                    = ENG
  belligerence           = 5
  capital                = 19
  manpower               = 485
  transports             = 1550
  escorts                = 60
  energy                 = 2000
  metal                  = 2000
  rare_materials         = 1000
  oil                    = 1500
  supplies               = 2500
  money                  = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 10
    free_market       = 8
    professional_army = 7
    defense_lobby     = 7
    interventionism   = 6
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 14 }
  #SpyInfo                = { country = "GER" NumberOfSpies = 4 }
  #SpyInfo                = { country = "FRA" NumberOfSpies = 2 }
  #SpyInfo                = { country = "SOV" NumberOfSpies = 8 }
  #SpyInfo                = { country = "SPA" NumberOfSpies = 5 }
  #SpyInfo                = { country = "POL" NumberOfSpies = 8 }
  #SpyInfo                = { country = "SWE" NumberOfSpies = 5 }
  #SpyInfo                = { country = "NOR" NumberOfSpies = 2 }
  #SpyInfo                = { country = "FIN" NumberOfSpies = 5 }
  #SpyInfo                = { country = "YUG" NumberOfSpies = 8 }
  #SpyInfo                = { country = "HUN" NumberOfSpies = 5 }
  #SpyInfo                = { country = "BUL" NumberOfSpies = 5 }
  #SpyInfo                = { country = "BEL" NumberOfSpies = 8 }
  #SpyInfo                = { country = "DEN" NumberOfSpies = 5 }
  #SpyInfo                = { country = "HOL" NumberOfSpies = 8 }
  #SpyInfo                = { country = "USA" NumberOfSpies = 1 }
  #SpyInfo                = { country = "ALB" NumberOfSpies = 5 }
  #SpyInfo                = { country = "GRE" NumberOfSpies = 5 }
  #SpyInfo                = { country = "ARG" NumberOfSpies = 5 }
  #SpyInfo                = { country = "BRA" NumberOfSpies = 5 }
  #SpyInfo                = { country = "JAP" NumberOfSpies = 5 }
  #SpyInfo                = { country = "ROM" NumberOfSpies = 5 }
  #SpyInfo                = { country = "LIT" NumberOfSpies = 5 }
  #SpyInfo                = { country = "LUX" NumberOfSpies = 5 }
  #SpyInfo                = { country = "POR" NumberOfSpies = 5 }
  #SpyInfo                = { country = "ITA" NumberOfSpies = 5 }
  #SpyInfo                = { country = "CHI" NumberOfSpies = 1 }
  #SpyInfo                = { country = "MEX" NumberOfSpies = 5 }
  #SpyInfo                = { country = "AST" NumberOfSpies = 5 }
  #SpyInfo                = { country = "NZL" NumberOfSpies = 5 }
  #SpyInfo                = { country = "CAN" NumberOfSpies = 5 }
  #SpyInfo                = { country = "IRE" NumberOfSpies = 1 }
  #SpyInfo                = { country = "IRQ" NumberOfSpies = 8 }
  #SpyInfo                = { country = "BHU" NumberOfSpies = 5 }
  #SpyInfo                = { country = "YEM" NumberOfSpies = 5 }
  #SpyInfo                = { country = "ETH" NumberOfSpies = 5 }
  # GREAT BRITAIN
  nationalprovinces      = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   1494
			     1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459 1457
			     1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288 1289
			     1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1297 1300 1292 575  576  444
			   }
  # GREAT BRITAIN
  ownedprovinces         = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444
			     1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
			     1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288
			     1289 1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1297 1300 1292 1454 1799 1797 1796 404  1802 1803 406  407
			     1813 1814 1504 1822 1798 1860 1864 1865 1866 1790 1824 1823 1806 1791 900  901  902  903  904  905  906  907  908  909
			     910  911  912  913  914  915  4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1800 1801 1065 1066 1069 1068 1067 1029
			     1028 1032 1031 1030 1040 1041 1349 1350 1351 1352 1353 1644 1646 1647 1315 758  891  871  873  806  807  808  809  897
			     538  652  653  664  665  666  668  805  896  866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061
			     1059 1035 1036 1112 1111 1105 1124 1125 1104 1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085
			     1012 988  982  1622 1683 1684 1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 1877 1878
			     1033 1039 1038 1034 1055 1056 1058 1044 1048 1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054 1614 1820 1611
			     575  576
			   }
  # GREAT BRITAIN
  controlledprovinces    = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444
			     1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
			     1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288
			     1289 1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1297 1300 1292 1454 1799 1797 1796 404  1802 1803 406  407
			     1813 1814 1504 1798 1822 1860 1864 1865 1866 1790 1824 1823 1806 1791 900  901  902  903  904  905  906  907  908  909
			     910  911  912  913  914  915  4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1800 1801 1065 1066 1069 1068 1067 1029
			     1028 1032 1031 1030 1040 1041 1349 1350 1351 1352 1353 1644 1646 1647 1315 758  891  871  873  806  807  808  809  897
			     538  652  653  664  665  666  668  805  896  866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061
			     1059 1035 1036 1112 1111 1105 1124 1125 1104 1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085
			     1012 988  982  1622 1683 1684 1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 1877 1878
			     1033 1039 1038 1034 1055 1056 1058 919  1044 1048 1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054 1614 1820 1611
			     575  576
			   }
  # UK 1941 techs
  # ######################
  techapps               = { 1040  1240  2220  2230  2100  2150  4010  4020  4030  4040  4070  4050  4120  4130  4140  4220  4230  4190  4250  2010  2020  2040
			     2050  2030  2070  2170  2180  2290  2300  2310  2320  2330  2340  2400  2410  2450  2460  2470  2510  2520  1010  1020
			     1030  1190  1200  1210  1220  1110  1120  1130  1070  1230  1150  1160  1310  1340  5010  5020  5030  5050  5060  5070
			     5080  5090  5100  5110  5120  5130  5140  5160  5180  5190  5200  5310  5320  5330  5350  5360  5370  5380  5410  5420
			     5430  5440  5470  5480  5490  5500  5550  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130
			     9140  9190  9210  9220  9230  9240  9250  9350  6010  6030  6110  6120  8010  8020  8030  8040  8050  8070  8100  8120
			     8130  8190  8200  8310  3010  3020  3030  3070  3080  3090  3100  3130  3140  3150  3190  3200  3210  3250  3260  3270
			     3280  3320  3330  3340  3350  3360  3400  3410  3420  14000 14010 14020 12100 12110
			   }
  diplomacy =
  { relation = { tag = AFG value = -75 }
    relation = { tag = ARG value = 75 }
    relation = { tag = AST value = 200 access = yes }
    relation = { tag = BEL value = 200 }
    relation = { tag = BHU value = 200 access = yes }
    relation = { tag = BUL value = -200 }
    relation = { tag = CAN value = 200 access = yes }
    relation = { tag = SLO value = -200 }
    relation = { tag = FIN value = 85 }
    relation = { tag = FRA value = 200 }
    relation = { tag = GER value = -200 }
    relation = { tag = GUA value = 50 }
    relation = { tag = HOL value = 200 }
    relation = { tag = HON value = 50 }
    relation = { tag = HUN value = -200 }
    relation = { tag = IRE value = 50 }
    relation = { tag = ITA value = -200 }
    relation = { tag = MEX value = 50 }
    relation = { tag = NEP value = 200 access = yes }
    relation = { tag = NZL value = 200 access = yes }
    relation = { tag = OMN value = 150 access = yes }
    relation = { tag = PER value = 25 }
    relation =
    { tag        = POR
      value      = 100
      guaranteed = { day = 22 month = may year = 1939 }
    }
    relation = { tag = ROM value = -200 }
    relation = { tag = SAF value = 200 access = yes }
    relation =
    { tag        = SAU
      value      = 100
      guaranteed = { day = 11 month = february year = 1940 }
    }
    relation =
    { tag        = SCH
      value      = 50
      guaranteed = { day = 19 month = april year = 1939 }
    }
    relation = { tag = SIA value = 70 }
    relation = { tag = SOV value = 150 }
    relation = { tag = SPA value = -65 }
    relation = { tag = SWE value = 80 }
    relation =
    { tag        = TUR
      value      = 75
      guaranteed = { day = 17 month = may year = 1938 }
    }
    relation = { tag = USA value = 150 }
    relation = { tag = VEN value = -10 }
    relation =
    { tag        = YEM
      value      = 150
      access     = yes
      guaranteed = { day = 11 month = february year = 1940 }
    }
    relation = { tag = NIC value = 200 }
  }
  headofstate            = { type = 9 id = 1033 }
  headofgovernment       = { type = 9 id = 1038 }
  foreignminister        = { type = 9 id = 1003 }
  armamentminister       = { type = 9 id = 1062 }
  ministerofsecurity     = { type = 9 id = 1088 }
  ministerofintelligence = { type = 9 id = 1103 }
  chiefofstaff           = { type = 9 id = 1120 }
  chiefofarmy            = { type = 9 id = 1130 }
  chiefofnavy            = { type = 9 id = 1140 }
  chiefofair             = { type = 9 id = 1147 }
  dormant_ministers      = { 1001 1031 1002 1004 1005 1081 1006 1007 1008 1127 1128 1009 1137 1010 1037 1045 1117 1129 1132 1149 1082 1163 1173 1174
			   }
  # UK OOB
  landunit =
  { location = 22
    id       = { type = 11000 id = 1 }
    name     = "Aldershot Command"
    division =
    { id            = { type = 11000 id = 1101 }
      name          = "Aldershot Command HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { id       = { type = 11000 id = 2 }
      name     = "1st Infantry Div."
      type     = motorized
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 11000 id = 3 }
      name     = "2nd Infantry Div."
      type     = infantry
      strength = 100
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 194 }
      name     = "6th Infantry Div."
      type     = infantry
      strength = 100
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 195 }
      name     = "76th Infantry Div."
      type     = infantry
      strength = 70
      model    = 2
    }
  }
  landunit =
  { location = 17
    id       = { type = 11000 id = 4 }
    name     = "Eastern Command"
    division =
    { id       = { type = 11000 id = 5 }
      name     = "4th Infantry Division"
      type     = motorized
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 11000 id = 6 }
      name     = "12th 'Eastern' Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 8 }
      name     = "44th 'Home Counties' Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 9 }
      name     = "54th 'East Anglia' Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 196 }
      name     = "77th Infantry Div."
      type     = infantry
      strength = 70
      model    = 0
    }
  }
  landunit =
  { location = 19
    id       = { type = 11000 id = 10 }
    name     = "London District"
    division =
    { id       = { type = 11000 id = 11 }
      name     = "47th 'London' Infantry Div."
      type     = motorized
      strength = 100
      model    = 0
      extra    = anti_tank
    }
    division =
    { id       = { type = 11000 id = 12 }
      name     = "56th 'London' Div."
      type     = motorized
      strength = 100
      model    = 0
      extra    = anti_air
    }
  }
  landunit =
  { location = 11
    id       = { type = 11000 id = 13 }
    name     = "Northern Command"
    division =
    { id            = { type = 11000 id = 1103 }
      name          = "Northern Command HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { id       = { type = 11000 id = 14 }
      name     = "5th Infantry Div."
      type     = motorized
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 15 }
      name     = "49th 'West Riding' Div."
      type     = infantry
      model    = 2
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 16 }
      name     = "46th 'North Midlands' Div."
      type     = infantry
      model    = 2
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 17 }
      name     = "23th 'Northumbrian' Div."
      type     = infantry
      model    = 2
      strength = 80
    }
    division =
    { id       = { type = 11000 id = 18 }
      name     = "50th 'Northumbrian' Div."
      type     = infantry
      model    = 2
      strength = 80
    }
  }
  landunit =
  { location = 8
    id       = { type = 11000 id = 19 }
    name     = "Scottish Command"
    division =
    { id            = { type = 11000 id = 1104 }
      name          = "Scottish Command HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { id       = { type = 11000 id = 20 }
      name     = "9th 'Scottish' Div."
      type     = motorized
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 11000 id = 21 }
      name     = "51st 'Highland' Div."
      type     = infantry
      model    = 2
      strength = 100
      extra    = SP_artillery
    }
    division =
    { id       = { type = 11000 id = 197 }
      name     = "15th 'Scottish' Div."
      type     = infantry
      model    = 2
      strength = 80
    }
    division =
    { id       = { type = 11000 id = 198 }
      name     = "52nd 'Lowlands' Div."
      type     = infantry
      model    = 2
      strength = 80
    }
  }
  landunit =
  { location = 20
    id       = { type = 11000 id = 22 }
    name     = "Southern Command"
    division =
    { id            = { type = 11000 id = 1100 }
      name          = "Southern Command HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { id       = { type = 11000 id = 23 }
      name     = "3rd Infantry Div."
      type     = motorized
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 24 }
      name     = "6th Armoured Division"
      type     = armor
      strength = 60
      model    = 2
      extra    = heavy_armor
    }
    division =
    { id       = { type = 11000 id = 25 }
      name     = "48th 'South Midlands' Div."
      type     = infantry
      model    = 2
      strength = 80
    }
    division =
    { id       = { type = 11000 id = 26 }
      name     = "61st Infantry Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 27 }
      name     = "43rd 'Wessex' Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 28 }
      name     = "45th Infantry Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 199 }
      name     = "7th Infantry Div."
      type     = infantry
      strength = 90
      model    = 2
    }
  }
  landunit =
  { location = 16
    id       = { type = 11000 id = 29 }
    name     = "Western Command"
    division =
    { id            = { type = 11000 id = 1102 }
      name          = "Western Command HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { id       = { type = 11000 id = 30 }
      name     = "55th 'West Lancashire' Div."
      type     = motorized
      strength = 80
      model    = 0
    }
    division =
    { id       = { type = 11000 id = 31 }
      name     = "42nd 'East Lancashire' Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 32 }
      name     = "66th Motorized Div."
      type     = infantry
      strength = 80
      model    = 0
    }
    division =
    { id       = { type = 11000 id = 33 }
      name     = "38th 'Welsh' Div."
      type     = infantry
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 34 }
      name     = "53rd 'Welsh' Motorized Div."
      type     = infantry
      strength = 80
      model    = 3
    }
  }
  landunit =
  { location = 21
    id       = { type = 11000 id = 201 }
    name     = "Mobile Defense Corps"
    division =
    { id       = { type = 11000 id = 202 }
      name     = "8th Armoured Division"
      type     = armor
      model    = 2
      strength = 90
    }
    division =
    { id       = { type = 11000 id = 203 }
      name     = "9th Armoured Division"
      type     = armor
      strength = 80
      model    = 2
    }
    division =
    { id       = { type = 11000 id = 204 }
      name     = "8th Infantry Div."
      type     = motorized
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 11000 id = 205 }
      name     = "10th Infantry Div."
      type     = motorized
      strength = 90
      model    = 0
      extra    = armored_car
    }
  }
  landunit =
  { location = 1056
    id       = { type = 11000 id = 211 }
    name     = "East African Command"
    division =
    { id       = { type = 11000 id = 212 }
      name     = "1st African Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 213 }
      name     = "2nd African Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 1315
    id       = { type = 11000 id = 35 }
    name     = "Hong Kong Command"
    division =
    { id       = { type = 11000 id = 36 }
      name     = "Hong Kong Defence Force"
      type     = garrison
      strength = 30
      model    = 1
      locked   = yes
    }
  }
  landunit =
  { location = 1353
    id       = { type = 11000 id = 37 }
    name     = "Far Eastern Command"
    division =
    { id       = { type = 11000 id = 38 }
      name     = "Singapore Defence Force"
      type     = garrison
      strength = 100
      model    = 1
      locked   = yes
    }
  }
  landunit =
  { location = 348
    id       = { type = 11000 id = 39 }
    name     = "Gibraltar Command"
    division =
    { id       = { type = 11000 id = 40 }
      name     = "Gibraltar Defence Force"
      type     = garrison
      strength = 100
      model    = 1
      locked   = yes
    }
  }
  landunit =
  { location = 31
    id       = { type = 11000 id = 41 }
    name     = "Malta Command"
    division =
    { id       = { type = 11000 id = 42 }
      name     = "Malta Defense Force"
      type     = garrison
      model    = 1
      strength = 100
      locked   = yes
    }
  }
  landunit =
  { location = 1517
    id       = { type = 11000 id = 43 }
    name     = "Ceylon Command"
    division =
    { id       = { type = 11000 id = 44 }
      name     = "Ceylon Defence Force"
      type     = garrison
      model    = 1
      strength = 100
      locked   = yes
    }
  }
  landunit =
  { location = 1457
    id       = { type = 11000 id = 300 }
    name     = "1st Indian Infantry"
    division =
    { id       = { type = 11000 id = 301 }
      name     = "1st Indian Infantry"
      type     = infantry
      strength = 60
      model    = 1
    }
  }
  landunit =
  { location = 1457
    id       = { type = 11000 id = 302 }
    name     = "2nd Indian Infantry"
    division =
    { id       = { type = 11000 id = 303 }
      name     = "2nd Indian Infantry"
      type     = infantry
      model    = 1
      strength = 40
    }
  }
  landunit =
  { location = 1505
    id       = { type = 11000 id = 304 }
    name     = "3rd Indian Infantry"
    division =
    { id       = { type = 11000 id = 305 }
      name     = "3rd Indian Infantry"
      type     = infantry
      model    = 1
      strength = 40
    }
  }
  landunit =
  { location = 1466
    id       = { type = 11000 id = 306 }
    name     = "4th Indian Infantry"
    division =
    { id       = { type = 11000 id = 307 }
      name     = "4th Indian Infantry"
      type     = infantry
      strength = 50
      model    = 1
    }
  }
  landunit =
  { location = 1469
    id       = { type = 11000 id = 310 }
    name     = "6th Indian Infantry"
    division =
    { id       = { type = 11000 id = 311 }
      name     = "6th Indian Infantry"
      type     = infantry
      strength = 60
      model    = 1
    }
  }
  landunit =
  { location = 1296
    id       = { type = 11000 id = 312 }
    name     = "7th Indian Infantry"
    division =
    { id       = { type = 11000 id = 313 }
      name     = "7th Indian Infantry"
      type     = infantry
      strength = 50
      model    = 1
    }
  }
  landunit =
  { location = 919
    id       = { type = 11000 id = 22312 }
    name     = "Tobruk Garrison"
    dig_in   = 10
    division =
    { id            = { type = 11000 id = 22313 }
      name          = "Tobruk Garrison"
      type          = garrison
      strength      = 100
      model         = 2
      extra         = artillery
      brigade_model = 4
    }
  }
  landunit =
  { name     = "1st Sudanese Colonials"
    location = 1030
    id       = { type = 11000 id = 224 }
    division =
    { id       = { type = 11000 id = 225 }
      name     = "1st Sudanese Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "2nd Sudanese Colonials"
    location = 1038
    id       = { type = 11000 id = 226 }
    division =
    { id       = { type = 11000 id = 227 }
      name     = "2nd Sudanese Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "3rd Sudanese Colonials"
    location = 1046
    id       = { type = 11000 id = 228 }
    division =
    { id       = { type = 11000 id = 229 }
      name     = "3rd Sudanese Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "1st Ugandan Colonials"
    location = 1064
    id       = { type = 11000 id = 230 }
    division =
    { id       = { type = 11000 id = 231 }
      name     = "1st Ugandan Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "1st Nigerian Colonials"
    location = 1008
    id       = { type = 11000 id = 232 }
    division =
    { id       = { type = 11000 id = 233 }
      name     = "1st Nigerian Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "1st Kenyan Colonials"
    location = 1141
    id       = { type = 11000 id = 234 }
    division =
    { id       = { type = 11000 id = 235 }
      name     = "1st Kenyan Colonialss"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "2nd Kenyan Colonials"
    location = 1141
    id       = { type = 11000 id = 236 }
    division =
    { id       = { type = 11000 id = 237 }
      name     = "2nd Kenyan Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "1st Tanganyikan Colonials"
    location = 1139
    id       = { type = 11000 id = 238 }
    division =
    { id       = { type = 11000 id = 239 }
      name     = "1st Tanganyikan Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "2nd Tanganyikan Colonials"
    location = 1139
    id       = { type = 11000 id = 240 }
    division =
    { id       = { type = 11000 id = 241 }
      name     = "2nd Tanganyikan Colonials"
      type     = militia
      strength = 80
      model    = 0
    }
  }
  landunit =
  { name     = "1st Burma Division"
    location = 1299
    id       = { type = 11000 id = 242 }
    division =
    { id       = { type = 11000 id = 243 }
      name     = "1st Burma Division"
      type     = infantry
      extra    = engineer # ##7th gurka regiment
      strength = 100
      model    = 2
    }
  }
  landunit =
  { location = 915
    id       = { type = 13016 id = 244 }
    name     = "Desert Rats"
    division =
    { id            = { type = 13016 id = 245 }
      name          = "6th Infantry Division"
      type          = motorized
      strength      = 70
      extra         = armored_car
      model         = 0
      brigade_model = 0
    }
    division =
    { id            = { type = 13016 id = 246 }
      name          = "50th Infantry Division"
      type          = motorized
      extra         = SP_artillery
      strength      = 55
      model         = 0
      brigade_model = 0
    }
    division =
    { id            = { type = 13016 id = 247 }
      name          = "7th Armoured Division"
      type          = armor
      strength      = 35
      extra         = tank_destroyer
      model         = 2
      brigade_model = 0
    }
    division =
    { id            = { type = 13016 id = 248 }
      name          = "2nd Armoured Division"
      type          = light_armor
      strength      = 40
      extra         = tank_destroyer
      model         = 1
      brigade_model = 0
    }
  }
  landunit =
  { location = 4
    id       = { type = 13016 id = 1249 }
    name     = "Suez Command"
    division =
    { id       = { type = 11000 id = 1253 }
      name     = "5th Indian Infantry"
      type     = infantry
      strength = 50
      model    = 1
    }
    division =
    { id       = { type = 11000 id = 1215 }
      name     = "12th African Division"
      type     = infantry
      strength = 100
      model    = 1
    }
  }
  landunit =
  { location = 906
    id       = { type = 11000 id = 1250 }
    name     = "8th Indian Infantry"
    division =
    { id       = { type = 11000 id = 1251 }
      name     = "8th Indian Infantry"
      type     = infantry
      strength = 50
      model    = 1
    }
  }
  landunit =
  { location = 1797
    id       = { type = 11000 id = 1277 }
    name     = "Mid East Command"
    division =
    { id            = { type = 11000 id = 1105 }
      name          = "Mid East Command HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
    division =
    { id       = { type = 11000 id = 1252 }
      name     = "4th Indian Infantry"
      type     = infantry
      strength = 50
      model    = 1
    }
    division =
    { id       = { type = 11000 id = 1214 }
      name     = "11th (East African) Division"
      type     = infantry
      strength = 100
      model    = 1
    }
  }
  landunit =
  { location = 901
    id       = { type = 11000 id = 1254 }
    name     = "1st Cavalry Division"
    division =
    { id       = { type = 11000 id = 1255 }
      name     = "1st Cavalry Division"
      type     = cavalry
      strength = 100
      model    = 3
    }
  }
  navalunit =
  { name     = "Home Fleet"
    id       = { type = 11000 id = 670 }
    location = 5
    base     = 5
    division =
    { id    = { type = 11000 id = 407 }
      name  = "HMS Resolution"
      type  = battleship
      model = 1 # Royal Sovereign class
    }
    division =
    { id    = { type = 11000 id = 412 }
      name  = "HMS Rodney"
      type  = battleship
      model = 2 # Nelson class
    }
    division =
    { id    = { type = 11000 id = 415 }
      name  = "HMS King George V"
      type  = battleship
      model = 3 # King George V class
    }
    division =
    { id    = { type = 11000 id = 418 }
      name  = "HMS Repulse" # sunk 411210
      type  = Battlecruiser
      model = 1 # Repulse class
    }
    division =
    { id            = { type = 11000 id = 434 }
      name          = "HMS Victorious"
      type          = Carrier
      model         = 3
      extra         = cag
      brigade_model = 4
    }
    division =
    { id    = { type = 11000 id = 441 }
      name  = "HMS Berwick"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 442 }
      name  = "HMS Cumberland"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 444 }
      name  = "HMS Kent"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 446 }
      name  = "HMS Norfolk"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 447 }
      name  = "HMS Suffolk"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 504 }
      name  = "HMS Charybdis"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 511 }
      name  = "HMS Kenya"
      type  = light_cruiser
      model = 3 # Fiji class
    }
    division =
    { id    = { type = 11000 id = 514 }
      name  = "HMS Nigeria"
      type  = light_cruiser
      model = 3 # Fiji class
    }
    division =
    { id    = { type = 11000 id = 472 }
      name  = "HMS Dunedin"
      type  = light_cruiser
      model = 0 # D class
    }
    division =
    { id    = { type = 11000 id = 561 }
      name  = "1st Destroyer Flotilla"
      type  = destroyer
      model = 2 # T class
    }
    division =
    { id    = { type = 11000 id = 562 }
      name  = "2nd Destroyer Flotilla"
      type  = destroyer
      model = 2 # T class
    }
    division =
    { id    = { type = 11000 id = 545 }
      name  = "3rd Destroyer Flotilla"
      type  = destroyer
      model = 1 # A/B Class
    }
    division =
    { id    = { type = 11000 id = 546 }
      name  = "4th Destroyer Flotilla"
      type  = destroyer
      model = 1 # A/B Class
    }
  }
  navalunit =
  { name     = "Reserve Fleet"
    id       = { type = 11000 id = 601 }
    location = 5
    base     = 5
    division =
    { id            = { type = 11000 id = 405 }
      name          = "HMS Formidable"
      type          = carrier
      model         = 3
      extra         = cag
      brigade_model = 4
    }
    division =
    { id            = { type = 11000 id = 409 }
      name          = "HMS Illustrious"
      type          = carrier
      model         = 3
      extra         = cag
      brigade_model = 4
    }
    division =
    { id            = { type = 11000 id = 400 }
      name          = "HMS Furious"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 4
    }
    division =
    { id    = { type = 11000 id = 416 }
      name  = "HMS Prince of Wales"
      type  = battleship
      model = 3 # King George V class
    }
    division =
    { id    = { type = 11000 id = 411 }
      name  = "HMS Warspite"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 11000 id = 413 }
      name  = "HMS Nelson"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 11000 id = 414 }
      name  = "HMS Effingham"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 11000 id = 421 }
      name  = "HMS Frobisher"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 11000 id = 478 }
      name  = "HMS Hawkins"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 11000 id = 517 }
      name  = "HMS London"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 420 }
      name  = "HMS Shropshire"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 425 }
      name  = "HMS Sussex"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 426 }
      name  = "HMS Capetown"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 11000 id = 427 }
      name  = "HMS Caredoc"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 11000 id = 429 }
      name  = "HMS Coventry"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 11000 id = 430 }
      name  = "HMS Delhi"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 11000 id = 431 }
      name  = "HMS Achillies"
      type  = light_cruiser
      model = 2 # Leander class
    }
    division =
    { id    = { type = 11000 id = 432 }
      name  = "HMS Arethusa"
      type  = light_cruiser
      model = 2 # Arethusa class
    }
    division =
    { id    = { type = 11000 id = 433 }
      name  = "HMS Leander"
      type  = light_cruiser
      model = 2 # Leander class
    }
    division =
    { id    = { type = 11000 id = 435 }
      name  = "HMS Orion"
      type  = light_cruiser
      model = 2 # Leander class
    }
    division =
    { id    = { type = 11000 id = 436 }
      name  = "HMS Phoebe"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 437 }
      name  = "HMS Scylla"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 438 }
      name  = "HMS Sirius"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 439 }
      name  = "HMS Belfast"
      type  = light_cruiser
      model = 3 # Edinburgh class
    }
    division =
    { id    = { type = 11000 id = 440 }
      name  = "HMS Liverpool"
      type  = light_cruiser
      model = 3 # Gloucester class
    }
    division =
    { id    = { type = 11000 id = 445 }
      name  = "HMS Manchester"
      type  = light_cruiser
      model = 3 # Gloucester class
    }
    division =
    { id    = { type = 11000 id = 448 }
      name  = "HMS Newcastle"
      type  = light_cruiser
      model = 3 # Southampton class
    }
    division =
    { id    = { type = 11000 id = 449 }
      name  = "5th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 453 }
      name  = "6th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 455 }
      name  = "7th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 456 }
      name  = "8th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 461 }
      name  = "9th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 462 }
      name  = "10th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 464 }
      name  = "11th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 466 }
      name  = "12th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 469 }
      name  = "13th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 475 }
      name  = "14th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 476 }
      name  = "15th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 477 }
      name  = "16th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 483 }
      name  = "17th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 11000 id = 489 }
      name  = "18th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "Western Approaches command"
    id       = { type = 11000 id = 671 }
    location = 23
    base     = 23
    division =
    { id    = { type = 11000 id = 452 }
      name  = "HMS Exeter"
      type  = heavy_cruiser
      model = 1 # York Class
    }
    division =
    { id    = { type = 11000 id = 457 }
      name  = "HMS Cardiff"
      type  = light_cruiser
      model = 0 # C class
    }
    division =
    { id    = { type = 11000 id = 460 }
      name  = "HMS Cairo (AA)"
      type  = light_cruiser
      model = 0 # C class
    }
    division =
    { id    = { type = 11000 id = 465 }
      name  = "HMS Curacoa (AA)"
      type  = light_cruiser
      model = 0 # C class
    }
    division =
    { id    = { type = 11000 id = 538 }
      name  = "19th Destroyer Flotilla"
      type  = destroyer
      model = 0 # V/W Class
    }
    division =
    { id    = { type = 11000 id = 499 }
      name  = "HMS Dido"
      type  = light_cruiser
      model = 2 # Dido class
    }
  }
  navalunit =
  { name     = "Murmansk Convoy Command"
    id       = { type = 11000 id = 672 }
    location = 5
    base     = 5
    division =
    { id    = { type = 11000 id = 496 }
      name  = "HMS Edinburgh"
      type  = light_cruiser
      model = 3 # Belfast class
    }
    division =
    { id    = { type = 11000 id = 491 }
      name  = "HMS Sheffield"
      type  = light_cruiser
      model = 3 # Southampton class
    }
    division =
    { id    = { type = 11000 id = 544 }
      name  = "20th Destroyer Flotilla"
      type  = destroyer
      model = 0 # Scott Class
    }
  }
  navalunit =
  { name     = "Mediterranean Fleet"
    id       = { type = 11000 id = 673 }
    location = 906
    base     = 906
    division =
    { id    = { type = 11000 id = 403 }
      name  = "HMS Queen Elisabeth"
      type  = battleship
      model = 1 # Queen Elisabeth Class
    }
    division =
    { id    = { type = 11000 id = 404 }
      name  = "HMS Valliant"
      type  = battleship
      model = 1 # Queen Elisabeth Class
    }
    division =
    { id    = { type = 11000 id = 401 }
      name  = "HMS Barham" # sunk 411125
      type  = battleship
      model = 1 # Queen Elisabeth Class
    }
    division =
    { id            = { type = 11000 id = 423 }
      name          = "HMS Eagle"
      type          = escort_carrier
      model         = 1
    }
    division =
    { id    = { type = 11000 id = 506 }
      name  = "HMS Naiad"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 500 }
      name  = "HMS Eurylus"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 498 }
      name  = "HMS Cleopatra"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 463 }
      name  = "HMS Carlisle (AA)"
      type  = light_cruiser
      model = 0 # C class
    }
    division =
    { id    = { type = 11000 id = 547 }
      name  = "21st Destroyer Flotilla"
      type  = destroyer
      model = 1 # A/B Class
    }
  }
  navalunit =
  { name     = "Force K"
    id       = { type = 11000 id = 674 }
    location = 13
    base     = 13
    division =
    { id    = { type = 11000 id = 485 }
      name  = "HMS Galatea"
      type  = light_cruiser
      model = 2 # Arethusa class
    }
    division =
    { id    = { type = 11000 id = 486 }
      name  = "HMS Penelope"
      type  = light_cruiser
      model = 2 # Arethusa class
    }
    division =
    { id    = { type = 11000 id = 481 }
      name  = "HMS Ajax"
      type  = light_cruiser
      model = 2 # Leander class
    }
    division =
    { id    = { type = 11000 id = 482 }
      name  = "HMS Neptune"
      type  = light_cruiser
      model = 2 # Leander class
    }
    division =
    { id    = { type = 11000 id = 484 }
      name  = "HMS Aurora"
      type  = light_cruiser
      model = 2 # Arethusa class
    }
    division =
    { id    = { type = 11000 id = 555 }
      name  = "28th Destroyer Flotilla"
      type  = destroyer
      model = 2 # G/H Class
    }
  }
  navalunit =
  { name     = "Force H"
    id       = { type = 11000 id = 675 }
    location = 348
    base     = 348
    division =
    { id    = { type = 11000 id = 402 }
      name  = "HMS Malaya"
      type  = battleship
      model = 1 # Queen Elisabeth Class
    }
    division =
    { id    = { type = 11000 id = 417 }
      name  = "HMS Renown"
      type  = Battlecruiser
      model = 1 # Repulse class
    }
    division =
    { id            = { type = 11000 id = 422 }
      name          = "HMS Argus"
      type          = escort_carrier
      model         = 0
    }
    division =
    { id            = { type = 11000 id = 428 }
      name          = "HMS Ark Royal"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 4
    }
    division =
    { id    = { type = 11000 id = 505 }
      name  = "HMS Hermione"
      type  = light_cruiser
      model = 2 # Dido class
    }
    division =
    { id    = { type = 11000 id = 468 }
      name  = "HMS Dauntless"
      type  = light_cruiser
      model = 0 # D class
    }
    division =
    { id    = { type = 11000 id = 536 }
      name  = "22nd Destroyer Flotilla"
      type  = destroyer
      model = 0 # V/W Class
    }
    division =
    { id    = { type = 11000 id = 563 }
      name  = "23rd Destroyer Flotilla"
      type  = destroyer
      model = 2 # T class
    }
  }
  navalunit =
  { name     = "South Atlantic squadron"
    id       = { type = 11000 id = 676 }
    location = 1116
    base     = 1116
    division =
    { id    = { type = 11000 id = 470 }
      name  = "HMS Despatch"
      type  = light_cruiser
      model = 0 # D class
    }
    division =
    { id    = { type = 11000 id = 471 }
      name  = "HMS Diomede"
      type  = light_cruiser
      model = 0 # D class
    }
    division =
    { id    = { type = 11000 id = 451 }
      name  = "HMS Dorsetshire"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 443 }
      name  = "HMS Devonshire"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 487 }
      name  = "HMS Birmingham"
      type  = light_cruiser
      model = 3 # Southampton class
    }
    division =
    { id    = { type = 11000 id = 532 }
      name  = "24th Destroyer Flotilla"
      type  = destroyer
      model = 0 # R/S Class
    }
  }
  navalunit =
  { name     = "Indian Ocean Squadron"
    id       = { type = 11000 id = 677 }
    location = 1817
    base     = 1817
    division =
    { id    = { type = 11000 id = 410 }
      name  = "HMS Royal Sovereign"
      type  = battleship
      model = 1 # Royal Sovereign class
    }
    division =
    { id    = { type = 11000 id = 408 }
      name  = "HMS Revenge"
      type  = battleship
      model = 1 # Royal Sovereign class
    }
    division =
    { id            = { type = 11000 id = 424 }
      name          = "HMS Hermes"
      type          = escort_carrier
      model         = 0
    }
    division =
    { id    = { type = 11000 id = 480 }
      name  = "HMS Enterprise"
      type  = light_cruiser
      model = 1 # E class
    }
    division =
    { id    = { type = 11000 id = 459 }
      name  = "HMS Colombo (AA)"
      type  = light_cruiser
      model = 0 # C class
    }
    division =
    { id    = { type = 11000 id = 450 }
      name  = "HMS Cornwall"
      type  = heavy_cruiser
      model = 1 # County class
    }
    division =
    { id    = { type = 11000 id = 541 }
      name  = "25th Destroyer Flotilla"
      type  = destroyer
      model = 0 # V/W Class
    }
  }
  navalunit =
  { name     = "India Station"
    id       = { type = 11000 id = 678 }
    location = 1517
    base     = 1517
    division =
    { id    = { type = 11000 id = 406 }
      name  = "HMS Ramilles"
      type  = battleship
      model = 1 # Royal Sovereign class
    }
    division =
    { id    = { type = 11000 id = 479 }
      name  = "HMS Emerald"
      type  = light_cruiser
      model = 1 # E Class
    }
    division =
    { id    = { type = 11000 id = 458 }
      name  = "HMS Ceres"
      type  = light_cruiser
      model = 0 # C class
    }
    division =
    { id    = { type = 11000 id = 454 }
      name  = "HMS Caledon (AA)"
      type  = light_cruiser
      model = 0 # C class
    }
    division =
    { id    = { type = 11000 id = 488 }
      name  = "HMS Glasgow"
      type  = light_cruiser
      model = 3 # Southampton class
    }
    division =
    { id    = { type = 11000 id = 512 }
      name  = "HMS Mauritius"
      type  = light_cruiser
      model = 3 # Fiji class
    }
    division =
    { id    = { type = 11000 id = 537 }
      name  = "26th Destroyer Flotilla"
      type  = destroyer
      model = 0 # V/W Class
    }
  }
  navalunit =
  { name     = "China Station"
    id       = { type = 11000 id = 679 }
    location = 1353
    base     = 1353
    division =
    { id    = { type = 11000 id = 473 }
      name  = "HMS Durban"
      type  = light_cruiser
      model = 0 # D class
    }
    division =
    { id    = { type = 11000 id = 467 }
      name  = "HMS Danae"
      type  = light_cruiser
      model = 0 # D class
    }
    division =
    { id    = { type = 11000 id = 474 }
      name  = "HMS Dragon"
      type  = light_cruiser
      model = 0 # D class
    }
    division =
    { id    = { type = 11000 id = 553 }
      name  = "27th Destroyer Flotilla"
      type  = destroyer
      model = 2 # E/F Class
    }
  }
  navalunit =
  { name     = "2nd Submarine Squadron"
    id       = { type = 11000 id = 731 }
    location = 5
    base     = 5
    division =
    { id    = { type = 11000 id = 732 }
      name  = "3rd Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 11000 id = 733 }
      name  = "4th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 11000 id = 734 }
      name  = "5th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 11000 id = 735 }
      name  = "6th Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 11000 id = 736 }
      name  = "7th Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 11000 id = 737 }
      name  = "8th Submarine Flotilla"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { name     = "1st Submarine Squadron"
    id       = { type = 11000 id = 738 }
    location = 906
    base     = 906
    division =
    { id    = { type = 11000 id = 739 }
      name  = "1st Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 11000 id = 740 }
      name  = "2nd Submarine Flotilla"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "3rd Submarine Squadron"
    id       = { type = 11000 id = 741 }
    location = 13
    base     = 13
    division =
    { id    = { type = 11000 id = 742 }
      name  = "9th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 11000 id = 743 }
      name  = "10th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 11000 id = 744 }
      name  = "11th Submarine Flotilla"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "4th Submarine Squadron"
    id       = { type = 11000 id = 745 }
    location = 348
    base     = 348
    division =
    { id    = { type = 11000 id = 746 }
      name  = "12th Submarine Flotilla"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "1st Transport Squadron"
    id       = { type = 11000 id = 680 }
    location = 14 # Liverpool
    base     = 14
    division =
    { id    = { type = 11000 id = 710 }
      name  = "1st Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 711 }
      name  = "2nd Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 712 }
      name  = "3rd Transport Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { name     = "2nd Transport Squadron"
    id       = { type = 11000 id = 681 }
    location = 21 # Portmouth
    base     = 21
    division =
    { id    = { type = 11000 id = 713 }
      name  = "4th Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 714 }
      name  = "5th Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 715 }
      name  = "6th Transport Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { name     = "3rd Transport Squadron"
    id       = { type = 11000 id = 684 }
    location = 906 # Alexandria
    base     = 906
    division =
    { id    = { type = 11000 id = 722 }
      name  = "7th Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 723 }
      name  = "8th Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 724 }
      name  = "9th Transport Flotilla"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { name     = "4th Transport Squadron"
    id       = { type = 11000 id = 686 }
    location = 1517 # Colombo
    base     = 1517
    division =
    { id    = { type = 11000 id = 728 }
      name  = "10th Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 729 }
      name  = "11th Transport Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 11000 id = 730 }
      name  = "12th Transport Flotilla"
      type  = transport
      model = 0
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 11000 id = 900 }
    name     = "RAF Bomber Command"
    division =
    { id       = { type = 11000 id = 901 }
      name     = "No.2 Strategic Group"
      type     = strategic_bomber
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 902 }
      name     = "No.3 Strategic Group"
      type     = strategic_bomber
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 903 }
      name     = "No.4 Strategic Group"
      type     = strategic_bomber
      model    = 1
      strength = 100
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 11000 id = 904 }
    name     = "No.5 RAF Tactical Group"
    division =
    { id       = { type = 11000 id = 905 }
      name     = "No.5 RAF Tactical Group"
      type     = tactical_bomber
      model    = 2
      strength = 100
    }
  }
  airunit =
  { location = 20
    base     = 20
    id       = { type = 11000 id = 906 }
    name     = "RAF Fighter Command"
    division =
    { id       = { type = 11000 id = 907 }
      name     = "1/No.11 RAF interceptor Group"
      type     = interceptor
      model    = 2
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 908 }
      name     = "2/No.11 RAF interceptor Group"
      type     = interceptor
      model    = 2
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 909 }
      name     = "1/No.12 RAF interceptor Group"
      type     = interceptor
      model    = 2
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 910 }
      name     = "2/No.12 RAF interceptor Group"
      type     = interceptor
      model    = 2
      strength = 100
    }
  }
  airunit =
  { location = 13
    base     = 13
    id       = { type = 11000 id = 911 }
    name     = "No.13 RAF interceptor Group"
    division =
    { id       = { type = 11000 id = 912 }
      name     = "1/No.13 RAF interceptor Group"
      type     = multi_role
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 913 }
      name     = "2/No.13 RAF interceptor Group"
      type     = multi_role
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 914 }
      name     = "1/No.14 RAF interceptor Group"
      type     = multi_role
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 915 }
      name     = "2/No.14 RAF interceptor Group"
      type     = multi_role
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 906
    base     = 906
    id       = { type = 11000 id = 916 }
    name     = "Middle East Air Command"
    division =
    { id       = { type = 11000 id = 917 }
      name     = "1/No.15 RAF interceptor Group"
      type     = interceptor
      model    = 3
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 918 }
      name     = "2/No.15 RAF interceptor Group"
      type     = interceptor
      model    = 3
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 919 }
      name     = "5/No.15 RAF interceptor Group"
      type     = interceptor
      model    = 3
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 920 }
      name     = "1/Middle East Group"
      type     = tactical_bomber
      model    = 2
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 921 }
      name     = "2/Middle East Group"
      type     = tactical_bomber
      model    = 2
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 922 }
      name     = "4/Middle East Group"
      type     = naval_bomber
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 348
    base     = 348
    id       = { type = 11000 id = 923 }
    name     = "Gibraltar Air Command"
    division =
    { id       = { type = 11000 id = 924 }
      name     = "Gibraltar Group"
      type     = interceptor
      model    = 3
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 925 }
      name     = "Gibraltar Group"
      type     = naval_bomber
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 1505
    base     = 1505
    id       = { type = 11000 id = 926 }
    name     = "India Air Command"
    division =
    { id       = { type = 11000 id = 927 }
      name     = "Indian Group"
      type     = tactical_bomber
      model    = 3
      strength = 100
    }
  }
  airunit =
  { location = 1353
    base     = 1353
    id       = { type = 11000 id = 928 }
    name     = "Far East Air Command"
    division =
    { id       = { type = 11000 id = 929 }
      name     = "1/Far East Group"
      type     = tactical_bomber
      model    = 3
      strength = 100
    }
    division =
    { id       = { type = 11000 id = 930 }
      name     = "2/Far East Group"
      type     = interceptor
      model    = 4
      strength = 100
    }
  }
  # Under Construction#
  division_development =
  { name  = "HMS Duke of York"
    type  = battleship
    model = 3
    cost  = 8.5
    id    = { type = 11000 id = 800 }
    date  = { year = 1941 month = november day = 4 }
  }
  division_development =
  { name  = "HMS Anson"
    type  = battleship
    model = 3
    cost  = 8.5
    id    = { type = 11000 id = 801 }
    date  = { year = 1942 month = june day = 22 }
  }
  division_development =
  { name  = "HMS Howe"
    type  = battleship
    model = 3
    cost  = 8.5
    id    = { type = 11000 id = 802 }
    date  = { year = 1942 month = august day = 29 }
  }
  division_development =
  { name  = "HMS Indomitable"
    type  = carrier
    model = 3
    cost  = 5.9
    id    = { type = 11000 id = 803 }
    date  = { year = 1941 month = november day = 10 }
    extra = cag
    brigade_model = 4
  }
  division_development =
  { name  = "HMS Charybdis"
    type  = light_cruiser
    model = 2
    cost  = 4.3
    id    = { type = 11000 id = 804 }
    date  = { year = 1941 month = december day = 3 }
  }
  division_development =
  { name  = "HMS Cleopatra"
    type  = light_cruiser
    model = 2
    cost  = 4.3
    id    = { type = 11000 id = 805 }
    date  = { year = 1941 month = december day = 5 }
  }
  division_development =
  { name  = "HMS Euryalus"
    type  = light_cruiser
    model = 2
    cost  = 4.3
    id    = { type = 11000 id = 806 }
    date  = { year = 1941 month = june day = 30 }
  }
  division_development =
  { name  = "HMS Trinidad"
    type  = light_cruiser
    model = 3
    cost  = 5.1
    id    = { type = 11000 id = 807 }
    date  = { year = 1941 month = november day = 14 }
  }
  division_development =
  { name  = "29th Destroyer Flotilla"
    type  = destroyer
    model = 1
    cost  = 1.7
    id    = { type = 11000 id = 808 }
    date  = { year = 1941 month = august day = 1 }
  }
  division_development =
  { name  = "30th Destroyer Flotilla"
    type  = destroyer
    model = 1
    cost  = 1.7
    id    = { type = 11000 id = 809 }
    date  = { year = 1941 month = september day = 1 }
  }
  division_development =
  { name  = "13th Submarine Flotilla"
    type  = submarine
    model = 2
    cost  = 1.7
    id    = { type = 11000 id = 811 }
    date  = { year = 1941 month = august day = 1 }
  }
  division_development =
  { name  = "14th Submarine Flotilla"
    type  = submarine
    model = 2
    cost  = 1.7
    id    = { type = 11000 id = 812 }
    date  = { year = 1941 month = october day = 1 }
  }
  division_development =
  { name  = "15th Submarine Flotilla"
    type  = submarine
    model = 2
    cost  = 1.7
    id    = { type = 11000 id = 813 }
    date  = { year = 1941 month = november day = 1 }
  }
}
