
##############################
# Country definition for GER #
##############################

province =
{ id            = 18
  radar_station = { size = 1 current_size = 1 }
}                 # Calais
province =
{ id         = 32
  ic         = 3
  anti_air   = 8
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Brest
province =
{ id         = 34
  ic         = 2
  anti_air   = 4
  naval_base = { size = 6 current_size = 6 }
}              # Lorient
province =
{ id         = 35
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
}              # Nantes
province =
{ id       = 42
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
}            # Dieppe
province =
{ id            = 43
  radar_station = { size = 1 current_size = 1 }
  naval_base    = { size = 3 current_size = 3 }
}                 # Dunkerque
province =
{ id            = 45
  radar_station = { size = 2 current_size = 1 }
}                 # Ghent
province =
{ id         = 46
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
}              # Rotterdam
province =
{ id            = 47
  radar_station = { size = 1 current_size = 1 }
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
}                 # Amsterdam
province = { id = 49 anti_air = 2 } # Eindhoven
province =
{ id            = 50
  anti_air      = 2
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 6 current_size = 3 }
}                 # Antwerp
province =
{ id            = 51
  anti_air      = 1
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 10 current_size = 6 }
}                 # Brussels
province =
{ id       = 56
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Paris
province = { id = 58 ic = 1 } # Le Mans
province =
{ id         = 59
  ic         = 1
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
}              # Cholet
province = { id = 62 ic = 2 } # Auxerre
province = { id = 66 landfort = 3 } # Aachen
province =
{ id            = 67
  anti_air      = 4
  radar_station = { size = 1 current_size = 1 }
}                 # Essen
province = { id = 70 anti_air = 2 } # Arlon
province =
{ id       = 73
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Strasbourg
province = { id = 74 landfort = 3 anti_air = 4 } # Saarbrücken
province =
{ id            = 75
  landfort      = 3
  radar_station = { size = 1 current_size = 1 }
  anti_air      = 2
  air_base      = { size = 10 current_size = 10 }
}                 # Cologne
province =
{ id            = 76
  anti_air      = 3
  radar_station = { size = 1 current_size = 1 }
}                 # Dortmund
province =
{ id       = 78
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
}            # Leeuwarden
province =
{ id            = 80
  anti_air      = 9
  radar_station = { size = 1 current_size = 1 }
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 10 current_size = 10 }
}                 # Wilhelmshafen
province =
{ id       = 82
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
}            # Kassel
province = { id = 88 anti_air = 3 } # Hamburg
province = { id = 89 anti_air = 3 } # Lübeck
province =
{ id         = 90
  anti_air   = 8
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Kiel
province =
{ id         = 107
  supplypool = 200
  oilpool    = 200
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
}              # Oslo
province =
{ id            = 110
  radar_station = { size = 1 current_size = 1 }
  anti_air      = 4
  air_base      = { size = 6 current_size = 6 }
  naval_base    = { size = 5 current_size = 5 }
}                 # Bergen
province = { id = 118 anti_air = 1 } # Trondheim
province =
{ id         = 125
  anti_air   = 6
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Narvik
province =
{ id         = 292
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 4 current_size = 4 }
}              # Aalborg
province =
{ id       = 294
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}            # Copenhagen
province =
{ id          = 296
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  rocket_test = { size = 4 current_size = 4 }
}               # Rostock
province = { id = 298 anti_air = 3 } # Magdeburg
province = { id = 299 ic = 1 } # Potsdam
province =
{ id       = 300
  ic       = 1
  anti_air = 7
  air_base = { size = 10 current_size = 10 }
}            # Berlin
province =
{ id         = 302
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
}              # Stettin
province = { id = 303 ic = 2 anti_air = 3 } # Danzig
province = { id = 307 anti_air = 2 } # Poznan
province =
{ id       = 308
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Küstrin
province =
{ id       = 309
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Cottbus
province = { id = 310 ic = 5 anti_air = 3 } # Leipzig
province =
{ id       = 311
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
}            # Dresden
province = { id = 312 anti_air = 3 } # Nuremberg
province = { id = 313 anti_air = 4 } # Frankfurt-am-Main
province = { id = 314 landfort = 3 anti_air = 3 } # Stuttgart
province = { id = 315 landfort = 3 } # Freiburg
province = { id = 316 ic = 1 } # Mulhouse
province =
{ id       = 325
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Bordeaux
province =
{ id       = 376
  ic       = 3
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # Munich
province =
{ id       = 377
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Innsbruck
province =
{ id       = 382
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}            # Zagreb
province =
{ id       = 386
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Sarajevo
province =
{ id         = 396
  supplypool = 200
  oilpool    = 200
  anti_air   = 2
  air_base   = { size = 3 current_size = 3 }
  naval_base = { size = 1 current_size = 1 }
}              # Crete
province =
{ id         = 401
  supplypool = 200
  oilpool    = 200
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
}              # Athens
province =
{ id       = 412
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Edessa
province =
{ id       = 453
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Belgrade
province = { id = 454 anti_air = 2 } # Osijek
province = { id = 460 anti_air = 1 } # Graz
province = { id = 462 anti_air = 1 } # Salzburg
province =
{ id       = 463
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # Vienna
province = { id = 466 landfort = 3 } # Strakonice
province = { id = 467 landfort = 3 } # Tábor
province =
{ id       = 469
  anti_air = 5
  air_base = { size = 5 current_size = 5 }
}            # Prague
province = { id = 470 anti_air = 2 } # Pilsen
province = { id = 471 landfort = 3 } # Ústí
province = { id = 472 landfort = 3 } # Liberec
province =
{ id       = 473
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Breslau
province = { id = 475 anti_air = 4 } # Brno
province =
{ id         = 479
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
}              # Cracow
province =
{ id       = 483
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}            # Lodz
province =
{ id       = 485
  ic       = 2
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
}            # Warsaw
province =
{ id       = 487
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Lublin
province = { id = 494 anti_air = 1 } # Zrenjanin
province =
{ id         = 510
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Königsberg

#####################
# Country main data #
#####################

country =
{ tag                    = GER
  # relation = { tag = YUG value = 50 }
  belligerence           = 40
  capital                = 300
  manpower               = 600
  transports             = 100
  escorts                = 25
  # Resource Reserves
  energy                 = 10000
  metal                  = 5000
  rare_materials         = 15000
  oil                    = 20000
  supplies               = 10000
  money                  = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 1
    free_market       = 5
    freedom           = 2
    professional_army = 7
    defense_lobby     = 10
    interventionism   = 10
  }
  SpyInfo                = { country = "GER" NumberOfSpies = 13 }
  #SpyInfo                = { country = "ENG" NumberOfSpies = 10 }
  #SpyInfo                = { country = "FRA" NumberOfSpies = 6 }
  #SpyInfo                = { country = "SOV" NumberOfSpies = 5 }
  #SpyInfo                = { country = "SPR" NumberOfSpies = 5 }
  #SpyInfo                = { country = "POL" NumberOfSpies = 10 }
  #SpyInfo                = { country = "SWE" NumberOfSpies = 8 }
  #SpyInfo                = { country = "NOR" NumberOfSpies = 10 }
  #SpyInfo                = { country = "FIN" NumberOfSpies = 5 }
  #SpyInfo                = { country = "YUG" NumberOfSpies = 5 }
  #SpyInfo                = { country = "HUN" NumberOfSpies = 8 }
  #SpyInfo                = { country = "BUL" NumberOfSpies = 5 }
  #SpyInfo                = { country = "BEL" NumberOfSpies = 8 }
  #SpyInfo                = { country = "DEN" NumberOfSpies = 7 }
  #SpyInfo                = { country = "HOL" NumberOfSpies = 8 }
  #SpyInfo                = { country = "ARG" NumberOfSpies = 8 }
  #SpyInfo                = { country = "USA" NumberOfSpies = 10 }
  #SpyInfo                = { country = "ALB" NumberOfSpies = 5 }
  #SpyInfo                = { country = "GRE" NumberOfSpies = 5 }
  #SpyInfo                = { country = "BRA" NumberOfSpies = 5 }
  #SpyInfo                = { country = "JAP" NumberOfSpies = 8 }
  #SpyInfo                = { country = "ROM" NumberOfSpies = 5 }
  #SpyInfo                = { country = "LIT" NumberOfSpies = 5 }
  #SpyInfo                = { country = "LUX" NumberOfSpies = 5 }
  #SpyInfo                = { country = "POR" NumberOfSpies = 5 }
  #SpyInfo                = { country = "ITA" NumberOfSpies = 10 }
  #SpyInfo                = { country = "CHI" NumberOfSpies = 10 }
  nationalprovinces      = { 67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  206 296 297 298 299 300 301 302 304 308 309 310 311 312 313
			     314 315 374 375 376 473 510 66  72  73  316 71  303 466 467 471 472 373 377 460 461 462 463 464 465 482 474 305 306 307
			     468 469 470 475
			   }
  # Germany
  ownedprovinces         = { 67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313 314
			     315 374 375 376 473 510 71  303 305 306 307 479 480 481 482 483 484 485 486 487 488 489 206 91  92  292 293 294 295 107
			     108 109 110 111 116 117 118 124 125 128 129 466 467 468 469 470 471 472 474 475 373 377 460 461 462 463 464 465 45  46
			     47  48  49  50  51  52  65  66  68  69  70  77  78  79  18  32  33  34  35  36  37  38  39  40  41  42  43  44  53  54
			     55  56  57  58  59  60  61  62  63  64  72  73  316 317 318 323 325 326 396 401 405 410 412 403 459 455 454 453 382 383
			     385 386 451 452 418 494
			   }
  # Germany
  controlledprovinces    = { 67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313 314
			     315 374 375 376 473 510 71  303 305 306 307 479 480 481 482 483 484 485 486 487 488 489 206 91  92  292 293 294 295 107
			     108 109 110 111 116 117 118 124 125 128 129 466 467 468 469 470 471 472 474 475 373 377 460 461 462 463 464 465 45  46
			     47  48  49  50  51  52  65  66  68  69  70  77  78  79  18  32  33  34  35  36  37  38  39  40  41  42  43  44  53  54
			     55  56  57  58  59  60  61  62  63  64  72  73  316 317 318 323 325 326 396 401 405 410 412 403 459 455 454 453 382 383
			     385 386 451 452 418 494
			   }
  # Germany 1941 techs
  # ######################
  techapps               = { 1010  1020  1030  1040  1070  1080  1090  1110  1120  1130  1190  1200  1210  1220  1230  1240  1310  1340  14000 14010
			     14020 2010  2020  2030  2040  2050  2070  2080  2150  2170  2220  2230  2290  2300  2310  2320  2330  2340  2370  2400
			     2410  2450  2460  2470  2510  2520  2530  3010  3020  3030  3040  3070  3080  3090  3100  3130  3140  3150  3160  3190
			     3200  3210  3220  3250  3260  3270  3280  3320  3330  3340  3400  3410  3420  3430  4010  4020  4030  4040  4050  4060
			     4070  4120  4130  4140  4150  4170  4190  4200  4220  4250  5010  5020  5030  5050  5060  5070  5080  5090  5100  5110
			     5120  5130  5140  5160  5180  5190  5200  5210  5220  5310  5320  5330  5350  5360  5370  5410  5420  5470  5480  5490
			     5500  5550  6210  6220  6230  6240  6250  6260  6270  6290  8010  8020  8030  8040  8050  8080  8090  8150  8160  8170
			     8210  8280  8290  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130  9140  9190  9200  9210
			     9220  9270  9290  9350
			   }
  inventions             = { 8000 8001 8010 }
  diplomacy =
  { relation = { tag = ARG value = 75 }
    relation = { tag = AST value = -200 }
    relation = { tag = BEL value = -200 }
    relation = { tag = BHU value = -200 }
    relation = { tag = BOL value = 15 }
    relation = { tag = BRA value = 50 }
    relation = { tag = BUL value = 200 access = yes }
    relation = { tag = CAN value = -200 }
    relation = { tag = CHL value = 50 }
    relation = { tag = COL value = -20 }
    relation = { tag = SLO value = 200 }
    relation = { tag = ENG value = -200 }
    relation = { tag = FIN value = 125 access = yes }
    relation = { tag = FRA value = -200 }
    relation = { tag = HOL value = -200 }
    relation =
    { tag        = HUN
      value      = 200
      access     = yes
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation =
    { tag        = ITA
      value      = 200
      access     = yes
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation =
    { tag        = JAP
      value      = 135
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation = { tag = MAN value = 20 }
    relation = { tag = MEN value = 20 }
    relation = { tag = NEP value = -200 }
    relation = { tag = NIC value = -200 }
    relation = { tag = NZL value = -200 }
    relation = { tag = OMN value = -200 }
    relation = { tag = POR value = 75 }
    relation =
    { tag        = ROM
      value      = 200
      access     = yes
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation = { tag = SAF value = -200 }
    relation = { tag = SCH value = 50 }
    relation = { tag = SOV value = -200 }
    relation =
    { tag        = SPA
      value      = 50
      guaranteed = { day = 18 month = november year = 1940 }
    }
    relation = { tag = SWE value = 50 access = yes }
    relation = { tag = TUR value = 10 }
    relation = { tag = USA value = -125 }
    relation = { tag = VIC value = 75 guaranteed = { day = 1 month = january year = 1941 } }
    relation = { tag = YEM value = -200 }
  }
  headofstate            = { type = 9 id = 1 }
  headofgovernment       = { type = 9 id = 42 }
  foreignminister        = { type = 9 id = 55 }
  armamentminister       = { type = 9 id = 80 }
  ministerofsecurity     = { type = 9 id = 108 }
  ministerofintelligence = { type = 9 id = 6 }
  chiefofstaff           = { type = 9 id = 156 }
  chiefofarmy            = { type = 9 id = 176 }
  chiefofnavy            = { type = 9 id = 9 }
  chiefofair             = { type = 9 id = 10 }
  dormant_ministers      = { 33 45 46 51 3 64 4 77 5 116 7 8 179 2 65 76 95 96 155 166 208 52 131 36 }
  dormant_leaders        = { 398 579 607 473 }
  # HEER
  # Heeresgruppe Süd
  landunit =
  { location = 479
    id       = { type = 10500 id = 500 }
    name     = "Hk HG Süd"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 1113 }
      name      = "Heeresgruppe Süd HQ"
      type      = hq
      model     = 1
      strength  = 100
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 501 }
      name      = "99. lei. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 502 }
      name      = "2. Fallschirmjaeger-Rgt"
      strength  = 35
      type      = paratrooper
      model     = 2
    }
  }
  landunit =
  { location = 479
    id       = { type = 10500 id = 503 }
    name     = "H.Kdo.XXXIV. (HG Süd Reserven)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 504 }
      name      = "125. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 505 }
      name      = "4. Gebirgs-Division"
      strength  = 100
      type      = bergsjaeger
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 506 }
      name      = "113. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 507 }
      name      = "132. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  landunit =
  { location = 479
    id       = { type = 10500 id = 508 }
    name     = "LI. Korps -HG Süd Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 509 }
      name      = "79. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 510 }
      name      = "95. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  # 11. Armee
  landunit =
  { location = 429
    id       = { type = 10500 id = 511 }
    name     = "11. Armee Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 512 }
      name      = "22. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = SP_artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 513 }
      name      = "72. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = anti_air
    }
  }
  landunit =
  { location = 429
    id       = { type = 10500 id = 514 }
    name     = "LIV. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 515 }
      name      = "50. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
  }
  landunit =
  { location = 429
    id       = { type = 10500 id = 517 }
    name     = "XXX. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 518 }
      name      = "198. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 516 }
      name      = "170. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = anti_tank
    }
  }
  landunit =
  { location = 429
    id       = { type = 10500 id = 519 }
    name     = "XI. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 520 }
      name      = "76. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = SP_artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 521 }
      name      = "239. Infanterie-Division"
      strength  = 100
      model     = 2
      type      = infantry
    }
  }
  # 17. Armee
  landunit =
  { location = 489
    id       = { type = 10500 id = 522 }
    name     = "17. Armee Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 523 }
      name      = "100. lei. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 524 }
      name      = "97. lei. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = anti_air
    }
  }
  landunit =
  { location = 489
    id       = { type = 10500 id = 525 }
    name     = "LII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 526 }
      name      = "454. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 527 }
      name      = "444. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 528 }
      name      = "101. lei. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
  }
  landunit =
  { location = 499
    id       = { type = 10500 id = 529 }
    name     = "XXXXIX. Geb. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 530 }
      name      = "257. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 531 }
      name      = "68. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 532 }
      name      = "1. Gebirgs-Division"
      strength  = 100
      type      = bergsjaeger
      model     = 2
      extra     = anti_tank
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 533 }
    name     = "IV. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 534 }
      name      = "71. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 535 }
      name      = "295. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 536 }
      name      = "24. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 537 }
      name      = "262. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = anti_tank
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 538 }
      name      = "296. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  # 6. Armee
  landunit =
  { location = 488
    id       = { type = 10500 id = 539 }
    name     = "LV. Korps -6 Armee Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 540 }
      name      = "168. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 541 }
      name      = "213. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 542 }
    name     = "XXXXIV. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 543 }
      name      = "9. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 544 }
      name      = "297. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 545 }
    name     = "Panzergruppe 1 -Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 546 }
      name      = "9. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg/IIIh
      extra     = tank_destroyer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 547 }
      name      = "16. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg/IIIh
      extra     = tank_destroyer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 548 }
      name      = "16. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = anti_air
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 549 }
      name      = "25. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 550 }
      name      = "5. Waffen SS-Division 'Wiking'"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = SP_artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 551 }
      name      = "1. Waffen SS-Division 'Leibstandarte AH'"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = tank_destroyer
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 552 }
    name     = "XXXXVIII. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 553 }
      name      = "57. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = rocket_artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 554 }
      name      = "75. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 555 }
      name      = "11. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg/IIIh
      extra     = SP_artillery
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 556 }
    name     = "XXIX. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 557 }
      name      = "111. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 558 }
      name      = "299. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 559 }
    name     = "III. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 560 }
      name      = "44. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 561 }
      name      = "298. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 562 }
      name      = "14. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg/IIIh
      extra     = SP_artillery
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 563 }
    name     = "XVII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 564 }
      name      = "62. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 565 }
      name      = "56. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
  }
  landunit =
  { location = 488
    id       = { type = 10500 id = 566 }
    name     = "XIV. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 567 }
      name      = "13. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIe/IIIg
      extra     = armored_car
    }
  }
  # Heeresgruppe Mitte
  landunit =
  { location = 485
    id       = { type = 10500 id = 568 }
    name     = "Hk HG Mitte"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 1112 }
      name      = "Heeresgruppe Mitte HQ"
      type      = hq
      model     = 1
      strength  = 100
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 569 }
      name      = "293. Infanterie-Division"
      strength  = 100
      model     = 2
      type      = infantry
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 570 }
      name      = "102. Infanterie-Division"
      strength  = 100
      model     = 2
      type      = infantry
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 571 }
      name      = "403. Sicherungs-Division"
      strength  = 100
      model     = 1
      type      = infantry
      extra     = police
    }
  }
  landunit =
  { location = 483
    id       = { type = 10500 id = 572 }
    name     = "H.Kdo.XXXV. (HG Mitte reserven)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 573 }
      name      = "293. Infanterie-Division"
      strength  = 100
      model     = 2
      type      = infantry
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 574 }
      name      = "293. Infanterie-Division"
      strength  = 100
      model     = 2
      type      = infantry
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 575 }
    name     = "XXIV. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 576 }
      name      = "1. Kavallerie-Division"
      strength  = 100
      type      = cavalry
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 577 }
      name      = "4. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg/IIIh
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 578 }
      name      = "3. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg/IIIh
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 579 }
      name      = "10. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = armored_car
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 580 }
      name      = "267. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = anti_tank
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 581 }
    name     = "XII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 582 }
      name      = "34. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 583 }
      name      = "45. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 584 }
      name      = "31. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = anti_air
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 585 }
    name     = "XXXXVII. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 586 }
      name      = "18. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg
      extra     = armored_car
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 587 }
      name      = "17. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIh
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 588 }
      name      = "29. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = tank_destroyer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 589 }
      name      = "167. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = armored_car
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 590 }
    name     = "XXXXVI. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 591 }
      name      = "2. Waffen SS-Division 'Reich'"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = tank_destroyer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 592 }
      name      = "10. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIh
      extra     = SP_artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 593 }
      name      = "I.R. 'GrossDeutschland'"
      strength  = 45
      type      = motorized
      model     = 1
      extra     = tank_destroyer
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 594 }
    name     = "Hk Panzergruppe 2"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 595 }
      name      = "255. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 596 }
    name     = "4. Armee -reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 597 }
      name      = "286. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 598 }
    name     = "XXXXIII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 599 }
      name      = "131. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 600 }
      name      = "134. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 601 }
      name      = "252 Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = anti_air
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 602 }
    name     = "IX. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 603 }
      name      = "292. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 604 }
      name      = "137. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 605 }
      name      = "263 Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
  }
  landunit =
  { location = 487
    id       = { type = 10500 id = 606 }
    name     = "VII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 607 }
      name      = "268. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 608 }
      name      = "7. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = armored_car
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 609 }
      name      = "23 Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = anti_tank
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 610 }
      name      = "221. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 611 }
      name      = "258 Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = anti_tank
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 612 }
    name     = "XIII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 613 }
      name      = "78. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = tank_destroyer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 614 }
      name      = "17. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 615 }
    name     = "XX. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 616 }
      name      = "162. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 617 }
      name      = "256. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 618 }
    name     = "VIII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 619 }
      name      = "8. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 620 }
      name      = "28. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = armored_car
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 621 }
      name      = "161 Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = anti_tank
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 622 }
    name     = "LVII. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 623 }
      name      = "12. Panzer-Division"
      strength  = 100
      type      = light_armor
      model     = 2 # Pz38t
      extra     = SP_artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 624 }
      name      = "19. armor-Division"
      strength  = 100
      type      = light_armor
      model     = 2 # Pz38t
      extra     = armored_car
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 625 }
      name      = "18. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 626 }
    name     = "V. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 627 }
      name      = "5. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 628 }
      name      = "35. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 629 }
    name     = "XXXIX. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 630 }
      name      = "7. Panzer-Division"
      strength  = 100
      type      = light_armor
      model     = 2 # Pz38t
      extra     = SP_artillery
    }
    division =
    { offensive     = { year = 1941 month = august day = 15 }
      id            = { type = 10500 id = 631 }
      name          = "20. Panzer-Division"
      strength      = 100
      type          = light_armor
      model         = 2 # Pz38t
      extra         = tank_destroyer
      brigade_model = 1
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 632 }
      name      = "20. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = tank_destroyer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 633 }
      name      = "14. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = engineer
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 634 }
    name     = "VI. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 635 }
      name      = "6. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 636 }
      name      = "26. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 637 }
    name     = "9. Armee Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 638 }
      name      = "87. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 639 }
      name      = "129. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 640 }
    name     = "16. Armee -Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 641 }
      name      = "253. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 642 }
    name     = "II. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 643 }
      name      = "32. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 644 }
      name      = "12. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 645 }
      name      = "121. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = engineer
    }
  }
  landunit =
  { location = 486
    id       = { type = 10500 id = 646 }
    name     = "XXVIII. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 647 }
      name      = "123. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 648 }
      name      = "122. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
  }
  landunit =
  { location = 206
    id       = { type = 10500 id = 649 }
    name     = "X. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 650 }
      name      = "126. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 651 }
      name      = "30. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
  }
  landunit =
  { location = 510
    id       = { type = 10500 id = 652 }
    name     = "LVI. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 653 }
      name      = "8. Panzer-Division"
      strength  = 100
      type      = light_armor
      model     = 2 # pz38t
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 654 }
      name      = "290. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
      extra     = armored_car
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 655 }
      name      = "3. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = SP_artillery
    }
  }
  landunit =
  { location = 510
    id       = { type = 10500 id = 656 }
    name     = "XXXXI. Korps (mot)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 657 }
      name      = "6. Panzer-Division"
      strength  = 100
      type      = light_armor
      model     = 2 # Pz38t
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 658 }
      name      = "269. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 659 }
      name      = "36. Infanterie-Division (mot)"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 660 }
      name      = "1. Panzer-Division"
      strength  = 100
      type      = armor
      model     = 2 # IIIg
      extra     = tank_destroyer
    }
  }
  landunit =
  { location = 305
    id       = { type = 10500 id = 661 }
    name     = "Panzergruppe 4 -Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 662 }
      name      = "3. Waffen SS-Division 'Totenkopf'"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = SP_artillery
    }
  }
  landunit =
  { location = 305
    id       = { type = 10500 id = 663 }
    name     = "18. Armee -Reserven"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 664 }
      name      = "58. Infanterie-Division"
      strength  = 100
      type      = motorized
      model     = 1
      extra     = anti_air
    }
  }
  landunit =
  { location = 206
    id       = { type = 10500 id = 665 }
    name     = "I. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 667 }
      name      = "1. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 668 }
      name      = "11. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 669 }
      name      = "21. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
  }
  landunit =
  { location = 510
    id       = { type = 10500 id = 670 }
    name     = "XXVI. Korps"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 671 }
      name      = "217. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = artillery
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 672 }
      name      = "61. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 673 }
      name      = "291. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
  }
  landunit =
  { location = 510
    id       = { type = 10500 id = 674 }
    name     = "Hk HG Nord"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 1101 }
      name      = "Heeresgruppe Nord HQ"
      type      = hq
      model     = 1
      strength  = 100
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 675 }
      name      = "206. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
      extra     = engineer
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 676 }
      name      = "251. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 3
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 677 }
      name      = "254. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 678 }
      name      = "7. Flieger-Division"
      strength  = 100
      type      = paratrooper
      model     = 2
    }
  }
  landunit =
  { location = 510
    id       = { type = 10500 id = 679 }
    name     = "Bef.Rückw.H.G 101 (HG Nord -Res)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 680 }
      name      = "285. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 681 }
      name      = "281. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 682 }
      name      = "207. Sicherungs-Division"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
  }
  landunit =
  { location = 304
    id       = { type = 10500 id = 683 }
    name     = "L. Korps (HG Nord -Res)"
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 684 }
      name      = "86. Infanterie-Division"
      strength  = 100
      type      = infantry
      model     = 2
    }
    division =
    { offensive = { year = 1941 month = august day = 15 }
      id        = { type = 10500 id = 685 }
      name      = "4. Waffen SS-Division 'Polizei'"
      strength  = 100
      type      = infantry
      model     = 1
      extra     = police
    }
  }
  # # Other fronts
  landunit =
  { location = 45
    id       = { type = 10500 id = 686 }
    name     = "H.Kdo.LXX."
    division =
    { id       = { type = 10500 id = 687 }
      name     = "69. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 688 }
      name     = "214. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 689 }
      name     = "163. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 18
    id       = { type = 10500 id = 690 }
    name     = "H.Kdo.XXXIII."
    division =
    { id       = { type = 10500 id = 691 }
      name     = "196. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 692 }
      name     = "181. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
  }
  landunit =
  { location = 107
    id       = { type = 10500 id = 693 }
    name     = "Geb.Kps.Norwegen"
    division =
    { id       = { type = 10500 id = 694 }
      name     = "3. Gebirgsjäger-Division"
      strength = 100
      type     = bergsjaeger
      extra    = artillery
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 695 }
      name     = "2. Gebirgsjäger-Division"
      strength = 100
      type     = bergsjaeger
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 696 }
      name     = "199. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 697 }
      name     = "702. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 125
    id       = { type = 10500 id = 698 }
    name     = "Hk A.O.K Norwegen"
    division =
    { id       = { type = 10500 id = 699 }
      name     = "710. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 1
    }
  }
  landunit =
  { location = 125
    id       = { type = 10500 id = 700 }
    name     = "H.Kdo.XXXVI."
    division =
    { id       = { type = 10500 id = 701 }
      name     = "6. Waffen SS-Division 'Nord'"
      strength = 100
      type     = bergsjaeger
      model    = 1
    }
    division =
    { id       = { type = 10500 id = 702 }
      name     = "169. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 47
    id       = { type = 10500 id = 703 }
    name     = "H.Kdo.XXXI."
    division =
    { id       = { type = 10500 id = 704 }
      name     = "223. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 705 }
      name     = "708. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 706 }
      name     = "88. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 707 }
      name     = "212. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 708 }
      name     = "333. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 32
    id       = { type = 10500 id = 709 }
    name     = "H.Kdo.LIX."
    division =
    { id       = { type = 10500 id = 710 }
      name     = "81. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 711 }
      name     = "305. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 712 }
      name     = "246. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 713 }
      name     = "715. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 38
    id       = { type = 10500 id = 714 }
    name     = "XXV. Korps"
    division =
    { id       = { type = 10500 id = 715 }
      name     = "709. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 716 }
      name     = "211. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 717 }
      name     = "205. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 718 }
      name     = "712. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 57
    id       = { type = 10500 id = 719 }
    name     = "H.Kdo.LX."
    division =
    { id       = { type = 10500 id = 720 }
      name     = "323. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 721 }
      name     = "83. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 722 }
      name     = "216. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 723 }
      name     = "319. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 323
    id       = { type = 10500 id = 724 }
    name     = "H.Kdo.XXXII."
    division =
    { id       = { type = 10500 id = 725 }
      name     = "336. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 726 }
      name     = "302. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 727 }
      name     = "225. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 728 }
      name     = "332. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 729 }
      name     = "716. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 35
    id       = { type = 10500 id = 730 }
    name     = "H.Kdo.XXXVII."
    division =
    { id       = { type = 10500 id = 731 }
      name     = "320. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 732 }
      name     = "321. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 733 }
      name     = "208. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 734 }
      name     = "304. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 735 }
      name     = "340. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 736 }
      name     = "306. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 737 }
      name     = "227. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  # # Southeast
  landunit =
  { location = 403
    id       = { type = 10500 id = 738 }
    name     = "H.Kdo.LXV."
    division =
    { id       = { type = 10500 id = 739 }
      name     = "714. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 740 }
      name     = "717. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
    division =
    { id       = { type = 10500 id = 741 }
      name     = "718. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 742 }
      name     = "704. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 386
    id       = { type = 10500 id = 743 }
    name     = "XVIII. Geb. Korps"
    division =
    { id       = { type = 10500 id = 744 }
      name     = "5. Gebirgs-Division"
      strength = 100
      type     = bergsjaeger
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 745 }
      name     = "6. Gebirgs-Division"
      strength = 100
      type     = bergsjaeger
      model    = 2
      extra    = anti_tank
    }
  }
  landunit =
  { location = 455
    id       = { type = 10500 id = 746 }
    name     = "12. Armee -Reserven"
    division =
    { id       = { type = 10500 id = 747 }
      name     = "164. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
      extra    = police
    }
  }
  # Afrika
  landunit =
  { location = 916
    id       = { type = 10500 id = 748 }
    name     = "Deutsche Afrika-Korps"
    division =
    { id            = { type = 10500 id = 749 }
      name          = "15. Panzer-Division"
      strength      = 50
      type          = armor
      model         = 2 # PzIIIh
      extra         = tank_destroyer
      brigade_model = 1
    }
    division =
    { id       = { type = 10500 id = 750 }
      name     = "5. lei. Infanterie-Division (mot)"
      strength = 100
      type     = motorized
      model    = 1
      extra    = armored_car
    }
  }
  # Denmark
  landunit =
  { location = 294
    id       = { type = 10500 id = 751 }
    name     = "218 Infanterie-Division"
    division =
    { id       = { type = 10500 id = 752 }
      name     = "218. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  # Germany
  landunit =
  { location = 300
    id       = { type = 10500 id = 753 }
    name     = "z.Vfg. im Heimatkriegsgebiet"
    division =
    { id       = { type = 10500 id = 754 }
      name     = "707. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 755 }
      name     = "713. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 309
    id       = { type = 10500 id = 756 }
    name     = "2. Armee"
    division =
    { id       = { type = 10500 id = 757 }
      name     = "2. Panzer-Division"
      strength = 100
      type     = armor
      model    = 3
      extra    = tank_destroyer
    }
    division =
    { id       = { type = 10500 id = 758 }
      name     = "60. Infanterie-Division (mot)"
      strength = 100
      type     = motorized
      model    = 1
      extra    = SP_artillery
    }
    division =
    { id       = { type = 10500 id = 759 }
      name     = "294. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 760 }
      name     = "46. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 761 }
      name     = "73. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 762 }
      name     = "183. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 763 }
      name     = "93. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 764 }
      name     = "94. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 765 }
      name     = "96. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 766 }
      name     = "98. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 767 }
      name     = "260. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 768 }
      name     = "5. armor-Division"
      strength = 100
      type     = armor
      model    = 2
      extra    = SP_artillery
    }
  }
  landunit =
  { location = 300
    id       = { type = 10500 id = 769 }
    name     = "OKW Reserven"
    division =
    { id            = { type = 10500 id = 1100 }
      name          = "OKW Reserven HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 2
    }
    division =
    { id       = { type = 10500 id = 770 }
      name     = "22. Panzer-Division"
      strength = 20
      type     = light_armor
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 771 }
      name     = "23. Panzer-Division"
      strength = 20
      type     = light_armor
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 772 }
      name     = "88. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 773 }
      name     = "205. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 774 }
      name     = "211. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 775 }
      name     = "212. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 776 }
      name     = "215. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 777 }
      name     = "223. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 778 }
      name     = "327. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 779 }
      name     = "333. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 780 }
      name     = "335. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 781 }
      name     = "337. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 782 }
      name     = "339. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 783 }
      name     = "340. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
    division =
    { id       = { type = 10500 id = 784 }
      name     = "342. Infanterie-Division"
      strength = 100
      type     = infantry
      model    = 2
    }
  }
  landunit =
  { location = 510
    id       = { type = 10500 id = 1102 }
    name     = "4. Panzergruppe HQ"
    division =
    { offensive     = { year = 1941 month = august day = 15 }
      id            = { type = 10500 id = 1103 }
      name          = "4. Panzergruppe HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { location = 485
    id       = { type = 10500 id = 1104 }
    name     = "3. Panzergruppe HQ"
    division =
    { offensive     = { year = 1941 month = august day = 15 }
      id            = { type = 10500 id = 1105 }
      name          = "3. Panzergruppe HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { location = 484
    id       = { type = 10500 id = 1106 }
    name     = "2. Panzergruppe HQ"
    division =
    { offensive     = { year = 1941 month = august day = 15 }
      id            = { type = 10500 id = 1107 }
      name          = "2. Panzergruppe HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { location = 480
    id       = { type = 10500 id = 1108 }
    name     = "1. Panzergruppe HQ"
    division =
    { offensive     = { year = 1941 month = august day = 15 }
      id            = { type = 10500 id = 1109 }
      name          = "1. Panzergruppe HQ"
      type          = hq
      model         = 1
      strength      = 100
      extra         = anti_air
      brigade_model = 1
    }
  }
  landunit =
  { location = 125
    id       = { type = 10500 id = 1110 }
    name     = "Armee Norwegen HQ"
    division =
    { id       = { type = 10500 id = 1111 }
      name     = "Armee Norwegen HQ"
      type     = hq
      model    = 1
      strength = 100
      extra    = police
    }
  }
  landunit =
  { location = 51
    id       = { type = 10500 id = 1114 }
    name     = "MB Belgien & Niederlände HQ"
    division =
    { id       = { type = 10500 id = 1115 }
      name     = "MB Belgien & Niederlände HQ"
      type     = hq
      model    = 1
      strength = 100
      extra    = police
    }
  }
  landunit =
  { location = 56
    id       = { type = 10500 id = 1116 }
    name     = "MB Frankreich HQ"
    division =
    { id       = { type = 10500 id = 1117 }
      name     = "MB Frankreich HQ"
      type     = hq
      model    = 1
      strength = 100
      extra    = police
    }
  }
  # KRIEGSMARINE
  navalunit =
  { name     = "Atlantische Flotte"
    id       = { type = 10500 id = 1 }
    location = 32 # Brest
    base     = 32 # Brest
    division =
    { id    = { type = 10500 id = 2 }
      name  = "KMS Scharnhorst"
      type  = battlecruiser
      model = 3
    }
    division =
    { id    = { type = 10500 id = 3 }
      name  = "KMS Gneisenau"
      type  = battlecruiser
      model = 3
    }
    division =
    { id    = { type = 10500 id = 4 }
      name  = "1. Zerstörergeschwader"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10500 id = 62 }
      name  = "2. Zerstörergeschwader"
      type  = destroyer
      model = 3
    }
    division =
    { id    = { type = 10500 id = 63 }
      name  = "3. Zerstörergeschwader"
      type  = destroyer
      model = 3
    }
  }
  navalunit =
  { name     = "Baltische Flotte"
    id       = { type = 10500 id = 5 }
    location = 302 # Stettin
    base     = 302 # Stettin
    division =
    { id    = { type = 10500 id = 6 }
      name  = "KMS Tirpitz"
      type  = battleship
      model = 3
    }
    division =
    { id    = { type = 10500 id = 7 }
      name  = "KMS Admiral Scheer"
      type  = heavy_cruiser
      model = 3
    }
    division =
    { id    = { type = 10500 id = 8 }
      name  = "KMS Köln"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 10500 id = 64 }
      name  = "4. Zerstörergeschwader"
      type  = destroyer
      model = 2
    }
    division =
    { id   = { type = 10500 id = 9 }
      name = "1. Truppentransporterflottille"
      type = transport
    }
    division =
    { id   = { type = 10500 id = 10 }
      name = "2. Truppentransporterflottille"
      type = transport
    }
  }
  navalunit =
  { name     = "Deutschland Geschwader"
    id       = { type = 10500 id = 12 }
    location = 90 # Kiel
    base     = 90 # Kiel
    division =
    { id    = { type = 10500 id = 13 }
      name  = "KMS Admiral Hipper"
      type  = heavy_cruiser
      model = 3
    }
    division =
    { id    = { type = 10500 id = 14 }
      name  = "KMS Deutschland"
      type  = heavy_cruiser
      model = 3
    }
  }
  navalunit =
  { name     = "5. Zerstörergeschwader"
    id       = { type = 10500 id = 15 }
    location = 110 # Bergen
    base     = 110 # Bergen
    division =
    { id    = { type = 10500 id = 16 }
      name  = "5. Zerstörergeschwader"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "8. Zerstörergeschwader"
    id       = { type = 10500 id = 17 }
    location = 125 # Narvik
    base     = 125 # Narvik
    division =
    { id    = { type = 10500 id = 18 }
      name  = "8. Zerstörergeschwader"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "Kriegsmarine Reserven"
    id       = { type = 10500 id = 19 }
    location = 302 # Stettin
    base     = 302 # Stettin
    division =
    { id    = { type = 10500 id = 61 }
      name  = "KMS Prinz Eugen"
      type  = heavy_cruiser
      model = 3
    }
    division =
    { id    = { type = 10500 id = 20 }
      name  = "KMS Nürnberg"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10500 id = 21 }
      name  = "KMS Schleswig-Holstein"
      type  = battlecruiser
      model = 0
    }
    division =
    { id    = { type = 10500 id = 22 }
      name  = "KMS Schlesien"
      type  = battlecruiser
      model = 0
    }
    division =
    { id    = { type = 10500 id = 23 }
      name  = "KMS Emden"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10500 id = 24 }
      name  = "KMS Leipzig"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 10500 id = 65 }
      name  = "6. Zerstörergeschwader"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10500 id = 66 }
      name  = "41. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 67 }
      name  = "42. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 68 }
      name  = "43. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 69 }
      name  = "44. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 70 }
      name  = "45. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 71 }
      name  = "46. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 72 }
      name  = "47. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 73 }
      name  = "48. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 74 }
      name  = "49. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 75 }
      name  = "50. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 76 }
      name  = "51. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 77 }
      name  = "52. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 78 }
      name  = "53. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10500 id = 79 }
      name  = "54. Unterseebootsflottille"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10500 id = 80 }
      name  = "55. Unterseebootsflottille"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10500 id = 81 }
      name  = "56. Unterseebootsflottille"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10500 id = 82 }
      name  = "57. Unterseebootsflottille"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10500 id = 83 }
      name  = "58. Unterseebootsflottille"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10500 id = 84 }
      name  = "59. Unterseebootsflottille"
      type  = submarine
      model = 3
    }
  }
  navalunit =
  { name     = "1. Unterseebootsflottille"
    id       = { type = 10500 id = 27 }
    location = 2422 # Western Approaches
    base     = 59 # La Rochelle
    division =
    { id    = { type = 10500 id = 28 }
      name  = "1. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "2. Unterseebootsflottille"
    id       = { type = 10500 id = 29 }
    location = 2422 # Western Approaches
    base     = 59 # La Rochelle
    division =
    { id    = { type = 10500 id = 30 }
      name  = "2. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "3. Unterseebootsflottille"
    id       = { type = 10500 id = 31 }
    location = 2422 # Western Approaches
    base     = 59 # La Rochelle
    division =
    { id    = { type = 10500 id = 32 }
      name  = "3. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "4. Unterseebootsflottille"
    id       = { type = 10500 id = 33 }
    location = 2422 # Western Approaches
    base     = 59 # La Rochelle
    division =
    { id    = { type = 10500 id = 34 }
      name  = "4. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "5. Unterseebootsflottille"
    id       = { type = 10500 id = 35 }
    location = 2421 # North Atlantic
    base     = 34 # Lorient
    division =
    { id    = { type = 10500 id = 36 }
      name  = "5. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "6. Unterseebootsflottille"
    id       = { type = 10500 id = 37 }
    location = 2421 # North Atlantic
    base     = 34 # Lorient
    division =
    { id    = { type = 10500 id = 38 }
      name  = "6. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "7. Unterseebootsflottille"
    id       = { type = 10500 id = 39 }
    location = 2421 # North Atlantic
    base     = 34 # Lorient
    division =
    { id    = { type = 10500 id = 40 }
      name  = "7. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "8. Unterseebootsflottille"
    id       = { type = 10500 id = 41 }
    location = 2421 # North Atlantic
    base     = 34 # Lorient
    division =
    { id    = { type = 10500 id = 42 }
      name  = "8. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "9. Unterseebootsflottille"
    id       = { type = 10500 id = 43 }
    location = 2380 # Northwest of Norway
    base     = 125 # Narvik
    division =
    { id    = { type = 10500 id = 44 }
      name  = "9. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "23. Unterseebootsflottille"
    id       = { type = 10500 id = 45 }
    location = 2440 # Central Mediterranean
    base     = 34 # Lorient
    division =
    { id    = { type = 10500 id = 46 }
      name  = "23. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "24. Unterseebootsflottille"
    id       = { type = 10500 id = 47 }
    location = 2430 # Western Med
    base     = 34 # Lorient
    division =
    { id    = { type = 10500 id = 48 }
      name  = "24. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "25. Unterseebootsflottille"
    id       = { type = 10500 id = 49 }
    location = 2451 # Eastern Med
    base     = 34 # Lorient
    division =
    { id    = { type = 10500 id = 50 }
      name  = "25. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "26. Unterseebootsflottille"
    id       = { type = 10500 id = 51 }
    location = 32 # Brest
    base     = 32 # Brest
    division =
    { id    = { type = 10500 id = 52 }
      name  = "26. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "27. Unterseebootsflottille"
    id       = { type = 10500 id = 53 }
    location = 32 # Brest
    base     = 32 # Brest
    division =
    { id    = { type = 10500 id = 54 }
      name  = "27. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "29. Unterseebootsflottille"
    id       = { type = 10500 id = 55 }
    location = 32 # Brest
    base     = 32 # Brest
    division =
    { id    = { type = 10500 id = 56 }
      name  = "29. Unterseebootsflottille"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { name     = "21. Unterseebootsflottille"
    id       = { type = 10500 id = 57 }
    location = 302 # Stettin
    base     = 302 # Stettin
    division =
    { id    = { type = 10500 id = 58 }
      name  = "21. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "22. Unterseebootsflottille"
    id       = { type = 10500 id = 59 }
    location = 2480 # Baltic Sea
    base     = 32 # Stettin
    division =
    { id    = { type = 10500 id = 60 }
      name  = "22. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  # LUFTWAFFE
  # Luftflotte 1
  airunit =
  { id       = { type = 10500 id = 400 }
    name     = "I. Fliegerkorps"
    location = 510
    base     = 510
    division =
    { id       = { type = 10500 id = 401 }
      name     = "KG 1 'Hindenburg'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88
      extra         = escort
      brigade_model = 0
    }
    division =
    { id       = { type = 10500 id = 402 }
      name     = "Kampfgeschwader 76"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88
      extra         = escort
      brigade_model = 0
    }
    division =
    { id       = { type = 10500 id = 403 }
      name     = "JG 54 'Grunherz'"
      strength = 100
      type     = multi_role
      model    = 0 # 109F
    }
    division =
    { id       = { type = 10500 id = 404 }
      name     = "Küstenfliegergruppe 806"
      strength = 35
      type     = naval_bomber
      model    = 1 # Ju88
    }
  }
  # Luftflotte 2
  airunit =
  { id       = { type = 10500 id = 405 }
    name     = "II. Fliegerkorps"
    location = 487
    base     = 487
    division =
    { id       = { type = 10500 id = 406 }
      name     = "JG 53 'Pik As'"
      strength = 100
      type     = multi_role
      model    = 0 # 109F
    }
    division =
    { id       = { type = 10500 id = 407 }
      name     = "KG 3 'Blitz'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88/He111
    }
    division =
    { id       = { type = 10500 id = 408 }
      name     = "KG 53 'Legion Condor'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # He 111
    }
    division =
    { id       = { type = 10500 id = 409 }
      name     = "Sturzkampfgeschwader 77"
      strength = 100
      type     = cas
      model    = 0 # Ju87B
    }
    division =
    { id       = { type = 10500 id = 410 }
      name     = "Schnellkampfgeschwader 210"
      strength = 100
      type     = multi_role
      model    = 0 # Bf 110
    }
    division =
    { id       = { type = 10500 id = 411 }
      name     = "JG 51 'Mölders'"
      strength = 100
      type     = multi_role
      model    = 0 # 109F
    }
  }
  airunit =
  { id       = { type = 10500 id = 412 }
    name     = "VIII. Fliegerkorps"
    location = 510
    base     = 510
    division =
    { id       = { type = 10500 id = 413 }
      name     = "KG 2 'Holzhammer'"
      strength = 100
      type     = tactical_bomber
      model    = 1 # Do17
    }
    division =
    { id       = { type = 10500 id = 414 }
      name     = "Schlachtgeschwader 1"
      strength = 100
      type     = cas
      model    = 0 # Ju87B
    }
    division =
    { id       = { type = 10500 id = 415 }
      name     = "StG 2 'Immelmann'"
      strength = 100
      type     = cas
      model    = 0 # Ju87B
    }
    division =
    { id       = { type = 10500 id = 416 }
      name     = "JG 2 'Richthofen'"
      strength = 75
      type     = multi_role
      model    = 0 # Bf 109/Hs 123
    }
    division =
    { id       = { type = 10500 id = 417 }
      name     = "JG 26 'Schlageter'"
      strength = 100
      type     = multi_role
      model    = 0 # Bf 110
    }
    division =
    { id       = { type = 10500 id = 418 }
      name     = "Jagdgeschwader 27"
      strength = 100
      type     = multi_role
      model    = 0 # 109F
    }
  }
  # Luftflotte 4
  airunit =
  { id       = { type = 10500 id = 419 }
    name     = "IV. Fliegerkorps"
    location = 487
    base     = 487
    division =
    { id       = { type = 10500 id = 420 }
      name     = "KG 27 'Boelcke'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # He111
    }
    division =
    { id       = { type = 10500 id = 421 }
      name     = "JG 77 'Herz As'"
      strength = 100
      type     = multi_role
      model    = 0 # Bf 109F
    }
  }
  airunit =
  { id       = { type = 10500 id = 422 }
    name     = "V. Fliegerkorps"
    location = 487
    base     = 487
    division =
    { id       = { type = 10500 id = 423 }
      name     = "KG 51 'Edelweiß'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88A
    }
    division =
    { id       = { type = 10500 id = 424 }
      name     = "KG 54 'Totenkopf'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88
    }
    division =
    { id       = { type = 10500 id = 425 }
      name     = "KG 55 'Greif'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # He111
    }
    division =
    { id       = { type = 10500 id = 426 }
      name     = "JG 3 'Udet'"
      strength = 100
      type     = multi_role
      model    = 0 # Bf 109F
    }
  }
  airunit =
  { id       = { type = 10500 id = 427 }
    name     = "KG 4 'General Wever'"
    location = 78
    base     = 78
    division =
    { id       = { type = 10500 id = 428 }
      name     = "KG 4 'General Wever'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # He111
    }
  }
  airunit =
  { id       = { type = 10500 id = 429 }
    name     = "KG 26 'Löwen'"
    location = 110
    base     = 110
    division =
    { id       = { type = 10500 id = 430 }
      name     = "KG 26 'Löwen'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # He111
    }
  }
  airunit =
  { id       = { type = 10500 id = 431 }
    name     = "KG 27 'Boelcke'"
    location = 32
    base     = 32
    division =
    { id       = { type = 10500 id = 432 }
      name     = "KG 27 'Boelcke'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # He111
    }
  }
  airunit =
  { id       = { type = 10500 id = 433 }
    name     = "Kampfgeschwader 28"
    location = 32
    base     = 32
    division =
    { id       = { type = 10500 id = 434 }
      name     = "Kampfgeschwader 28"
      strength = 100
      type     = tactical_bomber
      model    = 2 # He111
    }
  }
  airunit =
  { id       = { type = 10500 id = 435 }
    name     = "Seeaufklärungsgruppe 125"
    location = 32
    base     = 32
    division =
    { id       = { type = 10500 id = 436 }
      name     = "Seeaufklärungsgruppe 125"
      strength = 100
      type     = naval_bomber
      model    = 1 # Fw 200C
    }
  }
  airunit =
  { id       = { type = 10500 id = 437 }
    name     = "KG 30 'Adler'"
    location = 78
    base     = 78
    division =
    { id       = { type = 10500 id = 438 }
      name     = "KG 30 'Adler'"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88
    }
  }
  airunit =
  { id       = { type = 10500 id = 439 }
    name     = "Kampfgeschwader 76"
    location = 32
    base     = 32
    division =
    { id       = { type = 10500 id = 440 }
      name     = "Kampfgeschwader 76"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88
    }
  }
  airunit =
  { id       = { type = 10500 id = 441 }
    name     = "Kampfgeschwader 77"
    location = 32
    base     = 32
    division =
    { id       = { type = 10500 id = 442 }
      name     = "Kampfgeschwader 77"
      strength = 100
      type     = tactical_bomber
      model    = 2 # Ju88
    }
  }
  airunit =
  { id       = { type = 10453 id = 1 }
    name     = "Transportstaffel z.b.V."
    location = 300
    base     = 300
    division =
    { type  = transport_plane
      model = 0
      id    = { type = 10456 id = 1 }
      name  = "Transportstaffel z.b.V."
    }
    division =
    { type  = transport_plane
      model = 0
      id    = { type = 10456 id = 9999 }
      name  = "Transportstaffel z.b.V."
    }
  }
  airunit =
  { id       = { type = 10453 id = 2 }
    name     = "IX. Fliegerkorps"
    location = 78
    base     = 78
    division =
    { type       = interceptor
      model      = 2
      id         = { type = 10456 id = 2 }
      name       = "JG 7 'Nowotny'"
      experience = 5
    }
    division =
    { type       = interceptor
      model      = 2
      id         = { type = 10456 id = 3 }
      name       = "JG 6 'Horst Wessel'"
      experience = 5
    }
  }
  airunit =
  { id       = { type = 10453 id = 3 }
    name     = "Luftflotte 3"
    location = 47
    base     = 47
    division =
    { type  = multi_role
      model = 0
      id    = { type = 10456 id = 4 }
      name  = "JG 1 'Oesau'"
    }
    division =
    { type  = interceptor
      model = 2
      id    = { type = 10456 id = 5 }
      name  = "JG 5 'Eismeer'"
    }
  }
  division_development =
  { name  = "KMS Graf Zeppelin"
    type  = carrier
    model = 2
    cost  = 4.8
    id    = { type = 10500 id = 1000 }
    date  = { year = 1942 month = july day = 1 }
    extra = cag
    brigade_model = 2
  }
  division_development =
  { name  = "7. Zerstörergeschwader"
    type  = destroyer
    model = 3
    cost  = 2.4
    id    = { type = 10500 id = 1001 }
    date  = { year = 1941 month = september day = 1 }
  }
  division_development =
  { name  = "30. Unterseebootsflottille"
    type  = submarine
    model = 2
    cost  = 1.6
    id    = { type = 10500 id = 1002 }
    date  = { year = 1941 month = august day = 1 }
  }
  division_development =
  { name  = "31. Unterseebootsflottille"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10500 id = 1003 }
    date  = { year = 1941 month = september day = 1 }
  }
  division_development =
  { name  = "32. Unterseebootsflottille"
    type  = submarine
    model = 2
    cost  = 1.6
    id    = { type = 10500 id = 1004 }
    date  = { year = 1941 month = october day = 1 }
  }
}
