
##############################
# Country definition for USA #
##############################

Province =
{ id         = 1
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 6 current_size = 6 }
  supplypool = 100
}              # Reykjavik
province =
{ id         = 549
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
}              # Anchorage
province = { id = 553 supplypool = 1000 } # Juneau
province = { id = 595 ic = 2 } # Concord
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Plattsburgh
province =
{ id       = 595
  ic       = 2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id         = 600
  ic         = 3
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Boston
province =
{ id         = 602
  ic         = 4
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # New York
province = { id = 603 ic = 6 } # Newark
province =
{ id         = 606
  ic         = 2
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Washington D.C.
province = { id = 607 ic = 5 } # Baltimore
province = { id = 608 ic = 3 anti_air = 2 } # Philadelphia
province = { id = 609 ic = 1 } # Harrisburg
province = { id = 613 ic = 3 } # Buffalo
province =
{ id       = 614
  ic       = 3
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Pittsburgh
province = { id = 615 ic = 2 } # Cleveland
province =
{ id       = 616
  ic       = 8
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Detroit
province = { id = 619 ic = 1 } # Indianapolis
province =
{ id       = 620
  ic       = 3
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Chicago
province =
{ id       = 621
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Milwaukee
province =
{ id         = 633
  ic         = 4
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Norfolk
Province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 640
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province =
{ id       = 644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charleston
Province =
{ id       = 648
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Jacksonville
province =
{ id         = 651
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Miami
province = { id = 662 supplypool = 100 } # Midway Island
province =
{ id         = 663
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
  oilpool    = 1000
}              # Pearl Harbour
province =
{ id       = 670
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Atlanta
Province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Memphis
Province =
{ id       = 678
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Biloxi
province = { id = 680 ic = 2 } # New Orleans
province =
{ id       = 684
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Little Rock
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # St. Louis
province =
{ id       = 692
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Des Moines
province =
{ id       = 693
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
province =
{ id       = 698
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Bismarck
province =
{ id       = 707
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Denver
Province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Oklahoma City
province =
{ id       = 716
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Houston
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 730
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Phoenix
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Salt Lake City
Province =
{ id         = 748
  anti_air   = 1
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 8 current_size = 8 }
}              # Corpus Christi
province =
{ id         = 761
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Diego
province =
{ id         = 762
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # Los Angeles
province =
{ id       = 764
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id         = 765
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Francisco
province =
{ id         = 780
  ic         = 2
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Seattle
province =
{ id       = 783
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Portland
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Tulsa
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province =
{ id          = 889
  anti_air    = 3
  coastalfort = 6
  air_base    = { size = 4 current_size = 4 }
  Naval_base  = { size = 4 current_size = 4 }
  supplypool  = 100
}               # Colon
province = { id = 895
  air_base    = { size = 4 current_size = 4 }
  Naval_base  = { size = 4 current_size = 4 }
  supplypool = 50
} # Puerto Rico
province = { id = 1408 supplypool = 500 } # Attu Island
province =
{ id         = 1624
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Guam
province = { id = 1756 supplypool = 50 } # Samoa
province = { id = 1762 supplypool = 10 } # Phoenix Island
province = { id = 1765 supplypool = 50 } # Palmyra
province = { id = 1766 supplypool = 10 } # Johnson Island
province =
{ id         = 1786
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Wake Island

#####################
# Country main data #
#####################

country =
{ tag                    = USA
  # Resource Reserves
  energy                 = 2000
  metal                  = 2000
  rare_materials         = 1000
  oil                    = 1000
  supplies               = 1000
  money                  = 100
  manpower               = 550
  transports             = 1900
  escorts                = 14
  peacetime_ic_mod       = 0.50
  capital                = 606
  SpyInfo                = { country = "USA" NumberOfSpies = 14 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    freedom           = 10
    free_market       = 10
    professional_army = 1
    defense_lobby     = 3
    interventionism   = 4 # The Lend-Lease Act (3700), Oil Embargo against Japan (3701), and The Nanking Massacre(3724) has happened.
  }
  nationalprovinces      = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  1408 895  889
			   }
  ownedprovinces         = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1786 1624 1408 1    2
			     800  1764 1765
			   }
  controlledprovinces    = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606
			     607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614
			     629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685
			     686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789
			     790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1786 1624 1408 1    2
			     800  1764 1765
			   }
  # Usa 1941 techs
  # ######################
  techapps               = { 12100 6070  4060  4010  4020  4030  4040  4050  4120  4130  4140  4150  4190  4220  4230  4250  4260  2150
			     2160  2010  2020  2030  2040  2050  2030  2070  2290  2300  2310  2320  2330  2340  2400  2410  2450  2460  2470  2510
			     2520  1010  1020  1030  1190  1200  1210  1220  1230  1150  1160  1310  1340  5010  5020  5030  5050  5060  5070  5080
			     5090  5100  5110  5120  5130  5140  5150  5160  5180  5190  5200  5210  5220  5230  5310  5320  5330  5350  5360  5370
			     5380  5410  5420  5430  5440  5470  5480  5490  5500  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110
			     9120  9130  9140  9190  9210  9220  9230  9240  9250  9350  6010  6020  6040  6050  6060  8010  8020  8030  8040  8050
			     8060  8090  8100  8110  8160  8180  3010  3020  3030  3070  3080  3090  3100  3130  3140  3150  3190  3200  3210  3220
			     3250  3260  3270  3280  3320  3330  3340  3350  3360  3400  3410  3420  3430  14000 14010 14020 12100 12110
			   }
  diplomacy =
  { relation =
    { tag        = ARG
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = AST value = 150 }
    relation = { tag = BEL value = 75 }
    relation = { tag = BHU value = 100 }
    relation =
    { tag        = BOL
      value      = 85
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = BRA
      value      = 120
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = CAN value = 200 }
    relation =
    { tag        = CHL
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = COL
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = COS
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = CUB
      value      = 200
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = DOM
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = ECU
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = 90 }
    relation = { tag = FRA value = 65 }
    relation = { tag = GER value = -125 }
    relation =
    { tag        = GUA
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = HAI
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = HOL value = 70 }
    relation =
    { tag        = HON
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = IRE value = 75 }
    relation = { tag = JAP value = -125 }
    relation = { tag = LIB value = 200 access = yes }
    relation = { tag = MAN value = -200 }
    relation = { tag = MEN value = -200 }
    relation =
    { tag        = MEX
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = NEP value = 100 }
    relation =
    { tag        = NIC
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation =
    { tag        = PAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = PAR
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = PHI value = 200 access = yes }
    relation =
    { tag        = PRU
      value      = 75
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SAF value = 125 }
    relation =
    { tag        = SAL
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = SOV value = 175 }
    relation = { tag = SWE value = 75 }
    relation =
    { tag        = URU
      value      = 100
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation =
    { tag        = VEN
      value      = 125
      guaranteed = { day = 30 month = december year = 1940 }
    }
    relation = { tag = YEM value = 100 }
  }
  headofstate            = { type = 9 id = 6001 }
  headofgovernment       = { type = 9 id = 6044 }
  foreignminister        = { type = 9 id = 6003 }
  armamentminister       = { type = 9 id = 6077 }
  ministerofsecurity     = { type = 9 id = 6005 }
  ministerofintelligence = { type = 9 id = 6128 }
  chiefofstaff           = { type = 9 id = 6136 }
  chiefofarmy            = { type = 9 id = 6144 }
  chiefofnavy            = { type = 9 id = 6163 }
  chiefofair             = { type = 9 id = 6167 }
  dormant_ministers      = { 6006 6176 6009 6162 6158 6010 6107 6007 6008 6004 6041 6114 }
  # Mobile-Panama
  convoy =
  { id             = { type = 10205 id = 110 }
    transports     = 17
    escorts        = 14
    rare_materials = no
    energy         = no
    metal          = no
    oil            = yes
    supplies       = yes
    path           = { 676 2533 2532 2527 2526 2525 2576 889 }
  }
  # San Diego-Pearl Harbour
  convoy =
  { id             = { type = 10205 id = 111 }
    transports     = 17
    escorts        = 0
    rare_materials = no
    energy         = no
    metal          = no
    oil            = yes
    supplies       = yes
    path           = { 761 1938 1940 1942 1943 1931 663 }
  }
  # Seattle-Juneau
  convoy =
  { id             = { type = 10205 id = 112 }
    transports     = 15
    escorts        = 0
    rare_materials = no
    energy         = no
    metal          = no
    oil            = yes
    supplies       = yes
    path           = { 780 1922 1921 1914 1913 553 }
  }
  landunit =
  { id       = { type = 10200 id = 182 }
    name     = "1. USMC Division"
    location = 761
    division =
    { id       = { type = 10200 id = 183 }
      name     = "1. USMC Division"
      strength = 100
      type     = marine
      model    = 1
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 10200 id = 184 }
    name     = "2. USMC Division"
    location = 761
    division =
    { id       = { type = 10200 id = 185 }
      name     = "2. USMC Division"
      strength = 100
      type     = marine
      model    = 1
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 10200 id = 186 }
    name     = "Armoured Force"
    location = 636
    division =
    { id       = { type = 10200 id = 187 }
      name     = "1st Armored Division"
      strength = 100
      type     = armor
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 188 }
      name     = "2nd Armored Division."
      strength = 100
      type     = armor
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 189 }
      name     = "3rd Armored Division"
      strength = 100
      type     = armor
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 190 }
      name     = "4th Armored Division"
      strength = 100
      type     = armor
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 191 }
      name     = "5th Armored Division"
      strength = 100
      type     = armor
      model    = 1
    }
  }
  landunit =
  { id       = { type = 10200 id = 192 }
    name     = "I. Army Corps"
    location = 620
    division =
    { id       = { type = 10200 id = 193 }
      name     = "8. Infantry Division"
      strength = 100
      type     = infantry
      model    = 1
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 194 }
      name     = "9. Infantry Division"
      strength = 100
      type     = infantry
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 195 }
      name     = "30. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10200 id = 196 }
    name     = "II. Army Corps"
    location = 607
    division =
    { id       = { type = 10200 id = 197 }
      name     = "28. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 198 }
      name     = "29. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
    division =
    { id       = { type = 10200 id = 199 }
      name     = "44. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10200 id = 200 }
    name     = "VI. Army Corps"
    location = 600
    division =
    { id       = { type = 10200 id = 201 }
      name     = "1. Infantry Division 'Big Red One'"
      strength = 100
      type     = infantry
      model    = 1
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 202 }
      name     = "26. Natl Guards Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10200 id = 203 }
    name     = "VII. Army Corps"
    location = 642
    division =
    { id       = { type = 10200 id = 204 }
      name     = "2. Cavalry Division"
      strength = 100
      type     = cavalry
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 205 }
      name     = "5. Infantry Division"
      strength = 100
      type     = infantry
      model    = 1
      extra    = anti_air
    }
    division =
    { id       = { type = 10200 id = 206 }
      name     = "6. Infantry Division"
      strength = 100
      type     = infantry
      model    = 1
      extra    = engineer
    }
    division =
    { id       = { type = 10200 id = 207 }
      name     = "27. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 208 }
      name     = "33. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
    division =
    { id       = { type = 10200 id = 209 }
      name     = "35. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10200 id = 210 }
    name     = "IV. Army Corps"
    location = 725
    division =
    { id       = { type = 10200 id = 211 }
      name     = "1. Cavalry Division"
      strength = 100
      type     = cavalry
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 212 }
      name     = "4th Motorized Infantry Division"
      strength = 100
      type     = motorized
      model    = 0
    }
    division =
    { id       = { type = 10200 id = 213 }
      name     = "31. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 214 }
      name     = "43. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10200 id = 215 }
    name     = "V. Army Corps"
    location = 780
    division =
    { id       = { type = 10200 id = 216 }
      name     = "32. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 217 }
      name     = "34. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 218 }
      name     = "37. Natl Guards NG Division"
      strength = 100
      type     = infantry
      model    = 0
    }
    division =
    { id       = { type = 10200 id = 219 }
      name     = "38. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10200 id = 220 }
    name     = "VIII. Army Corps"
    location = 710
    division =
    { id       = { type = 10200 id = 221 }
      name     = "2. Infantry Division"
      strength = 100
      type     = infantry
      model    = 1
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 222 }
      name     = "36. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
    division =
    { id       = { type = 10200 id = 223 }
      name     = "45. Natl Guards Division"
      strength = 100
      type     = infantry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10200 id = 224 }
    name     = "III. Army Corps"
    location = 716
    division =
    { id       = { type = 10200 id = 225 }
      name     = "7. Infantry Division"
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 226 }
      name     = "40. Natl Guards Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10200 id = 227 }
    name     = "IX. Army Corps"
    location = 765
    division =
    { id       = { type = 10200 id = 228 }
      name     = "3. Natl Guards Division"
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 229 }
      name     = "41. Natl Guards Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10200 id = 230 }
    name     = "Panama Canal Zone"
    location = 889
    division =
    { id       = { type = 10200 id = 231 }
      name     = "Panama Mobile Force"
      strength = 100
      type     = infantry
      extra    = engineer
      model    = 2
    }
    division =
    { id            = { type = 10200 id = 235 }
      name          = "Fort Sherman"
      type          = garrison
      locked        = yes
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id            = { type = 10200 id = 236 }
      name          = "Fort Grant"
      type          = garrison
      locked        = yes
      extra         = artillery
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 10200 id = 232 }
    name     = "Hawaiian Department"
    location = 663
    division =
    { id       = { type = 10200 id = 233 }
      name     = "24. Infantry Division"
      strength = 100
      type     = infantry
      model    = 1
      extra    = artillery
    }
    division =
    { id       = { type = 10200 id = 234 }
      name     = "25. Infantry Division"
      strength = 100
      type     = infantry
      model    = 1
    }
  }
  landunit =
  { location = 606
    id       = { type = 10200 id = 1100 }
    name     = "East Coast HQ"
    division =
    { id       = { type = 10200 id = 1101 }
      name     = "East Coast HQ"
      type     = hq
      model    = 1
      strength = 100
      extra    = engineer
    }
  }
  landunit =
  { location = 762
    id       = { type = 10200 id = 1102 }
    name     = "West Coast HQ"
    division =
    { id       = { type = 10200 id = 1103 }
      name     = "West Coast HQ"
      type     = hq
      model    = 1
      strength = 100
      extra    = engineer
    }
  }
  landunit =
  { location = 1737
    id       = { type = 10200 id = 1104 }
    name     = "Phillipine HQ"
    division =
    { id       = { type = 10200 id = 1105 }
      name     = "Phillipine HQ"
      type     = hq
      model    = 1
      strength = 100
    }
  }


  landunit =
  { id       = { type = 10200 id = 312 }
    name     = "Reykjavik Force"
    location = 1
    division =
    { id            = { type = 10200 id = 313 }
      name          = "Reykjavik Garrison"
      type          = garrison
      locked        = yes
    }
  }
  # US Asiatic Fleet
  navalunit =
  { id       = { type = 10200 id = 1 }
    name     = "CA Squadron 1"
    location = 1737
    base     = 1737
    division =
    { id    = { type = 10200 id = 2 }
      name  = "USS Houston"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 4 }
      name  = "USS Marblehead"
      type  = light_cruiser
      model = 1
    }
  }
  navalunit =
  { id       = { type = 10200 id = 5 }
    name     = "DD Squadron 29"
    location = 1737
    base     = 1737
    division =
    { id   = { type = 10200 id = 6 }
      name = "57th Destroyer Division"
      type = destroyer
    }
    division =
    { id   = { type = 10200 id = 7 }
      name = "58th Destroyer Division"
      type = destroyer
    }
    division =
    { id   = { type = 10200 id = 8 }
      name = "59th Destroyer Division"
      type = destroyer
    }
    division =
    { id   = { type = 10200 id = 1300 }
      name = "Edward Rutledge Flotilla"
      type = transport
    }
    division =
    { id   = { type = 10200 id = 1301 }
      name = "Young America Flotilla"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10200 id = 9 }
    name     = "Submarine Squadron 20"
    location = 1737
    base     = 1737
    division =
    { id    = { type = 10200 id = 10 }
      name  = "21st Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 11 }
      name  = "22nd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 12 }
      name  = "23rd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 13 }
      name  = "24th Submarine Division"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10200 id = 14 }
      name  = "25th Submarine Division"
      type  = submarine
      model = 3
    }
  }
  # US PACIFIC FLEET
  navalunit =
  { id       = { type = 10200 id = 15 }
    name     = "BB Squadron 1"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 16 }
      name  = "USS Nevada"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 18 }
      name  = "USS Pennsylvania"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 24 }
      name  = "USS Tennessee"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 26 }
      name  = "USS California"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 30 }
      name  = "USS Maryland"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 10200 id = 1030 }
      name  = "USS Arizona"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 1031 }
      name  = "USS Oklahoma"
      type  = battleship
      model = 1
    }
  }
  navalunit =
  { id       = { type = 10200 id = 27 }
    name     = "BB Squadron 2"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 28 }
      name  = "USS Colorado"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 10200 id = 500 }
      name  = "USS West Virginia"
      type  = battleship
      model = 2
    }
  }
  navalunit =
  { id       = { type = 10200 id = 33 }
    name     = "CV Squadron 1"
    location = 663
    base     = 663
    division =
    { id            = { type = 10200 id = 34 }
      name          = "USS Lexington"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 4
    }
    division =
    { id            = { type = 10200 id = 36 }
      name          = "USS Saratoga"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 4
    }
    division =
    { id            = { type = 10200 id = 38 }
      name          = "USS Enterprise"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 4
    }
  }
  navalunit =
  { id       = { type = 10200 id = 39 }
    name     = "CA Squadron 2"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 501 }
      name  = "USS Raleigh"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 502 }
      name  = "USS Detroit"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 56 }
      name  = "USS Pensacola"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 58 }
      name  = "USS Salt Lake City"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 60 }
      name  = "USS Chicago"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 62 }
      name  = "USS Indianapolis"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 64 }
      name  = "USS Northampton"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 66 }
      name  = "USS Chester"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 68 }
      name  = "USS Louisville"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 70 }
      name  = "USS Portland"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 72 }
      name  = "USS New Orleans"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10200 id = 74 }
      name  = "USS Astoria"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10200 id = 76 }
      name  = "USS Minneapolis"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10200 id = 78 }
      name  = "USS San Francisco"
      type  = heavy_cruiser
      model = 2
    }
  }
  navalunit =
  { id       = { type = 10200 id = 49 }
    name     = "CA Squadron 3"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 50 }
      name  = "USS Honolulu"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10200 id = 54 }
      name  = "USS Helena"
      type  = light_cruiser
      model = 3
    }
  }
  navalunit =
  { id       = { type = 10200 id = 75 }
    name     = "CL Squadron 1"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 40 }
      name  = "USS Richmond"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 42 }
      name  = "USS Concord"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 44 }
      name  = "USS Trenton"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 46 }
      name  = "USS Phoenix"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10200 id = 48 }
      name  = "USS Boise"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10200 id = 52 }
      name  = "USS St Louis"
      type  = light_cruiser
      model = 3
    }
  }
  navalunit =
  { id       = { type = 10200 id = 79 }
    name     = "DD Flotilla 2"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 80 }
      name  = "7th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10200 id = 81 }
      name  = "8th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10200 id = 82 }
      name  = "11th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10200 id = 83 }
      name  = "12th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10200 id = 84 }
      name  = "50th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id   = { type = 10200 id = 302 }
      name = "Abraham Lincoln Flotilla"
      type = transport
    }
    division =
    { id   = { type = 10200 id = 303 }
      name = "Susan B. Anthony Flotilla"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10200 id = 85 }
    name     = "DD Flotilla 1"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 86 }
      name  = "1st Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 87 }
      name  = "2nd Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 88 }
      name  = "5th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10200 id = 89 }
      name  = "6th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 90 }
      name  = "9th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 91 }
      name  = "10th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id   = { type = 10200 id = 304 }
      name = "State Of Maryland Flotilla"
      type = transport
    }
    division =
    { id   = { type = 10200 id = 305 }
      name = "Amherst Victory Flotilla"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10200 id = 92 }
    name     = "Submarine Fleet 2"
    location = 663
    base     = 663
    division =
    { id    = { type = 10200 id = 93 }
      name  = "41th Submarine Division"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10200 id = 94 }
      name  = "42th Submarine Division"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10200 id = 95 }
      name  = "43th Submarine Division"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10200 id = 97 }
      name  = "61st Submarine Division"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10200 id = 98 }
      name  = "62nd Submarine Division"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10200 id = 152 }
      name  = "73nd Submarine Division"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 10200 id = 168 }
      name  = "74nd Submarine Division"
      type  = submarine
      model = 3
    }
  }
  # US Atlantic Fleet
  navalunit =
  { id       = { type = 10200 id = 99 }
    name     = "BB Squadron 3"
    location = 633
    base     = 633
    division =
    { id    = { type = 10200 id = 100 }
      name  = "USS New Mexico"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 102 }
      name  = "USS Mississippi"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 104 }
      name  = "USS Idaho"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 106 }
      name  = "USS Arkansas"
      type  = battleship
      model = 0
    }
    division =
    { id    = { type = 10200 id = 108 }
      name  = "USS New York"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 110 }
      name  = "USS Texas"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10200 id = 112 }
      name  = "USS North Carolina"
      type  = battleship
      model = 3
    }
    division =
    { id    = { type = 10200 id = 114 }
      name  = "USS Washington"
      type  = battleship
      model = 3
    }
  }
  navalunit =
  { id       = { type = 10200 id = 115 }
    name     = "CV Squadron 2"
    location = 633
    base     = 633
    division =
    { id            = { type = 10200 id = 116 }
      name          = "USS Ranger"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 4
    }
    division =
    { id            = { type = 10200 id = 118 }
      name          = "USS Wasp"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 4
    }
    division =
    { id            = { type = 10200 id = 120 }
      name          = "USS Yorktown"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 4
    }
  }
  navalunit =
  { id       = { type = 10200 id = 123 }
    name     = "CA Squadron 4"
    location = 633
    base     = 633
    division =
    { id    = { type = 10200 id = 124 }
      name  = "USS Augusta"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 126 }
      name  = "USS Tuscaloosa"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10200 id = 128 }
      name  = "USS Quincy"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10200 id = 261 }
      name  = "USS Vincennes"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10200 id = 263 }
      name  = "USS Wichita"
      type  = heavy_cruiser
      model = 2
    }
  }
  navalunit =
  { id       = { type = 10200 id = 138 }
    name     = "CL Squadron 2"
    location = 663
    base     = 633
    division =
    { id    = { type = 10200 id = 139 }
      name  = "USS Philadelphia"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10200 id = 129 }
      name  = "USS Omaha"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 131 }
      name  = "USS Milwaukee"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 133 }
      name  = "USS Cincinnati"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 135 }
      name  = "USS Memphis"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10200 id = 137 }
      name  = "USS Brooklyn"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10200 id = 141 }
      name  = "USS Savannah"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10200 id = 143 }
      name  = "USS Nashville"
      type  = light_cruiser
      model = 3
    }
  }
  navalunit =
  { id       = { type = 10200 id = 144 }
    name     = "DD Flotilla 3"
    location = 633
    base     = 633
    division =
    { id    = { type = 10200 id = 145 }
      name  = "13th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10200 id = 146 }
      name  = "14th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 147 }
      name  = "17th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 148 }
      name  = "18th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 149 }
      name  = "21th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 150 }
      name  = "22th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10200 id = 151 }
      name  = "25th Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id   = { type = 10200 id = 306 }
      name = "Josiah Bartlett Flotilla"
      type = transport
    }
    division =
    { id   = { type = 10200 id = 307 }
      name = "Sea Marlin Flotilla"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10200 id = 153 }
    name     = "DD Flotilla 4"
    location = 633
    base     = 633
    division =
    { id    = { type = 10200 id = 154 }
      name  = "3rd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 155 }
      name  = "4th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 156 }
      name  = "15th Destroyer Division"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10200 id = 157 }
      name  = "16th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 158 }
      name  = "19th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 159 }
      name  = "20th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 160 }
      name  = "23th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 161 }
      name  = "24th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 10200 id = 308 }
      name = "Booker T. Washington Flotilla"
      type = transport
    }
    division =
    { id   = { type = 10200 id = 309 }
      name = "Storm King Flotilla"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10200 id = 162 }
    name     = "DD Flotilla 8"
    location = 633
    base     = 633
    division =
    { id    = { type = 10200 id = 163 }
      name  = "53rd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 164 }
      name  = "54th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 165 }
      name  = "60th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 166 }
      name  = "61st Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10200 id = 167 }
      name  = "62nd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 10200 id = 310 }
      name = "Uruguay Flotilla"
      type = transport
    }
    division =
    { id   = { type = 10200 id = 311 }
      name = "A. P. Hill Flotilla"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10200 id = 169 }
    name     = "Submarine Fleet"
    location = 633
    base     = 633
    division =
    { id    = { type = 10200 id = 170 }
      name  = "11th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 171 }
      name  = "12th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 173 }
      name  = "31th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 174 }
      name  = "32th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 176 }
      name  = "51st Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 177 }
      name  = "52nd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 178 }
      name  = "53rd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 180 }
      name  = "71st Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10200 id = 181 }
      name  = "72nd Submarine Division"
      type  = submarine
      model = 1
    }
  }
  airunit =
  { id       = { type = 10200 id = 240 }
    name     = "First Air Force"
    location = 600
    base     = 600
    division =
    { id       = { type = 10200 id = 241 }
      name     = "1st USAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 242 }
      name     = "6th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 3
    }
    division =
    { id       = { type = 10200 id = 243 }
      name     = "20th USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
  }
  airunit =
  { id       = { type = 10200 id = 244 }
    name     = "Second Air Force"
    location = 600
    base     = 600
    division =
    { id       = { type = 10200 id = 245 }
      name     = "2nd USAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 246 }
      name     = "7th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 3
    }
    division =
    { id       = { type = 10200 id = 247 }
      name     = "12th USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
  }
  airunit =
  { id       = { type = 10200 id = 248 }
    name     = "Third Air Force"
    location = 633
    base     = 633
    division =
    { id       = { type = 10200 id = 249 }
      name     = "13th USAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 250 }
      name     = "9th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 3
    }
    division =
    { id       = { type = 10200 id = 251 }
      name     = "47th USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
  }
  airunit =
  { id       = { type = 10200 id = 252 }
    name     = "Fourth Air Force"
    location = 1737
    base     = 1737
    division =
    { id       = { type = 10200 id = 253 }
      name     = "4th USAF Strategic Bomb. Wing"
      strength = 100
      type     = strategic_bomber
      model    = 1
    }
    division =
    { id       = { type = 10200 id = 254 }
      name     = "10th USAF interceptor Wing"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 10200 id = 255 }
      name     = "57th USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
  }
  airunit =
  { id       = { type = 10200 id = 256 }
    name     = "14th USAF Tactical Bomb. Wing"
    location = 602
    base     = 602
    division =
    { id       = { type = 10200 id = 257 }
      name     = "14th USAF Tactical Bomb. Wing"
      strength = 100
      type     = tactical_bomber
      model    = 1
    }
  }
  airunit =
  { id       = { type = 10200 id = 258 }
    name     = "Transport Command"
    location = 620
    base     = 620
    division =
    { id       = { type = 10200 id = 259 }
      name     = "50th USAF Troop Carrier Wing"
      strength = 100
      type     = transport_plane
      model    = 0
    }
  }
  airunit =
  { id       = { type = 10200 id = 260 }
    name     = "Hawaiian Air Department"
    location = 663
    base     = 663
    division =
    { id       = { type = 10200 id = 264 }
      name     = "14th USAF Pursuit Wing"
      strength = 80
      type     = multi_role
      model    = 0
    }
    division =
    { id       = { type = 10200 id = 262 }
      name     = "18th USAF Bombardment Wing"
      strength = 40
      type     = tactical_bomber
      model    = 1
    }
  }
  # ##Builds###
  division_development =
  { name  = "USS South Dakota"
    type  = battleship
    model = 3
    cost  = 8
    id    = { type = 10200 id = 800 }
    date  = { year = 1942 month = march day = 20 }
  }
  division_development =
  { name  = "USS Indiana"
    type  = battleship
    model = 3
    cost  = 8
    id    = { type = 10200 id = 801 }
    date  = { year = 1942 month = april day = 30 }
  }
  division_development =
  { name  = "USS Massachusetts"
    type  = battleship
    model = 3
    cost  = 8
    id    = { type = 10200 id = 802 }
    date  = { year = 1942 month = may day = 12 }
  }
  division_development =
  { name  = "USS Alabama"
    type  = battleship
    model = 3
    cost  = 8
    id    = { type = 10200 id = 803 }
    date  = { year = 1942 month = august day = 16 }
  }
  division_development =
  { name  = "USS Hornet"
    type  = carrier
    model = 2
    cost  = 4.8
    id    = { type = 10200 id = 806 }
    date  = { year = 1941 month = november day = 20 }
    extra = cag
    brigade_model = 4
  }
  division_development =
  { name  = "70th Destroyer Division"
    type  = destroyer
    model = 2
    cost  = 1.6
    id    = { type = 10200 id = 814 }
    date  = { year = 1941 month = august day = 1 }
  }
  division_development =
  { name  = "71st Destroyer Division"
    type  = destroyer
    model = 2
    cost  = 1.6
    id    = { type = 10200 id = 815 }
    date  = { year = 1941 month = september day = 1 }
  }
  division_development =
  { name  = "80th Submarine Division"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10200 id = 818 }
    date  = { year = 1941 month = august day = 1 }
  }
  division_development =
  { name  = "81st Submarine Division"
    type  = submarine
    model = 3
    cost  = 2.4
    id    = { type = 10200 id = 819 }
    date  = { year = 1941 month = september day = 1 }
  }
}
