# ASD 26-Jan-07 - add brigades and floods

province = { id = 1214 province_revoltrisk = 10 } # Yantai
province =
{ id                  = 1215
  province_revoltrisk = 10
  naval_base          = { size = 1 current_size = 1 }
}                       # Qingdao
province = { id = 1217 province_revoltrisk = 10 } # Lianyungang
province = { id = 1218 province_revoltrisk = 10 } # Xuzhou
province = { id = 1220 province_revoltrisk = 10 } # Yangzhou
province = { id = 1221 province_revoltrisk = 10 } # Hefei
province = { id = 1222 province_revoltrisk = 10 } # Fuyang
province = { id = 1223 province_revoltrisk = 10 } # Kaifeng
province = { id = 1224 province_revoltrisk = 10 } # Anyang
province = { id = 1227 province_revoltrisk = 10 } # Luoyang
province = { id = 1228 province_revoltrisk = 10 ic = -2 infra = -0.3 } # Zhengzhou flooded & move industry
province = { id = 1229 province_revoltrisk = 10 infra = -0.3 } # Nanyang flooded
province = { id = 1230 province_revoltrisk = 10 infra = -0.3 } # Xinyang flooded
province = { id = 1231 province_revoltrisk = 10 } # Xiangfan
province = { id = 1232 province_revoltrisk = 10 } # Hankou
province = { id = 1233 province_revoltrisk = 10 } # Anqing
province = { id = 1234 province_revoltrisk = 10 } # Wuhu
province = { id = 1235 province_revoltrisk = 10 } # Nanjing
province = { id = 1236 province_revoltrisk = 10 } # Suzhou
province =
{ id                  = 1237
  province_revoltrisk = 10
  air_base            = { size = 4 current_size = 4 }
  anti_air            = 1
  naval_base          = { size = 2 current_size = 2 }
}                       # Shanghai
province =
{ id                  = 1238
  province_revoltrisk = 10
  air_base            = { size = 2 current_size = 2 }
}                       # Hangzhou
province = { id = 1239 province_revoltrisk = 10 } # Ningbo
province = { id = 1240 province_revoltrisk = 10 } # Wenzhou
province = { id = 1241 province_revoltrisk = 10 } # Quzhou
province = { id = 1242 province_revoltrisk = 10 } # Shangrao
province = { id = 1243 province_revoltrisk = 10 } # Nanping
province =
{ id                  = 1244
  province_revoltrisk = 10
  air_base            = { size = 1 current_size = 1 }
}                       # Fuzhou
province = { id = 1245 province_revoltrisk = 10 } # Quanzhou
province = { id = 1246 province_revoltrisk = 10 } # Longyan
province = { id = 1247 province_revoltrisk = 10 } # Xiamen
province = { id = 1248 province_revoltrisk = 10 } # Shantou
province = { id = 1249 province_revoltrisk = 10 } # Chao'an
province = { id = 1250 province_revoltrisk = 10 } # Ganzhou
province =
{ id                  = 1251
  province_revoltrisk = 10
  air_base            = { size = 1 current_size = 1 }
}                       # Nanchang
province = { id = 1252 province_revoltrisk = 10 } # Jiujiang
province = { id = 1253 province_revoltrisk = 10 } # Wuchang
province = { id = 1254 province_revoltrisk = 10 } # Pingxiang
province = { id = 1255 province_revoltrisk = 10 } # Changsha
province = { id = 1256 province_revoltrisk = 10 } # Zhuzhou
province = { id = 1257 province_revoltrisk = 10 } # Hengyang
province = { id = 1259 province_revoltrisk = 10 } # Shaoyang
province = { id = 1260 province_revoltrisk = 10 } # Changde
province = { id = 1261 province_revoltrisk = 10 ic = 5 } # Huaihua (ic from event 4107)
province =
{ id                  = 1262
  province_revoltrisk = 10
  air_base            = { size = 1 current_size = 1 }
}                       # Zunyi
province = { id = 1263 province_revoltrisk = 10 } # Fuling
province = { id = 1264 province_revoltrisk = 10 } # Enshi
province = { id = 1265 province_revoltrisk = 10 } # Wanxian
province = { id = 1266 province_revoltrisk = 10 } # Yichang
province = { id = 1267 province_revoltrisk = 10 } # Ankang
province = { id = 1268 province_revoltrisk = 10 } # Nancheng
province = { id = 1269 province_revoltrisk = 10 } # Xi'an
province = { id = 1276 province_revoltrisk = 10 IC = 3 infra = 0.2 } # Lanzhou (ic from event 4106)
province = { id = 1277 province_revoltrisk = 10 } # Tianshui
province = { id = 1278 province_revoltrisk = 10 } # Baoji
province = { id = 1279 province_revoltrisk = 10 } # Nanchong
province = { id = 1280 province_revoltrisk = 10 IC = 16 energy = 14 metal = 7 rare_materials = 4 } # Chongqing (ic + resources from event 4104,4105,4107,4108,4109)
province = { id = 1312 province_revoltrisk = 10 } # Shaoguan
province =
{ id                  = 1313
  ic = -6
  province_revoltrisk = 10
  air_base            = { size = 1 current_size = 1 }
  naval_base          = { size = 5 current_size = 5 }
}                       # Guangzhou
province = { id = 1314 province_revoltrisk = 10 } # Bao'an
province = { id = 1317 province_revoltrisk = 10 } # Jiangmen
province = { id = 1318 province_revoltrisk = 10 } # Maoming
province =
{ id                  = 1320
  province_revoltrisk = 10
  naval_base          = { size = 2 current_size = 2 }
}                       # Zhanjiang
province =
{ id                  = 1321
  province_revoltrisk = 10
  air_base            = { size = 1 current_size = 1 }
  naval_base          = { size = 1 current_size = 1 }
}                       # Hainan
province = { id = 1360 province_revoltrisk = 10 } # Chengdu
province = { id = 1361 province_revoltrisk = 10 } # Zigong
province = { id = 1363 province_revoltrisk = 10 } # Anshun
province = { id = 1364 province_revoltrisk = 10 } # Guiyang
province = { id = 1365 province_revoltrisk = 10 } # Kaili

#####################
# Country main data #
#####################

country =
{ tag                    = CHI
  capital                = 1280 # Chongqing
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 1000
  oil                    = 1000
  supplies               = 1000
  money                  = 20
  manpower               = 2170
  dissent                = 10
  diplomacy =
  { relation = { tag = CHC value = 100 }
    relation = { tag = CGX value = 200 }
    relation = { tag = CSX value = 200 }
    relation = { tag = CXB value = 200 }
    relation = { tag = CYN value = 200 }
    relation = { tag = ENG value = 100 }
    relation = { tag = GER value = 1 }
    relation = { tag = JAP value = -200 }
    relation = { tag = MAN value = -200 }
    relation = { tag = MEN value = -200 }
    relation = { tag = SIK value = -125 }
  }
  # Part of Guangdong
  nationalprovinces      = { 1275 1276 1277 1440 1441 1267 1268 1269 1270 1271 1278 1222 1223 1224 1227 1228 1229 1230 1273 1274 1439 1207 1208 1272
			     1209 1225 1226 1203 1204 1205 1206 1210 1211 1212 1213 1214 1215 1216 1386 1398 1388 1397 1202 1377 1387 1389 1390 1394
			     1395 1396 1374 1375 1378 1379 1380 1381 1382 1530 1218 1221 1233 1234 1217 1219 1220 1235 1236 1237 1263 1265 1279 1280
			     1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259 1260 1261 1242 1250 1251
			     1252 1254 1243 1244 1245 1246 1247 1293 1294 1305 1307 1308 1327 1362 1281 1282 1283 1448 1450 1451 1452 1453 1442 1443
			     1444 1421 1430 1431 1432 1433 1435 1445 1446 1447 1258 1309 1310 1311 1319 1325 1248 1249 1312 1313 1314 1317 1318 1320
			     1321 1322 1323 1324 1385 1399 1404 1419 1420 1434 1436 1437 1438
			   }
  ownedprovinces         = { 1276 1277 1267 1268 1269 1278 1222 1223 1224 1227 1228 1229 1230 1214 1215 1218 1219 1221 1233 1234 1217 1220 1235 1236 1237
			     1263 1265 1279 1280 1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259 1260
			     1261 1242 1250 1251 1252 1254 1243 1244 1245 1246 1247 1248 1249 1312 1313 1314 1317 1318 1320 1321
			   }
  # Guangdong
  controlledprovinces    = { 1276 1277 1267 1268 1269 1278 1222 1227 1228 1229 1230 1263 1265 1279 1280 1360 1361 1231 1232 1253 1264 1266 1240 1241
			     1262 1363 1364 1365 1255 1256 1257 1259 1260 1261 1242 1250 1251 1254 1243 1244 1245 1246 1249 1312 1313 1314 1317 1318
			     1320 1321
			   }
  # Great War Infantry
  techapps               = { 1010 1020 1110 1190 1310 2150 2290 3010 3070 3080 3130 4010 5080 5090 6210 6300 9010 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 6 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 5
    political_left    = 3
    free_market       = 9
    freedom           = 4
    professional_army = 1
    defense_lobby     = 8
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 52001 }
  headofgovernment       = { type = 9 id = 52026 }
  foreignminister        = { type = 9 id = 52033 }
  armamentminister       = { type = 9 id = 52046 }
  ministerofsecurity     = { type = 9 id = 52063 }
  ministerofintelligence = { type = 9 id = 52078 }
  chiefofstaff           = { type = 9 id = 52088 }
  chiefofarmy            = { type = 9 id = 52096 }
  chiefofnavy            = { type = 9 id = 52101 }
  chiefofair             = { type = 9 id = 52108 }
  landunit =
  { location = 1227 # Luoyang
    name     = "2. Juntuan"
    id       = { type = 22000 id = 1 }
    division =
    { id         = { type = 22000 id = 2 }
      name       = "30. Jun"
      type       = militia
      experience = 10
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id         = { type = 22000 id = 3 }
      name       = "42. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 4 }
      name = "40. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 5 }
      name = "68. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1229 # Nanyang (Luoyang)
    name     = "3. Juntuan"
    id       = { type = 22000 id = 6 }
    division =
    { id   = { type = 22000 id = 7 }
      name = "12. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1269 # Xi'an (Luoyang)
    name     = "Bei Henan Tifang Juntuan"
    id       = { type = 22000 id = 8 }
    division =
    { id   = { type = 22000 id = 9 }
      name = "76. Jun"
      type = militia
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id         = { type = 22000 id = 10 }
      name       = "Xin 5. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 11 }
      name = "97. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1228 # Zhengzhou (Luoyang)
    name     = "14. Juntuan"
    id       = { type = 22000 id = 12 }
    division =
    { id         = { type = 22000 id = 13 }
      name       = "14. Jun"
      type       = militia
      experience = 10
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 14 }
      name = "93. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 15 }
      name = "98. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1269 # Xianyang (Xi'an)
    name     = "4. Juntuan"
    id       = { type = 22000 id = 16 }
    division =
    { id   = { type = 22000 id = 17 }
      name = "38. Jun"
      type = militia
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 18 }
      name = "47. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 19 }
      name = "96. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1246 # Longyan
    name     = "5. Juntuan"
    id       = { type = 22000 id = 20 }
    division =
    { id   = { type = 22000 id = 21 }
      name = "3. Jun"
      type = militia
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 22 }
      name = "15. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 23 }
      name = "17. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1273 # Yinchuan
    name     = "Shanxi-Shaanxi-Suiyuan Bianqu"
    id       = { type = 22000 id = 24 }
    division =
    { id   = { type = 22000 id = 25 }
      name = "Xin 1. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 26 }
      name = "22. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1241 # Quzhou (Wenzhou)
    name     = "10. Juntuan"
    id       = { type = 22000 id = 27 }
    division =
    { id         = { type = 22000 id = 28 }
      name       = "28. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 29 }
      name = "91. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1249 # Chao'an (Fuzhou)
    name     = "23. Juntuan"
    id       = { type = 22000 id = 30 }
    division =
    { id         = { type = 22000 id = 31 }
      name       = "21. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 32 }
      name = "50. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1244 # Fuzhou
    name     = "25. Juntuan"
    id       = { type = 22000 id = 33 }
    division =
    { id   = { type = 22000 id = 34 }
      name = "100. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 35 }
      name = "Xin 28. Bubing Shi"
      type = militia
    }
  }
  landunit =
  { location = 1242 # Shangrao (Wenzhou)
    name     = "32. Juntuan"
    id       = { type = 22000 id = 36 }
    division =
    { id   = { type = 22000 id = 37 }
      name = "25. Jun"
      type = militia
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 38 }
      name = "29. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 39 }
      name = "67. Bubing Shi"
      type = militia
    }
  }
  landunit =
  { location = 1317 # Jiangmen
    name     = "9. Juntuan"
    id       = { type = 22000 id = 40 }
    division =
    { id         = { type = 22000 id = 41 }
      name       = "4. Jun"
      type       = militia
      experience = 10
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 42 }
      name = "49. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 43 }
      name = "65. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1312 # Shaoguan
    name     = "12. Juntuan"
    id       = { type = 22000 id = 44 }
    division =
    { id   = { type = 22000 id = 45 }
      name = "66. Jun"
      type = militia
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 46 }
      name = "62. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 47 }
      name = "63. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1229 # Nanyang (Xiangfan)
    name     = "11. Juntuan"
    id       = { type = 22000 id = 48 }
    division =
    { id         = { type = 22000 id = 49 }
      name       = "84. Jun"
      type       = militia
      experience = 10
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 50 }
      name = "39. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 51 }
      name = "92. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1260 # Changde (Xiangfan)
    name     = "33. Juntuan"
    id       = { type = 22000 id = 52 }
    division =
    { id         = { type = 22000 id = 53 }
      name       = "26. Jun"
      type       = militia
      experience = 10
      extra         = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 54 }
      name = "59. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 55 }
      name = "55. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 56 }
      name = "77. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1250 # Ganzhou (Xiangfan)
    name     = "22. Juntuan"
    id       = { type = 22000 id = 57 }
    division =
    { id         = { type = 22000 id = 58 }
      name       = "41. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 59 }
      name = "45. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1231 # Xiangfan
    name     = "29. Juntuan"
    id       = { type = 22000 id = 60 }
    division =
    { id         = { type = 22000 id = 61 }
      name       = "44. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 62 }
      name = "67. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1276 # Lanzhou
    name     = "8. Zhanqu Budui"
    id       = { type = 22000 id = 63 }
    division =
    { id   = { type = 22000 id = 64 }
      name = "80. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1254 # Pingxiang (Changsha)
    name     = "19. Juntuan"
    id       = { type = 22000 id = 65 }
    division =
    { id   = { type = 22000 id = 66 }
      name = "6. Jun"
      type = militia
      experience = 10
      extra = artillery
      brigade_model = 0
    }
    division =
    { id         = { type = 22000 id = 67 }
      name       = "74. Jun"
      type       = militia
    }
    division =
    { id   = { type = 22000 id = 68 }
      name = "79. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1318 # Maoming (Hengyang)
    name     = "27. Juntuan"
    id       = { type = 22000 id = 69 }
    division =
    { id   = { type = 22000 id = 70 }
      name = "20. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 71 }
      name = "70. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1257 # Hengyang
    name     = "Hunan-Hubei-Jiangxi Bianqu"
    id       = { type = 22000 id = 72 }
    division =
    { id   = { type = 22000 id = 73 }
      name = "8. Jun"
      type = militia
    }
    division =
    { id         = { type = 22000 id = 74 }
      name       = "73. Jun"
      type       = militia
      experience = 10
    }
  }
  landunit =
  { location = 1257 # Hengyang
    name     = "31. Juntuan"
    id       = { type = 22000 id = 75 }
    division =
    { id         = { type = 22000 id = 76 }
      name       = "18. Jun"
      type       = militia
      experience = 10
      extra = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 77 }
      name = "78. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 78 }
      name = "37. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 79 }
      name = "52. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1255 # Changsha
    name     = "20. Juntuan"
    id       = { type = 22000 id = 80 }
    division =
    { id         = { type = 22000 id = 81 }
      name       = "2. Jun"
      type       = militia
      experience = 10
      extra = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 82 }
      name = "54. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 83 }
      name = "53. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 84 }
      name = "97. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1231 # Xi'an
    name     = "34. Juntuan"
    id       = { type = 22000 id = 85 }
    division =
    { id         = { type = 22000 id = 86 }
      name       = "16. Jun"
      type       = militia
      experience = 10
      extra = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 87 }
      name = "27. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 88 }
      name = "90. Jun"
      type = militia
    }
    division =
    { id         = { type = 22000 id = 89 }
      name       = "Juntuan Qibing"
      type       = cavalry
      model      = 0
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 90 }
      name = "Shaanxi Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1227 # Luoyang
    name     = "Jiangsu-Shandong Zhanqu"
    id       = { type = 22000 id = 91 }
    division =
    { id   = { type = 22000 id = 92 }
      name = "51. Jun"
      type = militia
      extra = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 93 }
      name = "57. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 94 }
      name = "89. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 95 }
      name = "Shandong Youjidui"
      type = militia
    }
  }
  landunit =
  { location = 1266 # Yichang (Luoyang)
    name     = "Hebei-Chahar Zhanqu"
    id       = { type = 22000 id = 96 }
    division =
    { id         = { type = 22000 id = 97 }
      name       = "26. Jun"
      type       = militia
      experience = 10
      extra = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 98 }
      name = "59. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 99 }
      name = "55. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 100 }
      name = "77. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1280 # Chongqing
    name     = "Zhong Daiji Budui"
    id       = { type = 22000 id = 101 }
    division =
    { id         = { type = 22000 id = 102 }
      name       = "1. Jun"
      type       = militia
      experience = 10
      extra = artillery
      brigade_model = 1
    }
    division =
    { id   = { type = 22000 id = 103 }
      name = "31. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 104 }
      name = "36. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 105 }
      name = "71. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 106 }
      name = "99. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 107 }
      name = "5. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 108 }
      name = "Haiguan Jingcha Jun"
      type = militia
    }
  }
  landunit =
  { location = 1262 # Zunyi
    name     = "Shang Chang Jiang Jingbei"
    id       = { type = 22000 id = 109 }
    division =
    { id   = { type = 22000 id = 110 }
      name = "13. Jun"
      type = infantry
      extra = artillery
      brigade_model = 0
    }
    division =
    { id         = { type = 22000 id = 111 }
      name       = "75. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id         = { type = 22000 id = 112 }
      name       = "85. Jun"
      type       = militia
      experience = 10
    }
    division =
    { id   = { type = 22000 id = 113 }
      name = "91. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1277 # Wudu (Tianshui)
    name     = "Sichuan-Shaanxi-Hubei Bianqu"
    id       = { type = 22000 id = 114 }
    division =
    { id   = { type = 22000 id = 115 }
      name = "56. Jun"
      type = militia
      extra = artillery
      brigade_model = 0
    }
    division =
    { id   = { type = 22000 id = 116 }
      name = "95. Jun"
      type = militia
    }
    division =
    { id   = { type = 22000 id = 117 }
      name = "Xin 6. Jun"
      type = militia
    }
  }
  landunit =
  { location = 1240 # Wenzhou
    name     = "Zhejiang Jingbei"
    id       = { type = 22000 id = 118 }
    division =
    { id   = { type = 22000 id = 119 }
      name = "Zhejiang Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1244 # Fuzhou
    name     = "Fujian Jingbei"
    id       = { type = 22000 id = 120 }
    division =
    { id   = { type = 22000 id = 121 }
      name = "Fujian Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1320 # Zhanjiang
    name     = "Guangdong Jingbei"
    id       = { type = 22000 id = 122 }
    division =
    { id   = { type = 22000 id = 123 }
      name = "Guangdong Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1364 # Guiyang
    name     = "Guizhou Jingbei"
    id       = { type = 22000 id = 124 }
    division =
    { id   = { type = 22000 id = 125 }
      name = "Guizhou Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1360 # Chengdu
    name     = "Sichuan Jingbei"
    id       = { type = 22000 id = 126 }
    division =
    { id   = { type = 22000 id = 127 }
      name = "Sichuan Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1231 # Xiangfan
    name     = "Hubei Jingbei"
    id       = { type = 22000 id = 128 }
    division =
    { id   = { type = 22000 id = 129 }
      name = "Hubei Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1255 # Changsha
    name     = "Hunan Jingbei"
    id       = { type = 22000 id = 130 }
    division =
    { id   = { type = 22000 id = 131 }
      name = "Hunan Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1312 # Shaoguan
    name     = "Jiangxi Jingbei"
    id       = { type = 22000 id = 132 }
    division =
    { id   = { type = 22000 id = 133 }
      name = "Jiangxi Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1227 # Luoyang
    name     = "Henan Jingbei"
    id       = { type = 22000 id = 134 }
    division =
    { id   = { type = 22000 id = 135 }
      name = "Henan Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1276 # Lanzhou
    name     = "Gansu Jingbei"
    id       = { type = 22000 id = 136 }
    division =
    { id   = { type = 22000 id = 137 }
      name = "Gansu Baoantui"
      type = militia
    }
  }
  landunit =
  { location = 1280 # Chongqing
    name     = "Chongqing Jingbei"
    id       = { type = 22000 id = 138 }
    division =
    { id         = { type = 22000 id = 139 }
      name       = "Chongqing Jingcha Jun"
      type       = militia
      experience = 10
    }
  }
  landunit =
  { location = 1240 # Wenzhou
    name     = "Zhongcheng Zhengjiu Jun"
    id       = { type = 22000 id = 140 }
    division =
    { id   = { type = 22000 id = 141 }
      name = "Zhongcheng Zhengjiu Jun"
      type = bergsjaeger
    }
  }
  airunit =
  { location = 1262 # Zunyi
    id       = { type = 22000 id = 142 }
    name     = "Russian Volunteer Group"
    base     = 1262 # Zunyi
    division =
    { id    = { type = 22000 id = 143 }
      name  = "Qianjiji Hang Kong Dui"
      type  = interceptor
      model = 1
    }
    division =
    { id    = { type = 22000 id = 144 }
      name  = "Hongzhaji Hang Kong Dui"
      type  = tactical_bomber
      model = 1
    }
  }
  division_development =
  { name = "Xin 11. Jun"
    id   = { type = 22000 id = 145 }
    type = infantry
    cost = 3
    date = { day = 25 year = 1939 month = december }
  }
}
