
##############################
# Country definition for JAP #
##############################

province = { id = 1174 oilpool = 100 supplypool = 500 } # Shumushushima
province = { id = 1176 oilpool = 100 supplypool = 500 } # Toyohara
province = { id = 1179 anti_air = 1 } # Sapporo
province = { id = 1180 ic = 3 } # Sendai
province =
{ id         = 1181
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
  anti_air   = 1
}              # Akita
province = { id = 1182 anti_air = 1 } # Fukushima
province = { id = 1183 anti_air = 1 } # Niigata
province =
{ id         = 1184
  ic         = 8
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 2
}              # Tokyo
province =
{ id         = 1185
  ic         = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 1
}              # Nagoya
province =
{ id         = 1186
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 1
}              # Kanazawa
province =
{ id         = 1187
  ic         = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 1
}              # Osaka
province =
{ id         = 1188
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 1
}              # Hiroshima
province =
{ id         = 1189
  ic         = 4
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  anti_air   = 1
}              # Shikoku
province =
{ id         = 1190
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 1
}              # Fukuoka
province = { id = 1192 oilpool = 100 supplypool = 500 } # Amami
province =
{ id         = 1193
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  anti_air   = 1
  oilpool    = 100
  supplypool = 500
}              # Okinawa
province =
{ id         = 1196
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 1
}              # Busan
province =
{ id                  = 1202
  province_revoltrisk = 10
  air_base            = { size = 4 current_size = 4 }
  naval_base          = { size = 6 current_size = 6 }
  anti_air            = 1
}                       # Dalian
province = { id = 1203 province_revoltrisk = 10 } # Tangshan
province = { id = 1216 ic = -2 } # Jinan (-Ic from move industry event 4106)
province = { id = 1219 province_revoltrisk = 10 } # Nantong
province = { id = 1225 ic = -3 } # Taiyuan (-Ic from move industry event 4106)
province = { id = 1235 ic = -8 } # Nanjing (-Ic from move industry event 4107)
province = { id = 1238 ic = -3 } # Hangzhou(-Ic from move industry event 4107)
province =
{ id                  = 1322
  province_revoltrisk = 10
  air_base            = { size = 4 current_size = 4 }
  naval_base          = { size = 6 current_size = 6 }
  anti_air            = 1
  oilpool             = 100
  supplypool          = 500
}                       # Kaohsiung
province = { id = 1323 province_revoltrisk = 10 oilpool = 100 supplypool = 500 } # Taipei
province = { id = 1324 province_revoltrisk = 10 oilpool = 100 supplypool = 500 } # Hualien
province =
{ id       = 1391
  air_base = { size = 4 current_size = 4 }
  anti_air = 1
}            # Hyesan
province = { id = 1600 oilpool = 100 supplypool = 500 } # Bikini
province =
{ id         = 1601
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  anti_air   = 1
  oilpool    = 100
  supplypool = 500
}              # Eniwetok
province = { id = 1602 oilpool = 100 supplypool = 300 } # Wotje
province = { id = 1603 oilpool = 100 supplypool = 300 } # Maloelap
province = { id = 1604 oilpool = 100 supplypool = 500 } # Wolelai
province = { id = 1605 anti_air = 1 oilpool = 100 supplypool = 300 } # Majuro
province = { id = 1606 oilpool = 100 supplypool = 300 } # Mili
province = { id = 1607 oilpool = 100 supplypool = 300 } # Jaluit
province =
{ id         = 1608
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  anti_air   = 1
  oilpool    = 100
  supplypool = 500
}              # Kwajalein
province = { id = 1609 oilpool = 100 supplypool = 500 } # Kosrae
province = { id = 1610 oilpool = 100 supplypool = 500 } # Ponape
province = { id = 1612 oilpool = 100 supplypool = 500 } # Satawan
province =
{ id         = 1613
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 2
  oilpool    = 100
  supplypool = 500
}              # Truk
province = { id = 1615 oilpool = 100 supplypool = 500 } # Ulul
province = { id = 1616 oilpool = 100 supplypool = 500 } # Pulusuk
province = { id = 1617 oilpool = 100 supplypool = 500 } # Woleai
province = { id = 1618 oilpool = 100 supplypool = 500 } # Ulithi
province = { id = 1619 anti_air = 1 oilpool = 100 supplypool = 500 } # Yap
province = { id = 1620 oilpool = 100 supplypool = 500 } # Ngulu
province = { id = 1621 oilpool = 100 supplypool = 500 } # Palau
province = { id = 1625 oilpool = 100 supplypool = 500 } # Rota
province = { id = 1626 oilpool = 100 supplypool = 500 } # Tinian
province = { id = 1627 anti_air = 1 oilpool = 100 supplypool = 500 } # Saipan
province = { id = 1784 anti_air = 1 } # Bonin Islands
province = { id = 1785 oilpool = 100 supplypool = 500 } # Marcus Island

#####################
# Country main data #
#####################

country =
{ tag                    = JAP
  capital                = 1184
  belligerence           = 15
  manpower               = 735
  energy                 = 2000
  metal                  = 2000
  rare_materials         = 1000
  oil                    = 1500
  supplies               = 2000
  money                  = 100
  transports             = 600 # had 6 million tons = one third of UK, Increased to 600 in Armageddon 1.3
  escorts                = 11
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 2
    freedom           = 2
    free_market       = 3
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  SpyInfo                = { country = "JAP" NumberOfSpies = 11 }
  #SpyInfo                = { country = "ENG" NumberOfSpies = 6 }
  #SpyInfo                = { country = "FRA" NumberOfSpies = 6 }
  #SpyInfo                = { country = "SOV" NumberOfSpies = 5 }
  #SpyInfo                = { country = "USA" NumberOfSpies = 8 }
  #SpyInfo                = { country = "SIK" NumberOfSpies = 3 }
  #SpyInfo                = { country = "TAN" NumberOfSpies = 3 }
  #SpyInfo                = { country = "GER" NumberOfSpies = 6 }
  #SpyInfo                = { country = "CXB" NumberOfSpies = 6 }
  #SpyInfo                = { country = "CYN" NumberOfSpies = 6 }
  #SpyInfo                = { country = "LUX" NumberOfSpies = 3 }
  #SpyInfo                = { country = "POR" NumberOfSpies = 3 }
  #SpyInfo                = { country = "ITA" NumberOfSpies = 6 }
  #SpyInfo                = { country = "CHI" NumberOfSpies = 9 }
  #SpyInfo                = { country = "CGX" NumberOfSpies = 3 }
  #SpyInfo                = { country = "PHI" NumberOfSpies = 6 }
  #SpyInfo                = { country = "NZL" NumberOfSpies = 3 }
  #SpyInfo                = { country = "AST" NumberOfSpies = 6 }
  # Part of Guangdong
  nationalprovinces      = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1174 1176 1175 1194
			     1195 1196 1197 1198 1199 1393 1391 1376 1392 1200 1201 1624
			   }
  ownedprovinces         = { 1203 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1627 1626
			     1625 1619 1621 1604 1620 1618 1617 1616 1615 1613 1612 1610 1609 1600 1601 1602 1603 1605 1606 1607 1608 1323 1322 1324
			     1376 1391 1392 1200 1201 1199 1198 1197 1196 1195 1194 1393 1202 1176 1174
			   }
  controlledprovinces    = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1219 1627 1626 1625
			     1619 1621 1604 1620 1618 1617 1616 1615 1613 1612 1610 1609 1600 1601 1602 1603 1605 1606 1607 1608 1323 1322 1324 1376
			     1391 1392 1200 1201 1199 1198 1197 1196 1195 1194 1393 1202 1176 1174 1203 1204 1205 1210 1211 1212 1225 1226 1213 1214
			     1215 1216 1217 1220 1235 1236 1237 1221 1218 1223 1234 1233 1224 1238 1239 1252 1247 1248
			   }
  # Great War Infantry
  techapps               = { 1010  1020  1110  1150  1160  1190  1200  1210  1310  1340  2010  2020  2030  2040  2150  2290  2300  2310  2320  2330
			     2450  2460  2510  3010  3020  3030  3070  3080  3090  3100  3130  3140  3150  3190  3200  3210  3250  3260  3270  3280
			     3310  3320  3330  3340  3350  3400  3410  3420  3430  4010  4020  4050  4120  4130  4190  4250  5010  5050  5080  5090
			     5190  5200  5310  5320  5350  5470  6010  6030  6110  6120  6160  8010  8020  8030  8040  8060  8090  8100  8110  8180
			     9010  9020  9030  9040  9050  9060  9090  9100  9110  9190  9200  14000 12100 12110
			   }
  diplomacy =
  { relation = { tag = AST value = -25 }
    relation = { tag = BEL value = -25 }
    relation = { tag = BHU value = -50 }
    relation = { tag = CGX value = -200 }
    relation = { tag = CHC value = -200 }
    relation = { tag = CHI value = -200 }
    relation = { tag = CHL value = 20 }
    relation = { tag = CSX value = -200 }
    relation = { tag = CXB value = -200 }
    relation = { tag = CYN value = -200 }
    relation = { tag = ENG value = -50 }
    relation = { tag = FIN value = 20 }
    relation = { tag = FRA value = -40 }
    relation = { tag = GER value = 75 }
    relation = { tag = HOL value = -50 }
    relation = { tag = MAN value = 200 access = yes }
    relation = { tag = MEN value = 200 access = yes }
    relation = { tag = NEP value = -50 }
    relation = { tag = NZL value = -100 }
    relation = { tag = SAF value = -50 }
    relation = { tag = SIA value = 75 }
    relation = { tag = SIK value = -170 }
    relation = { tag = USA value = 15 }
  }
  headofstate            = { type = 9 id = 5001 }
  headofgovernment       = { type = 9 id = 5035 }
  foreignminister        = { type = 9 id = 5056 }
  armamentminister       = { type = 9 id = 5082 }
  ministerofsecurity     = { type = 9 id = 5108 }
  ministerofintelligence = { type = 9 id = 5137 }
  chiefofstaff           = { type = 9 id = 5007 }
  chiefofarmy            = { type = 9 id = 5008 }
  chiefofnavy            = { type = 9 id = 5200 }
  chiefofair             = { type = 9 id = 5185 }
  dormant_ministers      = { 5002 5040 5033 5034 5041 5003 5057 5063 5053 5055 5004 5005 5105 5106 5107 5115 5006 5134 5189 }
  landunit =
  { id       = { type = 30036 id = 1 }
    name     = "Shina Hakengun" # "China Exp Army"
    location = 1224
    division =
    { experience = 20
      id         = { type = 30036 id = 2 }
      name       = "Shina Hakengun Shireibu"
      type       = hq
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 3 }
      name       = "Dai 3 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
  }
  landunit =
  { id       = { type = 30036 id = 4 }
    name     = "Dai 23 Gun" # 23 army
    location = 1226
    division =
    { experience = 20
      id         = { type = 30036 id = 5 }
      name       = "Dai 13 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 6 }
      name       = "Dai 34 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
  }
  landunit =
  { id       = { type = 30036 id = 7 }
    name     = "Dai 39 Hoheishidan"
    location = 1225
    division =
    { experience = 20
      id         = { type = 30036 id = 8 }
      name       = "Dai 39 Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 9 }
    name     = "Dai 13 Gun"
    location = 1239 # Shanghai, China
    division =
    { experience = 20
      id         = { type = 30036 id = 10 }
      name       = "Dai 15 Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 11 }
      name       = "Dai 17 Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 12 }
    name     = "Dai 7 Hômengun"
    location = 1238
    division =
    { experience = 20
      id         = { type = 30036 id = 13 }
      name       = "Dai 22 Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 14 }
      name       = "Dai 17 Dokuritsu konsei ryodan" # "Dokuritsu konsei ryodan"
      strength   = 50
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 15 }
    name     = "Dai 6 Gun"
    location = 1234 # Shanghai
    division =
    { experience = 20
      id         = { type = 30036 id = 16 }
      name       = "Dai 20 Dokuritsu konsei ryodan"
      strength   = 50
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 17 }
      name       = "Dai 2 Dokuritsu konsei ryodan"
      strength   = 50
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 18 }
    name     = "Dai 23 Gun"
    location = 1252 # Jiujiang
    division =
    { experience = 20
      id         = { type = 30036 id = 19 }
      name       = "Dai 38 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 20 }
      name       = "Dai 51 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
  }
  landunit =
  { id       = { type = 30036 id = 21 }
    name     = "Dai 23 Gun"
    location = 1233 # Anqing
    division =
    { experience = 20
      id         = { type = 30036 id = 22 }
      name       = "Dai 104 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 23 }
      name       = "Dai 19 Dokuritsu konsei ryodan"
      type       = infantry
      model      = 1
      extra      = armored_car
    }
  }
  landunit =
  { id       = { type = 30036 id = 24 }
    name     = "Dai 2 Hômengun"
    location = 1208 # Hohhot
    division =
    { experience = 20
      id         = { type = 30036 id = 25 }
      name       = "Dai 27 Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 26 }
      name       = "Dai 35 Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 27 }
    name     = "Dai 1 Hômengun"
    location = 1235 # Nanjing
    division =
    { experience = 20
      id         = { type = 30036 id = 28 }
      name       = "Dai 36 Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 29 }
      name       = "Dai 37 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 30 }
      name       = "Dai 3 Dokuritsu konsei ryodan"
      strength   = 50
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 31 }
      name       = "Dai 16 Dokuritsu konsei ryodan"
      strength   = 50
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 32 }
    name     = "Dai 12 Gun"
    location = 1221 # Hefei
    division =
    { experience = 20
      id         = { type = 30036 id = 33 }
      name       = "Dai 32 Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 34 }
    name     = "Moukogo Gun"
    location = 1209 # Datong
    division =
    { experience = 20
      id         = { type = 30036 id = 35 }
      name       = "Dai 26 Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { id       = { type = 30036 id = 36 }
      name     = "Dai 2 Dokuritsu konsei ryodan"
      strength = 50
      type     = infantry
      model    = 1
    }
    division =
    { id    = { type = 30036 id = 37 }
      name  = "Dai 1 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 38 }
      name  = "Dai 2 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 39 }
      name  = "Dai 3 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 40 }
      name  = "Dai 4 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 41 }
      name  = "Dai 5 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
  }
  landunit =
  { id       = { type = 30036 id = 42 }
    name     = "Dai 10 Hoheishidan"
    location = 1223
    division =
    { id    = { type = 30036 id = 43 }
      name  = "Dai 10 Hoheishidan"
      type  = infantry
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 44 }
    name     = "Dai 29 Hoheishidan"
    location = 1218
    division =
    { experience = 20
      id         = { type = 30036 id = 45 }
      name       = "Dai 29 Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 46 }
    name     = "Dai 3 Hômengun"
    location = 1530 # Heihe
    division =
    { id    = { type = 30036 id = 47 }
      name  = "Dai 9 Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 48 }
      name  = "Dai 57 Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 49 }
      name  = "Dai 1 Boeitai"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 50 }
    name     = "Dai 4 Gun"
    location = 1381 # Mohe
    division =
    { id    = { type = 30036 id = 51 }
      name  = "Dai 1 Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 52 }
      name  = "Dai 2 Shubitai" # Homeguards
      type  = garrison
      model = 1
    }
    division =
    { id    = { type = 30036 id = 53 }
      name  = "Dai 3 Shubitai"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 54 }
    name     = "Dai 5 Gun"
    location = 1374 # Jiamusi
    division =
    { id    = { type = 30036 id = 55 }
      name  = "Dai 11 Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 56 }
      name  = "Dai 24 Hoheishidan"
      type  = infantry
      model = 1
    }
    division =
    { id    = { type = 30036 id = 57 }
      name  = "Dai 5 Shubitai"
      type  = garrison
      model = 1
    }
    division =
    { id       = { type = 30036 id = 58 }
      name     = "Dai 3 Manchuko Kiheishidan"
      strength = 50
      type     = cavalry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 30036 id = 59 }
    name     = "Dai 6 Gun"
    location = 1382 # Hailar, Manchuko
    division =
    { id    = { type = 30036 id = 60 }
      name  = "Dai 14 Hoheishidan"
      type  = infantry
      model = 1
      extra = armored_car
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 61 }
      name       = "Dai 23 Hoheishidan"
      type       = infantry
      model      = 1
      extra = armored_car
    }
  }
  landunit =
  { id       = { type = 30036 id = 62 }
    name     = "Dai 20 Gun"
    location = 1375 # Mudanjiang
    division =
    { id    = { type = 30036 id = 63 }
      name  = "Dai 8 Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 64 }
      name  = "Dai 25 Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 65 }
      name  = "Dai 6 Boeitai"
      type  = garrison
      model = 1
      extra      = police
    }
  }
  landunit =
  { id       = { type = 30036 id = 66 }
    name     = "Dai 14 Gun"
    location = 1248
    division =
    { experience = 20
      id         = { type = 30036 id = 67 }
      name       = "Dai 16 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 68 }
      name       = "Dai 48 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
  }
  landunit =
  { id       = { type = 30036 id = 69 }
    name     = "Dai 15 Gun"
    location = 1322
    division =
    { experience = 20
      id         = { type = 30036 id = 70 }
      name       = "Dai 33 Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 71 }
      name       = "Dai 55 Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 72 }
    name     = "Dai 15 Gun"
    location = 1235
    division =
    { experience = 20
      id         = { type = 30036 id = 73 }
      name       = "Dai 2 Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
  }
  landunit =
  { id       = { type = 30036 id = 74 }
    name     = "Daihon'ei" # Imperial General HQ
    location = 1184 # Tokyo
    division =
    { id    = { type = 30036 id = 75 }
      name  = "Daihon'ei"
      type  = hq
      model = 1
    }
    division =
    { experience = 40
      id         = { type = 30036 id = 76 }
      name       = "Konoe Shidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { id    = { type = 30036 id = 77 }
      name  = "Dai 4 Hoheishidan"
      type  = infantry
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 78 }
    name     = "Kita Hômengun" #North Japan Army"
    location = 1181
    division =
    { id    = { type = 30036 id = 79 }
      name  = "Dai 1 Shubitai"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 80 }
    name     = "Chûô Hômengun" # Central Japan Army"
    location = 1185
    division =
    { id    = { type = 30036 id = 81 }
      name  = "Dai 5 Shubitai"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 82 }
    name     = "Roppou Hômengun" # "West Japan Army"
    location = 1187
    division =
    { id    = { type = 30036 id = 83 }
      name  = "Dai 5 Hoheishidan"
      type  = infantry
      model = 0
    }
  }
  landunit =
  { id       = { type = 30036 id = 84 }
    name     = "Tôbu Hômengun" # East Japan Army
    location = 1190
    division =
    { id    = { type = 30036 id = 85 }
      name  = "Dai 16 Shubitai"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 86 }
    name     = "Chôsengun" # "Korean Army"
    location = 1376
    division =
    { id    = { type = 30036 id = 87 }
      name  = "Dai 19 Hoheishidan"
      type  = infantry
      model = 1
    }
    division =
    { id    = { type = 30036 id = 88 }
      name  = "Dai 20 Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 89 }
      name  = "Dai 1 Chôsen Shubitai"
      type  = garrison
      model = 1
    }
    division =
    { id    = { type = 30036 id = 90 }
      name  = "Dai 2 Chôsen Shubitai"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 91 }
    name     = "Takasago Gun" # "Taiwan Army"
    location = 1322
    division =
    { id    = { type = 30036 id = 92 }
      name  = "Dai 1 Takasago Shubitai"
      type  = garrison
      model = 1
    }
    division =
    { id    = { type = 30036 id = 93 }
      name  = "Dai 2 Takasago Shubitai"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 94 }
    name     = "Tokumu butai" # "Special Taskforce"
    location = 1322
    division =
    { experience = 40
      id         = { type = 30036 id = 95 }
      name       = "Dai 14. Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 96 }
    name     = "Shumushushima Chuton Gun"
    location = 1174
    division =
    { id   = { type = 30036 id = 97 }
      name = "Shumushushima Shubitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 98 }
    name     = "Shana Chuton Gun"
    location = 1177
    division =
    { id   = { type = 30036 id = 99 }
      name = "Shana Shubitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 100 }
    name     = "Hokkaido Chuton Gun"
    location = 1179
    division =
    { id   = { type = 30036 id = 101 }
      name = "Hokkaido Shubitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 102 }
    name     = "Toyohara Chuton Gun"
    location = 1176
    division =
    { id   = { type = 30036 id = 103 }
      name = "Toyohara Shubitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 104 }
    name     = "Naha Chuton Gun"
    location = 1193
    division =
    { id   = { type = 30036 id = 105 }
      name = "Naha Shubitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 106 }
    name     = "Saishu Chuton Gun"
    location = 1194
    division =
    { id   = { type = 30036 id = 107 }
      name = "Saishu Shubitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 108 }
    name     = "Bonin konkyochi tai"
    location = 1599
    division =
    { id   = { type = 30036 id = 109 }
      name = "Bonin keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 110 }
    name     = "Bikini konkyochi tai"
    location = 1600
    division =
    { id   = { type = 30036 id = 111 }
      name = "Bikini keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 112 }
    name     = "Eniwetok konkyochi tai"
    location = 1601
    division =
    { id   = { type = 30036 id = 113 }
      name = "Eniwetok keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 114 }
    name     = "Marshall konkyochi tai"
    location = 1605
    division =
    { id   = { type = 30036 id = 115 }
      name = "Marshall keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 116 }
    name     = "Kwajalein konkyochi tai"
    location = 1608
    division =
    { id   = { type = 30036 id = 117 }
      name = "Kwajalein keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 118 }
    name     = "Ponape konkyochi tai"
    location = 1610
    division =
    { id   = { type = 30036 id = 119 }
      name = "Ponape keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 120 }
    name     = "Truk konkyochi tai"
    location = 1613
    division =
    { id   = { type = 30036 id = 121 }
      name = "Truk keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 122 }
    name     = "Ulithi konkyochi tai"
    location = 1618
    division =
    { id   = { type = 30036 id = 123 }
      name = "Ulithi keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 124 }
    name     = "Yap konkyochi tai"
    location = 1619
    division =
    { id   = { type = 30036 id = 125 }
      name = "Yap keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 126 }
    name     = "Palau konkyochi tai"
    location = 1621
    division =
    { id   = { type = 30036 id = 127 }
      name = "Palau keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 128 }
    name     = "Saipan konkyochi tai"
    location = 1627
    division =
    { id   = { type = 30036 id = 129 }
      name = "Saipan keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 130 }
    name     = "Omura konkyochi tai"
    location = 1784
    division =
    { id   = { type = 30036 id = 131 }
      name = "Omura keibitai"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 132 }
    name     = "Marcus konkyochi tai"
    location = 1785
    division =
    { id   = { type = 30036 id = 133 }
      name = "Marcus keibitai"
      type = garrison
    }
  }
	######################
	### Japan Navy OOB ###
	######################
  navalunit =
  { id       = { type = 30036 id = 134 }
    name     = "Dai 1 Kido Kantai"
    location = 1188
    base     = 1188 # Hiroshima
    division =
    { id    = { type = 30036 id = 135 }
      name  = "IJN Ryuju"
      type  = escort_carrier
      model = 1
    }
    division =
    { id    = { type = 30036 id = 136 }
      name  = "IJN Chitose"
      type  = escort_carrier
      model = 1
    }
    division =
    { id    = { type = 30036 id = 137 }
      name  = "IJN Fuso"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 30036 id = 138 }
      name  = "IJN Yamashiro"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 30036 id = 139 }
      name  = "IJN Ise"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 30036 id = 140 }
      name  = "IJN Hyuga"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 30036 id = 141 }
      name  = "IJN Kongo"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 142 }
      name  = "IJN Hiei"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 143 }
      name  = "IJN Kako"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 144 }
      name  = "IJN Aoba"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 145 }
      name  = "IJN Kinugasa"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 146 }
      name  = "IJN Furutaka"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 147 }
      name  = "IJN Kitakami"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 148 }
      name  = "IJN Oi"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 149 }
      name  = "IJN Sendai"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 150 }
      name  = "IJN Yubari"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 151 }
      name  = "Dai 40 Kuchikusentai"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 30036 id = 152 }
      name  = "Dai 41 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 30036 id = 153 }
      name  = "Dai 45 Kuchikusentai"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { id       = { type = 30036 id = 154 }
    name     = "Dai 2 Nanken Kantai"
    location = 1184
    base     = 1184 # Tokyo
    #division = 	# seaplane tender added as a cvl above.
    #{ id    = { type = 30036 id = 155 }
    #  name  = "IJN Chitose"
    #  type  = carrier
    #  model = 1
    #}
    division =
    { id    = { type = 30036 id = 156 }
      name  = "IJN Atago"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 157 }
      name  = "IJN Maya"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 158 }
      name  = "IJN Chokai"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 159 }
      name  = "IJN Myoko"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 160 }
      name  = "IJN Suzuya"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 30036 id = 161 }
      name  = "IJN Kumano"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 30036 id = 162 }
      name  = "IJN Naka"
      type  = light_cruiser
      model = 1
    }
    division =
    { id       = { type = 30036 id = 163 }
      name     = "IJN Natori"
      type     = light_cruiser
      model    = 1
      maxspeed = 36
    }
    division =
    { id    = { type = 30036 id = 164 }
      name  = "Dai 2 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 30036 id = 165 }
      name  = "Dai 5 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 30036 id = 166 }
      name  = "Dai 7 Kuchikusentai"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { id       = { type = 30036 id = 167 }
    name     = "Dai 3 Nanken Kantai"
    location = 1322
    base     = 1322 # Taiwan
    division =
    { id    = { type = 30036 id = 168 }
      name  = "IJN Haruna"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 169 }
      name  = "IJN Nachi"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 170 }
      name  = "IJN Haguro"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 171 }
      name  = "IJN Ashigara"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 172 }
      name  = "IJN Tone"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 173 }
      name  = "IJN Jintsu"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 174 }
      name  = "IJN Kuma"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 175 }
      name  = "Dai 13 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 176 }
      name  = "Dai 17 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 30036 id = 177 }
      name = "Dai 10 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 178 }
      name = "Dai 11 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 179 }
      name = "Dai 12 Yuso Sentai"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 30036 id = 180 }
    name     = "Dai 4 Nanken Kantai"
    location = 1613
    base     = 1613 # Truk
    division =
    { id    = { type = 30036 id = 181 }
      name  = "IJN Tenryu"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 30036 id = 182 }
      name  = "IJN Tatsuta"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 30036 id = 183 }
      name  = "Dai 9 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 184 }
      name  = "Dai 10 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 185 }
      name  = "Dai 13 Sensuisentai"
      type  = submarine
      model = 3
    }
  }
  navalunit =
  { id       = { type = 30036 id = 186 }
    name     = "Hokuto Hômen Kantai" #Northen
    location = 1181
    base     = 1181 # Akita
    division =
    { id    = { type = 30036 id = 187 }
      name  = "IJN Tama"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 188 }
      name  = "IJN Kiso"
      type  = light_cruiser
      model = 1
    }
  }
  navalunit =
  { id       = { type = 30036 id = 189 }
    name     = "Dai 6 Sensuikantai"
    location = 1186
    base     = 1186 # Kanazawa (Maizuru)
    division =
    { id    = { type = 30036 id = 190 }
      name  = "Dai 1 Sensuisentai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 191 }
      name  = "Dai 2 Sensuisentai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 192 }
      name  = "Dai 3 Sensuisentai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 193 }
      name  = "Dai 4 Sensuisentai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 194 }
      name  = "Dai 5 Sensuisentai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 195 }
      name  = "Dai 6 Sensuisentai"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 30036 id = 196 }
      name  = "Dai 7 Sensuisentai"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 30036 id = 197 }
      name  = "Dai 8 Sensuisentai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 198 }
      name  = "Dai 9 Sensuisentai"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 30036 id = 199 }
      name  = "Dai 10 Sensuisentai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 200 }
      name  = "Dai 11 Sensuisentai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 201 }
      name  = "Dai 12 Sensuisentai"
      type  = submarine
      model = 3
    }
  }
  navalunit =
  { id       = { type = 30036 id = 202 }
    name     = "Shingeki butai" # "Striking Force"
    location = 1184
    base     = 1184 # Tokyo
    division =
    { id            = { type = 30036 id = 203 }
      name          = "IJN Kaga"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 3
      experience    = 20
    }
    division =
    { id            = { type = 30036 id = 204 }
      name          = "IJN Agaki"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 3
      experience    = 20
    }
    division =
    { id            = { type = 30036 id = 205 }
      name          = "IJN Soryu"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 3
      experience    = 20
    }
    division =
    { id    = { type = 30036 id = 206 }
      name  = "IJN Nagato"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 30036 id = 207 }
      name  = "IJN Mutsu"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 30036 id = 208 }
      name  = "IJN Kirishima"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 209 }
      name  = "IJN Takao"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 210 }
      name  = "IJN Mogami"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 30036 id = 211 }
      name  = "IJN Mikuma"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 30036 id = 212 }
      name  = "Dai 42 Kuchikusentai"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 30036 id = 213 }
      name  = "Dai 43 Kuchikusentai"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 30036 id = 214 }
    name     = "Yobikantai"  #Reserve fleet
    location = 1190
    base     = 1190
    division =
    { id            = { type = 30036 id = 215 }
      name          = "IJN Hosho"
      type          = escort_carrier
      model         = 0
      experience    = 20
    }
    division =
    { id    = { type = 30036 id = 216 }
      name  = "IJN Izumo"
      type  = heavy_cruiser
      model = 0
    }
    division =
    { id    = { type = 30036 id = 217 }
      name  = "IJN Hirado"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 30036 id = 218 }
      name  = "IJN Yahagi"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 30036 id = 219 }
      name  = "Dai 1 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 220 }
      name  = "Dai 3 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 221 }
      name  = "Dai 4 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 222 }
      name  = "Dai 6 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 223 }
      name  = "Dai 8 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 30036 id = 224 }
      name = "Dai 4 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 225 }
      name = "Dai 8 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 226 }
      name = "Dai 9 Yuso Sentai"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 30036 id = 227 }
    name     = "Shina Hômen Kantai" # China area fleet
    location = 1237
    base     = 1237
    division =
    { id    = { type = 30036 id = 228 }
      name  = "IJN Isuzu"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 229 }
      name  = "IJN Yura"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 230 }
      name  = "IJN Kinu"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 231 }
      name  = "IJN Abukuma"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 232 }
      name  = "Dai 12 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 30036 id = 233 }
      name  = "Dai 14 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 30036 id = 234 }
      name  = "Dai 15 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 30036 id = 235 }
      name  = "Dai 16 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 30036 id = 236 }
      name  = "Dai 18 Kuchikusentai"
      type  = destroyer
      model = 1
    }
    division =
    { id   = { type = 30036 id = 237 }
      name = "Dai 1 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 238 }
      name = "Dai 2 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 239 }
      name = "Dai 3 Yuso Sentai"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 30036 id = 240 }
    name     = "Chôsen Hômen Kantai" # Korea area fleet
    location = 1196
    base     = 1196
    division =
    { id    = { type = 30036 id = 241 }
      name  = "IJN Chikuma"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 30036 id = 242 }
      name  = "IJN Nagara"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 30036 id = 243 }
      name  = "Dai 11 Kuchikusentai"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 30036 id = 244 }
      name = "Dai 5 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 245 }
      name = "Dai 6 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 30036 id = 246 }
      name = "Dai 7 Yuso Sentai"
      type = transport
    }
  }
	#####################
	### JAPAN Air OOB ###
	#####################
  airunit =
  { id       = { type = 30036 id = 247 }
    name     = "Dai 1 Hikoshidan"
    location = 1184
    base     = 1184 # Tokyo
    division =
    { experience = 20
      id         = { type = 30036 id = 248 }
      name       = "Dai 1 Kyokutsi Hikodan"
      type       = interceptor
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 249 }
      name       = "Dai 12 Yosu no Hikodan"
      type       = transport_plane
      model      = 0
    }
  }
  airunit =
  { id       = { type = 30036 id = 250 }
    name     = "Dai 2 Hikoshidan"
    location = 1202
    base     = 1202 # Dalian
    division =
    { experience = 20
      id         = { type = 30036 id = 251 }
      name       = "Dai 2 Keibakugeki Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 252 }
      name       = "Dai 9 Keibakugeki Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 253 }
      name       = "Dai 8 Kyokutsi Hikodan"
      type       = interceptor
      model      = 1
    }
  }
  airunit =
  { id       = { type = 30036 id = 254 }
    name     = "Dai 3 Hikoshidan"
    location = 1322
    base     = 1322 # Taiwan
    division =
    { experience = 20
      id         = { type = 30036 id = 255 }
      name       = "Dai 3 Keibakugeki Hikodan"
      strength   = 100
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 256 }
      name       = "Dai 7 Keibakugeki Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 257 }
      name       = "Dai 10 Keibakugeki Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 258 }
      name       = "Dai 12 Kyokutsi Hikodan"
      type       = interceptor
      model      = 1
    }
  }
  airunit =
  { id       = { type = 30036 id = 259 }
    name     = "Dai 1 Kokutai"
    location = 1322
    base     = 1322 # Taiwan
    division =
    { experience = 20
      id         = { type = 30036 id = 260 }
      name       = "Dai 1 Kaigunkogeki Hikodan"
      type       = naval_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 261 }
      name       = "Dai 2 Kaigunkogeki Hikodan"
      type       = naval_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 262 }
      name       = "Dai 3 Sento Hikodan"
      type       = multi_role
      model      = 0
    }
  }
  # Completion dates for CVs and BBs based upon historical start date plus HoI 2 build times
  # These build times are quicker than history but player may delay completion by lowering them in build queue priority

  division_development =
  {  id    = { type = 30036 id = 263 }
    name  = "IJN Chiyoda" # seaplane carrier
    type  = escort_carrier
    model = 2
    cost  = 4
    date  = { year = 1938 month = december day = 14 } #86% ready
  }
  division_development =
    { id            = { type = 30036 id = 264 }
      name          = "IJN Hiryu"
      type          = carrier
      model         = 2
      cost          = 6
      date  = { year = 1939 month = march day = 25 } # 72% ready
      extra = cag
      brigade_model = 3
  }
  division_development =
  { id    = { type = 30036 id = 266 }
    name  = "IJN Zuiho" # conversion from submarine tender
    type  = escort_carrier
    model = 1
    cost  = 4
    date  = { year = 1939 month = july day = 4 } #58% ready
  }
  division_development =
  { id    = { type = 30036 id = 268 }
    name  = "IJN Shoho" # conversion from submarine tender, 1 year earlier than history per general HoI speed up
    type  = escort_carrier
    model = 1
    cost  = 4
    date  = { year = 1939 month = august day = 5 } # 54% ready
  }
  division_development =
  { id    = { type = 30036 id = 270 }
    name  = "IJN Shokaku"
    type  = carrier
    model = 3
    cost  = 7
    date  = { year = 1940 month = april day = 9 } #20% ready
    extra = cag
    brigade_model = 3
  }
  division_development =
  { name  = "Dai 33 Sensuisentai"
    type  = submarine
    model = 3
    cost  = 2.3
    id    = { type = 30036 id = 272 }
    date  = { year = 1939 month = may day = 1 }
  }
  division_development =
  { name  = "IJN Zuikaku"
    type  = carrier
    model = 3
    cost  = 7
    id    = { type = 30036 id = 273 }
    date  = { year = 1940 month = july day = 2 } #8% ready
    extra = cag
    brigade_model = 3
  }
  division_development =
  { name  = "IJN Yamato"
    type  = battleship
    model = 6
    cost  = 16
    id    = { type = 30036 id = 275 }
    date  = { year = 1940 month = april day = 30 } #20% ready
  }
  division_development =
  { name  = "IJN Musashi"
    type  = battleship
    model = 6
    cost  = 16
    id    = { type = 30036 id = 276 }
    date  = { year = 1940 month = july day = 17 } #10% ready
  }
}
