province = {
	id = 523
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 521
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 378
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 515
	air_base = {
		size = 10
		current_size = 10
		}

	}


province = {
	id = 525
	air_base = {
		size = 4
		current_size = 4
		}

	}

province = {
	id = 534
	air_base = {
		size = 3
		current_size = 3
		}

	}



#Anti Aircraft Batteries
province = { id = 531   anti_air = 3 } #Torino
province = { id = 368   anti_air = 2 } #Genoa
province = { id = 370   anti_air = 3 } #Milano
province = { id = 369   anti_air = 2 } #La Spezia
province = { id = 378   anti_air = 1 } #Venezia
province = { id = 512   anti_air = 1 } #Bologna
province = { id = 513   anti_air = 1 } #Firenze
province = { id = 515   anti_air = 3 } #Roma
province = { id = 521   anti_air = 2 } #Napoli
province = { id = 523   anti_air = 2 } #Taranto


country = {
    tag = ITA

	policy = {
	date = { year = 0 month = january day = 0 }
	democratic = 2
	political_left = 3
	freedom = 4
	free_market = 7
	professional_army = 3
	defense_lobby = 7
	interventionism = 6
    }

	headofstate = { type = 9 id = 3001 }
	headofgovernment = { type = 9 id = 3002 }
	foreignminister = { type = 9 id = 3003 }
	armamentminister = { type = 9 id = 3068 }
	ministerofsecurity = { type = 9 id = 3091 }
	ministerofintelligence = { type = 9 id = 3110 }
	chiefofstaff = { type = 9 id = 3125 }
	chiefofarmy = { type = 9 id = 3140 }
	chiefofnavy = { type = 9 id = 3149 }
	chiefofair = { type = 9 id = 3161 }

steal_leader = 6088 #Guzzoni
steal_leader = 6001
steal_leader = 6003
steal_leader = 6245
steal_leader = 6016
steal_leader = 6020
steal_leader = 6022
steal_leader = 6243
steal_leader = 6030
steal_leader = 6012
steal_leader = 6247
steal_leader = 6248
steal_leader = 6038
steal_leader = 6039
steal_leader = 6249
steal_leader = 6250
steal_leader = 6053
steal_leader = 6056
steal_leader = 6058
steal_leader = 6062
steal_leader = 6256
steal_leader = 6066
steal_leader = 6070
steal_leader = 6071
steal_leader = 6072
steal_leader = 6258
steal_leader = 6259
steal_leader = 6081
steal_leader = 6083
steal_leader = 6260
steal_leader = 6087
steal_leader = 6261
steal_leader = 6091
steal_leader = 6096
steal_leader = 6263
steal_leader = 6099
steal_leader = 6104
steal_leader = 6264
steal_leader = 6266
steal_leader = 6107
steal_leader = 6113
steal_leader = 6242
steal_leader = 6273
steal_leader = 6125
steal_leader = 6128
steal_leader = 6131
steal_leader = 6275
steal_leader = 6135
steal_leader = 6138
steal_leader = 6141
steal_leader = 6026
steal_leader = 6032
steal_leader = 6102
steal_leader = 6269
steal_leader = 6009
steal_leader = 6120
steal_leader = 6140
steal_leader = 6144
steal_leader = 6146
steal_leader = 6002
steal_leader = 6013
steal_leader = 6021
steal_leader = 6023
steal_leader = 6028
steal_leader = 6029
steal_leader = 6031
steal_leader = 6057
steal_leader = 6253
steal_leader = 6252
steal_leader = 6251
steal_leader = 6065
steal_leader = 6255
steal_leader = 6069
steal_leader = 6074
steal_leader = 6084
steal_leader = 6262
steal_leader = 6089
steal_leader = 6090
steal_leader = 6265
steal_leader = 6108
steal_leader = 6267
steal_leader = 6268
steal_leader = 6111
steal_leader = 6270
steal_leader = 6114
steal_leader = 6116
steal_leader = 6271
steal_leader = 6124
steal_leader = 6126
steal_leader = 6274
steal_leader = 6130
steal_leader = 6133
steal_leader = 6134
steal_leader = 6145
steal_leader = 6150
steal_leader = 6027
steal_leader = 6036
steal_leader = 6037
steal_leader = 6040
steal_leader = 6049
steal_leader = 6054
steal_leader = 6068
steal_leader = 6088
steal_leader = 6094
steal_leader = 6129
steal_leader = 6132
steal_leader = 6136
steal_leader = 6147
steal_leader = 6152
steal_leader = 6156
steal_leader = 6157
steal_leader = 6161
steal_leader = 6166
steal_leader = 6169
steal_leader = 6172
steal_leader = 6177
steal_leader = 6180
steal_leader = 6183
steal_leader = 6184
steal_leader = 6185
steal_leader = 6189
steal_leader = 6192
steal_leader = 6182
steal_leader = 6164
steal_leader = 6173
steal_leader = 6281
steal_leader = 6175
steal_leader = 6188
steal_leader = 6191
steal_leader = 6196
steal_leader = 6198
steal_leader = 6202
steal_leader = 6205
steal_leader = 6211
steal_leader = 6212
steal_leader = 6221
steal_leader = 6224
steal_leader = 6232
steal_leader = 6234
steal_leader = 6236
steal_leader = 6203
steal_leader = 6282
steal_leader = 6201
steal_leader = 6206
steal_leader = 6215
steal_leader = 6218
steal_leader = 6225
steal_leader = 6231
steal_leader = 6233
steal_leader = 6283
steal_leader = 6237




## Resource Reserves
manpower = 235
energy		= 6500
metal		= 6500
rare_materials 		= 5000
oil 		= 6500
supplies 	= 6500
money 		= 3500
consumer = 0.20
supply = 0.50
production = 0.00
reinforcement = 0.30



transports = 50
escorts = 10


	capital = 515

	ownedprovinces =      {
		525 526 524 523 522 521 520 519 518 517 516 515 513 514  512 379 369 368 531 370 371 378 534



	}
	controlledprovinces = {
		525 526 524 523 522 521 520 519 518 517 516 515 513 514  512 379 369 368 531 370 371 378 534
	}
	nationalprovinces =   {
		525 526 524 523 522 521 520 519 518 517 516 515 513 514  512 379 369 368 531 370 371 378 534
	}

	techapps               = { 1240  4070  4200  4010  4020  4030  4040  4050  4120  4130  4140  4190  4250  4260  2010  2020  2040  2030  2050  2070
			     2150  2290  2300  2310  2320  2330  2400  2450  2460  2470  2510  2520  1010  1020  1150  1160  1190  1200  1210  1220
			     1110  1120  1130  1030  1070  1230  1310  1340  5010  5050  5060  5080  5090  5100  5190  5200  5310  5320  5470  5480
			     5490  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  6010  6030  6110  6120  6130  8010  8020  8030  8040
			     8050  8070  8120  8310  3010  3020  3030  3070  3080  3090  3100  3130  3140  3150  3190  3200  3250  3260  3270  3280
			     3320  3400  3410  3420  3430  14000 14010 14020
			   }



#OOB ITA
#6th Italian Army
#Leader in Chief: Generale d'Armata Alfredo Guzzoni
#HQG leader: generale di Brigata Emilio Faldella
#XII Corps | Generale di corpo d'armata Mario Arisio

landunit = { location = 526 id = { type = 12000 id = 47 } name = "6a Armata" leader = 6088 #Guzzoni
division = { id = { type = 12000 id = 48 } name = "Q.G. 6a Armata" type = hq strength = 50 max_strength = 50 model = 1 }
}

landunit = { location = 525 name = "XII Corpo d'Armata" id = { type = 12000 id = 1 } leader = 6070 #Franzosi
division = { id = { type = 12000 id = 2 } name = "28a Divisione 'Aosta'" type = infantry strength = 70 max_strength = 70 model = 2 }
division = { id = { type = 12000 id = 3 } name = "26a Divisione 'Assietta'" type = infantry strength = 70 max_strength = 70 model = 2 }
}

landunit = { location = 525 name = "XIII Corpo d'Armata" id = { type = 12000 id = 5 }
division = { id = { type = 12000 id = 6 } name = "207. Divisione costiera" type = garrison strength = 70 max_strength = 70 model = 1 }
division = { id = { type = 12000 id = 7 } name = "202. Divisione costiera" type = garrison  strength = 70 max_strength = 70 model = 1 }
division = { id = { type = 12000 id = 8 } name = "208. Divisione costiera" type = garrison  strength = 60 max_strength = 60 model = 1 }
}


landunit = { location = 526 name = "XVI Corpo d'Armata" id = { type = 12000 id = 9 }
division = { id = { type = 12000 id = 10 } name = "54a Divisione 'Napoli'" type = infantry strength = 70 max_strength = 70 model = 2 }
}


landunit = { location = 526  name = "6. Riserva d'Armata" id = { type = 12000 id = 66 }
division = { id = { type = 12000 id = 11 } name = "4a Divisione 'Livorno'" type = infantry strength = 70 max_strength = 70 model = 2 }
}


landunit = { location = 526 name = "XVII Corpo d'Armata" id = { type = 12000 id = 12 }
division = { id = { type = 12000 id = 13 } name = "206. Divisione costiera" type = garrison strength = 70 max_strength = 70 model = 1 }
division = { id = { type = 12000 id = 14 } name = "213. Divisione costiera" type = garrison  strength = 70 max_strength = 70 model = 1 }
}



landunit = { location = 534 name = "Comando Costiero della Sardegna" id = { type = 12000 id = 15 }
division = { id = { type = 12000 id = 16 } name = "204. Divisione costiera" type = garrison strength = 70 max_strength = 70 model = 1 }
division = { id = { type = 12000 id = 17 } name = "205. Divisione costiera" type = garrison  strength = 70 max_strength = 70 model = 1 }
division = { id = { type = 12000 id = 20 } name = "203. Divisione costiera" type = garrison  strength = 60 max_strength = 60 model = 1 }
}



landunit = { location = 513 name = "Comando Costiero fiorentino" id = { type = 12000 id = 67 }
division = { id = { type = 12000 id = 68 } name = "224. Divisione costiera" type = bergsjaeger strength = 60 max_strength = 60 model = 1 }
division = { id = { type = 12000 id = 69 } name = "225. Divisione costiera" type = garrison strength = 60 max_strength = 60 model = 1 extra = artillery brigade_model = 2 }
division = { id = { type = 12000 id = 70 } name = "226. Divisione costiera" type = garrison strength = 60 max_strength = 60 model = 1 extra = artillery brigade_model = 2 }
}


landunit = { location = 519 name = "Comando Costiero di Anzio" id = { type = 12000 id = 21 }
division = { id = { type = 12000 id = 23 } name = "209. Divisione costiera" type = garrison  strength = 70 max_strength = 70 model = 1 }
}

landunit = { location = 524 name = "Comando Costiero della Calabria" id = { type = 12000 id = 25  }
division = { id = { type = 12000 id = 26 } name = "211. Divisione costiera" type = garrison strength = 70 max_strength = 70 model = 1 }
division = { id = { type = 12000 id = 27 } name = "212. Divisione costiera" type = garrison  strength = 70 max_strength = 70 model = 1 }
}


landunit = { location = 523 name = "Comando Costiero della Puglia" id = { type = 12000 id = 28 }
division = { id = { type = 12000 id = 29 } name = "214. Divisione costiera" type = garrison strength = 70 max_strength = 70 model = 1 }
}

landunit = { location = 514 name = "Comando Costiero di Rimini" id = { type = 12000 id = 30 }
division = { id = { type = 12000 id = 31 } name = "215. Divisione costiera" type = garrison strength = 70 max_strength = 70 model = 1 }
}

landunit = { location = 515 name = "Comando costiero del Lazio" id = { type = 12000 id = 18 }
division = { id = { type = 12000 id = 71 } name = "220. Divisione costiera" type = garrison strength = 60 max_strength = 60 model = 1 }
division = { id = { type = 12000 id = 22 } name = "221. Divisione costiera" type = garrison strength = 60 max_strength = 60 model = 1 }
}


landunit = { location = 515 name = "7a Armata" id = { type = 12000 id = 32 }
division = { id = { type = 12000 id = 33 } name = "132a Divisione 'Ariete'" type = armor model = 3 strength = 70 max_strength = 70 }
division = { id = { type = 12000 id = 34 } name = "103a Divisione 'Piacenza'" type = infantry strength = 70 max_strength = 70 model = 2 }
division = { id = { type = 12000 id = 35 } name = "10a Divisione 'Piave'" type = infantry strength = 70 max_strength = 70 model = 2 }
}


landunit = { location = 522 name = "7a Armata" id = { type = 12000 id = 36 }
division = { id = { type = 12000 id = 37 } name = "104a Divisione 'Mantova'" type = infantry  model = 2 strength = 70 max_strength = 70 }
division = { id = { type = 12000 id = 38 } name = "7a Divisione 'Lupi di Toscana'" type = infantry strength = 70 max_strength = 70 model = 2 }
}

landunit = { location = 523 name = "7a Armata" id = { type = 12000 id = 39 } leader = 6084 #Graziani
division = { id = { type = 12000 id = 40 } name = "21a Divisione 'Granatieri di Sardegna'" type = infantry  model = 2 strength = 70 max_strength = 70  }
division = { id = { type = 12000 id = 74 } name = "Q.G. 7a Armata" type = hq strength = 50 max_strength = 50 model = 1 }
}



airunit = { location = 534 base = 534 id = { type = 12000 id = 41 } name = "Aeronautica della Sardegna"
division = { id = { type = 12000 id = 42 } name = "23° Stormo Caccia" strength = 65 max_strength = 80 type = interceptor model = 1  }
}

airunit = { location = 525 base = 525 id = { type = 12000 id = 43 } name = "Aeronautica della Sicilia"
division = { id = { type = 12000 id = 44 } name = "2° Stormo Caccia" strength = 65 max_strength = 80 type = interceptor model = 1  }
}

airunit = { location = 525 base = 525 id = { type = 12000 id = 45 } name = "Aeronautica della Sicilia"
division = { id = { type = 12000 id = 46 } name = "10° Stormo Bombardieri" strength = 110 max_strength = 110 type = cas model = 1  }
 }


#navalunit = { location = 523 base = 523 id = { type = 12000 id = 49 } name = "Regio Marina"
#division = {  id = { type = 12000 id = 50 } name = "RM Taranto" strength = 100 type = heavy_cruiser model = 0 }
#division = {  id = { type = 12000 id = 51 } name = "RM Bari" strength = 100 type = heavy_cruiser model = 0 }
#division = {  id = { type = 12000 id = 52 } name = "2a Flottiglia Torpediniere" strength = 100 type = destroyer model = 1 }
#division = {  id = { type = 12000 id = 53 } name = "RM Vittorio Veneto" strength = 100 type = battleship model = 3 }
#division = {  id = { type = 12000 id = 54 } name = "RM Gorizia" strength = 100 type = heavy_cruiser model = 2 }
#division = {  id = { type = 12000 id = 55 } name = "9a Flottiglia Torpediniere" strength = 100 type = destroyer model = 1 }
#division = {  id = { type = 12000 id = 56 } name = "RM Littorio" strength = 100 type = battleship model = 3 }
#division = {  id = { type = 12000 id = 57 } name = "RM Luigi Cadorna" strength = 100 type = light_cruiser model = 1 }
#division = {  id = { type = 12000 id = 58 } name = "RM Eugena di Savoia" strength = 100 type = light_cruiser model = 1 }
#division = {  id = { type = 12000 id = 59 } name = "12a Flottiglia Torpediniere" strength = 100 type = destroyer model = 1 }
#division = {  id = { type = 12000 id = 60 } name = "7a Flottiglia Torpediniere" strength = 100 type = destroyer model = 1 }
#division = {  id = { type = 12000 id = 61 } name = "RM Duca degli Abruzzi" strength = 100 type = light_cruiser model = 1 }
#division = {  id = { type = 12000 id = 62 } name = "RM Guiseppe Garibaldi" strength = 100 type = heavy_cruiser model = 1 }
#division = {  id = { type = 12000 id = 63 } name = "RM Bolzano" strength = 100 type = heavy_cruiser model = 2 }
#division = {  id = { type = 12000 id = 64 } name = "RM Duca d'Aosta" strength = 100 type = heavy_cruiser model = 1 }
#division = {  id = { type = 12000 id = 65 } name = "RM Raimondo Montecuccoli" strength = 100 type = light_cruiser model = 0 }
#}


#S.France Occupation Units
landdivision = { dormant = yes id = { type = 12000 id = 19 } name = "201. Divisione costiera" type = garrison strength = 70 max_strength = 70 model = 1 }
landdivision = { dormant = yes id = { type = 12000 id = 72 } name = "223. Divisione costiera" type = bergsjaeger strength = 100 model = 1 }

#Post surrender ITA units
landdivision = { dormant = yes id = { type = 12000 id = 75 } name = "Gruppo Cremona" type = infantry strength = 60 max_strength = 60 model = 2 }
landdivision = { dormant = yes id = { type = 12000 id = 76 } name = "Gruppo Legnano" type = infantry strength = 60 max_strength = 60 model = 2 extra = artillery brigade_model = 2 }
landdivision = { dormant = yes id = { type = 12000 id = 77 } name = "Gruppo Friuli" type = infantry strength = 60 max_strength = 60 model = 2 extra = artillery brigade_model = 2 }
landdivision = { dormant = yes id = { type = 12000 id = 78 } name = "Gruppo Mantova" type = infantry strength = 60 max_strength = 60 model = 2 extra = artillery brigade_model = 2 }
landdivision = { dormant = yes id = { type = 12000 id = 79 } name = "Gruppo Piceno" type = infantry strength = 60 max_strength = 60 model = 2 extra = artillery brigade_model = 2 }
landdivision = { dormant = yes id = { type = 12000 id = 80 } name = "Gruppo Folgore" type = marine strength = 60 max_strength = 60 model = 2 extra = artillery brigade_model = 2 }

}#EOF