
##############################
# Country definition for UBO #
##############################

province =
{ id         = 32
  ic         = 1
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Brest
province = { id = 35 anti_air = 2 } # Nantes
province =
{ id         = 38
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Cherbourg
province = { id = 39 anti_air = 1 } # Caen
province =
{ id         = 43
  naval_base = { size = 3 current_size = 3 }
  anti_air   = 1
}              # Dunkerque
province =
{ id        = 44
  air_base  = { size = 10 current_size = 10 }
  metal     = 0
  max_metal = 0
  anti_air  = 3
}             # Lille
province = { id = 54 metal = 0 max_metal = 0 } # Amiens
province = { id = 55 metal = 0 max_metal = 0 } # Compiègne
province =
{ id       = 56
  ic       = 1
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # Paris
province =
{ id       = 59
  air_base = { size = 10 current_size = 10 }
  anti_air = 3
}            # Cholet
province =
{ id       = 62
  air_base = { size = 10 current_size = 10 }
  anti_air = 3
}            # Auxerre
province =
{ id        = 72
  anti_air  = 3
  air_base  = { size = 10 current_size = 10 }
  metal     = 71
  max_metal = 71
}             # Metz
province = { id = 73 anti_air = 2 } # Strasbourg
province = { id = 316 anti_air = 2 } # Mulhouse
province = { id = 317 anti_air = 1 } # Chaumont
province = { id = 320 ic = 1 anti_air = 1 } # Vichy
province =
{ id         = 325
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Bordeaux
province = { id = 329 infra = 0.4 } # Huesca
province = { id = 330 infra = 0.1 energy = 11 rare_materials = 4 oil = 25 } # Saragossa
province = { id = 331 infra = 0.3 energy = 12 rare_materials = 7 oil = 25 } # Bilbao
province = { id = 332 infra = 0.4 } # Oviedo
province = { id = 333 infra = 0.2 } # Burgos
province = { id = 334 infra = 0.4 } # La Coruña
province = { id = 335 infra = 0.1 } # Oporto
province = { id = 337 infra = 0.1 } # Guarda
province = { id = 338 infra = 0.2 energy = 10 rare_materials = 5 oil = 25 } # Salamanca
province = { id = 339 infra = 0.2 } # Valladolid
province = { id = 340 infra = 0.2 energy = 10 rare_materials = 5 oil = 25 air_base = 5 anti_air = 2 } # Sigüenza
province = { id = 342 infra = 0.2 } # Guadalajara
province = { id = 343 infra = 0.2 } # Badajoz
province = { id = 344 infra = 0.2 } # Evora
province = { id = 345 infra = 0.2 } # Faro
province = { id = 346 infra = 0.2 } # Huelva
province = { id = 347 infra = 0.2 ic = 5 } # Seville
province =
{ id          = 348
  anti_air    = 6
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 6
  coastalfort = 0
  oilpool     = 1000
  supplypool  = 1000
  ic          = 10
}               # Gibraltar
province = { id = 349 infra = 0.2 ic = 5 } # Málaga
province = { id = 350 infra = 0.4 ic = 5 } # Almería
province = { id = 351 infra = 0.2 ic = 5 } # Jaén
province = { id = 352 infra = 0.2 } # Murcia
province = { id = 353 infra = 0.2 air_base = 3 anti_air = 2 } # Albacete
province = { id = 354 infra = 0.1 } # València
province = { id = 355 infra = 0.2 } # Castellón
province = { id = 356 infra = 0.1 } # Tarragona
province =
{ id       = 359
  air_base = { size = 10 current_size = 10 }
  anti_air = 2
}            # Toulouse
province =
{ id         = 364
  ic         = 1
  anti_air   = 5
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Marseille
province = { id = 366 landfort = 5 } # Nice
province = { id = 527 landfort = 3 } # Grenoble
province = { id = 528 ic = 1 anti_air = 1 } # Lyon
province = { id = 535 infra = 0.2 air_base = 7 anti_air = 2 } # Mallorca
province = { id = 536 infra = 0.2 } # Menorca
province = { id = 537 infra = 0.3 } # Ibiza
province = { id = 942 infra = 0.2 } # Bône
province = { id = 943 infra = 0.4 } # Constantine
province = { id = 944 infra = 0.4 } # Sétif
province = { id = 945 infra = 0.2 energy = 10 rare_materials = 5 oil = 10 naval_base = 3 air_base = 3 anti_air = 2 } # Philippeville
province = { id = 946 infra = 0.2 } # Bougie
province = { id = 947 infra = 0.4 } # Blida
province = { id = 948 infra = 0.4 rare_materials = 5 oil = 15 } # Mascara
province =
{ id         = 949
  infra      = 0.2
  supplypool = 500
  oilpool    = 1
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 5 current_size = 5 }
}              # Algiers
province = { id = 950 infra = 0.2 } # Mostaganem
province = { id = 951 infra = 0.4 } # Sidi-Bel-Abbès
province = { id = 952 infra = 0.4 } # Tlemcen
province =
{ id         = 953
  infra      = 0.2
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Oran
province = { id = 954 infra = 0.2 ic = 5 } # Melilla
province = { id = 955 infra = 0.2 ic = 5 } # Villa Sanjuro
province = { id = 956 infra = 0.4 } # Oujda
province = { id = 957 infra = 0.2 ic = 7 anti_air = 1 } # Ceuta
province =
{ id         = 958
  infra      = 0.2
  ic         = 5
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Casablanca
province = { id = 959 infra = 0.4 ic = 5 anti_air = 1 } # Marrakech
province = { id = 960 infra = 0.2 } # Mogador
province = { id = 961 infra = 0.4 } # Lanzarote
province = { id = 962 infra = 0.3 } # Fuerteventura
province = { id = 963 infra = 0.2 } # Gran Canaria
province = { id = 964 infra = 0.2 } # Tenerife
province = { id = 965 infra = 0.2 } # La Palma
province = { id = 966 infra = 0.2 } # Agadir
province = { id = 967 infra = 0.2 } # Ifni
province = { id = 968 infra = 0.6 } # Ouezzane
province = { id = 969 infra = 0.6 } # Bouarfa
province = { id = 970 infra = 0.8 air_base = 6 anti_air = 2 } # Géryville
province = { id = 971 infra = 0.4 } # El Aaiún
province = { id = 972 infra = 0.4 naval_base = 4 air_base = 4 anti_air = 3 } # Villa Cisneros
province = { id = 973 infra = 0.4 } # Port-Étienne
province = { id = 974 infra = 0.8 } # Fort-Gouraud
province = { id = 975 infra = 0.8 } # Taoudenni
province = { id = 1013 infra = 0.8 } # El-Oued
province = { id = 1014 infra = 0.8 } # Fort Laperrine
province = { id = 1081 infra = 0.8 } # Largeau
province = { id = 1082 infra = 0.8 } # Tibesti
province = { id = 1083 infra = 0.8 air_base = 2 anti_air = 1 } # Agadez
province =
{ id         = 1146
  infra      = 0.4
  naval_base = 4
  air_base   = { size = 4 current_size = 3 }
  anti_air   = 2
}              # Cap Verde Islands

#####################
# Country main data #
#####################

country =
{ tag                    = UBO
  ai                     = "globalwar/FRA.ai"
  capital                = 56
  belligerence           = 0
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 50
  manpower               = 1000
  transports             = 100
  escorts                = 100
  peacetime_ic_mod       = 0.5
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 4
    free_market       = 6
    freedom           = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }

  ownedprovinces         = { 529  527  366  365  364  363  362  358  328  327  326  325  324  359  361  319  360  322  323  59   60   61   62   63
			     318  317  316  73   72   64   53   44   43   18   54   42   55   41   56   57   58   32   33   34   35   36   37   38
			     39   40   320  321  528  956  969  968  959  958  960  966  1014 970  1013 943  942  945  944  946  947  949  948  951
			     950  952  953  973  348  334  332  333  339  338  341  343  346  347  349  350  351  352  353  354  342  355  340  330
			     331  356  329  357  535  536  537  961  962  963  964  965  957  955  954  967  971  972  974  975  1083 335  336  337
			     344  345  1867 1146 1082 1081
			   }

  controlledprovinces    = { 529  527  366  365  364  363  362  358  328  327  326  325  324  359  361  319  360  322  323  59   60   61   62   63
			     318  317  316  73   72   64   53   44   43   18   54   42   55   41   56   57   58   32   33   34   35   36   37   38
			     39   40   320  321  528  956  969  968  959  958  960  966  1014 970  1013 943  942  945  944  946  947  949  948  951
			     950  952  953  973  348  334  332  333  339  338  341  343  346  347  349  350  351  352  353  354  342  355  340  330
			     331  356  329  357  535  536  537  961  962  963  964  965  957  955  954  967  971  972  974  975  1083 335  336  337
			     344  345  1867 1146 1082 1081
			   }

  techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5010 5080 8010 8020 8030 8040 8050 9010 }

  nationalprovinces      = { 529  527  366  365  364  363  362  358  328  327  326  325  324  359  361  319  360  322  323  59   60   61   62   63
			     318  317  316  73   72   64   53   44   43   18   54   42   55   41   56   57   58   32   33   34   35   36   37   38
			     39   40   320  321  528  956  969  968  959  958  960  966  1014 970  1013 943  942  945  944  946  947  949  948  951
			     950  952  953  973  348  334  332  333  339  338  341  343  346  347  349  350  351  352  353  354  342  355  340  330
			     331  356  329  357  535  536  537  961  962  963  964  965  957  955  954  967  971  972  974  975  1083 335  336  337
			     344  345  1867 1146 1082 1081 45   52   65   68   70   71   74   314  315  533  530  532  531  368  941  937  934  931
			     1015 1016 1067 1080 1084 998  976  977  979  980  984  981
			   }

  # #################
  # ###FRENCH OOB####
  # #################
  landunit =
  { id       = { type = 30007 id = 1 }
    name     = "1. Corps"
    location = 1146
    division =
    { id       = { type = 30007 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 3 }
    name     = "2. Corps"
    location = 1867
    division =
    { id       = { type = 30007 id = 4 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 5 }
    name     = "3. Corps"
    location = 965
    division =
    { id       = { type = 30007 id = 6 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 7 }
    name     = "4. Corps"
    location = 964
    division =
    { id       = { type = 30007 id = 8 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 9 }
    name     = "5. Corps"
    location = 963
    division =
    { id       = { type = 30007 id = 10 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 11 }
    name     = "6. Corps"
    location = 962
    division =
    { id       = { type = 30007 id = 12 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 13 }
    name     = "7. Corps"
    location = 961
    division =
    { id       = { type = 30007 id = 14 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 15 }
    name     = "8. Corps"
    location = 973
    division =
    { id       = { type = 30007 id = 16 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 17 }
    name     = "9. Corps"
    location = 974
    division =
    { id       = { type = 30007 id = 18 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 19 }
    name     = "10. Corps"
    location = 975
    division =
    { id       = { type = 30007 id = 20 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 21 }
    name     = "11. Corps"
    location = 1083
    division =
    { id       = { type = 30007 id = 22 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 23 }
    name     = "12. Corps"
    location = 1082
    division =
    { id       = { type = 30007 id = 24 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 25 }
    name     = "13. Corps"
    location = 1081
    division =
    { id       = { type = 30007 id = 26 }
      name     = "13th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 27 }
    name     = "14. Corps"
    location = 1014
    division =
    { id       = { type = 30007 id = 28 }
      name     = "14th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 29 }
    name     = "15. Corps"
    location = 1013
    division =
    { id       = { type = 30007 id = 30 }
      name     = "15th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 31 }
    name     = "16. Corps"
    location = 943
    division =
    { id       = { type = 30007 id = 32 }
      name     = "16th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 33 }
    name     = "17. Corps"
    location = 942
    division =
    { id       = { type = 30007 id = 34 }
      name     = "17th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 35 }
    name     = "18. Corps"
    location = 949
    division =
    { id       = { type = 30007 id = 170 }
      name     = "18th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 36 }
    name     = "19. Corps"
    location = 953
    division =
    { id       = { type = 30007 id = 37 }
      name     = "19th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 38 }
    name     = "20. Corps"
    location = 954
    division =
    { id       = { type = 30007 id = 39 }
      name     = "20th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 40 }
    name     = "21. Corps"
    location = 958
    division =
    { id       = { type = 30007 id = 41 }
      name     = "21st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 42 }
    name     = "22. Corps"
    location = 971
    division =
    { id       = { type = 30007 id = 43 }
      name     = "22nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 44 }
    name     = "23. Corps"
    location = 972
    division =
    { id       = { type = 30007 id = 45 }
      name     = "23rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 46 }
    name     = "24. Corps"
    location = 536
    division =
    { id       = { type = 30007 id = 47 }
      name     = "24th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 48 }
    name     = "25. Corps"
    location = 535
    division =
    { id       = { type = 30007 id = 49 }
      name     = "25th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 50 }
    name     = "26. Corps"
    location = 537
    division =
    { id       = { type = 30007 id = 51 }
      name     = "26th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 52 }
    name     = "27. Corps"
    location = 331
    division =
    { id       = { type = 30007 id = 53 }
      name     = "27th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 54 }
    name     = "28. Corps"
    location = 332
    division =
    { id       = { type = 30007 id = 55 }
      name     = "28th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 56 }
    name     = "29. Corps"
    location = 336
    division =
    { id       = { type = 30007 id = 57 }
      name     = "29th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 58 }
    name     = "30. Corps"
    location = 345
    division =
    { id       = { type = 30007 id = 59 }
      name     = "30th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 60 }
    name     = "31. Corps"
    location = 346
    division =
    { id       = { type = 30007 id = 61 }
      name     = "31st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 62 }
    name     = "32. Corps"
    location = 347
    division =
    { id       = { type = 30007 id = 63 }
      name     = "32nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 64 }
    name     = "33. Corps"
    location = 352
    division =
    { id       = { type = 30007 id = 65 }
      name     = "33rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 66 }
    name     = "34. Corps"
    location = 354
    division =
    { id       = { type = 30007 id = 67 }
      name     = "34th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 68 }
    name     = "35. Corps"
    location = 356
    division =
    { id       = { type = 30007 id = 69 }
      name     = "35th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 70 }
    name     = "36. Corps"
    location = 357
    division =
    { id       = { type = 30007 id = 71 }
      name     = "36th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 72 }
    name     = "37. Corps"
    location = 358
    division =
    { id       = { type = 30007 id = 73 }
      name     = "37th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 74 }
    name     = "38. Corps"
    location = 362
    division =
    { id       = { type = 30007 id = 75 }
      name     = "38th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 76 }
    name     = "39. Corps"
    location = 364
    division =
    { id       = { type = 30007 id = 77 }
      name     = "39th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 78 }
    name     = "40. Corps"
    location = 365
    division =
    { id       = { type = 30007 id = 79 }
      name     = "40th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 80 }
    name     = "41. Corps"
    location = 366
    division =
    { id       = { type = 30007 id = 81 }
      name     = "41st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 82 }
    name     = "42. Corps"
    location = 527
    division =
    { id       = { type = 30007 id = 83 }
      name     = "42nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 84 }
    name     = "43. Corps"
    location = 529
    division =
    { id       = { type = 30007 id = 85 }
      name     = "43rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 86 }
    name     = "44. Corps"
    location = 316
    division =
    { id       = { type = 30007 id = 87 }
      name     = "44th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 88 }
    name     = "45. Corps"
    location = 73
    division =
    { id       = { type = 30007 id = 89 }
      name     = "45th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 90 }
    name     = "46. Corps"
    location = 72
    division =
    { id       = { type = 30007 id = 91 }
      name     = "46th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 92 }
    name     = "47. Corps"
    location = 64
    division =
    { id       = { type = 30007 id = 93 }
      name     = "47th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 94 }
    name     = "48. Corps"
    location = 53
    division =
    { id       = { type = 30007 id = 95 }
      name     = "48th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 96 }
    name     = "49. Corps"
    location = 44
    division =
    { id       = { type = 30007 id = 97 }
      name     = "49th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 98 }
    name     = "50. Corps"
    location = 43
    division =
    { id       = { type = 30007 id = 99 }
      name     = "50th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 100 }
    name     = "51. Corps"
    location = 18
    division =
    { id       = { type = 30007 id = 101 }
      name     = "51st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 102 }
    name     = "52. Corps"
    location = 42
    division =
    { id       = { type = 30007 id = 103 }
      name     = "52nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 104 }
    name     = "53. Corps"
    location = 41
    division =
    { id       = { type = 30007 id = 105 }
      name     = "53rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 106 }
    name     = "54. Corps"
    location = 39
    division =
    { id       = { type = 30007 id = 107 }
      name     = "54th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 108 }
    name     = "55. Corps"
    location = 33
    division =
    { id       = { type = 30007 id = 109 }
      name     = "55th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 110 }
    name     = "56. Corps"
    location = 32
    division =
    { id       = { type = 30007 id = 111 }
      name     = "56th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 112 }
    name     = "57. Corps"
    location = 34
    division =
    { id       = { type = 30007 id = 113 }
      name     = "57th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 114 }
    name     = "58. Corps"
    location = 35
    division =
    { id       = { type = 30007 id = 115 }
      name     = "58th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 116 }
    name     = "59. Corps"
    location = 59
    division =
    { id       = { type = 30007 id = 117 }
      name     = "59th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 118 }
    name     = "60. Corps"
    location = 325
    division =
    { id       = { type = 30007 id = 119 }
      name     = "60th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 120 }
    name     = "61. Corps"
    location = 326
    division =
    { id       = { type = 30007 id = 121 }
      name     = "61st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30007 id = 218 }
    name     = "Armored Corps"
    location = 56
    division =
    { type  = armor
      model = 0
      id    = { type = 30007 id = 219 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30007 id = 220 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30007 id = 221 }
      name  = "3rd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30007 id = 222 }
      name  = "4th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30007 id = 223 }
      name  = "5th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30007 id = 224 }
      name  = "6th Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30007 id = 193 }
    name     = "Main Fleet"
    location = 32
    base     = 32
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30007 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30007 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30007 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30007 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30007 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30007 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30007 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30007 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30007 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30007 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30007 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30007 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30007 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30007 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30007 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30007 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30007 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30007 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30007 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30007 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30007 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30007 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30007 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30007 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30007 id = 173 }
    name     = "Bomber Group 1"
    location = 56
    base     = 56
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30007 id = 178 }
    name     = "Bomber Group 2"
    location = 56
    base     = 56
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30007 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30007 id = 183 }
    name     = "Fighter Group 1"
    location = 56
    base     = 56
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30007 id = 188 }
    name     = "Fighter Group 2"
    location = 56
    base     = 56
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30007 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
