
##############################
# Country definition for URO #
##############################

province = { id = 367 infra = 0.2 } # Corsica
province =
{ id         = 368
  landfort   = 5
  anti_air   = 3
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Genoa
province =
{ id         = 369
  anti_air   = 3
  naval_base = { size = 10 current_size = 10 }
}              # La Spezia
province =
{ id       = 370
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # Milan
province =
{ id         = 378
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Venice
province = { id = 381 ic = 5 } # Rijeka
province = { id = 382 ic = 5 anti_air = 1 } # Zagreb
province = { id = 383 infra = 0.1 ic = 5 } # Banja Luka
province = { id = 384 infra = 0.1 ic = 5 anti_air = 1 } # Split
province = { id = 385 infra = 0.1 ic = 5 } # Zenica
province = { id = 386 infra = 0.1 } # Sarajevo
province = { id = 387 infra = 0.2 } # Mostar
province = { id = 388 rare_materials = 10 oil = 15 air_base = 6 naval_base = 1 anti_air = 3 } # Dubrovnik
province = { id = 389 infra = 0.2 } # Podgorica
province = { id = 426 infra = 0.2 } # Craiova
province = { id = 427 infra = 0.2 } # Sibiu
province = { id = 451 infra = 0.1 } # Novi Pazar
province = { id = 452 infra = 0.1 } # Uzice
province = { id = 453 anti_air = 2 } # Belgrade
province = { id = 457 anti_air = 2 } # Budapest
province = { id = 460 air_base = 5 anti_air = 2 } # Graz
province = { id = 463 anti_air = 1 } # Vienna
province = { id = 496 air_base = 8 anti_air = 2 } # Arad
province = { id = 512 anti_air = 1 } # Bologna
province = { id = 513 anti_air = 1 } # Florence
province =
{ id       = 515
  ic       = 5
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Rome
province = { id = 516 energy = 31 rare_materials = 10 } # Perugia
province = { id = 518 infra = 0.2 ic = 5 energy = 16 metal = 6 rare_materials = 1 oil = 25 } # Cassino
province =
{ id       = 521
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # Naples
province = { id = 522 ic = 5 energy = 20 metal = 5 rare_materials = 5 oil = 10 } # Potenza
province =
{ id         = 523
  infra      = 0.2
  anti_air   = 1
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  energy     = 20
  oil        = 15
}              # Taranto
province = { id = 524 infra = 0.2 energy = 16 metal = 5 oil = 10 } # Reggio di Calabria
province =
{ id             = 525
  infra          = 0.2
  anti_air       = 2
  naval_base     = { size = 10 current_size = 10 }
  air_base       = { size = 10 current_size = 10 }
  energy         = 27
  rare_materials = 9
  oil            = 20
}                  # Palermo
province = { id = 526 infra = 0.2 energy = 20 rare_materials = 5 oil = 25 } # Catania
province = { id = 531 landfort = 5 anti_air = 3 } # Turin
province =
{ id         = 534
  infra      = 0.2
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Sardinia
province = { id = 916 infra = 0.2 } # Bardia
province = { id = 917 infra = 0.4 } # Forte Capuzzo
province = { id = 918 infra = 0.6 } # Forte Maddalena
province =
{ id         = 919
  infra      = 0.2
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
  landfort   = 3
}              # Tobruk
province = { id = 920 infra = 0.4 } # Derna
province = { id = 921 infra = 0.4 oil = 10 } # Mechili
province = { id = 922 infra = 0.4 oil = 6 } # Msus
province = { id = 923 infra = 0.2 } # Barca
province =
{ id         = 924
  infra      = 0.2
  anti_air   = 1
  ic         = 2
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 4 current_size = 4 }
}              # Bengazi
province = { id = 925 infra = 0.4 ic = 2 } # Agedabia
province = { id = 926 infra = 0.6 } # Al Jaghbub
province = { id = 927 infra = 0.6 air_base = 7 anti_air = 2 } # Aujila
province = { id = 928 infra = 0.6 } # Socna
province = { id = 929 infra = 0.4 ic = 2 } # Sirte
province = { id = 930 infra = 0.4 ic = 2 } # Homs
province = { id = 931 infra = 0.6 } # Ghadames
province =
{ id         = 932
  infra      = 0.2
  ic         = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  oilpool    = 100
  supplypool = 500
  anti_air   = 4
}              # Tripoli
province = { id = 933 infra = 0.4 ic = 2 } # Zuara
province = { id = 934 infra = 0.6 } # Gafsa
province = { id = 935 infra = 0.4 ic = 2 } # Gabès
province = { id = 936 infra = 0.2 } # Sfax
province = { id = 937 infra = 0.4 } # Kassarine
province = { id = 938 infra = 0.2 } # Sousse
province =
{ id         = 939
  infra      = 0.2
  air_base   = { size = 4 current_size = 2 }
  naval_base = 4
  anti_air   = 2
}              # Tunis
province = { id = 940 infra = 0.2 } # Bizerte
province = { id = 941 infra = 0.2 } # Tabarka
province = { id = 1015 infra = 0.8 } # Ghat
province = { id = 1016 infra = 0.8 } # Murzuk
province = { id = 1017 infra = 0.8 } # Calansho Sand Sea
province = { id = 1018 infra = 0.8 } # Kufra

#####################
# Country main data #
#####################

country =
{ tag                    = URO
  ai                     = "globalwar/ITA.ai"
  manpower               = 460
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 50
  belligerence           = 0
  capital                = 515
  transports             = 100
  escorts                = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 10
    freedom           = 6
    free_market       = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  nationalprovinces      = { 525  526  524  523  522  521  520  519  518  517  516  515  513  514  512  379  369  368  531  370  371  378  534  31
			     927  933  932  930  929  925  924  923  922  921  920  919  916  917  918  926  928  931  1017 1018 1016 1015 532  367
			     530  533  372  373  377  460  461  462  463  464  465  380  459  455  454  453  382  381  383  384  385  386  387  388
			     389  451  452  418  493  494  935  934  936  938  937  939  940  941  456  457  458  491  492  497  426  495  496  498
			     427  428  366  527  529  316  315  374  376  375  466  467  475  476  477  490  499  429  430  425  424  420  419  417
			     415  390  915  913  1020 1019 1067 1081 1082 1083 1014 1013 943  942
			   }
  ownedprovinces         = { 525  526  524  523  522  521  520  519  518  517  516  515  513  514  512  379  369  368  531  370  371  378  534  31
			     927  933  932  930  929  925  924  923  922  921  920  919  916  917  918  926  928  931  1017 1018 1016 1015 532  367
			     530  533  372  373  377  460  461  462  463  464  465  380  459  455  454  453  382  381  383  384  385  386  387  388
			     389  451  452  418  493  494  935  934  936  938  937  939  940  941  456  457  458  491  492  497  426  495  496  498
			     427  428
			   }
  controlledprovinces    = { 525  526  524  523  522  521  520  519  518  517  516  515  513  514  512  379  369  368  531  370  371  378  534  31
			     927  933  932  930  929  925  924  923  922  921  920  919  916  917  918  926  928  931  1017 1018 1016 1015 532  367
			     530  533  372  373  377  460  461  462  463  464  465  380  459  455  454  453  382  381  383  384  385  386  387  388
			     389  451  452  418  493  494  935  934  936  938  937  939  940  941  456  457  458  491  492  497  426  495  496  498
			     427  428
			   }

  techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5010 5080 8010 8020 8030 8040 8050 9010 }

  diplomacy              = { }

  landunit =
  { id       = { type = 30004 id = 1 }
    name     = "1. Corps"
    location = 941
    division =
    { id       = { type = 30004 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 3 }
    name     = "2. Corps"
    location = 940
    division =
    { id       = { type = 30004 id = 4 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 5 }
    name     = "3. Corps"
    location = 939
    division =
    { id       = { type = 30004 id = 6 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 7 }
    name     = "4. Corps"
    location = 938
    division =
    { id       = { type = 30004 id = 8 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 9 }
    name     = "5. Corps"
    location = 937
    division =
    { id       = { type = 30004 id = 10 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 11 }
    name     = "6. Corps"
    location = 934
    division =
    { id       = { type = 30004 id = 12 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 13 }
    name     = "7. Corps"
    location = 933
    division =
    { id       = { type = 30004 id = 14 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 15 }
    name     = "8. Corps"
    location = 932
    division =
    { id       = { type = 30004 id = 16 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 17 }
    name     = "9. Corps"
    location = 924
    division =
    { id       = { type = 30004 id = 18 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 19 }
    name     = "10. Corps"
    location = 919
    division =
    { id       = { type = 30004 id = 20 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 21 }
    name     = "11. Corps"
    location = 916
    division =
    { id       = { type = 30004 id = 22 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 23 }
    name     = "12. Corps"
    location = 917
    division =
    { id       = { type = 30004 id = 24 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 25 }
    name     = "13. Corps"
    location = 918
    division =
    { id       = { type = 30004 id = 26 }
      name     = "13th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 27 }
    name     = "14. Corps"
    location = 926
    division =
    { id       = { type = 30004 id = 28 }
      name     = "14th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 29 }
    name     = "15. Corps"
    location = 1017
    division =
    { id       = { type = 30004 id = 30 }
      name     = "15th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 31 }
    name     = "16. Corps"
    location = 1018
    division =
    { id       = { type = 30004 id = 32 }
      name     = "16th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 33 }
    name     = "17. Corps"
    location = 1016
    division =
    { id       = { type = 30004 id = 34 }
      name     = "17th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 35 }
    name     = "18. Corps"
    location = 1015
    division =
    { id       = { type = 30004 id = 170 }
      name     = "18th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 36 }
    name     = "19. Corps"
    location = 931
    division =
    { id       = { type = 30004 id = 37 }
      name     = "19th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 38 }
    name     = "20. Corps"
    location = 31
    division =
    { id       = { type = 30004 id = 39 }
      name     = "20th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 40 }
    name     = "21. Corps"
    location = 367
    division =
    { id       = { type = 30004 id = 41 }
      name     = "21st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 42 }
    name     = "22. Corps"
    location = 534
    division =
    { id       = { type = 30004 id = 43 }
      name     = "22nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 44 }
    name     = "23. Corps"
    location = 526
    division =
    { id       = { type = 30004 id = 45 }
      name     = "23rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 46 }
    name     = "24. Corps"
    location = 525
    division =
    { id       = { type = 30004 id = 47 }
      name     = "24th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 48 }
    name     = "25. Corps"
    location = 523
    division =
    { id       = { type = 30004 id = 49 }
      name     = "25th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 50 }
    name     = "26. Corps"
    location = 520
    division =
    { id       = { type = 30004 id = 51 }
      name     = "26th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 52 }
    name     = "27. Corps"
    location = 521
    division =
    { id       = { type = 30004 id = 53 }
      name     = "27th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 54 }
    name     = "28. Corps"
    location = 516
    division =
    { id       = { type = 30004 id = 55 }
      name     = "28th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 56 }
    name     = "29. Corps"
    location = 514
    division =
    { id       = { type = 30004 id = 57 }
      name     = "29th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 58 }
    name     = "30. Corps"
    location = 513
    division =
    { id       = { type = 30004 id = 59 }
      name     = "30th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 60 }
    name     = "31. Corps"
    location = 384
    division =
    { id       = { type = 30004 id = 61 }
      name     = "31st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 62 }
    name     = "32. Corps"
    location = 388
    division =
    { id       = { type = 30004 id = 63 }
      name     = "32nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 64 }
    name     = "33. Corps"
    location = 368
    division =
    { id       = { type = 30004 id = 65 }
      name     = "33rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 66 }
    name     = "34. Corps"
    location = 531
    division =
    { id       = { type = 30004 id = 67 }
      name     = "34th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 68 }
    name     = "35. Corps"
    location = 532
    division =
    { id       = { type = 30004 id = 69 }
      name     = "35th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 70 }
    name     = "36. Corps"
    location = 530
    division =
    { id       = { type = 30004 id = 71 }
      name     = "36th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 72 }
    name     = "37. Corps"
    location = 533
    division =
    { id       = { type = 30004 id = 73 }
      name     = "37th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 74 }
    name     = "38. Corps"
    location = 373
    division =
    { id       = { type = 30004 id = 75 }
      name     = "38th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 76 }
    name     = "39. Corps"
    location = 377
    division =
    { id       = { type = 30004 id = 77 }
      name     = "39th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 78 }
    name     = "40. Corps"
    location = 462
    division =
    { id       = { type = 30004 id = 79 }
      name     = "40th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 80 }
    name     = "41. Corps"
    location = 465
    division =
    { id       = { type = 30004 id = 81 }
      name     = "41st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 82 }
    name     = "42. Corps"
    location = 464
    division =
    { id       = { type = 30004 id = 83 }
      name     = "42nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 84 }
    name     = "43. Corps"
    location = 463
    division =
    { id       = { type = 30004 id = 85 }
      name     = "43rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 86 }
    name     = "44. Corps"
    location = 458
    division =
    { id       = { type = 30004 id = 87 }
      name     = "44th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 88 }
    name     = "45. Corps"
    location = 457
    division =
    { id       = { type = 30004 id = 89 }
      name     = "45th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 90 }
    name     = "46. Corps"
    location = 491
    division =
    { id       = { type = 30004 id = 91 }
      name     = "46th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 92 }
    name     = "47. Corps"
    location = 497
    division =
    { id       = { type = 30004 id = 93 }
      name     = "47th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 94 }
    name     = "48. Corps"
    location = 498
    division =
    { id       = { type = 30004 id = 95 }
      name     = "48th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 96 }
    name     = "49. Corps"
    location = 428
    division =
    { id       = { type = 30004 id = 97 }
      name     = "49th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 98 }
    name     = "50. Corps"
    location = 427
    division =
    { id       = { type = 30004 id = 99 }
      name     = "50th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 100 }
    name     = "51. Corps"
    location = 426
    division =
    { id       = { type = 30004 id = 101 }
      name     = "51st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 102 }
    name     = "52. Corps"
    location = 418
    division =
    { id       = { type = 30004 id = 103 }
      name     = "52nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 104 }
    name     = "53. Corps"
    location = 451
    division =
    { id       = { type = 30004 id = 105 }
      name     = "53rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 106 }
    name     = "54. Corps"
    location = 519
    division =
    { id       = { type = 30004 id = 107 }
      name     = "54rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30004 id = 218 }
    name     = "Armored Corps"
    location = 515
    division =
    { type  = armor
      model = 0
      id    = { type = 30004 id = 219 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30004 id = 220 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30004 id = 221 }
      name  = "3rd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30004 id = 222 }
      name  = "4th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30004 id = 223 }
      name  = "5th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30004 id = 224 }
      name  = "6th Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30004 id = 193 }
    name     = "Main Fleet"
    location = 369
    base     = 369
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30004 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30004 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30004 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30004 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30004 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30004 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30004 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30004 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30004 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30004 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30004 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30004 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30004 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30004 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30004 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30004 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30004 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30004 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30004 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30004 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30004 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30004 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30004 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30004 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30004 id = 173 }
    name     = "Bomber Group 1"
    location = 515
    base     = 515
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30004 id = 178 }
    name     = "Bomber Group 2"
    location = 515
    base     = 515
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30004 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30004 id = 183 }
    name     = "Fighter Group 1"
    location = 515
    base     = 515
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30004 id = 188 }
    name     = "Fighter Group 2"
    location = 515
    base     = 515
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30004 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
