
##############################
# Country definition for MEX #
##############################

province = { id = 539 infra = 0.2 } # Managua
province = { id = 540 infra = 0.2 } # San José
province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province = { id = 642 metal = 0 max_metal = 0 } # Nashville
province = { id = 643 infra = 0.2 } # Asheville
province =
{ id        = 644
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 0
  max_metal = 0
}             # Charleston
province = { id = 645 metal = 0 max_metal = 0 } # Columbia
Province =
{ id                 = 648
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  rare_materials     = 0
  max_rare_materials = 0
  energy             = 11
}                      # Jacksonville
province = { id = 649 rare_materials = 0 max_rare_materials = 0 } # Tampa
province =
{ id                 = 651
  anti_air           = 1
  air_base           = { size = 10 current_size = 10 }
  Naval_base         = { size = 10 current_size = 10 }
  rare_materials     = 0
  max_rare_materials = 0
}                      # Miami
province =
{ id       = 652
  infra    = 0.2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic       = 1
}            # Andros
province = { id = 653 infra = 0.2 } # New Providence
province = { id = 654 infra = 0.2 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Havana
province = { id = 655 infra = 0.2 metal = 0 max_metal = 0 } # Santa Clara
province = { id = 656 infra = 0.2 ic = 12 } # Camagüey
province = { id = 657 infra = 0.2 } # Guantánamo
province = { id = 664 infra = 0.2 ic = 2 } # Grand Bahama
province = { id = 665 infra = 0.2 ic = 2 } # The Abacos
province = { id = 666 infra = 0.2 } # Eleuthera
province = { id = 668 infra = 0.2 } # Long Island
province = { id = 669 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Augusta
province =
{ id                 = 670
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  metal              = 0
  max_metal          = 0
  rare_materials     = 0
  max_rare_materials = 0
}                      # Atlanta
province = { id = 671 infra = 0.2 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Chattanooga
province = { id = 672 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Birmingham
province =
{ id                 = 673
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  metal              = 0
  max_metal          = 0
  rare_materials     = 0
  max_rare_materials = 0
}                      # Memphis
province = { id = 675 metal = 0 max_metal = 0 oil = 0 max_oil = 0 } # Jackson
province = { id = 676 metal = 0 max_metal = 0 rare_materials = 0 max_rare_materials = 0 } # Mobile
province = { id = 677 rare_materials = 0 max_rare_materials = 0 } # Tallahassee
province =
{ id        = 678
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 0
  max_metal = 0
}             # Biloxi
province = { id = 679 metal = 0 max_metal = 0 } # Baton Rouge
province = { id = 680 metal = 0 max_metal = 0 } # New Orleans
province = { id = 682 oil = 0 max_oil = 0 } # Monroe
province =
{ id        = 684
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 4
  max_metal = 4
}             # Little Rock
Province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  oil      = 0
  max_oil  = 0
}            # Oklahoma City
province = { id = 715 rare_materials = 0 max_rare_materials = 0 oil = 0 max_oil = 0 } # Dallas
province =
{ id                 = 716
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  rare_materials     = 49
  max_rare_materials = 49
  oil                = 0
  max_oil            = 0
}                      # Houston
province = { id = 718 infra = 0.2 } # El Paso
province = { id = 721 oil = 0 max_oil = 0 } # Lubbock
province = { id = 722 infra = 0.2 oil = 0 max_oil = 0 } # Roswell
province = { id = 723 infra = 0.2 } # Las Cruces
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province = { id = 726 infra = 0.2 oil = 0 max_oil = 0 } # Los Alamos
province = { id = 727 infra = 0.2 } # Silver City
province = { id = 737 infra = 0.2 } # Mexicali
province = { id = 738 infra = 0.2 } # La Paz
province = { id = 739 infra = 0.2 } # Hermosillo
province = { id = 740 infra = 0.2 } # Nogales
province = { id = 741 infra = 0.2 } # Ciudad Juárez
province = { id = 742 infra = 0.2 air_base = 5 anti_air = 3 } # Chihuahua
province = { id = 743 infra = 0.2 naval_base = 3 anti_air = 2 } # Culiacán
province = { id = 744 infra = 0.2 } # Durango
province = { id = 745 infra = 0.2 } # Monclova
province = { id = 747 infra = 0.2 anti_air = 1 } # Monterrey
Province =
{ id         = 748
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 8 current_size = 8 }
  anti_air   = 3
}              # Corpus Christi
province = { id = 749 infra = 0.2 oil = 0 max_oil = 0 } # Tampico
province = { id = 750 infra = 0.2 energy = 19 } # León
province = { id = 751 infra = 0.2 anti_air = 1 } # Guadalajara
province = { id = 752 infra = 0.2 anti_air = 2 energy = 24 } # Mexico City
province = { id = 753 infra = 0.2 } # Puebla
province =
{ id         = 754
  infra      = 0.2
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # Acapulco
province = { id = 755 infra = 0.2 oil = 0 max_oil = 0 } # Villahermosa
province = { id = 756 infra = 0.2 } # Mérida
province =
{ id         = 757
  infra      = 0.2
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Guatemala
province = { id = 758 infra = 0.2 } # Belize City
province = { id = 759 infra = 0.2 } # San Salvador
province = { id = 760 infra = 0.2 } # Tegucigalpa
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  oil      = 3
  max_oil  = 3
}            # Tulsa
province = { id = 801 infra = 0.2 } # Curacao
province = { id = 802 infra = 0.2 naval_base = 3 air_base = 3 anti_air = 1 } # Barquisimeto
province = { id = 803 infra = 0.2 } # Barranquilla
province = { id = 804 infra = 0.2 } # Maracaibo
province = { id = 805 infra = 0.2 ic = 2 } # St. Lucia
province = { id = 806 infra = 0.2 ic = 2 } # St. George's
province = { id = 807 infra = 0.2 ic = 2 naval_base = 2 air_base = 2 anti_air = 1 } # Barbados
province = { id = 808 infra = 0.2 ic = 2 } # Tobago
province = { id = 809 infra = 0.2 ic = 2 oil = 0 max_oil = 0 } # Trinidad
province = { id = 810 infra = 0.2 } # Cumaná
province = { id = 811 infra = 0.2 } # Caracas
province = { id = 812 infra = 0.4 } # Cúcuta
province = { id = 813 infra = 0.2 air_base = 8 anti_air = 3 } # Bogotá
province = { id = 814 infra = 0.2 } # Guayaquil
province = { id = 815 infra = 0.2 } # Quito
province = { id = 817 infra = 0.4 } # Tigre
province = { id = 818 infra = 0.6 } # Iquitos
province = { id = 819 infra = 0.6 } # Mitú
province = { id = 867 infra = 0.4 } # Angostura Falls
province = { id = 868 infra = 0.6 } # Inirida
province = { id = 869 infra = 0.4 } # Ciudad Bolivar
province = { id = 870 infra = 0.2 } # Ciudad Guayana
province = { id = 888 infra = 0.2 } # Panamá
province =
{ id         = 889
  infra      = 0.2
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
}              # Colon
province = { id = 890 infra = 0.2 } # Medellín
province = { id = 891 infra = 0.2 ic = 2 } # Jamaica
province = { id = 892 infra = 0.2 naval_base = 4 air_base = 4 anti_air = 3 } # Port-au-Prince
province = { id = 893 infra = 0.2 } # Santiago
province = { id = 894 infra = 0.2 } # Santo Domingo
province = { id = 895 infra = 0.2 } # Puerto Rico
province = { id = 896 infra = 0.2 ic = 2 } # Virgin Islands
province = { id = 897 infra = 0.2 ic = 2 } # Antigua
province = { id = 898 infra = 0.2 ic = 2 } # Guadelope
province = { id = 899 infra = 0.2 ic = 2 } # Martinique

#####################
# Country main data #
#####################

country =
{ tag                    = UCS
  ai                     = "globalwar/MEX.ai"
  belligerence           = 0
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  capital                = 752
  manpower               = 100
  transports             = 100
  escorts                = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 1
    freedom           = 6
    free_market       = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  ownedprovinces         = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 814 815 817 818 718 746 717 721 720 719 715 716
			     748 722 723 724 725 726 727 712 713 714 793 680 681 682 683 684 685 686 670 671 672 673 674 675 676 677 678 679 669 634
			     635 636 637 642 643 644 645 646 647 648 649 650 651 895 889 652 653 664 665 666 668 758 805 806 807 808 809 891 896 897
			     801 804 802 810 811 869 870 654 655 656 657 757 539 540 759 760 803 812 813 890 867 819 868 888 892 893 894 898 899
			   }
  controlledprovinces    = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 814 815 817 818 718 746 717 721 720 719 715 716
			     748 722 723 724 725 726 727 712 713 714 793 680 681 682 683 684 685 686 670 671 672 673 674 675 676 677 678 679 669 634
			     635 636 637 642 643 644 645 646 647 648 649 650 651 895 889 652 653 664 665 666 668 758 805 806 807 808 809 891 896 897
			     801 804 802 810 811 869 870 654 655 656 657 757 539 540 759 760 803 812 813 890 867 819 868 888 892 893 894 898 899
			   }
  # Semi-Major Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5010 5080 8010 8020 8030 8040 8050 9010 }
  nationalprovinces      = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 814 815 817 818 718 746 717 721 720 719 715 716
			     748 722 723 724 725 726 727 712 713 714 793 680 681 682 683 684 685 686 670 671 672 673 674 675 676 677 678 679 669 634
			     635 636 637 642 643 644 645 646 647 648 649 650 651 895 889 652 653 664 665 666 668 758 805 806 807 808 809 891 896 897
			     801 804 802 810 811 869 870 654 655 656 657 757 539 540 759 760 803 812 813 890 867 819 868 888 892 893 894 898 899 633
			     632 638 639 640 641 687 688 792 711 710 709 708 728 729 736 761 816 821 820 872 871
			   }

  # Firepower
  landunit =
  { id       = { type = 30002 id = 1 }
    name     = "1. Corps"
    location = 809
    division =
    { id       = { type = 30002 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 3 }
    name     = "2. Corps"
    location = 808
    division =
    { id       = { type = 30002 id = 4 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 5 }
    name     = "3. Corps"
    location = 656
    division =
    { id       = { type = 30002 id = 6 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 7 }
    name     = "4. Corps"
    location = 657
    division =
    { id       = { type = 30002 id = 8 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 9 }
    name     = "5. Corps"
    location = 891
    division =
    { id       = { type = 30002 id = 10 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 11 }
    name     = "6. Corps"
    location = 892
    division =
    { id       = { type = 30002 id = 12 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 13 }
    name     = "7. Corps"
    location = 893
    division =
    { id       = { type = 30002 id = 14 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 15 }
    name     = "8. Corps"
    location = 894
    division =
    { id       = { type = 30002 id = 16 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 17 }
    name     = "9. Corps"
    location = 801
    division =
    { id       = { type = 30002 id = 18 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 19 }
    name     = "10. Corps"
    location = 895
    division =
    { id       = { type = 30002 id = 20 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 21 }
    name     = "11. Corps"
    location = 896
    division =
    { id       = { type = 30002 id = 22 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 23 }
    name     = "12. Corps"
    location = 897
    division =
    { id       = { type = 30002 id = 24 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 25 }
    name     = "13. Corps"
    location = 898
    division =
    { id       = { type = 30002 id = 26 }
      name     = "13th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 27 }
    name     = "14. Corps"
    location = 899
    division =
    { id       = { type = 30002 id = 28 }
      name     = "14th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 29 }
    name     = "15. Corps"
    location = 805
    division =
    { id       = { type = 30002 id = 30 }
      name     = "15th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 31 }
    name     = "16. Corps"
    location = 806
    division =
    { id       = { type = 30002 id = 32 }
      name     = "16th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 33 }
    name     = "17. Corps"
    location = 807
    division =
    { id       = { type = 30002 id = 34 }
      name     = "17th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 35 }
    name     = "18. Corps"
    location = 814
    division =
    { id       = { type = 30002 id = 170 }
      name     = "18th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 36 }
    name     = "19. Corps"
    location = 815
    division =
    { id       = { type = 30002 id = 37 }
      name     = "19th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 38 }
    name     = "20. Corps"
    location = 818
    division =
    { id       = { type = 30002 id = 39 }
      name     = "20th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 40 }
    name     = "21. Corps"
    location = 819
    division =
    { id       = { type = 30002 id = 41 }
      name     = "21st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 42 }
    name     = "22. Corps"
    location = 868
    division =
    { id       = { type = 30002 id = 43 }
      name     = "22nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 44 }
    name     = "23. Corps"
    location = 869
    division =
    { id       = { type = 30002 id = 45 }
      name     = "23rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 46 }
    name     = "24. Corps"
    location = 870
    division =
    { id       = { type = 30002 id = 47 }
      name     = "24th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 48 }
    name     = "25. Corps"
    location = 810
    division =
    { id       = { type = 30002 id = 49 }
      name     = "25th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 50 }
    name     = "26. Corps"
    location = 811
    division =
    { id       = { type = 30002 id = 51 }
      name     = "26th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 52 }
    name     = "27. Corps"
    location = 802
    division =
    { id       = { type = 30002 id = 53 }
      name     = "27th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 54 }
    name     = "28. Corps"
    location = 804
    division =
    { id       = { type = 30002 id = 55 }
      name     = "28th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 56 }
    name     = "29. Corps"
    location = 803
    division =
    { id       = { type = 30002 id = 57 }
      name     = "29th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 58 }
    name     = "30. Corps"
    location = 890
    division =
    { id       = { type = 30002 id = 59 }
      name     = "30th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 60 }
    name     = "31. Corps"
    location = 889
    division =
    { id       = { type = 30002 id = 61 }
      name     = "31st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 62 }
    name     = "32. Corps"
    location = 888
    division =
    { id       = { type = 30002 id = 63 }
      name     = "32nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 64 }
    name     = "33. Corps"
    location = 540
    division =
    { id       = { type = 30002 id = 65 }
      name     = "33rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 66 }
    name     = "34. Corps"
    location = 539
    division =
    { id       = { type = 30002 id = 67 }
      name     = "34th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 68 }
    name     = "35. Corps"
    location = 760
    division =
    { id       = { type = 30002 id = 69 }
      name     = "35th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 70 }
    name     = "36. Corps"
    location = 759
    division =
    { id       = { type = 30002 id = 71 }
      name     = "36th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 72 }
    name     = "37. Corps"
    location = 757
    division =
    { id       = { type = 30002 id = 73 }
      name     = "37th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 74 }
    name     = "38. Corps"
    location = 758
    division =
    { id       = { type = 30002 id = 75 }
      name     = "38th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 76 }
    name     = "39. Corps"
    location = 756
    division =
    { id       = { type = 30002 id = 77 }
      name     = "39th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 78 }
    name     = "40. Corps"
    location = 755
    division =
    { id       = { type = 30002 id = 79 }
      name     = "40th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 80 }
    name     = "41. Corps"
    location = 754
    division =
    { id       = { type = 30002 id = 81 }
      name     = "41st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 82 }
    name     = "42. Corps"
    location = 753
    division =
    { id       = { type = 30002 id = 83 }
      name     = "42nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 84 }
    name     = "43. Corps"
    location = 751
    division =
    { id       = { type = 30002 id = 85 }
      name     = "43rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 86 }
    name     = "44. Corps"
    location = 749
    division =
    { id       = { type = 30002 id = 87 }
      name     = "44th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 88 }
    name     = "45. Corps"
    location = 743
    division =
    { id       = { type = 30002 id = 89 }
      name     = "45th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 90 }
    name     = "46. Corps"
    location = 738
    division =
    { id       = { type = 30002 id = 91 }
      name     = "46th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 92 }
    name     = "47. Corps"
    location = 737
    division =
    { id       = { type = 30002 id = 93 }
      name     = "47th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 94 }
    name     = "48. Corps"
    location = 739
    division =
    { id       = { type = 30002 id = 95 }
      name     = "48th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 96 }
    name     = "49. Corps"
    location = 740
    division =
    { id       = { type = 30002 id = 97 }
      name     = "49th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 98 }
    name     = "50. Corps"
    location = 727
    division =
    { id       = { type = 30002 id = 99 }
      name     = "50th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 100 }
    name     = "51. Corps"
    location = 726
    division =
    { id       = { type = 30002 id = 101 }
      name     = "51st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 102 }
    name     = "52. Corps"
    location = 725
    division =
    { id       = { type = 30002 id = 103 }
      name     = "52nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 104 }
    name     = "53. Corps"
    location = 724
    division =
    { id       = { type = 30002 id = 105 }
      name     = "53rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 106 }
    name     = "54. Corps"
    location = 712
    division =
    { id       = { type = 30002 id = 107 }
      name     = "54th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 108 }
    name     = "55. Corps"
    location = 793
    division =
    { id       = { type = 30002 id = 109 }
      name     = "55th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 110 }
    name     = "56. Corps"
    location = 686
    division =
    { id       = { type = 30002 id = 111 }
      name     = "56th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 112 }
    name     = "57. Corps"
    location = 685
    division =
    { id       = { type = 30002 id = 113 }
      name     = "57th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 114 }
    name     = "58. Corps"
    location = 673
    division =
    { id       = { type = 30002 id = 115 }
      name     = "58th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 116 }
    name     = "59. Corps"
    location = 642
    division =
    { id       = { type = 30002 id = 117 }
      name     = "59th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 118 }
    name     = "60. Corps"
    location = 643
    division =
    { id       = { type = 30002 id = 119 }
      name     = "60th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 120 }
    name     = "61. Corps"
    location = 637
    division =
    { id       = { type = 30002 id = 121 }
      name     = "61st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 122 }
    name     = "62. Corps"
    location = 636
    division =
    { id       = { type = 30002 id = 123 }
      name     = "62nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 124 }
    name     = "63. Corps"
    location = 634
    division =
    { id       = { type = 30002 id = 125 }
      name     = "63rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 126 }
    name     = "64. Corps"
    location = 644
    division =
    { id       = { type = 30002 id = 127 }
      name     = "64th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 128 }
    name     = "65. Corps"
    location = 646
    division =
    { id       = { type = 30002 id = 129 }
      name     = "65th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 130 }
    name     = "66. Corps"
    location = 648
    division =
    { id       = { type = 30002 id = 131 }
      name     = "66th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 132 }
    name     = "67. Corps"
    location = 650
    division =
    { id       = { type = 30002 id = 133 }
      name     = "67th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 134 }
    name     = "68. Corps"
    location = 651
    division =
    { id       = { type = 30002 id = 135 }
      name     = "68th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 136 }
    name     = "69. Corps"
    location = 649
    division =
    { id       = { type = 30002 id = 137 }
      name     = "69th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 138 }
    name     = "70. Corps"
    location = 677
    division =
    { id       = { type = 30002 id = 139 }
      name     = "70th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 140 }
    name     = "71. Corps"
    location = 676
    division =
    { id       = { type = 30002 id = 141 }
      name     = "71st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 142 }
    name     = "72 Corps"
    location = 678
    division =
    { id       = { type = 30002 id = 143 }
      name     = "72nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 144 }
    name     = "73. Corps"
    location = 679
    division =
    { id       = { type = 30002 id = 145 }
      name     = "73rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 146 }
    name     = "74. Corps"
    location = 716
    division =
    { id       = { type = 30002 id = 147 }
      name     = "74th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 148 }
    name     = "75. Corps"
    location = 748
    division =
    { id       = { type = 30002 id = 149 }
      name     = "75th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 150 }
    name     = "76. Corps"
    location = 664
    division =
    { id       = { type = 30002 id = 151 }
      name     = "76th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 152 }
    name     = "77. Corps"
    location = 665
    division =
    { id       = { type = 30002 id = 153 }
      name     = "77th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 154 }
    name     = "78. Corps"
    location = 653
    division =
    { id       = { type = 30002 id = 155 }
      name     = "78th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 156 }
    name     = "79. Corps"
    location = 652
    division =
    { id       = { type = 30002 id = 157 }
      name     = "79th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 158 }
    name     = "80. Corps"
    location = 666
    division =
    { id       = { type = 30002 id = 159 }
      name     = "80th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 160 }
    name     = "81. Corps"
    location = 668
    division =
    { id       = { type = 30002 id = 161 }
      name     = "81st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 162 }
    name     = "82. Corps"
    location = 654
    division =
    { id       = { type = 30002 id = 163 }
      name     = "82nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 164 }
    name     = "83. Corps"
    location = 655
    division =
    { id       = { type = 30002 id = 165 }
      name     = "83rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30002 id = 218 }
    name     = "Armored Corps"
    location = 752
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 219 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 220 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 221 }
      name  = "3rd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 222 }
      name  = "4th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 223 }
      name  = "5th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30002 id = 224 }
      name  = "6th Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30002 id = 193 }
    name     = "Main Fleet"
    location = 754
    base     = 754
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30002 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30002 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30002 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30002 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30002 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30002 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30002 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30002 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30002 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30002 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30002 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30002 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30002 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30002 id = 173 }
    name     = "Bomber Group 1"
    location = 754
    base     = 754
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30002 id = 178 }
    name     = "Bomber Group 2"
    location = 754
    base     = 754
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30002 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30002 id = 183 }
    name     = "Fighter Group 1"
    location = 754
    base     = 754
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30002 id = 188 }
    name     = "Fighter Group 2"
    location = 754
    base     = 754
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30002 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
