
##############################
# Country definition for UIC #
##############################

province = { id = 1287 infra = 0.4 } # Imphal
province = { id = 1288 infra = 0.2 } # Chittagong
province = { id = 1289 infra = 0.2 } # Akyab
province = { id = 1290 infra = 0.4 } # Kalewa
province = { id = 1291 infra = 0.4 } # Myitkyina
province = { id = 1292 infra = 0.4 } # Kunchaung
province = { id = 1295 infra = 0.6 } # Lashio
province = { id = 1296 infra = 0.4 ic = 10 energy = 30 metal = 10 oil = 20 anti_air = 1 } # Mandalay
province = { id = 1297 infra = 0.2 } # Arakan
province = { id = 1298 infra = 0.2 naval_base = 10 air_base = 3 anti_air = 2 } # Bassein
province = { id = 1299 infra = 0.2 ic = 10 energy = 41 metal = 11 oil = 20 anti_air = 2 } # Rangoon
province = { id = 1300 infra = 0.4 } # Prome
province = { id = 1301 infra = 0.4 ic = 10 air_base = 4 anti_air = 2 } # Toungoo
province = { id = 1302 infra = 0.2 } # Sittang
province = { id = 1303 infra = 0.4 ic = 10 energy = 30 anti_air = 1 } # Chiang Rai
province = { id = 1304 infra = 0.6 } # Shan States
province = { id = 1306 infra = 0.7 } # Luang Prabang
province = { id = 1326 infra = 0.2 } # Haiphong
province = { id = 1328 infra = 0.2 rare_materials = 0 max_rare_materials = 0 air_base = 3 naval_base = 4 anti_air = 2 } # Hanoi
province = { id = 1329 infra = 0.4 energy = 30 } # Vientiane
province = { id = 1330 infra = 0.4 ic = 10 air_base = 5 anti_air = 1 } # Phitsanulok
province = { id = 1331 infra = 0.4 ic = 10 anti_air = 1 } # Khon Kaen
province = { id = 1332 infra = 0.4 } # Nhommarath
province = { id = 1333 infra = 0.2 } # Da Nang
province = { id = 1334 infra = 0.2 } # Qui Non
province = { id = 1335 infra = 0.2 rare_materials = 0 max_rare_materials = 0 } # Nha Trang
province = { id = 1336 infra = 0.4 ic = 10 anti_air = 1 } # Pakse
province = { id = 1337 infra = 0.2 rare_materials = 0 max_rare_materials = 0 energy = 36 oil = 5 } # Saigon
province = { id = 1338 infra = 0.2 rare_materials = 0 max_rare_materials = 0 air_base = 1 naval_base = 2 anti_air = 1 } # Rach Gia
province = { id = 1339 infra = 0.2 rare_materials = 0 max_rare_materials = 0 } # Battambang
province = { id = 1340 infra = 0.4 ic = 10 rare_materials = 0 max_rare_materials = 0 energy = 31 anti_air = 1 } # Phnom Penh
province = { id = 1341 infra = 0.4 ic = 10 anti_air = 1 } # Ubon Ratchthani
province = { id = 1342 infra = 0.4 } # Nakhon Ratchthani
province = { id = 1343 infra = 0.2 ic = 18 rare_materials = 0 max_rare_materials = 0 energy = 41 anti_air = 3 } # Bangkok
province = { id = 1344 infra = 0.4 ic = 10 } # Nakhon Sawan
province =
{ id         = 1345
  infra      = 0.2
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
}              # Thom Buri
province = { id = 1346 infra = 0.2 } # Moulmein
province = { id = 1347 infra = 0.2 rare_materials = 0 max_rare_materials = 0 } # Kra
province = { id = 1348 infra = 0.2 rare_materials = 0 max_rare_materials = 0 } # Singora
province = { id = 1349 infra = 0.2 rare_materials = 0 max_rare_materials = 0 energy = 31 air_base = 5 anti_air = 2 } # Alor Star
province = { id = 1350 infra = 0.2 rare_materials = 0 max_rare_materials = 0 energy = 30 } # Kota Bahru
province = { id = 1351 infra = 0.2 rare_materials = 0 max_rare_materials = 0 energy = 30 oil = 20 } # Kuantan
province = { id = 1352 infra = 0.2 energy = 30 rare_materials = 0 max_rare_materials = 0 oil = 20 } # Kuala Lumpur
province =
{ id                 = 1353
  infra              = 0.2
  ic                 = 10
  rare_materials     = 8
  max_rare_materials = 8
  oil                = 28
  energy             = 31
  metal              = 21
  naval_base         = 5
  anti_air           = 2
}                      # Singapore
province = { id = 1354 infra = 0.2 } # Bangka Island
province = { id = 1355 infra = 0.4 naval_base = 1 air_base = 1 anti_air = 1 } # Medan
province = { id = 1356 infra = 0.2 } # Dumai
province = { id = 1357 infra = 0.4 } # Padang
province = { id = 1358 infra = 0.2 ic = 10 anti_air = 1 } # Palembang
province = { id = 1359 infra = 0.4 ic = 10 air_base = 8 anti_air = 2 } # Oosthaven
province = { id = 1518 infra = 0.4 } # Andaman Islands
province = { id = 1519 infra = 0.4 } # Nicobar Islands
province = { id = 1628 infra = 0.2 ic = 10 } # Batavia
province = { id = 1629 infra = 0.2 } # Tjilatjap
province = { id = 1630 infra = 0.2 naval_base = 7 air_base = 7 anti_air = 2 } # Semarang
province = { id = 1631 infra = 0.2 } # Djokjakarta
province = { id = 1632 infra = 0.2 } # Soerabaja
province = { id = 1633 infra = 0.2 } # Malang
province = { id = 1634 infra = 0.2 } # Madura
province = { id = 1635 infra = 0.2 ic = 10 air_base = 6 anti_air = 2 } # Bali
province = { id = 1636 infra = 0.2 } # Lombok
province = { id = 1637 infra = 0.4 } # Sumbawa
province = { id = 1638 infra = 0.4 } # Sumba

#####################
# Country main data #
#####################

country =
{ tag                    = UIC
  ai                     = "globalwar/SIA.ai"
  belligerence           = 0
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  capital                = 1343
  transports             = 100
  escorts                = 100
  manpower               = 1000
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 1
    freedom           = 6
    free_market       = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  ownedprovinces         = { 1348 1347 1345 1343 1342 1331 1330 1344 1303 1338 1339 1340 1337 1335 1349 1350 1351 1352 1353 1518 1519 1336 1334 1333
			     1332 1341 1329 1328 1306 1326 1346 1285 1286 1287 1288 1297 1354 1355 1356 1357 1358 1359 1289 1290 1291 1898 1304 1295
			     1296 1301 1302 1299 1298 1300 1292 1877 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638
			   }
  controlledprovinces    = { 1348 1347 1345 1343 1342 1331 1330 1344 1303 1338 1339 1340 1337 1335 1349 1350 1351 1352 1353 1518 1519 1336 1334 1333
			     1332 1341 1329 1328 1306 1326 1346 1285 1286 1287 1288 1297 1354 1355 1356 1357 1358 1359 1289 1290 1291 1898 1304 1295
			     1296 1301 1302 1299 1298 1300 1292 1877 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638
			   }
  # ROTW Minor Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5010 5080 8010 8020 8030 8040 8050 9010 }
  nationalprovinces      = { 1348 1347 1345 1343 1342 1331 1330 1344 1303 1338 1339 1340 1337 1335 1349 1350 1351 1352 1353 1518 1519 1336 1334 1333
			     1332 1341 1329 1328 1306 1326 1346 1285 1286 1287 1288 1297 1354 1355 1356 1357 1358 1359 1289 1290 1291 1898 1304 1295
			     1296 1301 1302 1299 1298 1300 1292 1877 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1657 1658 1652 1651
			     1640 1653 1641 1642 1643 1650 1325 1309 1327 1305 1294 1283
			   }

  landunit =
  { id       = { type = 30011 id = 1 }
    name     = "1. Corps"
    location = 1518
    division =
    { id       = { type = 30011 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 3 }
    name     = "2. Corps"
    location = 1519
    division =
    { id       = { type = 30011 id = 4 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 5 }
    name     = "3. Corps"
    location = 1638
    division =
    { id       = { type = 30011 id = 6 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 7 }
    name     = "4. Corps"
    location = 1637
    division =
    { id       = { type = 30011 id = 8 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 9 }
    name     = "5. Corps"
    location = 1636
    division =
    { id       = { type = 30011 id = 10 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 11 }
    name     = "6. Corps"
    location = 1635
    division =
    { id       = { type = 30011 id = 12 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 13 }
    name     = "7. Corps"
    location = 1633
    division =
    { id       = { type = 30011 id = 14 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 15 }
    name     = "8. Corps"
    location = 1634
    division =
    { id       = { type = 30011 id = 16 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 17 }
    name     = "9. Corps"
    location = 1632
    division =
    { id       = { type = 30011 id = 18 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 19 }
    name     = "10. Corps"
    location = 1631
    division =
    { id       = { type = 30011 id = 20 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 21 }
    name     = "11. Corps"
    location = 1630
    division =
    { id       = { type = 30011 id = 22 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 23 }
    name     = "12. Corps"
    location = 1629
    division =
    { id       = { type = 30011 id = 24 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 25 }
    name     = "13. Corps"
    location = 1628
    division =
    { id       = { type = 30011 id = 26 }
      name     = "13th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 27 }
    name     = "14. Corps"
    location = 1354
    division =
    { id       = { type = 30011 id = 28 }
      name     = "14th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 29 }
    name     = "15. Corps"
    location = 1358
    division =
    { id       = { type = 30011 id = 30 }
      name     = "15th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 31 }
    name     = "16. Corps"
    location = 1359
    division =
    { id       = { type = 30011 id = 32 }
      name     = "16th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 33 }
    name     = "17. Corps"
    location = 1357
    division =
    { id       = { type = 30011 id = 34 }
      name     = "17th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 35 }
    name     = "18. Corps"
    location = 1356
    division =
    { id       = { type = 30011 id = 170 }
      name     = "18th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 36 }
    name     = "19. Corps"
    location = 1355
    division =
    { id       = { type = 30011 id = 37 }
      name     = "19th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 38 }
    name     = "20. Corps"
    location = 1353
    division =
    { id       = { type = 30011 id = 39 }
      name     = "20th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 40 }
    name     = "21. Corps"
    location = 1352
    division =
    { id       = { type = 30011 id = 41 }
      name     = "21st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 42 }
    name     = "22. Corps"
    location = 1351
    division =
    { id       = { type = 30011 id = 43 }
      name     = "22nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 44 }
    name     = "23. Corps"
    location = 1350
    division =
    { id       = { type = 30011 id = 45 }
      name     = "23rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 46 }
    name     = "24. Corps"
    location = 1349
    division =
    { id       = { type = 30011 id = 47 }
      name     = "24th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 48 }
    name     = "25. Corps"
    location = 1348
    division =
    { id       = { type = 30011 id = 49 }
      name     = "25th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 50 }
    name     = "26. Corps"
    location = 1345
    division =
    { id       = { type = 30011 id = 51 }
      name     = "26th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 52 }
    name     = "27. Corps"
    location = 1343
    division =
    { id       = { type = 30011 id = 53 }
      name     = "27th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 54 }
    name     = "28. Corps"
    location = 1339
    division =
    { id       = { type = 30011 id = 55 }
      name     = "28th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 56 }
    name     = "29. Corps"
    location = 1338
    division =
    { id       = { type = 30011 id = 57 }
      name     = "29th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 58 }
    name     = "30. Corps"
    location = 1337
    division =
    { id       = { type = 30011 id = 59 }
      name     = "30th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 60 }
    name     = "31. Corps"
    location = 1335
    division =
    { id       = { type = 30011 id = 61 }
      name     = "31st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 62 }
    name     = "32. Corps"
    location = 1334
    division =
    { id       = { type = 30011 id = 63 }
      name     = "32nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 64 }
    name     = "33. Corps"
    location = 1333
    division =
    { id       = { type = 30011 id = 65 }
      name     = "33rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 66 }
    name     = "34. Corps"
    location = 1332
    division =
    { id       = { type = 30011 id = 67 }
      name     = "34th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 68 }
    name     = "35. Corps"
    location = 1328
    division =
    { id       = { type = 30011 id = 69 }
      name     = "35th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 70 }
    name     = "36. Corps"
    location = 1326
    division =
    { id       = { type = 30011 id = 71 }
      name     = "36th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 72 }
    name     = "37. Corps"
    location = 1306
    division =
    { id       = { type = 30011 id = 73 }
      name     = "37th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 74 }
    name     = "38. Corps"
    location = 1304
    division =
    { id       = { type = 30011 id = 75 }
      name     = "38th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 76 }
    name     = "39. Corps"
    location = 1295
    division =
    { id       = { type = 30011 id = 77 }
      name     = "39th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 78 }
    name     = "40. Corps"
    location = 1292
    division =
    { id       = { type = 30011 id = 79 }
      name     = "40th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 80 }
    name     = "41. Corps"
    location = 1898
    division =
    { id       = { type = 30011 id = 81 }
      name     = "41st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 82 }
    name     = "42. Corps"
    location = 1291
    division =
    { id       = { type = 30011 id = 83 }
      name     = "42nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 84 }
    name     = "43. Corps"
    location = 1877
    division =
    { id       = { type = 30011 id = 85 }
      name     = "43rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 86 }
    name     = "44. Corps"
    location = 1287
    division =
    { id       = { type = 30011 id = 87 }
      name     = "44th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 88 }
    name     = "45. Corps"
    location = 1286
    division =
    { id       = { type = 30011 id = 89 }
      name     = "45th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 90 }
    name     = "46. Corps"
    location = 1285
    division =
    { id       = { type = 30011 id = 91 }
      name     = "46th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 92 }
    name     = "47. Corps"
    location = 1288
    division =
    { id       = { type = 30011 id = 93 }
      name     = "47th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 94 }
    name     = "48. Corps"
    location = 1289
    division =
    { id       = { type = 30011 id = 95 }
      name     = "48th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 96 }
    name     = "49. Corps"
    location = 1297
    division =
    { id       = { type = 30011 id = 97 }
      name     = "49th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 98 }
    name     = "50. Corps"
    location = 1299
    division =
    { id       = { type = 30011 id = 99 }
      name     = "50th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 100 }
    name     = "51. Corps"
    location = 1302
    division =
    { id       = { type = 30011 id = 101 }
      name     = "51st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30011 id = 218 }
    name     = "Armored Corps"
    location = 1343
    division =
    { type  = armor
      model = 0
      id    = { type = 30011 id = 219 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30011 id = 220 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30011 id = 221 }
      name  = "3rd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30011 id = 222 }
      name  = "4th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30011 id = 223 }
      name  = "5th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30011 id = 224 }
      name  = "6th Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30011 id = 193 }
    name     = "Main Fleet"
    location = 1343
    base     = 1343
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30011 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30011 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30011 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30011 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30011 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30011 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30011 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30011 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30011 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30011 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30011 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30011 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30011 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30011 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30011 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30011 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30011 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30011 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30011 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30011 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30011 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30011 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30011 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30011 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30011 id = 173 }
    name     = "Bomber Group 1"
    location = 1343
    base     = 1343
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30011 id = 178 }
    name     = "Bomber Group 2"
    location = 1343
    base     = 1343
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30011 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30011 id = 183 }
    name     = "Fighter Group 1"
    location = 1343
    base     = 1343
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30011 id = 188 }
    name     = "Fighter Group 2"
    location = 1343
    base     = 1343
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30011 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
