
##############################
# Country definition for UTO #
##############################

province = { id = 4 infra = 0.6 } # As Suwayz
province = { id = 255 infra = 0.2 } # Novorossisk
province = { id = 390 infra = 0.2 } # Tirana
province = { id = 391 infra = 0.2 } # Vlorë
province = { id = 392 infra = 0.1 } # Ioannina
province = { id = 396 infra = 0.2 naval_base = 5 air_base = 3 anti_air = 2 } # Crete
province =
{ id       = 399
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # Rhodes
province = { id = 401 anti_air = 1 } # Athens
province = { id = 404 infra = 0.2 } # Haifa
province = { id = 406 infra = 0.4 } # Eilat
province = { id = 407 infra = 0.6 ic = 5 } # Ar-Ruwayshid
province = { id = 408 infra = 0.2 } # Bursa
province = { id = 409 infra = 0.2 ic = 6 anti_air = 2 } # Istanbul
province = { id = 412 infra = 0.1 ic = 5 energy = 20 metal = 10 rare_materials = 5 anti_air = 1 } # Edessa
province = { id = 413 infra = 0.2 } # Skopje
province = { id = 414 infra = 0.1 } # Stip
province = { id = 415 infra = 0.1 } # Pristina
province = { id = 416 infra = 0.2 } # Gorna Dzhumaya
province = { id = 417 infra = 0.2 anti_air = 2 } # Sofia
province = { id = 419 infra = 0.2 } # Vraca
province = { id = 420 infra = 0.2 } # Pleven
province = { id = 421 infra = 0.2 } # Plovdiv
province = { id = 422 energy = 22 metal = 11 rare_materials = 6 } # Varna
province = { id = 437 infra = 0.2 energy = 29 metal = 20 rare_materials = 5 } # Izmir
province = { id = 438 infra = 0.2 energy = 11 metal = 10 rare_materials = 10 } # Antalya
province =
{ id             = 439
  infra          = 0.2
  anti_air       = 4
  air_base       = { size = 6 current_size = 6 }
  naval_base     = { size = 10 current_size = 10 }
  energy         = 29
  metal          = 10
  rare_materials = 5
}                  # Izmit
province = { id = 440 infra = 0.2 } # Karabük
province = { id = 441 infra = 0.4 } # Afyonkarahisar
province = { id = 442 infra = 0.4 ic = 5 } # Konya
province = { id = 443 infra = 0.2 naval_base = 1 air_base = 3 anti_air = 2 } # Mersin
province = { id = 444 infra = 0.2 } # Cyprus
province = { id = 445 infra = 0.2 } # Gaziantep
province = { id = 446 infra = 0.4 ic = 5 anti_air = 1 } # Kayseri
province = { id = 447 infra = 0.4 } # Sivas
province =
{ id       = 448
  infra    = 0.2
  anti_air = 4
  air_base = { size = 6 current_size = 6 }
}            # Ankara
province = { id = 449 infra = 0.2 } # Samsun
province = { id = 450 infra = 0.2 } # Trebizond
province = { id = 900 infra = 0.4 } # Suez
province = { id = 901 infra = 0.4 ic = 5 } # Port Said
province = { id = 902 infra = 0.4 } # Zaqazig
province = { id = 903 infra = 0.2 ic = 5 } # Cairo
province = { id = 904 infra = 0.4 } # Tanta
province = { id = 905 infra = 0.2 } # Fayum
province = { id = 906 infra = 0.2 ic = 5 anti_air = 1 } # Alexandria
province = { id = 907 infra = 0.8 } # Qattara
province = { id = 908 infra = 0.4 } # Gerawla
province = { id = 909 infra = 0.2 naval_base = 4 air_base = 4 anti_air = 2 } # El Alamein
province = { id = 910 infra = 0.2 } # Fuka
province = { id = 911 infra = 0.2 } # Mersa Matruh
province = { id = 912 infra = 0.4 air_base = 1 anti_air = 1 } # Nibeiwa
province = { id = 913 infra = 0.4 } # Rabia
province = { id = 914 infra = 0.2 } # Sidi Barrani
province = { id = 915 infra = 0.2 } # Sollum
province = { id = 1019 infra = 0.8 } # Great Sand Sea
province = { id = 1020 infra = 0.6 } # Siwa
province = { id = 1021 infra = 0.8 } # Ain Dalla
province = { id = 1022 infra = 0.8 air_base = 3 anti_air = 1 } # Western Desert
province = { id = 1023 infra = 0.2 } # Asyut
province = { id = 1024 infra = 0.2 } # Luxor
province = { id = 1025 infra = 0.6 } # Qusayr
province = { id = 1026 infra = 0.2 } # Aswan
province = { id = 1027 infra = 0.2 } # Idfu
province = { id = 1028 infra = 0.6 } # Wadi Halfa
province = { id = 1029 infra = 0.6 } # Dongola
province = { id = 1030 infra = 0.4 } # Port Sudan
province = { id = 1031 infra = 0.4 } # Berber
province = { id = 1032 infra = 0.6 air_base = 2 anti_air = 1 } # Omdurman
province = { id = 1033 infra = 0.4 naval_base = 2 anti_air = 1 } # Massaua
province = { id = 1034 infra = 0.4 } # Obbia
province = { id = 1035 infra = 0.4 } # Berbera
province = { id = 1036 infra = 0.4 } # Zeila
province = { id = 1037 infra = 0.4 } # Djibouti
province = { id = 1038 infra = 0.4 } # Assab
province = { id = 1039 infra = 0.6 } # Asmara
province = { id = 1040 infra = 0.6 } # Kassala
province = { id = 1041 infra = 0.6 } # Gallabat
province = { id = 1042 infra = 0.6 ic = 5 anti_air = 1 } # Gonder
province = { id = 1043 infra = 0.6 } # Desê
province = { id = 1044 infra = 0.6 air_base = 6 anti_air = 1 } # Debre Mark'os
province = { id = 1045 infra = 0.6 } # Gambêla
province = { id = 1046 infra = 0.4 ic = 5 anti_air = 2 } # Addis Ababa
province = { id = 1047 infra = 0.6 } # Jima
province = { id = 1048 infra = 0.6 } # Âdwa
province = { id = 1049 infra = 0.6 } # Denakil
province = { id = 1050 infra = 0.6 } # Dirê Dawa
province = { id = 1051 infra = 0.4 } # Harar
province = { id = 1052 infra = 0.4 } # Ginir
province = { id = 1053 infra = 0.6 } # Moyale
province = { id = 1054 infra = 0.6 } # Ogaden
province = { id = 1055 infra = 0.6 } # Bardera
province = { id = 1056 infra = 0.4 naval_base = 3 anti_air = 1 } # Mogadishu
province = { id = 1058 infra = 0.4 } # Kismayo
province = { id = 1065 infra = 0.6 } # Malakal
province = { id = 1066 infra = 0.4 ic = 5 anti_air = 1 } # Khartoum
province = { id = 1067 infra = 0.8 } # El Atrun
province = { id = 1068 infra = 0.6 } # El Obeid
province = { id = 1069 infra = 0.6 } # Waw
province = { id = 1504 infra = 0.4 naval_base = 6 anti_air = 2 } # Dubai
province = { id = 1790 infra = 0.4 } # Hilla
province = { id = 1791 infra = 0.6 air_base = 2 anti_air = 1 } # Karbala
province = { id = 1792 infra = 0.4 ic = 5 } # Damascus
province = { id = 1793 infra = 0.2 } # Tripoli
province = { id = 1794 infra = 0.2 } # Beirut
province = { id = 1795 infra = 0.4 } # Golan
province = { id = 1796 infra = 0.4 ic = 5 } # Amman
province = { id = 1797 infra = 0.4 ic = 5 air_base = 5 anti_air = 2 } # Jerusalem
province = { id = 1798 infra = 0.2 naval_base = 5 anti_air = 1 } # Tel Aviv
province = { id = 1799 infra = 0.2 } # Gaza
province = { id = 1800 infra = 0.4 } # el-Arish
province = { id = 1801 infra = 0.4 } # Sharm el-Sheikh
province = { id = 1802 infra = 0.6 ic = 5 } # Akaba
province = { id = 1803 infra = 0.6 ic = 5 } # Bayir
province = { id = 1804 infra = 0.4 } # Medina
province = { id = 1805 infra = 0.6 } # Jawf
province = { id = 1806 infra = 0.6 oil = 15 } # Najaf
province = { id = 1807 infra = 0.6 ic = 5 oil = 15 air_base = 7 anti_air = 3 } # Riyadh
province = { id = 1808 infra = 0.4 oil = 25 } # Jiddah
province = { id = 1809 infra = 0.4 } # Abha
province = { id = 1812 infra = 0.4 anti_air = 1 } # Sanaa
province = { id = 1813 infra = 0.2 naval_base = 6 air_base = 6 anti_air = 2 } # Aden
province = { id = 1814 infra = 0.4 } # Mukalla
province = { id = 1815 infra = 0.4 } # Socotra
province = { id = 1818 infra = 0.8 } # Rub al Khali
province = { id = 1819 infra = 0.4 anti_air = 1 } # Mascate
province = { id = 1820 infra = 0.4 } # Doha
province = { id = 1821 infra = 0.4 oil = 7 max_oil = 7 } # Dammam
province = { id = 1822 infra = 0.4 oil = 17 } # Kuweit City
province = { id = 1823 infra = 0.2 } # Basrah
province = { id = 1824 infra = 0.2 } # Nasiriyah
province = { id = 1843 infra = 0.2 } # Armavil
province = { id = 1844 infra = 0.4 } # Maikop
province = { id = 1845 infra = 0.4 } # Tuapse
province = { id = 1848 infra = 0.4 } # Batum

#####################
# Country main data #
#####################

country =
{ tag                    = UTO
  ai                     = "globalwar/TUR.ai"
  belligerence           = 0
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  capital                = 448
  manpower               = 1000
  transports             = 100
  escorts                = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 1
    freedom           = 6
    free_market       = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  nationalprovinces      = { 409  408  437  438  439  441  442  443  448  440  449  447  446  445  450  1851 1852 1853 1854 1855 392  393  394  395
			     396  400  401  402  403  405  410  411  412  419  420  422  421  417  416  1860 1864 1865 1866 1790 1824 1823 1806 1791
			     1821 1818 1809 1808 1807 1805 1804 1812 1819 1843 1037 1862 1861 1863 1792 1793 1794 1795 444  1822 1802 1504 1813 1814
			     1815 1035 1036 1820 404  1803 406  407  1798 1799 1797 1796 1800 1801 413  414  415  398  399  390  391  255  1848 1845
			     1844 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030 1040 1041 1033 1039 1038 1034 1055 1056 1058 900  901  902  903
			     904  905  906  907  908  909  910  911  912  913  914  915  4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1044 1048
			     1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054 1825 1789 1859 1856 1850 1849 1846 1842 270  257  256  254  423
			     424  425  426  418  451  389  916  917  918  926  1017 1018 1081 1080 1079 1070 1072 1064 1059 1061
			   }
  ownedprovinces         = { 409  408  437  438  439  441  442  443  448  440  449  447  446  445  450  1851 1852 1853 1854 1855 392  393  394  395
			     396  400  401  402  403  405  410  411  412  419  420  422  421  417  416  1860 1864 1865 1866 1790 1824 1823 1806 1791
			     1821 1818 1809 1808 1807 1805 1804 1812 1819 1843 1037 1862 1861 1863 1792 1793 1794 1795 444  1822 1802 1504 1813 1814
			     1815 1035 1036 1820 404  1803 406  407  1798 1799 1797 1796 1800 1801 413  414  415  398  399  390  391  255  1848 1845
			     1844 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030 1040 1041 1033 1039 1038 1034 1055 1056 1058 900  901  902  903
			     904  905  906  907  908  909  910  911  912  913  914  915  4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1044 1048
			     1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054
			   }
  controlledprovinces    = { 409  408  437  438  439  441  442  443  448  440  449  447  446  445  450  1851 1852 1853 1854 1855 392  393  394  395
			     396  400  401  402  403  405  410  411  412  419  420  422  421  417  416  1860 1864 1865 1866 1790 1824 1823 1806 1791
			     1821 1818 1809 1808 1807 1805 1804 1812 1819 1843 1037 1862 1861 1863 1792 1793 1794 1795 444  1822 1802 1504 1813 1814
			     1815 1035 1036 1820 404  1803 406  407  1798 1799 1797 1796 1800 1801 413  414  415  398  399  390  391  255  1848 1845
			     1844 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030 1040 1041 1033 1039 1038 1034 1055 1056 1058 900  901  902  903
			     904  905  906  907  908  909  910  911  912  913  914  915  4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1044 1048
			     1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054
			   }
  # Semi-Major Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5010 5080 8010 8020 8030 8040 8050 9010 }
  diplomacy              = { }

  landunit =
  { id       = { type = 30003 id = 1 }
    name     = "1. Corps"
    location = 1815
    division =
    { id       = { type = 30003 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 3 }
    name     = "2. Corps"
    location = 1056
    division =
    { id       = { type = 30003 id = 4 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 5 }
    name     = "3. Corps"
    location = 1058
    division =
    { id       = { type = 30003 id = 6 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 7 }
    name     = "4. Corps"
    location = 1055
    division =
    { id       = { type = 30003 id = 8 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 9 }
    name     = "5. Corps"
    location = 1053
    division =
    { id       = { type = 30003 id = 10 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 11 }
    name     = "6. Corps"
    location = 1047
    division =
    { id       = { type = 30003 id = 12 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 13 }
    name     = "7. Corps"
    location = 1065
    division =
    { id       = { type = 30003 id = 14 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 15 }
    name     = "8. Corps"
    location = 1069
    division =
    { id       = { type = 30003 id = 16 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 17 }
    name     = "9. Corps"
    location = 1067
    division =
    { id       = { type = 30003 id = 18 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 19 }
    name     = "10. Corps"
    location = 1019
    division =
    { id       = { type = 30003 id = 20 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 21 }
    name     = "11. Corps"
    location = 1020
    division =
    { id       = { type = 30003 id = 22 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 23 }
    name     = "12. Corps"
    location = 913
    division =
    { id       = { type = 30003 id = 24 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 25 }
    name     = "13. Corps"
    location = 915
    division =
    { id       = { type = 30003 id = 26 }
      name     = "13th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 27 }
    name     = "14. Corps"
    location = 910
    division =
    { id       = { type = 30003 id = 28 }
      name     = "14th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 29 }
    name     = "15. Corps"
    location = 909
    division =
    { id       = { type = 30003 id = 30 }
      name     = "15th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 31 }
    name     = "16. Corps"
    location = 906
    division =
    { id       = { type = 30003 id = 32 }
      name     = "16th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 33 }
    name     = "17. Corps"
    location = 901
    division =
    { id       = { type = 30003 id = 34 }
      name     = "17th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 35 }
    name     = "18. Corps"
    location = 1030
    division =
    { id       = { type = 30003 id = 170 }
      name     = "18th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 36 }
    name     = "19. Corps"
    location = 1033
    division =
    { id       = { type = 30003 id = 37 }
      name     = "19th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 38 }
    name     = "20. Corps"
    location = 1037
    division =
    { id       = { type = 30003 id = 39 }
      name     = "20th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 40 }
    name     = "21. Corps"
    location = 1035
    division =
    { id       = { type = 30003 id = 41 }
      name     = "21st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 42 }
    name     = "22. Corps"
    location = 1034
    division =
    { id       = { type = 30003 id = 43 }
      name     = "22nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 44 }
    name     = "23. Corps"
    location = 1822
    division =
    { id       = { type = 30003 id = 45 }
      name     = "23rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 46 }
    name     = "24. Corps"
    location = 1821
    division =
    { id       = { type = 30003 id = 47 }
      name     = "24th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 48 }
    name     = "25. Corps"
    location = 1820
    division =
    { id       = { type = 30003 id = 49 }
      name     = "25th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 50 }
    name     = "26. Corps"
    location = 1504
    division =
    { id       = { type = 30003 id = 51 }
      name     = "26th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 52 }
    name     = "27. Corps"
    location = 1819
    division =
    { id       = { type = 30003 id = 53 }
      name     = "27th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 54 }
    name     = "28. Corps"
    location = 1813
    division =
    { id       = { type = 30003 id = 55 }
      name     = "28th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 56 }
    name     = "29. Corps"
    location = 1812
    division =
    { id       = { type = 30003 id = 57 }
      name     = "29th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 58 }
    name     = "30. Corps"
    location = 1809
    division =
    { id       = { type = 30003 id = 59 }
      name     = "30th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 60 }
    name     = "31. Corps"
    location = 406
    division =
    { id       = { type = 30003 id = 61 }
      name     = "31st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 62 }
    name     = "32. Corps"
    location = 1801
    division =
    { id       = { type = 30003 id = 63 }
      name     = "32nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 64 }
    name     = "33. Corps"
    location = 900
    division =
    { id       = { type = 30003 id = 65 }
      name     = "33rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 66 }
    name     = "34. Corps"
    location = 1800
    division =
    { id       = { type = 30003 id = 67 }
      name     = "34th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 68 }
    name     = "35. Corps"
    location = 1799
    division =
    { id       = { type = 30003 id = 69 }
      name     = "35th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 70 }
    name     = "36. Corps"
    location = 410
    division =
    { id       = { type = 30003 id = 71 }
      name     = "36th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 72 }
    name     = "37. Corps"
    location = 1798
    division =
    { id       = { type = 30003 id = 73 }
      name     = "37th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 74 }
    name     = "38. Corps"
    location = 404
    division =
    { id       = { type = 30003 id = 75 }
      name     = "38th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 76 }
    name     = "39. Corps"
    location = 1794
    division =
    { id       = { type = 30003 id = 77 }
      name     = "39th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 78 }
    name     = "40. Corps"
    location = 1793
    division =
    { id       = { type = 30003 id = 79 }
      name     = "40th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 80 }
    name     = "41. Corps"
    location = 1862
    division =
    { id       = { type = 30003 id = 81 }
      name     = "41st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 82 }
    name     = "42. Corps"
    location = 445
    division =
    { id       = { type = 30003 id = 83 }
      name     = "42nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 84 }
    name     = "43. Corps"
    location = 444
    division =
    { id       = { type = 30003 id = 85 }
      name     = "43rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 86 }
    name     = "44. Corps"
    location = 399
    division =
    { id       = { type = 30003 id = 87 }
      name     = "44th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 88 }
    name     = "45. Corps"
    location = 437
    division =
    { id       = { type = 30003 id = 89 }
      name     = "45th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 90 }
    name     = "46. Corps"
    location = 398
    division =
    { id       = { type = 30003 id = 91 }
      name     = "46th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 92 }
    name     = "47. Corps"
    location = 396
    division =
    { id       = { type = 30003 id = 93 }
      name     = "47th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 94 }
    name     = "48. Corps"
    location = 400
    division =
    { id       = { type = 30003 id = 95 }
      name     = "48th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 96 }
    name     = "49. Corps"
    location = 405
    division =
    { id       = { type = 30003 id = 97 }
      name     = "49th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 98 }
    name     = "50. Corps"
    location = 408
    division =
    { id       = { type = 30003 id = 99 }
      name     = "50th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 100 }
    name     = "51. Corps"
    location = 439
    division =
    { id       = { type = 30003 id = 101 }
      name     = "51st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 102 }
    name     = "52. Corps"
    location = 449
    division =
    { id       = { type = 30003 id = 103 }
      name     = "52nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 104 }
    name     = "53. Corps"
    location = 1848
    division =
    { id       = { type = 30003 id = 105 }
      name     = "53rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 106 }
    name     = "54. Corps"
    location = 411
    division =
    { id       = { type = 30003 id = 107 }
      name     = "54th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 108 }
    name     = "55. Corps"
    location = 255
    division =
    { id       = { type = 30003 id = 109 }
      name     = "55th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 110 }
    name     = "56. Corps"
    location = 1843
    division =
    { id       = { type = 30003 id = 111 }
      name     = "56th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 112 }
    name     = "57. Corps"
    location = 1844
    division =
    { id       = { type = 30003 id = 113 }
      name     = "57th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 114 }
    name     = "58. Corps"
    location = 1851
    division =
    { id       = { type = 30003 id = 115 }
      name     = "58th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 116 }
    name     = "59. Corps"
    location = 1855
    division =
    { id       = { type = 30003 id = 117 }
      name     = "59th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 118 }
    name     = "60. Corps"
    location = 1860
    division =
    { id       = { type = 30003 id = 119 }
      name     = "60th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 120 }
    name     = "61. Corps"
    location = 1866
    division =
    { id       = { type = 30003 id = 121 }
      name     = "61st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 122 }
    name     = "62. Corps"
    location = 1824
    division =
    { id       = { type = 30003 id = 123 }
      name     = "62nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 124 }
    name     = "63. Corps"
    location = 1823
    division =
    { id       = { type = 30003 id = 125 }
      name     = "63rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 126 }
    name     = "64. Corps"
    location = 393
    division =
    { id       = { type = 30003 id = 127 }
      name     = "64th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 128 }
    name     = "65. Corps"
    location = 394
    division =
    { id       = { type = 30003 id = 129 }
      name     = "65th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 130 }
    name     = "66. Corps"
    location = 401
    division =
    { id       = { type = 30003 id = 131 }
      name     = "66th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 132 }
    name     = "67. Corps"
    location = 390
    division =
    { id       = { type = 30003 id = 133 }
      name     = "67th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 134 }
    name     = "68. Corps"
    location = 415
    division =
    { id       = { type = 30003 id = 135 }
      name     = "68th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 136 }
    name     = "69. Corps"
    location = 417
    division =
    { id       = { type = 30003 id = 137 }
      name     = "69th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 138 }
    name     = "70. Corps"
    location = 419
    division =
    { id       = { type = 30003 id = 139 }
      name     = "70th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 140 }
    name     = "71. Corps"
    location = 420
    division =
    { id       = { type = 30003 id = 141 }
      name     = "71st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 142 }
    name     = "72 Corps"
    location = 422
    division =
    { id       = { type = 30003 id = 143 }
      name     = "72nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 144 }
    name     = "73. Corps"
    location = 409
    division =
    { id       = { type = 30003 id = 145 }
      name     = "73rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 146 }
    name     = "74. Corps"
    location = 1068
    division =
    { id       = { type = 30003 id = 147 }
      name     = "74rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30003 id = 218 }
    name     = "Armored Corps"
    location = 448
    division =
    { type  = armor
      model = 0
      id    = { type = 30003 id = 219 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30003 id = 220 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30003 id = 221 }
      name  = "3rd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30003 id = 222 }
      name  = "4th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30003 id = 223 }
      name  = "5th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30003 id = 224 }
      name  = "6th Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30003 id = 193 }
    name     = "Main Fleet"
    location = 439
    base     = 439
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30003 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30003 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30003 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30003 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30003 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30003 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30003 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30003 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30003 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30003 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30003 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30003 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30003 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30003 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30003 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30003 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30003 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30003 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30003 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30003 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30003 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30003 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30003 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30003 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30003 id = 173 }
    name     = "Bomber Group 1"
    location = 448
    base     = 448
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30003 id = 178 }
    name     = "Bomber Group 2"
    location = 448
    base     = 448
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30003 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30003 id = 183 }
    name     = "Fighter Group 1"
    location = 448
    base     = 448
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30003 id = 188 }
    name     = "Fighter Group 2"
    location = 448
    base     = 448
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30003 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
