
##############################
# Country definition for USN #
##############################

province =
{ id         = 541
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Vancouver
province = { id = 542 infra = 0.4 } # Kiska Island
province = { id = 543 infra = 0.4 } # Amchitka Island
province = { id = 544 infra = 0.4 } # Andreanof Islands
province = { id = 545 infra = 0.4 } # Yunaska Island
province = { id = 546 infra = 0.4 } # Umnak Island
province = { id = 547 infra = 0.4 } # Unalaska Island
province = { id = 548 infra = 0.4 } # Unimak Island
province =
{ id         = 549
  infra      = 0.4
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  anti_air   = 2
}              # Anchorage
province = { id = 550 infra = 0.4 rare_materials = 5 } # Seward Peninsula
province = { id = 551 infra = 0.6 rare_materials = 5 } # Fairbanks
province = { id = 552 infra = 0.6 rare_materials = 5 } # Whitehorse
province = { id = 553 infra = 0.4 supplypool = 1000 } # Juneau
province = { id = 554 infra = 0.4 rare_materials = 5 } # Prince George
province = { id = 557 infra = 0.4 } # Fort McMurray
province = { id = 558 infra = 0.6 } # Yellowknife
province = { id = 559 infra = 0.6 } # Kugluktuk
province = { id = 560 infra = 0.6 } # Repulse Bay
province = { id = 561 infra = 0.6 } # Rankin Inlet
province = { id = 563 infra = 0.6 naval_base = 4 air_base = 4 anti_air = 1 } # Baffin Island
province = { id = 564 infra = 0.4 } # Radisson
province = { id = 565 infra = 0.2 } # Fort Severn
province = { id = 566 infra = 0.4 } # Churchill
province = { id = 567 infra = 0.2 } # Dauphin
province =
{ id       = 569
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Winnipeg
province = { id = 570 infra = 0.2 } # Norway House
province = { id = 573 infra = 0.2 } # Val d'Or
province = { id = 574 infra = 0.2 } # Sept-Îles
province = { id = 575 infra = 0.2 } # Labrador
province =
{ id         = 576
  infra      = 0.2
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Newfoundland
province = { id = 578 infra = 0.2 } # Cape Breton
province =
{ id         = 579
  infra      = 0.2
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Halifax
province = { id = 580 infra = 0.2 } # Moncton
province =
{ id         = 581
  infra      = 0.2
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 4 current_size = 4 }
}              # Saint John
province = { id = 584 infra = 0.2 } # Sherbrooke
province =
{ id       = 585
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Montréal
province =
{ id         = 586
  anti_air   = 4
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Québec City
province = { id = 587 infra = 0.2 } # Gatineau
province =
{ id       = 588
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # Ottawa
province = { id = 589 anti_air = 1 } # Toronto
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Plattsburgh
province =
{ id       = 595
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id         = 600
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Boston
province =
{ id         = 602
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # New York
province =
{ id         = 606
  ic         = -3
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
}              # Washington D.C.
province = { id = 607 ic = -2 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Baltimore
province = { id = 608 anti_air = 2 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Philadelphia
province = { id = 609 ic = -1 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Harrisburg
province = { id = 610 energy = 0 max_energy = 0 } # Scranton
province = { id = 611 infra = 0.2 } # Altoona
province = { id = 612 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Syracuse
province = { id = 613 metal = 0 max_metal = 0 } # Buffalo
province =
{ id         = 614
  ic         = -2
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
}              # Pittsburgh
province = { id = 615 ic = -3 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Cleveland
province =
{ id         = 616
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  energy     = 0
  max_energy = 0
}              # Detroit
province = { id = 618 energy = 0 max_energy = 0 } # Grand Rapids
province = { id = 619 ic = -1 energy = 0 max_energy = 0 } # Indianapolis
province =
{ id         = 620
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
}              # Chicago
province =
{ id                 = 621
  anti_air           = 1
  air_base           = { size = 4 current_size = 4 }
  energy             = 0
  max_energy         = 0
  metal              = 0
  max_metal          = 0
  rare_materials     = 0
  max_rare_materials = 0
}                      # Milwaukee
province = { id = 622 metal = 0 max_metal = 0 } # Marquette
province = { id = 625 ic = -1 } # Peoria
province = { id = 626 ic = -2 energy = 0 max_energy = 0 } # Decatur
province = { id = 627 ic = -2 energy = 0 max_energy = 0 } # Evansville
province = { id = 628 ic = -4 energy = 1 max_energy = 1 metal = 0 max_metal = 0 } # Columbus
province = { id = 629 infra = 0.2 ic = -1 metal = 0 max_metal = 0 } # Charleston
province = { id = 630 infra = 0.2 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Clarksburg
province = { id = 631 ic = -1 energy = 0 max_energy = 0 } # Charlotteville
province = { id = 632 ic = -1 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Richmond
province =
{ id         = 633
  ic         = -1
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
}              # Norfolk
province = { id = 639 infra = 0.2 energy = 0 max_energy = 0 } # Marion
province =
{ id         = 640
  ic         = -3
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
}              # Louisville
province =
{ id        = 689
  ic        = -2
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 0
  max_metal = 0
}             # St. Louis
province = { id = 690 ic = -2 metal = 0 max_metal = 0 } # Kansas City
province = { id = 691 ic = -1 metal = 0 max_metal = 0 } # Cedar Rapids
province =
{ id        = 692
  ic        = -1
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 0
  max_metal = 0
}             # Des Moines
province =
{ id        = 693
  anti_air  = 1
  air_base  = { size = 4 current_size = 4 }
  metal     = 0
  max_metal = 0
}             # Minneapolis
province = { id = 694 metal = 9 max_metal = 9 } # Duluth
province =
{ id       = 698
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Bismarck
province = { id = 703 infra = 0.2 } # Billings
province = { id = 704 infra = 0.2 } # Casper
province = { id = 705 infra = 0.2 } # Rock Springs
province = { id = 706 infra = 0.2 energy = 0 max_energy = 0 } # Grand Junction
province =
{ id         = 707
  infra      = 0.2
  ic         = -2
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
}              # Denver
province = { id = 708 energy = 0 max_energy = 0 } # Aspen
province = { id = 711 ic = -1 energy = 0 max_energy = 0 metal = 0 max_metal = 0 } # Wichita
province = { id = 728 infra = 0.2 } # Tucson
province = { id = 729 infra = 0.2 } # Yuma
province =
{ id         = 730
  infra      = 0.2
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  energy     = 0
  max_energy = 0
}              # Phoenix
province = { id = 732 infra = 0.2 energy = 0 max_energy = 0 } # Provo
province =
{ id         = 733
  infra      = 0.2
  air_base   = { size = 10 current_size = 10 }
  energy     = 0
  max_energy = 0
  anti_air   = 3
}              # Salt Lake City
province = { id = 734 infra = 0.2 } # Las Vegas
province = { id = 735 infra = 0.2 } # Mojave Desert
province = { id = 736 infra = 0.2 } # Imperial Valley
province =
{ id         = 761
  ic         = -2
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
  anti_air   = 2
}              # San Diego
province =
{ id         = 762
  ic         = -3
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
  oil        = 1
  max_oil    = 1
}              # Los Angeles
province =
{ id       = 764
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id         = 765
  ic         = -3
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  energy     = 0
  max_energy = 0
  metal      = 0
  max_metal  = 0
}              # San Francisco
province = { id = 767 infra = 0.2 } # Sierra Nevada
province = { id = 768 infra = 0.2 } # Reno
province = { id = 769 infra = 0.2 } # Harney Basin
province = { id = 770 infra = 0.2 } # Pocatello
province = { id = 771 infra = 0.2 } # Boise
province = { id = 772 infra = 0.2 air_base = 5 anti_air = 2 } # Anaconda
province = { id = 773 infra = 0.2 } # Missoula
province = { id = 774 infra = 0.2 } # Great Falls
province = { id = 775 infra = 0.2 } # Butte
province = { id = 776 infra = 0.2 } # Lewiston
province = { id = 777 infra = 0.2 } # Elk City
province =
{ id         = 780
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  anti_air   = 3
}              # Seattle
province = { id = 781 infra = 0.2 } # Richland
province =
{ id       = 783
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Portland
province = { id = 784 infra = 0.2 } # Mount Hood
province = { id = 785 infra = 0.2 } # Klamath Falls
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province = { id = 792 ic = -1 } # Topeka
province = { id = 794 infra = 0.6 air_base = 4 anti_air = 1 } # Fort Resolution
province = { id = 795 infra = 0.4 } # Prince Albert
province = { id = 796 infra = 0.2 } # Edmonton
province =
{ id       = 797
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Calgary
province = { id = 798 infra = 0.2 } # Saskatoon
province = { id = 1408 infra = 0.4 supplypool = 500 } # Attu Island

#####################
# Country main data #
#####################

country =
{ tag                    = USN
  ai                     = "globalwar/USA.ai"
  belligerence           = 0
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 100
  manpower               = 1000
  transports             = 100
  escorts                = 100

  capital                = 606
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 7
    freedom           = 6
    free_market       = 6
    professional_army = 6
    defense_lobby     = 6
    interventionism   = 10
  }
  ownedprovinces         = { 633  632  631  638  639  606  607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582
			     583  599  600  601  613  614  629  630  640  641  615  628  617  616  618  619  627  687  688  689  626  625  620  621
			     624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789  790  791  792  710  711  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  1408 556  541  555  554  552  558  557  796  797  799  798  795  794  559  560  561  563  566
			     567  570  568  569  571  565  572  588  589  590  591  587  585  584  573  586  574  564  581  580  579  578  1909 575
			     576
			   }
  controlledprovinces    = { 633  632  631  638  639  606  607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582
			     583  599  600  601  613  614  629  630  640  641  615  628  617  616  618  619  627  687  688  689  626  625  620  621
			     624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789  790  791  792  710  711  728  729  730
			     575  576  731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779
			     780  781  782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549
			     548  547  546  545  544  543  542  1408 572  588  589  590  591  587  585  584  573  586  574  564  581  580  579  578
			     1909 556  541  555  554  552  558  557  796  797  799  798  795  794  559  560  561  563  566  567  570  568  569  571
			     565
			   }
  # early esc car
  # USA 1936 techs
  # ######################
  techapps               = { 1010 1190 2010 2290 2450 3010 3070 3130 3190 3250 3320 3400 4010 4120 5010 5080 8010 8020 8030 8040 8050 9010}
  nationalprovinces      = { 633  632  631  638  639  606  607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582
			     583  599  600  601  613  614  629  630  640  641  615  628  617  616  618  619  627  687  688  689  626  625  620  621
			     624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789  790  791  792  710  711  728  729  730
			     731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781
			     782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547
			     546  545  544  543  542  1408 556  541  555  554  552  558  557  796  797  799  798  795  794  559  560  561  563  566
			     567  570  568  569  571  565  572  588  589  590  591  587  585  584  573  586  574  564  581  580  579  578  1909 575
			     576  634  636  637  643  642  673  685  686  793  712  724  725  726  727  740  739  737
			   }

  landunit =
  { id       = { type = 30010 id = 1 }
    name     = "1. Corps"
    location = 1408
    division =
    { id       = { type = 30010 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 3 }
    name     = "2. Corps"
    location = 543
    division =
    { id       = { type = 30010 id = 4 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 5 }
    name     = "3. Corps"
    location = 542
    division =
    { id       = { type = 30010 id = 6 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 7 }
    name     = "4. Corps"
    location = 544
    division =
    { id       = { type = 30010 id = 8 }
      name     = "4th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 9 }
    name     = "5. Corps"
    location = 545
    division =
    { id       = { type = 30010 id = 10 }
      name     = "5th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 11 }
    name     = "6. Corps"
    location = 546
    division =
    { id       = { type = 30010 id = 12 }
      name     = "6th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 13 }
    name     = "7. Corps"
    location = 547
    division =
    { id       = { type = 30010 id = 14 }
      name     = "7th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 15 }
    name     = "8. Corps"
    location = 548
    division =
    { id       = { type = 30010 id = 16 }
      name     = "8th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 17 }
    name     = "9. Corps"
    location = 553
    division =
    { id       = { type = 30010 id = 18 }
      name     = "9th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 19 }
    name     = "10. Corps"
    location = 541
    division =
    { id       = { type = 30010 id = 20 }
      name     = "10th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 21 }
    name     = "11. Corps"
    location = 780
    division =
    { id       = { type = 30010 id = 22 }
      name     = "11th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 23 }
    name     = "12. Corps"
    location = 556
    division =
    { id       = { type = 30010 id = 24 }
      name     = "12th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 25 }
    name     = "13. Corps"
    location = 782
    division =
    { id       = { type = 30010 id = 26 }
      name     = "13th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 27 }
    name     = "14. Corps"
    location = 765
    division =
    { id       = { type = 30010 id = 28 }
      name     = "14th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 29 }
    name     = "15. Corps"
    location = 762
    division =
    { id       = { type = 30010 id = 30 }
      name     = "15th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 31 }
    name     = "16. Corps"
    location = 761
    division =
    { id       = { type = 30010 id = 32 }
      name     = "16th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 33 }
    name     = "17. Corps"
    location = 736
    division =
    { id       = { type = 30010 id = 34 }
      name     = "17th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 35 }
    name     = "18. Corps"
    location = 729
    division =
    { id       = { type = 30010 id = 170 }
      name     = "18th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 36 }
    name     = "19. Corps"
    location = 728
    division =
    { id       = { type = 30010 id = 37 }
      name     = "19th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 38 }
    name     = "20. Corps"
    location = 708
    division =
    { id       = { type = 30010 id = 39 }
      name     = "20th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 40 }
    name     = "21. Corps"
    location = 709
    division =
    { id       = { type = 30010 id = 41 }
      name     = "21st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 42 }
    name     = "22. Corps"
    location = 710
    division =
    { id       = { type = 30010 id = 43 }
      name     = "22nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 44 }
    name     = "23. Corps"
    location = 711
    division =
    { id       = { type = 30010 id = 45 }
      name     = "23rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 46 }
    name     = "24. Corps"
    location = 792
    division =
    { id       = { type = 30010 id = 47 }
      name     = "24th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 48 }
    name     = "25. Corps"
    location = 688
    division =
    { id       = { type = 30010 id = 49 }
      name     = "25th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 50 }
    name     = "26. Corps"
    location = 687
    division =
    { id       = { type = 30010 id = 51 }
      name     = "26th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 52 }
    name     = "27. Corps"
    location = 641
    division =
    { id       = { type = 30010 id = 53 }
      name     = "27th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 54 }
    name     = "28. Corps"
    location = 640
    division =
    { id       = { type = 30010 id = 55 }
      name     = "28th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 56 }
    name     = "29. Corps"
    location = 639
    division =
    { id       = { type = 30010 id = 57 }
      name     = "29th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 58 }
    name     = "30. Corps"
    location = 638
    division =
    { id       = { type = 30010 id = 59 }
      name     = "30th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 60 }
    name     = "31. Corps"
    location = 632
    division =
    { id       = { type = 30010 id = 61 }
      name     = "31st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 62 }
    name     = "32. Corps"
    location = 633
    division =
    { id       = { type = 30010 id = 63 }
      name     = "32nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 64 }
    name     = "33. Corps"
    location = 605
    division =
    { id       = { type = 30010 id = 65 }
      name     = "33rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 66 }
    name     = "34. Corps"
    location = 604
    division =
    { id       = { type = 30010 id = 67 }
      name     = "34th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 68 }
    name     = "35. Corps"
    location = 603
    division =
    { id       = { type = 30010 id = 69 }
      name     = "35th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 70 }
    name     = "36. Corps"
    location = 602
    division =
    { id       = { type = 30010 id = 71 }
      name     = "36th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 72 }
    name     = "37. Corps"
    location = 601
    division =
    { id       = { type = 30010 id = 73 }
      name     = "37th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 74 }
    name     = "38. Corps"
    location = 596
    division =
    { id       = { type = 30010 id = 75 }
      name     = "38th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 76 }
    name     = "39. Corps"
    location = 583
    division =
    { id       = { type = 30010 id = 77 }
      name     = "39th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 78 }
    name     = "40. Corps"
    location = 581
    division =
    { id       = { type = 30010 id = 79 }
      name     = "40th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 80 }
    name     = "41. Corps"
    location = 580
    division =
    { id       = { type = 30010 id = 81 }
      name     = "41st Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 82 }
    name     = "42. Corps"
    location = 579
    division =
    { id       = { type = 30010 id = 83 }
      name     = "42nd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 84 }
    name     = "43. Corps"
    location = 578
    division =
    { id       = { type = 30010 id = 85 }
      name     = "43rd Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 86 }
    name     = "44. Corps"
    location = 1909
    division =
    { id       = { type = 30010 id = 87 }
      name     = "44th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 88 }
    name     = "45. Corps"
    location = 586
    division =
    { id       = { type = 30010 id = 89 }
      name     = "45th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 90 }
    name     = "46. Corps"
    location = 574
    division =
    { id       = { type = 30010 id = 91 }
      name     = "46th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 92 }
    name     = "47. Corps"
    location = 576
    division =
    { id       = { type = 30010 id = 93 }
      name     = "47th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 94 }
    name     = "48. Corps"
    location = 575
    division =
    { id       = { type = 30010 id = 95 }
      name     = "48th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 96 }
    name     = "49. Corps"
    location = 563
    division =
    { id       = { type = 30010 id = 97 }
      name     = "49th Infantry Division"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 30010 id = 218 }
    name     = "Armored Corps"
    location = 606
    division =
    { type  = armor
      model = 0
      id    = { type = 30010 id = 219 }
      name  = "1st Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30010 id = 220 }
      name  = "2nd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30010 id = 221 }
      name  = "3rd Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30010 id = 222 }
      name  = "4th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30010 id = 223 }
      name  = "5th Armored Division"
    }
    division =
    { type  = armor
      model = 0
      id    = { type = 30010 id = 224 }
      name  = "6th Armored Division"
    }
  }
  navalunit =
  { id       = { type = 30010 id = 193 }
    name     = "Main Fleet"
    location = 606
    base     = 606
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30010 id = 194 }
      name          = "Carrier 1"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type          = carrier
      model         = 0
      id            = { type = 30010 id = 195 }
      name          = "Carrier 2"
      extra         = cag
      brigade_model = 0
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30010 id = 196 }
      name  = "Battleship 1"
    }
    division =
    { type  = battleship
      model = 0
      id    = { type = 30010 id = 197 }
      name  = "Battleship 2"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30010 id = 198 }
      name  = "Battlecruiser 1"
    }
    division =
    { type  = battlecruiser
      model = 0
      id    = { type = 30010 id = 199 }
      name  = "Battlecruiser 2"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30010 id = 200 }
      name  = "Heavy Cruiser 1"
    }
    division =
    { type  = heavy_cruiser
      model = 0
      id    = { type = 30010 id = 201 }
      name  = "Heavy Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30010 id = 202 }
      name  = "Light Cruiser 1"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30010 id = 203 }
      name  = "Light Cruiser 2"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30010 id = 204 }
      name  = "Light Cruiser 3"
    }
    division =
    { type  = light_cruiser
      model = 0
      id    = { type = 30010 id = 205 }
      name  = "Light Cruiser 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30010 id = 206 }
      name  = "Destroyer 1"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30010 id = 207 }
      name  = "Destroyer 2"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30010 id = 208 }
      name  = "Destroyer 3"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30010 id = 209 }
      name  = "Destroyer 4"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30010 id = 210 }
      name  = "Destroyer 5"
    }
    division =
    { type  = destroyer
      model = 0
      id    = { type = 30010 id = 211 }
      name  = "Destroyer 6"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30010 id = 212 }
      name  = "Transport 1"
    }
    division =
    { type  = transport
      model = 0
      id    = { type = 30010 id = 213 }
      name  = "Transport 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30010 id = 214 }
      name  = "Submarine 1"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30010 id = 215 }
      name  = "Submarine 2"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30010 id = 216 }
      name  = "Submarine 3"
    }
    division =
    { type  = submarine
      model = 0
      id    = { type = 30010 id = 217 }
      name  = "Submarine 4"
    }
  }
  airunit =
  { id       = { type = 30010 id = 173 }
    name     = "Bomber Group 1"
    location = 606
    base     = 606
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 174 }
      name  = "1st Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 175 }
      name  = "2nd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 176 }
      name  = "3rd Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 177 }
      name  = "4th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30010 id = 178 }
    name     = "Bomber Group 2"
    location = 606
    base     = 606
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 179 }
      name  = "5th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 180 }
      name  = "6th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 181 }
      name  = "7th Air Wing"
    }
    division =
    { type  = tactical_bomber
      model = 0
      id    = { type = 30010 id = 182 }
      name  = "8th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30010 id = 183 }
    name     = "Fighter Group 1"
    location = 606
    base     = 606
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 184 }
      name  = "9th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 185 }
      name  = "10th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 186 }
      name  = "11th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 187 }
      name  = "12th Air Wing"
    }
  }
  airunit =
  { id       = { type = 30010 id = 188 }
    name     = "Fighter Group 2"
    location = 606
    base     = 606
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 189 }
      name  = "13th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 190 }
      name  = "14th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 191 }
      name  = "15th Air Wing"
    }
    division =
    { type  = interceptor
      model = 0
      id    = { type = 30010 id = 192 }
      name  = "16th Air Wing"
    }
  }
}
