#
# by Dec152000 and Aregorn for HSR2_DD
#


country = {
    tag = U01

	ai = "AMI_1936.ai"
	manpower = 0

	policy = {
	date = { year = 0 month = january day = 0 }
	democratic = 5
	political_left = 5
	freedom = 5
	free_market = 5
	professional_army = 1
	defense_lobby = 5
	interventionism = 1
	}

	capital = 2606

	ownedprovinces =      {
		2606 2607
	}
	controlledprovinces = {
		2606 2607
	}
	nationalprovinces =   {
		2606 2607
	}

	diplomacy = { }

	SpyInfo = { country = "ami" NumberOfSpies = 5 }


	techapps = {

2290 2300 2310 # GW artillery

2450 # GW Static AA

1010 1020 # Early infantry

1190 1200 # Early cavalry

1110 # Early Mountain

5010 5020 # Mechanized Agriculture
5080 5090 # Construction
5190 # Basic Oil Refining
5310 5320 # Basic CT machine
5470 5480 # Nukes labs

6010 6030 6110 6120 # Trench Warfare doctrine (land)

	}
}