#
# by Aregorn for HSR2_DD
#
##############################
# Country definition for ENG #
##############################

province =
{ id         = 5
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Scapa Flow
province =
{ id       = 9
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Glasgow
province =
{ id         = 13
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Sheffield
province =
{ id         = 14
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Liverpool
province = { id = 16 anti_air = 2 } # Birmingham
province =
{ id         = 17
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Norwich
province = { id = 19 anti_air = 3 } # London
province =
{ id          = 20
  anti_air    = 5
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
}               # Dover
province =
{ id         = 21
  anti_air   = 6
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Portsmouth
province =
{ id         = 23
  anti_air   = 6
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Plymouth
province = { id = 28 oilpool = 1000 supplypool = 2000 } # Belfast
province =
{ id          = 31
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 5 current_size = 5 }
  landfort    = 0
  coastalfort = 1
  oilpool     = 1000
  supplypool  = 1000
}               # Malta
province =
{ id          = 348
  anti_air    = 6
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 6
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 1000
}               # Gibraltar
province =
{ id       = 444
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cyprus
province =
{ id         = 538
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id         = 576
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Newfoundland
province =
{ id       = 652
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Andros
province =
{ id         = 866
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
  oilpool    = 100
  supplypool = 200
}              # Falkland Islands
province =
{ id       = 873
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Georgetown
province = { id = 900 anti_air = 2 } # Suez
province = { id = 901 anti_air = 2 oilpool = 1000 supplypool = 2000 } # Port Said
province = { id = 903 anti_air = 2 } # Cairo
province =
{ id         = 906
  anti_air   = 5
  air_base   = { size = 7 current_size = 7 }
  naval_base = { size = 10 current_size = 10 }
  coastalfort = 2
}              # Alexandria
province =
{ id         = 988
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 1000
  supplypool = 2000
}              # Freetown
province =
{ id       = 1002
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Accra
province =
{ id       = 1008
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Lagos
province =
{ id       = 1061
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mombasa
province =
{ id       = 1066
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Khartoum
province =
{ id       = 1296
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mandalay
province =
{ id         = 1299
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Rangoon
province =
{ id          = 1315
  anti_air    = 4
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 2
  oilpool     = 1000
  supplypool  = 1000
}               # Hong Kong
province =
{ id          = 1353
  anti_air    = 6
  air_base    = { size = 8 current_size = 8 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
}               # Singapore
province =
{ id       = 1457
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Calcutta
province =
{ id       = 1467
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Indore
province =
{ id       = 1469
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Delhi
province =
{ id         = 1494
  anti_air   = 1
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 8 current_size = 8 }
}              # Karachi
province =
{ id         = 1505
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 1000
  supplypool = 2000
}              # Bombay
province =
{ id       = 1514
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cochin
province =
{ id         = 1516
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # Trincomalee
province =
{ id          = 1517
  anti_air    = 2
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
}               # Colombo
province =
{ id       = 1644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Kuching
province = { id = 1797 anti_air = 1 } # Jerusalem
province =
{ id         = 1798
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Tel Aviv
province =
{ id         = 1813
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
}              # Aden
province =
{ id         = 1817
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 100
  supplypool = 200
}              # Diego Garcia Island

#####################
# Country main data #
#####################

country =
{ tag                    = ENG
  capital                = 19

	peacetime_ic_mod = 0.50
	extra_tc = 5
	tc_mod = 1.10

  manpower               = 40
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 70
  transports             = 1000
  escorts                = 150
  diplomacy =
  { relation =
    { tag        = AFG
      value      = -75
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = ARG value = 75 }
    relation = { tag = AST value = 200 } # was access = yes
    relation =
    { tag        = AUS
      value      = 75
      guaranteed = { day = 27 month = september year = 1934 }
    }
    relation = { tag = BEL value = 150 }
    relation = { tag = BHU value = 200 access = yes }
    relation = { tag = BUL value = 20 }
    relation = { tag = CAN value = 200 } # was access = yes
    relation = { tag = CUB value = 30 }
    relation = { tag = CZE value = 125 }
    relation =
    { tag        = DEN
      value      = 100
      guaranteed = { day = 30 month = august year = 1934 }
    }
    relation = { tag = ENG value = 50 }
    relation = { tag = EST value = 65 }
    relation = { tag = ETH value = 50 }
    relation = { tag = FIN value = 85 }
    relation = { tag = FRA value = 150 }
    relation = { tag = GER value = 1 }
    relation =
    { tag        = GRE
      value      = 50
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = GUA value = 50 }
    relation = { tag = HOL value = 125 }
    relation = { tag = HON value = 50 }
    relation = { tag = HUN value = -50 }
    relation =
    { tag        = IRE
      value      = 25
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation =
    { tag        = IRQ
      value      = 100
      access     = yes
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = ITA value = -50 }
    relation = { tag = JAP value = -25 }
    relation = { tag = LAT value = 65 }
    relation = { tag = LIT value = 65 }
    relation = { tag = MEX value = 50 }
    relation = { tag = NEP value = 200 access = yes }
    relation =
    { tag        = NOR
      value      = 90
      guaranteed = { day = 30 month = august year = 1934 }
    }
    relation = { tag = NZL value = 200 } # was access = yes
    relation =
    { tag        = OMN
      value      = 150
      access     = yes
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation =
    { tag        = PER
      value      = 25
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = POL value = 50 }
    relation =
    { tag        = POR
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = ROM value = 50 }
    relation = { tag = SAF value = 200 } # was access = yes
    relation =
    { tag        = SAU
      value      = 100
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation =
    { tag        = SCH
      value      = 50
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation = { tag = SIA value = 70 }
    relation = { tag = SPR value = -10 }
    relation = { tag = SOV value = -25 }
    relation =
    { tag        = SWE
      value      = 80
      guaranteed = { day = 30 month = august year = 1934 }
    }
    relation =
    { tag        = TUR
      value      = 75
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = USA value = 150 }
    relation = { tag = VEN value = -10 }
    relation =
    { tag        = YEM
      value      = 150
      access     = yes
      guaranteed = { day = 11 month = february year = 1934 }
    }
  }

  SpyInfo                = { country = "ENG" NumberOfSpies = 9 }

  # GREAT BRITAIN
  nationalprovinces      = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   1494
			     1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459 1457
			     1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288 1289
			     1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1300 1292 1454 1297 1878 1877 444
			   }
  # GREAT BRITAIN
  ownedprovinces         = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444
			     1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
			     1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288
			     1289 1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1300 1292 1454 1297 1878 1877 1799 1797 1796 404  1802 1803
			     406  407  1813 1814 1820 1822 1504 1798 900  901  902  903  904  905  906  907  908  909  910  911  912  913  914  915
			     4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1800 1801 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030 1040 1041
			     1349 1350 1351 1352 1353 1644 1646 1647 1315 758  891  871  873  806  807  808  809  897  538  652  653  664  665  666
			     668  805  896  866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1112 1111 1105
			     1124 1125 1104 1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085 1012 988  982  1622 1683 1684
			     1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 575  576  1614 1611
			   }
  # GREAT BRITAIN
  controlledprovinces    = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444
			     1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
			     1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288
			     1289 1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1300 1292 1454 1297 1878 1877 1799 1797 1796 404  1802 1803
			     406  407  1813 1814 1820 1822 1504 1798 900  901  902  903  904  905  906  907  908  909  910  911  912  913  914  915
			     4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1800 1801 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030 1040 1041
			     1349 1350 1351 1352 1353 1644 1646 1647 1315 758  891  871  873  806  807  808  809  897  538  652  653  664  665  666
			     668  805  896  866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1112 1111 1105
			     1124 1125 1104 1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085 1012 988  982  1622 1683 1684
			     1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 575  576  1614 1611
			   }
  # Commonwealth Tech '36
  # UK 1936 techs
  # ######################
  techapps               = { 4010  4120  4130  2150  2010  2020  2030  2290  2300  2310  2450  2460  2510  1010  1020  1190  1200  1210  1220
			     4220  1110  2400  1150  1310  5010  5020  5050  5080  5090  5190  5200  5310  5320  5410  5470  5480  3420  9010  9020
			     9030  9140  8010  8020  8030  8040  8050  8070  8100  8120  3010  3020  3030  3070  3080  3090
			     3100  3130  3140  3150  3190  3200  3210  3250  3260  3270  3280  3320  3330  3340  3400  3410  14000
			   }
  blueprints             = { 6010 6030 6110 6120 6130 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 10
    free_market       = 8
    professional_army = 7
    defense_lobby     = 3
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 1001 }
  headofgovernment       = { type = 9 id = 1002 }
  foreignminister        = { type = 9 id = 1003 }
  armamentminister       = { type = 9 id = 1004 }
  ministerofsecurity     = { type = 9 id = 1005 }
  ministerofintelligence = { type = 9 id = 1006 }
  chiefofstaff           = { type = 9 id = 1007 }
  chiefofarmy            = { type = 9 id = 1008 }
  chiefofnavy            = { type = 9 id = 1009 }
  chiefofair             = { type = 9 id = 1010 }
  landunit =
  { name     = "Aldershot Command"
    location = 22
    id       = { type = 12700 id = 1 }
    division =
    { id       = { type = 12700 id = 1706 }
      name     = "British Army HQ"
      type     = hq
      model    = 0
      strength = 100
      extra    = rocket_artillery
      experience = 20
    }
    division =
    { id            = { type = 12700 id = 2 }
      name          = "1st Infantry Division"
      type          = infantry
      extra         = artillery
      brigade_model = 2
      strength      = 100
      extra    = engineer
      brigade_model = 8
      experience = 20
    }
    division =
    { id       = { type = 12700 id = 3 }
      name     = "2nd Infantry Division"
      type     = infantry
      strength = 100
      extra    = engineer
      brigade_model = 8
      experience = 20
    }
  }
  landunit =
  { name     = "Northern Command"
    location = 10
    id       = { type = 12700 id = 4 }
    division =
    { id       = { type = 12700 id = 5 }
      name     = "5th Infantry Division"
      type     = infantry
      strength = 100
      experience = 20
    }
  }
  landunit =
  { name     = "Southern Command"
    location = 21
    id       = { type = 12700 id = 6 }
    division =
    { id       = { type = 12700 id = 7 }
      name     = "3rd Infantry Division"
      type     = infantry
      strength = 100
      experience = 20
    }
  }
  landunit =
  { name     = "Hong Kong Command"
    location = 1315
    id       = { type = 12700 id = 8 }
    division =
    { id       = { type = 12700 id = 9 }
      name     = "Hong Kong Defence Force"
      type     = garrison
      strength = 100
      locked   = yes
      experience = 20
    }
  }
  landunit =
  { name     = "Singapore Command"
    location = 1353
    id       = { type = 12700 id = 10 }
    division =
    { id       = { type = 12700 id = 11 }
      name     = "Singapore Defence Force"
      type     = garrison
      strength = 100
      locked   = yes
      experience = 20
    }
  }
  landunit =
  { name     = "Gibraltar Command"
    location = 348
    id       = { type = 12700 id = 12 }
    division =
    { id       = { type = 12700 id = 13 }
      name     = "Gibraltar Defence Force"
      type     = garrison
      strength = 100
      locked   = yes
      experience = 20
    }
  }
  landunit =
  { name     = "Ceylon Command"
    location = 1517
    id       = { type = 12700 id = 14 }
    division =
    { id       = { type = 12700 id = 15 }
      name     = "Ceylon Defence Force"
      type     = garrison
      strength = 100
      locked   = yes
      experience = 20
    }
  }
  landunit =
  { name     = "Malta Command"
    location = 31
    id       = { type = 12700 id = 16 }
    division =
    { id       = { type = 12700 id = 17 }
      name     = "Malta Defence Force"
      type     = garrison
      strength = 100
      locked   = yes
      experience = 20
    }
  }
  landunit =
  { name     = "Middle East Command"
    location = 1797
    id       = { type = 12700 id = 18 }
    division =
    { id       = { type = 12700 id = 19 }
      name     = "7th Infantry Division"
      type     = infantry
      strength = 100
      experience = 20
    }
    division =
    { id       = { type = 12700 id = 20 }
      name     = "8th Infantry Division"
      type     = infantry
      strength = 100
      experience = 20
    }
  }
  landunit =
  { name     = "1st Indian Army"
    location = 1469
    id       = { type = 12700 id = 21 }
    division =
    { id       = { type = 12700 id = 22 }
      name     = "1st Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "2nd Indian Army"
    location = 1285
    id       = { type = 12700 id = 23 }
    division =
    { id            = { type = 12700 id = 24 }
      name          = "2nd Indian Infantry"
      type          = infantry
      extra         = artillery
      brigade_model = 2
      strength      = 100
      experience = 15
    }
  }
  landunit =
  { name     = "3rd Indian Army"
    location = 1299
    id       = { type = 12700 id = 25 }
    division =
    { id       = { type = 12700 id = 26 }
      name     = "3rd Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "4th Indian Army"
    location = 1494
    id       = { type = 12700 id = 27 }
    division =
    { id       = { type = 12700 id = 28 }
      name     = "4th Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "5th Indian Army"
    location = 1478
    id       = { type = 12700 id = 29 }
    division =
    { id       = { type = 12700 id = 30 }
      name     = "5th Indian Infantry"
      type     = infantry
      extra    = engineer
      brigade_model = 8
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "6th Indian Army"
    location = 1461
    id       = { type = 12700 id = 31 }
    division =
    { id       = { type = 12700 id = 32 }
      name     = "6th Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "7th Indian Army"
    location = 1505
    id       = { type = 12700 id = 33 }
    division =
    { id       = { type = 12700 id = 34 }
      name     = "7th Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "8th Indian Army"
    location = 1513
    id       = { type = 12700 id = 35 }
    division =
    { id       = { type = 12700 id = 36 }
      name     = "8th Indian Infantry"
      type     = infantry
      extra    = anti_tank
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "9th Indian Army"
    location = 1509
    id       = { type = 12700 id = 37 }
    division =
    { id       = { type = 12700 id = 38 }
      name     = "9th Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "10th Indian Army"
    location = 1514
    id       = { type = 12700 id = 39 }
    division =
    { id       = { type = 12700 id = 40 }
      name     = "10th Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "11th Indian Army"
    location = 1515
    id       = { type = 12700 id = 41 }
    division =
    { id       = { type = 12700 id = 42 }
      name     = "11th Indian Infantry"
      type     = infantry
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "12th Indian Army"
    location = 1516
    id       = { type = 12700 id = 43 }
    division =
    { id       = { type = 12700 id = 44 }
      name     = "12th Indian Infantry"
      type     = infantry
      extra    = engineer
      brigade_model = 8
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Sudanese Colonial Army"
    location = 1065
    id       = { type = 12700 id = 45 }
    division =
    { id       = { type = 12700 id = 46 }
      name     = "1st Sudanese Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Sudanese Colonial Guard"
    location = 1066
    id       = { type = 12700 id = 47 }
    division =
    { id       = { type = 12700 id = 48 }
      name     = "2nd Sudanese Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Sudanese Colonial Troops"
    location = 1041
    id       = { type = 12700 id = 49 }
    division =
    { id       = { type = 12700 id = 50 }
      name     = "3rd Sudanese Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Ugandan Colonial Army"
    location = 1064
    id       = { type = 12700 id = 51 }
    division =
    { id       = { type = 12700 id = 52 }
      name     = "1st Ugandan Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Ugandan Colonial Corps"
    location = 1060
    id       = { type = 12700 id = 53 }
    division =
    { id       = { type = 12700 id = 54 }
      name     = "2nd Ugandan Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Kenyan Colonial Army"
    location = 1064
    id       = { type = 12700 id = 55 }
    division =
    { id       = { type = 12700 id = 56 }
      name     = "1st Kenyan Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Kenyan Colonial Corps"
    location = 1059
    id       = { type = 12700 id = 57 }
    division =
    { id       = { type = 12700 id = 58 }
      name     = "2nd Kenyan Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Tanganyikan Colonial Army"
    location = 1061
    id       = { type = 12700 id = 59 }
    division =
    { id       = { type = 12700 id = 60 }
      name     = "1st Tanganyikan Colonials"
      type     = militia
      strength = 100
      experience = 15
    }
  }
  landunit =
  { name     = "Tanganyikan Colonial Corps"
    location = 1141
    id       = { type = 12700 id = 61 }
    division =
    { id            = { type = 12700 id = 62 }
      name          = "2nd Tanganyikan Colonials"
      type          = militia
      strength      = 100
      extra         = artillery
      brigade_model = 0
      experience = 15
    }
  }
##################
# AI Garrisons
##################

	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 336 }
			name = "Malta Garrison"
			type = bergsjaeger
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 337 }
			name = "Gibraltar Garrison"
			type = bergsjaeger
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 338 }
			name = "Cyprus Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 339 }
			name = "Suez Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 386 }
			name = "Suez Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 387 }
			name = "Suez Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 340 }
			name = "Belfast Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}

	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 341 }
			name = "Plymouth Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 342 }
			name = "Portsmouth Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 343 }
			name = "Dover Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 344 }
			name = "Bristol Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 345 }
			name = "Norwich Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 346 }
			name = "Liverpool Garrison"
			type = infantry
			extra = engineer
			brigade_model = 9
			model = 2
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 347 }
			name = "Sheffield Garrison"
			type = infantry
			extra = engineer
			brigade_model = 9
			model = 2
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 348 }
			name = "Blackpool Garrison"
			type = infantry
			extra = engineer
			brigade_model = 9
			model = 2
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 349 }
			name = "Sunderland Garrison"
			type = infantry
			extra = engineer
			brigade_model = 9
			model = 2
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 350 }
			name = "Edinburgh Garrison"
			type = infantry
			extra = engineer
			brigade_model = 9
			model = 2
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 351 }
			name = "Glasgow Garrison"
			type = infantry
			extra = engineer
			brigade_model = 9
			model = 2
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 352 }
			name = "Alexandria Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 353 }
			name = "Aleppo Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 354 }
			name = "Triploi Garrison"
			type = infantry
			extra = engineer
			brigade_model = 9
			model = 2
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 355 }
			name = "Beirut Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 356 }
			name = "Georgetown Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 357 }
			name = "Falklands Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 358 }
			name = "Alexandria Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 359 }
			name = "Home Army"
			type = garrison
			model = 0
			extra = engineer
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 360 }
			name = "Home Army"
			type = garrison
			model = 0
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 361 }
			name = "Home Army"
			type = garrison
			model = 0
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 362 }
			name = "Home Army"
			type = garrison
			model = 0
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 363 }
			name = "Home Army"
			type = garrison
			model = 0
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 364 }
			name = "Home Army"
			type = garrison
			model = 0
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 365 }
			name = "Fuka Garrison"
			type = garrison
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 366 }
			name = "Garrison El Alamein"
			type = garrison
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 367 }
			name = "Bardia Garrison"
			type = garrison
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 368 }
			name = "Tobruk Garrison"
			type = garrison
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 369 }
			name = "Bengazi Garrison"
			type = garrison
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 370 }
			name = "Alexandria Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 371 }
			name = "Newfoundland Garrison"
			type = bergsjaeger
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 372 }
			name = "Gibraltar Garrison"
			type = bergsjaeger
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 373 }
			name = "Malta Garrison"
			type = bergsjaeger
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 374 }
			name = "8th Army-El Alamein"
			type = armor
			model = 2
			extra = sp_artillery
			brigade_model = 1
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 375 }
			name = "8th Army-El Alamein"
			type = motorized
			model = 0
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 376 }
			name = "8th Army-El Alamein"
			type = motorized
			model = 0
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 377 }
			name = "Crete Defence Force"
			type = infantry
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 378 }
			name = "Crete Defence Force"
			type = infantry
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 379 }
			name = "Narvik"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 380 }
			name = "Cardiff"
			type = garrison
			model = 1
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 381 }
			name = "Tel Aviv"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 382 }
			name = "Tel Aviv"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 383 }
			name = "Gaza"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 384 }
			name = "Gaza"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 385 }
			name = "el-Arish"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 388 }
			name = "Port Said Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 389 }
			name = "Port Said Garrison"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 390 }
			name = "el-Arish"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 391 }
			name = "Haifa"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 392 }
			name = "Haifa"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 393 }
			name = "Alamein"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 394 }
			name = "Alamein"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 395 }
			name = "Tobruk"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 396 }
			name = "Bardia"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 397 }
			name = "fuka"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 398 }
			name = "Tripoli"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 399 }
			name = "Tripoli"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 400 }
			name = "Beirut"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 401 }
			name = "Beirut"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 402 }
			name = "Aleppo"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 403 }
			name = "Aleppo"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 404 }
			name = "Cyprus"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 405 }
			name = "Tanta"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 406 }
			name = "Zaqazig"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 407 }
			name = "temp"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 408 }
			name = "temp"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}
	landdivision = {
		dormant = yes locked = yes
	        	id = { type = 12700 id = 409 }
			name = "temp"
			type = infantry
			model = 2
			extra = engineer
			brigade_model = 9
		}

###### Royal Navy ######
  navalunit =
  { name     = "Home Fleet"
    id       = { type = 12700 id = 84 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 85 }
      name  = "HMS Nelson"
      type  = battleship
      model = 2
      extra = naval_fire_controll_l brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 86 }
      name  = "HMS Rodney"
      type  = battleship
      extra = naval_fire_controll_l brigade_model = 0
      model = 2
    }
    division =
    { id    = { type = 12700 id = 87 }
      name  = "HMS Royal Sovereign"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12700 id = 88 }
      name  = "HMS Royal Oak"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12700 id = 89 }
      name  = "HMS Resolution"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12700 id = 90 }
      name  = "HMS Ramillies"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12700 id = 91 }
      name  = "HMS Hood"
      type  = battlecruiser
      model = 2
      extra = naval_fire_controll_l brigade_model = 0
      experience = 10
    }
    division =
    { id    = { type = 12700 id = 92 }
      name  = "HMS Renown"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 252 }
      name  = "HMS Repulse"
      type  = battlecruiser
      model = 2
      extra = naval_fire_controll_l brigade_model = 0
    }
    division =
    { id            = { type = 12700 id = 93 }
      name          = "HMS Furious"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 12700 id = 96 }
      name  = "HMS Cairo"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 97 }
      name  = "HMS Galathea"
      type  = light_cruiser
      model = 2
      extra = naval_fire_controll_s brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 98 }
      name  = "HMS Dunedin"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 99 }
      name  = "HMS Neptune"
      type  = light_cruiser
      model = 2
      extra = naval_fire_controll_s brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 100 }
      name  = "HMS Orion"
      type  = light_cruiser
      model = 2
      extra = naval_fire_controll_s brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 101 }
      name  = "1st Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12700 id = 102 }
      name  = "2nd Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12700 id = 103 }
      name  = "3rd Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12700 id = 268 }
      name  = "4th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { id       = { type = 12700 id = 104 }
    name     = "HMS Argus"
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id            = { type = 12700 id = 105 }
      name          = "HMS Argus"
      type          = carrier
      model         = 0
      extra         = cag
      brigade_model = 2
    }
  }
  # 2nd Submarine Squadron#
  navalunit =
  { name     = "2nd Submarine Squadron"
    id       = { type = 12700 id = 106 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 107 }
      name  = "3rd Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 108 }
      name  = "4th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 109 }
      name  = "5th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 110 }
      name  = "6th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 111 }
      name  = "7th Submarine Flotilla"
      type  = submarine
      model = 1
    }
  }
  # 1st Transport Squadron#
  navalunit =
  { name     = "1st Transport Squadron"
    id       = { type = 12700 id = 112 }
    location = 1505 # Hyderabad
    base     = 1505
    division =
    { id    = { type = 12700 id = 113 }
      name  = "Suffolk Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 114 }
      name  = "Trojan Star Flotilla"
      type  = transport
      model = 0
    }
  }
  # 2nd Transport Squadron#
  navalunit =
  { name     = "2nd Transport Squadron"
    id       = { type = 12700 id = 117 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 118 }
      name  = "Empire Arquebus Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 119 }
      name  = "Hororata Flotilla"
      type  = transport
      model = 0
    }
  }
  # 3rd Transport Squadron#
  navalunit =
  { name     = "3rd Transport Squadron"
    id       = { type = 12700 id = 122 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 123 }
      name  = "Clan Macauley Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 124 }
      name  = "Empire Captain Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 125 }
      name  = "Andes Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 126 }
      name  = "Empire Charmain Flotilla"
      type  = transport
      model = 0
    }
  }
  # 4th Transport Squadron#
  navalunit =
  { name     = "4th Transport Squadron"
    id       = { type = 12700 id = 127 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 128 }
      name  = "Essex Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 129 }
      name  = "Maloja Flotilla"
      type  = transport
      model = 0
    }
  }
  # 5th Transport Squadron#
  navalunit =
  { name     = "5th Transport Squadron"
    id       = { type = 12700 id = 132 }
    location = 23 # Plymouth
    base     = 23
    division =
    { id    = { type = 12700 id = 133 }
      name  = "Empire Splendour Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 134 }
      name  = "Sam Torch Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 135 }
      name  = "Resolution Flotilla"
      type  = transport
      model = 0
    }
  }
  # Non-Associated Destroyers#
  navalunit =
  { name     = "1st Destroyer Squadron"
    id       = { type = 12700 id = 137 }
    location = 23 # Plymouth
    base     = 23
    division =
    { id    = { type = 12700 id = 269 }
      name  = "5th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 138 }
      name  = "6th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12700 id = 139 }
      name  = "7th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "2nd Destroyer Squadron"
    id       = { type = 12700 id = 140 }
    location = 14
    base     = 14
    division =
    { id    = { type = 12700 id = 270 }
      name  = "8nd Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 141 }
      name  = "9th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "3rd Destroyer Squadron"
    id       = { type = 12700 id = 142 }
    location = 14 # Actually based at Milford Haven, but that is located in the same province as Cardiff.
    base     = 14
    division =
    { id    = { type = 12700 id = 271 }
      name  = "10rd Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 143 }
      name  = "11th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "4th Destroyer Squadron"
    id       = { type = 12700 id = 144 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 272 }
      name  = "12th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 145 }
      name  = "13th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "5th Destroyer Squadron"
    id       = { type = 12700 id = 146 }
    location = 21 # Portsmouth
    base     = 21
    division =
    { id    = { type = 12700 id = 273 }
      name  = "14th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 147 }
      name  = "15th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12700 id = 148 }
      name  = "16th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { name     = "Mediterranean Fleet"
    id       = { type = 12700 id = 149 }
    location = 906 # Alexandria
    base     = 906
    division =
    { id    = { type = 12700 id = 150 }
      name  = "HMS Queen Elizabeth"
      type  = battleship
      model = 1
      experience = 10
    }
    division =
    { id    = { type = 12700 id = 151 }
      name  = "HMS Barham"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12700 id = 152 }
      name  = "HMS Valiant"
      type  = battleship
      model = 1
      experience = 10
    }
    division =
    { id    = { type = 12700 id = 253 }
      name  = "HMS Malaya"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 12700 id = 254 }
      name  = "HMS Warspite"
      type  = battleship
      model = 1
      experience = 10
    }
    division =
    { id    = { type = 12700 id = 153 }
      name  = "HMS Revenge"
      type  = battleship
      model = 1
    }
    division =
    { id            = { type = 12700 id = 154 }
      name          = "HMS Courageous"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id            = { type = 12700 id = 157 }
      name          = "HMS Glorious"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 12700 id = 158 }
      name  = "HMS Devonshire"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 159 }
      name  = "HMS London"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 160 }
      name  = "HMS Shropshire"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 161 }
      name  = "HMS Sussex"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 163 }
      name  = "HMS Exeter"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 164 }
      name  = "HMS York"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 165 }
      name  = "HMS Coventry"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 166 }
      name  = "HMS Curlew"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 167 }
      name  = "HMS Delhi"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 168 }
      name  = "HMS Despatch"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 169 }
      name  = "HMS Durban"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 170 }
      name  = "HMS Arethusa"
      type  = light_cruiser
      model = 2
      experience = 10
      extra = naval_fire_controll_s brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 171 }
      name  = "17th Destroyer Flotilla"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12700 id = 172 }
      name  = "18th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 173 }
      name  = "19th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 174 }
      name  = "20th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 175 }
      name  = "21st Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 176 }
      name  = "22nd Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
  }
  # 1st Submarine Squadron#
  navalunit =
  { name     = "1st Submarine Squadron"
    id       = { type = 12700 id = 177 }
    location = 906 # Alexandria
    base     = 906
    division =
    { id    = { type = 12700 id = 178 }
      name  = "1st Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 12700 id = 179 }
      name  = "2nd Submarine Flotilla"
      type  = submarine
      model = 2
    }
  }
  # America & West Indies Station#
  navalunit =
  { name     = "America & West Indies Station"
    id       = { type = 12700 id = 180 }
    location = 538 # Bermuda
    base     = 538
    division =
    { id    = { type = 12700 id = 181 }
      name  = "HMS Dragon"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 182 }
      name  = "HMS Ajax"
      type  = light_cruiser
      model = 2
      extra = naval_fire_controll_s brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 274 }
      name  = "23rd Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 183 }
      name  = "24th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
  }
  # Africa Station#
  navalunit =
  { name     = "Africa Station"
    id       = { type = 12700 id = 184 }
    location = 988 # Freetown
    base     = 988
    division =
    { id    = { type = 12700 id = 261 }
      name  = "HMS Leander"
      type  = light_cruiser
      model = 2
      extra = naval_fire_controll_s brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 185 }
      name  = "HMS Carlisle"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 275 }
      name  = "25th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 186 }
      name  = "26th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
  }
  # East Indies Station#
  navalunit =
  { name     = "East Indies Station"
    id       = { type = 12700 id = 187 }
    location = 1517
    base     = 1517
    division =
    { id    = { type = 12700 id = 188 }
      name  = "HMS Norfolk"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 189 }
      name  = "HMS Diomede"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 190 }
      name  = "HMS Emerald"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 191 }
      name  = "HMS Enterprise"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 276 }
      name  = "27th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 192 }
      name  = "28th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
  }
  # China Station#
  navalunit =
  { name     = "China Station"
    id       = { type = 12700 id = 193 }
    location = 1315 # Hong Kong
    base     = 1315
    division =
    { id            = { type = 12700 id = 194 }
      name          = "HMS Eagle"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 1
    }
    division =
    { id    = { type = 12700 id = 201 }
      name  = "HMS Capetown"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 202 }
      name  = "29th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 203 }
      name  = "30th Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
  }
  # 3rd Submarine Squadron#
  navalunit =
  { name     = "3rd Submarine Squadron"
    id       = { type = 12700 id = 204 }
    location = 1315 # Hong Kong
    base     = 1315
    division =
    { id    = { type = 12700 id = 205 }
      name  = "8th Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 12700 id = 206 }
      name  = "9th Submarine Flotilla"
      type  = submarine
      model = 2
    }
  }
  # Reserve Fleet#
  navalunit =
  { name     = "Reserve Fleet"
    id       = { type = 12700 id = 207 }
    location = 21 # Southampton
    base     = 21
    division =
    { id            = { type = 12700 id = 208 }
      name          = "HMS Hermes"
      type          = carrier
      model         = 0
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 12700 id = 209 }
      name  = "HMS Effingham"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 210 }
      name  = "HMS Frobisher"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 211 }
      name  = "HMS Dorsetshire"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 155 }
      name  = "HMS Hawkins"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 156 }
      name  = "HMS Berwick"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 162 }
      name  = "HMS Cornwall"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 195 }
      name  = "HMS Cumberland"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 196 }
      name  = "HMS Suffolk"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 197 }
      name  = "HMS Kent"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 12700 id = 212 }
      name  = "HMS Achilles"
      type  = light_cruiser
      model = 2
      extra = naval_fire_controll_s brigade_model = 0
    }
    division =
    { id    = { type = 12700 id = 213 }
      name  = "HMS Caledon"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 214 }
      name  = "HMS Calypso"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 215 }
      name  = "HMS Caradoc"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 216 }
      name  = "HMS Calcutta"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 217 }
      name  = "HMS Colombo"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 218 }
      name  = "HMS Cardiff"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 219 }
      name  = "HMS Ceres"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 220 }
      name  = "HMS Curacao"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 221 }
      name  = "HMS Danae"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 222 }
      name  = "HMS Dauntless"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 12700 id = 223 }
      name  = "31st Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 12700 id = 224 }
      name  = "32nd Destroyer Flotilla"
      type  = destroyer
      model = 0
    }
  }
  # #################
  # Royal Airforce #
  # #################
  airunit =
  { location = 14
    base     = 14
    id       = { type = 12700 id = 63 }
    name     = "1st Tactical Wing"
    division =
    { id       = { type = 12700 id = 64 }
      name     = "No.1 RAF Tactical Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
      experience = 10
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 12700 id = 65 }
    name     = "RAF Strategic Bomber Command"
    division =
    { id       = { type = 12700 id = 66 }
      name     = "No.2 RAF Strategic Group"
      type     = strategic_bomber
      model    = 0
      strength = 100
      experience = 10
    }
    division =
    { id       = { type = 12700 id = 68 }
      name     = "no.3 RAF Strategic Group"
      type     = strategic_bomber
      model    = 0
      strength = 100
      experience = 10
    }
    division =
    { id       = { type = 12700 id = 70 }
      name     = "no.4 RAF Strategic Group"
      type     = strategic_bomber
      model    = 0
      strength = 100
      experience = 10
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 12700 id = 251 }
    name     = "2nd Tactical Wing"
    division =
    { id       = { type = 12700 id = 71 }
      name     = "No.5 RAF Tactical Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
      experience = 10
    }
  }
  airunit =
  { location = 14
    base     = 14
    id       = { type = 12700 id = 72 }
    name     = "1st Fighter Wing"
    division =
    { id       = { type = 12700 id = 73 }
      name     = "No.11 RAF Fighter Group"
      type     = interceptor
      model    = 0
      strength = 100
      experience = 20
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 12700 id = 74 }
    name     = "2nd Fighter Wing"
    division =
    { id       = { type = 12700 id = 75 }
      name     = "No.12 RAF Fighter Group"
      type     = interceptor
      model    = 0
      strength = 100
      experience = 20
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 12700 id = 76 }
    name     = "3rd Fighter Wing"
    division =
    { id       = { type = 12700 id = 77 }
      name     = "No.13 RAF Fighter Group"
      type     = interceptor
      model    = 0
      strength = 100
      experience = 20
    }
  }
  airunit =
  { location = 1798
    base     = 1798
    id       = { type = 12700 id = 78 }
    name     = "Middle East Air Command"
    division =
    { id       = { type = 12700 id = 79 }
      name     = "Middle East Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
      experience = 10
    }
  }
  airunit =
  { location = 1505
    base     = 1505
    id       = { type = 12700 id = 80 }
    name     = "India Air Command"
    division =
    { id       = { type = 12700 id = 81 }
      name     = "Indian Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
      experience = 10
    }
  }
  airunit =
  { location = 1353
    base     = 1353
    id       = { type = 12700 id = 82 }
    name     = "Far East Air Command"
    division =
    { id       = { type = 12700 id = 83 }
      name     = "Far East Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
      experience = 10
    }
  }
  # Warships Under Construction#
  division_development =
  { name  = "33rd Destroyer Flotilla"
    type  = destroyer
    model = 2
    cost  = 1.5
    id    = { type = 12700 id = 500 }
    date  = { year = 1936 month = march day = 1 }
  }
  division_development =
  { name  = "34th Destroyer Flotilla"
    type  = destroyer
    model = 2
    cost  = 1.5
    id    = { type = 12700 id = 501 }
    date  = { year = 1936 month = april day = 1 }
  }
  division_development =
  { name  = "10th Submarine Flotilla"
    type  = submarine
    model = 2
    cost  = 1.5
    id    = { type = 12700 id = 502 }
    date  = { year = 1936 month = march day = 1 }
  }
}
