# Air bases

# Kiev
province = {
	id = 238
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Odessa
province = {
	id = 233
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 5
		current_size = 5
		}
	}

# Kharkov
province = {
	id = 248
	air_base = {
		size = 5
		current_size = 3 # Still damaged after last battles
		}
	}


province = {
	id = 277
	air_base = {
		size = 5
		current_size = 5
		}
	}


province = {
	id = 250
	air_base = {
		size = 5
		current_size = 5
		}
	}

country = {
    tag = GER

	ai = "fallblau_GER_I.ai"

    policy = {
	date = { year = 0 month = january day = 0 }
	democratic = 1
	political_left = 1
	free_market = 5
	freedom = 2
	professional_army = 5
	defense_lobby = 10
	interventionism = 10
    }


#
# LEADERS
##########################

steal_leader = 31142 # Jany - HUngary
steal_leader = 4412 # Davidescu - Romania
steal_leader = 416 #Schuster

# Italians
steal_leader = 6102 #Messe - HQ
steal_leader = 6108 #Nasi - Alpini
steal_leader = 6150 #Zingales - II Corps
steal_leader = 6077 #Gariboldi - XXXV Corps


#
# Basic pack 1942, Eastern Front
#####################################

steal_leader = 2
steal_leader = 4
steal_leader = 5
steal_leader = 6
steal_leader = 8
steal_leader = 9
steal_leader = 10
steal_leader = 13
steal_leader = 14
steal_leader = 15
steal_leader = 17
steal_leader = 18
steal_leader = 19
steal_leader = 20
steal_leader = 21
steal_leader = 22
steal_leader = 23
steal_leader = 24
steal_leader = 26
steal_leader = 27
steal_leader = 28
steal_leader = 29
steal_leader = 30
steal_leader = 31
steal_leader = 32
steal_leader = 33
steal_leader = 34
steal_leader = 36
steal_leader = 37
steal_leader = 38
steal_leader = 39
steal_leader = 40
steal_leader = 41
steal_leader = 43
steal_leader = 47
steal_leader = 50
steal_leader = 51
steal_leader = 52
steal_leader = 53
steal_leader = 54
steal_leader = 55
steal_leader = 56
steal_leader = 57
steal_leader = 58
steal_leader = 60
steal_leader = 62
steal_leader = 63
steal_leader = 64
steal_leader = 65
steal_leader = 67
steal_leader = 68
steal_leader = 69
steal_leader = 71
steal_leader = 72
steal_leader = 73
steal_leader = 74
steal_leader = 75
steal_leader = 77
steal_leader = 78
steal_leader = 79
steal_leader = 80
steal_leader = 82
steal_leader = 83
steal_leader = 84
steal_leader = 85
steal_leader = 86
steal_leader = 87
steal_leader = 88
steal_leader = 89
steal_leader = 90
steal_leader = 91
steal_leader = 92
steal_leader = 93
steal_leader = 95
steal_leader = 97
steal_leader = 98
steal_leader = 100
steal_leader = 101
steal_leader = 102
steal_leader = 103
steal_leader = 104
steal_leader = 106
steal_leader = 108
steal_leader = 110
steal_leader = 111
steal_leader = 113
steal_leader = 115
steal_leader = 116
steal_leader = 117
steal_leader = 119
steal_leader = 121
steal_leader = 123
steal_leader = 124
steal_leader = 127
steal_leader = 128
steal_leader = 129
steal_leader = 131
steal_leader = 132
steal_leader = 133
steal_leader = 135
steal_leader = 136
steal_leader = 137
steal_leader = 138
steal_leader = 140
steal_leader = 141
steal_leader = 142
steal_leader = 143
steal_leader = 144
steal_leader = 146
steal_leader = 147
steal_leader = 150
steal_leader = 152
steal_leader = 154
steal_leader = 155
steal_leader = 156
steal_leader = 158
steal_leader = 159
steal_leader = 160
steal_leader = 162
steal_leader = 163
steal_leader = 164
steal_leader = 165
steal_leader = 166
steal_leader = 168
steal_leader = 169
steal_leader = 170
steal_leader = 171
steal_leader = 172
steal_leader = 173
steal_leader = 174
steal_leader = 175
steal_leader = 176
steal_leader = 177
steal_leader = 180
steal_leader = 181
steal_leader = 182
steal_leader = 183
steal_leader = 184
steal_leader = 185
steal_leader = 187
steal_leader = 188
steal_leader = 189
steal_leader = 190
steal_leader = 191
steal_leader = 192
steal_leader = 193
steal_leader = 194
steal_leader = 195
steal_leader = 196
steal_leader = 198
steal_leader = 200
steal_leader = 201
steal_leader = 204
steal_leader = 205
steal_leader = 206
steal_leader = 210
steal_leader = 211
steal_leader = 212
steal_leader = 213
steal_leader = 214
steal_leader = 215
steal_leader = 216
steal_leader = 217
steal_leader = 218
steal_leader = 219
steal_leader = 220
steal_leader = 221
steal_leader = 223
steal_leader = 224
steal_leader = 226
steal_leader = 227
steal_leader = 228
steal_leader = 231
steal_leader = 232
steal_leader = 233
steal_leader = 234
steal_leader = 235
steal_leader = 237
steal_leader = 238
steal_leader = 239
steal_leader = 240
steal_leader = 241
steal_leader = 242
steal_leader = 243
steal_leader = 244
steal_leader = 245
steal_leader = 246
steal_leader = 248
steal_leader = 249
steal_leader = 250
steal_leader = 251
steal_leader = 253
steal_leader = 254
steal_leader = 256
steal_leader = 257
steal_leader = 258
steal_leader = 259
steal_leader = 260
steal_leader = 261
steal_leader = 263
steal_leader = 265
steal_leader = 266
steal_leader = 268
steal_leader = 269
steal_leader = 270
steal_leader = 271
steal_leader = 272
steal_leader = 273
steal_leader = 275
steal_leader = 276
steal_leader = 278
steal_leader = 279
steal_leader = 280
steal_leader = 281
steal_leader = 282
steal_leader = 284
steal_leader = 285
steal_leader = 286
steal_leader = 287
steal_leader = 288
steal_leader = 289
steal_leader = 290
steal_leader = 291
steal_leader = 292
steal_leader = 293
steal_leader = 294
steal_leader = 295
steal_leader = 296
steal_leader = 297
steal_leader = 298
steal_leader = 299
steal_leader = 303
steal_leader = 304
steal_leader = 305
steal_leader = 306
steal_leader = 307
steal_leader = 308
steal_leader = 310
steal_leader = 311
steal_leader = 314
steal_leader = 316
steal_leader = 318
steal_leader = 321
steal_leader = 322
steal_leader = 324
steal_leader = 325
steal_leader = 327
steal_leader = 329
steal_leader = 330
steal_leader = 332
steal_leader = 334
steal_leader = 335
steal_leader = 336
steal_leader = 338
steal_leader = 339
steal_leader = 342
steal_leader = 343
steal_leader = 344
steal_leader = 345
steal_leader = 346
steal_leader = 347
steal_leader = 348
steal_leader = 350
steal_leader = 351
steal_leader = 352
steal_leader = 353
steal_leader = 354
steal_leader = 356
steal_leader = 357
steal_leader = 359
steal_leader = 360
steal_leader = 361
steal_leader = 364
steal_leader = 366
steal_leader = 368
steal_leader = 369
steal_leader = 370
steal_leader = 371
steal_leader = 372
steal_leader = 426
steal_leader = 427
steal_leader = 428
steal_leader = 430
steal_leader = 431
steal_leader = 432
steal_leader = 433
steal_leader = 434
steal_leader = 436
steal_leader = 437
steal_leader = 438
steal_leader = 441
steal_leader = 444
steal_leader = 447
steal_leader = 448
steal_leader = 449
steal_leader = 450
steal_leader = 451
steal_leader = 452
steal_leader = 454
steal_leader = 455
steal_leader = 456
steal_leader = 459
steal_leader = 460
steal_leader = 462
steal_leader = 463
steal_leader = 465
steal_leader = 466
steal_leader = 468
steal_leader = 470
steal_leader = 471
steal_leader = 475
steal_leader = 477
steal_leader = 478
steal_leader = 479
steal_leader = 480
steal_leader = 481
steal_leader = 482
steal_leader = 484
steal_leader = 485
steal_leader = 486
steal_leader = 487
steal_leader = 489
steal_leader = 493
steal_leader = 494
steal_leader = 495
steal_leader = 498
steal_leader = 500
steal_leader = 503
steal_leader = 504
steal_leader = 505
steal_leader = 506
steal_leader = 508
steal_leader = 509
steal_leader = 512
steal_leader = 513
steal_leader = 522
steal_leader = 523
steal_leader = 526
steal_leader = 527
steal_leader = 530
steal_leader = 531
steal_leader = 533
steal_leader = 534
steal_leader = 535
steal_leader = 536
steal_leader = 538
steal_leader = 540
steal_leader = 542
steal_leader = 546
steal_leader = 548
steal_leader = 549
steal_leader = 552
steal_leader = 553
steal_leader = 556
steal_leader = 557
steal_leader = 559
steal_leader = 562
steal_leader = 563
steal_leader = 564
steal_leader = 565
steal_leader = 567
steal_leader = 568
steal_leader = 569
steal_leader = 570
steal_leader = 571
steal_leader = 572
steal_leader = 573
steal_leader = 575
steal_leader = 576
steal_leader = 580
steal_leader = 581
steal_leader = 582
steal_leader = 584
steal_leader = 585
steal_leader = 586
steal_leader = 589
steal_leader = 592
steal_leader = 593
steal_leader = 594
steal_leader = 595
steal_leader = 596
steal_leader = 600
steal_leader = 601
steal_leader = 602
steal_leader = 603
steal_leader = 605
steal_leader = 608
steal_leader = 609
steal_leader = 612
steal_leader = 613
steal_leader = 614
steal_leader = 615
steal_leader = 616
steal_leader = 617
steal_leader = 618
steal_leader = 619
steal_leader = 620
steal_leader = 621
steal_leader = 622
steal_leader = 623
steal_leader = 632
steal_leader = 633
steal_leader = 634
steal_leader = 635
steal_leader = 636
steal_leader = 637
steal_leader = 638
steal_leader = 639
steal_leader = 640
steal_leader = 641
steal_leader = 642
steal_leader = 643
steal_leader = 644
steal_leader = 645
steal_leader = 646
steal_leader = 647
steal_leader = 648
steal_leader = 649
steal_leader = 650
steal_leader = 651
steal_leader = 652
steal_leader = 653
steal_leader = 654
steal_leader = 655
steal_leader = 657
steal_leader = 658
steal_leader = 659
steal_leader = 660
steal_leader = 661
steal_leader = 663
steal_leader = 664
steal_leader = 665
steal_leader = 666
steal_leader = 667
steal_leader = 668
steal_leader = 669
steal_leader = 670
steal_leader = 672
steal_leader = 673
steal_leader = 675
steal_leader = 676
steal_leader = 677
steal_leader = 678
steal_leader = 679
steal_leader = 680
steal_leader = 681
steal_leader = 682
steal_leader = 683
steal_leader = 684
steal_leader = 685
steal_leader = 686
steal_leader = 687
steal_leader = 688
steal_leader = 689
steal_leader = 690
steal_leader = 691
steal_leader = 692
steal_leader = 693
steal_leader = 694
steal_leader = 695
steal_leader = 696
steal_leader = 698
steal_leader = 699
steal_leader = 701
steal_leader = 703
steal_leader = 704
steal_leader = 706
steal_leader = 707
steal_leader = 708
steal_leader = 709
steal_leader = 710
steal_leader = 711
steal_leader = 712
steal_leader = 713
steal_leader = 714
steal_leader = 716
steal_leader = 718
steal_leader = 719
steal_leader = 720
steal_leader = 722
steal_leader = 723
steal_leader = 725
steal_leader = 726
steal_leader = 727
steal_leader = 728
steal_leader = 729
steal_leader = 730
steal_leader = 731
steal_leader = 732
steal_leader = 734
steal_leader = 735
steal_leader = 736
steal_leader = 737
steal_leader = 738
steal_leader = 739
steal_leader = 740
steal_leader = 742
steal_leader = 743
steal_leader = 744
steal_leader = 745
steal_leader = 746
steal_leader = 747
steal_leader = 748
steal_leader = 749
steal_leader = 750
steal_leader = 752
steal_leader = 753
steal_leader = 754
steal_leader = 755
steal_leader = 756
steal_leader = 757
steal_leader = 758
steal_leader = 759
steal_leader = 760
steal_leader = 761
steal_leader = 762
steal_leader = 763
steal_leader = 764
steal_leader = 765
steal_leader = 766
steal_leader = 768
steal_leader = 769
steal_leader = 770
steal_leader = 771
steal_leader = 772
steal_leader = 773
steal_leader = 774
steal_leader = 775
steal_leader = 776
steal_leader = 777
steal_leader = 778
steal_leader = 779
steal_leader = 780
steal_leader = 783
steal_leader = 784
steal_leader = 785
steal_leader = 787
steal_leader = 788
steal_leader = 789
steal_leader = 790
steal_leader = 791
steal_leader = 792
steal_leader = 794
steal_leader = 795
steal_leader = 796
steal_leader = 799
steal_leader = 800
steal_leader = 801
steal_leader = 805
steal_leader = 806
steal_leader = 807
steal_leader = 808
steal_leader = 809
steal_leader = 810
steal_leader = 811
steal_leader = 812
steal_leader = 813
steal_leader = 815
steal_leader = 816
steal_leader = 817
steal_leader = 818
steal_leader = 819
steal_leader = 820
steal_leader = 821
steal_leader = 822
steal_leader = 824
steal_leader = 825
steal_leader = 827
steal_leader = 828
steal_leader = 829
steal_leader = 830
steal_leader = 832
steal_leader = 833
steal_leader = 835
steal_leader = 836
steal_leader = 837
steal_leader = 901
steal_leader = 902
steal_leader = 903
steal_leader = 904
steal_leader = 905
steal_leader = 906
steal_leader = 907
steal_leader = 908
steal_leader = 909
steal_leader = 910
steal_leader = 911
steal_leader = 913
steal_leader = 914
steal_leader = 915
steal_leader = 917
steal_leader = 918
steal_leader = 919
steal_leader = 920
steal_leader = 922
steal_leader = 923
steal_leader = 924
steal_leader = 925
steal_leader = 926
steal_leader = 927
steal_leader = 928
steal_leader = 929
steal_leader = 930
steal_leader = 931
steal_leader = 932
steal_leader = 933
steal_leader = 934
steal_leader = 935
steal_leader = 936
steal_leader = 937
steal_leader = 938
steal_leader = 939
steal_leader = 940
steal_leader = 941
steal_leader = 942
steal_leader = 943
steal_leader = 944
steal_leader = 945
steal_leader = 946
steal_leader = 948
steal_leader = 949
steal_leader = 950
steal_leader = 951
steal_leader = 952
steal_leader = 954
steal_leader = 955
steal_leader = 956
steal_leader = 957
steal_leader = 959
steal_leader = 960
steal_leader = 961
steal_leader = 962
steal_leader = 963
steal_leader = 964
steal_leader = 965
steal_leader = 966
steal_leader = 968
steal_leader = 969
steal_leader = 970
steal_leader = 971
steal_leader = 972
steal_leader = 973
steal_leader = 974
steal_leader = 975
steal_leader = 977


	headofstate = { type = 9 id = 1 }
	headofgovernment = { type = 9 id = 42 }
	foreignminister = { type = 9 id = 55 }
	armamentminister = { type = 9 id = 80 }
	ministerofsecurity = { type = 9 id = 108 }
	ministerofintelligence = { type = 9 id = 6 }
	chiefofstaff = { type = 9 id = 156 }
	chiefofarmy = { type = 9 id = 177 }
	chiefofnavy = { type = 9 id = 192 }
	chiefofair = { type = 9 id = 10 }


	diplomacy = {
		relation = { tag = ROM access = yes }
	}


	capital = 562

	extra_tc = 200

	free = 		{
		oil 	=	70
		supplies =	100
		ic = 70
	}

	manpower = 850


	# Enough resources to keep TP running


	oil = 1000
	supplies = 5000



    ownedprovinces =
	{

# Western Ukraine only
562 502 229 226 227 238 228

}
    controlledprovinces =
	{

# Occupation - higher partisan activity

562
502
229
226
227
238
228
231
232
233
240
237
236
234
251
235
250
252
254
246
245
239
241
273
272
225
276
277
243
247
244
242
248
249

}
    nationalprovinces =
	{

# Western Ukraine - for game purposes only
562 502 229 226 227 238 228

}

	  techapps               = { 1010  1020  1030  1040  1070  1080  1090  1110  1120  1130  1190  1200  1210  1220  1230  1240  1310  1340  14000 14010
			     14020 2010  2020  2030  2040  2050  2070  2080  2150  2170  2220  2230  2290  2300  2310  2320  2330  2340  2370  2400
			     2410  2450  2460  2470  2510  2520  2530  3010  3020  3030  3040  3070  3080  3090  3100  3130  3140  3150  3160  3190
			     3200  3210  3220  3250  3260  3270  3280  3320  3330  3340  3400  3410  3420  3430  4010  4020  4030  4040  4050  4060
			     4070  4120  4130  4140  4150  4170  4190  4200  4220  4250  5010  5020  5030  5050  5060  5070  5080  5090  5100  5110
			     5120  5130  5140  5160  5180  5190  5200  5210  5220  5310  5320  5330  5350  5360  5370  5410  5420  5470  5480  5490
			     5500  5550  6210  6220  6230  6240  6250  6260  6270  6290  8010  8020  8030  8040  8050  8080  8090  8150  8160  8170
			     8210  8280  8290  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130  9140  9190  9200  9210
			     9220  9270  9290  9350
			   }


# HEER
#
# Fall Blau eve, july 1942
##############################


#
# 2nd Army, northern pincer
##############################

	landunit = {

	location = 277 #Bordering AG Center
	#leader =
	id = { type = 10500 id = 1 }
	name = "2. Armee Reserve"
	dig_in = 20

		division = {
			id = { type = 10500 id = 2 }
			name = "88. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
			extra = artillery
			brigade_model = 4 # Medium modern art.
	}

		division = {
			id = { type = 10500 id = 3 }
			name = "383. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

		division = {
			id = { type = 10500 id = 4 }
			name = "323. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

		division = {
			id = { type = 10500 id = 5 }
			name = "340. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

	}

	landunit = {

	location = 277 #Bordering AG Center
	#leader =
	id = { type = 10500 id = 6 }
	name = "LV. Korps"
	dig_in = 20
		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 7 }
			name = "1. SS Brigade (mot)"
			strength = 40
			max_strength = 40
			type = motorized
			model = 1
	}

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 8 }
			name = "45. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 9 }
			name = "95. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 10 }
			name = "299. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

	}

	landunit = {

	location = 277 #Bordering AG Center
	#leader =
	id = { type = 10500 id = 11 }
	name = "VII. Korps"
	dig_in = 20

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 12 }
			name = "16. Infanterie-Division (mot)"
			strength = 100
			type = motorized
			model = 1
	}

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 13 }
			name = "387. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

	}

# 4th Tank Army
##################

	landunit = {

	location = 243 #Bordering AG Center
	#leader =
	id = { type = 10500 id = 14 }
	name = "XIII. Korps"
	dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 15 }
		name = "11. Panzer-Division"
		strength = 100
		type = armor
		model = 3 #IIIL/IVF2
		extra = engineer
		experience = 20
		}


		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 16 }
			name = "385. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 17 }
			name = "82. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
	}


	}

	landunit = {

	location = 243 #Bordering AG Center
	#leader =
	id = { type = 10500 id = 18 }
	name = "XXIV. Panzer Korps"
	dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 19 }
		name = "9. Panzer-Division"
		strength = 100
		type = armor
		model = 3 #IIIL/IVF2
		experience = 20
		}


		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 20 }
			name = "3. Infanterie-Division (mot)"
			strength = 100
			type = motorized
			model = 1
			extra = engineer
			experience = 20
		}



	}

	landunit = {

	location = 243 #Bordering AG Center
	#leader =
	id = { type = 10500 id = 21 }
	name = "XXXXVIII. Panzer Korps"
	dig_in = 20

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 22 }
			name = "24. Panzer-Division"
			strength = 100
			type = armor
			model = 3 #IIIL/IVF2
			experience = 20
		}


		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 23 }
			name = "'GrossDeutschland' Division"
			strength = 100
			type = motorized
			model = 1
			extra = tank_destroyer
			experience = 20
		}

		division = {
			offensive = { year = 1942 month = august day = 20  }
			id = { type = 10500 id = 24 }
			name = "377. Infanterie-Division"
			strength = 100
			type = infantry
			model = 3
			extra = engineer
		}

	}

# 11. Armee - Sevastopol Siege
#################################



	landunit = {

		location = 252
		id = { type = 10500 id = 25 }
		name = "LIV. Korps"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 26 }
		name = "50. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 3 # Light modern art.
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 27 }
		name = "22. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = SP_artillery
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 28 }
		name = "24. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Light modern art.
		}


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 29 }
		name = "46. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 30 }
		name = "Div. 4 Infanterie Alpinisti (rom)"
		type = bergsjaeger
		strength = 100
		model = 0
		}

		}

	landunit = {
		location = 254
		id = { type = 10500 id = 31 }
		name = "XXX. Korps"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 32 }
		name = "28. lei. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}



		division = { offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 33 }
		name = "72. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = anti_air
		brigade_model = 1
		}

		division = { offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 34 }
		name = "170. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = anti_tank
		}

	}


	landunit = {
		location = 254
		id = { type = 10500 id = 35 }
		name = "XXXXII. Korps"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 36 }
		name = "132. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = SP_artillery
		brigade_model = 1 # Stug III
		}

		}



	landunit = {
		location = 254
		name = "Corp 7 Armata (rom)"
		id = { type = 10500 id = 37 }
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 38 }
		name = "Divizie 8 Cavalerie"
		type = cavalry
		model = 1
		strength = 100
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 39 }
		name = "Divizia 19 Infanterie"
		type = infantry
		strength = 100
		model = 1
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 40 }
		name = "Divizia 10 Infanterie"
		type = infantry
		strength = 100
		model = 1
		}
		}



#17. Armee
#######################


	landunit = {
		location = 238
		id = { type = 10500 id = 41 }
		name = "BefhHG 'Sud'"

		division = {
		id = { type = 10500 id = 42 }
		name = "213. Sicherungs-Division"
		strength = 100
		type = infantry
		model = 1
		extra = police
		}

		division = {
		id = { type = 10500 id = 43 }
		name = "444. Sicherungs-Division"
		strength = 100
		type = infantry
		model = 1
		extra = police
		}

		division = {
		id = { type = 10500 id = 44 }
		name = "105. gyalog hadosztály (hun)"
		strength = 100
		type = infantry
		model = 1
		extra = police
		}
	}

	landunit = {
		location = 249
		id = { type = 10500 id = 45 }
		name = "LII. Korps"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 46 }
		name = "111. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}
	}


	landunit = {
		location = 249
		id = { type = 10500 id = 47 }
		name = "XXXXIX. Geb. Korps"
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 48 }
		name = "198. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = engineer
		}

		division = { offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 49 }
		name = "4. Gebirgs-Division"
		strength = 100
		type = bergsjaeger
		model = 1
		experience = 20
		extra = anti_tank
		}
	}

	landunit = {
		location = 249
		id = { type = 10500 id = 50 }
		name = "IV. Korps"
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 51 }
		name = "76. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}

		division = { offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 52 }
		name = "295. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = engineer
		}

		division = { offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 53 }
		name = "370. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}

		division = { offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 54 }
		name = "94. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = anti_tank
		}

		division = { offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 55 }
		name = "9. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}
	}



# 6. Armee
#########################


	landunit = {
		location = 247
		id = { type = 10500 id = 56 }
		name = "VIII. Korps"
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 57 }
		name = "305. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 58 }
		name = "376. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 59 }
		name = "389. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = engineer
		}

	}


	landunit = {
		location = 247
		id = { type = 10500 id = 60 }
		name = "XVII. Korps"
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 61 }
		name = "79. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 62 }
		name = "113. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 63 }
		name = "294. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = SP_artillery
		brigade_model = 1 # Stug III
		}

	}

	landunit = {
		location = 247
		id = { type = 10500 id = 64 }
		name = "XXIX. Korps"
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 65 }
		name = "57. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 66 }
		name = "75. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 67 }
		name = "168. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

	}

	landunit = {
		location = 247
		id = { type = 10500 id = 68 }
		name = "XXXX. Korps (mot)"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 69 }
		name = "100. lei. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 70 }
		name = "336. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 71 }
		name = "29. Infanterie-Division (mot)"
		strength = 100
		type = motorized
		model = 1
		extra = SP_artillery
		brigade_model = 1 # Stug III
		}


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 72 }
		name = "3. Panzer-Division"
		strength = 100
		type = armor
		model = 2 #IIIh
		experience = 20
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 73 }
		name = "23. Panzer-Division"
		strength = 100
		type = armor
		model = 3 #IIIe/IIIg
		experience = 20
		}

	}

#
# 1st Tank Army
#####################################

	landunit = {
		location = 248
		id = { type = 10500 id = 74 }
		name = "III. Korps (mot)"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 76 }
		name = "14. Panzer-Division"
		strength = 100
		type = armor
		model = 3 #IIIL/IVF2
		experience = 20
		extra = SP_artillery
		brigade_model = 1 # Stug III
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 77 }
		name = "60. Infanterie-Division (mot)"
		strength = 100
		type = motorized
		model = 1
		extra = tank_destroyer
		brigade_model = 1 # Stug III
		}


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 78 }
		name = "16. Panzer-Division"
		strength = 100
		type = armor
		model = 3
		experience = 20
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 79 }
		name = "22. Panzer-Division"
		strength = 100
		type = armor
		model = 3
		experience = 20
		}

	}


	landunit = {
		location = 248
		id = { type = 10500 id = 80 }
		name = "XXXXIX. Korps"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 81 }
		name = "101. lei. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 82 }
		name = "97. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		extra = artillery
		brigade_model = 4 # Medium modern art.
		}

	}


	landunit = {
		location = 248
		id = { type = 10500 id = 83 }
		name = "LI. Korps"
		dig_in = 20

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 84 }
		name = "71. lei. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 85 }
		name = "297. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}
	}

	landunit = {
		location = 248
		name = "XI. Korps"
	        id = { type = 10500 id = 86 }
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 87 }
		name = "Divizia 2 Infanterie (rom)"
		type = infantry
		model = 1
		strength = 100
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 88 }
		name = "295. Infanterie-Division"
		strength = 100
		type = infantry
		model = 3
		}
	}

	landunit = {
	location = 248
	name = "Corp 6 Armata"
	id = { type = 10500 id = 89 }
		dig_in = 20


		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 90 }
		name = "Divizia 4 Infanterie (rom)"
		type = infantry
		model = 1
		strength = 100
		}

		division = {
		offensive = { year = 1942 month = august day = 20  }
		id = { type = 10500 id = 91 }
		name = "Divizia 20 Infanterie (rom)"
		type = infantry
		model = 1
		strength = 100
		}
	}



#
# HQ
########################

	landunit = {
	location = 238
	leader = 279 # von Bock
	name = "Armee Gruppe'B' HQ"
	id = { type = 10500 id = 92 }


		division = {
		id = { type = 10500 id = 93 }
		name = "Armee Gruppe'B' HQ"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 250
	leader = 189 # List
	name = "Armee Gruppe'A' HQ"
	id = { type = 10500 id = 94 }


		division = {
		id = { type = 10500 id = 95 }
		name = "Armee Gruppe'A' HQ"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 248
	leader = 310 # von Kleist
	name = "1. Panzer Armee HQ"
	id = { type = 10500 id = 96 }


		division = {
		id = { type = 10500 id = 97 }
		name = "1. Panzer Armee HQ"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 247
	leader = 215 # Paulus
	name = "6. Armee HQ"
	id = { type = 10500 id = 99 }


		division = {
		id = { type = 10500 id = 100 }
		name = "6. Armee HQ"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 249
	leader = 231 # Ruoff
	name = "17. Armee HQ"
	id = { type = 10500 id = 101 }


		division = {
		id = { type = 10500 id = 102 }
		name = "17. Armee HQ"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 252
	leader = 324 # Manstein
	name = "11. Armee HQ"
	id = { type = 10500 id = 103 }


		division = {
		id = { type = 10500 id = 104 }
		name = "11. Armee HQ"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 243
	leader = 143 # Hoth
	name = "4. Panzer Armee HQ"
	id = { type = 10500 id = 105 }


		division = {
		id = { type = 10500 id = 106 }
		name = "4. Panzer Armee HQ"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 277
	leader = 351 # Weichs
	name = "2. Armee HQ"
	id = { type = 10500 id = 107 }


		division = {
		id = { type = 10500 id = 108 }
		name = "2. Armee HQ"
		type = hq
		extra = anti_air
		}

	}


#
# Allies - Italian 8th Army
###########################



	landunit = {
	location = 250
	leader = 6077 #Gariboldi - XXXV Corps
	name = "XXXV Corpo d'Armata (Ita)"
	id = { type = 10500 id = 109 }

		division = {
		id = { type = 10500 id = 110 }
		name = "9. Divisione 'Pasubio'"
		strength = 80
		max_strength = 80
		type = motorized
		model = 0
		experience = 10
		extra = artillery
		}

		division = {
		id = { type = 10500 id = 111 }
		name = "52. Divisione 'Torino'"
		strength = 80
		max_strength = 80
		type = motorized
		experience = 10
		model = 0
		}

		division = {
		id = { type = 10500 id = 112 }
		name = "3. Divisione 'Celere'"
		strength = 80
		max_strength = 80
		type = cavalry
		experience = 10
		model = 3
		}

		division = {
		id = { type = 10500 id = 113 }
		name = "3a Divisione 'Principe Amedeo'"
		strength = 80
		max_strength = 80
		type = cavalry
		experience = 10
		model = 3
		}
	}


	landunit = {
	location = 235
	leader = 6150 #Zingales - II Corps
	name = "II Corpo d'Armata (Ita)"
	id = { type = 10500 id = 114 }

		division = {
		id = { type = 10500 id = 115 }
		name = "2. Divisione 'Sforzesca'"
		strength = 80
		max_strength = 80
		type = infantry
		model = 2
		extra = artillery
		}

		division = {
		id = { type = 10500 id = 116 }
		name = "3. Divisione 'Ravenna'"
		strength = 80
		max_strength = 80
		type = infantry
		experience = 10
		model = 2
		}

		division = {
		id = { type = 10500 id = 117 }
		name = "5. Divisione 'Cosseria'"
		strength = 80
		max_strength = 80
		type = infantry
		model = 2
		}

	}


	landunit = {
	location = 235
	leader = 6108 #Nasi - Alpini
	name = "Corpo d'Armata Alpino"
	id = { type = 10500 id = 118 }

		division = {
		id = { type = 10500 id = 119 }
		name = "3a Divisione Alpina 'Julia'"
		strength = 80
		max_strength = 80
		type = bergsjaeger
		model = 1
		}

		division = {
		id = { type = 10500 id = 120 }
		name = "4a Divisione Alpina 'Cuneense'"
		strength = 80
		max_strength = 80
		type = bergsjaeger
		model = 1
		}

		division = {
		id = { type = 10500 id = 121 }
		name = "2a Divisione Alpina 'Tridentina'"
		strength = 80
		max_strength = 80
		type = bergsjaeger
		model = 1
		}
	}

	landunit = {
	location = 235
	leader = 6102 # Messe
	name = "8a Armata (Ita)"
	id = { type = 10500 id = 122 }


		division = {
		id = { type = 10500 id = 123 }
		name = "8a Armata HQ (Ita)"
		type = hq
		extra = anti_air
		}

	}

	landunit = {
	location = 235
	name = "8a Armata Security Group (Ita)"
	id = { type = 10500 id = 124 }


		division = {
		id = { type = 10500 id = 125 }
		name = "165. Divisione 'Vincenza'"
		strength = 70
		max_strength = 70
		type = infantry
		model = 2
		extra = police
		}
	}

#
# Hungarian 2nd Army
#######################


	landunit = {
	location = 242
	leader = 31142 # Jany
	name = "II Allandó Hadsereg"
	id = { type = 10500 id = 126 }


		division = {
		id = { type = 10500 id = 127 }
		name = "2. hadsereg"
		type = hq
		extra = anti_air
		}

	}


	landunit = {
	id = { type = 10500 id = 128 }
	name = "III Állandó Hadsereg (Hun)"
	location = 242

		division = {
		id = { type = 10500 id = 129 }
		name = "6. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}

		division = {
		id = { type = 10500 id = 130 }
		name = "7. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}

		division = {
		id = { type = 10500 id = 131 }
		name = "8. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}
		}

	landunit = {
	id = { type = 10500 id = 132 }
	name = "IV Állandó Hadsereg (Hun)"
	location = 242

		division = {
		id = { type = 10500 id = 133 }
		name = "10. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}

		division = {
		id = { type = 10500 id = 134 }
		name = "12. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}

		division = {
		id = { type = 10500 id = 135 }
		name = "13. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}
		}

	landunit = {
	id = { type = 10500 id = 136 }
	name = "VIII Állandó Hadsereg (Hun)"
	location = 242

		division = {
		id = { type = 10500 id = 137 }
		name = "19. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}

		division = {
		id = { type = 10500 id = 138 }
		name = "20. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}

		division = {
		id = { type = 10500 id = 139 }
		name = "23. gyalog hadosztály"
		strength = 100
		type = infantry
		model = 2
		}
		}


#
# German Reinforcements
#####################################


landdivision = {

		dormant = yes

	        id = { type = 10500 id = 140 }
			name = "Infanterie-Division 'Brandenburg' (mot)"
			type = motorized
			model = 1
			experience = 30
			extra = engineer
		}


landdivision = {

		dormant = yes

	        id = { type = 10500 id = 141 }
			name = "18. Infanterie-Division (mot)"
			type = motorized
			model = 1
			experience = 20
		}

landdivision = {

		dormant = yes

	        id = { type = 10500 id = 142 }
			name = "6. Panzer-Division"
			strength = 100
			type = armor
			model = 4 #IIIj/IVG
			experience = 20
		}



#
# Kriegsmarine - Black Sea Area
#####################################


	navalunit = {
		name = "Black Sea Echelon"
		id = { type = 10500 id = 600 }
		leader = 416 #Schuster
		location = 233 #Odessa
		base = 233 #Odessa

	division = {  id = { type = 10500 id = 601 } name = "Black Sea Kriegsmarine Echelon" type = submarine	model = 1 }
		}



transports = 40
escorts = 10




###########################################
#
# Luftwaffe orbat 1942
#
###########################################


# LUFTWAFFE
# Luftflotte 4
#################

		airunit = {
		id = { type = 10500 id = 400 }
		name = "I. Fliegerkorps"
		leader = 914 #Förster
		location = 248
		base = 248

			division = {
			id = { type = 10500 id = 401 }
			name = "Kampfgeschwader 76"
			strength = 100
			type = tactical_bomber
			model = 3 #Ju88
			experience = 20
			}

			division = {
			id = { type = 10500 id = 402 }
			name = "JG 54 'Grunherz'"
			strength = 100
			type = multi_role
			model = 0 #bf109f
			experience = 20
			}

			division = {
			id = { type = 10500 id = 403 }
			name = "KG 30 'Adler'"
			strength = 100
			type = tactical_bomber
			model = 3 #Ju88
			experience = 20
			}

			division = {
			id = { type = 10500 id = 404 }
			name = "KG 54 'Totenkopf'"
			strength = 100
			type = tactical_bomber
			model = 3 # Ju88
			experience = 20
			}

			}

		airunit = {
		id = { type = 10500 id = 405 }
		name = "IV. Fliegerkorps"
		leader = 462 #Pflugbeil
		location = 250
		base = 250

			division = {
			id = { type = 10500 id = 406 }
			name = "JG 6 'Horst Wessel'" #"LG 2"
			strength = 80
			type = multi_role
			model = 0 #109F
			experience = 20
			}

			division = {
			id = { type = 10500 id = 407 }
			name = "KG 51 'Edelweiß'"
			strength = 100
			type = tactical_bomber
			model = 3 #Ju88
			experience = 20
			}

			division = {
			id = { type = 10500 id = 408 }
			name = "JG 2 'Richthofen'"
			strength = 100
			type = multi_role
			model = 0 #109F
			experience = 20
			}


			division = {
			id = { type = 10500 id = 409 }
			name = "Sturzkampfgeschwader 5"
			strength = 100
			type = cas
		       	model = 1 #Ju87
			experience = 20
			}

		}


		airunit = {
		id = { type = 10500 id = 410 }
		name = "VIII. Fliegerkorps"
		leader = 479 #von Richthofen
		location = 277
		base = 277

			division = {
			id = { type = 10500 id = 411 }
			name = "KG 27 'Boelcke'"
			strength = 100
			type = tactical_bomber
			model = 2 #He111
			experience = 20
			}

			division = {
			id = { type = 10500 id = 412 }
			name = "JG 3 'Udet'"
			strength = 100
			type = multi_role
			model = 0 #Bf109f
			experience = 20
			}

			division = {
			id = { type = 10500 id = 413 }
			name = "KG 55 'Greif'"
			strength = 100
			type = tactical_bomber
			model = 2 #He111
			experience = 20
			}

			division = {
			id = { type = 10500 id = 414 }
			name = "JG 77 'Herz As'"
			strength = 100
			type = multi_role
			model = 0 #109F
			experience = 20
			}

		}

# Allies AF
##########################

		airunit = {
		id = { type = 10500 id = 415 }
		name = "Italian Exp. Cops"
		location = 238
		base = 238

			division = {
			id = { type = 10500 id = 416 }
			name = "1 Stormo"
			strength = 100
			type = interceptor
			model = 2 #various
			}

			division = {
			id = { type = 10500 id = 417 }
			name = "14 Stormo"
			strength = 100
			type = tactical_bomber
			model = 1 #various
			}

			division = {
			id = { type = 10500 id = 418 }
			name = "39 Stormo"
			strength = 100
			type = cas
			model = 0 #various
			}

			}

		airunit = {
		id = { type = 10500 id = 419 }
		name = "Romanian Fliegerkorps"
		leader = 4412 # Davidescu
		location = 233
		base = 233

			division = {
			id = { type = 10500 id = 420 }
			name = "9 FARR"
			strength = 100
			type = interceptor
			model = 1 #various
			}

			division = {
			id = { type = 10500 id = 421 }
			name = "6 FARR"
			strength = 100
			type = tactical_bomber
			model = 1 #various
			}

			division = {
			id = { type = 10500 id = 423 }
			name = "JG 52"
			strength = 100
			type = multi_role
		  	model = 0 #bf109f
			}

		}



############################################

}


